### ISSUE TITLE
Add support for AWS X-Ray service

### ISSUE THREAD

**Issue by hwine** [spulec/moto#1006]
The [AWS X-Ray](https://aws.amazon.com/xray/) can be very helpful for debugging on AWS. This is especially true of [Lambda functions](http://docs.aws.amazon.com/xray/latest/devguide/xray-services-lambda.html)

I was hoping to use moto with a lambda function written in Python 2.7. The [fleece project](https://github.com/racker/fleece) provide Python support for X-Ray, but the two projects do not work well together at the moment.

**Comment by terrycain** [comment]
Have started on X-Ray support. Do you have anything that generates decent X-Ray data as I could do with some "real world" data to mock it out right

**Comment by hwine** [comment]
I don't -- for my use case, I'd just be happy if the calls were intercepted by moto so boto doesn't try to connect to AWS during testing :)

**Comment by terrycain** [comment]
Ahh no problem, should be done soon then :smile:

**Comment by terrycain** [comment]
Ahh just thinking about this. Does your app directly make calls to the Xray service using boto3? As the AWS xray client by default just throws UDP packets to a local daemon which then sends batches to the AWS service. If the latter then you'll need to point the aws xray daemon to a moto server.

**Comment by hwine** [comment]
No, I'm using [racker/fleece](https://github.com/racker/fleece) (see [docs](https://github.com/racker/fleece#x-ray-integration) and some [additional notes about X-Ray](https://github.com/racker/fleece/pull/45#issuecomment-317906853)).

> then you'll need to point the aws xray daemon to a moto server.

n00b question - does that mean I would need to change to using ``moto`` in standalone mode?

**Comment by terrycain** [comment]
Yeah it sounds like fleece will monkeypatch the aws-xray sdk into the botocore library (which will then be able to trace anything your app then does). But the way xray works is a daemon runs on a port, it gets loads of udp segments from your lambda then the daemon uploads bulk segments into xray.

Moto doesnt mock the dameon that xray would post to, only what the daemon would then bulk upload to.
So I guess you would need to set `AWS_XRAY_DAEMON_ADDRESS` which would point the lambda to a custom xray daemon, which would then need to be pointed to a moto server.

https://github.com/racker/fleece/blob/master/fleece/xray.py#L97-L108

https://github.com/spulec/moto#stand-alone-server-mode

**Comment by terrycain** [comment]
@JackDanger this can be closed after merge of #1255

**Comment by JackDanger** [comment]
Closing as fixed. Thanks @terrycain
