### ISSUE TITLE
Add support for S3 object tagging

### ISSUE THREAD

**Issue by eric-weaver** [spulec/moto#1008]
It would be nice if moto added support for S3 object tagging. Object tagging needs 3 actions, added directly onto the boto3 `upload_object` function, `get_object_tagging` to retrieve object tagsets, and `put_object_tagging` for adding tags to existing objects in S3.

I would be happy to take a stab at this. Is there a good starting point / modeling used for adding new functionality to services?

**Comment by JackDanger** [comment]
Great idea, @eric-weaver! A good example of adding a feature to S3 responses is #960 but an example of a feature that includes both responses and some coordination of model data is #986 

If you start with the tests (the ones in #960 are a great example) then you don't have to understand all the details and you can create something in s3/responses.py that works and store backend state in s3/models.py. If you get stuck just push what you have and ask for assistance - four eyes are better than two!

**Comment by mklosi** [comment]
This has been implemented, merged and deployed already? 

i keep getting this: `TypeError: string indices must be integers`

**Comment by eric-weaver** [comment]
@mklosi This has been merged in and released with I believe the 1.1.0 release. It was working at the time but a lot has changed in moto since then. I recommend creating a new issue and including a stacktrace of the error and a snippet so others can help.

**Comment by mklosi** [comment]
hi @eric-weaver. thanks for responding. 

I've created the ticket with code and traceback. let me know if there is anything else i can help with. 
https://github.com/spulec/moto/issues/1318
