### ISSUE TITLE
Support the ability to start/stop moto server mode through code

### ISSUE THREAD

**Issue by eric-weaver** [spulec/moto#1015]
Feature Request:
Make the server module into a package that can be importable and controlled directly.

Use Case:
Spinning up 2 different `mock_s3` instances. One with the default aws address and one with a custom DNS `endpoint_url` passed into boto3. 

I have only been able to run 2 separate mocks of the same service via the standalone server with different ports. It would be helpful if moto had a way to programmatically start/stop the standalone server mode natively with python. Currently the only way I have nicely been able to accomplish this is by starting the server in a subprocess. 

```python
def _moto_server_process(service, host, port):
    cmd = ['moto_server', service, '-p', str(port), '-H', host]
    return subprocess.Popen(cmd, stdout=subprocess.PIPE,
                            stderr=subprocess.STDOUT)
```

**Comment by JackDanger** [comment]
@eric-weaver Would it be enough to wrap this `_moto_server_process` subprocess helper somehow so that it is easier to call or is it important that the Moto server instances have the same memory space?

**Comment by thehesiod** [comment]
btw I created this: https://gist.github.com/thehesiod/2e4094a1db1190f7e122e7043f1973a0

**Comment by automaticgiant** [comment]
@thehesiod that's great. i'm creating test coverage for terraform configs with pytest and `python-terraform` and this sounds really helpful for writing a pytest fixture.
and to @eric-weaver 's credit, mine is another supporting use case for such functionality.

**Comment by thehesiod** [comment]
@automaticgiant just updated it to my latest version

**Comment by ricfeatherstone** [comment]
Any chance of implementing this or providing a simple example of how to use the MotoService above?
I'm trying to use `behave` to test `terraform` code and would like to be able to start the moto server in code

**Comment by spulec** [comment]
@ricfeatherstone have you tried using the code in `_moto_server_process()` above?

**Comment by bblommers** [comment]
Moto 3.0.6 now includes a way to start the MotoServer programmatically.
See the documentation here: http://docs.getmoto.org/en/latest/docs/server_mode.html#start-within-python

It is still in beta while we collect feedback, so if you find any bugs or improvements, feel free to open a new issue!

**Comment by karkir0003** [comment]
I tried this function and it wasn't working @bblommers. Is there a way to mock lambda with `moto` without having to spin up docker containers or an alternative framework to accomplish this task without spinning up local docker daemons and that the solution will work on github actions
