### ISSUE TITLE
Add Heath Check Endpoint 

### ISSUE THREAD

**Issue by rhkiswani** [spulec/moto#1020]
Hi All,

I'm using MOTO as mock for AWS for my application and I'm running two instances on remote machine in order to make it available for my dev/qa/CI environments.

The problem we're faceing right now that sometimes the server crushing due to number of threads (Python 2.7 ) known issue or sometimes due to the machine resources.

So we want to automate restarting the MOTO server if anything goes wrong.

Suggestion :
Maybe you can add health check endpoint that can be checked every interval ex http://MOTO_SERVER_HOST:PORT/helath-check

**Comment by JackDanger** [comment]
@rhkiswani We do already have something that will work like a healthcheck at "http://MOTO_SERVER_HOST:PORT/moto-api/data.json" - would that work for you?

**Comment by spulec** [comment]
I'm going to close this out; feel free to reopen with more info.
