### ISSUE TITLE
moto vs moto-ext

### ISSUE THREAD

**Issue by joekiller** [spulec/moto#1040]
I noticed that https://pypi.python.org/pypi/moto-ext, used by localstack, points to moto root but I can't find much info on moto-ext's relationship with moto. What is the relationship of moto vs moto-ext and how might they be maintained differently?

Thanks Steve! (and everyone else)

**Comment by JackDanger** [comment]
It looks like @whummer created moto-ext. I would guess @whummer made it to avoid having to wait for a moto release.

I suspect we should move Moto to a faster release cadence but that's something that's up to Steve

**Comment by JackDanger** [comment]
@spulec what do you think about moving to a faster release cadence? I'd be happy to manage releases and do a tiny patch release for all minor feature additions then leave all minor and major version upgrades to you.
A lot of folks contribute code and immediately need to use the features they've added. Being able to publish a release for them right away would be really helpful to the community, I think.

**Comment by georgepsarakis** [comment]
@JackDanger some extra information on releases (at least I recently discovered it :smile: ), you could actually automate the release process in [Travis CI](https://docs.travis-ci.com/user/deployment/pypi/#Deploying-tags). When you push a tag (which you can as a collaborator), the PyPI package will be automatically released as well.

**Comment by spulec** [comment]
Completely agree that this needs to get fixed (especially with me having less time to work on the project lately).

This came up in the past with https://github.com/spulec/moto/issues/640

I like that solution so that people can use their changes right away.

Even with that though, I think we will need to come up with a strategy for more frequent 'real' releases. @JackDanger happy to add you on PyPI. Let me know your username.

**Comment by JackDanger** [comment]
@spulec I'm "jackdanger" on PyPi. My day to day is building https://opsolutely.com with heavy support from Moto so I plan to be in the thick of things for the indefinite future and I'm happy to handle all the small, low-latency issues like this. 👍

**Comment by dlutsch** [comment]
Any update on when we might be seeing the next release?

**Comment by JackDanger** [comment]
@spulec If you add 'jackdanger' on PyPi I'll release a new version for us

**Comment by spulec** [comment]
done!

**Comment by JackDanger** [comment]
@dlutsch @georgepsarakis @joekiller @spulec I've just released a new minor version that captures the last two months of community contributions: [1.1.0](https://github.com/spulec/moto/tree/1.1.0)

When new endpoints are added or bugs are fixed I'll bump the patch version and release incrementally.

I'll be offline next week but back after September 6th. Thanks for making all of this possible, @spulec !
