### ISSUE TITLE
Next Pypi release?

### ISSUE THREAD

**Issue by gregsterin** [spulec/moto#1050]
There have been some useful new support / fixes pushed in since last pypi release. will there be a new version soon?

**Comment by kawasakitoshiya** [comment]
I want `mock_elbv2` released.

**Comment by rocky4570** [comment]
+1 on this - the last release on pypi is 2017-06-04.

**Comment by justinsr20** [comment]
+1 on this, would like to use the new rds start stop without having to patch requirements file

**Comment by toshitanian** [comment]
discussion seems to be under here : https://github.com/spulec/moto/issues/1040

**Comment by gregsterin** [comment]
yay new releases https://pypi.python.org/pypi/moto/. Closing.
