### ISSUE TITLE
storage change to hardisk from memory

### ISSUE THREAD

**Issue by mrigankt** [spulec/moto#1069]
we need to change the storage of everything to hardisk in place of ram so that the data is not lost after the reboot. How to do that which file to tweak for the same.

**Comment by JackDanger** [comment]
To do this correctly we would have to change almost all of the Moto source code. But you might be able to get what you want by pickling (`pickle.dumps`) `moto.backends.BACKENDS` to a string and storing that in a file. Then, when you need to restore the previous state you can `pickle.loads` the contents of the file and restore the `moto.backends.BACKENDS` data.

**Comment by spulec** [comment]
Going to close this right now. If someone wants to propose ideas, I am open.
