### ISSUE TITLE
dynamodb2.update_item & delete_item ignore ConditionExpression for items that don't exists

### ISSUE THREAD

**Issue by abadyan-vonage** [spulec/moto#1071]
Using a table with 1 hash key named id, trying to make the following update_item which should only happen when the item exists:

`table.update_item(Key={"id": msg_id},
                                                 UpdateExpression= "set #text = :updated_text, #lastModified = :lastModified, #status= :status",
                                                 ConditionExpression="id = :msg_id",
                                                 ExpressionAttributeNames={
                                                     "#text": "text",
                                                     "#lastModified": "lastModified",
                                                     "#status": "status"
                                                 },
                                                 ExpressionAttributeValues={
                                                     ":msg_id": msg_id,
                                                     ":updated_text": updated_text,
                                                     ":lastModified":dt,
                                                     ":status": status
                                                 })`

This works with the real dynamodb server (fails when item doesn't exist) but with moto the update always happens. It doesn't even matter what I put in ConditionExpression, the update always go through.

I'm using moto 1.0.1 (using pip), working with the @mock_dynamodb2 decorator using boto3 1.4.6, boto 2.48.0, botocore 1.6.3.

**Comment by bblommers** [comment]
ConditionExpressions has been implemented by https://github.com/spulec/moto/pull/2266 - looks like this works now.
Feel free to reopen a new issue if the problem still persists
