### ISSUE TITLE
Support `raw message delivery` of messaging from sns to sqs

### ISSUE THREAD

**Issue by toshitanian** [spulec/moto#1079]
# boto3
http://boto3.readthedocs.io/en/latest/reference/services/sns.html#SNS.Client.set_subscription_attributes

# API doc
### get_subscription_attributes
http://docs.aws.amazon.com/sns/latest/api/API_GetSubscriptionAttributes.html

### set_subscription_attributes
http://docs.aws.amazon.com/sns/latest/api/API_SetSubscriptionAttributes.html

# how to set the value
 `raw message delivery`
http://docs.aws.amazon.com/sns/latest/dg/large-payload-raw-message.html

```
To enable raw message delivery using one of the AWS SDKs, you must use the SetSubscriptionAttribute action and configure the RawMessageDelivery attribute with a value of true. The default value is false.
```

**Comment by terrycain** [comment]
Try the latest version, should be fixed

**Comment by spulec** [comment]
I'm going to close this out; feel free to reopen if not fixed in the latest version.
