### ISSUE TITLE
change endpoint url

### ISSUE THREAD

**Issue by mrigankt** [spulec/moto#1080]
we are using some third party  application for dynamodb and s3 due to localstack limitation of saving data in memory. we need to change the end point url in localstack to 3rd party url so that lcalstack can fetch data from third party in place of local stack in built services.  we also want to set those 3rd party application as lambda trigger in loclastack. please let us know how to do it and which file to make the changes.

**Comment by spulec** [comment]
Moto doesn't currently support third-party applications for dynamodb. It sounds like you want to open an issue with localstack. Feel free to reopen if I am misinterpreting your question.
