### ISSUE TITLE
1.1.1 update breaks @mock_cloudformation_deprecated

### ISSUE THREAD

**Issue by ruivapps** [spulec/moto#1094]
we are still using @mock_cloudformation_deprecated for cloud formation (boto2)
everything works on 1.0.1, but once update to 1.1.1
we receive error on create stack on cloud formation 

this is our deploy code:

        c = CloudFormation(self.parameters['aws_access_key_id'],
                           self.parameters['aws_secret_access_key'],
                           self.parameters['region'])
        c.deploy(stack_name=self.parameters['stack_name'],
                 template_url=self.parameters['template_url'],
                 parameters=cloudformation_parameters)

below is the error trackback

tests/test_src/test_aws_cloudformation_provision.py:47: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
src/aws_cloudformation_provision.py:155: in run
    self._deploy_stack_()
src/aws_cloudformation_provision.py:117: in _deploy_stack_
    parameters=cloudformation_parameters)
src/aws_cloudformation_provision.py:186: in deploy
    stack_policy_body, stack_policy_url)
../../../python/p2/lib/python2.7/site-packages/boto/cloudformation/connection.py:403: in create_stack
    body = self._do_request('CreateStack', params, '/', 'POST')
../../../python/p2/lib/python2.7/site-packages/boto/cloudformation/connection.py:296: in _do_request
    response = self.make_request(call, params, path, method)
../../../python/p2/lib/python2.7/site-packages/boto/connection.py:1116: in make_request
    return self._mexe(http_request)
../../../python/p2/lib/python2.7/site-packages/boto/connection.py:944: in _mexe
    response = connection.getresponse()
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py:1118: in getresponse
    response = self.response_class(*args, **kwds)
../../../python/p2/lib/python2.7/site-packages/boto/connection.py:390: in __init__
    http_client.HTTPResponse.__init__(self, *args, **kwargs)
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py:375: in __init__
    self.fp = sock.makefile('rb', 0)
../../../python/p2/lib/python2.7/site-packages/moto/packages/httpretty/core.py:340: in makefile
    self._entry.fill_filekind(self.fd)
../../../python/p2/lib/python2.7/site-packages/moto/packages/httpretty/core.py:603: in fill_filekind
    self.request, self.info.full_url(), headers)
../../../python/p2/lib/python2.7/site-packages/moto/core/utils.py:106: in __call__
    result = self.callback(request, url, headers)
../../../python/p2/lib/python2.7/site-packages/moto/core/responses.py:111: in dispatch
    return cls()._dispatch(*args, **kwargs)
../../../python/p2/lib/python2.7/site-packages/moto/core/responses.py:179: in _dispatch
    return self.call_action()
../../../python/p2/lib/python2.7/site-packages/moto/core/responses.py:196: in call_action
    response = method()
../../../python/p2/lib/python2.7/site-packages/moto/cloudformation/responses.py:57: in create_stack
    role_arn=role_arn,
../../../python/p2/lib/python2.7/site-packages/moto/cloudformation/models.py:152: in create_stack
    cross_stack_resources=self.exports,
../../../python/p2/lib/python2.7/site-packages/moto/cloudformation/models.py:34: in __init__
    self.resource_map = self._create_resource_map()
../../../python/p2/lib/python2.7/site-packages/moto/cloudformation/models.py:42: in _create_resource_map
    resource_map.create()
../../../python/p2/lib/python2.7/site-packages/moto/cloudformation/parsing.py:425: in create
    if isinstance(self[resource], ec2_models.TaggedEC2Resource):
../../../python/p2/lib/python2.7/site-packages/moto/cloudformation/parsing.py:365: in __getitem__
    resource_logical_id, resource_json, self, self._region_name)
../../../python/p2/lib/python2.7/site-packages/moto/cloudformation/parsing.py:258: in parse_and_create_resource
    resource_tuple = parse_resource(logical_id, resource_json, resources_map)
../../../python/p2/lib/python2.7/site-packages/moto/cloudformation/parsing.py:233: in parse_resource
    resource_json = clean_json(resource_json, resources_map)
../../../python/p2/lib/python2.7/site-packages/moto/cloudformation/parsing.py:200: in clean_json
    cleaned_val = clean_json(value, resources_map)
../../../python/p2/lib/python2.7/site-packages/moto/cloudformation/parsing.py:200: in clean_json
    cleaned_val = clean_json(value, resources_map)
../../../python/p2/lib/python2.7/site-packages/moto/cloudformation/parsing.py:207: in clean_json
    return [clean_json(val, resources_map) for val in resource_json]
../../../python/p2/lib/python2.7/site-packages/moto/cloudformation/parsing.py:200: in clean_json
    cleaned_val = clean_json(value, resources_map)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

resource_json = {'Fn::Select': [0, {'Fn::GetAtt': ['Subnets']}]}, resources_map = <moto.cloudformation.parsing.ResourceMap object at 0x10d8dad10>

    def clean_json(resource_json, resources_map):
        """
        Cleanup the a resource dict. For now, this just means replacing any Ref node
        with the corresponding physical_resource_id.
    
        Eventually, this is where we would add things like function parsing (fn::)
        """
        if isinstance(resource_json, dict):
            if 'Ref' in resource_json:
                # Parse resource reference
                resource = resources_map[resource_json['Ref']]
                if hasattr(resource, 'physical_resource_id'):
                    return resource.physical_resource_id
                else:
                    return resource
    
            if "Fn::FindInMap" in resource_json:
                map_name = resource_json["Fn::FindInMap"][0]
                map_path = resource_json["Fn::FindInMap"][1:]
                result = resources_map[map_name]
                for path in map_path:
                    result = result[clean_json(path, resources_map)]
                return result
    
            if 'Fn::GetAtt' in resource_json:
                resource = resources_map.get(resource_json['Fn::GetAtt'][0])
                if resource is None:
                    return resource_json
                try:
                    return resource.get_cfn_attribute(resource_json['Fn::GetAtt'][1])
                except NotImplementedError as n:
                    logger.warning(str(n).format(
                        resource_json['Fn::GetAtt'][0]))
                except UnformattedGetAttTemplateException:
                    raise ValidationError(
                        'Bad Request',
                        UnformattedGetAttTemplateException.description.format(
                            resource_json['Fn::GetAtt'][0], resource_json['Fn::GetAtt'][1]))
    
            if 'Fn::If' in resource_json:
                condition_name, true_value, false_value = resource_json['Fn::If']
                if resources_map.lazy_condition_map[condition_name]:
                    return clean_json(true_value, resources_map)
                else:
                    return clean_json(false_value, resources_map)
    
            if 'Fn::Join' in resource_json:
                join_list = clean_json(resource_json['Fn::Join'][1], resources_map)
                return resource_json['Fn::Join'][0].join([str(x) for x in join_list])
    
            if 'Fn::Split' in resource_json:
                to_split = clean_json(resource_json['Fn::Split'][1], resources_map)
                return to_split.split(resource_json['Fn::Split'][0])
    
            if 'Fn::Select' in resource_json:
                select_index = int(resource_json['Fn::Select'][0])
                select_list = clean_json(resource_json['Fn::Select'][1], resources_map)
>               return select_list[select_index]
E               KeyError: 0

../../../python/p2/lib/python2.7/site-packages/moto/cloudformation/parsing.py:171: KeyError

**Comment by ruivapps** [comment]
just fond the broken part.

1.0.1 has no problem with
AvailabilityZone": {
      "Default": "us-east-1b", 
      **"Type": "AWS::EC2::AvailabilityZone::Name",** 
      "Description": "Availablity zone used for the bridge"
    }, 

but 1.1.1 seems have issue with it.
by change the Type to "String", everything works fine

**Comment by JackDanger** [comment]
@nadlerjessie Could you take a look at this? This is something that you're pretty good at and it's a bit over my head

**Comment by nadlerjessie** [comment]
Sorry for the delayed response on this. 

@ruivapps Can you please let me know what `clean_json({'Fn::GetAtt': ['Subnets']}, resource_map)` evaluates to? If I am reading your error correctly, it looks like it will be an empty list in `1.1.1`. I'd be curious to see what the results are for both versions `1.0.1` and `1.1.1`. Thanks!

**Comment by ruivapps** [comment]
when I am testing it again. with moto 1.1.11
I no longer see the problem
