### ISSUE TITLE
better response mocking

### ISSUE THREAD

**Issue by thehesiod** [spulec/moto#1100]
currently when you enable in-proc mocking it causes all request responses to fail if it doesn't match an implemented AWS endpoint because `pass_through` is `False`.  Instead it should allow all non AWS endpoints to pass through.  This is causing an issue in my PR (https://github.com/spulec/moto/pull/1048)  because I try to use the docker client and its requests end up responding with connection errors due to the mocking.  I had to do some ugly hacks to get it to work.

I can understand why this was done, to ensure unimplemented AWS endpoints cause connection errors...however I think there are better ways of handling this (like only doing this for *.amazonaws.com urls).

I'm opening this to discuss how to resolve this.  I can work on something that is agreed upon.

**Comment by elbeanio** [comment]
I've worked around this by just importing and using responses directly. Passthrough might be useful in some situations but most of the time I want all http calls mocked.

```
from moto.packages.responses import responses`

def test_thing():
    responses.add(responses.GET, "http://example.org/foo", body="<h2>Response!</h2>")

    test_http_call()
```

**Comment by spulec** [comment]
Closing in favor of #1026
