### ISSUE TITLE
elbv2 is not working in stand-alone server mode

### ISSUE THREAD

**Issue by chrisLeeTW** [spulec/moto#1106]
create elbv2 load-balancer need security group & vpc subnet, which is mock by ec2.

but stand-alone server mode only can mock one service at a time ?

any workaround or advice will be appreciated.

**Comment by JackDanger** [comment]
@chrisLeeTW Can you share the code that's not working? All of AWS should be able to be mocked all at the same time both in standalone server mode and in the in-memory mode

**Comment by chrisLeeTW** [comment]
@JackDanger I use moto in stand-alone server mode, 
and startup command is : `moto_server -H 0.0.0.0 -p 5002 elbv2`

And I using awscli to create elbv2 resource. first I try this command without luck.

`aws --endpoint-url=http://localhost:5002 elbv2 create-load-balancer --name test-alb`

error response is `aws: error: argument --subnets is required`

So I realize that I need to create vpc & security group & subnet first.

And then I try this command also without luck.

`aws --endpoint-url=http://localhost:5002 ec2 create-vpc --cidr-block 10.0.0.0/16`

response is

Unable to parse response (syntax error: line 1, column 54), invalid XML received:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>

I think the reason for this result is that I should mock ec2 & elbv2 at the same time when startup moto stand-alone server mode.

But I can not find out any way I can specific multiple mock services when startup.

**Comment by chrisLeeTW** [comment]
according the source ( https://github.com/spulec/moto/blob/master/moto/server.py#L163 )

Service argument only accept assign one time.

So I really do not know how to mock all the services at the same time in stand-alone server mode.

Any idea will help. thx.

**Comment by JackDanger** [comment]
If you run `moto_server` without specifying a service then it operates like all services together. This worked for me on the latest Moto:

```
$ moto_server -H 0.0.0.0 -p 5002 &

$ aws --endpoint-url=http://localhost:5002 ec2 create-vpc --cidr-block 10.0.0.0/16
# prints vpc_id
$ aws --endpoint-url=http://localhost:5002 ec2 create-subnet --vpc-id vpc-a7e90e82 --cidr-block 10.0.0.0/16
# prints subnet_id
$ aws --endpoint-url=http://localhost:5002 elbv2 create-load-balancer --name test-alb --subnets subnet-346e3199
```

**Comment by chrisLeeTW** [comment]
@JackDanger Really Thanks. It's works. sorry for the misunderstanding.
