### ISSUE TITLE
Add IAM User/key configuration

### ISSUE THREAD

**Issue by blacar** [spulec/moto#1131]
This tool is amazing, thanks for it.

Is there any way to configure users/keys so I can test authentication is denied using wrong key par?

**Comment by JackDanger** [comment]
@blacar Right now Moto doesn't do any checking of aws access keys and secrets at all. What would you imagine that API might look like? I can see how it would be handy.

**Comment by blacar** [comment]
Hi, @JackDanger In terms of API I imagine it will look like the authentication AWS S3 API. In terms of usage probably it will need some configuration either in memory or file where to store credentials and secret to check. I question because there are other products holding these features (e.g. minio, zenko, ...) I know moto use case is different but still covering the most of the S3 API sounds like good.
