### ISSUE TITLE
Add add_permission to lambda

### ISSUE THREAD

**Issue by oharaandrew314** [spulec/moto#1142]
Lambda is missing the `add_permission` method.  I'm more concerned about my test not hitting any errors when executing the call rather then permissions actually being respected.

What do you guys think about me implementing the method while ignoring handling permissions on `invoke`?

**Comment by JackDanger** [comment]
It's not rare for us to implement an endpoint to do just a little of the actual feature and then leave TODOs for ourselves to finish it later. As long as the endpoint is in the right direction toward a full implementation then it's okay to not go all the way with it.

**Comment by oharaandrew314** [comment]
Sounds good to me!

**Comment by dbfr3qs** [comment]
I would suggest also implementing the remove_permission function as well, the two functions could just keep track of the state of the permission, which might just be a dumb class or dictionary - as long as it includes the StatementId.

**Comment by oharaandrew314** [comment]
@dbfr3qs I did so in #1143, but I was having trouble with the URLs in server mode.

**Comment by dbfr3qs** [comment]
I have made a suggestion no that PR. Let me know if it helps. I am happy to help if I can.

**Comment by dbfr3qs** [comment]
I believe this now exists - I added this when I add [get_policy](https://github.com/spulec/moto/pull/1234). This can probably be closed.

**Comment by JackDanger** [comment]
Nice!
