### ISSUE TITLE
Future enhancement: Provide utility class for querystring handling

### ISSUE THREAD

**Issue by nuwang** [spulec/moto#1155]
This issue is a tracking issue for a proposed future enhancement. It's a continuation of a discussion in the PR here: https://github.com/spulec/moto/pull/1152

Currently, there's still a fair amount of duplication in querystring parameter handling logic.  (e.g. in ec2.util - filters_from_querystring, tags_from_query_string, dhcp_configuration_from_querystring, dict_from_querystring, tags_from_query_string).

However, since all AWS parameters have a fixed set of formats, a standard utility class for parsing them would facilitate reuse. I think the following primitives would be beneficial.

- get_param() - get a single parameter
- get_param_array() - to get an array of parameters
- get_param_dict() - to get a compound dict structure, including all nested values.

While all of the above exist in various forms (in BaseResponse in particular), they need to be documented and moved to a central, reusable location. (The inherited methods are less usable when outside of the BaseResponse class)

Perhaps the arguments could even be parsed and made available as a standardised data structure.

If the above can be done, many of the related methods in ec2.util could be removed, or composed out of the above primitives.

**Comment by terrycain** [comment]
Continuing from that, it would probably make sense to provide something like a TagContainer type class which deals with all the tag logic (including that tags dont need values) as I'm pretty sure the tag logic is the same throughout AWS

**Comment by toshitanian** [comment]
It would be good if we make a document for development.

**Comment by bblommers** [comment]
A bit of an update on this:

The `ec2/utils`-class no longer has any querystring-logic left - everything is now handled by the generic methods like `_get_param()`

The BaseResponse-class now contains a few other methods, like `_get_multi_param`. As far as I can tell, all services are now using these 4/5 methods to read all parameters

The `TaggingService` now exists, which contains centralized logic for tag reading/storage/writing.

Development documentation can now be found here: 
http://docs.getmoto.org/en/latest/docs/contributing/index.html

With that in mind, I would propose closing this issue, as all the cleanup mentioned in this topic has been done. (:partying_face:)
