### ISSUE TITLE
Question: Official docker image

### ISSUE THREAD

**Issue by terrycain** [spulec/moto#1159]
Its late and I'm probably overlooking something but do you have an image on DockerHub that's built direct from this repo's Docker file? If I am right and there is not one, is there a reason why not other than no one has set it up?

**Comment by JackDanger** [comment]
I don't believe we have one and it would be super useful to have one. Please feel free to make one!

**Comment by dbfr3qs** [comment]
Could a docker build and publish step be added to the Makefile?

**Comment by JackDanger** [comment]
@dbfr3qs It sure could. I don't know how we'd manage Dockerhub credentials and all that but we could make pushing a new image part of the release process

**Comment by dbfr3qs** [comment]
How does make publish get run?

**Comment by JackDanger** [comment]
> How does make publish get run?

I do it manually on my laptop and I then get my PyPi credentials out of 1Password every time. It's not a great solution but it's working so far for me. I suppose we could set up a DockerHub organization that at least I have write access to and then docker images would be built and published there. 

@spulec, do you have any opinions on publishing a DockerHub image on release?

**Comment by dbfr3qs** [comment]
You could maybe run the publish step in travis CI based off a tag being set (like when creating a release), maybe use the TRAVIS_TAG environment variable somehow. If TRAVIS_TAG=release make publish. Perhaps use travis's encrypted environment variables for credentials for docker and pipit (I haven't done any of this using travis, but it looks like a possibility).

**Comment by terrycain** [comment]
Will do, will also redo the docker file to use alpine if thats alright, should be able to get the download size to around 40mb from 300.

**Comment by terrycain** [comment]
You can I believe just link dockerhub with github and it github notifies it to build.

**Comment by terrycain** [comment]
And sorta off topic, you can add something like the following to get travis to publish to pypi when you tag a commit
```
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: whoevers_username
  password:
    secure: SOME_BASE64_TRAVIS_SECRET
  on:
    tags: true
    repo: spulec/moto
    python: 3.5
```

**Comment by dbfr3qs** [comment]
@terrycain excellent! @JackDanger there is room there to further automate the deployment to Pypi, if you are so inclined, using the approach @terrycain has mentioned, which is documented [here](https://docs.travis-ci.com/user/deployment/pypi/).

**Comment by spulec** [comment]
I like this. I can add some encrypted keys if we think that is the right way to go

**Comment by terrycain** [comment]
Yeah I think when I did it there was a script that set up all the Travis
yml for me so it shouldn't be too difficult.

**Comment by dbfr3qs** [comment]
If anything this would reduce the amount of work for @JackDanger.

**Comment by spulec** [comment]
This is all being done now. Let me know if we need anything else.
