### ISSUE TITLE
EC2 Instances in VPC do not get IPs that match the VPC Subnet

### ISSUE THREAD

**Issue by DonavanFritz** [spulec/moto#1175]
When creating an EC2 instances inside of a subnet with moto, the IP addresses that the instance gets assigned does not align with the subnet that the instance is being launched in.  Additionally, when setting the subnet attribute `MapPublicIpOnLaunch` to `True`, the value is not respected when the instance is launched in said subnet. 

Here's a script to easily reproduce:

```
import boto3, botocore, moto, sys
from moto import mock_ec2

@mock_ec2
def main():
    print('python version:', sys.version)
    print('moto version:', moto.__version__)
    print('boto3 version:', boto3.__version__)
    print('botocore version:', botocore.__version__)
    client = boto3.client('ec2', 'us-east-1')

    result = client.create_vpc(CidrBlock='192.168.0.0/16')
    vpc_id = result['Vpc']['VpcId']
    print('Created VpcId=', vpc_id)

    result = client.create_subnet(CidrBlock='192.168.1.0/24', VpcId=vpc_id)
    subnet_id = result['Subnet']['SubnetId']
    print('Created SubnetId=', subnet_id)

    client.modify_subnet_attribute(
        SubnetId=subnet_id,
        MapPublicIpOnLaunch={'Value': True}
    )

    resource = boto3.resource('ec2', 'us-east-1')
    i = resource.create_instances(
        ImageId='ami-abc123',
        MinCount=1,
        MaxCount=1,
        SubnetId=subnet_id
    )[0]

    print('instance_id=', i.instance_id)
    print('private_ip_address=', i.private_ip_address)
    print('public_ip_address=', i.public_ip_address)
    print('subnet_id=', i.subnet_id)
    print('subnet.cidr_block=', i.subnet.cidr_block)
    print('vpc_id=', i.vpc_id)
    print('vpc.cidr_block=', i.vpc.cidr_block)

if __name__ == '__main__':
    exit(main())
```

The output I got when running:

```
python version: 3.5.2 (v3.5.2:4def2a2901a5, Jun 26 2016, 10:47:25) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
moto version: 1.0.1
boto3 version: 1.4.4
botocore version: 1.5.73
Created VpcId= vpc-3679181b
Created SubnetId= subnet-36678a48
instance_id= i-9542d363
private_ip_address= 10.86.170.112
public_ip_address= None
subnet_id= subnet-36678a48
subnet.cidr_block= 192.168.1.0/24
vpc_id= vpc-3679181b
vpc.cidr_block= 192.168.1.0/16
```

What I would expect:

```
 ... 
private_ip_address= 192.168.1.X
public_ip_address= X.X.X.X
 ...
```

I expect `private_ip_address` to return a private ip address within the subnet address range (`192.168.1.0/24` in this example) and `public_ip_address` to return a public ip address address vs `None`.  Additionally, it needs to take into consideration [reserved IPs](http://boto3.readthedocs.io/en/latest/reference/services/ec2.html#EC2.Client.create_subnet) by AWS. 

This is my first time using moto (nice job btw!) so I'm not familiar with the code base.  I'm happy to submit a PR if you can point me in the direction of where the edits would need to take place.

**Comment by terrycain** [comment]
[This](https://github.com/spulec/moto/blob/master/moto/ec2/models.py#L2194-L2208) is the function that creates and stores a subnet. I would do some IP checks there to ensure the subnet cidr is within the vpc cidr.

[This](https://github.com/spulec/moto/blob/master/moto/ec2/responses/instances.py#L52-L57) function creates the instance.

[This](https://github.com/spulec/moto/blob/master/moto/ec2/models.py#L619) Is the class that stores instances
[This](https://github.com/spulec/moto/blob/master/moto/ec2/models.py#L405) function eventually gets called which sets up public/private IPs

Which leads to [This](https://github.com/spulec/moto/blob/master/moto/ec2/models.py#L539) dodgy function to get instance IPs. a few lines later you get the subnet from a subetId, you should get the subnet, from that you have a cidr, from which you can generate an IP. I would think it would make sense to exclude the network, .1 .2 and broadcast addresses from the generation. Also make a list in the subnet object to store the IPs as you dont want to give them out again. On termination, remove the IP from said subnet, you probably want to do that on removal of the nic not the instance.

Public IPs, eventually you get [here](https://github.com/spulec/moto/blob/master/moto/ec2/models.py#L179), somewhere that is getting set to False i guess so then `public_ip` remains set to None
