### ISSUE TITLE
Coveralls Bugs

### ISSUE THREAD

**Issue by terrycain** [spulec/moto#1185]
Ok firstly, coveralls needs to be re-oauth'd to github as you cant actually view line by line coverage on there.

Secondly, it spams more than once per commit. We could do with it not doing that. It appeared 3 times earlier, ideally we want all 4 test runs to merge into 1 notification as the coverage is global across the 4 runs as its all the same codebase.

**Comment by captainkerk** [comment]
It seems like I caused this behavior on #1265 by a commit and push, then before it had a chance to finish I amended that commit and force pushed. 

Is [Auto Cancellation](https://blog.travis-ci.com/2017-03-22-introducing-auto-cancellation) for this build in Travis CI set? That may help, as the first commit's build will be cancelled.

**Comment by spulec** [comment]
I've reauthed coveralls and disabled Auto Cancellation on Travis. Let me know if there is anything else.
