### ISSUE TITLE
"Expected hash not equal to calculated hash" error with S3 put object

### ISSUE THREAD

**Issue by copenhas** [spulec/moto#1219]
First I would like to thank all of you for such a comprehensive AWS mocking library... now on to my issue.

I'm getting an "Expected hash not equal to calculated hash" exception thrown from AWSSDK for .NET when using moto's stand alone s3 server. This always happens when putting an object into the server. 

It appears to be that moto returns an ETag with the wrong (?) hash value in it. I've debugged the AWSSDK to find the [line where the check is made](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/S3/Custom/Internal/AmazonS3ResponseHandler.cs#L137) and verified the that calculated hash matches what I get when calculating the hash manually in .NET and in Python. My Python code is based on the [etag code in moto](https://github.com/spulec/moto/blob/master/moto/s3/models.py#L85).

I have all the relevant code and my test file uploaded to a gist:
https://gist.github.com/copenhas/677cf1b1066af1c53fce9feaa9ff0191

The test file has no line endings, but before it did have multiple Windows line endings creating whitespace at the bottom. This caused differences in hash values between my .NET and Python code. I removed them as a test and found that I was able to generate the same hash value between my .NET and Python code. I'm not positive but Python might be stripping out the carriage return character which could cause some Windows compatibility issues with this library.

Output of the C# program (I've tried .NET Core 2.0 and .NET Full Framework 4.6.1)
```
.NET MD5: "32A0E5FD908F68255E88DA135632BD5F"
MotoTest
Expected hash not equal to calculated hash
Moto MD5: "8929c640fcd7b0a9b8800f6852df4f93"
```

Output of Python script:
```
PS C:\> python .\md5.py
"32a0e5fd908f68255e88da135632bd5f"
```

Exception details coming out of AWSSDK:
```
Amazon.Runtime.AmazonClientException occurred
  HResult=0x80131500
  Message=Expected hash not equal to calculated hash
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at Amazon.S3.Internal.AmazonS3ResponseHandler.CompareHashes(String etag, Byte[] hash) in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Services\S3\Custom\Internal\AmazonS3ResponseHandler.cs:line 213
   at Amazon.S3.Internal.AmazonS3ResponseHandler.ProcessResponseHandlers(IExecutionContext executionContext) in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Services\S3\Custom\Internal\AmazonS3ResponseHandler.cs:line 186
   at Amazon.S3.Internal.AmazonS3ResponseHandler.<InvokeAsync>d__1`1.MoveNext() in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Services\S3\Custom\Internal\AmazonS3ResponseHandler.cs:line 60
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in E:\A\_work\308\s\src\mscorlib\src\System\Runtime\ExceptionServices\ExceptionServicesCommon.cs:line 130
```

Moto output from C# program:
```
PS C:\> moto_server s3
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [28/Sep/2017 09:08:25] "PUT /MotoTest HTTP/1.1" 200 -
127.0.0.1 - - [28/Sep/2017 09:08:25] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [28/Sep/2017 09:08:25] "PUT /MotoTest/my-file.txt HTTP/1.1" 200 -
127.0.0.1 - - [28/Sep/2017 09:08:26] "GET /MotoTest/my-file.txt HTTP/1.1" 200 -
```

My system details:
```
PS C:\dev> python --version
Python 3.5.2
```

Moto was installed via: `pip install moto[server]`
```
PS C:\dev> pip show moto
Name: moto
Version: 1.1.14
Summary: A library that allows your python tests to easily mock out the boto library
Home-page: https://github.com/spulec/moto
Author: Steve Pulec
Author-email: spulec@gmail.com
License: Apache
Location: c:\python35\lib\site-packages
Requires: python-dateutil, six, boto, Jinja2, requests, xmltodict, cryptography, boto3, pytz, pyaml, cookies, mock, werkzeug, dicttoxml
```

Windows 7 Professional Service Pack 1
Visual Studio Enterprise 2017 Version 15.3.4

Thanks for taking a look. I would really appreciate help figuring this out so I can use the S3 server in my local testing.

**Comment by terrycain** [comment]
Will have a look

**Comment by terrycain** [comment]
I just created a unit test
```
@mock_s3
def test_hash():
    client = boto3.client('s3', region_name='eu-central-1')
    client.create_bucket(Bucket='test-bucket')

    file_content = b'A Test File'
    computed_etag = '"{0}"'.format(hashlib.md5(file_content).hexdigest())

    client.put_object(Bucket='test-bucket', Key='test_file.txt', Body=b'A Test File')
    resp = client.get_object(Bucket='test-bucket', Key='test_file.txt')

    computed_etag.should.equal(resp['ETag'])
```

And it claims the ETag is fine. The only thing I can think of is if the C# sdk uses the multipart upload behind the scenes then the ETags arn't going to be the same anyway.

**Comment by copenhas** [comment]
It would appear so. The .NET SDK generates a different hash then moto. I have no problems using AWS S3 service itself though.

**Comment by terrycain** [comment]
Can this be closed? As I'm wanting to blame .net ha

**Comment by copenhas** [comment]
I'll try to update and replicate your test tomorrow. I believe everyone on my team has switched to localstack which seems to be working for us.

**Comment by spulec** [comment]
I'm going to close this out; feel free to reopen with more info if the problem remains
