### ISSUE TITLE
Enable linter to catch PEP issues

### ISSUE THREAD

**Issue by thehesiod** [spulec/moto#1220]
There are a lot of annoying things from PEP, but some good ones like standardize spacing and naming conventions.  Perhaps can enable a linter with a subset of PEP?  I know some projects use flake. This will help avoid people having to catch these issues by hand, which is very error prone.

**Comment by terrycain** [comment]
Travis does run make lint at the start of all test runs. flake8 is catching some stuff.

**Comment by thehesiod** [comment]
We should enable spacing and naming conventions I'm guessing to reduce the work for the reviewers as it seems those are things you want

**Comment by spulec** [comment]
I have a PR to add Black to this repo. Feedback welcome

https://github.com/spulec/moto/pull/2290

**Comment by thehesiod** [comment]
cool, that is quite the amount of string quoting normalization :) I'm not sure the value that particular normalization for the first iteration given it's not meant to catch bugs and adds a ton of noise to the first commit (and marginal value IMHO).  I think for some of the checks you need to install the specific flake8 plugin.  Here are some that I was thinking of for one of the repos I'm working on:

Perhaps it's worth an iterative approach?

```
flake8-return
flake8-comprehensions
flake8-builtins
flake8-eradicate
flake8-mutable
flake8-SQL ?
flake8-deprecated ?
flake8-type-annotations
flake8-string-format
flake8-mypy
pep8-naming
```

**Comment by spulec** [comment]
Yeah, I don't have particular thoughts on string quoting. Happy to rerun black with that fix disabled.

Any of those seem reasonable to me to add.

**Comment by bblommers** [comment]
I think we can close this, now that _black_ is enforced
