### ISSUE TITLE
dicttoxml is GPLv2-licensed

### ISSUE THREAD

**Issue by drmorr0** [spulec/moto#1229]
I see in [this patch](https://github.com/spulec/moto/commit/3cdb4afad0f6a42c790c39c56e2b6f0680d54ff7#diff-2eeaed663bd0d25b7e608891384b7298) the [dicttoxml](https://github.com/quandyfactory/dicttoxml) library was added as a requirement, which is GPLv2-licensed.  Unfortunately the GPLv2 is [not compatible](https://www.apache.org/licenses/GPL-compatibility.html) with the Apache2.0 license, which moto is licensed under, and as far as I understand it, this would require moto to switch to a GPLv2-based licensing scheme.  (The difference between GPLv2 and LGPLv2 is that LGPL allows you to link libraries in to non-GPL-licensed code, whereas GPL considers even linking of libraries to create a "derivative work").  Any chance we could get a version of moto that doesn't depend on GPLv2-licensed code?

**Comment by drmorr0** [comment]
Also I noticed that dicttoxml is only used in [one place](https://github.com/spulec/moto/search?utf8=✓&q=dicttoxml&type=) so it seems like it might not be that hard to replace it with something else.

**Comment by JackDanger** [comment]
@drmorr0 Great find, thank you for this. Yes, we can remove this dependency immediately and provide you with a new version of Moto without a problematic license.

**Comment by drmorr0** [comment]
Fantastic, thank you.  We've been using an ancient version of moto that didn't have this dependency and I was hoping to upgrade to a more recent version -- it's really useful software.  Let me know if there's any way I can help with the change.

**Comment by JackDanger** [comment]
@drmorr0 once #1231 is merged I'll release a new version for you. Please give that a review if you have a moment.

**Comment by JackDanger** [comment]
@drmorr0 Moto version 1.1.21 is now released and does not depend on dicttoxml

**Comment by drmorr0** [comment]
Nice!  Thank you so much!
