### ISSUE TITLE
Implementation of get_policy (IAM) to the moto library

### ISSUE THREAD

**Issue by josenrihernand** [spulec/moto#1238]
Hello all,

I am in progress of implement get_policy (IAM) to moto library.

When I execute a test with some python script that use "get_policy", I get the following error message:
TypeError: get_policy() got an unexpected keyword argument 'policyarn'

Here is the changes I applied, after I cloned the moto library to my local environment:

**..tests/test_iam.py:**

@mock_iam
def test_get_policy():
    conn = boto3.client('iam', region_name='us-east-1')
    conn.create_policy(
        PolicyName="TestGetPolicy",
        PolicyDocument='{"some":"policy"}')
    version = conn.create_policy_version(
        PolicyArn="arn:aws:iam::aws:policy/TestGetPolicy",
        PolicyDocument='{"some":"policy"}')
    with assert_raises(ClientError):
        conn.get_policy(
            PolicyArn="arn:aws:iam::aws:policy/TestGetPolicy",
    retrieved = conn.get_policy(
        PolicyArn="arn:aws:iam::aws:policy/TestGetPolicy",
        VersionId=version.get('PolicyVersion').get('VersionId'))
    retrieved.get('Policy').get('Document').should.equal({'some':'policy'})

**..moto/iam/responses.py:**

    def get_policy(self):
        policyarn = self._get_param('PolicyArn')
        policyarn = iam_backend.get_policy(
            policyarn = policyarn)
        template = self.response_template(GET_POLICY_TEMPLATE)
        return template.render(policyarn = policyarn)

Regarding "..moto/iam/models.py", it looks like get_policy entries were already implemented (it is the same file as the current one on moto library).

Any help / comment would be appreciated,

Thanks,

**Comment by JackDanger** [comment]
@josenrihernand Thanks for working on this!

The problem you're running into is that the current implementation of `get_policy` in the IAM Moto backend gets the policy by name: https://github.com/spulec/moto/blob/master/moto/iam/models.py#L471

You'll want to extend that to get it by name or by arn (or create a new `get_policy_by_arn` method, if that feels better). Each policy has a `.arn` propery on it so you can list the policies and find the one with a matching arn and return it.

**Comment by JackDanger** [comment]
If you push your work on a pull request and mark the PR as 'WIP' (work in progress) then we'll be able to run your actual failing tests locally to help debug

**Comment by josenrihernand** [comment]
Hi @JackDanger,

Thanks a lot to take a moment, and review it !

I'll summarize the advance so far about this issue:

The most recent adjustment I have applied on the code, follows:

**Template GET_POLICY_TEMPLATE on ../moto/iam/responses.py:**

GET_POLICY_TEMPLATE = """<GetPolicyResponse xmlns="https://iam.amazonaws.com/doc/2010-05-08/">
  <GetPolicyResult>
      <Document>{{ policyarn.document }}</Document>
      <DefaultVersionId>{{ policyarn.default_version_id }}</DefaultVersionId>
      <CreateDate>2017-10-04T15:45:35Z</CreateDate>
  </GetPolicyResult>
  <ResponseMetadata>
    <RequestId>20f7279f-99ee-11e1-a4c3-27EXAMPLE804</RequestId>
  </ResponseMetadata>
</GetPolicyResponse>"""

**get_policy function on ../moto/iam/responses.py:**

    def get_policy(self):
        policyarn = self._get_param('PolicyArn')
        policyarn = iam_backend.get_policy(
            policyarn)
        template = self.response_template(GET_POLICY_TEMPLATE)
        return template.render(policyarn = policyarn)

**test_get_policy function on ../tests/test_iam.py**

@mock_iam
def test_get_policy():
    conn = boto3.client('iam', region_name='us-east-1')
    conn.create_policy(
        PolicyName="TestGetPolicy",
        PolicyDocument='{"some":"policy"}')
    version = conn.create_policy_version(
        PolicyArn="arn:aws:iam::aws:policy/TestGetPolicy",
        PolicyDocument='{"some":"policy"}')
    with assert_raises(ClientError):
        conn.get_policy(
            PolicyArn="arn:aws:iam::aws:policy/TestGetPolicy",
    retrieved = conn.get_policy(
        PolicyArn="arn:aws:iam::aws:policy/TestGetPolicy",
        VersionId=version.get('PolicyVersion').get('VersionId'))
    retrieved.get('Policy').get('Document').should.equal({'some':'policy'})

After these adjustments, when I execute my unittest & mock, the following code works (it did not work before, because the get_policy was not implemented. In this code, "list_attached_group_policies" was also recently implemented):
---------------------------------------------------------------
groupPolicies = iam_conn_client.list_attached_group_policies(
       GroupName = groups["GroupName"]
for attachedPolicy in groupPolicies["AttachedPolicies"]:
	currentPolicy = iam_conn_client.get_policy(
	PolicyArn = attachedPolicy["PolicyArn"]
	);
---------------------------------------------------------------

print("Attached Policy: ", attachedPolicy["PolicyArn"]);   --> **it works.**
--> ('Attached Policy: ', 'arn:aws:iam::aws:policy/TestDBPolicy')

print("Current Policy: ", currentPolicy);	--> **it also works.**
--> ('Current Policy: ', {u'Policy': {u'CreateDate': datetime.datetime(2017, 10, 4, 15, 45, 35, tzinfo=tzutc()), u'DefaultVersionId': ''}, 'ResponseMetadata': {'RetryAttempts': 0, 'HTTPStatusCode': 200, 'RequestId': '20f7279f-99ee-11e1-a4c3-27EXAMPLE804', 'HTTPHeaders': {u'Content-Type': u'text/plain', u'server': u'amazon.com'}}})

However, the next lines of my script fail, with the following error message:
----------------------------------------------------------------
groupPolicies = iam_conn_client.list_attached_group_policies(
       GroupName = groups["GroupName"]
policy_version = iam_conn_client.get_policy_version(
      PolicyArn = attachedPolicy["PolicyArn"],
      VersionId = currentPolicy["Policy"]["DefaultVersionId"]
);
----------------------------------------------------------------
**An error occurred (NoSuchEntity) when calling the GetPolicyVersion operation: Policy version not found**

I don't know if these error is related to the code I added recently, to implement get_policy, or not.

It looks like the root cause, is because "DefaultVersionId" return no value (please check the output for "Current Policy" above).

I'll spend some time trying to fix it, if not, maybe I'll push a pull request with the mark "WIP"...

However, if by the time you read this input, you have any comments / suggestion, it'd be appreciated...


Again, thanks a lot !

**Comment by josenrihernand** [comment]
Hi @JackDanger

What is the procedure for PR ? 
Should i create a new branch on moto repo ? or should i push the moto repo on my own repo ?

thanks a lot!

**Comment by JackDanger** [comment]
@josenrihernand You'll want to fork the repo and push a branch to your fork and then create a pull request from that branch. Only a few folks have permissions to push branches to Moto but anybody can create a pull request from a fork. Thanks!

**Comment by josenrihernand** [comment]
ok JackDanger, I got it. 

thanks !

**Comment by josenrihernand** [comment]
Hi @JackDanger ,

I just create a PR from my fork, and also I describe a help request:   WIP Iam get policy #1240

I really appreciate your help (or from someone else), in order to implement get_policy and, also, something about a error messages i am getting with get_policy_version.

thanks a lot !

**Comment by spulec** [comment]
Closed with https://github.com/spulec/moto/pull/1759
