### ISSUE TITLE
Quick Question: Recommended Mock Setup in Tests

### ISSUE THREAD

**Issue by fxfitz** [spulec/moto#1241]
Is there a recommended way of setting up a mock before each test?

For example, I'm looking to write a series of tests that expect there already to have a SQS Queue created and a message in it.

Any recommendations on how to do that?

Thanks!

**Comment by terrycain** [comment]
If your using pytest, fixtures could be the way to go (go look at aiobotocore's unit tests for that). Else just run a function at the start of the test case cant hurt e.g. [this](https://github.com/terrycain/moto/blob/batch/tests/test_batch/test_batch.py#L123)

**Comment by fxfitz** [comment]
Yeah, that's actually what I"m doing now, but was wondering if anyone else had any better or more elegant recommendations. 

If not, we can definitely close the issue! :-)

```python
@pytest.fixture
def setup_sqs():
    mock = moto.mock_sqs()
    mock.start()

    session = boto3.session.Session(**FAKE_AWS_CREDS)
    sqs = session.client('sqs')
    sqs.create_queue(QueueName=FAKE_QUEUE_NAME)

    yield
    mock.stop()
```
