### ISSUE TITLE
Errors returned by mock_s3

### ISSUE THREAD

**Issue by tnuhwg** [spulec/moto#1243]
I have a function that calls the boto3 S3 resource. that I'm trying to test using mock_s3. It traps the error for the case when the bucket does not exist, however, mock_s3 returns a different error.

If I test the code using S3 directly, then the ClientError that is returned is:
{'ResponseMetadata': {'HTTPStatusCode': 404, 'RetryAttempts': 0, 'HostId': 'V/TEKk03JwrrcYsu4naQRqY1w0t8x5SE9RqvwFK0L9Q531HyAlNPC1H859LqMveNp8pBXXBGlzE=', 'RequestId': '2699661E0DBD064E', 'HTTPHeaders': {'x-amz-id-2': 'V/TEKk03JwrrcYsu4naQRqY1w0t8x5SE9RqvwFK0L9Q531HyAlNPC1H859LqMveNp8pBXXBGlzE=', 'server': 'AmazonS3', 'transfer-encoding': 'chunked', 'x-amz-request-id': '2699661E0DBD064E', 'date': 'Thu, 05 Oct 2017 15:27:51 GMT', 'content-type': 'application/xml'}}, 'Error': {'Message': 'Not Found', 'Code': '404'}}

If I test the code using mock_s3, then the ClientError that is returned is:
{'ResponseMetadata': {'RetryAttempts': 0, 'HTTPStatusCode': 404, 'HTTPHeaders': {u'Content-Type': u'text/plain'}}, 'Error': {'Message': 'The specified bucket does not exist', 'Code': 'NoSuchBucket', 'BucketName': 'ra-nobucket', 'RequestID': '7a62c49f-347e-4fc4-9331-6e8eEXAMPLE'}}

I can add code to handle both errors, but that defeats the purpose of testing.

Any suggestions?

**Comment by JackDanger** [comment]
@tnuhwg I suspect your code is written in a way that it expects an S3 bucket to already exist. When you `mock_s3` you start from an empty S3 and you'll need to make that bucket yourself. Something like:
```
    conn = boto3.resource('s3', region_name='us-east-1')
    conn.create_bucket(Bucket='mybucket')
```
then your test code should work.
