### ISSUE TITLE
moto should throw errors for not implemented endpoints for each service

### ISSUE THREAD

**Issue by thehesiod** [spulec/moto#1254]
I was confused when I saw https://github.com/spulec/moto/issues/1249 because I knew that the lambda service was implemented so I didn't understand why the user was getting connect errors until @dbfr3qs reminded me that due to how the url rewriting works in moto, if the specific endpoint for service is not implemented then boto will try to connect to the actual AWS endpoint.  This is bad, instead moto should have a generic fallback for unimplemented endpoints of "supported" services.

**Comment by spulec** [comment]
Going to close this in favor of https://github.com/spulec/moto/issues/1567
