### ISSUE TITLE
s3.copy_object() doesn't increment the VersionId correctly

### ISSUE THREAD

**Issue by alexwlchan** [spulec/moto#1271]
If you update the file at an S3 key using `copy_object()` in a version-controlled bucket, moto does not assign the key a new VersionId.

Here’s a brief summary of repro steps, with a full runnable test case below:

* Create a version-controlled S3 bucket
* Upload two files to the bucket (say `key1` and `key2`). Check they’re both assigned a VersionID `0`
* Use the `copy_object` API to copy the contents of `key1` into `key2`
* Check that the VersionId of `key2` is updated accordingly

I’d expect the VersionId to change for the new version (this is the behaviour in Amazon S3 proper); what actually happens is the VersionID is created at `0` and stays at `0`.

### Test environment

I’m using Python 3.6.1, with moto 1.1.23 and boto 1.4.7 installed in a virtualenv using pip.

<details>
<summary>Output of "pip freeze"</summary>

<br/>

```
asn1crypto==0.23.0
aws-xray-sdk==0.92.2
boto==2.48.0
boto3==1.4.7
botocore==1.7.30
certifi==2017.7.27.1
cffi==1.11.2
chardet==3.0.4
cookies==2.2.1
cryptography==2.1.1
docker==2.5.1
docker-pycreds==0.2.1
docutils==0.14
idna==2.6
Jinja2==2.9.6
jmespath==0.9.3
jsonpickle==0.9.5
MarkupSafe==1.0
mock==2.0.0
moto==1.1.23
pbr==3.1.1
pyaml==17.10.0
pycparser==2.18
python-dateutil==2.6.1
pytz==2017.2
PyYAML==3.12
requests==2.18.4
s3transfer==0.1.11
six==1.11.0
urllib3==1.22
websocket-client==0.44.0
Werkzeug==0.12.2
wrapt==1.10.11
xmltodict==0.11.0
```

</details>

### Test case

This is a complete, runnable test case:

```python
import boto3
import moto

moto.mock_s3().start()

client = boto3.client('s3')

BUCKET = 'mygreatbukkit'
SRC_KEY = 'file_src.txt'
DST_KEY = 'file_dst.txt'

# Create the bucket, and enable versioning
client.create_bucket(
    Bucket=BUCKET,
    CreateBucketConfiguration={'LocationConstraint': 'eu-west-1'}
)
client.put_bucket_versioning(
    Bucket=BUCKET, VersioningConfiguration={'Status': 'Enabled'}
)

# Then create both keys, and inspect their VersionId
for Key in [SRC_KEY, DST_KEY]:
    client.put_object(
        Bucket=BUCKET, Key=Key, Body=b'I live at %s' % Key.encode()
    )
    resp = client.get_object(Bucket=BUCKET, Key=Key)
    print((Key, resp['VersionId']))

# Now copy the object from one bucket to the other, and check that S3
# assigns it a new VersionId
client.copy_object(
    CopySource={'Bucket': BUCKET, 'Key': SRC_KEY},
    Bucket=BUCKET,
    Key=DST_KEY
)
resp = client.get_object(Bucket=BUCKET, Key=DST_KEY)
print((DST_KEY, resp['VersionId']))
```

This is the output when running under moto; notice that VersionId stays the same:

```
('file_src.txt', '0')
('file_dst.txt', '0')
('file_dst.txt', '0')
```

This is the output if you remove `moto.mock_s3().start()`, and run it against S3 directly:

```
('file_src.txt', '00ehtAiYbwaQu5qz9EAT.jL4J4mxbaS9')
('file_dst.txt', '2sCyWtdg6yfMKBELO0PxLq11xLWD.EcB')
('file_dst.txt', 'W2UQ7ec4PUK30T.28D0j1ZE50NzSuDAs')
```

Notice that the VersionId has changed after calling `copy_object()`.

**Comment by terrycain** [comment]
Yep confirmed bug, am making a PR as we speak.
