### ISSUE TITLE
Support missing for SNS Publish "Subject" optional parameter

### ISSUE THREAD

**Issue by hwine** [spulec/moto#1276]
The API (and boto3) allow for an optional parameter [``Subject`` to the ``publish``](http://docs.aws.amazon.com/sns/latest/api/API_Publish.html) method on an sns client. There are some constraints on the value of that field, (<100 characters is one) which do not appear to be checked in the current ``moto``.

A simplification of the method I'd like to test with ``moto`` is at the end. If I test using a message of
```python
    msg = "nope " * 21  # > 100 characters
```
It passes with ``moto``, but throws an exception on AWS: ``An error occurred (InvalidParameter) when calling the Publish operation: Invalid parameter:
Subject``

```python
    def send_sns(self, msg):
        subject = msg.split('\n')[0]
        client = boto3.client("sns")
        topic_arn = os.environ.get('SNSARN', "")
        response = client.publish(Message=msg, Subject=subject,
                                  TopicArn=topic_arn)
```

Here are my current library versions for python2.7:
```
Package                      Version     
---------------------------- ----------- 
boto                         2.48.0      
boto3                        1.4.7       
botocore                     1.7.29      
moto                         1.1.22      
```

**Comment by JackDanger** [comment]
@hwine Thanks for finding and reporting this! Would you mind writing a (failing) test that reproduces this bug? If you get stuck feel free to make a comment here and somebody will jump in to help out. I recommend looking at `tests/test_sns/test_sns.py` to start.

**Comment by hwine** [comment]
@JackDanger looks like @terrycain beat me to it. ;)  If that didn't cover it, let me know specifically what you're looking for.

**Comment by terrycain** [comment]
Yeah sorry was bored, and this popped up :wink:
