### ISSUE TITLE
Start Instance calling actual EC2 endpoint

### ISSUE THREAD

**Issue by dmitrypolo** [spulec/moto#1277]
Currently I am writing some tests using this library. Following the simple example you provide:

```
import boto3
from moto import mock_ec2

def add_servers(ami_id, count):
    client = boto3.client('ec2', region_name='us-west-1')
    client.run_instances(ImageId=ami_id, MinCount=count, MaxCount=count)

@mock_ec2
def test_add_servers():
    add_servers('ami-1234abcd', 2)

    client = boto3.client('ec2', region_name='us-west-1')
    instances = client.describe_instances()['Reservations'][0]['Instances']
    assert len(instances) == 2
    instance1 = instances[0]
    assert instance1['ImageId'] == 'ami-1234abcd'
```

I follow this example and create a test of my own, a trivial one to illustrate the point:

```
def start_instance(instance_id):
    client = boto3.client('ec2')
    client.start_instances(InstanceIds=[instance_id])

@mock_ec2
def test_start_instance():
    start_instance('abc123')
    client = boto3.client('ec2')
    instances = client.describe_instances()
    print instances

test_start_instance()

ClientError                               Traceback (most recent call last)
<ipython-input-6-f3b792259f42> in <module>()
----> 1 test_start_instance()

/Users/dmitry/Desktop/my-sandbox/lib/python2.7/site-packages/moto/core/models.pyc in wrapper(*args, **kwargs)
     68             self.start(reset=reset)
     69             try:
---> 70                 result = func(*args, **kwargs)
     71             finally:
     72                 self.stop()

<ipython-input-5-7ae1987ef89c> in test_start_instance()
      5 @mock_ec2
      6 def test_start_instance():
----> 7     start_instance('abc123')
      8     client = boto3.client('ec2')
      9     instances = client.describe_instances()

<ipython-input-5-7ae1987ef89c> in start_instance(instance_id)
      1 def start_instance(instance_id):
      2     client = boto3.client('ec2')
----> 3     client.start_instances(InstanceIds=[instance_id])
      4 
      5 @mock_ec2

/Users/dmitry/Desktop/my-sandbox/lib/python2.7/site-packages/botocore/client.pyc in _api_call(self, *args, **kwargs)
    310                     "%s() only accepts keyword arguments." % py_operation_name)
    311             # The "self" in this scope is referring to the BaseClient.
--> 312             return self._make_api_call(operation_name, kwargs)
    313 
    314         _api_call.__name__ = str(py_operation_name)

/Users/dmitry/Desktop/my-sandbox/lib/python2.7/site-packages/botocore/client.pyc in _make_api_call(self, operation_name, api_params)
    603             error_code = parsed_response.get("Error", {}).get("Code")
    604             error_class = self.exceptions.from_code(error_code)
--> 605             raise error_class(parsed_response, operation_name)
    606         else:
    607             return parsed_response

ClientError: An error occurred (InvalidInstanceID.NotFound) when calling the StartInstances operation: The instance ID '[u'abc123']' does not exist
```

I am working from within a virtual environment and have verified that the correct path is being called upon by using `moto.__path__`. The version I am using is `1.0.1` according to `moto.__version` even though when it is installed through `pip` it says `moto==1.1.23 in ./lib/python2.7/site-packages`. I have tried uninstalling and reinstalling as well. Please advise how to proceed.

**Comment by bpandola** [comment]
You're trying to start an instance that you haven't created (or stopped).  Moto is replying correctly, telling you that the instance does not exist.  In order to test your `start_instance` method, you need to create and stop an instance in your `test_start_instance` method first (the call to boto3's `create_instances` method will return the instance identifier, which you can then pass on to your method under test).

Moto isn't like a MagicMock--it's an actual in-memory representation of the AWS resources.  So you can't start an instance you haven't created, you can't create an instance in a vpc you haven't previously defined *in Moto*, etc.  At my work, we have a `setup_mock_aws` method that essentially starts Moto and populates it with all of our expected subnets, vpcs, security groups, etc.  Then we run our tests.

**Comment by dmitrypolo** [comment]
@bpandola you are correct, I was under the impression it worked like MagicMock, using your suggestions I was able to go ahead and create a method which populates the services I need. Thank you. I am closing this issue.
