### ISSUE TITLE
Resources in mentioned in cloud formation template is not getting created.

### ISSUE THREAD

**Issue by mishraawake** [spulec/moto#1282]
Hi,
I am creating security group through cloud formation template and then trying to retrieve that through boto client but it says that security group does not exists. If i create security group through command line then i am able to fetch it.
It seems like resources in cloud formation does not get created when we deploy it.

**Comment by terrycain** [comment]
Can we get a test case that shows this failing.

**Comment by mishraawake** [comment]
Hi, 
I debuged and found out the reason. In case of route53 models.py in moto, physical_resource_id is returning as name of resource but it should have been id of resource.

**Comment by terrycain** [comment]
Ahh if you havent already I can PR that later.

**Comment by JackDanger** [comment]
Nice work, @terrycain !
