### ISSUE TITLE
AWS SDK XRay is now at 0.93 and it looks like 0.92.2 is not available publicly anymore

### ISSUE THREAD

**Issue by gaffo** [spulec/moto#1290]
Could we upgrade the version or do a >= instead of a == in setup.py?

**Comment by frivoire** [comment]
Exactly : version 0.92.2 *is* available on pypi, but only as a wheel and not at a tar.gz, cf this issue :
https://github.com/aws/aws-xray-sdk-python/issues/1

So I agree with you, there is an issue/improvement.
So I've created this PR : https://github.com/spulec/moto/pull/1292

**Comment by terrycain** [comment]
This is merged, can it be closed now?

**Comment by JackDanger** [comment]
Thanks for the triage @terrycain
