### ISSUE TITLE
Optional "Subject" parameter to SNS Publish not propagated into the response

### ISSUE THREAD

**Issue by hwine** [spulec/moto#1298]
Now that #1276 has been merged, I'll re-raise the issue I [embedded](https://github.com/spulec/moto/pull/1283#discussion_r146011781) in that review.

The Subject field is now accepted, and validated. However, the value of the Subject field is not propagated into the message. Rather it returns the default value 'my subject' from https://github.com/spulec/moto/blob/462eceae6f73f0b529ecc12fe03eaf018f059b43/moto/sns/models.py#L104

Supporting that would be handy, but looks to be challenging. (I played with it a bit and ended up with a lot of blind ``**kwargs`` which hides other types of API issues.)

Note that there are several other optional fields in this message. From [the docs](https://docs.aws.amazon.com/sns/latest/api/API_Publish.html), these other fields are also not required: ``MessageAttributes``, ``MessageStructure``, ``PhoneNumber``, ``TargetArn``, and ``TopicArn``.

One approach might be to use ``**kwargs`` all the way down to the ``get_post_data`` call, and do some matching of template keys to supplied keys. But that feels a bit brittle, and may not cover all the code paths.

**Comment by thehesiod** [comment]
so I added "Subject" support in https://github.com/spulec/moto/pull/1387, each one will have to be implemented uniquely.

**Comment by hwine** [comment]
@thehesiod wow! Thanks, and that was a lot of work.

Since it looks like a major headache to deal with this issue generically, I think we should declare victory with the 'Subject' support (since that led to an actual exception on AWS). If other "I can't test properly" cases crop up, they should likely be new bugs.

Changing the summary to reflect that.

**Comment by thehesiod** [comment]
@hwine wasn't too bad :)  Sounds like a plan!
