### ISSUE TITLE
Cloudwatch.moto support for alarm states

### ISSUE THREAD

**Issue by dlcron** [spulec/moto#1311]
Feature request regarding cloudwatch moto.
===========================================

Hello, I need following apis:
* `boto3.client('cloudwatch').describe_alarms(StateValue=)`
* `boto3.client('cloudwatch').set_alarm_state`

Currently those are not supported and raises NotImplementedError:
* https://github.com/spulec/moto/blob/eb220cc6fb120a978de93be3905c50799875ba8d/moto/cloudwatch/responses.py#L166
* https://github.com/spulec/moto/blob/eb220cc6fb120a978de93be3905c50799875ba8d/moto/cloudwatch/models.py#L125

Thanks!

**Comment by terrycain** [comment]
API docs for [set_alarm_state](https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_SetAlarmState.html), and [describe_alarms](https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_DescribeAlarms.html)

Will have a look.

**Comment by terrycain** [comment]
Good issue, a failing test case would of sped things up but then again its not too difficult to make one. :smile:

**Comment by dlcron** [comment]
Yeah, I'll remember about this next time ;_). Thanks!
