### ISSUE TITLE
Simulating boto3 errors or access denied

### ISSUE THREAD

**Issue by christophetd** [spulec/moto#1322]
Hi, 

I'm interested to use Moto to test the implementation of class exposing a `is_bucket_writable` method returning True or False. Basically the code is:

```python
def is_bucket_writable(bucket_name, tmp_dir, s3_resource):
    random_filename = str(uuid.uuid4()) + '.txt'
    bucket = s3_resource.Bucket(bucket_name)
    try:
        bucket.put_object(Key=random_filename, Body='')
        silently_delete_bucket_file(bucket, random_filename)
        return True
    except ClientError as e:
        return False
```

... so it relies on boto3 throwing a `ClientError` to work. Is there anyway to make boto3 throwing an exception for that? I've tried changing the bucket ACL (`conn.BucketAcl('bucket').put(...)`) but I didn't manage to find any that would deny me access.

Thank you!

**Comment by terrycain** [comment]
I have a feeling ACLs might not be implemented yet. If you could write up a simple testcase I could probably get it done.

**Comment by christophetd** [comment]
I'll see if I can find some time to do that. In any case, do you think making boto3 throw errors is doable? The use case would be to test your application error handling, or something a bit more exotic like I'm doing

**Comment by terrycain** [comment]
mmm, it should be possible, i'll have a think

**Comment by dmateusp** [comment]
I know this issue is very old, but is is possible to simulate errors now ? I'm trying to simulate denied access to a bucket
