### ISSUE TITLE
Feature request: Support for resourcegroupstaggingapi

### ISSUE THREAD

**Issue by pll** [spulec/moto#1325]
Would love to see some basic support for this API call!

Thanks.
--
Paul

**Comment by terrycain** [comment]
This is going to be an interesting one.
Can I get a list of resources you intend to use with this? Mainly as moto has a ton of resources and I'm bound to miss some so if I can satisfy what your after, any more that are missing can be added after the fact.

**Comment by pll** [comment]
These  are the current supported resources for Resource Group Tagging:
http://docs.aws.amazon.com/awsconsolehelpdocs/latest/gsg/supported-resources.html

At this time I am merely calling this function to get a list of the supported resources which are already tagged.  Does that make sense? I'm basically using it as a means to discover if an environment of a specific name exists. So, we  have an automated process that deploys infrastructure and tags it all. I want to see if `environment-a` exists, so I do:

```
def environment_exists(env_name, env_vers=None):
    client = boto3.client('resourcegroupstaggingapi')
    env_name_filter = { 'Key': 'env_name', 'Values': [ env_name ] }
    env_vers_filter = { 'Key': 'env_vers', 'Values': [ env_vers ] }
    tag_filters = [ env_name_filter ]
    if env_vers:
        tag_filters.append(env_vers_filter)
    results = client.get_resources(TagFilters = tag_filters)

    if len(results['ResourceTagMappingList']) > 0:
        return True

    return False
```

From a moto perspective, all I'd really need to do, at a minimum, is be able to mock a VPC, EC2 instance, or some other supported resource, tag it, then call the moto-mocked version of `resourcegroupstaggingapi()` and get an appropriate dict back.  I hope that made sense :)

**Comment by terrycain** [comment]
Yeah should be fine, thanks for the example. Shouldn't be too difficult to get working.

**Comment by pll** [comment]
@terrycain I would love to help add this support, but have no idea how moto actually works in order to contribute, any way you could you include me on the PRs so I can learn by watching ?

**Comment by terrycain** [comment]
Sure, when I start the PR I normally mention the issue so you'll see it appear in the thread at some point. I'll try and order my commits a bit better so if you view commit by commit you'll see hopefully a fairly logical way of adding support.

**Comment by pll** [comment]
Awesome!  I seem to encounter a lot of edge cases that moto doesn't yet support. I'd love to learn how to properly extend it!  Thanks!

**Comment by terrycain** [comment]
Yeah moto is more of a do it/fix it as we see it project due to the scale of things to do.

**Comment by terrycain** [comment]
^^ above is link to PR, feel free to ask questions about things

**Comment by pll** [comment]
@terrycain  - Thanks. Took a look at the diffs, but am kinda lost. I think I need to understand the basic architecture of moto and how it works. I'm such an advanced programmer that it's obvious to me by reading the code.  I'll keep poking at it though, since I really *want* to understand so I can contribute as well!

**Comment by terrycain** [comment]
Yeah the first few changes are purely to set up moto so it knows about the new api. The responses  file handles incoming requests from boto3, the models file mainly deals with all the application logic and storage.

moto does some funky stuff with the request url, which it then maps to functions defined in the responses file automagically

**Comment by pll** [comment]
Oh, interesting.  Yeah, I probably just need to spend a lot of time poking through the code, maybe even running it in the debugger to poke at things to see what it's doing in order to understand the why's and how's.  Is there any basic developer documentation for moto anywhere?  Everything I've seen is end-user oriented.

**Comment by terrycain** [comment]
Yeah theres not really any docs for developers, I should probably write some at some point

**Comment by kyleposluns** [comment]
> Yeah theres not really any docs for developers, I should probably write some at some point

Do any docs for this exist now?

**Comment by spulec** [comment]
@kyleposluns we added a bit of documentation here: https://github.com/spulec/moto/blob/master/CONTRIBUTING.md
