### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by terrycain** [spulec/moto#1350]
@JackDanger can we bump version. Or better yet, can you email me the pypi details so i can automate it :wink:

**Comment by JackDanger** [comment]
I've now released Moto version 1.1.25
@terrycain what's your PyPi username? I'll see if I can add you to the project!

**Comment by JackDanger** [comment]
@spulec Can you add @terrycain to the PyPi project so Terry can do releases?

It's probably time we add a more formalized release process. I'll write a short guide for contributors and add some helpful scripts.

**Comment by JackDanger** [comment]
I've created some new guides for maintainers to easily release new versions of Moto. It's now a 3-command process: #1355

**Comment by thehesiod** [comment]
can we get another new release?  Would like one with https://github.com/spulec/moto/pull/2055 to avoid having to install this via git

**Comment by spulec** [comment]
Moto is on continuous release now. We cut a pre-release for each commit to master.
