### ISSUE TITLE
Moto returns inaccessible regions (for most accounts) when calling describe_regions

### ISSUE THREAD

**Issue by 2rs2ts** [spulec/moto#1361]
For most AWS customers, certain regions are not available: cn-north-1 and us-gov-west-1. When you call [`DescribeRegions`](http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeRegions.html) you get the list of AWS regions available to you(r account.) This is how `boto3`'s EC2 client works: it calls `DescribeRegions`. However, `boto` gets its endpoints from a JSON file, and by default it seems that file includes cn-north-1 and us-gov-west-1.

You can demonstrate this pretty easily in the python REPL, if you have your credentials set up:

```
>>> set([region.name for region in boto.ec2.regions()]) - set([region['RegionName'] for region in boto3.client('ec2', region_name='us-west-2').describe_regions()['Regions']])
set([u'cn-north-1', u'us-gov-west-1'])
```

Of course if your account has access to these other regions then you will get a different output, but I think most people are dealing with similar conditions to me and my company. You'd expect not to have cn-north-1 and us-gov-west-1 in the output of DescribeRegions. And if you're using boto3, you wouldn't expect to have to fiddle with boto settings just to get your mocks to work right.

Making this "just work" for everyone is tricky because there's no single right answer; it totally depends on the person's account. The solution is up to you, but I'll give my opinion in case it matters. I think you should return the list of regions that the majority of accounts will have access to. I think it's better to return a list that's correct for the majority of users rather than a list that's correct for what I assume is no user (because you need a special account to use cn-north-1, and I'm not sure that people with access to that region have access to any other regions.)

For reference, here are the relevant library versions I have, as of this post:

```
boto==2.48.0
boto3==1.4.8
botocore==1.8.1
moto==1.1.25
```

**Comment by terrycain** [comment]
Issue is that filtering out cn-north-1 and us-gov-west-1 is a little bit of hassle as we just simply ask boto3 what regions exist, regardless if you have access to them, and on from that Moto has absolutely no clue about what account is requesting data, so toggling this on and off would be even more difficult... And I do some work in cn-north-1 so it being there is nice :wink:

**Comment by gjehanin** [comment]
And if we choice, as for majority of AWS users, to list all regions excepted these ones. How can we do this? Bec I think Boto3 filter cannot do that....isn't it?

**Comment by spulec** [comment]
I am going to close this, but would be open to a PR adding something to the settings.py file. I would lean toward having all regions in there by default.
