### ISSUE TITLE
new PendingDeprecationWarning: Could not find AMI 

### ISSUE THREAD

**Issue by tardyp** [spulec/moto#1372]
Upgrading moto to latest version 1.25

Following snippet was used to create an imageId in moto:
```
        instance = r.create_instances(ImageId='foo', MinCount=1, MaxCount=1)[0]
        c.create_image(InstanceId=instance.id, Name="foo", Description="bar")
        c.terminate_instances(InstanceIds=[instance.id])
```
Now this snippet fails with a deprecation warning:

```
exceptions.PendingDeprecationWarning: Could not find AMI with image-id:foo, in the near future this will cause an error
```
We forbid all deprecation warnings in buildbot code, so we would like to have a new way of doing it which would not trigger the warning.

**Comment by terrycain** [comment]
We've now prepackaged a bunch of image id's and fixed describe_images, if your just after any old image, run [describe_images](https://boto3.readthedocs.io/en/latest/reference/services/ec2.html#EC2.Client.describe_images) and pick one of the results.

**Comment by tardyp** [comment]
@terrycain Sounds good. I'll try that tomorrow. Thanks.
I'd appreciated that explaination in the deprecation message.

**Comment by tardyp** [comment]
@terrycain I just tried that, and now I have another issue.
The ImageLocation of all those images are equal to None.

```
        amis = list(r.images.all())
        for a in amis:
            print(a.image_location)
```
result:
1.1.24: amazon/getting-started
1.1.25: None
