### ISSUE TITLE
Feature request: Make it easier to assert against sent SES emails

### ISSUE THREAD

**Issue by bjmc** [spulec/moto#1392]
As a feature request, it would be nice if the Mock SES backend kept the actual email content in the [`sent_messages`](https://github.com/spulec/moto/blob/master/moto/ses/models.py#L41) list, and made it easy to make assertions against them.

I think two things would be needed:

* The [Message](https://github.com/spulec/moto/blob/master/moto/ses/models.py#L13) class would have to capture actual content of the emails.

* The backend would have to expose those messages somehow so test code could assert against them.

I'm imagining something like

```python
with fake_ses() as mock_ses:
    ... # tests that trigger sending email
    assert 'expected@example.com' in mock_ses.sent_messages[0].recipients
```

**Comment by r1b** [comment]
Hi @bjmc,

You can do this by asserting against the SES backend e.g:

```python
from moto.ses import ses_backend
assert 'expected@example.com' in ses_backend.sent_messages[0].recipients
```

This was not clear to me either :)

**Comment by spulec** [comment]
Going to close this. @r1b 's suggestion is our current best practice.

**Comment by tomviner** [comment]
> @bjmc The SES backend state is available on the SES module, e.g:
> 
> ```python
> from boto.ses import ses_backend
> assert ses_backend.sent_messages[0]
> ```

For future readers, `ses_backend` is available on `moto` not `boto`:
```python
from moto.ses import ses_backend
#    ^^^^
assert ses_backend.sent_messages[0]
```
