### ISSUE TITLE
SNS endpoint parsing issue

### ISSUE THREAD

**Issue by thehesiod** [spulec/moto#1394]
Testing my code recently I noticed that the SNS endpoint was listed as `arn:aws:lambda:us-east-1:123456789012:function:test-function:$LATEST`, however all the code in sns/models.py assumes that `self.endpoint.split(":")[-1]` is the function name.  Need to investigate what's right.

**Comment by thehesiod** [comment]
aha, looks like there can be multiple types of function ARNs: http://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html, will create a PR

**Comment by thehesiod** [comment]
ok, PR created

**Comment by terrycain** [comment]
Ahh yes, theres a whole mess of ARNs, I believe once you publish functions, the $LATEST part gets get to an incrementing number.
