### ISSUE TITLE
dynamodb2 put_item returnvalues all_old return wrong value

### ISSUE THREAD

**Issue by alexanderfanz** [spulec/moto#1404]
I have this code:
```
class Test(unittest.TestCase):
    @mock_dynamodb2
    def test_t1(self):
        self.conn = boto3.resource('dynamodb', region_name=_region_name)
        self.conn.create_table(
            TableName=_table_name,
            KeySchema=[
                {
                    'AttributeName': 'partition_key',
                    'KeyType': 'HASH'
                },
                {
                    'AttributeName': 'sort_key',
                    'KeyType': 'RANGE'
                }
            ],
            AttributeDefinitions=[
                {
                    'AttributeName': 'partition_key',
                    'AttributeType': 'S'
                },
                {
                    'AttributeName': 'sort_key',
                    'AttributeType': 'S'
                },

            ],
            ProvisionedThroughput={
                'ReadCapacityUnits': 1,
                'WriteCapacityUnits': 1
            }
        )

        item = {
            'partition_key': 'test',
            'sort_key': 'test',
            'attr1': 'value1'
        }
        item_new = {
            'partition_key': 'test',
            'sort_key': 'test',
            'attr1': 'value1',
            'attr2': 100
        }

        self.conn.Table(_table_name).put_item(Item=item)

        r = self.conn.Table(_table_name).put_item(Item=item_new, ReturnValues='ALL_OLD')
        print(r)

```

when I run this test, in the terminal should be the value of `item`, but the output is the value of `item_new`

here is the doc http://boto3.readthedocs.io/en/latest/reference/services/dynamodb.html#DynamoDB.Table.put_item

> ReturnValues (string) --
Use ReturnValues if you want to get the item attributes as they appeared before they were updated with the PutItem request. For PutItem , the valid values are:
> NONE - If ReturnValues is not specified, or if its value is NONE , then nothing is returned. (This setting is the default for ReturnValues .)
> ALL_OLD - If PutItem overwrote an attribute name-value pair, then the content of the old item is returned.

Please tell me if there is another way to do this.

**Comment by lloydChris** [comment]
I have experienced this as well.  For additional clarity, in the example above the line:
`self.conn.Table(_table_name).put_item(Item=item)`
will return the value of item.

**Comment by spulec** [comment]
Thanks for opening.

It looks like we don't support `ALL_OLD` for the `put_item` endpoint right now. I'll add this as a feature request.

**Comment by spulec** [comment]
This should be fixed with https://github.com/spulec/moto/pull/1938
