### ISSUE TITLE
open shards should not report a StartingSequenceNumber

### ISSUE THREAD

**Issue by bcavagnolo** [spulec/moto#1405]
I am developing a KCL application and I'm using moto kinesis and moto dynamodb for testing. KCL seemed to be successfully calling `describe-stream` to get the details on the kinesis stream. But it did not invoke my application. After digging around in the KCL source for a while, I discovered the problem. It seems that on `describe-stream` moto returns something like this:

```
{
    "StreamDescription": {
        "KeyId": null, 
        "EncryptionType": null, 
        "StreamStatus": "ACTIVE", 
        "StreamName": "ingress-local-test", 
        "Shards": [
            {
                "ShardId": "shardId-000000000000", 
                "HashKeyRange": {
                    "EndingHashKey": "340282366920938463463374607431768211456", 
                    "StartingHashKey": "0"
                }, 
                "SequenceNumberRange": {
                    "EndingSequenceNumber": 0, 
                    "StartingSequenceNumber": 0
                }
            }
        ], 
        "StreamARN": "arn:aws:kinesis:us-east-1:123456789012:ingress-local-test", 
        "EnhancedMonitoring": null, 
        "StreamCreationTimestamp": null, 
        "RetentionPeriodHours": null
    }
}
```
Because there is both a `EndingSequenceNumber` and `StartingSequenceNumber`, KCL infers that the this shard id closed. This is consistent with the AWS documentation:

http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_streams_DescribeStream.html

...which says:

"Each shard in the stream has a SequenceNumberRange associated with it. If the SequenceNumberRange has a StartingSequenceNumber but no EndingSequenceNumber, then the shard is still open (able to receive more stream records). If both StartingSequenceNumber and EndingSequenceNumber are present, then that shard is closed and can no longer receive more data."

So I think moto should probably not report the StartingSequenceNumber in this case. Indeed I removed that field from the `Shard` model's json and my application progressed.

I considered submitting a PR to simply remove this field. But I wasn't quite sure how this is all meant to interact with the `merge-shards` and `split-shards` behavior.

**Comment by rcoh** [comment]
The correct behavior is actually only returning a `StartingSequenceNumber` -- `EndingSequenceNumber` should only be returned for closed shards

**Comment by bcavagnolo** [comment]
Ah yes. Typo. Sorry. I should have said: "So I think moto should probably not report the EndingSequenceNumber in this case."
