### ISSUE TITLE
EMR list_step responses don't contain start date in output

### ISSUE THREAD

**Issue by ashb** [spulec/moto#1427]
There is a bug in the LIST_STEP_TEMPLATE and other EMR templates around the start date for steps: the conditional looks at `ready_datetime` but then outputs `start_datetime`.

This from https://github.com/spulec/moto/blob/896f040fca975865c1d441d90016446c72db3ed4/moto/emr/responses.py#L794-L796

```
            {% if step.ready_datetime is not none %}
            <StartDateTime>{{ step.start_datetime.isoformat() }}</StartDateTime>
            {% endif %}
```

Nothing in the code looks at `step.ready_datetime` that I could see (use create, start, and end), so I'm guessing the conditional is wrong. This exists in a few other templates too.

**Comment by spulec** [comment]
This looks like it has been fixed.

**Comment by ashb** [comment]
Not sure that it is. The template at least still has the same block in master

https://github.com/spulec/moto/blob/ec3f6bbc6ce1b477efb1ec76ca333f7271ac0c88/moto/emr/responses.py#L838-L840

**Comment by bblommers** [comment]
I agree @ashb - haven't used EMR much, but that looks wonky. Reopening
