### ISSUE TITLE
Recent update to botocore breaks some cloudformationstack tests

### ISSUE THREAD

**Issue by dbfr3qs** [spulec/moto#1436]
Due to a recent update to botocore (1.8.29) cloudformation.get_templates now returns OrderedDicts rather than regular dicts, leading to some cloudformation tests failing.

I've included a fix with this [commit](https://github.com/spulec/moto/pull/1432/commits/7d0733ad1026e8d251e90d82aa4a3afdafbd51b5) in #1432

**Comment by koxudaxi** [comment]
@dbfr3qs 
I just created the pullrequest https://github.com/spulec/moto/pull/1446 to fix the commit https://github.com/spulec/moto/pull/1432/commits/7d0733ad1026e8d251e90d82aa4a3afdafbd51b5
the commit has unneeded comments. 
Could you please check the pullrequest ?
