### ISSUE TITLE
Setting SQS Redrive Policy has no effect

### ISSUE THREAD

**Issue by anderson-dan-w** [spulec/moto#1437]
## Quick Edit
My search skills were lacking; found [does not make dead letter](https://github.com/spulec/moto/issues/675) after already posting. I'd argue this is related but distinct, in that I'd expect some indication that setting `RedrivePolicy` is un-supported in `moto`.

## Originally
Using Anaconda-IPython:
`sys.version[:5] == '2.7.6'`
`moto.__version__ == (u'1.2.0', )  ## installed via pip install moto`
`boto3.__version__ == '1.5.1'`

### Reproduce:
```python
import json
import boto3
from moto import mock_sqs

@mock_sqs
def make_with_deadletter():
    sqs = boto3.resource('sqs', region_name='us-west-2')
    deadletter = sqs.create_queue(QueueName='my-deadletter')
    redrive_policy = {
        'deadLetterTargetArn': deadletter.attributes['QueueArn'],
        'maxReceiveCount': 1
    }

    queue = sqs.create_queue(QueueName='my=queue')
    response = queue.set_attributes(
        Attributes={
            'RedrivePolicy': json.dumps(redrive_policy)
        }
    )
    assert 'RedrivePolicy' in queue.attributes
    return response, queue
```

## Expected Behavior:
Either:
  - `assert` passes successfully, indicating the `RedrivePolicy` is in place, pointing at the deadletter queue `my-deadletter`
    - Dug a little into the [code](https://github.com/spulec/moto/blob/272b4802c379a430b5351b5cd85dded64d137b57/moto/sqs/models.py#L212), and it looks like it *should* be doing this already, not sure what I'm missing.

Or:
  - `queue.set_attributes(...)` fails, or returns non-200 `HTTPStatusCode`, to indicate values weren't set.

## Experienced Behavior:
  - `response` finishes "successfully":
    ```python
    >> print(response)
    {
        'ResponseMetadata': {
            'HTTPHeaders': {
                u'Content-Type': u'text/plain',
                u'server': u'amazon.com',
                u'x-amz-crc32': '293834496',
                u'x-amzn-requestid': u'ISVPJ76Z7G5EG20TP0L2CX3HA5AC338I9V6IJGQINB6U8ES0Y9KG'
            },
           'HTTPStatusCode': 200,
           'RequestId': 'ISVPJ76Z7G5EG20TP0L2CX3HA5AC338I9V6IJGQINB6U8ES0Y9KG',
           'RetryAttempts': 0
        }
    }
    ```
    Note: `HTTPStatusCode == 200`

  - but `queue` does not have `RedrivePolicy` attribute

Notes:
  - Also tried `queue.reload()` after `queue.set_attributes(...)` with the same (failed) result (no `RedrivePolicy`)
  - Also tried `fresh_queue = sqs.get_queue_by_name(QueueName='my-queue')` after `queue.set_attributes(...)` and `fresh_queue.attributes` has same (failed) result (no `RedrivePolicy`)

**Comment by spulec** [comment]
Added with https://github.com/spulec/moto/pull/1439 and the remaining implementation should be done as part of https://github.com/spulec/moto/issues/675
