### ISSUE TITLE
Package version variable is tuple instead of string

### ISSUE THREAD

**Issue by okomestudio** [spulec/moto#1461]
Due to the line ending with comma, `__version__` contains a tuple instead of (more conventional I believe) string with version spec:

https://github.com/spulec/moto/blob/master/moto/__init__.py#L6

Is this intended or a botched regex replacement with bumpversion?

This is only an issue when I want to decide which tests to run or not based on `moto` version.

**Comment by JackDanger** [comment]
Nice catch! I just tested `bumpversion` and it seems to be working fine so this must have been a mistake that I introduced by hand. fixed in #1462 (merged to master)
