### ISSUE TITLE
describe_db_instances() response is missing IAMDatabaseAuthenticationEnabled and DbiResourceId keys

### ISSUE THREAD

**Issue by RealSalmon** [spulec/moto#1465]
moto==1.2.0
boto==2.48.0
boto3==1.5.8
botocore==1.8.22

The response from describe_db_instances() is missing the following keys:
   - DbiResourceId
   - IAMDatabaseAuthenticationEnabled

The following test case will replicate the issue:
```python
import boto3
from moto import mock_rds

@mock_rds
def test_describe_db_instances():
    # Create the database instance
    client = boto3.client('rds')
    client.create_db_instance(
        DBName='best-database-evar',
        DBInstanceIdentifier='best-instance-evar',
        AllocatedStorage=10,
        DBInstanceClass='t2.small',
        Engine='mysql',
        EngineVersion='42',
        MasterUsername='root',
        MasterUserPassword='override all security',
        EnableIAMDatabaseAuthentication=True
    )

    response = client.describe_db_instances(DBInstanceIdentifier='best-instance-evar')
    instance = response['DBInstances'][0]

    assert instance['DBInstanceIdentifier'] == 'best-instance-evar'

    # these keys are missing in the response
    assert 'IAMDatabaseAuthenticationEnabled' in instance
    assert 'DbiResourceId' in instance
```

The expected behavior is that this should pass. Specifically, IAMDatabaseAuthenticationEnabled should be True, and DbiResourceId should at the very least be some randomly generated string (I am not sure what the exact format should be).

The actual behavior is that the last 2 assertions fail because these keys are not in the response as they would be in a real call.

**Comment by usamaSaddiq** [comment]
Hi,

Did you manage to get it to work using the fix?

Cheers

**Comment by spulec** [comment]
Thanks; this should be fixed now.
