### ISSUE TITLE
Downgrade Jinja2 requirement to 2.7.3

### ISSUE THREAD

**Issue by acrewdson** [spulec/moto#1472]
As a result of issue https://github.com/spulec/moto/issues/728, the Jinja2 requirement was bumped to `>=2.8`, even though the missing feature in question, `lstrip_blocks`, was added in Jinja 2.7 ('Added finer grained support for stripping whitespace on the left side of blocks', from  http://jinja.pocoo.org/docs/2.10/changelog/#version-2-7).

I know this might be an unusual request, but I believe that pushing the `Jinja2` requirement in `setup.py` back down to `>=2.7.3` would not break anything, and it would be really helpful to projects that are still on that old version of Jinja2 (to avoid dependency resolution conflicts).

If you'd be willing to consider this, I can make a PR. Thank you.

**Comment by JackDanger** [comment]
I think that’s a very disciplined approach, @acrewdson
A PR would be appreciated!

**Comment by acrewdson** [comment]
@JackDanger sounds good, will do 👍
