### ISSUE TITLE
cloudformation create_change_set fails when Tags are supplied

### ISSUE THREAD

**Issue by benlast** [spulec/moto#1490]
**How to reproduce**:
* Using `moto` 1.2.0, call `create_change_set` and supply the `Tags` kwarg as a list of dicts, each dict holding a `Key` and `Value` (as defined in [the AWS boto3 docs](https://boto3.readthedocs.io/en/latest/reference/services/cloudformation.html#CloudFormation.Client.create_change_set).

[This line] in `moto/cloudformation/responses.py`](https://github.com/spulec/moto/blob/master/moto/cloudformation/responses.py#L90) calls `self._get_list_prefix("Tags.member")` which correctly returns a list of dicts. However, the line in full is `tags = {tag[0]: tag[1] for tag in self._get_list_prefix("Tags.member")}` which appears to be trying to convert a list of tuples to a dict. This fails because the source list for the comprehension is a list of dicts, not tuples.

*Expected behaviour*: it should be possible to pass tags as defined in the `boto3` docs.

**Comment by encee** [comment]
I am seeing the same behavior.

**Comment by spulec** [comment]
Fixed with https://github.com/spulec/moto/commit/a0708a70fcc1b265a25fccb01ec1ca67e409a5ce
