### ISSUE TITLE
dynamodb scan projection expressions do not limit items returned

### ISSUE THREAD

**Issue by ssolari** [spulec/moto#1491]
In a table, "MyTable", with multiple attributes, "attribute1", "attribute2", etc.   The following command should return a list of dictionaries having a single key in each->"attribute1".   However, each dictionary in the return result includes all attributes. 
```
response = dynamodb.scan(TableName="MyTable", ProjectionExpression="attribute1", Select='SPECIFIC_ATTRIBUTES')
```

**Comment by IVIURRAY** [comment]
having the same issue here - I might take a look

**Comment by chris-erickson** [comment]
Seems like this also affects `get_item`: https://github.com/spulec/moto/blob/3a5d857a60c3a2d140ed2c8adfe8dcaf71a4cac8/moto/dynamodb2/models.py#L596

Similar functionality was added to `query` https://github.com/spulec/moto/pull/1176 so perhaps this isn't a huge lift for someone?

**Comment by spulec** [comment]
Thanks for opening; setting this as a feature request to implement in scans too.

**Comment by bblommers** [comment]
Closing this, as query/scan/get_item now all support the projection expression
