### ISSUE TITLE
Direct Access to EC2 Metadata Server?

### ISSUE THREAD

**Issue by josh-padnick** [spulec/moto#1496]
I'm using moto in server mode by invoking it from the command line. I'd like to directly access the EC2 Instance Metadata for an individual EC2 Instance, and I see that Moto internally supports this, but is it possible to access this endpoint via server mode?

In particular, I'd like to be able to something like `curl http://169.254.169.254/<ec2-instance-id>/meta-data/instance-type` and have that automatically return `t2.micro` or the applicable value.

BTW, Moto is an awesome project!

**Comment by spulec** [comment]
Hmmmm. I can't think of a way that this will really make sense and match the AWS APIs. Going to close out, but I'm open to ideas if people have any.
