### ISSUE TITLE
SNS publish enforces subject <100 characters, AWS enforces <=100

### ISSUE THREAD

**Issue by plemahieu** [spulec/moto#1503]
Issue exists on latest moto master branch. Tests were done with moto 1.2.0

Moto's sns publish enforces <100 characters for the subject parameter:

    `botocore.errorfactory.InvalidParameterException: An error occurred (InvalidParameter) when calling the Publish operation: Subject must be less than 100 characters`

This error is raised by moto. And this is correct per AWS docs:

    https://docs.aws.amazon.com/sns/latest/api/API_Publish.html

However, AWS seems to internally enforce <=100 characters for the subject. At 101 characters AWS generates this (vague) error:

    `An error occurred (InvalidParameter) when calling the Publish operation: Invalid parameter: Subject`

AWS itself will create SNS messages with exactly 100 character subjects. For example, AWS Config will truncate the subject length to exactly 100 if the notification subject exceeds 100 characters. We encountered this issue while using moto to unit test code that re-publishes AWS Config SNS messages. Works in production but fails unit test with moto.

I suggest moto be updated to behave like AWS and enforce <= 100. Ideally AWS should update their docs.

**Comment by plemahieu** [comment]
Showed up in unit tests so, I'd say pain was minimal. :)

**Comment by chrisjameslennon** [comment]
yup more than 100 characters in subject generates this error.
