### ISSUE TITLE
Impossible to test Redshift cluster_restored waiters

### ISSUE THREAD

**Issue by ahill-mlft** [spulec/moto#1506]
Let us suppose we have this code:

```
# snap_restorer.py
def restore_snapshot(redshift_client, snapshot_id):
    cluster_identifier = 'temp_' + snapshot_id
    redshift_client.restore_from_cluster_snapshot(
        ClusterIdentifier=cluster_identifier,
        SnapshotIdentifier=snapshot_id,
    )
    redshift_client.get_waiter('cluster_restored').wait(
        ClusterIdentifier=cluster_identifier,
        WaiterConfig={
            'Delay': 1,
            'MaxAttempts': 2,
        }
    )
```

And we wish to test it like so:

```
# test_snap_restorer.py
import boto3
from moto import mock_redshift

from snap_restorer import restore_snapshot

@mock_redshift
def test_restore_snapshot():
    client = boto3.client('redshift', region_name='us-east-1')
    # Make a cluster for a snapshot to associate with
    client.create_cluster(
        ClusterIdentifier='whatever',
        MasterUsername='whoever',
        MasterUserPassword='wh473v3r',
        NodeType='multi-node',
        NumberOfNodes=2,
    )
    # And a snapshot to test with
    client.create_cluster_snapshot(
        SnapshotIdentifier='testsnapshot',
        ClusterIdentifier='whatever',
    )

    restore_snapshot(client, 'testsnapshot')
```

This test will promptly fail thanks to the tight settings for the `WaiterConfig`, but if left at its defaults the test would instead hang for thirty minutes, and then fail.

Moto's Redshift backend will never generate the `RestoreStatus` object that botocore's `ClusterRestored` waiter searches for, so we can't mock out this kind of interaction yet.

**Comment by spulec** [comment]
Yeah, we've struggled in the past with these types of timing-based tests. 

Any thoughts on how you would want it to work? Some API in Moto that allows you to manipulate time forward?

**Comment by ahill-mlft** [comment]
I don't even care so much about simulating time inside moto, at least not right now; I just want to be able to test interactions that happen to include waiters at all.

In this particular case, creating the new mocked cluster with a `RestoreStatus` of `{'Status': 'completed'}` immediately (when created from the `restore_from_cluster_snapshot` method, of course) would satisfy the waiter and allow the test to pass.

**Comment by bpandola** [comment]
@ahill-mlft I added support for your basic use-case in #1597.  Are there other Redshift waiters you'd like to see implemented?
