### ISSUE TITLE
Pre create resources (eg, s3 buckets)

### ISSUE THREAD

**Issue by patrick91** [spulec/moto#1507]
Hi, I've been using moto for mocking s3 responses in tests, I was wondering if there is a way to auto create some s3 buckets so that I don't have to do so manually in the tests.

That would be a great feature for the mock server as well :)

**Comment by mikegrima** [comment]
@patrick91 : We use pytest and fixtures in our tests to pre-create resources. Here is an example: https://github.com/Netflix-Skunkworks/historical/blob/master/historical/tests/conftest.py#L122

Every test that makes use of that fixture gets all those resources created a priori.

**Comment by spulec** [comment]
I'm going to agree with @mikegrima 's suggestion here.

Let us know if that doesn't work for your use case and we can re-examine.
