### ISSUE TITLE
Adding the CloudFormation StackSet endpoints

### ISSUE THREAD

**Issue by svdgraaf** [spulec/moto#1514]
I want to start implementing the CloudFormation StackSet endpoints, as I need those for a project. Is there anything I need to keep in mind when doing this?

**Comment by spulec** [comment]
Nothing in particular. I'll add this issue as a feature request.

We do generally like to have high test coverage so that would be appreciated.

**Comment by corrjo** [comment]
@svdgraaf have you made any progress toward adding stackset support? Let me know if I can be of any help.

**Comment by corrjo** [comment]
@svdgraaf No worries, I'll see if I can carve out some time and add them :)

**Comment by corrjo** [comment]
Finally found some time to do this #2015

**Comment by spulec** [comment]
Closed with https://github.com/spulec/moto/pull/2015
