### ISSUE TITLE
Support ParameterFilters for SSM GetParametersByPath API

### ISSUE THREAD

**Issue by alexcasalboni** [spulec/moto#1517]
Has this functionality been excluded intentionally? or maybe it's been added recently?

API documentation here: https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_GetParametersByPath.html#systemsmanager-GetParametersByPath-request-ParameterFilters

`ParameterStringFilter ` documentation here: https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_ParameterStringFilter.html

**Comment by spulec** [comment]
Nope, just hasn't been added yet. I'll set this as a feature request.

**Comment by alexcasalboni** [comment]
Thanks, @spulec.

I'd love to contribute but I'm not very familiar with the code base. Do you have any hint about a possible implementation?

**Comment by spulec** [comment]
The two main places you will be looking are the [response](https://github.com/spulec/moto/blob/master/moto/ssm/responses.py#L84-L101) and the [model](https://github.com/spulec/moto/blob/master/moto/ssm/models.py#L96-L109).

In the former, you are going to want to parse out the `ParameterFilters` from the request and pass that through. In the latter, you will use those filters to modify which parameters we return.

I generally find it easiest to start by writing some tests and then developing against them. Let me know if we can help or feel free to hop on [Gitter](https://gitter.im/awsmoto/Lobby).

**Comment by craiga** [comment]
If it helps, I've written a small script to demonstrate this problem.

```python
from pprint import pprint

import boto3
import moto


def create_params_describe_params():
    ssm = boto3.client('ssm')

    ssm.put_parameter(Name='aaabbb', Value='As and Bs',
                      Type='String', Overwrite=True)
    ssm.put_parameter(Name='aaaccc', Value='As and Cs',
                      Type='String', Overwrite=True)
    ssm.put_parameter(Name='bbbccc', Value='Bs and Cs',
                      Type='String', Overwrite=True)

    response = ssm.describe_parameters(ParameterFilters=[
        {'Key': 'Name',
         'Option': 'BeginsWith',
         'Values': ['aaa']}])
    return [p['Name'] for p in response['Parameters']]


if __name__ == '__main__':
    print("Without moto:")
    pprint(create_params_describe_params())

    with moto.mock_ssm():
        print("With moto:")
        print(create_params_describe_params())
```

Output:

```
Without moto:
['aaabbb', 'aaaccc']
With moto:
['aaabbb', 'aaaccc', 'bbbccc']
```

The name "bbbccc" shouldn't be returned as it does not start with "aaa".

**Comment by bblommers** [comment]
This was implemented by https://github.com/spulec/moto/pull/2453
