### ISSUE TITLE
Support sfn (step functions)

### ISSUE THREAD

**Issue by tuler** [spulec/moto#1531]
Support for step functions API (sfn)

http://boto3.readthedocs.io/en/latest/reference/services/stepfunctions.html

**Comment by spulec** [comment]
Added as a feature request.

Right now I don't have a particular use for this so I can't promise anything for timing.

If someone does have time, pull requests are much appreciated (even small one just to get a service started). If you have some example code you want to work, preferably with some example data, that can also speed up the process.

**Comment by jblakeney** [comment]
+1

**Comment by spulec** [comment]
Closed with https://github.com/spulec/moto/pull/2409

Feel free to open additional issues for more endpoints.
