### ISSUE TITLE
SSM SendCommand requires 'InstanceIds', which should be optional.

### ISSUE THREAD

**Issue by mliudev** [spulec/moto#1534]
moto version: 1.3.1
botocore: 1.9.15

issue:

I'm getting `KeyError: InstanceIds'` when mocking the following code:

```
                ssm_client.send_command(
                    DocumentName='AWS-RunShellScript',
                    Parameters=ssm_parameters,
                    Targets=[{
                        'Key': 'tag:aws:cloudformation:stack-name',
                        'Values': (session.get_stack_name(), )}])
```

This should be reproducible by calling the `send_command` function as above where no `InstanceIds` parameter is passed.

I've tracked this issue down to this line:
https://github.com/spulec/moto/blob/master/moto/ssm/models.py#L145

InstanceIds are an optional parameter according to the AWS docs here: 
https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_SendCommand.html

Since I'm sending a `Targets` parameter I shouldn't need to include any InstanceIds. I expect the code above to pass it's test.

**Comment by spulec** [comment]
Thanks for opening. This should be fixed now.

**Comment by mliudev** [comment]
Thanks!
