### ISSUE TITLE
Dynamodb filter expression does not support contains

### ISSUE THREAD

**Issue by prachi2295** [spulec/moto#1539]
Below I am providing a python code which puts 3 records in dynamodb out of which 2 should be returned by applying dynamodb filter expression 'contains' but it returns none.

from moto import mock_dynamodb2
import boto3
import sys
from boto3.dynamodb.conditions import Key, Attr

db_attributes = [
    {
        'primary_name': 'Hello',
        'serial_no': 1,
        'filter': 'ABC'
    },
    {
        'primary_name': 'Hello',
        'serial_no': 2,
        'filter': 'ABCD'
    },
    {
        'primary_name': 'Hello',
        'serial_no': 3,
        'filter': 'XYZ'
    }
]

def create_mock_resources():
    dbclient = boto3.client('dynamodb', region_name='us-east-1')
    dbclient.create_table(
        TableName="FilterCheck",
        AttributeDefinitions=[
            {
                'AttributeName': 'primary_name',
                'AttributeType': 'S'
            },
            {
                'AttributeName': 'serial_no',
                'AttributeType': 'N'
            }
        ],
        KeySchema=[
            {
                'AttributeName': 'primary_name',
                'KeyType': 'HASH'
            },
            {
                'AttributeName': 'serial_no',
                'KeyType': 'RANGE'
            }
        ],
        ProvisionedThroughput={
            'ReadCapacityUnits': 2,
            'WriteCapacityUnits': 1
        }
    )

@mock_dynamodb2
def check_filter_expression():
    create_mock_resources()
    dynamo_db = boto3.resource("dynamodb", region_name='us-east-1')
    table = dynamo_db.Table("FilterCheck")
    for item in db_attributes:
        table.put_item(
            Item=item
        )
    response = table.query(
                    KeyConditionExpression=Key('primary_name').eq('Hello') &
                    Key('serial_no').gt(0),
                    FilterExpression=Attr('filter').contains('ABC')
            )
    print(response)

def main_func(argv):
    check_filter_expression()

if __name__ == '__main__':
    exit(main_func(sys.argv[1:]))

**Comment by spulec** [comment]
This should be fixed with #1559
