### ISSUE TITLE
ConnectionError when ussing moto

### ISSUE THREAD

**Issue by key1706** [spulec/moto#1540]
Try running test_push_data_send_success(self):
Here is my traceback:
`..\Api\pushDataSend.py:106: in Execute
    FirebaseServerKey)
..\Api\pushDataSend.py:334: in SendMessage
    timeout=self.Constant.TIMEOUT)
C:\Users\KhuongNHQ\AppData\Local\Programs\Python\Python36-32\lib\site-packages\botocore\vendored\requests\api.py:109: in post
    return request('post', url, data=data, json=json, **kwargs)
C:\Users\KhuongNHQ\AppData\Local\Programs\Python\Python36-32\lib\site-packages\botocore\vendored\requests\api.py:50: in request
    response = session.request(method=method, url=url, **kwargs)
C:\Users\KhuongNHQ\AppData\Local\Programs\Python\Python36-32\lib\site-packages\botocore\vendored\requests\sessions.py:465: in request
    resp = self.send(prep, **send_kwargs)
C:\Users\KhuongNHQ\AppData\Local\Programs\Python\Python36-32\lib\site-packages\botocore\vendored\requests\sessions.py:573: in send
    r = adapter.send(request, **kwargs)
C:\Users\KhuongNHQ\AppData\Local\Programs\Python\Python36-32\lib\site-packages\moto\packages\responses\responses.py:308: in unbound_on_send
    return self._on_request(adapter, request, *a, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <moto.packages.responses.responses.RequestsMock object at 0x03EC67D0>
adapter = <botocore.vendored.requests.adapters.HTTPAdapter object at 0x0560A7F0>
request = <PreparedRequest [POST]>
kwargs = {'cert': None, 'proxies': {}, 'stream': False, 'timeout': 2, ...}
match = None
error_msg = 'Connection refused: POST https://fcm.googleapis.com/fcm/send'
response = ConnectionError('Connection refused: POST https://fcm.googleapis.com/fcm/send',)

    def _on_request(self, adapter, request, **kwargs):
        match = self._find_match(request)
        # TODO(dcramer): find the correct class for this
        if match is None:
            if self.pass_through:
                return self.original_send(adapter, request, **kwargs)
    
            error_msg = 'Connection refused: {0} {1}'.format(request.method,
                                                             request.url)
            response = ConnectionError(error_msg)
            response.request = request
    
            self._calls.add(request, response)
>           raise response
E           requests.exceptions.ConnectionError: Connection refused: POST https://fcm.googleapis.com/fcm/send

C:\Users\KhuongNHQ\AppData\Local\Programs\Python\Python36-32\lib\site-packages\moto\packages\responses\responses.py:250: ConnectionError`

**Comment by key1706** [comment]
@JackDanger please help me

**Comment by spulec** [comment]
It looks like your tests are trying to talk to Google. As of now, we don't allow making requests to other websites while Moto is active.

Feel free to follow along on #1026 for possible solutions going forward.
