### ISSUE TITLE
Implement S3 notification message sending

### ISSUE THREAD

**Issue by TylerFromVT** [spulec/moto#1541]
Not a bug report at this time, more a question of whether a given feature has been implemented. I'm using Moto as part of a smoke test suite to check AWS deployments, verifying, among other things that the proper "connections" are setup.

I've written a test, using Python and Boto3, that creates an S3 bucket, an SQS queue and notification/permissions to send a message to the queue when a file is uploaded to the bucket. The code is setup to work either with Moto or directly to AWS. The test that looks for the message passes when configured to actually work with AWS but no message shows up in the Moto version. 

Would you expect this to pass? Is this kind of "wiring" between components part of Moto? Thanks in advance!

Here is the test that's failing:

`

    def test_that_uploading_file_puts_message_in_queue(self):
        messages = test_utilities.get_messages(self.queue_name)
        self.assertEqual(0, messages.get_number_of_messages());

        bucket_key = "TheGunslinger"
        test_utilities.upload_file(self.bucket_name, bucket_key)
        messages = test_utilities.get_messages(self.queue_name)

        self.assertEqual(1, messages.get_number_of_messages())
        self.assertEqual("ObjectCreated:Put", messages.get_event_name(0))
        self.assertEqual(bucket_key, messages.get_bucket_key(0))

`

**Comment by spulec** [comment]
Thanks for opening the issue. It looks like we support the configuration of S3 notifications, but don't actually implement the message sending right now. I'll set this as a feature request.

**Comment by Syntactical01** [comment]
Could we get a way to hook into this as well? A way to give it a function to call when a notification is entered instead of a mocked lambda (which requires us to zip the code or inline it if its simple). This would be really helpful for simple unit testing with pytest. I understand this may break how moto normally does things but I will leave this comment as food for thought.

**Comment by bblommers** [comment]
With #5007 merged, a first iteration of this is now available as of moto >= 3.1.5.dev7.
We currently only support targets `AWSLambda` and `SQS`, for events `s3:ObjectCreated:Copy` and `s3:ObjectCreated:Put`.

An up-to-date list of what's supported can be found here: http://docs.getmoto.org/en/latest/docs/services/s3.html

@Syntactical01 This implementation does not include any hooks. As a workaround, you should be able to monkeypatch the internal method to achieve this. The source code can be found here:
https://github.com/spulec/moto/blob/ac6d88518d2a5d40bbb13170bfebb8ca0ec38d46/moto/s3/notifications.py#L41

I'll close this for now - feel free to open a new issue/PR if there is a another target or event that you'd like to see support for!
