### ISSUE TITLE
s3.download_file() fails on empty key

### ISSUE THREAD

**Issue by RonRothman** [spulec/moto#1542]
When trying to download an empty (zero-length) key, `s3.download_file()` fails with "ValueError: I/O operation on closed file".  (This appears to be a duplicate of https://github.com/spulec/moto/issues/483, but that issue was closed so I'm not sure how to handle this report.)

Here's a minimal example that demonstrates the failure:

```
import boto3
from moto import mock_s3

mock_s3().start()
s3 = boto3.client('s3')
s3.create_bucket(Bucket='foo')
s3.put_object(Bucket='foo', Key='hello/world.txt', Body='')  # write zero bytes
s3.download_file('foo', 'hello/world.txt', '/tmp/foo')
```

```
Traceback (most recent call last):
  File "/tmp/t.py", line 11, in <module>
    s3.download_file('foo', 'hello/world.txt', '/tmp/foo')
  File "/usr/local/lib/python2.7/dist-packages/boto3/s3/inject.py", line 130, in download_file
    extra_args=ExtraArgs, callback=Callback)
  File "/usr/local/lib/python2.7/dist-packages/boto3/s3/transfer.py", line 307, in download_file
    future.result()
  File "/usr/local/lib/python2.7/dist-packages/s3transfer/futures.py", line 73, in result
    return self._coordinator.result()
  File "/usr/local/lib/python2.7/dist-packages/s3transfer/futures.py", line 233, in result
    raise self._exception
ValueError: I/O operation on closed file
```

Whereas this code does not fail: (the only change is that we're writing one byte to the key, instead of zero bytes)

```
import boto3
from moto import mock_s3

mock_s3().start()
s3 = boto3.client('s3')
s3.create_bucket(Bucket='foo')
s3.put_object(Bucket='foo', Key='hello/world.txt', Body='X')  # write one byte
s3.download_file('foo', 'hello/world.txt', '/tmp/foo')
```

```
> pip freeze | grep -E '(moto|boto3)'
boto3==1.6.17
moto==1.3.1
```

**Comment by Bennyelg** [comment]
I'll take this.

**Comment by DanHanson82** [comment]
I'm having the same issue when streaming from s3 running locally or in a container.  Works fine with boto but ```E           ValueError: I/O operation on closed file
``` when running with moto

**Comment by hevy-CC4477** [comment]
same issue. Any idea, when this was introduced ?

**Comment by rouge8** [comment]
@Bennyelg did you have luck looking into this?

**Comment by joarleymoraes** [comment]
Same issue.

**Comment by bblommers** [comment]
This is fixed on master by now, as I can no longer reproduce the provided test case, so it should work on the latest release (2.2.6).
I'll close this, but let me know if I've missed anything.
