### ISSUE TITLE
Python 3.7 removes `re._pattern_type`

### ISSUE THREAD

**Issue by ewdurbin** [spulec/moto#1546]
Ref: https://github.com/python/cpython/pull/1646

Moto uses `re._pattern_type` in vendored responses library `RequestsMock._has_url_match`, which has been removed/renamed to `re.Pattern` as of Python 3.7.

https://github.com/spulec/moto/blob/4184acc0d27b584a921939fb85467cebf27bb025/moto/packages/responses/responses.py#L221

I've filed a report with the upstream project at https://github.com/getsentry/responses/issues/195

Python `3.7.0b3`
moto `1.3.1`

**Comment by spulec** [comment]
Thanks for opening the issue (and all the other amazing work you do for the python community)!

We recently unvendored `responses` with https://github.com/spulec/moto/pull/1553 so I believe this issue can be closed.
