### ISSUE TITLE
Feature request: AWS Glue Mock

### ISSUE THREAD

**Issue by OElesin** [spulec/moto#1561]
I would like to ask if the maintainers are adding AWS Glue mock. If not all but some of the core APIs.

Thanks in advance

**Comment by spulec** [comment]
As a general rule, new endpoints get added when people that need them have some extra time to add them to Moto.

Right now I don't have a particular use for this so I can't promise anything for timing.

If someone does have time, pull requests are much appreciated (even small one just to get a service started). If you have some example code you want to work, preferably with some example data, that can also speed up the process.

**Comment by chayac** [comment]
Has any work been done on this? I'm interested in contributing, but wanted to make sure someone else isn't already ahead of me.

**Comment by TheDooner64** [comment]
@chayac @OElesin I just opened a PR #1750 with some initial work on the AWS Glue mock. I am focused on the Glue Data Catalog, so not sure if that aligns with your own use cases

**Comment by spulec** [comment]
Going to close this for now given #1750. Feel free to open feature requests for specific endpoints.
