### ISSUE TITLE
Update to readme/docs to include endpoints that are mocked

### ISSUE THREAD

**Issue by stevenmwade** [spulec/moto#1570]
There does not seem to be a list of what it means when something has `core endpoints done`. It would be great to actually have a list of the functions that are mocked. Working with the s3 mock, it does not seem that `download_fileobj` is actually mocked, though it does not fail.

**Comment by JackDanger** [comment]
@stevenmwade The full list of what's implemented is here: https://github.com/spulec/moto/blob/master/IMPLEMENTATION_COVERAGE.md

I believe `download_fileobj` is just a helper method wrapping up the `.get()` method on an S3 object. Moto implements the latter so `download_fileobj` works as well.

**Comment by stevenmwade** [comment]
@JackDanger It would be great to have a link to that on the README, but also that seems to be pretty out of date as not even `put_object` is listed as complete.

Though if `download_fileobj` is complete, there must be something wrong because it is only downloading an empty file (returns `b''`), but has 187 bytes.
