### ISSUE TITLE
SQS messages don't contain MessageGroupId

### ISSUE THREAD

**Issue by DHager** [spulec/moto#1578]
My use-case involves a simple FIFO queue, where the MessageGroupId isn't only an instruction to SQS, but also contains some data that the consumer is also interested in accessing later. (Note that this is *not* the same kind of "attribute" as the user-land ones using `MessageAttributes`)

### Reproduction script

```python
from moto import mock_sqs
import boto3

with mock_sqs():
    queue = boto3.resource('sqs').create_queue(
        QueueName="test_queue",
        Attributes={
            'FifoQueue ': 'true',
            'ContentBasedDeduplication': 'false'
        }
    )

    queue.send_message(
        MessageBody="{}",
        MessageDeduplicationId="DDID-1",
        MessageGroupId="GID-1",
    )

    messages = queue.receive_messages(
        AttributeNames=['MessageGroupId'],
        MaxNumberOfMessages=10,
        VisibilityTimeout=10,
        WaitTimeSeconds=0,
    )

    msg = messages[0]
    mgid = msg.attributes['MessageGroupId']
    assert "GID-1" == mgid
    
```

Fails with:

```
Traceback (most recent call last):
  File "test.py", line 27, in <module>
    mgid = msg.attributes['MessageGroupId']
KeyError: 'MessageGroupId'
```

### Next steps 

I plan to start a PR later which will at least allow the data to flow from producer to consumer.  

I am not familiar with the moto codebase, but my initial scan of the code suggests changes would be necessary to:

* Inside `moto.sqs.models.SQSBackend#send_message` pull the data out with `self._get_param('MessageGroupId')`
* Store the value as a property of `moto.sqs.models.Message`
* Put in an XML `<Attribute>` block in `moto.sqs.responses.RECEIVE_MESSAGE_RESPONSE` that emits the value from the mode.

I expect the main issues will involve the extent to which the attribute should only be allowed or appear on certain queue-types.

### Out of scope

Will not implement actually using the `MessageGroupId` for selectively ordering messages -- that's a much bigger problem and may be related to work needed for #1438.

**Comment by spulec** [comment]
Closed with #1580

**Comment by azhadsyed** [comment]
I noticed in "out of scope":

> Will not implement actually using the MessageGroupId for selectively ordering messages

Do you know if this is being tracked? I didn't see it but just checking.

**Comment by bblommers** [comment]
@azhadsyed Moto does have logic to ensure only one message per group is processed simultaneously - is that what you're referring to? https://github.com/getmoto/moto/blob/4ed8b93e182891763d23aa6fe6cacf7e0205a509/moto/sqs/models.py#L916

If there is any other logic still missing, you can just create an new issue for this - that is the only way we track feature requests.

**Comment by azhadsyed** [comment]
I'm seeing some behavior where Moto isn't exposing messages within the same group in a FIFO manner (e.g. given messages 1, 2, 3, published in that order, message 3 is visible before message 2) ...but either way, I will follow the issue process, thanks for the help!
