### ISSUE TITLE
Enhancement Request - Please add support for Trusted Advisor. 

### ISSUE THREAD

**Issue by pmsharsha84** [spulec/moto#1583]
Is there is any chance of adding support for Trusted Advisor in near future?

## Reporting Bugs

Please be aware of the following things when filing bug reports:

1. Avoid raising duplicate issues. *Please* use the GitHub issue search feature
   to check whether your bug report or feature request has been mentioned in
   the past.
2. When filing bug reports about exceptions or tracebacks, please include the
   *complete* traceback. Partial tracebacks, or just the exception text, are
   not helpful.
3. Make sure you provide a suitable amount of information to work with. This
   means you should provide:

   - Guidance on **how to reproduce the issue**. Ideally, this should be a
     *small* code sample that can be run immediately by the maintainers.
     Failing that, let us know what you're doing, how often it happens, what
     environment you're using, etc. Be thorough: it prevents us needing to ask
     further questions.
   - Tell us **what you expected to happen**. When we run your example code,
     what are we expecting to happen? What does "success" look like for your
     code?
   - Tell us **what actually happens**. It's not helpful for you to say "it
     doesn't work" or "it fails". Tell us *how* it fails: do you get an
     exception? A hang? How was the actual result different from your expected
     result?
   - Tell us **what version of Moto you're using**, and
     **how you installed it**. Tell us whether you're using standalone server
     mode or the Python mocks. If you are using the Python mocks, include the
     version of boto/boto3/botocore.

   If you do not provide all of these things, it will take us much longer to
   fix your problem.

**Comment by spulec** [comment]
As a general rule, new endpoints get added when people that need them have some extra time to add them to Moto.

Right now I don't have a particular use for this so I can't promise anything for timing.

If someone does have time, pull requests are much appreciated (even small one just to get a service started). If you have some example code you want to work, preferably with some example data, that can also speed up the process.

I'm going to mark this as a feature request.

**Comment by bblommers** [comment]
The `support` service is now available as of moto >= 2.x!
Will close this, but let us know if you're still missing a specific feature/method in the service.
