### ISSUE TITLE
Cannot create Lambda function in Localstack via Serverless

### ISSUE THREAD

**Issue by albegali** [spulec/moto#1588]
`moto` may not build the ARN correctly on the CloudFormation output XML.
Exemple: (see: temyers/serverless-localstack#24 (comment))

```
<DescribeStacksResponse>
  <DescribeStacksResult>
   <Stacks>
     <member>
       <Outputs>
         <member>
           <OutputKey>HelloLambdaFunctionQualifiedArn</OutputKey>
           <OutputValue><moto.awslambda.models.LambdaVersion object at 0x7f82f8363090></OutputValue>
         </member>
         <member>
           <OutputKey>ServiceEndpoint</OutputKey>
           <OutputValue>https://<moto.apigateway.models.RestAPI object at 0x7f82f8363c10>.execute-api.us-east-1.amazonaws.com/local</OutputValue>
         </member>
       </Outputs>
     </member>
   </Stacks>
 </DescribeStacksResult>
</DescribeStacksResponse>
```

(some members were suppressed on this sample above)

I guess that `<moto.awslambda.models.LambdaVersion object at 0x7f82f8363090>` should had been coerced to its ARN, and <moto.apigateway.models.RestAPI object at 0x7f82f8363c10> to its URL.

(refs: https://github.com/localstack/localstack/issues/711)

**Comment by johnbarry343** [comment]
@alanjds Did you end up making a fork for this?

**Comment by alanjds** [comment]
No. Forked only localstack/localstack#759. The described patch here was not properly "coded" anywhere but on my virtualenv on my machine.

**Comment by alanjds** [comment]
@johnbarry343 Done: PR https://github.com/spulec/moto/pull/1643

**Comment by spulec** [comment]
Fixed with https://github.com/spulec/moto/pull/1643

**Comment by alanjds** [comment]
Just noticed: Maybe `moto.apigateway.models.RestAPI` needs a new `__repr__` too:

```xml
<member>
   <OutputKey>ServiceEndpoint</OutputKey>
   <OutputValue>https://<moto.apigateway.models.RestAPI object at 0x7f82f8363c10>.execute-api.us-east-1.amazonaws.com/local</OutputValue>
</member>
```
@albegali: Should reopen?

**Comment by spulec** [comment]
I just pushed https://github.com/spulec/moto/commit/7951eeddc365130c9606718dc665ad4f944d4687 which should fix that. Let me know if you are still seeing issues.

**Comment by alanjds** [comment]
Thanks @spulec
