### ISSUE TITLE
Appsync implementation plans

### ISSUE THREAD

**Issue by iartarisi** [spulec/moto#1629]
Hi, I'm wondering about the plans for implementing appsync support. Looking at the [IMPLEMENTATION COVERAGE](https://github.com/spulec/moto/blob/cb364eedc6e4edcfa3c65f152c7d13f1e5fe2ea4/IMPLEMENTATION_COVERAGE.md#appsync---0-implemented), it seems that only "admin" endpoints are planned. But what about implementing a mock API for queries, mutations and subscriptions? I think this should be doable with plain HTTP for queries/mutations and websockets for subscriptions.

So what's the reason for not including Query/Mutation/Subscription support in that plan?

**Comment by spulec** [comment]
Any work on Appsync would be great.

It isn't a priority of mine right now, but I'd be happy to accept a PR from anyone that has some time. I'm going to mark this as a feature request.
