### ISSUE TITLE
IoT does not work in server mode

### ISSUE THREAD

**Issue by brianrower** [spulec/moto#1631]
**Versions:** 
moto 1.3.3
awscli 1.15.14
python 3.6.1

**How to reproduce:**
```
pip install moto
pip install moto[server]
moto server iot
aws --endpoint-url http://localhost:5000 iot create-thing --thing-name testing

```

The create thing request results in a 404:
```
An error occurred (404) when calling the CreateThing operation: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>

```
This occurs for all iot and iot-data endpoints.

**Possible Resolution:**
The code seems to be implemented, but the url paths are not defined in  Adding the URL's seems to solve the routing issues, I've done this in the branch [here](https://github.com/spulec/moto/compare/master...brianrower:feature/fix-iot-server)

**Problems:**
BUT, for the device shadow API to work (which is iot-data) you have to call create-thing, which is an iot api call. I'm unclear how to run iot and iot-data in the same process to enable this.
The work around I came up with is:

- modify your hosts file to point iot.us-west-2.amazonaws.com and data.iot.us-west-2.amazonaws.com to localhost
- run "moto server" with no parameters
- aws --endpoint-url http://iot.region.amazonaws.com:5000 iot create-thing --thing-name testing
- aws --endpoint-url http://data.iot.us-west-2.amazonaws.com:5000 iot-data update-thing-shadow --thing-name testing --payload '{"state": { "desired": {"testing":true}}}' testing

The workaround succeeds because "get_backend_for_host" in server.py lookups up which service to call based on the domain name and allows both iot and iot-data to be hit in the same process.
Is this the preferred method of interacting wtih moto standalone server? If so I'll add documentation to instruct users in this way. If not, what other way is there?

**Comment by brianrower** [comment]
Also, how do I run the iot unit tests? they fail for me even on master.

**Comment by spulec** [comment]
Yeah, I generally think running `moto server` without parameters is the easiest way to go.

How are you running the tests? In server mode?

**Comment by brianrower** [comment]
Yes, I'm running tests with moto in server mode.
I was trying to use localstack, but since this doesn't work in moto it doesn't work in localstack either :-)
Thoughts on documenting the hosts file workaround mentioned above? or other suggestions?

**Comment by spulec** [comment]
Ah, it actually looks like this is a known issue: https://github.com/spulec/moto/blob/master/Makefile#L4-L5

**Comment by realshadow** [comment]
Hey @spulec ,

what is the status of this? Every operation I try hits 404 in server mode or in docker container. The hosts workaround doesnt work as well. 

Versions:
moto: 1.3.13
awscli: 2.0.19
python: 3.8.3

**Comment by spulec** [comment]
From my knowledge, we have never had IoT working in server mode. Someone would have to implement the auth logic (or a workaround) to make that work.
