### ISSUE TITLE
Implementation coverage should be written to file

### ISSUE THREAD

**Issue by sthuber90** [spulec/moto#1633]
### Actual
The `implementation_coverage.py` script prints the newly calculated coverage to the console

### Expected
The `implementation_coverage.py` script should update the `IMPLEMENTAITON_COVERAGE.md`

**Comment by spulec** [comment]
It looks like this is handled by the Makefile: https://github.com/spulec/moto/blob/master/Makefile#L43-L45

Let me know if I am missing something though.

**Comment by sthuber90** [comment]
I may be missing something, but to me it doesn't look like the `implementation_coverage` from the make file is called during a travis build, but only when moto/scripts/bump_version is called. For me this changes I made in the pull request regarding this issue make sense to me. Still I may be missing something

**Comment by spulec** [comment]
We only intend to run the script when we bump versions. If it ran on Travis, it wouldn't have a way to push the results back to Github.

Apologies if I'm not understanding your request.

**Comment by sthuber90** [comment]
To me it just seemed odd that the `implementation_coverage` script does not write into the `IMPLEMENTATION_COVERAGE.md` itself or that the script provides a flag to be able to either print the coverage result to the console or write it to the file or even do both. Does that makes sense? If the change I made in the pull request is fine for you than that's all there is to it  😃

**Comment by spulec** [comment]
Okay. I don't have strong feelings either way.

Can you change the Makefile so it will work with this new script?

**Comment by sthuber90** [comment]
Sure will look into it
