### ISSUE TITLE
mock_s3 gives "ConnectionError: Connection refused..." error when Key used in put_object call contains leading forward slash

### ISSUE THREAD

**Issue by jwldev2014** [spulec/moto#1637]
This is very specific situation, however the behavior of moto in this situation doesn't match what happens when you use the actual boto3 connecting to AWS.

The situation is if you have a Key for a S3 object that you are putting into a S3 bucket that has a leading forward slash ("/").

So if your Key is "/abc" and you try putting an object into a S3 bucket with the key as follows:

```
def do_something():
  my_bucket = boto3.resource('s3', region_name='us-west-2').Bucket('my_bucket')
  my_bucket.put_object(Key='/abc', Body='ABCD')
```

If you run this snippet of code (along with required imports and so on), then an object with the key "/abc" will be placed in the bucket with the content specified.

When you view this on the AWS Console, it will seem a bit strange because at the "root" level of the S3 bucket, you'll find a "folder" with no name. Upon clicking this no-named folder, you'll see an object named "abc" with the content specified. So this is the expected behavior when boto3 is being used without moto.

When moto is used in a similar situation, lets say as follows:

```
@moto_s3
def do_something_moto()
  conn = botot3.resource('s3', region_name='us-west-2')
  conn.create_bucket(Bucket='my_bucket')
  bucket.put_object(Key='/abc', Body='ABCD')
```

If you run this code, you will get an error with a traceback ending with:

`ConnectionError: Connection refused: PUT https://foobar.s3.us-west-2.amazonaws.com//abc`

If you remove the leading forward slash from the Key in the put_object call:

`bucket.put_object(Key='abc', Body='ABCD')`

Then this code will run without an error. As pointed out above when using the boto3 without moto, a Key with a leading forward slash is a valid key and should not cause an error. This is really an edge case, but I think moto should be made to handle this situation correctly.

As for versions of boto3 and moto being used:
boto3: 1.7.19
moto: 1.3.3

**Comment by spulec** [comment]
Thanks for opening. Agree this is a bug and going to set it as such.

**Comment by mikegrima** [comment]
Debugging this -- I'm thinking the issue is related to the S3 regex.

**Comment by alikoneko** [comment]
I was recently burned by this. I couldn't modify my tests to not use the leading slash. Our leading slash was caused by a pre-fix var being set to an empty string, I did the reasonable thing, and wrapped setting of the key in a conditional to drop the prefix if its not set.

**Comment by RDProjekt** [comment]
I believe there are two problems that need to be solved here.

One is lack of the proper regexp for paths with leading two slashes in `url_paths`. Fixing this makes the code from the original report work, but not in the server mode.

Unfortunately there's also a bug in Werkzeug, which is used by moto for server mode, that prevents proper handling of paths with multiple leading slashes, see [here](https://github.com/pallets/werkzeug/pull/1286#issuecomment-383943350).

I think I have the fix for the first problem, but the tests verifying it need to be skipped in server mode as they are obviously still failing there. Should I create the PR for this or wait till Werkzeug is fixed first?

**Comment by spulec** [comment]
A PR for the first problem would be great until Werkzeug solves the second problem.
