### ISSUE TITLE
SSM backend doesn't support specifying version in get_parameter.

### ISSUE THREAD

**Issue by revotus** [spulec/moto#1638]
SSM backend currently does support specifying a version for "get_parameter" and related methods.

Reproduce:

import boto3
from moto import mock_ssm

@mock_ssm
def test_get_version():
    client = boto3.client('ssm', region_name='us-east-1')
    client.put_parameter({'Name': 'namey', 'Type': 'String', 'Value': 'valley'})
    client.put_parameter({'Name': 'namey', 'Type': 'String', 'Value': 'Sally'})
    client.get_parameter({'Name': 'namey:1'})

Error response:

botocore.errorfactory.ParameterNotFound: An error occurred (ParameterNotFound) when calling the GetParameter operation: Parameter /namey:1 not found.

Expected:

{'Parameter':
    {'Name': 'namey', 'Type': 'String', 'Value': 'valley', 'Version': 1}
}

Possible Fix:

Changing self._parameters to take lists for each parameter. Append each new version. Check for versioned parameter name, search through the list for the parameter name and find the one with the matching version. If not found, raise ParameterVersionNotFound error.
This would also be a necessary first step to implementing the "get_parameter_history" method.

**Comment by spulec** [comment]
Thanks for opening. Going to set this as a feature request.

**Comment by bblommers** [comment]
With the associated PR in place, this should be supported as of moto >= 1.3.16.
Will close this - do let us know if there is still something missing.
