### ISSUE TITLE
Dynamodb2 table query to support QueryFilter

### ISSUE THREAD

**Issue by nadersoliman** [spulec/moto#164]
A feature request for Dynamodb2 table to support QueryFilter

Thanks,

**Comment by im-auld** [comment]
@spulec What part of the code would need to be patched to make QueryFilters work? I'll see if I can get it working.

**Comment by spulec** [comment]
https://github.com/spulec/moto/blob/master/moto/dynamodb2/models.py#L281

**Comment by im-auld** [comment]
Added a bug fix for this issue, tests are passing: https://travis-ci.org/spulec/moto/builds/224523178
