### ISSUE TITLE
boto3.client('events').describe_event_bus()['Policy'] should be JSON string, not dict

### ISSUE THREAD

**Issue by cpitchford** [spulec/moto#1640]
Affects version 1.3.3 of Moto, with botocore 1.10.5, installed using pip using with python 2.7.14 and python mocks.

http://boto3.readthedocs.io/en/latest/reference/services/events.html#CloudWatchEvents.Client.describe_event_bus

This code shows the difference between a call to AWS and a call through Moto:
[moto_events_returns_dict_not_json_string.zip](https://github.com/spulec/moto/files/2005709/moto_events_returns_dict_not_json_string.zip)

    Real bus policy returned as <type 'unicode'>
    Mock bus policy returned as <type 'dict'>

One liner that should not fail:

    json.load(boto3.clients('events').describe_event_bus()['Policy'])

**Comment by cpitchford** [comment]
I hope I've submitted a fix in this PR, wrapping the policy with a json.dumps()

https://github.com/spulec/moto/pull/1639

**Comment by spulec** [comment]
Closed with https://github.com/spulec/moto/pull/1639
