### ISSUE TITLE
events.put_permission requires incorrect Action parameter, should require fully qualified events:PutEvents value

### ISSUE THREAD

**Issue by cpitchford** [spulec/moto#1642]
Affects version 1.3.3 of Moto, with botocore 1.10.5, installed using pip using with python 2.7.14 and python mocks.

As per http://boto3.readthedocs.io/en/latest/reference/services/events.html#CloudWatchEvents.Client.put_permission

The Action parameter for put_permission should be fully qualified as "events:PutEvents". "PutEvents" should not be accepted.

    import boto3
    from moto import mock_events
    
    mock = mock_events()
    mock.start()
    
    moto_events = boto3.client('events')
    mock_bus_policy_json = moto_events.describe_event_bus()['Policy']

    # This should fail, but is accepted
    moto_events.put_permission(
        Action="PutEvents",
        StatementId="testing",
        Principal="123456789012")
    
    # This should work but is rejected:
    moto_events.put_permission(
        Action="events:PutEvents",
        StatementId="testing",
        Principal="123456789012")
    
    botocore.exceptions.ClientError: An error occurred (InvalidParameterValue) when calling the PutPermission operation: Action must be PutEvents

This is hopefully fixed in PR: https://github.com/spulec/moto/pull/1641

**Comment by spulec** [comment]
Closed with https://github.com/spulec/moto/pull/1641
