### ISSUE TITLE
Support TagSpecifications in SpotFleetLaunchSpec

### ISSUE THREAD

**Issue by mattmb** [spulec/moto#1644]
Spot Fleets now support tags which come in the form of TagSpecifications in the LaunchSpecifications

moto seems to support making a request with a TagSpecification but it does not return them on a ```describe_spot_fleet_requests()``` Here's some places I guess we need to change:

https://github.com/spulec/moto/blob/master/moto/ec2/models.py#L2959
https://github.com/spulec/moto/blob/master/moto/ec2/responses/spot_fleets.py#L88

**Comment by spulec** [comment]
Thanks; added as a feature request.

**Comment by drmorr0** [comment]
I think we can close this now?
