### ISSUE TITLE
ARN returned by autoscaling.describe_launch_configuration has new line and whitespace

### ISSUE THREAD

**Issue by cpitchford** [spulec/moto#1646]
Affects version 1.3.3 of Moto, with botocore 1.10.5, installed using pip using with python 2.7.14 and python mocks.

The statement that defines LaunchConfigurationARN had a newline and whitespace prefix

The ARN reported in describe_launch_configurations has this newline and white space.
Arns should not have whitespace or newlines!

    import boto3,json
    from moto import mock_autoscaling
    from six import string_types
    
    
    
    mock = mock_autoscaling()
    mock.start()
    
    moto_autoscaling = boto3.client('autoscaling')
    
    moto_lc = moto_autoscaling.create_launch_configuration(
        LaunchConfigurationName="test-lc",
        ImageId="ami-12345678",
        SecurityGroups=["sg-12345678"]
    )
    
    arn = moto_autoscaling.describe_launch_configurations(LaunchConfigurationNames=["test-lc"])['LaunchConfigurations'][0]['LaunchConfigurationARN']
    
    print arn
    if ' ' in arn:
      print "Has spaces"
    
    if '\n' in arn:
      print "Has newline"
      
    

This code returns:

    arn:aws:autoscaling:us-east-1:803981987763:launchConfiguration:
              9dbbbf87-6141-428a-a409-0752edbe6cad:launchConfigurationName/test-lc
    Has spaces
    Has newline

what me would expect to see:

    arn:aws:autoscaling:us-east-1:803981987763:launchConfiguration:9dbbbf87-6141-428a-a409-0752edbe6cad:launchConfigurationName/test-lc

**Comment by cpitchford** [comment]
Similarly, this also affects AutoScalingGroupARN with whitespace and newline that leaks into describe_auto_scaling_groups

**Comment by spulec** [comment]
Fixed with https://github.com/spulec/moto/pull/1645
