### ISSUE TITLE
No result using cointains in filter when scanning dynamodb2

### ISSUE THREAD

**Issue by martinhyldgaard** [spulec/moto#1648]
Trying to write some tests, I ran into a problem using contains for filtering. This small example run with pytest illustrates the problem:
```
import boto3
import moto
from contextlib import contextmanager
import uuid
from boto3.dynamodb.conditions import Attr
import os

os.environ['AWS_DEFAULT_REGION'] = 'eu-central-1'
TXNS_TABLE = 'TestTable'
@contextmanager
def do_test_setup():
    with moto.mock_dynamodb2():
        set_up_dynamodb()
        yield

def set_up_dynamodb():
    client = boto3.client('dynamodb')
    client.create_table(
        AttributeDefinitions=[
            {
                'AttributeName': 'id',
                'AttributeType': 'S'
            },
        ],
        KeySchema=[
            {
                'AttributeName': 'id',
                'KeyType': 'HASH'
            }
        ],
        TableName=TXNS_TABLE,
        ProvisionedThroughput={
            'ReadCapacityUnits': 10,
            'WriteCapacityUnits': 1
        }
    )


def test_moto():
    with do_test_setup():
        print('boto3 version: ' + boto3.__version__)
        print('moto version: ' + moto.__version__)
        table = boto3.resource('dynamodb').Table(TXNS_TABLE)
        id = str(uuid.uuid1())
        table.put_item(Item={'id': id, 'list': ['a', 'b']})
        idFilter = Attr('id').eq(id)

        found = table.scan(
            FilterExpression=idFilter
        )
        assert len(found['Items']) == 1

        listFilter = Attr('list').contains('b')
        found = table.scan(
            FilterExpression=listFilter
        )
        assert len(found['Items']) == 1

```

The first assert, on the scan using idFilter is successful. The second assert, on the scan using listFilter fails. The length of Items is 0, where I expect 1.
Both asserts succeed if I run the code against an empty table in AWS.
I use boto3 version: 1.7.22 and moto version: 1.3.3. Installation has been done through PyCharm

**Comment by martinhyldgaard** [comment]
Looking around it seems related to #1539, but that seems to be fixed by #1559 on April 13. 1.3.3 should include the fix since it is from April 19.

**Comment by spulec** [comment]
Yeah, it looks like this is still an issue. Marking it as a bug.

**Comment by dplore** [comment]
I am also seeing this behavior on python3 boto3 version 1.7.64

**Comment by francoisesy** [comment]
Hi,
I have a similiar issue: no results when using 'contains' or 'equal' filters on list fields.  Is there any plans for this to be fixed soon?
Below the examples using unittest that illustrate the problem:
`import unittest
import boto3
from moto import mock_dynamodb2
from boto3.dynamodb.conditions import Attr


class TestDynamo(unittest.TestCase):
    @mock_dynamodb2
    def test_filter_contains(self):
        dynamodb = boto3.resource('dynamodb', 'ap-southeast-2')
        dynamodb.create_table(
            TableName='Items',
            KeySchema=[
                {
                    'AttributeName': 'id',
                    'KeyType': 'HASH'  # Partition key
                },
            ],
            AttributeDefinitions=[
                {
                    'AttributeName': 'id',
                    'AttributeType': 'S'
                },
            ],
            ProvisionedThroughput={
                'ReadCapacityUnits': 5,
                'WriteCapacityUnits': 5
            }
        )
        table = dynamodb.Table('Items')

        item = {
            'id': 'F86C2327-F563-4C67-95DC21EBE6BCB87E',
            'extensionList': [
                'pdf'
            ],
        }
        table.put_item(Item=item)

        response = table.scan(
            FilterExpression=Attr('extensionList').contains('pdf'),
        )
        assert len(response['Items']) == 1

    @mock_dynamodb2
    def test_filter_equal(self):
        dynamodb = boto3.resource('dynamodb', 'ap-southeast-2')
        dynamodb.create_table(
            TableName='Items',
            KeySchema=[
                {
                    'AttributeName': 'id',
                    'KeyType': 'HASH'  # Partition key
                },
            ],
            AttributeDefinitions=[
                {
                    'AttributeName': 'id',
                    'AttributeType': 'S'
                },
            ],
            ProvisionedThroughput={
                'ReadCapacityUnits': 5,
                'WriteCapacityUnits': 5
            }
        )
        table = dynamodb.Table('Items')

        item = {
            'id': 'F86C2327-F563-4C67-95DC21EBE6BCB87E',
            'extensionList': [
                'pdf'
            ],
        }
        table.put_item(Item=item)

        response = table.scan(
            FilterExpression=Attr('extensionList').eq(['pdf']),
        )
        assert len(response['Items']) == 1
`
I'm using moto v1.3.8 and boto3 1.9.145.

**Comment by francoisesy** [comment]
Hi,
I have a similiar issue: no results when using 'contains' or 'equal' filters on list fields. Is there any plans for this to be fixed soon?
I'm using moto v1.3.8 and boto3 1.9.145. Below the examples using unittest that illustrate the problem:
```import unittest
import boto3
from moto import mock_dynamodb2
from boto3.dynamodb.conditions import Attr


class TestDynamo(unittest.TestCase):
    @mock_dynamodb2
    def test_filter_contains(self):
        dynamodb = boto3.resource('dynamodb', 'ap-southeast-2')
        dynamodb.create_table(
            TableName='Items',
            KeySchema=[
                {
                    'AttributeName': 'id',
                    'KeyType': 'HASH'  # Partition key
                },
            ],
            AttributeDefinitions=[
                {
                    'AttributeName': 'id',
                    'AttributeType': 'S'
                },
            ],
            ProvisionedThroughput={
                'ReadCapacityUnits': 5,
                'WriteCapacityUnits': 5
            }
        )
        table = dynamodb.Table('Items')

        item = {
            'id': 'F86C2327-F563-4C67-95DC21EBE6BCB87E',
            'extensionList': [
                'pdf'
            ],
        }
        table.put_item(Item=item)

        response = table.scan(
            FilterExpression=Attr('extensionList').contains('pdf'),
        )
        assert len(response['Items']) == 1
```
Results in: ` AssertionError: assert 0 == 1`
I have the same result when using equal filter as below:
```response = table.scan(
            FilterExpression=Attr('extensionList').eq(['pdf']),
        )
        assert len(response['Items']) == 1```

**Comment by ericowlie** [comment]
I'm getting this issue too, so +1

**Comment by bblommers** [comment]
Contains is now supported in the [latest version](https://pypi.org/project/moto/#history), and both test cases now pass for me. (Not sure at what point/with which PR this feature was implemented...)
Going to close this - feel free to open a new issue if there's still a problem
