### ISSUE TITLE
ECS/run_task should default attributes from task_definition

### ISSUE THREAD

**Issue by adamdavis40208** [spulec/moto#1660]
`def run_task(self, cluster_str, task_definition_str, count, overrides, started_by):`
`>       cluster_name = cluster_str.split('/')[-1]`
`E       AttributeError: 'NoneType' object has no attribute 'split'`

http://boto3.readthedocs.io/en/latest/reference/services/ecs.html#ECS.Client.run_task

According to this definition, only task_definition is required.

**Comment by spulec** [comment]
Thanks for opening; this will take some work to fix.

We'll need to add the ability to fallback to reading the cluster (and other attributes) from the task_definition. I'm going to set this as a feature request.

**Comment by bblommers** [comment]
As far as I can tell, this was fixed with #2876. Will close this, but do let us know if there's anything still missing in the latest version.
