### ISSUE TITLE
The UserId parameter for ModifySnapshotAttribute has not been implemented in Moto yet.

### ISSUE THREAD

**Issue by jofwar** [spulec/moto#1662]
Version: moto 1.3.3

using mock_ec2 to test successful permission updates on a snapshot.

thanks!

**Comment by spulec** [comment]
Thanks for opening; setting as a feature request.

**Comment by bpandola** [comment]
Looks like this was implemented in #3178 and is available in moto >= 1.3.15.dev1016

**Comment by bblommers** [comment]
Correct @bpandola - will close this. Let me know if I've missed anything @jofwar
