### ISSUE TITLE
SQS: Create Queue Does not Raise Error With Different Attributes

### ISSUE THREAD

**Issue by NelsonScott** [spulec/moto#1663]
Expected Behavior:
Using an SQS resource, calling `create_queue` with attributes that do not match the existing queue's attributes should raise an error `QueueNameExists`

http://boto3.readthedocs.io/en/latest/reference/services/sqs.html#SQS.ServiceResource.create_queue

> If the queue name, attribute names, or attribute values don't match an existing queue, CreateQueue returns an error.

Actual Behavior:
Queue is returned with its existing attributes.  Attributes are not updated and error is not raised.  

Steps to Reproduce:
```python
In [2]: from moto import mock_sqs

In [3]: mock_sqs().start()

In [4]: import boto3

In [5]: resource = boto3.resource('sqs', region_name='us-east-1')

In [6]: resource.create_queue(QueueName="test-q-1")
Out[6]: sqs.Queue(url='https://queue.amazonaws.com/123456789012/test-q-1')

In [7]: q = _

In [8]: q.attributes
Out[8]: 
{'ApproximateNumberOfMessages': '0',
 'ApproximateNumberOfMessagesDelayed': '0',
 'ApproximateNumberOfMessagesNotVisible': '0',
 'CreatedTimestamp': '1527802340.44',
 'DelaySeconds': '0',
 'LastModifiedTimestamp': '1527802340.44',
 'MaximumMessageSize': '65536',
 'MessageRetentionPeriod': '345600',
 'QueueArn': 'arn:aws:sqs:us-east-1:123456789012:test-q-1',
 'ReceiveMessageWaitTimeSeconds': '0',
 'VisibilityTimeout': '30'}

In [9]: resource.create_queue(QueueName="test-q-1", Attributes={'VisibilityTimeout': '60'})
Out[9]: sqs.Queue(url='https://queue.amazonaws.com/123456789012/test-q-1')
```

**Comment by spulec** [comment]
Thanks for opening; this should be fixed now.

**Comment by spulec** [comment]
Fixed in master; we haven't cut a new release yet.
