### ISSUE TITLE
Bug: Implementation Coverage script not working as expected

### ISSUE THREAD

**Issue by sthuber90** [spulec/moto#1673]
For a project of mine I needed to use the _iot-data_ service. Looking into [`IMPLEMENTATION_COVERAGE.md`](https://github.com/spulec/moto/blob/master/IMPLEMENTATION_COVERAGE.md) it looked like the service wasn't implemented yet. After doing a bit of searching I found #1303, where the _iot-data_ service was added to moto.

https://github.com/spulec/moto/blob/0f816566df3aefc20b9054e4dc9f7ca7373bc6f6/IMPLEMENTATION_COVERAGE.md#L2527-L2532

Being interested why this isn't reflected in `IMPLEMENTATION_COVERAGE.md` I dug a bit deeper. I found out that coverage information is not only missing for _iot-data_, but also for _cognito-identity_, and _cognito-idp_. The all have in common that their moto attribute represation is without the "-" i.e. iotdata, cognitoidentity, cognitoidp. If this "renaming pattern" can be seen as set (default) adding following line between these two lines:
https://github.com/spulec/moto/blob/4198abfd24a3aab49a8b83640ca265870e2688d1/scripts/implementation_coverage.py#L8-L9

`service_name = service_name.replace("-", "") if "-" in service_name else service_name`

This will result in having correct coverage info on _iot-data_, _cognito-identity_, as well as _cognito-idp_ services.

Should I make a pull request for this?

**Comment by spulec** [comment]
Ah, thanks for digging in. Yes, a PR would be wonderful.

**Comment by kidomine** [comment]
Hello all!

I would like to add the following to this thread/issue: in relation to this item, Lambda is also reported as 0%.<br>
The implementation coverage script cannot detect the module properly because the module for Lambda is written as `awslambda` instead of `lambda`.<br>
Currently, I am unsure as to how to handle this. Changing an entire module name seems too risky overall and the value is relatively low overall.<br>
Personally though, I would go with changing the module name from `awslambda` to `lambda`.<br>

The following will work, but it's too hacky (see `moto/scripts/implementation_coverage.py)`:
```python
def get_moto_implementation_lambda(service_name):
    if not hasattr(moto, 'aws' + service_name):
        return None

    module = getattr(moto, 'aws' + service_name)
    if module is None:
        return None
    mock = getattr(module, "mock_{}".format(service_name))
    if mock is None:
        return None
    backends = list(mock().backends.values())
    if backends:
        return backends[0]

    return None

def get_moto_implementation(service_name):
    if not hasattr(moto, service_name):
        return None

    module = getattr(moto, service_name)
    if module is None:
        return None
    mock = getattr(module, "mock_{}".format(service_name))
    if mock is None:
        return None
    backends = list(mock().backends.values())
    if backends:
        return backends[0]

    return None
```

What do you guys think?

Thanks!

**Comment by sthuber90** [comment]
Thank you for pointing out this issue. From what I can tell it would be impossible to rename `awslambda` to `lambda` as it is a reserved word in python. Maybe I overlooked something and it is actually possible. In that case, renaming the module would be my prefered way to handle it.

Another solution would be to change `awslambda\__init__.py` from:
``` python
from __future__ import unicode_literals
from .models import lambda_backends
from ..core.models import base_decorator, deprecated_base_decorator

lambda_backend = lambda_backends['us-east-1']
mock_lambda = base_decorator(lambda_backends)
mock_lambda_deprecated = deprecated_base_decorator(lambda_backends)
```
to:
``` python
from __future__ import unicode_literals
from .models import lambda_backends
from ..core.models import base_decorator, deprecated_base_decorator

lambda_backend = lambda_backends['us-east-1']
mock_awslambda = base_decorator(lambda_backends)
mock_awslambda_deprecated = deprecated_base_decorator(lambda_backends)
```

Then just adjusting the `implementation_coverage.py`:
``` python
def standardize_service_name(service_name):
    name = service_name
    if "-" in service_name:
        name = service_name.replace("-", "")

    if name == "lambda":
        name = 'aws' + name

    return name


def get_moto_implementation(service_name):
    service_name_standardized = standardize_service_name(service_name)
    if not hasattr(moto, service_name_standardized):
        return None
    module = getattr(moto, service_name_standardized)
    if module is None:
        return None
    mock = getattr(module, "mock_{}".format(service_name_standardized))
    if mock is None:
        return None
    backends = list(mock().backends.values())
    if backends:
        return backends[0]
```

The result is:
```
## lambda - 23% implemented
- [ ] add_permission
- [ ] create_alias
- [ ] create_event_source_mapping
- [X] create_function
- [ ] delete_alias
- [ ] delete_event_source_mapping
- [X] delete_function
- [ ] delete_function_concurrency
- [ ] get_account_settings
- [ ] get_alias
- [ ] get_event_source_mapping
- [X] get_function
- [ ] get_function_configuration
- [ ] get_policy
- [ ] invoke
- [ ] invoke_async
- [ ] list_aliases
- [ ] list_event_source_mappings
- [X] list_functions
- [X] list_tags
- [ ] list_versions_by_function
- [ ] publish_version
- [ ] put_function_concurrency
- [ ] remove_permission
- [X] tag_resource
- [X] untag_resource
- [ ] update_alias
- [ ] update_event_source_mapping
- [ ] update_function_code
- [ ] update_function_configuration
```

@spulec  Do you have any preferred way of handling this?

**Comment by kidomine** [comment]
@sthuber90 sorry, for the late reply. I also did not realize that `lambda` is a keyword. :p <br>
Personally, I would not worry much about the implementation details of `implementation_coverage.py` as long as it generates the correct report since it is not really critical to moto (I know you guys have other stuff to prioritize).<br>
Also, it seems @spulec already made updates re this, so I'll just leave this in your capable hands.<br>
Thank you!
