### ISSUE TITLE
Some tests not being run in travis

### ISSUE THREAD

**Issue by william-richard** [spulec/moto#1674]
I noticed that pytest is being imported in the dynamodb tests, but this is not being caught by travis!

https://github.com/spulec/moto/blob/master/tests/test_dynamodb2/test_dynamodb.py#L9

I'm not sure why isn't travis running these tests, or what other tests it might be missing. When I run `make test` locally, the `test_dynamodb2` directory runs, and fails because of an import error.

Is this a problem with nose? or how we're using it? or something else?

**Comment by spulec** [comment]
Hmm, maybe Travis has it installed by default?

**Comment by william-richard** [comment]
I don't think that's the issue.  I went through the travis output, and I could not find any mention of the`test_dynamodb2` in the section of the output that lists when each test is run.  That's why I think tests are not being run, rather than pytest being installed already in travis (though it does look like pytest might be installed already).

**Comment by spulec** [comment]
It looks like nose only print the module name, not the folder name so we will see `test_dyanmodb.` for both the dynamo and dynamo2 tests.

You can confirm by seeing two different `test_list_tables_layer_1` here: https://api.travis-ci.org/v3/job/441495243/log.txt

Going to close, but feel free to reopen if I'm missing something.
