### ISSUE TITLE
Compatibility with pyfakefs

### ISSUE THREAD

**Issue by zeraqis** [spulec/moto#1682]
I extensively use [pyfakes](https://github.com/jmcgeheeiv/pyfakefs) for my unit tests and when trying to use it unison with `moto` I was not able to get it to work.

Some background on pyfakefs : it creates an in-memory file system and patches most in-built `os`, `shutil` commands to use the in-memory file system instead.

A simple code sample : 

```
import boto3
from moto import mock_s3
from pyfakefs.fake_filesystem_unittest import TestCase


class ExampleTestCase(TestCase):
    def setUp(self):
        self.setUpPyfakefs()

    @mock_s3
    def test_upload_dir(self):
        conn = boto3.resource('s3', region_name='eu-west-1')
        conn.create_bucket(Bucket='mybucket')
```

Gives me the following error :

```
boto3.exceptions.ResourceNotExistsError: The 's3' resource does not exist.
The available resources are:
```

I suspect this would have to do with `pyfakefs` creating a completely clean slate of a local filesystem.

While I agree that it is not very relevant to raise an issue about `moto`'s compatibility with 3rd party libraries, I was curious as to what moto expects to be on the filesystem? Perhaps I could create the files which moto expects in the in-memory filesystem of `pyfakefs`?

**Comment by spulec** [comment]
Can you confirm this works without the moto decorator? Based on the error, I think this may be an interaction between boto3 and pyfakes.

**Comment by Tomasito665** [comment]
Adding the whole site-packages directory works, but could be slow if you have a lot of packages. At least with `lazy_read=False`. What you could do instead is add only the directories of `boto3` and `botocore`.

```python
import pathlib
import boto3
import botocore
import unittest

# in your setup
for module in [boto3, botocore]:
    module_dir = pathlib.Path(module.__file__).parent
    self.fs.add_real_directory(module_dir, lazy_read=False)

```

**Comment by bblommers** [comment]
Going to close this, as it looks like there's a solution to this.

**Comment by JamieMcKernanKaizen** [comment]
Does anyone know how to implement this when using moto with pytest fixtures?

**Comment by jinkang23** [comment]
> Does anyone know how to implement this when using moto with pytest fixtures as opposed to unittest setup?

In `pytest`, by changing the order of fixtures  to ensure `moto` client fixtures are passed in first then `fs` fixture appears to solve this problem. 

example:  
```python
def test_helloworld(moto_s3_client,moto_ec2_client,fs,mock_context,monkeypatch):
    # test logic here 
    ...
```

**Comment by gaboreyes** [comment]
> Adding the whole site-packages directory works, but could be slow if you have a lot of packages. At least with `lazy_read=False`. What you could do instead is add only the directories of `boto3` and `botocore`.
> 
> ```python
> import pathlib
> import boto3
> import botocore
> import unittest
> 
> # in your setup
> for module in [boto3, botocore]:
>     module_dir = pathlib.Path(module.__file__).parent
>     self.fs.add_real_directory(module_dir, lazy_read=False)
> ```

2023 and this worked for me, thank you so much!
