### ISSUE TITLE
Feature: Firehose S3 Integration

### ISSUE THREAD

**Issue by jk-stack** [spulec/moto#1691]
```python
self.firehose.create_delivery_stream(
      DeliveryStreamName=self.problem_reporter_delivery_stream_name,
      S3DestinationConfiguration={
        'RoleARN': 'arn:aws:iam::123456789012:role/firehose_delivery_role',
        'BucketARN': 'arn:aws:s3:::' + self.problem_reporter_bucket_name,
        'Prefix': 'myPrefix',
        'BufferingHints': {
          'SizeInMBs': 1,
          'IntervalInSeconds': 60
        },
        'CompressionFormat': 'UNCOMPRESSED',
 }
)
```

I create a bucket with name self.problem_reporter_bucket_name, but after calling PUT_RECORD, and checking sometime later, there is nothing in my S3 Bucket.

Is firehose even supported?

**Comment by spulec** [comment]
We have support for Firehose resource APIs, but I don't think the functionality for them does much. I'll add this as a feature request.

**Comment by bblommers** [comment]
This feature is now part of moto >= 2.2.7.dev31. I'll close this for now, but let us know if there are still issues/things missing.
