### ISSUE TITLE
EC2 Instance Type Validation

### ISSUE THREAD

**Issue by alecrajeev** [spulec/moto#1695]
Steps To Reproduce

1. Launch an EC2 instance with an invalid instance type such as t3.nano.
`
client.run_instances(InstanceType="t3.nano", ImageId="ami-00000000", MaxCount=1, MinCount=1, )
`

2. Run Describe Instances and see that the instance is launched with an invalid instance type.
`
{'Reservations': [{'Groups': [], 'Instances': [{'AmiLaunchIndex': 0, 'ImageId': 'ami-00000000', 'InstanceId': 'i-b4955ca3971326510', 'InstanceType': 't3.nano', ..............., 'StateReason': {'Code': '', 'Message': ''}, 'Tags': [], 'VirtualizationType': 'paravirtual'}], 'OwnerId': '123456789012', 'ReservationId': 'r-3e442b18'}], 'ResponseMetadata': {'RequestId': 'fdcdcab1-ae5c-489e-9c33-4637c5dda355', 'HTTPStatusCode': 200, 'HTTPHeaders': {'Content-Type': 'text/plain', 'server': 'amazon.com'}, 'RetryAttempts': 0}}
`

Referring to  'InstanceType': 't3.nano'

3. An InvalidParameterValueError should occur.

`
botocore.exceptions.ClientError: An error occurred (InvalidParameterValue) when calling the RunInstances operation: Invalid value 't3.nano' for InstanceType.
`

4. Only reproduced on python mocks so far, but could likely be reproduced on standalone server

**Comment by alecrajeev** [comment]
fix for #1696

**Comment by spulec** [comment]
Thanks for opening; setting this as a feature request for instance type validation.

**Comment by alecrajeev** [comment]
@spulec Thanks! I have opened PR on this here #1696
