### ISSUE TITLE
Unable to set subscribe attributes for SNS with subscribe function

### ISSUE THREAD

**Issue by MichaelBellBOM** [spulec/moto#1704]
From:
https://boto3.readthedocs.io/en/latest/reference/services/sns.html#SNS.Client.subscribe
There is an optional Attributes keyword parameter that allows the setting of subscription attributes.

This feature is missing from moto and is preventing this from being mocked.

To reproduce mock the subscribe call for sns and then the get_subscription_attributes, to see that the attributes are not set.

**Comment by spulec** [comment]
Fixed with #1705
