### ISSUE TITLE
DynamoDB issue: global secondary index causes query error

### ISSUE THREAD

**Issue by adamdavis40208** [spulec/moto#1710]
Error code:

TypeError: unsupported operand type(s) for +: 'dict_values' and 'list'

https://github.com/spulec/moto/blob/master/moto/dynamodb2/responses.py#L336

table.global_indexes is a dict hence the issue.

**Comment by spulec** [comment]
It would be great if you have some code that can reproduce the issue.

**Comment by adamdavis40208** [comment]
Sure thing, let me grab one of my tests.

**Comment by adamdavis40208** [comment]
https://gist.github.com/adamdavis40208/27118919e12ef7b3e59552abbef5098d

It's actually happening even with one GSI, and querying it with boto3.

**Comment by matthew-craig-ncino** [comment]
I have found I get this same issue, the conditions for me to trigger it are as follows

Environment: python3, boto3, moto

IF I use global secondary indexes on a table and attempt to query the secondary index it triggers this TypeError.  IF I move to a python2 environment, the same code does NOT trigger the TypeError for me.

**Comment by bblommers** [comment]
@adamdavis40208 There's been quite a few changes in DynamoDB, and I can no longer reproduce this issue with the [latest version](https://pypi.org/project/moto/#history). Running  your test works fine now.
Will close this for now - feel free to open a new issue if there's still something amiss
