### ISSUE TITLE
How to make mocked `create_access_key` return predictable results?

### ISSUE THREAD

**Issue by techraf** [spulec/moto#1716]
Is there a way to mock `create_access_key` in an assertable way? E.g., provide a seed for the random function?

Sample PyTest test:

    import boto3
    from moto import mock_iam
    
    @mock_iam
    def test_create_access_keys():
        iam = boto3.client('iam')
        iam.create_user(UserName='test-user')

        # call to a method replaced with `iam.create_access_key` here:
        response = iam.create_access_key(UserName='test-user')
        assert response['AccessKey']['AccessKeyId']) == predetermined_access_key_id
        assert response['AccessKey']['SecretAccessKey']) == predetermined_secret_access_key

How can I assert the results?

Is there a way to have `predetermined_access_key_id` and `predetermined_secret_access_key` values fixed?

**Comment by spulec** [comment]
No, we don't have a way to do that today.

Can you talk a bit more about your use case and why you want to do that? I don't quite understand what you are trying to accomplish and want to make sure any feature we add would actually help.

**Comment by bblommers** [comment]
Going to close this due to a lack of response
