### ISSUE TITLE
Add support for AWS Organizations

### ISSUE THREAD

**Issue by ashleygould** [spulec/moto#1720]
I have made a first start at mocking out some primary organizations endpoints:
https://github.com/ashleygould/moto/tree/organizations_support

I could certainly use some guidance and advice.

endpoints covered so far:
    - create_organization
    - describe_organization
    - create_account
    - describe_account
    - list_accounts

**Comment by spulec** [comment]
Your fork looks like an amazing start!

I would be happy to have you open a pull request now and we can merge all of that work in so people can start using it. We can always add more later with additional pull requests.

Let me know if you have more specific questions.

**Comment by ashleygould** [comment]
Great!  I will do a little bit of cleanup and submit.

question:
- does the project have recommendations about mocking out botocore exceptions? Or do folks implement mock exceptions as the need arises? I did see several examples among the more mature resources

**Comment by spulec** [comment]
Closed with https://github.com/spulec/moto/pull/1727
