### ISSUE TITLE
404 on LIst Tags

### ISSUE THREAD

**Issue by stephenrjohnson** [spulec/moto#1725]
I've created a cloudformation stack using the following template:

```
AWSTemplateFormatVersion: '2010-09-09'
Description: Persistant resouces for Nucleus
Resources:
  TestLambda:
      Type: AWS::Lambda::Function
      Properties:
         Handler: 'test.handler'
         Role : 'Default'
         Runtime : 'python'
         Code : 
          ZipFile: 'def lambda_handler(event, context):return (event, context)'
      Tags:
        - Key: "TestKey"
        - Value: "TestValue"
Outputs:
  LambdaID:
    Value: 
      Fn::GetAtt: 
        - "TestLambda"        
        - "Arn"
```

When I then call list_tags on the arn that is returned I get 404 but the function is there in list functions:

Botocore.exceptions.ClientError: An error occurred (404) when calling the ListTags operation:
`Request tags for : arn:aws:lambda:us-west-2:123456789012:function:Test-Lambda-1-TestLambda-348A-Z77953306:1`

List functions returns:

`{'ResponseMetadata': {'HTTPStatusCode': 200, 'HTTPHeaders': {'Content-Type': 'text/plain'}, 'RetryAttempts': 0}, 'Functions': [{'FunctionName': 'Test-Lambda-1-TestLambda-348A-Z77953306', 'FunctionArn': 'arn:aws:lambda:us-west-2:123456789012:function:Test-Lambda-1-TestLambda-348A-Z77953306:$LATEST', 'Runtime': 'python', 'Role': 'Default', 'Handler': 'test.handler', 'CodeSize': 182, 'Description': '', 'Timeout': 3, 'MemorySize': 128, 'LastModified': '2018-07-20 08:19:53', 'CodeSha256': '06cd1061eff3bf526ace9bdb2f1575a45f45c3bee6347149f461bc4be46839e3', 'Version': '$LATEST', 'VpcConfig': {'SubnetIds': [], 'SecurityGroupIds': []}}]}`
----

Just wondering what I'm doing wrong. Thanks.

**Comment by bblommers** [comment]
This should now be implemented. Relevant PR: https://github.com/spulec/moto/pull/1344
Relevant test case: https://github.com/spulec/moto/blob/master/tests/test_awslambda/test_lambda.py#L787

Closing this - feel free to reopen if there's still an issue
