### ISSUE TITLE
ECS describe tasks without full arn

### ISSUE THREAD

**Issue by Matthijsy** [spulec/moto#1740]
Currently it's only possible to find tasks when passing the full arn to `describe_tasks()`. When using boto3 it's also working to pass the resource id.

Example:
When you want to describe this task:
`arn:aws:ecs:us-east-1:123456789012:task/1abf0f6d-a411-4033-b8eb-a4eed3ad252a`  in boto3 you could just do: 
`client.describe_tasks(tasks=['1abf0f6d-a411-4033-b8eb-a4eed3ad252a'])`
But in moto you needs to do:
 `client.describe_tasks(tasks=['arn:aws:ecs:us-east-1:123456789012:task/1abf0f6d-a411-4033-b8eb-a4eed3ad252a'])` otherwise you don't get the tasks. 
It would be great if it's possible to only use the resource_id and not the full arn.

**Comment by spulec** [comment]
Thanks; setting as feature request.

**Comment by gruebel** [comment]
@spulec I think you fixed this with your own commit 7c1fd0a2f1b834dcc7cd6e9c852cff765b066cc7

**Comment by spulec** [comment]
Good call. Thanks.
