### ISSUE TITLE
moto.mock_dynamodb2 treats not equals as equals in filter expressions

### ISSUE THREAD

**Issue by drewpearce** [spulec/moto#1743]
when constructing a not equals filter expression like this:
```python
Attr('fieldname').ne('some value')
```
moto appears to be treating as `eq` (equals)

- How to duplicate
  - See test script below
- What you expect to happen
  - The script should print out 3 scans of the table with sample data.
    - Non filtered scan -- all 3 records
    - filter with providerName eq aws -- 1 record, where providerName eq aws
    - filter with providerName ne aws -- 2 records, where providerName ne aws
- What actually happens
  - Script prints out 3 scans of the table with sample data
    - Non filtered scan -- all 3 records
    - filter with providerName eq aws -- 1 record, where providerName eq aws
    - filter with providerName ne aws -- 1 record, where providerName eq aws
      - This demonstrates the reported bug
- Version Info. I've tested on the following
  - python 2.7.15 with moto 1.1.25 and boto3 1.7.40 installed via pip
  - python 2.7.15 with moto 1.3.3 and boto3 1.7.66 installed via pip
  - python 3.6.5 with moto 1.3.3 and boto3 1.7.66 installed via pip

test script
```python
import boto3
from boto3.dynamodb.conditions import Attr
from moto import mock_dynamodb2
import os
from pprint import pprint

# set aws env vars
os.environ['AWS_DEFAULT_REGION'] = 'us-east-1'

# start mock
mock = mock_dynamodb2()
mock.start()

# vars and objects
table_object = boto3.resource('dynamodb')
table_name = 'test_table'
data = [
    {
        'id': 1,
        'providerName': 'aws'
    }, {
        'id': 2,
        'providerName': 'azure'
    }, {
        'id': 3,
        'providerName': 'google'
    }
]

# create table
create_table = table_object.create_table(
    TableName=table_name,
    KeySchema=[
        {
            'AttributeName': 'id',
            'KeyType': 'HASH'
        }
    ],
    AttributeDefinitions=[
        {
            'AttributeName': 'id',
            'AttributeType': 'N'
        }
    ],
    ProvisionedThroughput={
        'ReadCapacityUnits': 1,
        'WriteCapacityUnits': 5
    }
)

# instantiate boto/moto table object
table = table_object.Table(table_name)

# batch write data to table
with table.batch_writer() as batch:
    for item in data:
        batch.put_item(Item=item)

# print all data
print('\n\n\nALL ITEMS')
pprint(table.scan())

# filter providerName eq aws
filter = Attr('providerName').eq('aws')
print('\n\n\nPROVIDER NAME EQ aws')
pprint(table.scan(FilterExpression=filter))

# filter providerName ne aws
filter = Attr('providerName').ne('aws')
print('\n\n\nPROVIDER NAME NE aws')
pprint(table.scan(FilterExpression=filter))
```

**Comment by shift-support** [comment]
running into this as well.  Kinda breaking the tests

**Comment by spulec** [comment]
I don't think we've implemented this yet. Setting as a feature request. Thanks!

**Comment by shift-support** [comment]
To clarify, this isn't an enhancement, it's a bug.  It is implemented but treats not_equals as equals.

**Comment by bblommers** [comment]
Closing this, as the associated PR has been merged
