### ISSUE TITLE
mock_dynamodb2 do not works with dynamodb reserved words

### ISSUE THREAD

**Issue by dotnet007** [spulec/moto#1749]
**what actually happens**
dynamodb2 API provides a way to work with attributes that are reserved words (https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/ReservedWords.html) like "status".
Is throwing an exception:
botocore.errorfactory.ConditionalCheckFailedException: An error occurred (ConditionalCheckFailedException) when calling the UpdateItem operation: A condition specified in the operation could not be evaluated.

**how to reproduce the issue**
Try to call the update_item api call using the ExpressionAttributeValues and ExpressionAttributeNames to use reserved words in the attributes, like "status" (ExpressionAttributeNames).  It fails if you are using the # alias.

**what you expected to happen**
Do the update in the mocked table with the same behavior as in the real dynamodb table.
 
**what version of Moto you're using**
1.3.3

**how you installed it**
In my local Mac OS machine with pip install moto

**Comment by bblommers** [comment]
I realize this was raised quite a while back, but ExpressionAttributeNames/Values definitely work in the latest version. (moto >= 1.3.15.dev914)

Will close this - let us know if you run into any other issues.
