### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by lalarsson** [spulec/moto#1752]
Hi! Thanks for the awesome work!

I'm wondering when the next release is coming, kind of waiting for https://github.com/spulec/moto/pull/1643 to fix some issues I'm having...

**Comment by yan12125** [comment]
I'd like to see Python 3.7 support (#1733) merged before the next release.

**Comment by yan12125** [comment]
1.3.4 is released! Not 3.7-compatible yet, though.
