### ISSUE TITLE
secretsmanager.DescribeSecret is not implemented

### ISSUE THREAD

**Issue by NeilRoberts** [spulec/moto#1753]
Moto does not currently implement secretsmanager.DescribeSecret.

https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_DescribeSecret.html

**Comment by sepulworld** [comment]
Nevermind you already did!

**Comment by NeilRoberts** [comment]
Can you help me understand what's happening here? Is the report saying that my change caused these lines to not be covered, or just that they aren't?

https://coveralls.io/builds/18353836

**Comment by sepulworld** [comment]
I'm not sure on coveralls output there. Your tests in your PR cover the bases for me.

**Comment by NeilRoberts** [comment]
Excellent.

I'm going to add RotateSecret next, so that should be along soon.

**Comment by spulec** [comment]
Closed with https://github.com/spulec/moto/pull/1754
