### ISSUE TITLE
secretsmanager.SecretsManagerBackend doesn't save the friendly name and doesn't verify that the supplied SecretId or Name is valid

### ISSUE THREAD

**Issue by NeilRoberts** [spulec/moto#1770]
AWS SecretsManager allows the use of either the ARN or friendly name when specifying which secret to touch. When Moto creates a new secret, it accepts the friendly name, but never saves it (a field already exists for this). None of the methods that accept a SecretId or Name verify a match to either the saved secret_id or name.

I need this fixed for something else that I'm doing. Expect a PR shortly.

**Comment by spulec** [comment]
Fixed with https://github.com/spulec/moto/pull/1772
