### ISSUE TITLE
ECS list tasks should handle filters like 'desiredStatus', 'family', 'service_name'

### ISSUE THREAD

**Issue by Matthijsy** [spulec/moto#1785]
Currently when calling the `list_task()` method on ECS with the `desiredStatus` set to 'STOPPED' all the tasks are returned. I would expect to only get the stopped tasks. 

When looking at the code probably a filter on status should be added to this method: https://github.com/spulec/moto/blob/master/moto/ecs/models.py#L612

**Comment by spulec** [comment]
Thanks; setting as a feature request.

**Comment by jung-kim** [comment]
I would like to add that as of 2020/02/13, [list_tasks()](https://github.com/spulec/moto/blob/master/moto/ecs/models.py#L793-L826) haven't properly implemented filtering for `family`, `desiredStatus`, and `service_name` filtering.

Should I open separate ticket for this?  Or should this ticket's scope be expanded?

**Comment by bblommers** [comment]
This is now part of moto >= 1.3.16.dev59
