### ISSUE TITLE
Incorrect query parsing to detect delete objects

### ISSUE THREAD

**Issue by vergnes** [spulec/moto#1787]
**how to reproduce the issue**
Send a request to the delete objects endpoint such as
`curl -X POST http://localhost:5000/bucket?delete=`. This typically what the AWS Go SDK will send when using `DeleteObjects`.

**what you expected to happen**
The request is processed.

**what actually happens**.
The request fails with a 400 HTTP error.

https://github.com/spulec/moto/blob/master/moto/s3bucket_path/utils.py needs to be fixed to accept a query string with `delete=`

**Comment by spulec** [comment]
Can you give some code to reproduce? We have multiple tests that test general key deletion so it would be helpful to narrow this down: https://github.com/spulec/moto/blob/master/tests/test_s3/test_s3.py#L548-L591

**Comment by vergnes** [comment]
With boto as client, the issue cannot be reproduced. The problem occurs when the client sends the query parameter `delete` with `=` at the end.

**Comment by valsoray17** [comment]
@vergnes were you able to workaround the issue? That's the same issue I have with Go SDK

**Comment by bblommers** [comment]
This has been fixed by https://github.com/spulec/moto/pull/2944
