### ISSUE TITLE
Importing moto messes with logging import

### ISSUE THREAD

**Issue by fruechel** [spulec/moto#1795]
## Reporting Bugs

The short and sweet:
```
>>> import logging
>>> logging.config
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'logging' has no attribute 'config'
>>> import moto
>>> logging.config
<module 'logging.config' from '/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/config.py'>
```

That is, when importing moto, `config` is added to the `logging` module when usually you have to run `import logging.config` to make it work. This lead to tests passing but production code failing - it used `logging.config` without importing it.

```
% pip freeze | grep -i moto
moto==1.3.4
```

I grepped through the moto code but could not find any indication as to where this might be happening. It is entirely possible that a dependency of moto does this. This also means it might not be a moto bug at all but I'm hoping with more knowledge of moto, you are able to determine where this is coming from.

If you feel this is a non-issue or minor enough, feel free to close it. Otherwise, let me know if you have any questions.

**Comment by spulec** [comment]
I'm guessing this is a dependency of moto importing logging.config.

I'm not positive which one, but going to close this since we can't really do much.
