### ISSUE TITLE
boto3 delete object ISSUE

### ISSUE THREAD

**Issue by angu10** [spulec/moto#1811]
## Reporting Bugs

Please be aware of the following things when filing bug reports:

1. Avoid raising duplicate issues. *Please* use the GitHub issue search feature
   to check whether your bug report or feature request has been mentioned in
   the past.
2. When filing bug reports about exceptions or tracebacks, please include the
   *complete* traceback. Partial tracebacks, or just the exception text, are
   not helpful.
3. Make sure you provide a suitable amount of information to work with. This
   means you should provide:

   - Guidance on **how to reproduce the issue**. Ideally, this should be a
     *small* code sample that can be run immediately by the maintainers.
     Failing that, let us know what you're doing, how often it happens, what
     environment you're using, etc. Be thorough: it prevents us needing to ask
     further questions.
   - Tell us **what you expected to happen**. When we run your example code,
     what are we expecting to happen? What does "success" look like for your
     code?
   - Tell us **what actually happens**. It's not helpful for you to say "it
     doesn't work" or "it fails". Tell us *how* it fails: do you get an
     exception? A hang? How was the actual result different from your expected
     result?
   - Tell us **what version of Moto you're using**, and
     **how you installed it**. Tell us whether you're using standalone server
     mode or the Python mocks. If you are using the Python mocks, include the
     version of boto/boto3/botocore.

   If you do not provide all of these things, it will take us much longer to
   fix your problem.

**Comment by angu10** [comment]
ef delete_object(bucketName,key):
    try:
        response = client.delete_object(Bucket=bucketName,Key=key)
        return reponse
    except Exception as e:
            return ("Error: %s" %str(e))
            
        

i = delete_object(xyx','test/test.txt')

Question:
I was passing a wrong key and it returned HTTP 204 and then I tried with a valid key and also got a 204. Why I'm not getting any error when I'm passing the wrong key.

**Comment by spulec** [comment]
I don't believe we've implemented that yet; will set as a feature request.

**Comment by bblommers** [comment]
I've just tested this against S3 itself, and it doesn't throw an error either. 
This is the actual AWS response:
```
{'ResponseMetadata': {
    'HTTPStatusCode': 204,
    'RetryAttempts': 0,
    'HostId': '...',
    'RequestId': '...',
    'HTTPHeaders': {
        'x-amz-id-2': '...',
        'date': 'Sat, 20 Jun 2020 10:35:46 GMT',
        'x-amz-request-id': '...',
        'server': 'AmazonS3'
    }
}}
```

From [the docs](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Client.delete_object):
`Removes the null version (if there is one) of an object [...]. If there isn't a null version, Amazon S3 does not remove any objects.`
No mention of an exception being thrown. 

Will close this - let me know if I've missed anything.
