### ISSUE TITLE
mismatch libraries

### ISSUE THREAD

**Issue by liewjls** [spulec/moto#1832]
Hi, 

I'm currently running moto 1.3.5. I think I have updated some libraries and it's seems stop working now. 

Here are the errors:
`

python
Python 2.7.15 (default, Sep 18 2018, 20:16:18)
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import moto
/usr/local/lib/python2.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.23) or chardet (2.0.3) doesn't match a supported version!
  RequestsDependencyWarning)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/moto/__init__.py", line 38, in <module>
    from .secretsmanager import mock_secretsmanager  # flake8: noqa
  File "/usr/local/lib/python2.7/site-packages/moto/secretsmanager/__init__.py", line 5, in <module>
    secretsmanager_backend = secretsmanager_backends['us-east-1']
KeyError: u'us-east-1'
>>>`

Any ideas how to resolve this? 

Thanks.

**Comment by spulec** [comment]
Which version of boto3/botocore do you have installed?

**Comment by liewjls** [comment]
Thank you for prompt reply. 

Here are the details:
`pip show boto3
Name: boto3
Version: 1.9.7
Summary: The AWS SDK for Python
Home-page: https://github.com/boto/boto3
Author: Amazon Web Services

pip show botocore
Name: botocore
Version: 1.9.16
Summary: Low-level, data-driven core of boto 3.
Home-page: https://github.com/boto/botocore
Author: Amazon Web Services

`

**Comment by liewjls** [comment]
Sorry. It's appear due to the requests library using wrong requirements for chardet and urllib3 libraries. Found https://stackoverflow.com/a/51967038/1817668 fix my problem. 

thanks.
