### ISSUE TITLE
dynamodb2 UpdateExpression "REMOVE" not working for nested attributes.

### ISSUE THREAD

**Issue by avinashbitra** [spulec/moto#1834]
table.update_item(...
            UpdateExpression='REMOVE attra.#attrb',
            ExpressionAttributeNames={
                "#attrb": 'value'
            }
        )

Expected:  attra.attrb removed from my item
Result: attra.attrb not removed and no error.

CODE: dynamodb2/models.py line 147

                if action == "REMOVE":
                    self.attrs.pop(value, None) -- value = "atta.attr.b"

**Comment by spulec** [comment]
Thanks; setting as a feature request.

**Comment by BradyShober** [comment]
This was driving me crazy trying to figure out why it wasn't working in my test

**Comment by ZoidBB** [comment]
I'll be submitting a PR for this shortly.
