### ISSUE TITLE
Moto always returns State: {Code: "provisioning"} for ELBV2

### ISSUE THREAD

**Issue by emr0327** [spulec/moto#1841]
- I expected the State of the load balancer to eventually reach Code: "active"
   - I could not auto-test my code that is dependent on an "active" state because the code is always "provisioning"
   - Moto version: 1.3.1

**Comment by spulec** [comment]
We don't currently have a solid solution for state transition. Going to close this in favor of https://github.com/spulec/moto/issues/380
