### ISSUE TITLE
ResourceGroupsTaggingAPI.Client.get_resources does not return tagged resources.

### ISSUE THREAD

**Issue by markchalloner** [spulec/moto#1849]
### Test

```
import boto3
from moto import mock_ec2, mock_resourcegroupstaggingapi


def test():
    mock_ec2().start()
    mock_resourcegroupstaggingapi().start()


    ec2 = boto3.resource('ec2', region_name='us-west-1')
    vpc = ec2.create_vpc(CidrBlock='10.0.0.0/16')
    ec2.create_tags(Resources=[vpc.id], Tags=[{'Key': 'test', 'Value': 'test'}])

    assert list(ec2.vpcs.filter(Filters=[{'Name':'tag:test', 'Values': ['test']}]))

    resourcegroupstaggingapi = boto3.client('resourcegroupstaggingapi')
    resources = resourcegroupstaggingapi.get_resources(TagFilters=[{'Key': 'test', 'Values': ['test']}])

    assert resources['ResourceTagMappingList']

    mock_resourcegroupstaggingapi().stop()
    mock_ec2().stop()

```

### Output:

> FAILED                            [ 0%]
test.py (test)
...
E       assert []
...

## Expected

Response dictionary key 'ResourceTagMappingList'  to be a list with one item (the Vpc).

## Actual

Response dictionary key 'ResourceTagMappingList'  is a list with no items.

## Library versions

```
moto = { git = "git://github.com/spulec/moto.git", ref = "dfa7935e13e6065810d6fc4e1edbf3e86499aea5" }
boto3 = "==1.7.79"
botocore = "==1.10.79"
```

**Comment by spulec** [comment]
I don't believe we've implemented this yet. Going to set as a feature request. Thanks!

**Comment by tsiq-shiv** [comment]
Doesn't look like this is implemented for SecretsManager and/or SNS (from what I've tried so far). Is there a list of S3 services for which `get_resources` has been implemented?

**Comment by bblommers** [comment]
This is now part of moto >= 1.3.16.dev58
