### ISSUE TITLE
Contributing `cancel_job` for Batch

### ISSUE THREAD

**Issue by drmmarsunited** [spulec/moto#1850]
It looks like the `cancel_job` is the last API not implemented for AWS Batch support.  I'd like to help finish that off as I'm actively working on a project where I could use Batch support in moto :)

I've never contributed here before, but the rules mentioned opening an issue here first to discuss approach.  Seeing as how there is a lot done for Batch already, I'm hoping it will help shorten the learning curve.

**Comment by spulec** [comment]
Thanks; a pull request would be very welcome.

Going to set this issue as a feature request.
