### ISSUE TITLE
Add trusted hosts / networks to Server mode

### ISSUE THREAD

**Issue by trickstyler** [spulec/moto#1855]
Currently (Java) AWS API can only work with Moto from the local network (if it starts with "192.168.X.X") or if the request is coming from the same host as the server, that's very limiting because i want to run Moto on a container in an external network.

Any chance to add trusted networks or hosts via config file or CLI args?

I'd appreciate any info if this had been addressed or i'm using it wrong

**Comment by trickstyler** [comment]
SOLVED using 
request.putCustomRequestHeader("HOST", "motoserver")

on AWS api

**Comment by trickstyler** [comment]
I'm reopening this To request that server mode could work with requests coming from different IP addresses (e.g. that do _NOT_ start 192.168.X.X)

I'm trying to work with boto3 to Moto container running in a different network
and since boto3 doesn't support putting custom headers on the request - it's impossible to use Moto

I'd greatly appreciate any guidance if you think i'm doing something wrong

**Comment by spulec** [comment]
Maybe I'm misunderstanding, does something like `moto_server ec2 -H 0.0.0.0` not work?

**Comment by spulec** [comment]
If we bind to 0.0.0.0, it should allow requests from anyone (this is just a light wrapper around flask).

What requires the custom headers?

**Comment by trickstyler** [comment]
when i tried reaching moto from outside a Docker - i couldn't because it'll only allow connections from hosts named: "localhost"/"motoserver" or from IP address starting with "192.168.X.X".

I fixed it using PR #2316 but it's your decision whether to approve :)

**Comment by christhomas** [comment]
I checked out the PR and I am wondering what @trickstyler has done to get it to work because in my case it's giving the same result
