### ISSUE TITLE
Suggestion requested for mock_s3: Unable to Mock

### ISSUE THREAD

**Issue by yks0000** [spulec/moto#1858]
I am trying to test s3 put_object function which I have. AWS S3 is already created and not part of program. Below is the program and unit test related to it.

**FileName**: s3_moto_module.py
    
```
import boto3

bucket_prefix = "test-bucket-moto"

def get_client(service, region):
    s3_service_config = boto3.session.Config(signature_version='s3v4')
    client = boto3.client(service, config=s3_service_config, region_name=region)
    return client

def upload_key(data, s3_file_key, aws_acc_id):
    client = get_client('s3', region="us-west-2")
    s3_bucket = "{}-{}".format(bucket_prefix, aws_acc_id)
    client.put_object(
        ACL='private',
        Body=data,
        Bucket=s3_bucket,
        Key=s3_file_key
    )

if __name__ == '__main__':
    upload_key(data="test", s3_file_key="dummy_key", aws_acc_id="1234567890")
```

**UnitTest**:
    
```
from unittest import TestCase
from moto import mock_s3
from s3_moto_module import upload_key, get_client


class TestAwsS3(TestCase):

    def setUp(self):
        self.account_id = "1234567890"
        self.bukect_name = "test-bucket-moto-{}".format(self.account_id)
        self.s3_file_key = "dummy_s3_key"
        self.file_name = "/tmp/{}".format(self.s3_file_key)
        self.data = "s3_dummy_data"

    @mock_s3
    def __moto_setup(self):
        client = get_client('s3', region="us-west-2")
        client.create_bucket(Bucket=self.bukect_name, CreateBucketConfiguration={'LocationConstraint': 'us-west-2'})

    @mock_s3
    def test_upload_key(self):
        self.__moto_setup()
        upload_key(self.data, self.s3_file_key, self.account_id)
```

        
When I run this, it gives below error as because it is trying to create a bucket which already exists:

`botocore.errorfactory.BucketAlreadyOwnedByYou: An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it.`
            
If I give another name for `self.bukect_name`, it actually creates a bucket in AWS Account. (Account which has aws_profile=default)

This does look like mock call. Please let us know what wrong I am doing here.

Package Versions

```
boto3 = 1.9.5
botocore = 1.12.5
moto = 1.3.3
```

`Python Version: 3.6.5`

**Comment by yks0000** [comment]
Seems like related to https://github.com/spulec/moto/issues/1793

**Comment by spulec** [comment]
Yes, going to close in favor of #1793
