### ISSUE TITLE
Determine required IAM permissions

### ISSUE THREAD

**Issue by jaronsummers** [spulec/moto#1863]
Howdy,

So something I've been thinking about recently is a good way to estimate the IAM permissions that a given application would need in order to function, Doing code analysis seems super difficult, and would be language-specific.

Is this something that would make sense to extend from moto_server, or roll into it?

I have been looking through the code a little bit, but I am generally not familiar with moto, it just seemed to me that there might be a way to have moto_server track which actions are taken, have an understanding of the permissions required to do that thing, and then provide a report, or even a generated policy document that would make all of those actions possible against real AWS endpoints.

Does that seem plausible? Any hints on the best place to start? Am I a crazy person?

**Comment by jaronpeloton** [comment]
Okay, cool, thanks for the feedback. I'll start poking around and see what I come up with.
