### ISSUE TITLE
Support NextToken for SSM's GetParametersByPath

### ISSUE THREAD

**Issue by lephuongbg** [spulec/moto#1864]
Currently SSM implementation doesn't return NextToken yet. It would be nice if this is added into feature backlog. For now we have to add `pragma: no branch` to ignore 'NextToken' branch.

I have seen a similar request for SNS. Wonder if this could be quickly implement using the same way. https://github.com/spulec/moto/issues/144

**Comment by spulec** [comment]
Thanks; setting as a feature request.
