### ISSUE TITLE
secretsmanager.PutSecretValue is not implemented

### ISSUE THREAD

**Issue by NeilRoberts** [spulec/moto#1867]
Moto does not currently implement secretsmanager.PutSecretValue

https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_PutSecretValue.html

***NOTE***
~~I am implementing this and will open a PR when it's complete and ready.~~

**Comment by NeilRoberts** [comment]
Unfortunately, I did not. When it became apparent that our pipeline/DevOps didn't support Secrets Manager, I had to change directions and my promised time to work on this keeps being pushed out. Please pick it up if you have bandwidth and I will check back with the project when I can.

**Comment by spulec** [comment]
Closed with https://github.com/spulec/moto/pull/2116
