### ISSUE TITLE
logs.filter_log_events is only partially implemented

### ISSUE THREAD

**Issue by sean-abbott** [spulec/moto#1873]
I suspect this is already well known, but mock_logs.filter_log_events is basically unimplemented.

Given the following code:
```
import boto3
import time

from moto import mock_logs

log_group_name = 'stuff'
log_stream_name = 'whatnot'

mock = mock_logs()
mock.start()
log_client = boto3.client('logs')

log_client.create_log_group(logGroupName=log_group_name) 
log_client.create_log_stream(logGroupName=log_group_name, logStreamName=log_stream_name)
timestamp = int(round(time.time() * 1000))
response = log_client.put_log_events(
        logGroupName=log_group_name,
        logStreamName=log_stream_name,
        logEvents= [
            {
                'timestamp': timestamp,
                'message': "test"
                },
            {
                'timestamp': timestamp,
                'message': "ERROR:root:scraper <ingestion.scrapers.my.scraper object at 0x7fac6be1f5f8> exited w error HTTP Error 500: INTERNAL SERVER ERROR"
                }
            ],
        sequenceToken='0')
events1 = log_client.filter_log_events(logGroupName=log_group_name, logStreamNames=[log_stream_name], filterPattern="ERROR")
events2 = log_client.filter_log_events(logGroupName=log_group_name, logStreamNames=[log_stream_name], filterPattern="baz")

assert len(events1['events']) == 1
assert len(events2['events']) == 0
```

I would expect filter to actually work and the asserts to be true.

 However, both events in the log stream end up in the "filtered" event object.
I know you know this because the filter_func (https://github.com/spulec/moto/blob/master/moto/logs/models.py#L114-L121) is basically unimplemented, but it would be nice to at least have that show in the docs someplace

Installed into a virtualenv via pip. I am using python mocks.
boto==2.49.0
boto3==1.7.80
botocore==1.10.80
moto==1.3.4

I would love to help expand the capabilities of the filter, but since I only need the simple case of a single element, I'd probably end up stopping pretty early. Also, not sure where in your docs this could be annotated.

**Comment by spulec** [comment]
Thanks; setting as a feature request.
