### ISSUE TITLE
Check the item size of DynamoDB

### ISSUE THREAD

**Issue by zzl0** [spulec/moto#1874]
Feature Request:

There is a [400 KB limit](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Limits.html#limits-items) on the item size in DynamoDB, it seems current DynamoDB implementation doesn't check the item size in [put_item](https://github.com/spulec/moto/blob/master/moto/dynamodb2/responses.py#L183-L234) method.

Appreciate it if you are interested in implementing this feature!

**Comment by bblommers** [comment]
@zzl0 @spulec This should be fixed now!

**Comment by spulec** [comment]
Closed with https://github.com/spulec/moto/pull/2455
