### ISSUE TITLE
missing Description for IpRange

### ISSUE THREAD

**Issue by EvgenyKhaliper** [spulec/moto#1895]
Seems like when adding ingress rule to security group 'authorize_security_group_ingress()' the "Description" is ignored unlike in boto3.

Seems the code is in SecurityGroups class _process_rules_from_querystring method

```
            ip_ranges = []
            ip_ranges_tree = ip_permission.get('IpRanges') or {}
            for ip_range_idx in sorted(ip_ranges_tree.keys()):
                ip_ranges.append(ip_ranges_tree[ip_range_idx]['CidrIp'][0])
```

I don't know if is there a reason for that or is it a bug but it definitely makes it hard to test feature i've wrote using moto.

**Comment by spulec** [comment]
Thanks; setting as a feature request.

**Comment by bblommers** [comment]
The description is now persisted as of moto >= 1.3.16.dev199
