### ISSUE TITLE
DynamoDB doesn't support ReturnValues for put, delete, and update item

### ISSUE THREAD

**Issue by Ben-Wu** [spulec/moto#1902]
This is an extension of issue https://github.com/spulec/moto/issues/1404

`put_item` and `update_item` ignores the `ReturnValues` argument and will always return the updated new item (behaves like `ALL_NEW`).

`delete_item` supports `ALL_OLD` but for any other value it return an item with no attributes where it should not be returning an item at all.

These actions should also be raising a `ValidationException` for invalid arguments passed to `ReturnValues`.

Here a notebook with an example of the current behaviour: https://nbviewer.jupyter.org/gist/Ben-Wu/7945add78b69c1e45b47d2450ae27d1d

(moto==1.3.6)

**Comment by kgutwin** [comment]
Addressed by PR #1938.

**Comment by spulec** [comment]
Closed with https://github.com/spulec/moto/pull/1938
