### ISSUE TITLE
Cookies dependency deprecation flag

### ISSUE THREAD

**Issue by triat** [spulec/moto#1914]
One of the dependencies of moto is `Cookies` and I have deprecation warnings on this one (on python3.6). I've checked their repo, the error is reported but it doesn't look really active (last commit 4 years ago).

I wanted to raise it, to make sure that there is enough time to do a switch of lib, or to find a solution with the owner of the `Cookies` repo to avoid any bad surprise the day it is removed from python.

I'm not sure if it has already been reported (I've tried to find a similar issue), so please excuse me if it is a duplication.

Here the link to the issue:
https://gitlab.com/sashahart/cookies/issues/4

**Comment by spulec** [comment]
It looks like they are suggesting we move to https://github.com/pyrates/biscuits/

**Comment by triat** [comment]
I guess it would be a good move yes :) Thanks for having a look at it

**Comment by spulec** [comment]
I missed that this dependency had actually been removed with https://github.com/spulec/moto/pull/1835
