### ISSUE TITLE
BaseMockAWS.__enter__() should return self

### ISSUE THREAD

**Issue by karok2m** [spulec/moto#1915]
https://github.com/spulec/moto/blob/71a054af92a45e2a8b5d7c4fb435841949e1895c/moto/core/models.py#L44

`__enter__()` method should return mock object. That would make it possible to interact with backend of the mock.

We have a case where we test our EMR step creation wrappers and want to change status of steps while we are polling them. For this we want to access mock backend. Currently the code snippet for this has to looks like this:

```
mock_emr_obj = moto.mock_emr()
with mock_emr_obj:
    do_something(...)
    emr_backend = mock_emr_obj.backends[self.aws_region]
    do_something_else_with_backend(...)
```

If `BaseMockAWS.__enter__()` returns `self`, the code can be rewritten with canonical context manager syntax:

```
with moto.mock_emr() as mock_emr_obj:
    do_something(...)
    emr_backend = mock_emr_obj.backends[self.aws_region]
    do_something_else_with_backend(...)
```

**Comment by spulec** [comment]
Thanks for opening. I agree and will set this as a feature request.

**Comment by spulec** [comment]
PR opened with https://github.com/spulec/moto/issues/1915
