### ISSUE TITLE
Realistic timers

### ISSUE THREAD

**Issue by tarekziade** [spulec/moto#192]
Creating an instance or any of these operations, can take quite some time.

It would be great if moto had a mode where it tries to make the API calls as "slow" as AWS.

**Comment by spulec** [comment]
Two ideas from #1940:

- Utilize [Boto events](https://botocore.amazonaws.com/v1/documentation/api/latest/topics/events.html)
- Use an approach similar to what Freezegun with the concept of [ticking forward time](https://github.com/spulec/freezegun#manual-ticks)

Either of these approaches would need to work with server-based mode.

**Comment by bblommers** [comment]
Moto 3.1.8 now contains a state manager, that would allow you to artificially slow down how fast Moto moves through states, like how long it takes to get from `initializing` to `ready`, etc.

The general documentation can be found here:
http://docs.getmoto.org/en/latest/docs/configuration/state_transition/index.html

Note that while the framework is in place, it still has to be implemented for every model separately. The documentation contains a list of models that currently support this.

Given the age of this ticket, I'm going to close this now. Please open a new issue if you have any questions around this, or if you'd like to see support for specific models.
