### ISSUE TITLE
create_image - possibility to mangle/set creation date (testing purposes)

### ISSUE THREAD

**Issue by Constantin07** [spulec/moto#1923]
I'm working on testing a cleanup script for AMI images.
For deleting images it looks for image count as well as creation date. e.g.

- keep last 3 images no matter how old
- keep images newer than 1 day

In test script I create new images (around 10) but I cannot test it properly because creation date is almost the same  and the deletion is skipped based on the second criteria above.

```
ami-4db63882 Name: project 1541429211 Description: Created from i-1776d2bedafa7591a Creation date: 2018-11-05T14:46:51.000Z
ami-96214ce5 Name: projec 1541429211 Description: Created from i-1776d2bedafa7591a Creation date: 2018-11-05T14:46:51.000Z
ami-4a994a27 Name: project 1541429211 Description: Created from i-1776d2bedafa7591a Creation date: 2018-11-05T14:46:51.000Z
ami-38fcdfc0 Name: project 1541429211 Description: Created from i-1776d2bedafa7591a Creation date: 2018-11-05T14:46:51.000Z
ami-ce1a7575 Name: project 1541429211 Description: Created from i-1776d2bedafa7591a Creation date: 2018-11-05T14:46:51.000Z
```

Is there any way to set/mangle the creation date of images ?

**Comment by spulec** [comment]
Closed as similar to https://github.com/spulec/moto/pull/1936
