### ISSUE TITLE
Snapshots deleted even when linked to existing AMIs

### ISSUE THREAD

**Issue by Constantin07** [spulec/moto#1928]
Current behaviour:

In the current implementation it's allowing to delete snapshots even when they are still linked to existing AMIs.

Expected behaviour:

It should error out that the snapshot is still being used, so a de-registration of AMI is required as prerequisite.

moto==1.3.7
boto==2.49.0
boto3==1.7.84
botocore==1.12.37

**Comment by spulec** [comment]
Thanks; setting as a feature request.
