### ISSUE TITLE
Nested attribute in FilterExpression raises ValueError "Invalid attribute name" while mocking dynamodb

### ISSUE THREAD

**Issue by gsmetak** [spulec/moto#1929]
I'm initializing the connection and the table like this

```python    
self.conn = boto3.resource('dynamodb')
self.table = self.conn.create_table(
            TableName="UserMoments",
            KeySchema=[
                {
                    'AttributeName': 'user_id',
                    'KeyType': 'HASH'
                },
                {
                    'AttributeName': 'created',
                    'KeyType': 'RANGE'
                }
            ],
            AttributeDefinitions=[
                {
                    'AttributeName': 'created',
                    'AttributeType': 'S'
                },
                {
                    'AttributeName': 'user_id',
                    'AttributeType': 'S'
                }
            ],
            ProvisionedThroughput={
                'ReadCapacityUnits': 123,
                'WriteCapacityUnits': 123
            },
        )
```

I add an item like this, among other properties:
```python
item = {}
item['sensor'] = {}
item['sensor']['end'] = 1541483780
item['user_id'] = "91393bed451c403c53f135be"
item['created'] = 1541479780
self.table.put_item(Item=item)
```

And then I make a query to the table, with my FilterExpression containing this:

` Attr("sensor.end").between(start, end) `

The error I get is this:

`ValueError: Invalid attribute name sensor.end`

And I see that the actual item is stored in this way:

`item = Item: {'Attributes': {'sensor': {'M': {'end': {'N': '1541483780'}}}, ... `

Am I missing something in the initial setup of moto?

I am using the latest versions for both moto and boto3.

**Comment by bblommers** [comment]
@gsmetak Can you verify whether this has been fixed already? I can't reproduce it anymore for moto >= 1.3.10

**Comment by spulec** [comment]
Going to close; let me know if someone is able to reproduce with the latest version.
