### ISSUE TITLE
Could python-jose 3.0.1 be used instead of <3.0.0 ?

### ISSUE THREAD

**Issue by andreclaro** [spulec/moto#1930]
Hello, 

Could we use python-jose 3.0.1 instead of <3.0.0 ?

https://github.com/spulec/moto/blob/90a62b56400251620684a094d85e458bc3abb17e/setup.py#L21

Thanks!
André Claro

**Comment by ajhodges** [comment]
There's two pending PRs to address this #1905 and #1927. One of these just needs to be merged...

**Comment by spulec** [comment]
Closed with https://github.com/spulec/moto/pull/1927
