### ISSUE TITLE
Application Autoscaling service

### ISSUE THREAD

**Issue by sinemetu1** [spulec/moto#1931]
Are there plans to add support for the [ApplicationAutoScaling](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/application-autoscaling.html) service?

Thanks!

**Comment by dawngerpony** [comment]
FYI I am now working on this, I have an immediate need to mock the following functions:

1. [`describe_scalable_targets`](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/application-autoscaling.html#ApplicationAutoScaling.Client.describe_scalable_targets)
1. [`register_scalable_target`](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/application-autoscaling.html#ApplicationAutoScaling.Client.register_scalable_target)

**Comment by bblommers** [comment]
An initial implementation is now available as of moto >= 1.3.15.dev925, thanks to @dawngerpony

**Comment by dawngerpony** [comment]
https://pypi.org/project/moto/1.3.15.dev925/
