### ISSUE TITLE
S3 backend missing *_replication_configuration functions / creating a bucket instead

### ISSUE THREAD

**Issue by shaepe-nc** [spulec/moto#1939]
Just bumped into an unsupported functionality of getting and putting replication configuration on an S3 bucket. 

Seems that calling the put_replication_configuration call ends up in creating a new bucket instead. 
Could track it down to "moto/s3/responses.py", into function "_bucket_response_put". Here it ends in the "else" block, creating a new bucket in the default region "us-east-1". 
Should that really be the intended behaviour for reasons I do not understand yet or would it be better to throw an NotImplemented exception here?

**Comment by spulec** [comment]
Sounds like we haven't implement this yet. Going to set as a feature request. Thanks!
