### ISSUE TITLE
Error when updating Cloudformation stack containing unsupported resources

### ISSUE THREAD

**Issue by grahamlyons** [spulec/moto#1966]
When updating a Cloudformation stack which contains a resource which contains a resource which isn't supported by the moto implementation then a `TypeError` is generated, complaining about not being able to unpack a `NoneType` object.

The error is thrown at the bottom of this block: https://github.com/spulec/moto/blob/ed861ec/moto/cloudformation/parsing.py#L500-L511

And this line actually generates the error: https://github.com/spulec/moto/blob/ed861ec/moto/cloudformation/parsing.py#L306-L307

The return site expects a tuple and tries to unpack it but as the resource isn't supported the  `parse_resource` function returns `None`: https://github.com/spulec/moto/blob/ed861ec/moto/cloudformation/parsing.py#L264-L270

It looks like the logic needs to be updated to catch that case, which the corresponding create function does: https://github.com/spulec/moto/blob/ed861ec/moto/cloudformation/parsing.py#L294-L296

**Comment by spulec** [comment]
Thanks; setting this as a bug.
