### ISSUE TITLE
IAM get access key last used not implemented

### ISSUE THREAD

**Issue by surfaslt** [spulec/moto#1971]
Using Boto3 like:
```
client = boto3.client('iam')
client.create_user(UserName="test_user")
key = client.create_access_key(UserName="test_user")
key_id = key.get('AccessKeyMetadata').get('AccessKeyId')
client.get_access_key_last_used(AccessKeyId=key_id)
```
throws: `NotImplementedError: The get_access_key_last_used action has not been implemented` because the method is not in `moto/iam/responses.py`

https://docs.aws.amazon.com/IAM/latest/APIReference/API_GetAccessKeyLastUsed.html

**Comment by surfaslt** [comment]
Raised pull request https://github.com/spulec/moto/pull/1972
I need some help with that if possible.

**Comment by spulec** [comment]
Closed with https://github.com/spulec/moto/pull/1972
