### ISSUE TITLE
Is it possible to mock calls to get different policies from AWS

### ISSUE THREAD

**Issue by pageholder** [spulec/moto#1974]
I'm currently trying to unit test a bunch of functions I created which get the account password policy from the iam client:
iam_client = boto3.client('iam')
pwdPolicy = iam_client.get_account_password_policy()

There is a bunch of these I'm using such as;
get_trail_status and get_event_selectors from the CloudTrail client.
get_bucket_acl and get_bucket_policy from the s3 client.
describe_metric_filters from the logs client.

I know this probably isn't the place to ask for help but thanks in advance!

**Comment by spulec** [comment]
I'm not sure I understand. You can add the decorators for each of these services; is that what you mean?
