### ISSUE TITLE
search job definition by name only in batch submit job method 

### ISSUE THREAD

**Issue by dedominicisfa** [spulec/moto#1976]
In the real aws, you can call the boto3 batch.submit_job method with a job definition name, without including the entire arn, nor the revision. If you include only the name, the latest revision is assumed. IN moto, in the BatchBackend class, the job definition name is searched by arn, or by name and revision. It should also be searched just by name, as the real aws does.

**Comment by spulec** [comment]
Thanks; setting this as a feature request.
