### ISSUE TITLE
Feature - S3 bucket to support transfer acceleration settings

### ISSUE THREAD

**Issue by gbataille** [spulec/moto#1987]
Implement
* `get_bucket_accelerate_configuration`
* `put_bucket_accelerate_configuration`

Bonus
* If the client connection is opened with `botocore.config.Config(s3={'use_accelerate_endpoint': True}`, then `generate_presigned_url` should return an url with the transfer accelerated endpoint

--> I'll try to give it a go this month

**Comment by spulec** [comment]
Thanks; setting as a feature request.
