### ISSUE TITLE
Health of the project?

### ISSUE THREAD

**Issue by adamdavis40208** [spulec/moto#1995]
PRs have been piling up since late October -- 35 or so.

Many of these are submitted, but either don't pass coveralls or the build process. 

Some suggestions: 

* Adding https://github.com/probot/stale to this repo. Labels can be used to keep around issues/PRs that may just need extra time to merge/waiting on the next release (so valid work doesn't get closed)

* Closing PRs after 30 days that don't meet checks.

* Add to the amount of people able to merge/review PRs

**Comment by grahamlyons** [comment]
I am also concerned about the maintenance of moto. It's an awesome project: I use it a lot and recommend it whenever I can, but it does seem that there are a lot of pull requests and issues building up.

**Comment by spulec** [comment]
Thanks for opening.

Agree that the progress on the project has been inconsistent over time between our volunteers.

As a general rule, if anyone has reviewed a couple PRs or helped with some issues, I am happy to give them more access. We have a lot of issues and PRs so could definitely use help with reviews.

I'm going to keep this issue open to look into https://github.com/probot/stale

Other things that might help are https://github.com/spulec/moto/issues/1659 and https://github.com/spulec/moto/issues/2211.

Open to other ideas as well.

**Comment by spulec** [comment]
Going to close this for now and focus on #1659 going forward.
