### ISSUE TITLE
Unable to mock ses

### ISSUE THREAD

**Issue by fedecastelli** [spulec/moto#1998]
Hi there,

I'm writing unit tests for my project and I need to mock SES api. I've found this project and reading the documentation and seeing unit tests written, I thought that it's perfect for what I have to do.
So I wrote this code:
```
@mock_ses
def test_send_html_email():

    import boto3
    conn = boto3.client("ses", region_name="us-east-1")
    kwargs = dict(
        Source="no-reply@example.com",
        Destination={
            "ToAddresses": ["unittest@example.com"]
        },
        Message={
            "Subject": {"Data": "test subject"},
            "Body": {"Html": {"Data": "test body"}}
        }
    )
    conn.send_email(**kwargs)
```

Everything is working fine but I always receive the email that I've sent. I think that this project allows you to simulate the email sent and gives you the response. So, what am I doing wrong?

**Comment by fedecastelli** [comment]
I can't find any workaround into the issues you've linked me.

**Comment by kgutwin** [comment]
I'm sorry, I was in a hurry earlier. Try adding `boto3.setup_default_session()` right after the `import boto3` line in your test function. This regenerates the default session for Boto, which is sometimes needed after moto is started.

**Comment by georgepsarakis** [comment]
@fedecastelli do you perhaps mean that mocking is not working as expected and the API request is sent to the AWS SES service?

**Comment by fedecastelli** [comment]
Yes, @georgepsarakis.

**Comment by fedecastelli** [comment]
I tried to use the suggestion of @kgutwin and it's working now. Thank you! I can close the issue.
