### ISSUE TITLE
Problems with mock_s3, OrdinaryCallingFormat and bucket.delete_keys

### ISSUE THREAD

**Issue by horida** [spulec/moto#2001]
I use `boto.connect`_s3 (boto==2.34.0) with `is_secure=True` and `calling_format` `OrdinaryCallingFormat`. Which works perfectly.
During my tests, when calling `deleted_keys` on a `s3.bucket.Bucket` object inside a `mock_s3bucket_path` context manager, with a key of  name `myfolder/name`, I encounter an issue with moto==0.3.9:

in `moto/s3/responses.py`:
```python
167         if request.path == u'/?delete':                                                                                                
168             return self._bucket_response_delete_keys(request, bucket_name, headers)                                                    
```

Here request.path is `'/mybucket/?delete'`

The test works though using `mock_s3` instead of `mock_s3bucket_path` and without `OrdinaryCallingFormat` when connecting. Unfortunately, this configuration does not work outside the test, i.e. moto.

Is there a reason against using `if request.path.endswith('/?delete')`?

**Comment by spulec** [comment]
This should have been fixed with https://github.com/spulec/moto/pull/518, but feel free to reopen if it isn't.
