### ISSUE TITLE
Support Tags in Secrets Manager

### ISSUE THREAD

**Issue by norton120** [spulec/moto#2004]
## Why?
Currently secretsmanager `describe_secret` returns a hardcoded set of empty tags for the secret. If tags are an important part of your deployment process this breaks :( 

## What? 
persist a`Tags` list passed in `create_secret` to the `describe_secret` method. 

## Who will this help? 
- people who use tags in secrets manager

**Comment by sepulworld** [comment]
Thanks @norton120 Ill add tags to this PR which is waiting to be merged. https://github.com/spulec/moto/pull/1898

**Comment by spulec** [comment]
Closed with https://github.com/spulec/moto/pull/1898
