### ISSUE TITLE
Implement cloudwatch pagination

### ISSUE THREAD

**Issue by Siebjee** [spulec/moto#2010]
The paginator next token of the cloudwatch response provides a hardcoded NextToken. Boto core states: `boto.core.exceptions.PaginationError: Error during pagination: The same next token was received twice...`

Moto test:
```python
from my_script import get_metrics

@mock_cloudwatch
def test_get_metrics():
  region = 'eu-west-1'
  instance = 'i-abcdef12345'
  metrics_namespace = 'test_space'
  get_metrics(metrics_namespace, instance, region)
```

my_script:
```python
def get_metrics(metrics_namespace, instance, region):
  cloudwatch = boto3.client('cloudwatch', region)
  
  instance_metrics = list()
  paginator = cloudwatch.get_paginator('list_metrics')
  pages = paginator.paginate(Namespace=metrics_namespace)

  for page in pages:
    if page['ResponseMetadata']['HTTPStatusCode'] != 200:
      raise Exception('ERROR: {}'.format(page))
    for metric in page['Metrics']
      for key in metric['Dimensions']:
        if key['Name'] == 'InstanceId' and key['Value'] == instance:
          instance_metrics.append(metric)

  return instance_metrics
```

**Comment by aandis** [comment]
+1. More details on this - 

- Moto version - `1.3.8`
- Execption - `botocore.exceptions.PaginationError: Error during pagination: The same next token was received twice: {'NextToken': '\n            96e88479-4662-450b-8a13-239ded6ce9fe\n        '}`
- To reproduce - 
```python
cloudwatch = boto3.resource('cloudwatch')
metric = cloudwatch.Metric(namespace, metric_name)
metric.put_data(...) # This triggers the exception.
```

- The token is hardcoded [here](https://github.com/spulec/moto/blob/8cb4db1896521af99ff295b028f604c6ab599401/moto/cloudwatch/responses.py#L330).
- Getting rid of the token from the response template fixes the issue. This is what I'm temporarily using in my [fork](https://github.com/aandis/moto/commit/6f4b12cfea458840c6957cb3a2d87a964a5a844a).

**Comment by spulec** [comment]
Thanks; setting this issue as a feature request to implement proper pagination in cloudwatch
