### ISSUE TITLE
Lambda invoke fails to run and returns 202 with invalid CRC32

### ISSUE THREAD

**Issue by MateuszKubuszok** [spulec/moto#2034]
When I tried to use awslambda to mock calling lambda from Java SDK I've got the exception with the following message:

    Unable to execute HTTP request: Client calculated crc32 checksum didn't match that calculated by server side

When I looked into logs I've seen that moto throws error:

    FileNotFoundError: [Errno 2] No such file or directory

and the result is

```
{
    "StatusCode": 202,
    "FunctionError": "Handled"
}
```

which explains the invalid CRC32.

After struggling with a problem for a day I've decided to give up and ask for help. My complete setup (lamba function, how I upload it, how I run server) is in this gist: https://gist.github.com/MateuszKubuszok/4965f272200bc942a9ac5ef9836fc957 . Is it a bug or did I configured something wrong? I wasn't able to fund any clue in docs, code and issues list.

**Comment by luksfarris** [comment]
For anyone struggling with this, see my comment to this related issue:
https://github.com/spulec/moto/issues/2260#issuecomment-508676953

**Comment by spulec** [comment]
I believe @luksfarris comment is correct and should fix this. Feel free to reopen if that is not the case.
