### ISSUE TITLE
Does moto work with aioboto3?

### ISSUE THREAD

**Issue by anshitmt** [spulec/moto#2039]
I am using moto to mock s3 calls in my test cases. 

Following is the code snippet:

```
# class code (decorated with mock_s3) and having setUp method to initialise bucket SOME_BUCKET

def test_something(self):
    async def test_s3_upload():
        s3 = boto3.resource("s3")
        s3_object = s3.Object(SOME_BUCKET, SOME_PATH)
        s3_object.put(Body=bytes("haha", "utf-8")) # this works

        async with aioboto3.resource('s3', use_ssl=False, endpoint_url=BaseConfig.S3_ENDPOINT_URL) as s3:
            s3_object = s3.Object(SOME_BUCKET, SOME_PATH)
            await s3_object.put(Body=bytes("haha", "utf-8")) # this doesn't

    self.loop.run_until_complete(test_s3_upload())
```

aioboto3 is not able to work correctly. Looks like it is not able to connect to mocked s3 server created by moto. It finds the bucket-name in aws.

Is this a known issue? If yes, is there a way to get around this as of now?

**Comment by spulec** [comment]
My guess is that this won't work easily due to the nature of the monkey-patching. I'd be excited for someone to dig into it thought.

**Comment by zhammer** [comment]
@spulec can you expand on:
> this won't work easily due to the nature of the monkey-patching

would maybe want to experiment with getting this to work for a project i'm working on. some background info would be helpful!

**Comment by spulec** [comment]
Now that I think about it, using Moto with the standalone server mode should be fine with this.

For non-server mode, we are using all singletons in the backends so I think it could result in weird behavior. I don't have a lot of experience with this though. Curious to hear any results. I am going to close this out for now.

**Comment by caniko** [comment]
Can we re-open this issue @spulec, and rename to "`aioboto3` support"? It is something I would've needed, and I think it makes sense to support. Unless you have an alternative.
