### ISSUE TITLE
Moto doesn't implement default limits on dynamoDB return

### ISSUE THREAD

**Issue by shade34321** [spulec/moto#2042]
According to the [AWS docs](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Scan.html) a DynamoDB scan will return data up to the maximum data size limit (1MB) or to the limit if it's set. Currently Moto doesn't do this and returns everything or the limit if set. There are two primary solutions for adding this feature.
1) A quick and dirty fix is to set a default limit. 
2) The correct way is to check the size and return up to 1MB but this can get quite complicated but doable. We could check the sizes of the items as they are being inserted and store the size with the item somehow or check the sizes of the items within the trim method and once we reach the 1 MB limit return.

I have done 1 already but have a few questions and still need to write tests. I could probably do the second option but it would take a big longer.

[Here](https://github.com/shade34321/moto/blob/implement_scan_limits/moto/dynamodb2/models.py#L674-L676) is my rudimentary implementation of the first option. It sets a default value of 1K for the limit and if you try and set the limit to something greater than that it will set it back to 1K. This will mock AWS's behavior of returning a max of "1 MB" regardless of limit. If you're ok with this I can add the tests and put up the PR for this.

I did have some questions around what some of these other scan functions are doing specifically the two below.
https://github.com/shade34321/moto/blob/implement_scan_limits/moto/dynamodb2/models.py#L895-L910
https://github.com/shade34321/moto/blob/implement_scan_limits/moto/dynamodb2/responses.py#L487-L537 

Thanks!

**Comment by spulec** [comment]
Thanks; setting as a feature request.
