### ISSUE TITLE
mock_dynamodb2 isn't working

### ISSUE THREAD

**Issue by ericman93** [spulec/moto#2043]
I have multiple test classes and they all are inherited from a base class In my base class I have `mock_dynamodb2` decorator, and inside the `setUpClass` method I can see all tables from AWS.
  When using
  
  ```
  mock_dynamo = mock_dynamodb2()
  mock_dynamo.start()
  ```
  everything is working as expected

**Comment by spulec** [comment]
Sorry, I'm having trouble understanding what the problem is. Can you give some example code of what isn't working and what you expect to happen?
