### ISSUE TITLE
mock_dynamodb2 require ProvisionedThroughput when creating table with BillingMode, PAY_PER_REQUEST

### ISSUE THREAD

**Issue by chuajiesheng** [spulec/moto#2046]
# Description

When using `'BillingMode': 'PAY_PER_REQUEST'` to create a DynamoDB table, `ProvisionedThroughput` is not a required key. moto check for `ProvisionedThroughput` by referencing they key directly in [moto/dynamodb2/responses.py#L99](https://github.com/spulec/moto/blob/142fc65260698a298d05e2e379183ce37fbc741a/moto/dynamodb2/responses.py#L99)

[From https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_CreateTable.html#DDB-CreateTable-request-ProvisionedThroughput]
Represents the provisioned throughput settings for a specified table or index. The settings can be modified using the UpdateTable operation.

If you set BillingMode as PROVISIONED, you must specify this property. If you set BillingMode as PAY_PER_REQUEST, you cannot specify this property. 

# Code

```
schema = {
        'TableName': table_name,
        'KeySchema': [
            {
                'AttributeName': 'uuid',
                'KeyType': 'HASH'  # Partition key
            },
            {
                'AttributeName': 'epoch',
                'KeyType': 'RANGE'  # Sort key
            }
        ],
        'AttributeDefinitions': [
            {
                'AttributeName': 'uuid',
                'AttributeType': 'S'
            },
            {
                'AttributeName': 'epoch',
                'AttributeType': 'N'
            },

        ],
        'BillingMode': 'PAY_PER_REQUEST'
    }
dynamodb = boto3.resource('dynamodb', region_name='ap-southeast-1')
table = dynamodb.create_table(**schema)
```

# Error

```
self = <moto.dynamodb2.responses.DynamoHandler object at 0x10a24c898>

    def create_table(self):
        body = self.body
        # get the table name
        table_name = body['TableName']
        # get the throughput
>       throughput = body["ProvisionedThroughput"]
E       KeyError: 'ProvisionedThroughput'

venv/lib/python3.7/site-packages/moto/dynamodb2/responses.py:99: KeyError
```

# Packages

```
asn1crypto==0.24.0
aws-xray-sdk==0.95
boto==2.49.0
boto3==1.9.86
botocore==1.12.86
certifi==2018.11.29
cffi==1.11.5
chardet==3.0.4
cryptography==2.5
docker==3.7.0
docker-pycreds==0.4.0
docutils==0.14
ecdsa==0.13
future==0.17.1
idna==2.8
Jinja2==2.10
jmespath==0.9.3
jsondiff==1.1.1
jsonpickle==1.1
MarkupSafe==1.1.0
mock==2.0.0
moto==1.3.7
pbr==5.1.2
pocketsphinx==0.1.3
pyaml==18.11.0
pycparser==2.19
pycryptodome==3.7.3
python-dateutil==2.7.5
python-jose==2.0.2
pytz==2018.9
PyYAML==3.13
requests==2.21.0
responses==0.10.5
s3transfer==0.1.13
six==1.12.0
urllib3==1.24.1
websocket-client==0.54.0
Werkzeug==0.14.1
wrapt==1.11.1
xmltodict==0.11.0
```

**Comment by shiba24** [comment]
Thank you for the report - I pick up this bug. Now under implementation.

**Comment by shiba24** [comment]
Now merged! Please close this issue.

**Comment by luv-hunggk** [comment]
@shiba24 
I looking at version 1.3.8 don't have fixed this problem.
when do you release this version?

**Comment by chuajiesheng** [comment]
@luv-hunggk 1.3.8 was released on 23 Apr while this commit was merge on the 30 Apr. I guess you have to wait for the next release.

**Comment by luv-hunggk** [comment]
Thank you. I will wait.
I can know, when do you will release this problem? Because a month has passed and I have not seen the new version.
