### ISSUE TITLE
Services list in documentation is incomplete

### ISSUE THREAD

**Issue by seanf** [spulec/moto#2051]
The table in the [README on GitHub](https://github.com/spulec/moto#readme) includes quite a few mock services which aren't listed in the [docs](http://docs.getmoto.org/en/latest/#currently-implemented-services) ([source](https://github.com/spulec/moto/blob/master/docs/index.rst#currently-implemented-services)), such as

* ACM
* CloudwatchEvents
* Cognito Identity
* Cognito Identity Provider
* DynamoDB
* DynamoDB2
* ECR
* ELBv2
* IoT
* Logs
* etc etc

**Comment by spulec** [comment]
Closed with https://github.com/spulec/moto/pull/2258
