### ISSUE TITLE
KMS module returns iso8601 dates instead timestamp as per official API reference

### ISSUE THREAD

**Issue by gchiesa** [spulec/moto#2052]
I'm using moto version:
```
Name: moto
Version: 1.3.7
Summary: A library that allows your python tests to easily mock out the boto library
Home-page: https://github.com/spulec/moto
Author: Steve Pulec
Author-email: spulec@gmail.com
License: Apache
Location: /usr/local/lib/python2.7/site-packages
Requires: requests, backports.tempfile, Jinja2, boto3, werkzeug, cfn-lint, python-dateutil, mock, botocore, docker, jsondiff, responses, cryptography, six, idna, pytz, boto, PyYAML, aws-xray-sdk, xmltodict, python-jose
Required-by: 
```

The KMS module is not returning dates in the format specified in the AWS API Reference (https://docs.aws.amazon.com/kms/latest/APIReference/API_KeyMetadata.html#KMS-Type-KeyMetadata-CreationDate)

The official API uses ```timestamp``` for the dates but moto returns ```iso_8601_datetime_without_milliseconds```

That causes issues with mocking when use moto[server] with statically typed languages that use mappers and expect the date fields with a timestamp.

**Comment by georgepsarakis** [comment]
From the [boto3 example output](https://github.com/boto/botocore/blob/3b2a60b963bc48a41ecfc9d9f010a976c592f0bc/botocore/data/kms/2014-11-01/examples-1.json#L78) it seems that the datetime format is correct (as returned by [iso_8601_datetime_without_milliseconds](https://github.com/spulec/moto/blob/1095b7d94bdd46b1bb2dbff0122994baf94f2eeb/moto/core/utils.py#L183)). Have you observed differences with the actual AWS response?

**Comment by gchiesa** [comment]
You can reproduce it easily with: 
```
21:32 $ aws kms describe-key --key-id alias/aws/s3
{
    "KeyMetadata": {
        "Origin": "AWS_KMS", 
        "KeyId": "*******-3441-4073-8189-***********", 
        "Description": "Default master key that protects my S3 objects when no other key is defined", 
        "KeyManager": "AWS", 
        "Enabled": true, 
        "KeyUsage": "ENCRYPT_DECRYPT", 
        "KeyState": "Enabled", 
        "CreationDate": 1550608350.021, 
        "Arn": "arn:aws:kms:eu-west-1:************:key/*******-3441-4073-8189-***********", 
        "AWSAccountId": "************"
    }
}
```
*** = masked info

as you can see the creation date is a timestamp, and also the documentation mentioned in the ticket reports the AWS API returns a timestamp and not a iso8601 date

**Comment by spulec** [comment]
Fixed with https://github.com/spulec/moto/pull/2193
