### ISSUE TITLE
New pip release?

### ISSUE THREAD

**Issue by mnylen** [spulec/moto#2065]
Would it be possible to get a new pip release? The latest one (1.3.7) is from Nov 2018 and there has been a lot of improvements made since then.

Currently I'm building a docker image out of the master branch manually to run the server with these changes, but would be more convenient to be able to just install from pip directly.

**Comment by rbu** [comment]
@spulec @JackDanger What would be needed to cut a new release?

**Comment by tmbo** [comment]
What is the plan here, you merged some great and needed fixes into master - would be great to use them by pulling a release from pypi.

Are there any plans for a near-future release?

**Comment by mikegrima** [comment]
I agree! However, that would be a question for @spulec as he is the main owner of this repo.

**Comment by spulec** [comment]
Just released `1.3.8`. Apologies for the delay.

**Comment by tmbo** [comment]
Thanks a lot for you ongoing efforts 🚀👑

**Comment by tutordelphia** [comment]
What changed in 1.3.8? I didn't see anything in the changelog. Thanks. 

Actually, I found my answer looking through https://github.com/spulec/moto/compare/1.3.7..1.3.8 but it may be good to add in a summary anyway since it looks like a lot more features were implemented.
