### ISSUE TITLE
Wrong data type for creation date for kms create key

### ISSUE THREAD

**Issue by woohooyayaya** [spulec/moto#2072]
I'm using the java sdk. I tried to make a call to local moto kms server but I got the following error. 

Caused by: com.amazonaws.SdkClientException: Unable to unmarshall response (Invalid format: "2015-01-01 00:00:00" is malformed at " 00:00:00"). Response Code: 200, Response Text: OK

It appears that the returned date is in a wrong format. 

This is what I got from moto: 
{
    "KeyMetadata": {
        "Arn": "arn:aws:kms:us-east-1:0123456789012:key/acf199ae-dbf8-47c0-8801-9f74ec1f1c13",
        "CreationDate": "2015-01-01 00:00:00",
        "AWSAccountId": "0123456789012",
        "KeyState": "Enabled",
        "Enabled": true,
        "KeyId": "acf199ae-dbf8-47c0-8801-9f74ec1f1c13"
    }
}

This is what I got from kms: 

{
    "KeyMetadata": {
        "Arn": "arn:aws:kms:us-east-1:285746992305:key/4bcd2729-89f2-4c0c-b565-b31d87eebb14",
        "Description": "",
        "KeyState": "Enabled",
        "Enabled": true,
        "CreationDate": 1551129207.775,
        "KeyId": "4bcd2729-89f2-4c0c-b565-b31d87eebb14",
        "AWSAccountId": "285746992305",
        "Origin": "AWS_KMS",
        "KeyManager": "CUSTOMER",
        "KeyUsage": "ENCRYPT_DECRYPT"
    }
}

Can you please fix this? Thanks a lot.

**Comment by spulec** [comment]
Fixed with https://github.com/spulec/moto/pull/2073
