### ISSUE TITLE
Certificate Authority support in AWS IoT

### ISSUE THREAD

**Issue by sahilkoladiya** [spulec/moto#2079]
IoT is missing support for following APIs.

list_things, register_ca_certificate, register_certificate, describe_ca_certificate, list_certificates_by_ca, delete_ca_certificate, update_ca_certificate, get_registration_code

Without this APIs, it's hard to mock a service via moto when someone gets device certificate signed by their own certificate authority vs relying in AWS IoT default CA.

**Comment by spulec** [comment]
Thanks; setting as a feature request.
