### ISSUE TITLE
Cognito IDP - Allow create pool and pool client to receive desired ID

### ISSUE THREAD

**Issue by nykolaslima** [spulec/moto#2094]
In real applications probably the pool id and client id are going to be configured through some configuration file or environment variables. It means that applications are going to be coded to load these configurations with a pre defined value.

When setting up Cognito IDP dependent tests, when you are creating a user pool or a user pool client the ID is generated by the moto internals and there is no option to override it. It requires the production code to be changed in order to receive "runtime" pool and client ids in order to be able to test it.

```
def create_user_pool(self, name, extended_config):
...

def create_user_pool_client(self, user_pool_id, extended_config):
...
``` 
https://github.com/spulec/moto/blob/master/moto/cognitoidp/models.py#L306
https://github.com/spulec/moto/blob/master/moto/cognitoidp/models.py#L350

Would it be possible to add an extra parameter into these methods in order to receive an optional `id`?
There is another way to override the `id`?

I opened this issue in order to discuss if it would be possible and what are the possible compatibility issues due a method parameter contract change. If we agree on a solution, I could implement it and open a PR.

**Comment by spulec** [comment]
As a general rule we don't like to do this. We like to keep the APIs the same as AWS.

Are you able to have your application read it as an environment variable and then have your test code write the id as an environment variable after moto creates it?

**Comment by bblommers** [comment]
I'm going to close this due to a lack of response. @spulec's suggestion would be the way to tackle this though - create a userpool within Moto, and mock/change your configuration in such a way that it reads the ID of the created pool.
