### ISSUE TITLE
[SWF] DecisionTask previousStartedEventId always 0

### ISSUE THREAD

**Issue by crisperson** [spulec/moto#2107]
**Repro**: Unfortunately we can't share our internals, but this should be reproducible with any workflow definition -- given a workflow with steps A->B->C notice that you should continuously spawn the "A" step at each decision task (the proceedings from A->B, B->C all work correctly). 

**What**: DecisionTasks are always populated with a previousStartedEventId of 0, and based on some quick investigation it doesn't look like that value is updated. 

**Expected**: Based on the AWS documentation here (https://docs.aws.amazon.com/amazonswf/latest/apireference/API_PollForDecisionTask.html) we rely on the previousStartedEventId to tell us whether we have already processed events on subsequent polls. With it always being zero our local mocks end up handling the initial workflow started event every time decision tasks are polled and we end up getting into this recursive state. 

**What Happens**: The workflows proceed and decision tasks are still created, but because they never have a new previousStartedEventId set we lose the PollForDecisionTask feature discussed above.

**Version**: 1.3.7. We run it in the standalone server mode.

**Comment by spulec** [comment]
Yes, it looks like we haven't implemented this. Setting this issue as a feature request.

Thanks!
