### ISSUE TITLE
Coveralls showing incorrect coverage changes.

### ISSUE THREAD

**Issue by markchalloner** [spulec/moto#2109]
Coveralls seems to show incorrect changes in coverage leading to PRs being falsely tagged as failing checks. This:

* makes merging harder for maintainers who need to decide to merge despite the apparent decrease in coverage,
* means valid PRs are less likely to be accepted,
* and blocks the suggestion in #1995 to auto-close stale contributions

Example of incorrect coverage changes: [down by 30% on a 9 line code change](https://github.com/spulec/moto/pull/2082).

I suspect that the Coveralls is simply comparing all the code at the HEAD of the branch against the code at the HEAD of the master (in this case the branch diverges from master 16 days ago) meaning coverage decrease comes from missing files.

A better solution would be to compare the code at the HEAD of the [pull/merge ref](https://github.com/spulec/moto/tree/pull/2082/merge) (which stays up to date with master).

**Comment by spulec** [comment]
Thanks. Going to close this in favor of https://github.com/spulec/moto/issues/2211 where we will drop or changeup coveralls.
