### ISSUE TITLE
moto can't find key when using multiprocessing

### ISSUE THREAD

**Issue by jennyfolkesson** [spulec/moto#2111]
Hi, I was trying to upload images with boto3 with multiprocessing. With real data it runs fine but  testing with moto failed, so I was hoping you could help me.
A bit simplified, my code looks like this:

```buildoutcfg
import boto3
import cv2
import concurrent.futures
import glob
from moto import mock_s3
import numpy as np
import numpy.testing
import os
from testfixtures import TempDirectory
import unittest


def upload_im(key_file_path, bucket_name='testing'):
    """
    Upload serialized image to S3 storage after checking that key
    doesn't already exist.
    """
    (key, file_path) = key_file_path
    im = cv2.imread(file_path, cv2.IMREAD_ANYDEPTH)
    # Create new client
    s3_client = boto3.client('s3')
    # Make sure image doesn't already exist
    response = s3_client.list_objects_v2(
        Bucket=bucket_name,
        Prefix=key,
    )
    if response['KeyCount'] == 0:
        res, im_bytes = cv2.imencode('.png', im)
        # Upload slice to S3
        s3_client.put_object(
            Bucket=bucket_name,
            Key=key,
            Body=im_bytes.tostring(),
        )


def multiprocess_upload(data_path, s3_dir):
    file_paths = glob.glob(os.path.join(data_path, "*.png"))
    keys = []
    for f in file_paths:
        keys.append("/".join([s3_dir, os.path.basename(f)]))
    with concurrent.futures.ProcessPoolExecutor(max_workers=1) as ex:
        ex.map(upload_im, zip(keys, file_paths))
    # for key_file_path in zip(keys, file_paths):
    #     upload_im(key_file_path)


class TestUploader(unittest.TestCase):

    def setUp(self):
        """
        Set up temporary test directory and mock S3 bucket connection
        """
        # Create temporary directory and write temp image
        self.tempdir = TempDirectory()
        self.temp_path = self.tempdir.path
        # Temporary frame
        self.im = np.ones((10, 15), dtype=np.uint16)
        self.im[2:5, 3:12] = 10000
        # Save test files
        for c in range(5):
            file_name = 'img_{}.png'.format(c)
            file_path = os.path.join(self.temp_path, file_name)
            cv2.imwrite(file_path, self.im)

        # Setup mock S3 bucket
        self.s3_dir = 'test_dir'
        self.mock = mock_s3()
        self.mock.start()
        self.conn = boto3.resource('s3', region_name='us-east-1')
        self.bucket_name = 'testing'
        self.conn.create_bucket(Bucket=self.bucket_name)

    def tearDown(self):
        """
        Tear down temporary folder and files and stop S3 mock
        """
        TempDirectory.cleanup_all()
        self.mock.stop()

    def test_multiprocess_upload(self):
        multiprocess_upload(self.temp_path, self.s3_dir)
        for c in range(5):
            file_name = 'img_{}.png'.format(c)
            key = "/".join([self.s3_dir, file_name])
            byte_string = self.conn.Object(
                self.bucket_name, key).get()['Body'].read()
            # Construct an array from the bytes and decode image
            im_encoded = np.fromstring(byte_string, dtype='uint8')
            im = cv2.imdecode(im_encoded, cv2.IMREAD_ANYDEPTH)
            # Assert that contents are the same
            self.assertEqual(im.dtype, np.uint16)
            numpy.testing.assert_array_equal(im, self.im)
```

When running multiprocess_upload sequentially it works (commented out code at bottom of function), but this is the error I get when using multiprocessing:

Traceback (most recent call last):
  File "/Users/jenny.folkesson/Code/uploader_tests.py", line 92, in test_multiprocess_upload
    self.bucket_name, key).get()['Body'].read()
  File "/Users/jenny.folkesson/miniconda3/envs/py36/lib/python3.6/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/Users/jenny.folkesson/miniconda3/envs/py36/lib/python3.6/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/Users/jenny.folkesson/miniconda3/envs/py36/lib/python3.6/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/jenny.folkesson/miniconda3/envs/py36/lib/python3.6/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchKey: An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.

I'm using versions:
boto3: 1.7.84
moto: 1.3.6

Thank you in advance.

**Comment by dargueta** [comment]
Moto holds S3 keys in processes' memory. Unfortunately, you can't use multiprocessing since processes don't share memory. As soon as your the worker exits, all the files it "uploaded" disappear. I haven't tested this but you *might* be able to do this when using [server mode](http://docs.getmoto.org/en/latest/docs/server_mode.html).

**Comment by jennyfolkesson** [comment]
Thank you @dargueta. Since it works with boto3 + real data I made the decision to patch the multiprocessing part of my tests to make it work with moto.
Here's my mock workaround in case anyone else is having the same issue.
https://github.com/czbiohub/imagingDB/blob/master/imaging_db/images/tiffolder_splitter_tests.py#L42
