### ISSUE TITLE
fixed IP for instances

### ISSUE THREAD

**Issue by tarekziade** [spulec/moto#212]
When generating instances with Moto, they all get a fixed IP address (46.51.219.63) 

I would like to be able to configure that address because in my tests, I have another mock server that mimics an AWS box that's supposedly created, and my journey continues :)

**Comment by bbangert** [comment]
We're developing a AWS load tester. We need to generate many instances, perferably with small differences (the IP address). It'd be nice to be able to specify alternate IP's for the mock instances.

**Comment by spulec** [comment]
I just pushed https://github.com/spulec/moto/commit/dd5cab8c6382ffe3800e41dbf909f6006a8d6c54 which will at least return a random IP for different network interfaces.

I'm open to additional ideas, but am generally -0 on anything that would require additional configuration/APIs beyond normal boto usage.

**Comment by spulec** [comment]
The other way to do this is to manually modify the IP address in memory after creation by importing `ec2_backends`.
