### ISSUE TITLE
Use arbitrary region for batch

### ISSUE THREAD

**Issue by darrenleeweber** [spulec/moto#2138]
To be sure that moto is actually mocking boto3 calls, I want to use an arbitrary AWS region that does not exist, e.g. `us-west-10` or any other string that matches a region pattern (if necessary).  I ran into a case where the decorators were not applied to pytest fixtures and it actually ran and created test fixture infrastructure on AWS (not cool).  So, in paranoia mode, I want to dev/test some pytest code with no network connection and a bogus AWS region.  But...
```
self = <moto.batch.responses.BatchResponse object at 0x7f07188c3f98>

    @property
    def batch_backend(self):
        """
        :return: Batch Backend
        :rtype: moto.batch.models.BatchBackend
        """
>       return batch_backends[self.region]
E       KeyError: 'us-west-10'

.venv/lib/python3.7/site-packages/moto/batch/responses.py:21: KeyError
```

```
# pyproject.toml
[tool.poetry.dependencies]
python = "^3.7"
boto3 = "^1.9"
botocore = "^1.12"
```

```
$ pip freeze | grep oto
boto==2.49.0
boto3==1.9.126
botocore==1.12.126
moto==1.3.7
```

**Comment by spulec** [comment]
You can try using the gov region (or china) or another region that you don't have access to. As our goal is to mimic AWS and this could lead to other issues, I don't see us implementing it.
