### ISSUE TITLE
Add owner-id to filters for EC2 Model "Snapshot" ***PR is up and tests pass!!!***

### ISSUE THREAD

**Issue by jeffery75** [spulec/moto#2141]
This is not a bug, but a feature request.  I am opening this issue in order to reference it with the PR that I am submitting.

Basically this is a simple two line addition to allow `owner-id` to be a filter when searching on the EC2 model for an Snapshot.

**Update: May 24, 2019**
This issue and PR have been up for quite some time.  The tests pass and I sure would like to be able to use the code.  I have received no feedback so far.  What does it take to get this done?

**Comment by jeffery75** [comment]
My PR is finally working.  Would be great if someone is available to review and approve!

**Comment by jeffery75** [comment]
Thank you Terry!

**Comment by jeffery75** [comment]
@terrycain Thank you again for reviewing & merging.  I'd really love to use this code soon.  Can you tell me when the next release will be?  I cannot seem to find any information regarding a schedule or how to request a release.

**Comment by terrycain** [comment]
No clue on release. Create an issue and tag spulec for a release I think

**Comment by spulec** [comment]
Closed with https://github.com/spulec/moto/pull/2142
