### ISSUE TITLE
creating rds with option group 

### ISSUE THREAD

**Issue by tallyl** [spulec/moto#2183]
Seems to be ignoring when creating an rds with an option group - seems to be ignoring the option group and it isnt displayed in the response 
or when using describe 
code example : 

@mock_ec2
    def __subnet_list(self):
        ec2 = boto3.client('ec2', region_name='us-east-1')
        subnet_list = []
        for subnet in ec2.describe_subnets()["Subnets"]:
            # print(subnet["SubnetId"])
            subnet_list.append(subnet["SubnetId"])
            return subnet_list

    @mock_rds2
    def __setup(self):
        subnet_list = self.__subnet_list()
        rds = boto3.client('rds', region_name='us-east-1')
        response = rds.create_db_parameter_group(DBParameterGroupName="pg", DBParameterGroupFamily="oracle-se2-12.2", Description="Test")
        response = rds.create_option_group(OptionGroupName="og", EngineName="oracle-se", MajorEngineVersion="11.2", OptionGroupDescription="Test")
    
        response = rds.create_db_subnet_group(DBSubnetGroupName="dbsg", SubnetIds=subnet_list, DBSubnetGroupDescription="Text")
        response = rds.create_db_instance(DBName="TestDB", DBInstanceIdentifier="TestDB", DBInstanceClass="db.t2.micro", OptionGroupName="og", Engine="oracle-se2", MultiAZ=False,
                                          StorageType="gp2", AllocatedStorage=10, LicenseModel="bring-your-own-license", MasterUsername="oracle", MasterUserPassword="oracle",
                                          Port=1521, DBSubnetGroupName="dbsg")
                                          # DBParameterGroupName="tally", DBSubnetGroupName="subnet")

response : 

{'DBInstance': {'DBInstanceIdentifier': 'TestDB', 'DBInstanceClass': 'db.t2.micro', 'Engine': 'oracle-se2', 'DBInstanceStatus': 'available', 'MasterUsername': 'oracle', 'DBName': 'TestDB', 'Endpoint': {'Address': 'TestDB.aaaaaaaaaa.us-east-1.rds.amazonaws.com', 'Port': 1521}, 'AllocatedStorage': 10, 'PreferredBackupWindow': '03:50-04:20', 'BackupRetentionPeriod': 1, 'DBSecurityGroups': [], 'VpcSecurityGroups': [], 'DBParameterGroups': [{'DBParameterGroupName': 'None', 'ParameterApplyStatus': 'in-sync'}], 'DBSubnetGroup': {'DBSubnetGroupName': 'dbsg', 'DBSubnetGroupDescription': 'Text', 'VpcId': 'vpc-88031ca9', 'SubnetGroupStatus': 'Complete', 'Subnets': [{'SubnetIdentifier': 'subnet-440027d4', 'SubnetAvailabilityZone': {'Name': 'us-east-1a'}, 'SubnetStatus': 'Active'}]}, 'PreferredMaintenanceWindow': 'wed:06:38-wed:07:08', 'MultiAZ': False, 'EngineVersion': 'None', 'AutoMinorVersionUpgrade': False, 'ReadReplicaDBInstanceIdentifiers': [], 'LicenseModel': 'bring-your-own-license', **_'OptionGroupMemberships': [], '_**PubliclyAccessible': False, 'StatusInfos': [], 'StorageType': 'gp2', 'StorageEncrypted': False, 'DbiResourceId': 'db-M5ENSHXFPU6XHZ4G4ZEI5QIO2U', 'CopyTagsToSnapshot': False, 'DBInstanceArn': 'arn:aws:rds:us-east-1:1234567890:db:TestDB', 'IAMDatabaseAuthenticationEnabled': False}, 'ResponseMetadata': {'RequestId': '523e3218-afc7-11c3-90f5-f90431260ab4', 'HTTPStatusCode': 200, 'HTTPHeaders': {'server': 'amazon.com'}, 'RetryAttempts': 0}}

This scenario is also missing in the rds testing py 
the option group in create rds is never verified or tested 

another bug 👍 cannot create option group for EngineName="oracle-se2" - doesn't accept at MajorEngineVersion
also not engineName accepts MajorEngineVersion=12.2

**Comment by spulec** [comment]
Thanks for opening. It looks like we haven't implemented the `OptionGroupMemberships` tag in the response yet. I'm going to set this as a feature request.

**Comment by tallyl** [comment]
Thanks !
