### ISSUE TITLE
Add ``admin_update_user_attributes`` to ``cognito-idp``

### ISSUE THREAD

**Issue by ngoue** [spulec/moto#2184]
Add support for:
```
import boto3

cognito_idp = boto3.client('cognito-idp')
cognito_idp.admin_update_user_attributes(
    UserPoolId='us-east-1_abcdef123',
    Username='my-username',
    UserAttributes=[{ ... }]
) 
```

**Comment by Phlip** [comment]
+1!

**Comment by jblakeney** [comment]
I just opened a PR for some other Cognito work I needed. I will try to add this method later tonight!

**Comment by ngoue** [comment]
@jblakeney this is already merged!

https://github.com/spulec/moto/pull/2185

**Comment by terrycain** [comment]
Just not released yet

**Comment by spulec** [comment]
Closed with https://github.com/spulec/moto/pull/2185
