### ISSUE TITLE
Access Key with a custom created date

### ISSUE THREAD

**Issue by mlevit** [spulec/moto#2207]
Hey guys,

Is there a way to `create_access_key` with a custom `CreateDate` as I need to test a function that will look for Access Key's older than 90 day? Or is there a way to overwrite the `CreateDate` with a custom date?

**Comment by spulec** [comment]
If you are using python and the mock decorators, you can import the backend from moto and modify any resource attributes: https://github.com/spulec/moto/blob/master/moto/backends.py

Note that these APIs are private though and subject to change.
