### ISSUE TITLE
Change coveralls fail threshold

### ISSUE THREAD

**Issue by terrycain** [spulec/moto#2211]
@spulec Can you change the coveralls fail threshold to 1% or 0.5% as we're getting lots of failures for values like 0.005% etc... 

Will make scanning the PR list for PRs that have actually passed travis much easier.

**Comment by markchalloner** [comment]
It would also me worth setting coveralls to compare against the [merge head](https://github.com/spulec/moto/tree/pull/2082/merge) of the branch too if possible (see https://github.com/spulec/moto/issues/2109).

**Comment by spulec** [comment]
I'm happy to change, but do you think it is just worth dropping at this point?

**Comment by terrycain** [comment]
Hmm, I like the idea of the coverage, its helpful but currently its more annoying as it makes github think most of the pr's have failed as they're missing 0.001% of coverage. Then i cant quickly scan down the pr list to find pr's that could be merged.

I'd say lower the threshold for a bit and see how we do.

**Comment by spulec** [comment]
Cool. I've set the threshold to a 0.5% decrease for now.

I'm going to close this, but happy to keep adjusting if this feels off.
