### ISSUE TITLE
EC2 AllocationId missing from describe_addresses

### ISSUE THREAD

**Issue by mlevit** [spulec/moto#2221]
Missing `AllocationId` field from EC2 `describe_addresses` function.

**Comment by spulec** [comment]
Thanks; setting as a feature request.

**Comment by peterb154** [comment]
Ran into the same issue.. Looking for a workaround because the `ec2_client.create_nat_gateway()` requires an AllocationId https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2.html#EC2.Client.create_nat_gateway

The moto_ec2 describe_addresses() is also missing the AllocationId

Here is a demo of the missing AllocationId

test.py
```
from moto import mock_ec2
import boto3
import json

@mock_ec2
def example():
    ec2_client = boto3.client("ec2")
    print(json.dumps(ec2_client.allocate_address(), indent=2))
    print()
    print(json.dumps(ec2_client.describe_addresses(), indent=2))


if __name__ == "__main__":
    example()
```

And the reponse
```
$ python test.py
{
  "PublicIp": "127.232.102.18",
  "Domain": "standard",
  "ResponseMetadata": {
    "RequestId": "59dbff89-35bd-4eac-99ed-be587EXAMPLE",
    "HTTPStatusCode": 200,
    "HTTPHeaders": {
      "server": "amazon.com"
    },
    "RetryAttempts": 0
  }
}

{
  "Addresses": [
    {
      "InstanceId": "",
      "PublicIp": "127.232.102.18",
      "Domain": "standard",
      "NetworkInterfaceId": ""
    }
  ],
  "ResponseMetadata": {
    "RequestId": "59dbff89-35bd-4eac-99ed-be587EXAMPLE",
    "HTTPStatusCode": 200,
    "HTTPHeaders": {
      "server": "amazon.com"
    },
    "RetryAttempts": 0
  }
}
```

**Comment by peterb154** [comment]
Looked at the AWS documentation a little closer https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2.html#EC2.Client.allocate_address and noticed that the default "Domain" is to be null, which I think will also not return an allocationId. Pretty sure moto behaves correctly.

**AllocationId (string)** --

[EC2-VPC] The ID that AWS assigns to represent the allocation of the Elastic IP address **for use with instances in a VPC**

I think the moto.ec2.models.ElasticAddress.__init__() acts correctly, where if the domain is not specified, the allocation id is None

moto/ec2/models.py
```
class ElasticAddress(object):
    def __init__(self, domain, address=None):
        if address:
            self.public_ip = address
        else:
            self.public_ip = random_ip()
        self.allocation_id = random_eip_allocation_id() if domain == "vpc" else None
        self.domain = domain
        self.instance = None
        self.eni = None
        self.association_id = None
```

**Comment by bblommers** [comment]
I agree - the docs are pretty specific that it refers to addresses within a VPC:
    
    AllocationId (string) --

    [EC2-VPC] The ID that Amazon Web Services assigns to represent the allocation 
    of the Elastic IP address for use with instances in a VPC.

Closing this.
