### ISSUE TITLE
Any plan to support clone the resource that is already in AWS

### ISSUE THREAD

**Issue by charlie0077** [spulec/moto#2223]
It would be great if moto supports automatically clone the resource that is already there in AWS, so that you don't need to create the resource in the test.

**Comment by spulec** [comment]
No plans as of today, but it is something I've thought about in the past. I'm going to set this as a feature request and see if it gathers additional support.

**Comment by bblommers** [comment]
AWS supports a tool called [Former2](https://former2.com/) that generates CloudFormation for your existing resources. You can then import those CF templates into Moto to generate (/clone) the resources.

Using an external tool may be a bit of a PITA, but given the effort involved in recreating this feature in Moto, and the fact that there have been no other requests for this feature, it sounds like the best option.
