### ISSUE TITLE
Support VersionIdsToStages field in SecretsManager.DescribeSecret

### ISSUE THREAD

**Issue by sam-clotfelter** [spulec/moto#2230]
describe_secret does not return VersionIdsToStages.

I'm using moto master branch on a local docker container.

**Comment by klesniewski** [comment]
Not having VersionIdsToStages renders moto unusable with [aws-secretsmanager-caching-java](https://github.com/aws/aws-secretsmanager-caching-java) library (see [intro](https://aws.amazon.com/blogs/security/use-aws-secrets-manager-client-side-caching-libraries-to-improve-the-availability-and-latency-of-using-your-secrets/). The caching library seeks for secret version at specific stage (by default `"AWSCURRENT"`) and if it doesn't have this map or none of the versions are marked with the stage, then it does not resolve the secret.

Current options:
* Not use moto/localstack for integration testing
* Not use caching library

**Comment by bblommers** [comment]
This has been implemented by #3029 , and should be available as of moto >= 1.3.15.dev882

**Comment by sbwhitney** [comment]
> This has been implemented by #3029 , and should be available as of moto >= 1.3.15.dev882

Hi, thanks for adding the feature. Do you intend to post an updated version to pypi? 1.3.14 is available when pip installing.
