### ISSUE TITLE
Use Mock_Lambda with tox

### ISSUE THREAD

**Issue by JMGama** [spulec/moto#2235]
## Can not use @mock_lambda when running on tox.
I can not find a way to make the @mock_lambda decorator work when unittest run in tox.
I know that mock_lambda decorator needs Docker to work, but I can not find a way to make it work.

- moto 1.3.7
- python 3.6
- tox 3.8.6
- working in Windows

**Comment by spulec** [comment]
Hmmm, to my knowledge Tox shouldn't change anything.

Can you give an example of the code you are using?

**Comment by JMGama** [comment]
I have a function that is going to be tested, this function calls a **lambda** so I need to mock that lambda with a simple True response. 
I'm working on **Windows** so I need to have docker running to be able to mock a lambda with moto, everything works well but when I try to do everything with tox it runs with a problem trying to mock te lambda, **it looks like there is a problem with the docker because moto works with S3 mocks but not with the lambda mock that needs docker.** 

I think im doing something wrong with moto. 😞

The **_error_** that throw is the same that gives me when I run it without tox in windows with **docker off**:

> AssertionError: assert None is True
>\+  where None = <function fake_lambda at 0x000002A3A248A9D8>('001', 'test@test.com', 'Mr. Test')

I think it's trying to hit the lambda but since it doesn't exist throws a None.

### Here is an example code I'm trying to make.
tox.ini

```
[tox]
envlist = py36, py3.7, py3.8
skipsdist = True

[testenv]
deps = pytest
	pyyml
	fakeredis
	moto
	-r requirements.txt
commands = pytest test.py
```

create_user.py

```
lambda_client = boto3.client('lambda')

def save_user(user_id, email, name):
    try:
        request = {
            'userId': str(user_id),
            'email': str(email),
            'name': str(name)
        }
        a = lambda_client.invoke(
            FunctionName="fake_lambda",
            InvocationType='RequestResponse',
            Payload=json.dumps(request),
        )
        r = a.get('Payload').read()
        api_response = json.loads(r)
        return api_response
    except Exception as e:
        print(e)
```

test.py
```
from moto import mock_lambda
@mock_lambda
def test_function():
    from create_user import save_user 
    fake_lambda("fake_lambda")

    user_id = "001"
    email = "test@test.com"
    name = "Mr. Test"

    assert save_user(user_id, email, name) is True

    
def fake_lambda(function_name):
    def return_event():
        import zipfile
        import io

        code = """def lambda_handler(event, context):\n   return True"""
        zip_output = io.BytesIO()
        zip_file = zipfile.ZipFile(zip_output, 'w', zipfile.ZIP_DEFLATED)
        zip_file.writestr('lambda_function.py', code)
        zip_file.close()
        zip_output.seek(0)
        return zip_output.read()

    import boto3

    conn = boto3.client('lambda')
    conn.create_function(
        FunctionName=function_name,
        Runtime='python2.7',
        Role='test-iam-role',
        Handler='lambda_function.lambda_handler',
        Code={
            'ZipFile': return_event(),
        },
        Description='test lambda function',
        Timeout=3,
        MemorySize=128,
        Publish=True,
    )
```

requirements.txt
```
redis==3.2.1
python-dateutil==2.8.0
boto3==1.9.130
pymysql==0.9.3
```

**Comment by spulec** [comment]
Given that `save_user` seems to be returning None, I'm guessing an exception was thrown in there. Is there `print(e)` printing an exception? Can you drop a pdb in there and see what is happening?

**Comment by clowtown** [comment]
#2623 is related I believe. I've experienced this with the latest version of moto in which the invoke lambda response payload has the log contents in addition to the expected response. 

> b'\x1b[32mSTART RequestId: 3524550a-aa0f-1ed1-cad9-30af8d887f73 Version: 1\x1b[0m\r\n**inside the stringy lambda handler**\r\n\x1b[32mEND RequestId: 3524550a-aa0f-1ed1-cad9-30af8d887f73\x1b[0m\r\n\x1b[32mREPORT RequestId: 3524550a-aa0f-1ed1-cad9-30af8d887f73\tInit Duration: 168.62 ms\tDuration: 4.72 ms\tBilled Duration: 100 ms\tMemory Size: 128 MB\tMax Memory Used: 23 MB\t\x1b[0m\r\n\r\n{"statusCode":200,"body":"\\"Finished successfully!\\""}'

Where the lambda was defined as follows:
`"""
import json

def lambda_handler(event, context):
    print('inside the stringy lambda handler')
    return {'statusCode': 200, 'body': json.dumps('Finished successfully!')}
"""`

**Comment by bblommers** [comment]
Hi @JMGama, can you still reproduce this with the latest dev-version? (1.3.17.dev283)

**Comment by bblommers** [comment]
@clowtown The issue that log contents were returned alongside the expected response was fixed in https://github.com/spulec/moto/pull/2669

Going to close this due to a lack of response, but feel free to reopen if there's still an issue with Tox somehow
