### ISSUE TITLE
Docker Volume Issue - Moto + AWS Lambda

### ISSUE THREAD

**Issue by AmillerSC** [spulec/moto#2260]
Hello - We are currently experiencing an issue when trying to leverage Moto for tests with AWS Lambda functions.

 **We are currently using:**
- docker-py 4.0.2 |
-moto 1.3.8 
-pytest 4.6.3
-Python 3.6

Basically, when we run our tests, we are seeing a failure (with the below traceback) followed by a success. This is 100% consistent. 

**Observations:**
-When the test runs and the volume does NOT exist, the test will fail but our verification commands show that it creates the volume. When the test fails, a container process is NOT started and we get the traceback messages with the AttributeError
-The following test will succeed (and create a container process) and will subsequently remove the volume
-The next test fails in identical fashion to bullet point 1 and this cycle continues forever.

**Traceback:**
`Traceback (most recent call last):
  File "/Users/jasonwalsh/workspace/github.com/hopdrops/hopdrops/.eggs/moto-1.3.8-py3.6.egg/moto/awslambda/models.py", line 307, in _invoke_lambda
    with _DockerDataVolumeContext(self) as data_vol:
  File "/Users/jasonwalsh/workspace/github.com/hopdrops/hopdrops/.eggs/moto-1.3.8-py3.6.egg/moto/awslambda/models.py", line 113, in __enter__
    container = self._lambda_func.docker_client.containers.run('alpine', 'sleep 100', volumes=volumes, detach=True)
  File "/Users/jasonwalsh/workspace/github.com/hopdrops/hopdrops/.eggs/docker-4.0.2-py3.6.egg/docker/models/containers.py", line 803, in run
    detach=detach, **kwargs)
  File "/Users/jasonwalsh/workspace/github.com/hopdrops/hopdrops/.eggs/docker-4.0.2-py3.6.egg/docker/models/containers.py", line 860, in create
    create_kwargs = _create_container_args(kwargs)
  File "/Users/jasonwalsh/workspace/github.com/hopdrops/hopdrops/.eggs/docker-4.0.2-py3.6.egg/docker/models/containers.py", line 1087, in _create_container_args
    v.get('bind') for v in volumes.values()
  File "/Users/jasonwalsh/workspace/github.com/hopdrops/hopdrops/.eggs/docker-4.0.2-py3.6.egg/docker/models/containers.py", line 1087, in <listcomp>
    v.get('bind') for v in volumes.values()
AttributeError: 'str' object has no attribute 'get'`

**Notes:**
-We have not successfully run this before but we did try some different pinnings of docker-py and different Moto versions to no avail
-We are testing locally with fairly simple code. This is reproducible and we are certain the failures occur when the volume does not previously exist before testing

We believe the issue *MIGHT* be somewhere in the following code but despite forking and changing a few things, do not have this working:

`@property
    def name(self):
        return self._vol_ref.volume.name

    def __enter__(self):
        # See if volume is already known
        with self.__class__._lock:
            self._vol_ref = self.__class__._data_vol_map[self._lambda_func.code_sha_256]
            self._vol_ref.refcount += 1
            if self._vol_ref.refcount > 1:
                return self

            # See if the volume already exists
            for vol in self._lambda_func.docker_client.volumes.list():
                if vol.name == self._lambda_func.code_sha_256:
                    self._vol_ref.volume = vol
                    return self

            # It doesn't exist so we need to create it
            self._vol_ref.volume = self._lambda_func.docker_client.volumes.create(self._lambda_func.code_sha_256)
            if docker_3:
                volumes = {self.name: {'bind': '/tmp/data', 'mode': 'rw'}}
            else:
                volumes = {self.name: '/tmp/data'}
            container = self._lambda_func.docker_client.containers.run('alpine', 'sleep 100', volumes=volumes, detach=True)
            try:
                tar_bytes = zip2tar(self._lambda_func.code_bytes)
                container.put_archive('/tmp/data', tar_bytes)
            finally:
                container.remove(force=True)

        return self`

Let me know what other information is needed to help troubleshoot this.

**Comment by luksfarris** [comment]
For anyone who ends up here, mocking lambdas with `moto` requires docker, it's on the readme.
So, if you try to use `mock_lambda` from inside a container, it won't work (because it will call docker from inside the python image container).
A cool workaround for this, is to use the moto Standalone Server. Run:

```
moto_server lambda 
```

Then

```
moto_server lambda
```

Then, add to your code:

```
boto3.client('lambda', endpoint_url='http://localhost:5000', region_name='us-west-1')
```

**Comment by spulec** [comment]
@luksfarris is correct.

@AmillerSC can you confirm that works?

**Comment by AmillerSC** [comment]
@spulec We're able to use moto for non-lambda functions fine, because they do not use Docker. We have tried on macOS and Windows with Docker installed and it doesn't work consistently (it creates the container only 50% of the time (when the volume already exists).

I have not yet tried the standalone server workaround yet.

**Comment by spulec** [comment]
And the other 50% of the time, you are getting the above stacktrace?

**Comment by bblommers** [comment]
Going to close this due to a lack of response, but do let me know if there's still an issue.
