### ISSUE TITLE
If-Modified-Since request header not honored in GET

### ISSUE THREAD

**Issue by aakhan-sep** [spulec/moto#2263]
If-Modified-Since does not appear to be honored when calling GET Object.
When calling GetObject with If-Modified-Since in the header and a date that should cause a 304 response, the header is ignored and the object is returned regardless.
This goes against the behavior documented [here](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectGET.html)

A similar issue was created and a fix was merged: #960
While the logic for If-Modified-Since was implemented for HEAD, it was never implemented for GET in that issue.

Is there a reason for this? If not, may I submit a PR to fix this?

**Comment by spulec** [comment]
Closed with https://github.com/spulec/moto/pull/2276
