### ISSUE TITLE
Inaccurate CloudWatch GetMetricStatistics response

### ISSUE THREAD

**Issue by efritz** [spulec/moto#2267]
The following template constructs a CloudWatch response that does not behave the same as production: https://github.com/spulec/moto/blob/2275c53b3e4c6d21bc3de6d2dee9a02bad7a3491/moto/cloudwatch/responses.py#L278

This causes issues with the Go SDK which looks for a _member_ XML tag within the _datapoints_ list. All responses using moto with go therefore have empty datapoint lists.

Here is the relevant AWS SDK for Go code that unmarshals lists: https://github.com/aws/aws-sdk-go/blob/68afe677298a894afc385165f93ec26895a50c9e/private/protocol/xml/xmlutil/unmarshal.go#L166

The following is an actual get-metric-statistics response using the AWS CLI.

```xml
<GetMetricStatisticsResponse xmlns="http://monitoring.amazonaws.com/doc/2010-08-01/">
    <GetMetricStatisticsResult>
        <Datapoints>
            <member>
                <Unit>None</Unit>
                <Sum>1.0</Sum>
                <Timestamp>2019-06-28T15:52:00Z</Timestamp>
            </member>
            <member>
                <Unit>None</Unit>
                <Sum>2.0</Sum>
                <Timestamp>2019-06-28T15:53:00Z</Timestamp>
            </member>
        </Datapoints>
        <Label>executed</Label>
    </GetMetricStatisticsResult>
    <ResponseMetadata>
        <RequestId>26d654c4-99bd-11e9-b1e7-132b58350ac1</RequestId>
    </ResponseMetadata>
</GetMetricStatisticsResponse>
```

**Comment by spulec** [comment]
Thanks!
