### ISSUE TITLE
DynamoDB query validation fails queries with leading newlines

### ISSUE THREAD

**Issue by jeffcasavant** [spulec/moto#2275]
This query:

```
q = """
            SET
            Metadata.subscription.event_history = list_append(
                if_not_exists(Metadata.subscription.event_history, :empty_list),
                :new_event_tuple),
            UpdatedOn = :timestamp,
            UpdatedBy = :appid
        """
```

works in DynamoDB, but not in Moto.  The relevant line in Moto that invalidates this query is https://github.com/spulec/moto/blob/c8b94b6e9fd170363a73d8804db33fb4c6bc4575/moto/dynamodb2/models.py#L137 resulting in the error `Mismatched operators and values in update expression`.

I worked around this by running `strip()` on the query before execution time (making the `parts` list length divisible by two again).  I think this list construction is newline-sensitive when it should not be.

This query is run via `update_item()`, and it is validated by the line referenced above; this should be a valid toy example.

Expected: this query to run and set the above nested list value.
Actual: the `Mismatched operators` error is thrown.
Versions of packages (all pip installed): `moto==1.3.8` `boto3==1.9.145` `botocore==1.12.145`

**Comment by spulec** [comment]
Good catch.

Do you think it should be enough for us to `.strip()` `update_expression` inside of `update`?

**Comment by jeffcasavant** [comment]
That'll probably do it, based on the test case I have - and it'll handle this whole issue the way I've phrased it.

I'm curious if there are other places where moto should be pre-processing the query in the same way as well.  I think this is the only place where moto does this particular test.

**Comment by smthfrmn** [comment]
when running a similar `UpdateExpression`:

```python
    update_expression = '''
    SET errors = list_append(
            if_not_exists(errors, :empty_list),
            :new_error
        )
    SET latest_failed_timestamp = :current_timestamp
    SET service_resource_type = :service_resource_type
    '''
```

I'm not getting an error, but my `errors` field is being set to the string

```
"list_append(\n'
    if_not_exists(errors, :empty_list),\n'
    :new_error\n'
)"
```

Am I missing something?

Using `moto 1.3.10`, `botocore 1.12.86`, and `boto3 1.9.86`
