### ISSUE TITLE
DynamoDB  does not show query results when fitlering for an attribute that has the same name as a value from a different attribute.

### ISSUE THREAD

**Issue by mmussio85** [spulec/moto#2279]
Hi, I'm mocking a dynamoDB table in this way...
Description': 'test data 1',
SupportLanguage': 'en',
PhoneNumber: +1000000,
Modality: PhoneNumber

so when doing a query against this table in this way...
elems = db_table.query(
            IndexName=index_name,
            KeyConditionExpression=Key('SupportLanguage').eq(req_support_lang),
            FilterExpression=Attr('Modality').eq(kwargs['req_modalities']),
            ProjectionExpression='Modality, PhoneNumber')
data = elems['Items']

The query is not bringing any item.

Note: index_name is an index based on SupportLanguage.

I'm using Python 3.67 moto==1.3.7 and pytest 4.6.3

Other than that, I tried a scan and changed the Modality attribute to something different from PhoneNumber and It works ! but It's mandatory that the PhoneNumber field must be named that way.

I consider moto is cionfused because the attribute name is equal to one of the values I have in the table for a different attribute.

**Comment by bblommers** [comment]
Hi @mmussio85, can you reproduce this with the latest version of Moto? (https://pypi.org/project/moto/#history)

**Comment by bblommers** [comment]
Going to close this due to a lack of response - feel free to reopen if it is still an issue after all.
