### ISSUE TITLE
moto 1.3.9 does not work with .aws/credentials for non-mocked calls while moto 1.3.6 did

### ISSUE THREAD

**Issue by gforis** [spulec/moto#2293]
## moto 1.3.9 not using .aws/credentials for non-mocked calls

I found the below problem with 1.3.9, while this was working fine with 1.3.6
Unfortunately 1.3.6 miss some features I need and those are implemented in 1.3.9.

Sample Code
```
import sys
import boto3
import moto

from moto import mock_sts

@mock_sts
def test_1():
    print('Mocked call:', boto3.client('sts').get_caller_identity())

def test_2():
    print('Non-mocked call:', boto3.client('sts').get_caller_identity())

def main(argv):
    test_1()
    test_2()

if __name__ == '__main__':
    main(sys.argv)
```

Failing stack
> boto==2.49.0
> boto3==1.9.186
> botocore==1.12.186
> moto==1.3.9

Failing run

> (venv) ➜  ~ python a.py 
> Mocked call: {'Account': '123456789012', 'Arn': 'arn:aws:sts::123456789012:user/moto', 'ResponseMetadata': {'RequestId': 'mmm', 'HTTPStatusCode': 200, 'HTTPHeaders': {'server': 'amazon.com', 'Content-Type': 'text/plain'}, 'RetryAttempts': 0}, 'UserId': 'EXAMPLE'}
> Traceback (most recent call last):
>   File "a.py", line 19, in <module>
>     main(sys.argv)
>   File "a.py", line 16, in main
>     test_2()
>   File "a.py", line 12, in test_2
>     print('Non-mocked call:', boto3.client('sts').get_caller_identity())
>   File "/home/gb/venv/lib/python3.5/site-packages/botocore/client.py", line 357, in _api_call
>     return self._make_api_call(operation_name, kwargs)
>   File "/home/gb/venv/lib/python3.5/site-packages/botocore/client.py", line 661, in _make_api_call
>     raise error_class(parsed_response, operation_name)
> botocore.exceptions.ClientError: An error occurred (InvalidClientTokenId) when calling the GetCallerIdentity operation: The security token included in the request is invalid.
> ...

Working stack
> boto==2.49.0
> boto3==1.7.84
> botocore==1.10.84
> moto==1.3.6

Passing run
> (venv) ➜  ~ python a.py            
> Mocked call: {'Account': '123456789012', 'Arn': 'arn:aws:sts::123456789012:user/moto', 'ResponseMetadata': {'RequestId': 'mmm', 'HTTPStatusCode': 200, 'HTTPHeaders': {'server': 'amazon.com', 'Content-Type': 'text/plain'}, 'RetryAttempts': 0}, 'UserId': 'EXAMPLE'}
> Non-mocked call: {'Account': 'XXX', 'Arn': 'arn:aws:sts::XXX:user/ZZZ', 'ResponseMetadata': {'RequestId': 'abc', 'HTTPStatusCode': 200, 'HTTPHeaders': {'content-length': '459', 'date': 'Wed, 10 Jul 2019 20:18:13 GMT', 'x-amzn-requestid': 'ddd', 'content-type': 'text/xml'}, 'RetryAttempts': 0}, 'UserId': 'kkk'}
> (venv) ➜  ~

**Comment by spulec** [comment]
Can you confirm that `test_2()` works if you comment out `test_1()` and the call to it?

If it does work, can you try testing on moto==1.3.8. I'm having trouble recreating this and understanding where it changed would be helpful.

**Comment by gforis** [comment]
On 1.3.6 it works fine when commented out only test_1 and the related call.
However, on 1.3.8 with the same setup it runs into the InvalidClientTokenId error.
For 1.3.8, I had to comment out the moto imports to make it work.

**Comment by spulec** [comment]
This now works for me against `master`. Can you confirm?

**Comment by gforis** [comment]
Hmm.., I have tested this with `moto==1.3.14.dev31` and the issue persists. With `moto==1.3.6` above code works all right. I have enclosed below the related requirements.txt:

Stack with failing call:

> asn1crypto==0.24.0
> attrs==19.1.0
> aws-sam-translator==1.12.0
> aws-xray-sdk==2.4.2
> boto==2.49.0
> boto3==1.9.188
> botocore==1.12.188
> certifi==2019.6.16
> cffi==1.12.3
> cfn-lint==0.22.3
> chardet==3.0.4
> cryptography==2.7
> docker==4.0.2
> docutils==0.14
> ecdsa==0.13.2
> future==0.17.1
> idna==2.8
> Jinja2==2.10.1
> jmespath==0.9.4
> jsondiff==1.1.2
> jsonpatch==1.23
> jsonpickle==1.2
> jsonpointer==2.0
> jsonschema==3.0.1
> MarkupSafe==1.1.1
> mock==3.0.5
> moto==1.3.14.dev31
> pkg-resources==0.0.0
> pyasn1==0.4.5
> pycparser==2.19
> pyrsistent==0.15.3
> python-dateutil==2.8.0
> python-jose==3.0.1
> pytz==2019.1
> PyYAML==5.1.1
> requests==2.22.0
> responses==0.10.6
> rsa==4.0
> s3transfer==0.2.1
> six==1.12.0
> sshpubkeys==3.1.0
> urllib3==1.25.3
> websocket-client==0.56.0
> Werkzeug==0.15.5
> wrapt==1.11.2
> xmltodict==0.12.0

Working stack:

> asn1crypto==0.24.0
> attrs==19.1.0
> aws-sam-translator==1.12.0
> aws-xray-sdk==0.95
> boto==2.49.0
> boto3==1.7.84
> botocore==1.10.84
> certifi==2019.6.16
> cffi==1.12.3
> cfn-lint==0.22.3
> chardet==3.0.4
> cookies==2.2.1
> cryptography==2.7
> docker==4.0.2
> docutils==0.14
> ecdsa==0.13.2
> future==0.17.1
> idna==2.8
> Jinja2==2.10.1
> jmespath==0.9.4
> jsondiff==1.1.1
> jsonpatch==1.23
> jsonpickle==1.2
> jsonpointer==2.0
> jsonschema==3.0.1
> MarkupSafe==1.1.1
> mock==3.0.5
> moto==1.3.6
> pkg-resources==0.0.0
> pyaml==19.4.1
> pyasn1==0.4.5
> pycparser==2.19
> pycryptodome==3.8.2
> pyrsistent==0.15.3
> python-dateutil==2.8.0
> python-jose==2.0.2
> pytz==2019.1
> PyYAML==5.1.1
> requests==2.22.0
> responses==0.10.6
> rsa==4.0
> s3transfer==0.1.13
> six==1.12.0
> sshpubkeys==3.1.0
> urllib3==1.25.3
> websocket-client==0.56.0
> Werkzeug==0.15.5
> wrapt==1.11.2
> xmltodict==0.12.0

**Comment by spulec** [comment]
Hmmmm. Is there anything else unusual about your setup? What OS, etc? Any environment variables related to AWS auth?

Is it still giving the `The security token included in the request is invalid.` error?

**Comment by gforis** [comment]
This has been tested now with `1.3.14.dev61` and confirmed working with that.
Thanks a lot for the fix.
