### ISSUE TITLE
cognito-idp: NotImplementedError: The update_user_pool_domain action has not been implemented

### ISSUE THREAD

**Issue by caguado** [spulec/moto#2308]
## Description
The current master does not implement the [update_user_pool_domain](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/cognito-idp.html#CognitoIdentityProvider.Client.update_user_pool_domain) endpoint of cognito-idp, neither is listed on the implementation coverage.

**Comment by spulec** [comment]
Thanks for opening! Setting this as a feature request.

**Comment by spulec** [comment]
Closed with #2309

**Comment by caguado** [comment]
Wow! Thanks for the super quick response!

**Comment by spulec** [comment]
Thanks for your help! We do prereleases based on each commit so you should be able to install this from [pypi shortly](https://pypi.org/project/moto/#history).
