### ISSUE TITLE
instance metadata tied direct to core model

### ISSUE THREAD

**Issue by joekiller** [spulec/moto#231]
Currently moto has internal EC2 metadata included in its core model (https://github.com/spulec/moto/blob/eedb4c4b738c01642f00628b1de2827d03fc5209/moto/core/models.py#L46).  This has a bad side effect where if a user is using ec2 moto mocks, instance metadata responses from external requests calls are intercepted by moto and return successfully.

This is a problem as sometimes times the code might be outside an ec2 instance when making boto calls and expect the metadata call to fail with a ConnectionError (from requests for example).

It should be considered to make metadata its own mock service as it really isn't an EC2 service so much as a feature of an EC2 instance.  

Thoughts?

**Comment by spulec** [comment]
Sounds good
