### ISSUE TITLE
cognito-identity: NotImplementedError: The get_open_id_token action has not been implemented

### ISSUE THREAD

**Issue by caguado** [spulec/moto#2310]
## Description
The current master does not implement the [get_open_id_token](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/cognito-identity.html#CognitoIdentity.Client.get_open_id_token) endpoint of cognito-identity.

**Comment by spulec** [comment]
Closed with https://github.com/spulec/moto/pull/2311
