### ISSUE TITLE
Add support for EventBridge

### ISSUE THREAD

**Issue by dmulter** [spulec/moto#2322]
Please add support for both partner and customer API endpoints for the new [Amazon EventBridge](https://aws.amazon.com/eventbridge/) service. See the [EventBridge boto3 API](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/events.html?highlight=eventbridge) docs for all methods.

**Comment by spulec** [comment]
Setting this as a feature request; thanks!

**Comment by spulec** [comment]
Going to call this closed with https://github.com/spulec/moto/pull/2536

Feel free to open other issues with more specific endpoints.
