### ISSUE TITLE
Missing SNS message attributes in SQS subscription

### ISSUE THREAD

**Issue by aeby** [spulec/moto#2331]
This is a follow-up for #888. If `RawMessageDelivery` for a SQS subscription is enabled, the `message_attributes` are simply discarded in the SNS [model.py](https://github.com/spulec/moto/blob/master/moto/sns/models.py#L101-L102). On AWS the message attributes are included in the message. I think something like this cloud make sense:
```python
if self.attributes.get('RawMessageDelivery') != 'true':
    enveloped_message = json.dumps(self.get_post_data(message, message_id, subject, message_attributes=message_attributes), sort_keys=True, indent=2, separators=(',', ': '))
    sqs_backends[region].send_message(queue_name, enveloped_message)
else:
    sqs_backends[region].send_message(queue_name, message, message_attributes)
```
This way the message attributes get either enveloped or added to the message for raw delivery.

_Update_: I just saw that we have to transform the `message_attributes` for SQS first.

**Comment by spulec** [comment]
Thanks. Agree with your thinking. I am going to set this as a feature request.

**Comment by aeby** [comment]
@spulec: have you an idea on how to convert the message attributes? Is there somewhere a function? I could then submit a PR if you like

**Comment by spulec** [comment]
A PR would be great. I can't say I am very familiar with the desired SQS behavior here. I'm not sure what the logic needed to convert the attributes is.
