### ISSUE TITLE
Why is this a hardcoded host?

### ISSUE THREAD

**Issue by christhomas** [spulec/moto#2335]
https://github.com/spulec/moto/blob/5dbdff7ca7d393f4e9f3c37f0e4f89c4f0ec4a20/moto/server.py#L110

Can you explain why you're hardcoding host names here? Why when I put /moto-api the host will be set to moto_api

Is there a reason why the hostname needs to be "moto_api" and it can't just be the HTTP_HOST of the request made to the server?

**Comment by spulec** [comment]
If a user it going to the `/moto-api` path, we assume they are trying to use the extra API calls we have added with Moto. The host is how we determine which backend should handle the request.

Is this causing an issue for some reason?

**Comment by christhomas** [comment]
But why make this unsafe assumption at all? Just use the host given from the request. This code would still work. It doesn't need hard coding like this and it's not even a safe assumption anyway.

Is there a reason you want to hardcode this?

**Comment by spulec** [comment]
We use the host to determine the backend. See a few lines down where we call `get_backend_for_host`, which relies on the host to know which service should serve the request. We don't have another way to determine which of the services should handle the response.

Have you tried commenting out that line and running it because I'm fairly sure it won't work.

**Comment by christhomas** [comment]
in order for moto_api to be a working hostname for this server to run, it needs to either be resolved in the /etc/hosts or a dns server, right?

so why don't we fix this in a way which means we simplify the code, remove some hardcoded stuff, and potentially make life easier for everybody?

the moto server can be told which services it wants to host, so lets just update the instructions to say that you should update your hosts file to include something more precise like: iam.eu-west-1.moto.develop, s3.eu-central-1.moto.develop, etc. 

Then you could just use the host without all this hardcoding and you'd clean up all the custom cases since this is the same url scheme that aws is using.

Would that work? I'm just getting into the code and finding a couple of low hanging fruits, see if I can help or not

**Comment by spulec** [comment]
The hostname is not actually being resolved anywhere. This is just changing a variable on the server-side of the process. Asking users to change a hosts file seems much more complicated than what we are asking of them now.

Is this causing an issue for something that you are trying to do?

**Comment by christhomas** [comment]
nothing really, I was just looking because we were talking about an issue in the same part of the code and I thought I could be helpful in some way, thanks for the explanation though
