### ISSUE TITLE
Change setup.py to require cfn-lint newer than 0.4.0

### ISSUE THREAD

**Issue by joshuaatwork** [spulec/moto#2336]
On systems with a very old version of cfn-lint the moto '1.3.13'  fails when mocking cloudformation with:

"/moto/cloudformation/utils.py", line 8, in <module>
    from cfnlint import decode, core
ImportError: cannot import name 'decode'

Decode did not exist before 0.4.0. Updating the requirement in settings.py to include a version requirement will fix this. Thanks!

**Comment by spulec** [comment]
Fixed; thanks!
