### ISSUE TITLE
S3 PUT etag is incompatible with dotnet client

### ISSUE THREAD

**Issue by davidje13** [spulec/moto#2339]
This appears to be the same issue raised in #1219 (though that was closed without resolution)

When PUTting a non-empty file from the AWSSDK.S3 package to a moto server, an exception is thrown by the client:

> ```
> One or more errors occurred. (Expected hash not equal to calculated hash)
> [...]
> ----- Inner Stack Trace -----
>    at Amazon.S3.Internal.AmazonS3ResponseHandler.CompareHashes(String etag, Byte[] hash) in ...\AWSDotNetPublic\sdk\src\Services\S3\Custom\Internal\AmazonS3ResponseHandler.cs:line 213
>    at Amazon.S3.Internal.AmazonS3ResponseHandler.ProcessResponseHandlers(IExecutionContext executionContext) in ...\AWSDotNetPublic\sdk\src\Services\S3\Custom\Internal\AmazonS3ResponseHandler.cs:line 89
>    at Amazon.S3.Internal.AmazonS3ResponseHandler.InvokeAsync[T](IExecutionContext executionContext) in ...\AWSDotNetPublic\sdk\src\Services\S3\Custom\Internal\AmazonS3ResponseHandler.cs:line 60
> ```

We integrate like so:

```csharp
var client = new AmazonS3Client(
    new BasicAWSCredentials("A", "B"),
    new AmazonS3Config
    {
        ForcePathStyle = true, // required to match moto API
        ServiceURL = "http://localhost:5000",
    }
)

await client.PutBucketAsync("test");

var response = await client.PutObjectAsync(new PutObjectRequest
{
    BucketName = "test",
    Key = "file",
    InputStream = new MemoryStream(new byte [] { 1, 2, 3 })
});
```

Talking to the real S3 service with the same code works, and talking to moto using the AWS CLI works. It is only the combination of the dotnet client and moto which fails.

Investigation reveals this is due to a different `etag` calculation in moto. I believe this is something to do with which data is included in the hash algorithm. As a test, I disabled etag generation entirely inside moto:

```patch
diff --git a/moto/s3/models.py b/moto/s3/models.py
index 2a628d68..74fc76a1 100644
--- a/moto/s3/models.py
+++ b/moto/s3/models.py
@@ -145,6 +145,7 @@ class FakeKey(BaseModel):

     @property
     def etag(self):
+        return ""
         if self._etag is None:
             value_md5 = hashlib.md5()
             self._value_buffer.seek(0)
```

Which resolved the issue (the client skips this check if no etag is given)

---

I'm not sure what the exact discrepancy is in the calculation, but since disabling the etag works, could a flag be added to the standalone server to remove it? Something like `moto_server s3 --no-etag` maybe.

If it helps diagnose how the hash is wrong, debugging reveals these results (note that comparison is performed case insensitively):

```
Content: new byte [] { 1, 2, 3 } - key: "test", bucket: "test"
Observed ETAG: 2552e43dc26f09a754768c014609d016
Expected ETAG: 5289DF737DF57326FCDD22597AFB1FAC
```

```
Content: new byte [] { 1 } - key: "test", bucket: "test"
Observed ETAG: 995dcc1a90a1d5bda551bb3c15b92123
Expected ETAG: 55A54008AD1BA589AA210D2629C1DF41
```

```
Content: new byte [] { } (no content) - key: "test", bucket: "test"
Observed ETAG: d41d8cd98f00b204e9800998ecf8427e
Expected ETAG: D41D8CD98F00B204E9800998ECF8427E (pass)
```

**Comment by spulec** [comment]
Thanks for opening this. I am going to set this as a feature request for us to implement etags properly.

**Comment by bblommers** [comment]
A similar bug for the Java SDK has been fixed as of Moto >= 2.2.4. 
@davidje13 Are you able to verify whether that fixes the problem for you as well?

**Comment by davidje13** [comment]
Sorry this was quite a lot of projects ago so I don't have access / context any more.

I suggest trying the code I posted in the original issue in a blank .Net CLI project. It should be able to confirm one way or the other pretty quickly.

**Comment by bblommers** [comment]
No worries @davidje13. I'm not too familiar with dotnet myself, that's why I asked.

With a lot of Google-fu I did manage to get your code running, and it does not throw any errors against the latest MotoServer version - so I'll consider this issue closed. 👍
