### ISSUE TITLE
API Gateway:update_api_key is not implemented

### ISSUE THREAD

**Issue by chichi1091** [spulec/moto#2340]
Please add support for[update_api_key](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/apigateway.html#APIGateway.Client.update_api_key)

Maybe I can help with PullRequest.

**Comment by spulec** [comment]
Thanks for opening. I'm going to set this as a feature request. A PR would be very welcome if you get time!

**Comment by gruebel** [comment]
@spulec I think this is also solved by the aove PR #2350

**Comment by spulec** [comment]
@gruebel thanks!
