### ISSUE TITLE
S3 section of Implementation Coverage document doesn't match apparent S3 module

### ISSUE THREAD

**Issue by gene1wood** [spulec/moto#2347]
The [`IMPLEMENTATION_COVERAGE.md`](https://github.com/spulec/moto/blame/e4a4e6183560489e98b95e815b439c7a1cf3566c/IMPLEMENTATION_COVERAGE.md#L3603) document shows that S3 has 15% coverage and calls like `put_object` aren't implemented.

At the same time though [the README's main example](https://github.com/spulec/moto/blame/e4a4e6183560489e98b95e815b439c7a1cf3566c/README.md#L21-L28) uses `put_object` implying it is supported.

In [looking through the code](https://github.com/spulec/moto/blame/e4a4e6183560489e98b95e815b439c7a1cf3566c/moto/s3/models.py#L53) it appears that indeed uploading content to S3 is supported.

Is the `IMPLEMENTATION_COVERAGE.md` document just out of date for S3? Is `put_object` not implemented and the example in the README works via some means other than using an implemented mocked endpoint for S3?

If the S3 section of `IMPLEMENTATION_COVERAGE.md` is just inaccurate, could it be updated with all the S3 calls that are implemented?

**Comment by mikegrima** [comment]
The doc is out of date. Please feel free to submit a PR to update it.

**Comment by jrstarke** [comment]
I'll take a crack at this

**Comment by spulec** [comment]
This has been fixed
