### ISSUE TITLE
S3 new storage classes is not implemented

### ISSUE THREAD

**Issue by kama-meshi** [spulec/moto#2349]
Amazon announced new [storage classes](https://docs.aws.amazon.com/AmazonS3/latest/dev/storage-class-intro.html) of S3, "INTELLIGENT_TIERING", "GLACIER" and "DEEP_ARCHIVE".
Could you add support for these?

When specified these storage class, `InvalidStorageClass` will be raised.

``` python
import moto
import boto3

# moto==1.3.13
# boto3==1.9.199
# Python 3.7.4

@moto.mock_s3
def test_put_object():
    conn = boto3.resource('s3')
    conn.create_bucket(Bucket='mybucket')
    obj = conn.Object('mybucket', 'myfile')
    obj.put(Body='xxx'.encode(), StorageClass='INTELLIGENT_TIERING')
    # Error!!
    # botocore.exceptions.ClientError: An error occurred (InvalidStorageClass) when calling the PutObject operation: The storage class you specified is not valid
```

refs #1653

**Comment by spulec** [comment]
Thanks for opening; setting this as a feature request.
