### ISSUE TITLE
Secretsmanager put_secret_value still does not support SecretBinary

### ISSUE THREAD

**Issue by kevinmbt** [spulec/moto#2366]
The functions for put_secret_value don't have fields for secret_binary in them. 

Offending methods: https://github.com/spulec/moto/blob/master/moto/secretsmanager/models.py#L157, https://github.com/spulec/moto/blob/master/moto/secretsmanager/responses.py#L72

**Comment by spulec** [comment]
Thanks; setting as a feature request.

**Comment by spulec** [comment]
Closed with #2385
