### ISSUE TITLE
Make anchors in IMPLEMENTATION_COVERAGE.md independent of percent implemented

### ISSUE THREAD

**Issue by isuftin** [spulec/moto#2368]
This is a feature update request: In the [implementation coverage](https://github.com/spulec/moto/blob/master/IMPLEMENTATION_COVERAGE.md) document, it would be a lot more convenient and (at least to me) logical to anchor links to the feature and not the feature plus the percent covered it is.

`https://github.com/spulec/moto/blob/master/IMPLEMENTATION_COVERAGE.md#efs` - GOOD

`https://github.com/spulec/moto/blob/master/IMPLEMENTATION_COVERAGE.md#efs---0-implemented` - BAD

The former makes a much more static link from downstream docs in my own projects while the latter creates a moving target

**Comment by spulec** [comment]
Good call!
