### ISSUE TITLE
AttributeError: 'function' object has no attribute 'when'

### ISSUE THREAD

**Issue by Extrabeefy** [spulec/moto#2372]
Moto Version: 1.3.13
Python: 3.7
Boto: 1.9.204

When using the test_send_raw_email for mock_ses under: 
     https://github.com/spulec/moto/blob/master/tests/test_ses/test_ses_boto3.py 
I am getting the following error: 
     AttributeError: 'function' object has no attribute 'when'
at this line:
     send_raw_email.when.called_with(**kwargs).should.throw(ClientError)

**Comment by spulec** [comment]
You will need to `import sure`. That should solve it. Feel free to reopen if it doesn't.
