### ISSUE TITLE
Should we want to be funded and give reward solving issues?

### ISSUE THREAD

**Issue by toshitanian** [spulec/moto#2383]
[Issuehunt](https://issuehunt.io/) is a community that receive fund to repository and set rewards to issues.
I think that moto will drive more by using this community.

If maintainers and contributors wants to use it, I want to register to Issuehunt.

ref: https://help.github.com/en/articles/displaying-a-sponsor-button-in-your-repository

**Comment by spulec** [comment]
I don't see any problem with adding this. PR welcome unless someone comes up with reasons against.

**Comment by toshitanian** [comment]
ok I will

**Comment by spulec** [comment]
Going to close this out. PR welcome if someone wants to add this.

**Comment by bblommers** [comment]
@spulec From what I can see, to use IssueHunt, an admin has to sign up to the website, register the repo and install the app. No code changes necessary
