### ISSUE TITLE
Cut a release?

### ISSUE THREAD

**Issue by mariusvniekerk** [spulec/moto#2389]
It's been quite a few commits since the last release.  Could be cut a 1.3.14?

There are quite a few fixes to issues like those in #2371

**Comment by omkark96** [comment]
It is a substantial fix in itself to cut a new release, yes.

**Comment by spulec** [comment]
Let me know if there is a reason you can't use the prereleases: https://pypi.org/project/moto/#history

**Comment by spulec** [comment]
You need to set an explicit version like `moto==1.3.14.dev250`
