### ISSUE TITLE
Add support for ElasticBeanstalk

### ISSUE THREAD

**Issue by nielslaukens** [spulec/moto#2405]
Hi,

Thank you for creating this wonderful library. It makes my testing-endevours much easier.

I would like to test some Elastic Beanstalk code, but according to [IMPLEMENTATION_COVERAGE], these are not yet implemented. The [CONTRIBUTING] document asks me to create an issue first.

[IMPLEMENTATION_COVERAGE]: https://github.com/spulec/moto/blob/master/IMPLEMENTATION_COVERAGE.md
[CONTRIBUTING]: https://github.com/spulec/moto/blob/master/CONTRIBUTING.md

Specifically, I'd like to mock out:
* `elasticbeanstalk:describe_environments` which would require these to be able to fill the mock with data:
  * `elasticbeanstalk:create_application`
  * `elasticbeanstalk:create_environment`
* `elasticbeanstalk:list_tags_for_resource` which would require these to be able to fill the mock with data:
  * `elasticbeanstalk:update_tags_for_resource`
* `elasticbeanstalk:list_available_solution_stacks` which may require some way to fill in the returned data?

I'm willing to put in some effort to add these myself, but will probably need some guidance along the way. I'll try to create (failing) tests and PR these, referencing this issue.

**Comment by spulec** [comment]
Yes, PRs are very much welcome for new endpoints. Let us know if you have particular questions on how to get started.
