### ISSUE TITLE
SQS PhysicalResourceId should always be its QueueUrl

### ISSUE THREAD

**Issue by maxenglander** [spulec/moto#2407]
According to the [AWS CFN docs for SQS](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sqs-queues.html#aws-properties-sqs-queues-return-values-ref), the physical resource ID should be its queue URL.

>Ref
>
>When you pass the logical ID of this resource to the intrinsic Ref function, Ref returns the queue URL. For example:
>
>{ "Ref": "https://sqs.us-east-2.amazonaws.com/123456789012/aa4-MyQueue-Z5NOSZO2PZE9" }

However, `moto` currently uses the queue name as the physical resource ID:

https://github.com/spulec/moto/blob/3a5d857a60c3a2d140ed2c8adfe8dcaf71a4cac8/moto/sqs/models.py#L322-L324

**Comment by spulec** [comment]
Thanks; setting this as a feature request.
