### ISSUE TITLE
Logs filter-log-events ignores filterPattern argument.

### ISSUE THREAD

**Issue by danieltahara** [spulec/moto#2419]
When a `filterPattern` is given to `filter_log_events`  the filter is ignored.

e.g.

```
        malformed = {"message": "hello", "timestamp": 100}

        logs_client.put_log_events(
            logGroupName=log_group,
            logStreamName=log_streams[0],
            logEvents=[malformed],
        )

       res = logs_client.filter_log_events(
            logGroupName=log_group,
            filterPattern='{$.my_json_field = "foo"}',
            startTime=0,
            endTime=12345667,
        )
 
      # Fails
       assert len(res["events"]) == 0 
```

On 1.3.9 locally (installed with pip), but the problem exists on master.

Here's the specific LOC where it just ignores `filter_pattern`: https://github.com/spulec/moto/blob/master/moto/logs/models.py#L126

I think it's probably reasonable to support basic key equality for json filters, as well as simple matching on text. Anything beyond that might get tricky, but you can throw an error in that case instead of silently ignoring.

At the very least, raising NotImplemented() when filter_pattern is non-empty would be desirable.

**Comment by spulec** [comment]
Thanks; I am going to set this as a feature request for us to implement filter_pattern.
