### ISSUE TITLE
Add support for EC2 state 'OutOfService' in moto ELB 'describe_instance_health'

### ISSUE THREAD

**Issue by ivarunk** [spulec/moto#2421]
Add support for instance state 'OutOfService' in moto ELB 'describe_instance_health'
https://github.com/spulec/moto/blob/master/moto/elb/responses.py#L260

mocking doesn't have support for 'OutOfService', once an instance is registered to an ELB its state is shown as 'InService'.

The state of EC2 instance in 'describe_instance_health' should be changed to 'OutOfService' if the EC2 instance is stopped/fails ELB healthcheck.

**Comment by spulec** [comment]
Thanks for opening. I am tagging this as a feature request.
