### ISSUE TITLE
Tags on official docker releases

### ISSUE THREAD

**Issue by clar-cmp** [spulec/moto#2425]
In #1159 it was mentioned that images are finally published to dockerhub. Unfortunately, tags don't seem to be pushed automatically, and we can't pin down a specific version for repeatability.

It would be lovely if you could include tags other than `latest` when pushing images to Docker Hub. This wouldn't be too much extra work to add to the Makefile and release flow, I think.

**Comment by thetumper** [comment]
Agreed.  Also wondering on next release, and regularity of releases.  What is the criteria?

**Comment by spulec** [comment]
PR welcome!

I am fine to push docker images on every commit, just like we do for PyPI: https://github.com/spulec/moto/issues/640

**Comment by thetumper** [comment]
In lieu of getting the automated push to docker done, could someone consider a manual push to docker?  The latest was last updated there 2 months ago.  That would at least help many of us in the short term, until the automated pushes could be configured.  Thanks!

**Comment by spulec** [comment]
Version `1.3.14` has been tagged on dockerhub.

I am keeping this open until we automate that process.

**Comment by spulec** [comment]
Sorry about that; should be fixed going forward with https://github.com/spulec/moto/commit/72e616cb48e3a781bd68280c48bd6aa8dc099a1a
