### ISSUE TITLE
Could you help me release this package?

### ISSUE THREAD

**Issue by mangin** [spulec/moto#2429]
I've found instruction how to do it:
https://github.com/spulec/moto/blob/master/CONTRIBUTING.md#releasing-a-new-version-of-moto

But I've found some problem too:
1) the last version of moto on PyPi == 1.3.13
2) the last version of moto by tag == 1.3.10
3) the last version of moto by master == 1.3.4
4) And finaly I have some error in the bumping process:

```bash
~/dev/src/moto (master) $ ./scripts/bump_version 1.3.13
Traceback (most recent call last):
  File "/home/aleksandermangin/.pyenv/versions/3.7.0/bin/bumpversion", line 11, in <module>
    sys.exit(main())
  File "/home/aleksandermangin/.pyenv/versions/3.7.0/lib/python3.7/site-packages/bumpversion/__init__.py", line 912, in main
    f.should_contain_version(current_version, context)
  File "/home/aleksandermangin/.pyenv/versions/3.7.0/lib/python3.7/site-packages/bumpversion/__init__.py", line 208, in should_contain_version
    assert self.contains(version.original), msg
AssertionError: Did not find '1.3.4' or '1.3.4' in file setup.py
```

**Comment by spulec** [comment]
I don't think I understand. Are you trying to release this to PyPI under a different name?

Only the maintainers of the package are able to create releases.

**Comment by mangin** [comment]
You are right. I skipped the sub title (Maintainers). I thought that if someone wants to release the package he has to create PR with changing version. But it was wrong thought

But we still have problem with strange versions on PyPi.
For example:
1) https://pypi.org/project/moto/1.3.13/ is a package that was uploaded to PyPi
2) BUT we don't have tag 1.3.13 in repo. I think It's so strange.
3) https://github.com/spulec/moto/blob/master/.bumpversion.cfg has current version 1.3.4

**Comment by spulec** [comment]
2) Yes, this was a mistake. Sorry about that. 
3) That file is no longer being used. You should feel free to ignore.
