### ISSUE TITLE
Lambda UpdateFunctionCode and UpdateFunctionConfiguration Missing

### ISSUE THREAD

**Issue by sethblack** [spulec/moto#2461]
Nothing too insane here. Both of these are missing from the lambda implementation.

https://docs.aws.amazon.com/lambda/latest/dg/API_UpdateFunctionCode.html
https://docs.aws.amazon.com/lambda/latest/dg/API_UpdateFunctionConfiguration.html

I should be able to get a PR in today if nobody else has taken these one.

**Comment by spulec** [comment]
Closed with https://github.com/spulec/moto/pull/2464
