### ISSUE TITLE
Modifying EC2 instance attributes

### ISSUE THREAD

**Issue by minigoatboy** [spulec/moto#2472]
Hello,

Firstly, thank you so much for creating this.  It's solved so many problems I was having with AWS controller code testing!

This is more of a question than an issue, so apologies if this is in the wrong place.

I am testing some code that has some validation checking around how long an instance has been running and that's problematic to test here as it's impractical to wait for the 10 minute threshold in the test to pass, especially when the entire test suite takes under a minute!  Are you aware of any way in which I can modify attributes of mock created EC2 instances so that I can push the launchtime back in time a bit please?

Thanks again!

**Comment by spulec** [comment]
Can you use freezegun and then have it move the [time forward](https://github.com/spulec/freezegun#moving-time-to-specify-datetime)?

This won't work if you are using the standalone server mode.

**Comment by minigoatboy** [comment]
Hi Spulec,

Thanks for the response and also apologies for my delay in responding to you.  This looks like it'll do exactly what I need, so I'll take a look now.

Thank you!
