### ISSUE TITLE
Add support  for organizations API to tag_resource and list_tag_for_resources

### ISSUE THREAD

**Issue by SiahaanBernard** [spulec/moto#2479]
Hi
Thank you for creating this amazing library.

Currently I'm working creating tools for managing aws organizations and account(organizations api), unfortunately not all functions is covered yet [IMPLEMENTATION_COVERAGE](https://github.com/spulec/moto/blob/master/IMPLEMENTATION_COVERAGE.md),
I would like to mockout these functions:
- `tag_resource`
- `list_tag_for_resources`

I'm currently working on this issue in my local  and will create PR for this feature, might need your help and guidance.

**Comment by spulec** [comment]
Cool, thanks for opening. Setting this as a feature request.
