### ISSUE TITLE
SSM issue when URL is used as a value.

### ISSUE THREAD

**Issue by rjamesnw** [spulec/moto#2498]
I was told to lost here regarding this issue: https://github.com/localstack/serverless-localstack/issues/45#issuecomment-536738225

Try to create an SSM property:
    > aws. ssm put-parameter --name /test/propa --value "http://theres.nothinghere.com/abc" --type String --region us-east-1 --overwrite

It doesn't work, because AWS, by default, treats URLs as value SOURCES, which is just stupid, and the only way to treat the URL as a STRING value is to set `cli_follow_urlparam=false` in the AWS config file.

The problem is that your project does not respect this setting, and URL values fail to deploy.

Read more about it here: https://github.com/aws/aws-cli/issues/3451

**Comment by spulec** [comment]
I don't exactly understand how you are using Moto. It sounds like you are using Moto in server mode and using the aws cli client. Then Moto is just acting as the server so it can't respect any client-side config (it wouldn't have access).

I don't know how serverless-localstack works, but this doesn't seem like it can be a Moto issue based on my look at the code.

**Comment by rjamesnw** [comment]
I’m not using it directly. I’m using local stack which uses it. I was told the issue wasn’t with local stack and was sent here. The link to the original post is above.

**Comment by JackDanger** [comment]
@rjamesnw It looks like this all happens client-side: https://github.com/aws/aws-cli/blob/ffe0b199c4d3faf74ea0ab599d5617911481dda1/awscli/paramfile.py#L191-L199

It appears that aws-cli reads your local configuration to (optionally) disable fetching these URLs and, if it's not disabled, it performs the fetch before making a call to AWS/Moto/Localstack. So by the time Localstack or Moto receive the request I think the url fetching has already taken place?

**Comment by rjamesnw** [comment]
I have no idea.  I don't know enough about these systems.  I just know it doesn't work with localstack, but does work normally.  When `cli_follow_urlparam=false`, the URL itself IS the value, and not what it points to.

**Comment by bblommers** [comment]
In the latest version of CLI, it simply stores the value itself, without fetching anything:
``` bash
$ aws ssm put-parameter --name /test/propa --value "http://theres.nothinghere.com/abc" --type String --region us-east-1 --overwrite --endpoint-url http://localhost:4566
{
    "Version": 1
}
$ aws ssm get-parameter --name '/test/propa' --region us-east-1 --endpoint-url http://localhost:4566
{
    "Parameter": {
        "Name": "/test/propa",
        "Type": "String",
        "Value": "http://theres.nothinghere.com/abc",
        "Version": 1,
        "LastModifiedDate": "2022-03-24T10:17:17.548000-01:00",
        "ARN": "arn:aws:ssm:us-east-1:123456789012:parameter/test/propa",
        "DataType": "text"
    }
}

```
There is also no reference in the docs to `cli_follow_urlparam`, so it looks like they dropped this behaviour.

I'm assuming that fixes this issue, so I'll close this.
