### ISSUE TITLE
Using python3 comparison functions fail with NoneType exception

### ISSUE THREAD

**Issue by qnordic** [spulec/moto#2510]
Working on a specific repro script but I came across an issue in the comparisons.py file when one of the values is None.

Suspect code that fails:
https://github.com/spulec/moto/blob/master/moto/dynamodb2/comparisons.py#L932-L938

These issues did not happen in Python2 since `None` was evaluated to always be less than any integer, however, in Python3 any time a comparison of `<` or `>` is used, `None` does not work.

**Comment by spulec** [comment]
Fixed with https://github.com/spulec/moto/pull/2511
