### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by Sytten** [spulec/moto#2516]
It's been a while since there was a release, this process should be automated in travis.
Also note that the release in bumpconfig is not in sync nor the releases in github with what is on pypi.

**Comment by Sytten** [comment]
Tagging the owner @spulec so we can get some feedback

**Comment by gdippolito** [comment]
:ship: :ship: :ship:

**Comment by stribb** [comment]
@spulec Is there anything we can do to help? One of my projects has lower coverage than it otherwise would if Moto were updated, so I have a strong incentive to help out :)

**Comment by Sytten** [comment]
I am working on a better CI for the project, meanwhile I switched to the dev releases for my own project to get the latest features @stribb

**Comment by spulec** [comment]
If someone wants to update the changelog, that would be a big help. Otherwise, I suggest using the dev releases.

**Comment by bblommers** [comment]
Here you go @spulec: https://github.com/spulec/moto/pull/2556. Update to the changelog.

**Comment by spulec** [comment]
`moto 1.3.14` is now released.
