### ISSUE TITLE
Add mocks for AWS DataSync

### ISSUE THREAD

**Issue by baolsen** [spulec/moto#2526]
Create moto service/endpoints to test the boto3 DataSync APIs
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/datasync.html

**Comment by baolsen** [comment]
I'm busy with AIRFLOW-5824 and would like to use moto for testing the DataSync backend. Going to start working on this so long as I need something in place soonish

**Comment by baolsen** [comment]
PR submitted 
https://github.com/spulec/moto/pull/2532

**Comment by spulec** [comment]
Closed with https://github.com/spulec/moto/pull/2532
