### ISSUE TITLE
"InvalidParameter: Phone number does not meet the E164 format" from recent update to localstack SNS

### ISSUE THREAD

**Issue by john20xdoe** [spulec/moto#2529]
Not sure if I should file this in the localstack Github Repo. Please advise if I need to move this issue. 

A recent update for validating E164 format broke localstack SNS subscribe. in the real AWS SNS, dashes in the E.164 formatted number is supported aside from the usual E.164 format.

**In AWS SNS:**
```
# usual 
+631234567890
# also still allowed
+63-123-456-7890
```
This works in our production SNS that uses `apiVersion: 2010-03-31`.

**When using localstack SNS** 
It rejects the dashed phone number with the error:
`Stack trace "InvalidParameter: Phone number does not meet the E164 format\n    at Request.extractError...` (This is when used via npm 'aws-sdk' in a nodejs app. A simpler repro using awscli is below.)

**Step to replicate** (needs `awscli`, and maybe `awscli-local`, installable by pip)
1. Spin up localstack SNS service. (defaults to http://localstack:4575)
2. Prepare a mock topic.
```
$ aws --endpoint-url=http://localhost:4575 sns create-topic --name SOME_TOPIC

{
    "TopicArn": "arn:aws:sns:us-west-2:123456789012:SOME_TOPIC"
}
```
3. Subscribe to the mock topic with "usual" E164 format. (succeeds)
```
$ aws --endpoint-url=http://localhost:4575 sns subscribe --topic-arn arn:aws:sns:us-west-2:123456789012:SOME_TOPIC --protocol sms --notification-endpoint +631234567890

{
    "SubscriptionArn": "arn:aws:sns:us-west-2:123456789012:SOME_TOPIC:2002f71d-1a9e-425c-9065-1d709b5c6c53"
}
```
4. Subscribe to the mock topic with "dashed" E164 format. (rejected).
```
$ aws --endpoint-url=http://localhost:4575 sns subscribe --topic-arn arn:aws:sns:us-west-2:123456789012:SOME_TOPIC --protocol sms --notification-endpoint +63-123-456-7890

An error occurred (InvalidParameter) when calling the Subscribe operation: Phone number does not meet the E164 format
```

The cause was a recent update to the REGEX for checking E164 format.
https://github.com/spulec/moto/blob/e00af2f73cb7d27c3755f18b2161b9acbd8ca8aa/moto/sns/utils.py#L5

Is it possible to make this REGEX support dashes? The real AWS SNS supports it, and our production db has thousands of records with the dashed format and they are working. Would be nice if localstack and moto can imitate that as well. =)

**Comment by john20xdoe** [comment]
HI @spulec , can you give an idea when the merged fix will possibly reflect in the latest localstack image? I'm unfamiliar how the changes in moto goes into their latest image. As of writing, the latest localstack SNS docker image still rejects the dashed phone number.

**Comment by spulec** [comment]
I'm unfamiliar as well. I don't have anything to do with Localstack so I couldn't tell you.
