### ISSUE TITLE
Remove debug logs

### ISSUE THREAD

**Issue by jjbuck** [spulec/moto#2535]
I'm using the "mock_s3" module to mock some interactions with S3 in some unit tests. Is there a way to remove the debug-level logs that get printed? 

I've tried putting the following at the top of my unit tests without success.

```
import logging
for name in logging.Logger.manager.loggerDict.keys():
    if ('moto' in name) or ('mock_s3' in name):
        logging.getLogger(name).setLevel(logging.CRITICAL)

```

**Comment by spulec** [comment]
Can you give an example of the logs you are seeing? Moto only logs in a couple places (Cloudformation comes to mind) so I would be surprised to see a lot of them.

**Comment by bblommers** [comment]
If moto is running in server mode, you might have to disable Flask logging, since that does have quite a lot of logging.
Going to close this for now due to inactivity - feel free to reopen if it's still an issue
