### ISSUE TITLE
Mocking the AccountId

### ISSUE THREAD

**Issue by fabioasdias** [spulec/moto#2545]
As far as I could tell, the accountid used in moto is hard-coded in iam.models.

I would very much like to be able to test stuff across several custom accounts (so I can have unified code that behaves differently based on where it is). Is this on the roadmap? Am I missing an existing way of doing this?

This is related to #27 in spirit.

**Comment by mikegrima** [comment]
Unfortunately, this is really hard to solve, as there is effectively 1 dataset for each region, and adding account abstraction would be a big endeavor.

You might be able to fake things by mocking out the account number.

**Comment by fabioasdias** [comment]
Easier said than done, a quick search on the source codes revealed that '123456789012' is hardcoded in about 282 places in 57 files. So mocking moto.iam.models.ACCOUNT_ID (which would be the reasonable place for it, if a central configuration setting isn't adopted - which would be handy for the multiple account support) doesn't affect much.

**Comment by fabioasdias** [comment]
(Matter of fact, shouldn't the AccountId be a string, to allow for leading zeros?)
