### ISSUE TITLE
Unable to execute template actions against SES

### ISSUE THREAD

**Issue by kevinfguo** [spulec/moto#2549]
Moto claims that all SES endpoints are implements; but it seems like endpoints around actions that invoke email templates are not. I first discovered the issue through usage of [localstack](https://github.com/localstack/localstack), which wraps around moto. 

Any template action I make against localstack's SES results in a 500 response. If I do something as simple as:

`aws --endpoint-url=http://localhost:4579 ses list-templates`

I get a 500. Same thing if I make an action such as:

`aws ses get-template --template-name test`

I would expect the proper error response, such as:
`An error occurred (TemplateDoesNotExist) when calling the GetTemplate operation: Template test does not exist.`

Looking into the moto SES implementation on both the [models](https://github.com/spulec/moto/blob/master/moto/ses/responses.py) and [responses](https://github.com/spulec/moto/blob/master/moto/ses/responses.py), it does not appear that templates are implemented (e.g. `getTemplate`, `createTemplate`, `listTemplates`), nor are other methods such as `sendBulkTemplatedEmail`. 

It would be ideal for to store a fake template similar to how moto stores a verified identity and to be able to use those templates to mock sending bulk templated emails.

**Comment by spulec** [comment]
We don't claim to implement all SES endpoints. See [here](https://github.com/spulec/moto/blob/master/IMPLEMENTATION_COVERAGE.md#ses).

I'm happy to set this as a feature request for adding the template endpoints.

**Comment by spulec** [comment]
Oh, I see in the README that we contradict this and say all endpoints are done. Sorry about that. The README is not always comprehensive. I'll work on cleaning that up.

**Comment by bblommers** [comment]
The create-template, list-template and get-template have been implemented by https://github.com/spulec/moto/pull/2987.
These methods should be available as of moto >= 1.3.15.dev847.

Feel free to open a new issue if anything is still missing.
