### ISSUE TITLE
Add support for DAX

### ISSUE THREAD

**Issue by srypher** [spulec/moto#2558]
Hello, I'm currently adding DAX clusters to some dynamo instances in services that I'm writing and find that it'd be really useful to be able to mock out DAX clients for unit testing. I don't see anything in the docs about DAX mocks in moto and wanted to put in a feature request to add support for this. Thanks, and apologies in advance if this isn't the correct place to submit a feature request!

**Comment by spulec** [comment]
Thanks for opening! Setting this as a feature request.
