### ISSUE TITLE
dynamodb2 create_table should not expect all attributes to be indexes

### ISSUE THREAD

**Issue by remarkablerocket** [spulec/moto#2561]
I've just upgraded to 1.3.14 and started having this issue.

Creating a table with one key and several attributes (including the key) but no secondary indexes results in the following error:
```botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the CreateTable operation: One or more parameter values were invalid: Some index key attributes are not defined in AttributeDefinitions. Keys: ['KeyName'], AttributeDefinitions: ['KeyName', 'MyAttribute1']```

I think this might be down to the following line of code, which assumes the keys plus indexes will be equal to the attributes list, rather than a subset of it:
https://github.com/spulec/moto/blob/master/moto/dynamodb2/responses.py#L147

**Comment by bblommers** [comment]
Hi @remarkablerocket ,

Just to check I understand the use case directly - is this a representative test?
```
def test_attr_definitions():
    dynamodb = boto3.client("dynamodb", region_name="us-east-1")
    dynamodb.create_table(
        AttributeDefinitions=[{"AttributeName": "customer_nr", "AttributeType": "S"},
                              {"AttributeName": "other", "AttributeType": "S"}],
        TableName="table_with_missing_attribute_definitions",
        KeySchema=[{"AttributeName": "customer_nr", "KeyType": "HASH"}],
        BillingMode="PAY_PER_REQUEST",
    )
```
Running that against AWS itself gives an error as well:
```
One or more parameter values were invalid: Number of attributes in KeySchema does not exactly match number of attributes defined in AttributeDefinitions
```
Moto gives the wrong error message, but it is right in failing an invalid create-operation like that, I think.

**Comment by remarkablerocket** [comment]
Damn, you're right. I could've sworn I'd used this setup successfully before but now I've checked and turns out I used secondary indexes previously 😅
