### ISSUE TITLE
DynamoDB update_item does not update item on value type change (regression in 1.3.14)

### ISSUE THREAD

**Issue by rbu** [spulec/moto#2562]
Our automated tests ran with moto 1.3.14 today and we experience several unexpected test failures, all relating to DynamoDB. From the cases I looked at, it seems moto's dynamodb now fails to update an item's value when its type changes. Consider this test (works in 1.3.13, fails in 1.3.14). All tests run on Python 3.7.5.

```
import moto

with moto.mock_dynamodb2():
    dynamo = boto3.resource("dynamodb", region_name="eu-central-1")
    dynamo.create_table(
        AttributeDefinitions=[{"AttributeName": "job_id", "AttributeType": "S"}],
        TableName="origin-rbu-dev",
        KeySchema=[{"AttributeName": "job_id", "KeyType": "HASH"}],
        ProvisionedThroughput={"ReadCapacityUnits": 1, "WriteCapacityUnits": 1},
    )
    table = dynamo.Table("origin-rbu-dev")
    table.put_item(Item={"job_id": "a", "output": None})
    table.update_item(
                Key=dict(job_id="a"),
                UpdateExpression="SET output = :output",
                ExpressionAttributeValues={
                    ":output": "updated",
                },
    )
    assert table.scan()["Items"][0]["output"] == "updated"
```

Bisecting yielded this commit:
64cf1fc2c9825a029402a347d2c4977c04c58dbb is the first bad commit
commit 64cf1fc2c9825a029402a347d2c4977c04c58dbb
Author: Bert Blommers <bblommers@users.noreply.github.com>
Date:   Tue Oct 22 20:40:41 2019 +0100

    Refactor DynamoDB update expressions (#2497)
    
    * Refactor DynamoDB.update to use recursive method for nested updates
    
    * Simplify DynamoDB.update_item logic

**Comment by rbu** [comment]
ping #2497

**Comment by bblommers** [comment]
Thanks for opening this issue @rbu - you're correct, that did break in my refactoring exercise.
See the attached PR - I've fixed the issue, and added your test case to verify this is now working.

**Comment by rbu** [comment]
@bblommers thanks for looking into this and fixing it so fast. I ran our test suite with moto master (6922606) and it's green again.
