### ISSUE TITLE
Class Decorator is blocking os.environ patching in setup/teardown in 1.3.14 (worked on 1.3.13)

### ISSUE THREAD

**Issue by clowtown** [spulec/moto#2566]
Class level decorator is decorating the setup/teardown which is preventing them from setting other key values. 

I understand that mocking setup can also be a good thing if we are setting up a boto client, but raising this issue in case it was not intentional. My own attempt to `patch.dict` os.environ further inside setup seemed to work but unsure of side effects.

python version 3.7.5
```
from moto import mock_s3
@mock_s3
class MotoUpdateBrokeTest(unittest.TestCase):
    def setUp(self) -> None:
        os.environ["GLUE_JOB_NAME"] = "glue-job"

    def tearDown(self):
        pass

    def test_env_is_set(self):
        self.assertEqual(os.environ["GLUE_JOB_NAME"], "glue-job")

```

resulting test run
```
 _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = environ({'AWS_ACCESS_KEY_ID': 'foobar_key', 'AWS_SECRET_ACCESS_KEY': 'foobar_secret'})
key = 'GLUE_JOB_NAME'

    def __getitem__(self, key):
        try:
            value = self._data[self.encodekey(key)]
        except KeyError:
            # raise KeyError with the original key value
>           raise KeyError(key) from None
E           KeyError: 'GLUE_JOB_NAME'
```

**Comment by clowtown** [comment]
#2285

**Comment by clowtown** [comment]
@bblommers @spulec  - I'm not sure on a good resolution to this, but I'm curious what others are doing when they need to mock environment variables. Given the fact that the class level decorator will wrap all class methods, including the setup/teardown, are we better off to 

- Create an additional class to define non setup/teardown methods and delegate to the decorated class?
- Only annotate test methods and no longer the class (perhaps remove class level support for decorator?)
- Use a Test Suite to orchestrate the setup/teardown and wire in the test case (with it's setup/teardown replaced if unneeded)

**Comment by spulec** [comment]
The patching won't override any environment variables which were set before it started. For example, the following works.

```
class MotoUpdateBrokeTest(unittest.TestCase):
    def setUp(self) -> None:
        os.environ["GLUE_JOB_NAME"] = "glue-job"
        self.s3_mock = mock_s3()
        self.s3_mock.start()

    def tearDown(self):
        self.s3_mock.stop()

    def test_env_is_set(self):
        self.assertEqual(os.environ["GLUE_JOB_NAME"], "glue-job")
```

**Comment by clowtown** [comment]
@spulec the issue isn’t with standard patching, it’s with the class decorator. Attempt your example above with class decorator and the test should fail. This is because the setup is wrapped and environment patch is undone by the decorator

**Comment by spulec** [comment]
Yes, agree. Sorry, I was attempting to answer the "what are others doing" and give you a workaround.
