### ISSUE TITLE
[Question] Unit test TearDown removing everything

### ISSUE THREAD

**Issue by emirot** [spulec/moto#2590]
Hi There,

I would like to use Moto to do some unit tests.

Current Version: moto==1.3.14

I have some issues tearing down my fake infrastructure.
Like `botocore.exceptions.ClientError: An error occurred (InvalidVolume.NotFound) when calling the DescribeVolumes operation: The volume '{'vol-43e1cbd3'}' does not exist.`

I would like to have in my unit tests two things:
- setUp (creates the infra for every test)
- tearDown (terminate resources) I would like to delete everything  so next run I don't have terminated instances but a fresh new fake infra.
Is there a way to do that ?

Best,

Nolan

**Comment by emirot** [comment]
Should it be used like so: https://stackoverflow.com/a/37844504/2201037

```
import unittest
import boto
from boto.s3.key import Key
from moto import mock_s3
import boto3


class TestS3Actor(unittest.TestCase):
    mock_s3 = mock_s3()

    def setUp(self):
        self.mock_s3.start()
        self.location = "eu-west-1"
        self.bucket_name = 'test_bucket_01'
        self.key_name = 'stats_com/fake_fake/test.json'
        self.key_contents = 'This is test data.'
        s3 = boto.connect_s3()
        bucket = s3.create_bucket(self.bucket_name, location=self.location)
        k = Key(bucket)
        k.key = self.key_name
        k.set_contents_from_string(self.key_contents)

    def tearDown(self):
        self.mock_s3.stop()

    def test_s3_boto3(self):
        s3 = boto3.resource('s3', region_name=self.location)
        bucket = s3.Bucket(self.bucket_name)
        assert bucket.name == self.bucket_name
        # retrieve already setup keys
        keys = list(bucket.objects.filter(Prefix=self.key_name))
        assert len(keys) == 1
        assert keys[0].key == self.key_name
        # update key
        s3.Object(self.bucket_name, self.key_name).put(Body='new')
        key = s3.Object(self.bucket_name, self.key_name).get()
        assert 'new' == key['Body'].read()
```

Is it possible with the decorator ?

**Comment by spulec** [comment]
As part of the `mock_s3.start()` call, it should be resetting all of the data. If that isn't what you are seeing, can you please post the code related to volumes that you are describing?

**Comment by bblommers** [comment]
Going to close this due to a lack of response, but feel free to let me know if this is still an issue.

**Comment by medley56** [comment]
@bblommers I think this is still an issue. I'm using `mock_s3` context manager, which should presumably call `start()` upon entering but in separate tests I'm having pre-existing object conflicts.

**Comment by bblommers** [comment]
@medley56 Can you share a minimum reproducible example of your usecase?
Which version of Moto are you using?

**Comment by medley56** [comment]
Actually I am now thinking it's a separate but possibly still real issue. I'm getting a FileExistsError when using mock_s3 with cloudpathlib's exclusive write mode option to S3Path but it's not because the file in the mock bucket exists. It's because the local file that's actually getting stored behind the scenes of mock_s3 apparently already exists on the filesystem so the exclusive write fails. Is there a reason that mock_s3 would pre-create a file object and then try to write to it after it exists?

**Comment by medley56** [comment]
This is not reliably reproducible. I'll open a new issue if I can figure out how to make it happen reproducibly.
