### ISSUE TITLE
New MarketplaceMetering.batch_meter_usage endpoint

### ISSUE THREAD

**Issue by stj** [spulec/moto#2592]
I started work on a mock for the [MarketplaceMetering.Client.batch_meter_usage](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/meteringmarketplace.html#MarketplaceMetering.Client.batch_meter_usage) endpoint in a [branch of mine](https://github.com/stj/moto/tree/meteringmarketplace).
To make sure I am doing it in a way that it can be accepted to be merged into moto, I'd like to get some guidance on how I should go in writing this.

Happy to make a WIP PR to use for further discussions.

**Comment by spulec** [comment]
This looks like a great start! A PR would be very welcome.

**Comment by bblommers** [comment]
Hi @stj, is this still something you're interested in? It looks like the branch is (still) in good shape. 

Let me know if you want some help with this! Happy to clean up any merge conflicts etc.

**Comment by bblommers** [comment]
Hope you don't mind @stj  - I took your branch, cleaned it up a bit, and released it. This is now part of moto >= 4.0.7.dev21.
Please let us know if you run into any issues with this, or want to see more features.

**Comment by stj** [comment]
This was a really old branch and I don't think work was finished. I remember having a hard time understanding the implementation of moto to figure out how to write the mock API.
In the end I didn't use moto for my implementation.
Did you test this branch before merging?

**Comment by bblommers** [comment]
@stj I was able to reuse the tests that you wrote, actually - it only covered the happy path, but I figured that was a good start.

The biggest limitation of the current implementation is probably that all records will have the status `CustomerNotSubscribed`, just because the `resolve_customer` isn't yet implemented.
