### ISSUE TITLE
API Key value should be at least 20 characters

### ISSUE THREAD

**Issue by jzivanov** [spulec/moto#2607]
The create_api_key api, is missing validation on api_key value min length. 

`aws apigateway create-api-key --name 'TESTKEY' --description 'should not be valid' --value '12345'
`

> An error occurred (BadRequestException) when calling the CreateApiKey operation: API Key value should be at least 20 characters

**Comment by bblommers** [comment]
This is now part of moto >= 1.3.17.dev265
