### ISSUE TITLE
cognito-idp issue. create_user_pool isn't working.

### ISSUE THREAD

**Issue by perez-alejandrodaniel** [spulec/moto#2612]
Hi everyone!

I'm trying to mock congnito-idp and I'm having problems with the line
https://github.com/spulec/moto/blob/502957f1f9560cb6dff75271e6812498f4ff7bba/moto/cognitoidp/models.py#L71

My unit test try to create a signed user and add it to a new users pool

```
   cidp = boto3.client('cognito-idp', region_name='us-east-1')

    pool_name = 'users-pool-for-testing'
    pool_lambda_value = \
        'arn:aws:lambda:{}:{}:function:my-function-{}-cognito-pre-signup'\
        .format('us-east-1', '123456789012', 'dev')

    result = cidp.create_user_pool(PoolName=pool_name, LambdaConfig={"PreSignUp": pool_lambda_value})

    r = cidp.sign_up(
        ClientId='9rb9mhrfqme9lbjepb999jrlml',
        Username='cognito-test-user',
        Password='password',
        UserAttributes=[{'Name': 'email',
                         'Value': 'cognito-test-user@notmydomain.ro'}])

    r = cidp.admin_confirm_sign_up(
        UserPoolId=pool_name,
        Username='cognito-test-user')
```

I'm receiving the following error:
```
self = <moto.cognitoidp.models.CognitoIdpUserPool object at 0x7fa082bbfa20>
region = 'us-east-1', name = 'users-pool-for-testing'
extended_config = {'LambdaConfig': {'PreSignUp': 'arn:aws:lambda:us-east-1:123456789012:function:my-function-dev-cognito-pre-signup'}, 'PoolName': 'users-pool-for-testing'}

    def __init__(self, region, name, extended_config):
        self.region = region
>       self.id = "{}_{}".format(self.region, str(uuid.uuid4().hex))
E       AttributeError: 'str' object has no attribute 'hex'

../../../venv/lib/python3.7/site-packages/moto/cognitoidp/models.py:71: AttributeError
```

Environment.
- Python 3.7
- Moto 1.3.14
- Boto 1.10.18

I have checked twice my environment and my code, and I couldn't detect any other possible source of errors. I'm using other features from Moto, like DynamoDB mock, SQS mock and S3 mock without problems.

**Comment by spulec** [comment]
Hmmm, I am struggling to recreate this. Can you drop a `import pdb;pdb.set_trace()` in there and confirm it is the `uuid.uuid4()` that is causing the issue? Do you happen to have an alternative `uuid` library installed?

**Comment by bblommers** [comment]
Going to close this due to a lack of response, but feel free to let me know if this is still an issue.
