### ISSUE TITLE
Cloudwatch put_metric_data expects microseconds.

### ISSUE THREAD

**Issue by markchalloner** [spulec/moto#2614]
The [cloudwatch function put_metric_data expects a timestamp with microseconds](https://github.com/spulec/moto/blob/502957f1f9560cb6dff75271e6812498f4ff7bba/moto/cloudwatch/models.py#L277) in the format:

```
%Y-%m-%dT%H:%M:%S.%fZ
```

However if the datetime does not have microseconds (e.g. sourced from cost-explorer or `datetime.datetime(2019, 12, 3, 0, 0, 0)` then the call to `datetime.strptime` will fail with the error:

```
 ValueError: time data '2019-12-03T00:00:00Z' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'
```

A workaround is to add a microsecond if one doesn't exist:

```
datetime_ = datetime.datetime(2019, 12, 3, 0, 0, 0)
if datetime_.microsecond == 0:
    datetime_ += datetime.timedelta(microseconds=1)
```

**Comment by PeterCui1991** [comment]
@markchalloner Hi, do we have any update on this issue? It seems like put metric data automatically assign millisecond to timestamp which cannot match datapoint format which expects self[name] = datetime.strptime(value, '%Y-%m-%dT%H:%M:%SZ'). Please let me know we have a solution for this.

**Comment by bblommers** [comment]
Closing - the associated PR has fixed this
