### ISSUE TITLE
Batch RegisterJobDefinition (and other APIs?) missing support for timeout.attemptDurationSeconds

### ISSUE THREAD

**Issue by kislyuk** [spulec/moto#2628]
See:
- https://docs.aws.amazon.com/batch/latest/APIReference/API_JobTimeout.html#Batch-Type-JobTimeout-attemptDurationSeconds
- https://docs.aws.amazon.com/batch/latest/APIReference/API_RegisterJobDefinition.html
- https://docs.aws.amazon.com/batch/latest/APIReference/API_SubmitJob.html

The moto server accepts the input, but does not correctly echo it back out.

**Comment by bblommers** [comment]
This merged PR now echoes the output, and also implements the behavior - Batch jobs will be stopped when the runtime exceeds the max duration.

Let us know if there are any other issues.
