### ISSUE TITLE
Xray Client Broken Tests

### ISSUE THREAD

**Issue by mikegrima** [spulec/moto#2638]
@terrycain : Can you take a look at why the XRay Client tests are broken?

Something about:
```
aws_xray_sdk.core.exceptions.exceptions.SegmentNotFoundException: cannot find the current segment/subsegment, please make sure you have a segment open
```

**Comment by mikegrima** [comment]
Interesting... If I'm in the `moto/tests/test_xray` directory and run `nosetests` from there, there are no errors.

Errors are only showing when I'm in the `moto/` directory...

**Comment by mikegrima** [comment]
So this is interesting... When running the Xray tests, a `.coverage` Sqlite database is created.

The stracktrace is showing an error related to sqlite.

**Comment by mikegrima** [comment]
It looks like the issue is related to `coverage` 5.0, which was recently released. They recently introduced sqlite support and somehow that it is not playing nicely with the xray client.

**Comment by mikegrima** [comment]
In the meantime, I am going to pin `coverage` to `4.5.4`.

**Comment by Syntactical01** [comment]
Any update on this bug?
