### ISSUE TITLE
AMI creation_date not specific enough to allow for sorting

### ISSUE THREAD

**Issue by curiositycasualty** [spulec/moto#2653]
**Description:**
While working on an internal AMI cleanup tool, I found it difficult to use `moto` since the `instance.create_image` actions called in rapid succession will create "AMI"s that all have a similar `creation_date`, see below.

**Actual:**
"AMI"s `image` resources created with moto have a `creation_date` which is only specific to the second

**Expected:**
I was hoping that the specificity of the timestamp might vary enough between calls at the millisecond level to allow me to test my cleanup tool `creation_date` sorting features.

**Workaround:**
Add a delay using `time.sleep` of at least 1 second between `instance.create_image` calls such that `creation_date` is varied.

```python
for selection in selections:
            <snip>
            image = instance.create_image(Name=<snip>)
            image.create_tags(Tags=tags(**selection))
```

```python
In [2]: [x.creation_date for x in self._ec2.images.all()]
Out[2]:
['2019-12-23T21:48:44.000Z',
 '2019-12-23T21:48:44.000Z',
 '2019-12-23T21:48:44.000Z',
 '2019-12-23T21:48:44.000Z',
 '2019-12-23T21:48:44.000Z',
 '2019-12-23T21:48:44.000Z',
 '2019-12-23T21:48:44.000Z',
 '2019-12-23T21:48:44.000Z',
 '2019-12-23T21:48:44.000Z',
 '2019-12-23T21:48:44.000Z',
 '2019-12-23T21:48:44.000Z',
 '2019-12-23T21:48:44.000Z',
 '2019-12-23T21:48:44.000Z']
```

**Comment by spulec** [comment]
Looking at some real AWS calls, this seems to match their behavior. I can see how it would be annoying here, but our goal is to match what AWS does.

I'm going to close this, but let me know if you are seeing different behavior for AWS.

**Comment by curiositycasualty** [comment]
This is the solution I was thinking of: https://github.com/spulec/moto/compare/master...curiositycasualty:if/microseconds?expand=1

But then I went and looked and you are correct. EC2 doesn't cough up any microseconds either :/
```bash
aws --profile <profile> ec2 describe-images --owners=self --query 'Images[*].CreationDate'
[
    "2019-07-31T19:01:35.000Z",
    "2019-08-16T18:40:29.000Z",
    "2019-02-12T22:06:57.000Z",
    "2019-01-22T20:56:17.000Z",
```

**Comment by spulec** [comment]
Assuming you aren't using the server-based mode of Moto, you could use Freezegun and the tick argument to move time forward: https://github.com/spulec/freezegun#tick-argument

That will at least make it so that your test doesn't have to actually wait.
