### ISSUE TITLE
S3 CreationDate not correctly formatted

### ISSUE THREAD

**Issue by rnorth** [spulec/moto#2665]
I think there's a small regression in version 1.3.15.3 of the library, as used by Localstack.

This appears to be generating incorrectly formatted `CreationDate` fields in S3 ListBucket responses, which breaks some clients (AWS Java SDK chokes on the formatting; AWS CLI does not).

More background is captured in this Localstack issue: https://github.com/localstack/localstack/issues/1899

I suspect this issue can be simply fixed by amending this line to format the creation date according to ISO8601: https://github.com/spulec/moto/commit/ab0853cddc6bf9a0789999751a5d698186b8ebd0#diff-f28b3d402b1d050e247f518f3b94865bR1313

**Comment by spulec** [comment]
I think this should be fixed with https://github.com/spulec/moto/commit/19bf8bf76207a01a168ec842c2e4e917adc466dd

Let me know if that isn't sufficient.

**Comment by timvlaer** [comment]
Apparently isoformat() doesn't add timezone info, so the Java SDK fails with `Invalid format: "2020-06-02T08:43:57.470630" is too short`. Adding a `Z` to the end solves the issue.

I made a fix similar to #2904 in PR #3040
