### ISSUE TITLE
Cognito-idp: readable attributes in JWT payload should be in idToken and not in accessToken

### ISSUE THREAD

**Issue by franz-see** [spulec/moto#2670]
This is related to https://github.com/spulec/moto/issues/1755 which implemented returning the readable attributes in the JWT Payload.

But that issue added the JWT attributes in the accessToken. It should have been in the idToken

See https://auth0.com/docs/api-auth/why-use-access-tokens-to-secure-apis for more information on idToken vs accessToken

**Comment by franz-see** [comment]
Pull Request for fix on this one - https://github.com/spulec/moto/pull/2671

**Comment by bblommers** [comment]
Closing, as the associated PR is now merged
