### ISSUE TITLE
Cognito-idp: jwt token always uses token_use of "id"

### ISSUE THREAD

**Issue by franz-see** [spulec/moto#2672]
Bug : Regardless if the jwt token is an access token or id token, it's `token_use` property is always `id`. 

The expected behaviour is that the access token jwt token's `token_use` should be `access` while id token jwt token's `token_use` should be `id`

**Comment by franz-see** [comment]
Pull Request - https://github.com/spulec/moto/pull/2673

**Comment by bblommers** [comment]
Closing this, as the associated PR is merged.
