### ISSUE TITLE
Mocked S3 keys don't preserve Content-Encoding

### ISSUE THREAD

**Issue by catlee** [spulec/moto#268]
I have some boto code which does this:

key = bucket.new_key("keyname")
key.set_metadata("Content-Encoding", "gzip")
key.set_contents_from_string(compressed_data)

Later, when I get the key, I can see the content-encoding property set properly:

key = bucket.get_key("keyname")
assert key.content_encoding == "gzip"

I can't test this with mocked S3 keys, the Content-Encoding metadata seems to disappear. It's not set on key.content_encoding, nor is it in key.metadata.

**Comment by twolfson** [comment]
I ran into this problem with `Content-Type`. Any word on when this is going to be published to `PyPI`?

**Comment by spulec** [comment]
Sorry about that. Just pushed `0.4.0` to PyPI!

**Comment by twolfson** [comment]
Awesome. thanks! =D
