### ISSUE TITLE
1.3.15 release?

### ISSUE THREAD

**Issue by joelhess** [spulec/moto#2681]
Is there a timeline for releasing the next update? We're looking for this to issue to be released: https://github.com/spulec/moto/issues/2563

Thanks for everything!

**Comment by bblommers** [comment]
FYI: You can use dev-releases that will have this fix included, until an official release is made
Dev-releases are done after every PR-merge, and versions are visible here: https://pypi.org/project/moto/#history

**Comment by owenfarrell** [comment]
@bblommers Thanks for the heads up re: pre-releases.

But to the point that @joelhess raised - what serves as the trigger for releases? Are you marching towards a specific date, folding in major new capabilities, or is there some other initiative that you are looking to get to "done"?

**Comment by spulec** [comment]
Given the nature of this project (always adding random features/endpoints/etc), we don't have much of a defined schedule. Every couple months or so, I try to cut an official release when I get some time, but encourage people to use the dev releases between as necessary.

I'm open to other ideas, especially if there is a reason that dev releases can't be used.

**Comment by mekza** [comment]
@spulec what do you think making a new pre-release available on PyPI every time a pull request is accepted and merged?

**Comment by spulec** [comment]
@mekza this is already being done. See here: https://pypi.org/project/moto/#history
