### ISSUE TITLE
SQS: RedrivePolicy cannot be retrieved using get_queue_attributes

### ISSUE THREAD

**Issue by npellegrin** [spulec/moto#2682]
Hello,

I upgraded from moto 1.3.7 to 1.3.14, and a comportment changed in SQS queues. It looks like a bug, you can find below the details :)

**what version of Moto you're using**
moto 1.3.14

**what you expected to happen**
When a SQS queue is created with a `RedrivePolicy` attribute, requesting the single `RedrivePolicy` attribute on the queue (with get_queue_attributes method) should return it.

**what actually happens**
When requesting `RedrivePolicy` attribute, the message `botocore.errorfactory.InvalidAttributeName: An error occurred (InvalidAttributeName) when calling the GetQueueAttributes operation: Unknown Attribute RedrivePolicy.` is displayed.

When requesting "All" attributes, RedrivePolicy actually exists in the returned attribute list.

**how to reproduce the issue**

Below, is a unit test using moto reproducing the problem.

```
import json
import boto3

from moto import mock_sqs


@mock_sqs
def test_get_queue_redrive_policy():
    client = boto3.client('sqs')

    client.create_queue(QueueName='dlq')
    dlq_arn = client.get_queue_attributes(
        QueueUrl="https://eu-west-1.queue.amazonaws.com/123456789012/dlq")['Attributes']['QueueArn']

    expected = json.dumps({
        "maxReceiveCount": 5,
        "deadLetterTargetArn": dlq_arn
    })
    client.create_queue(
        QueueName='sqs_queue',
        Attributes={
            "RedrivePolicy": expected
        })

    attributes = client.get_queue_attributes(
        QueueUrl="https://eu-west-1.queue.amazonaws.com/123456789012/sqs_queue",
        AttributeNames=["RedrivePolicy"])

    assert attributes['Attributes']['RedrivePolicy'] == expected
```

You can notice that replacing `AttributeNames=["RedrivePolicy"]` to `AttributeNames=["All"]` will pass the test.

**Comment by npellegrin** [comment]
It is not an enhancement, it worked with moto 1.3.7

**Comment by joemulray** [comment]
+1 also experiencing this same issue, running on `moto 1.3.13`

**Comment by spulec** [comment]
Sorry about that; it should be fixed in master now.

**Comment by willronchetti** [comment]
Can we get a release for this? I can't use `moto` in my application because of this bug.

**Comment by spulec** [comment]
@willronchetti we do continuous releases so you can use this now: https://pypi.org/project/moto/#history
