### ISSUE TITLE
pip install moto fails for project

### ISSUE THREAD

**Issue by marcboggs** [spulec/moto#2686]
I could not find this issue in the forum, but trying to install moto from the command line or from pycharm fails.

Collecting moto
  Using cached https://files.pythonhosted.org/packages/1e/84/6e115b45be00273c7cfad5b9506b7c8a78bc7d2a11afe72517a7f6d01289/moto-1.3.14-py2.py3-none-any.whl
Collecting python-jose<4.0.0 (from moto)
  Using cached https://files.pythonhosted.org/packages/6c/80/5bdf2543fe002dc74429e9360148deb4d9e0b453acdc2b5c6fb1617f4f9d/python_jose-3.1.0-py2.py3-none-any.whl
Collecting python-dateutil<3.0.0,>=2.1 (from moto)
  Downloading https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl (227kB)
Collecting requests>=2.5 (from moto)
  Using cached https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl
Collecting boto3>=1.9.201 (from moto)
  Downloading https://files.pythonhosted.org/packages/43/a6/433564e7b241ecb012c67e6580e302ecdc79c8b5189e3f7efb6e7b0fde45/boto3-1.10.50-py2.py3-none-any.whl (128kB)
Collecting werkzeug (from moto)
  Using cached https://files.pythonhosted.org/packages/ce/42/3aeda98f96e85fd26180534d36570e4d18108d62ae36f87694b476b83d6f/Werkzeug-0.16.0-py2.py3-none-any.whl
Collecting boto>=2.36.0 (from moto)
  Using cached https://files.pythonhosted.org/packages/23/10/c0b78c27298029e4454a472a1919bde20cb182dab1662cec7f2ca1dcc523/boto-2.49.0-py2.py3-none-any.whl
Collecting aws-xray-sdk!=0.96,>=0.93 (from moto)
  Using cached https://files.pythonhosted.org/packages/f1/be/1580b7f224986de2bb328fafcaca0c6f460adb94d521709123ac12b80005/aws_xray_sdk-2.4.3-py2.py3-none-any.whl
Collecting botocore>=1.12.201 (from moto)
  Downloading https://files.pythonhosted.org/packages/24/2d/47bc2f26b9f014998ad5c6ed844424a69f8ea77d26dab22a4e2ddbff20d4/botocore-1.13.50-py2.py3-none-any.whl (5.9MB)
Collecting responses>=0.9.0 (from moto)
  Using cached https://files.pythonhosted.org/packages/3e/0c/940781dd49710f4b1f0650c450c9fd8491db0e1bffd99ebc36355607f96d/responses-0.10.9-py2.py3-none-any.whl
Collecting cfn-lint>=0.4.0 (from moto)
  Using cached https://files.pythonhosted.org/packages/04/11/0aea3979a3f98eabac05e47309aa3e44f7c1f6399a3504e1d51b9893df5c/cfn_lint-0.26.2-py3-none-any.whl
Collecting PyYAML>=5.1 (from moto)
  Using cached https://files.pythonhosted.org/packages/3d/d9/ea9816aea31beeadccd03f1f8b625ecf8f645bd66744484d162d84803ce5/PyYAML-5.3.tar.gz
Collecting xmltodict (from moto)
  Using cached https://files.pythonhosted.org/packages/28/fd/30d5c1d3ac29ce229f6bdc40bbc20b28f716e8b363140c26eff19122d8a5/xmltodict-0.12.0-py2.py3-none-any.whl
Collecting idna<2.9,>=2.5 (from moto)
  Using cached https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl
Collecting pytz (from moto)
  Using cached https://files.pythonhosted.org/packages/e7/f9/f0b53f88060247251bf481fa6ea62cd0d25bf1b11a87888e53ce5b7c8ad2/pytz-2019.3-py2.py3-none-any.whl
Collecting sshpubkeys<4.0,>=3.1.0 (from moto)
  Using cached https://files.pythonhosted.org/packages/08/96/b5308537f88df326939006a8331a2edc528f25d920c49dbd9fc2c53c4e68/sshpubkeys-3.1.0-py2.py3-none-any.whl
Collecting Jinja2>=2.10.1 (from moto)
  Using cached https://files.pythonhosted.org/packages/65/e0/eb35e762802015cab1ccee04e8a277b03f1d8e53da3ec3106882ec42558b/Jinja2-2.10.3-py2.py3-none-any.whl
Collecting cryptography>=2.3.0 (from moto)
  Using cached https://files.pythonhosted.org/packages/be/60/da377e1bed002716fb2d5d1d1cab720f298cb33ecff7bf7adea72788e4e4/cryptography-2.8.tar.gz
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Collecting six>1.9 (from moto)
  Using cached https://files.pythonhosted.org/packages/65/26/32b8464df2a97e6dd1b656ed26b2c194606c16fe163c695a992b36c11cdf/six-1.13.0-py2.py3-none-any.whl
Collecting jsondiff==1.1.2 (from moto)
  Using cached https://files.pythonhosted.org/packages/33/0c/ddb17571e061c655871ccbf76cdada55a31569327d21517de779d4887241/jsondiff-1.1.2.tar.gz
Collecting docker>=2.5.1 (from moto)
  Using cached https://files.pythonhosted.org/packages/cc/ca/699d4754a932787ef353a157ada74efd1ceb6d1fc0bfb7989ae1e7b33111/docker-4.1.0-py2.py3-none-any.whl
Collecting mock (from moto)
  Using cached https://files.pythonhosted.org/packages/05/d2/f94e68be6b17f46d2c353564da56e6fb89ef09faeeff3313a046cb810ca9/mock-3.0.5-py2.py3-none-any.whl
Collecting pyasn1 (from python-jose<4.0.0->moto)
  Using cached https://files.pythonhosted.org/packages/62/1e/a94a8d635fa3ce4cfc7f506003548d0a2447ae76fd5ca53932970fe3053f/pyasn1-0.4.8-py2.py3-none-any.whl
Collecting ecdsa<1.0 (from python-jose<4.0.0->moto)
  Using cached https://files.pythonhosted.org/packages/b8/11/4b4d30e4746584684c758d8f1ddc1fa5ab1470b6bf70bce4d9b235965e99/ecdsa-0.15-py2.py3-none-any.whl
Collecting rsa (from python-jose<4.0.0->moto)
  Using cached https://files.pythonhosted.org/packages/02/e5/38518af393f7c214357079ce67a317307936896e961e35450b70fad2a9cf/rsa-4.0-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.5->moto)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests>=2.5->moto)
  Using cached https://files.pythonhosted.org/packages/b9/63/df50cac98ea0d5b006c55a399c3bf1db9da7b5a24de7890bc9cfd5dd9e99/certifi-2019.11.28-py2.py3-none-any.whl
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests>=2.5->moto)
  Using cached https://files.pythonhosted.org/packages/b4/40/a9837291310ee1ccc242ceb6ebfd9eb21539649f193a7c8c86ba15b98539/urllib3-1.25.7-py2.py3-none-any.whl
Collecting jmespath<1.0.0,>=0.7.1 (from boto3>=1.9.201->moto)
  Using cached https://files.pythonhosted.org/packages/83/94/7179c3832a6d45b266ddb2aac329e101367fbdb11f425f13771d27f225bb/jmespath-0.9.4-py2.py3-none-any.whl
Collecting s3transfer<0.3.0,>=0.2.0 (from boto3>=1.9.201->moto)
  Using cached https://files.pythonhosted.org/packages/16/8a/1fc3dba0c4923c2a76e1ff0d52b305c44606da63f718d14d3231e21c51b0/s3transfer-0.2.1-py2.py3-none-any.whl
Collecting future (from aws-xray-sdk!=0.96,>=0.93->moto)
  Using cached https://files.pythonhosted.org/packages/45/0b/38b06fd9b92dc2b68d58b75f900e97884c45bedd2ff83203d933cf5851c9/future-0.18.2.tar.gz
Collecting jsonpickle (from aws-xray-sdk!=0.96,>=0.93->moto)
  Using cached https://files.pythonhosted.org/packages/07/07/c157520a3ebd166c8c24c6ae0ecae7c3968eb4653ff0e5af369bb82f004d/jsonpickle-1.2-py2.py3-none-any.whl
Collecting wrapt (from aws-xray-sdk!=0.96,>=0.93->moto)
  Using cached https://files.pythonhosted.org/packages/23/84/323c2415280bc4fc880ac5050dddfb3c8062c2552b34c2e512eb4aa68f79/wrapt-1.11.2.tar.gz
Collecting docutils<0.16,>=0.10 (from botocore>=1.12.201->moto)
  Using cached https://files.pythonhosted.org/packages/22/cd/a6aa959dca619918ccb55023b4cb151949c64d4d5d55b3f4ffd7eee0c6e8/docutils-0.15.2-py3-none-any.whl
Collecting jsonschema~=3.0 (from cfn-lint>=0.4.0->moto)
  Using cached https://files.pythonhosted.org/packages/c5/8f/51e89ce52a085483359217bc72cdbf6e75ee595d5b1d4b5ade40c7e018b8/jsonschema-3.2.0-py2.py3-none-any.whl
Collecting aws-sam-translator>=1.19.1 (from cfn-lint>=0.4.0->moto)
  Using cached https://files.pythonhosted.org/packages/a4/fb/46a67369e4e71cab8e73ca73ca0b938c297767d0ef8cfcad21b4f064ed66/aws-sam-translator-1.19.1.tar.gz
Collecting jsonpatch (from cfn-lint>=0.4.0->moto)
  Using cached https://files.pythonhosted.org/packages/86/7e/035d19a73306278673039f0805b863be8798057cc1b4008b9c8c7d1d32a3/jsonpatch-1.24-py2.py3-none-any.whl
Collecting MarkupSafe>=0.23 (from Jinja2>=2.10.1->moto)
  Using cached https://files.pythonhosted.org/packages/b9/2e/64db92e53b86efccfaea71321f597fa2e1b2bd3853d8ce658568f7a13094/MarkupSafe-1.1.1.tar.gz
Collecting cffi!=1.11.3,>=1.8 (from cryptography>=2.3.0->moto)
  Using cached https://files.pythonhosted.org/packages/2d/bf/960e5a422db3ac1a5e612cb35ca436c3fc985ed4b7ed13a1b4879006f450/cffi-1.13.2.tar.gz
Collecting pypiwin32==223; sys_platform == "win32" and python_version >= "3.6" (from docker>=2.5.1->moto)
  Using cached https://files.pythonhosted.org/packages/d0/1b/2f292bbd742e369a100c91faa0483172cd91a1a422a6692055ac920946c5/pypiwin32-223-py3-none-any.whl
Collecting websocket-client>=0.32.0 (from docker>=2.5.1->moto)
  Using cached https://files.pythonhosted.org/packages/4c/5f/f61b420143ed1c8dc69f9eaec5ff1ac36109d52c80de49d66e0c36c3dfdf/websocket_client-0.57.0-py2.py3-none-any.whl
Requirement already satisfied: setuptools in c:\users\abhalla\pycharmprojects\untitled\venv\lib\site-packages\setuptools-40.8.0-py3.8.egg (from jsonschema~=3.0->cfn-lint>=0.4.0->moto) (40.8.0)
Collecting attrs>=17.4.0 (from jsonschema~=3.0->cfn-lint>=0.4.0->moto)
  Using cached https://files.pythonhosted.org/packages/a2/db/4313ab3be961f7a763066401fb77f7748373b6094076ae2bda2806988af6/attrs-19.3.0-py2.py3-none-any.whl
Collecting pyrsistent>=0.14.0 (from jsonschema~=3.0->cfn-lint>=0.4.0->moto)
  Using cached https://files.pythonhosted.org/packages/90/aa/cdcf7ef88cc0f831b6f14c8c57318824c9de9913fe8de38e46a98c069a35/pyrsistent-0.15.7.tar.gz
Collecting jsonpointer>=1.9 (from jsonpatch->cfn-lint>=0.4.0->moto)
  Using cached https://files.pythonhosted.org/packages/18/b0/a80d29577c08eea401659254dfaed87f1af45272899e1812d7e01b679bc5/jsonpointer-2.0-py2.py3-none-any.whl
Collecting pycparser (from cffi!=1.11.3,>=1.8->cryptography>=2.3.0->moto)
  Using cached https://files.pythonhosted.org/packages/68/9e/49196946aee219aead1290e00d1e7fdeab8567783e83e1b9ab5585e6206a/pycparser-2.19.tar.gz
Collecting pywin32>=223 (from pypiwin32==223; sys_platform == "win32" and python_version >= "3.6"->docker>=2.5.1->moto)

 

  **Could not find a version that satisfies the requirement pywin32>=223 (from pypiwin32==223; sys_platform == "win32" and python_version >= "3.6"->docker>=2.5.1->moto) (from versions: )
No matching distribution found for pywin32>=223 (from pypiwin32==223; sys_platform == "win32" and python_version >= "3.6"->docker>=2.5.1->moto)**

**Comment by bblommers** [comment]
This is an issue in docker, and there's not much that we can do about it. I believe this would be fixed by this PR: https://github.com/docker/docker-py/pull/2469

Running in a virtualenv might also be a workaround, if that's an option?

**Comment by spulec** [comment]
Going to close then; let me know if there is a reason to keep this open instead.
