### ISSUE TITLE
[Bug] Creating subnet group returns an index error 

### ISSUE THREAD

**Issue by sillyfatcat** [spulec/moto#2689]
```
        vpc_conn = boto3.client("ec2", self.region)
        vpc = vpc_conn.create_vpc(CidrBlock="10.0.0.0/16")["Vpc"]
        subnet = vpc_conn.create_subnet(VpcId=vpc["VpcId"], CidrBlock="10.0.1.0/24")[
            "Subnet"
        ]

        conn = boto3.client("rds", region_name=self.region)
        conn.create_db_subnet_group(
            DBSubnetGroupName="db_subnet1",
            DBSubnetGroupDescription="my db subnet",
            SubnetIds=[subnet["SubnetId"]],
        )
```
This fails with the following traceback

> self = <moto.rds2.models.SubnetGroup object at 0x11e40e550>, subnet_name = 'db_subnet1', description = 'my db subnet', subnets = [], tags = []
> 
>     def __init__(self, subnet_name, description, subnets, tags):
>         self.subnet_name = subnet_name
>         self.description = description
>         self.subnets = subnets
>         self.status = "Complete"
>         self.tags = tags
> >       self.vpc_id = self.subnets[0].vpc_id
> E       IndexError: list index out of range
> 
> ../my-venv/lib/python3.7/site-packages/moto/rds2/models.py:677: IndexError

**Comment by gruebel** [comment]
@bblommers I can't see any problem in the code. there is even a test which exactly covers that scenario
https://github.com/spulec/moto/blob/6b62a9d90fbcca86efe3f3dacc2586281ba109a9/tests/test_rds2/test_rds2.py#L1230-L1258
@sillyfatcat do you have maybe some more details about that code part? Maybe the full example? Do you use the mock decorators?

**Comment by bblommers** [comment]
I could reproduce the behaviour with ```mock_rds```.
The test provided works fine when using ```mock_rds2``` though, so that might have been the problem.

Closing it for now due to inactivity
