### ISSUE TITLE
Typo in README.md file

### ISSUE THREAD

**Issue by screwnet** [spulec/moto#2691]
## Bug report
Category: Typo

1. Could not find any previous reference.
2. Not a programmatic error / bug / exception.
3. The typo exists in 'master' branch of code.
     Section: 
         https://github.com/spulec/moto#what-about-those-pesky-imports
   - Current state:
         sume_func()
     Expected state:
        some_func()
   - This change makes documentation clean.
   - Not Applicable, not a programmatic error / bug / exception.
NOTE: Some spacing (whitespaces) will be fixed during the course.

**Comment by bblommers** [comment]
Welcome to moto, @screwnet! Thanks for your contribution.
I've merged the PR, so closing this.

**Comment by screwnet** [comment]
Thank you!
