### ISSUE TITLE
S3 ListParts output XML - duplicate/incorrect content..

### ISSUE THREAD

**Issue by castaway** [spulec/moto#2695]
I am using localstack (which uses moto for S3) to test the Perl/Paws AWS sdk implementation. Calling S3 ListParts causes issues as the XML parsing fails to match the expected result.

Template here (I think) https://github.com/spulec/moto/blob/master/moto/s3/responses.py#L1858

a) the StorageClass element exists twice - which causes my parser to return an array of 2 STANDARD values (lines 1863 and 1872 in the link above).
b) NextPartNumberMarker comes out with a number and a space, eg: 

```<NextPartNumberMarker>1 </NextPartNumberMarker>``` 

which I can probably fix my end, however the default XML parser returns it as a string, whereas it correctly parses:

```<MaxParts>1</MaxParts>```

as an integer.

**Comment by spulec** [comment]
Fixed with https://github.com/spulec/moto/commit/d73a548bb0b72c8ccbb70e316ae5112f2f9264c5

and

https://github.com/spulec/moto/commit/27ca96519b5517fa51b954972ee95c46f77d8782

Thanks for opening! Let me know if that doesn't work.
