### ISSUE TITLE
Volume Size in Describe Instances when using Cloud Formation

### ISSUE THREAD

**Issue by zbrookle** [spulec/moto#2699]
The volume size being returned in describe instances is not accurate. I created the ec2 using cloud formation, along with an ebs volume that is mounted on it. The volume I created was specified to be 100 mb but the one when using describe volume is of size 8 mb. To be clear this works fine with boto3.client('ec2').create_volume but not cloud formation

**Comment by spulec** [comment]
Thanks; setting this as a feature request to make it work with CF.
