### ISSUE TITLE
mock_s3 raises wrong exception when versioning is enabled for a bucket

### ISSUE THREAD

**Issue by ikonstantynov** [spulec/moto#2710]
Hi there,

I'm testing some method that calls `get_object` method from `boto3.client('s3')`. There is a `VersioningConfiguration` enabled for a bucket that I'm trying to get a file from.
When I try to test a case where there is no such version for a given file, I'm receiving the wrong error code from moto. 

Originally, s3 returns me a response with a response error code = `NoSuchVersion` while moto is always returning `NoSuchKey` error code.

Can this `NoSuchVersion` exception be added?

**Comment by bblommers** [comment]
This should now be fixed as of moto >= 1.3.16.dev200
