### ISSUE TITLE
No default metrics found in cloudwatch for S3 when mocking

### ISSUE THREAD

**Issue by PeterCui1991** [spulec/moto#2711]
I am mocking Cloudwatch and S3 to list metrics for S3. Here is my code:

  ```
  @mock_iam
  @mock_s3_b2
  @mock_sts_b2
  @mock_cloudwatch_b2
  @mock_ec2_b2
  def test_s3_task_process_msg_with_buckets_created(self):

    """

    :return:
    """
    # Create a stream for testing that output can match what we expect
    cw = boto.ec2.cloudwatch.connect_to_region(CLOUD_REGION, aws_access_key_id=access_key,
                                               aws_secret_access_key=secret_key)
    s3 = boto.s3.connect_to_region(CLOUD_REGION, aws_access_key_id=access_key,
                                          aws_secret_access_key=secret_key)

    bucket_name_1 = 'test-bucket-1'
    bucket_name_2 = 'test-bucket-2'

    s3.create_bucket(bucket_name=bucket_name_1)
    s3.create_bucket(bucket_name=bucket_name_2)

    metrics_s3_bucket_1 = cw.list_metrics(dimensions={'BucketName': bucket_name_1})

```
`Output: metrics_s3_bucket_1 = []`

I created cloudwatch and s3 connection, and create two buckets for further tests, but I tried to list metrics for bucket 1 and it returns nothing.

In production, BucketSizeBytes and NumberOfObjects should be setup as default metrics. Am I doing something wrong to mock this process?

**Comment by bblommers** [comment]
The mock looks fine to me, but we don't support OOTB S3 metrics at the moment. 
Flagging this as an enhancement.

**Comment by PeterCui1991** [comment]
@bblommers Thank you so much. That makes sense to me. Looking forward to enhancement and really appreciate you guys' work.

**Comment by bblommers** [comment]
The implementation for this had some bugs, so it was removed again in https://github.com/spulec/moto/pull/2929. Will re-open this issue for now
