### ISSUE TITLE
ElasticSearch not implemented yet?

### ISSUE THREAD

**Issue by PeterCui1991** [spulec/moto#2719]
Just want to make sure if we have plans to implement Elastic Search in the near future?
Or if need help please provide some instructions, I can help develop ElasticSearch and Cloudfront if needed.

**Comment by mrshu** [comment]
Echoing the suggestion from @PeterCui1991 -- I'd also be happy to help with that.

**Comment by bblommers** [comment]
PR's are always welcome for new services. See our https://github.com/spulec/moto/blob/master/CONTRIBUTING.md, specifically the section on `Missing services`, for some examples on how to get started with this.
