### ISSUE TITLE
docs.getmoto.org title has a very old version number

### ISSUE THREAD

**Issue by wlonkly** [spulec/moto#2735]
Hi!

I was Googling for moto docs the other day and noticed that the HTML title of the doc site contains the version number "0.4.10" which is ancient.

I grepped through the repo and couldn't find any reference to it so I have no idea where it's coming from, but it threw me off so I thought I'd point it out.

I _did_ verify that recent commits in `docs/` have found their way to the docs site, so it's at least getting updated, just has the wrong title.

---- 

![image](https://user-images.githubusercontent.com/1545955/74042214-1a64f480-4995-11ea-9f56-f71cc83b8b51.png)

----

![image (38)](https://user-images.githubusercontent.com/1545955/74042161-015c4380-4995-11ea-9cb6-1e6893210780.png)

----

**Comment by spulec** [comment]
Thanks; it looks like we had hardcoded the version. This should be fixed with https://github.com/spulec/moto/commit/f111dd7febca9377056d0860e6b481e7797b446e
