### ISSUE TITLE
created autoscale policy's policy arn doesn't return as expected

### ISSUE THREAD

**Issue by PeterCui1991** [spulec/moto#2744]
```
def setup_autoscale_group():
    mocked_networking = setup_networking_deprecated()
    conn = boto.connect_autoscale()
    config = LaunchConfiguration(
        name="tester", image_id="ami-abcd1234", instance_type="m1.small"
    )
    conn.create_launch_configuration(config)

    group = AutoScalingGroup(
        name="tester_group",
        max_size=2,
        min_size=2,
        launch_config=config,
        vpc_zone_identifier=mocked_networking["subnet1"],
    )
    conn.create_auto_scaling_group(group)
    return group

@mock_autoscaling_deprecated
def test_create_policy():
    setup_autoscale_group()
    conn = boto.connect_autoscale()
    policy = ScalingPolicy(
        name="ScaleUp",
        adjustment_type="ExactCapacity",
        as_name="tester_group",
        scaling_adjustment=3,
        cooldown=60,
    )
    conn.create_scaling_policy(policy)

    policy = conn.get_all_policies()[0]
    print policy.arn
```
The policy arn returned here is not expected, It should return policy arn for "ScaleUp", and autoscale group name should be tester-group.
But arn is like this: arn:aws:autoscaling:us-east-1:803981987763:scalingPolicy:c322
761b-3172-4d56-9a21-0ed9d6161d67:autoScalingGroupName/my-test-asg:policyName/MyScaleDownPolicy

I think this is a bug that when create policy, it won't assign correct policy arn to policy.

**Comment by bblommers** [comment]
Hi @PeterCui1991, I can't reproduce this I'm afraid. I'm getting the ScaleUp-policy, as expected: `ScalingPolicy(ScaleUp group:tester_group adjustment:ExactCapacity)`

Are you creating another policy first, that is also being returned in the `get_all_policies()` call?

**Comment by bblommers** [comment]
Going to close this due to a lack of response, but feel free to let me know if this is still an issue.
