### ISSUE TITLE
AssociatePublicIpAddress = False on primary network interface is ignored

### ISSUE THREAD

**Issue by tekumara** [spulec/moto#2762]
When creating an ec2 instance and a primary network interface with `"AssociatePublicIpAddress": False`, an instance is created with a public IP address.

I am expecting no public IP address to be created.

Example request:

```
kwargs = {
        "ImageId": ami,
        "MaxCount": 1,
        "MinCount": 1,
        "KeyName": "test-key",
        "InstanceType": "t2.medium",
        "EbsOptimized": False,
        "NetworkInterfaces": [
            {
                "DeviceIndex": 0,
                "Description": "Primary network interface",
                "DeleteOnTermination": True,
                "SubnetId": "subnet-317243a9",
                "Ipv6AddressCount": 0,
                "Groups": "default",
                "AssociatePublicIpAddress": False,
            }
        ]
    }
```

I'm using moto 1.3.14

**Comment by tekumara** [comment]
Thanks for the fix @bblommers I've tested it but it still seems like a PublicIpAddress and PublicDnsName are being created when `AssociatePublicIpAddress` = `False`

**Comment by bblommers** [comment]
You're right @tekumara - I just ran the test against AWS, and realized the mistake. My test case worked when providing an instance-level SubnetId, but I didn't realize that the SubnetId has to be provided as part of the NIC. A followup PR will be out soon.
