### ISSUE TITLE
Improvement: Cloudformation responses always have a hardcoded `CreationDate`

### ISSUE THREAD

**Issue by garkenbout-quintor** [spulec/moto#2773]
Whilst using Localstack (which uses this framework) whenever responses are returned through the CLI the creationdate fields are always a fixed value in the past. eg. the LIST_STACKS_RESPONSE (in moto/cloudformation/models.py) contains the `CreationDate` value `2011-05-23T15:47:44Z`.

Expected behaviour;
A proper timestamp is generated and passed to the response (for instance {{ stack.creation_time }} ). 

Note: Localstack has fixed this issue by replacing the response body as seen in [this pull request](https://github.com/localstack/localstack/pull/2103/files) but a fix in the underlying framework would be the best way to go

**Comment by bblommers** [comment]
Welcome to moto, @garkenbout-quintor! Thanks for raising this -  I've marked it as an enhancement. 

Off-topic: Is that Quintor in Groningen? If so, small world! I used to work there from 2011-2013 :)

**Comment by garkenbout-quintor** [comment]
Off-topic; Technically The Hague Quintor, but correct ;) small world indeed!

On-topic; Thanks for marking this, gonna follow the progress ;) (was gonna try and make the improvement, but not being familiar with the codebase makes it a bit more difficult for a quick fix)

**Comment by bblommers** [comment]
There was already a PR for this, but that obviously needs some love: #1310

Could be a good starting point for people who want to pick this up
