### ISSUE TITLE
describe_create_account_status in NOT available in moto 1.3.14

### ISSUE THREAD

**Issue by ywauto83** [spulec/moto#2788]
I can see describe_create_account_status in master https://github.com/spulec/moto/blob/a92f862e861d41b573a864b4057d98fa1cde842d/moto/organizations/models.py#L305

but after  pip install moto==1.3.14, "describe_create_account_status" is NOT available, getting the below error message

```
E       NotImplementedError: The describe_create_account_status action has not been implemented

/Users/yuanwa/.local/share/virtualenvs/aws.fde.onboarding.payload_generator-5peQ2YZG/lib/python3.7/site-packages/moto/core/responses.py:393: NotImplementedErr
```

**Comment by bblommers** [comment]
Hi @ywauto83, that method should work just fine - we even have a test for it: https://github.com/spulec/moto/blob/master/tests/test_organizations/test_organizations_boto3.py#L164

Can you share your full test?

**Comment by gruebel** [comment]
@bblommers the release 1.3.14 was made on the 14.11.19, but the PR #2543 for this functionality was merged one day later, so it didn't made the cut. I think you can close this issue.

**Comment by bblommers** [comment]
Thanks @gruebel 

@ywauto83 More recent releases are available here: https://pypi.org/project/moto/#history
Closing this - please reopen if you're still having an issue with the latest release
