### ISSUE TITLE
Potential bug for s3 OrdinaryCallingFormat in python 3 environment

### ISSUE THREAD

**Issue by PeterCui1991** [spulec/moto#2791]
When I connected to s3 and setup calling_format as OrdinaryCallingFormat in Python 3.7 environment, s3.lookup(bucket_name) cannot return the bucket just created.
But it works in Py2 environment. Is this a bug?
Code is like below:
```
s3 = boto.s3.connect_to_region(self.region, **kwargs)
s3.calling_format = boto.s3.connection.OrdinaryCallingFormat()
bucket = s3.lookup(bucket_name)
```
bucket return None. bucket_name bucket should be expected.

Thanks for help.

**Comment by bblommers** [comment]
Hi @PeterCui1991, all formats should be supported, as far as I know. This might need some debugging.

What kind of bucket name are you using?

**Comment by PeterCui1991** [comment]
Test-bucket-1
I had this issue only in py3 environment. It can run in py2

**Comment by PeterCui1991** [comment]
@bblommers Hi is this issue related to bucket name? but this bucket name works in python 2 environment. What do you think?

**Comment by bblommers** [comment]
@PeterCui1991 Bucket names cannot contain upper case characters (anymore), so I can't create that bucket to even try and reproduce it.
Using a lower case bucket name, the lookup function works fine for me in Python 2 and 3

**Comment by PeterCui1991** [comment]
Yes. I used lower case name. That capital T was because of email auto
convert. The bucket name is like this “test-bucket-1”

It still cannot return expected object.
Environment is like this:
Python 3.7

Boto == 2.49
Boto3 == 1.12.1
Botocore == 1.15.20
Moto == 1.3.14

**Comment by bblommers** [comment]
We've just released Moto 3, where we've dropped support for boto2 altogether, so I'm going to close this.

I realize it's been a while - hopefully you did find a solution for this! Let us know if there's still anything we can do to help.
