### ISSUE TITLE
@mock_secretsmanager fails with "AttributeError: module 'mock' has no attribute 'patch'"

### ISSUE THREAD

**Issue by grandmair40** [spulec/moto#2793]
The test looks like this:
from moto import mock_secretsmanager

@mock_secretsmanager
def test_config():
    print()

This is pretty much empty test at the moment , I just commented out the rest while trying to investigate the problem..
It gives the following trace:

$ pytest
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.7.6, pytest-5.3.5, py-1.8.1, pluggy-0.13.1
rootdir: /mnt/c/work/projects/marketo/marketo-api
collected 2 items / 1 error / 1 selected

================================================================================== ERRORS ==================================================================================
________________________________________________________________ ERROR collecting tests/auth/test_config.py ________________________________________________________________
/home/ec2-user/.local/share/virtualenvs/marketo-api-BbINKz9i/lib/python3.7/site-packages/py/_path/local.py:701: in pyimport
    __import__(modname)
<frozen importlib._bootstrap>:983: in _find_and_load
    ???
<frozen importlib._bootstrap>:967: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:677: in _load_unlocked
    ???
/home/ec2-user/.local/share/virtualenvs/marketo-api-BbINKz9i/lib/python3.7/site-packages/_pytest/assertion/rewrite.py:143: in exec_module
    exec(co, module.__dict__)
/mnt/c/work/projects/marketo/marketo-api/tests/authorizer/test_config.py:3: in <module>
    ???
/home/ec2-user/.local/share/virtualenvs/marketo-api-BbINKz9i/lib/python3.7/site-packages/moto/core/models.py:663: in __call__
    mocked_backend = self.mock_backend(self.backends)
/home/ec2-user/.local/share/virtualenvs/marketo-api-BbINKz9i/lib/python3.7/site-packages/moto/core/models.py:47: in __init__
    self.env_variables_mocks = mock.patch.dict(os.environ, FAKE_KEYS)
E   AttributeError: module 'mock' has no attribute 'patch'

the same test working on the following configuration on the different machine:
$ pytest
=============================================================================================== test session starts ===============================================================================================
platform linux -- Python 3.6.9, pytest-5.3.5, py-1.8.1, pluggy-0.13.1
rootdir: .../projects/marketo-api
collected 1 items                                                                                                                                                                                                
tests/auth/test_config.py . 

The only difference that I can see is different version of python.
pip list returns same versions on both PCs
Could you help with this please?

**Comment by gruebel** [comment]
@grandmair40 there is a high chance that you have a file named `mock.py` in the search path of your Python runtime on the faulty machine. If you use virtualenv for that project, then activate it and start a Python session
```
>>> import mock
>>> mock.__file__
'.../venv/lib/site-packages/mock/__init__.py'
```
the output should be the same on both machines. I hope this helps!

**Comment by bblommers** [comment]
Going to close this due to a lack of response, but feel free to let me know if this is still an issue.
