### ISSUE TITLE
 DynamoDB2: update set incorrectly defaults to string when using attribute

### ISSUE THREAD

**Issue by pvbouwel** [spulec/moto#2806]
This is a bug for moto==1.3.14 .

When using an update expression and setting an attribute `att1` to the value of another attribute `att2` moto will set the attribute to a string equal to the name `att2`.  Whereas AWS DynamoDB will make sure the value is passed on.

Reproduction via tests:
```
import boto3
from moto import mock_dynamodb2

table_name = 'Thread'
forum_name = 'ForumName'
table_definition = {
        "AttributeDefinitions": [
            {
                'AttributeName': forum_name,
                'AttributeType': 'S'
            }
        ],
        "TableName": table_name,
        "KeySchema": [
            {
                'AttributeName': forum_name,
                'KeyType': 'HASH'
            }
        ],
        "BillingMode": 'PAY_PER_REQUEST',
    }
subject1_value = 'my_subject1'
subject2_value = 'my_subject2'
subject1_attr_name = 'subject1'
subject2_attr_name = 'subject2'


def create_load_update_get_delete(deleteTable=False):
    session = boto3.Session(profile_name='default')
    ddb_client = session.client('dynamodb')
    try:
        ddb_client.create_table(**table_definition)
        waiter = ddb_client.get_waiter('table_exists')
        waiter.wait(TableName=table_name)
    except ddb_client.exceptions.ResourceInUseException:
        print("Table exists not creating.")

    ddb_client.put_item(
        TableName=table_name,
        Item={
            forum_name: {'S': 'forum1'},
            subject1_attr_name: {'S': subject1_value},
            subject2_attr_name: {'S': subject2_value}
        }
    )
    ddb_client.update_item(
        TableName=table_name,
        Key={forum_name: {'S': 'forum1'}},
        UpdateExpression=f'SET {subject1_attr_name} = {subject2_attr_name}'
    )
    response = ddb_client.get_item(
        TableName=table_name,
        Key={forum_name: {'S': 'forum1'}}
    )
    items = response.get('Item', {})
    if deleteTable:
        ddb_client.delete_table(TableName=table_name)
    return items


@mock_dynamodb2
def test_mocked():
    # This tests fails since it would actually be equal to subject2_attr_name
    updated_item = create_load_update_get_delete()
    updated_subject1_value = updated_item[subject1_attr_name]['S']
    assert updated_subject1_value == subject2_value


def test_aws():
    # This tests fails since it would actually be equal to subject2_attr_name
    updated_item = create_load_update_get_delete(deleteTable=True)
    updated_subject1_value = updated_item[subject1_attr_name]['S']
    assert updated_subject1_value == subject2_value
```

**Comment by bblommers** [comment]
Hi @pvbouwel, I'm going to mark this as an enhancement, as it's a feature that we haven't implemented yet.
Do you have a link to official AWS docs about this feature? I've never seen this syntax before - you learn something new every day :)

**Comment by pvbouwel** [comment]
It seems to be part of the UpdateExpression.  

It seems the right-hand side of a SET assignment can just be an expression so my example is like a simple version of it.
In the docs https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_UpdateItem.html#DDB-UpdateItem-request-UpdateExpression I do see they use  `SET myNum = myNum + :val` which shows that righthand side should be able to cope with attribute names.

Probably the best doc is https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.UpdateExpressions.html 
According to that doc the possibilities are limited.  I'll look at giving a stab it myself as much as time permits.

**Comment by pvbouwel** [comment]
It seems that the mock is too forgiving at the moment for SET update expressions in general.  I believe an appropriate fix would need to correct that as well.

For example:
 AttributeExpressionValue passed in that is not used => Exception is thrown
 String in expression that is not an AttributeExpressionValue  => Exception is thrown
 number literal in expression that is not part of attributeName => Exception is thrown

Exception depends on what happens.

The reason why I believe this (or at least part of this) is necessary is because DynamoDB is quite forgiving for attribute names. A plus-sign and a . are allowed in attribute names. Due to this one needs strict rules in what can be in an UpdateExpression. (It's not just splitting in the expression in tokens it seems as 'My+Val' can be the attribute name 'My+Val' or attribute 'My' operator '+' and attribute name 'Val'.   (So that is something that I learned today ;) )

These type of changes would however mean that tests passing an older version could suddenly start failing.  This is imho not a problem but rather a good thing as it would mean that there is in fact a bug in the code under test and therefore the current code can give a false sense of safety.
