### ISSUE TITLE
implementation of ec2 vpc endpoint - are there plans?

### ISSUE THREAD

**Issue by 111andre111** [spulec/moto#2826]
Are there any plans to implement vpc endpoint creation at some time?
Regarding this document 
https://github.com/spulec/moto/blob/master/IMPLEMENTATION_COVERAGE.md#ec2
and looking in the source code under @ mock-ec2 decorator I cannot see any equivalent up to now.
It would be nice to to have that feature.

Thank you

**Comment by johnwc** [comment]
I've actually did this, as we needed testing for endpoints as well. I'm hoping to get the addition submitted within the next week.

**Comment by bblommers** [comment]
Already in place @johnwc :)

**Comment by 111andre111** [comment]
Perfect, thank you indeed.
