### ISSUE TITLE
Set batch job FAILED status from container exit status

### ISSUE THREAD

**Issue by dazza-codes** [spulec/moto#2829]
RE https://github.com/spulec/moto/blob/master/moto/batch/models.py#L499

When the container runs a command with a non-zero exit status, the batch job status should be FAILED.

e.g. the following command should result in a FAILED job status:
```
command = ['/bin/sh', '-c', 'echo Fail && exit 1']
```
These failures usually have a `statusReason` like:
- "Essential container in task exited" - container error

```
$ docker run alpine /bin/sh -c "echo Fail && exit 1"
Fail
$ echo $?
1
```
Compared with a successful exit status:
```
$ docker run alpine /bin/sh -c "echo Hello"
Hello
$ echo $?
0
```

Also note this is different from a docker CMD failure like
```
$ docker run alpine /bin/bash -c "echo Hello"
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory": unknown.
ERRO[0000] error waiting for container: context canceled 
```

### versions
```
aiobotocore==0.12.0
boto==2.49.0
boto3==1.12.3
botocore==1.15.3
moto==1.3.14
```

**Comment by dazza-codes** [comment]
It appears that it's impossible to confirm that the `container` actually contains a command override because the job-description does not return the actual command, it returns a fixed string at
- https://github.com/spulec/moto/blob/master/moto/batch/models.py#L350-L351

**Comment by dazza-codes** [comment]
The `job_description` is missing a `createdAt` value (this is most likely set when the job is first submitted).

**Comment by bblommers** [comment]
Setting the status to FAILED was implemented as part of #3956, and is part of moto >= 2.0.9.dev3

Will leave this open to also implement the missing attributes

**Comment by orenmazor** [comment]
I just came across this ticket. one thing I'd love to add is the attempts tracking. I'm not sure if this exists yet, but none of my jobs (failed or otherwise) collect attempts information

**Comment by dazza-codes** [comment]
Some additional attributes might be addressed by https://github.com/spulec/moto/issues/4364

**Comment by bblommers** [comment]
The attached PR just added support for `attempts`-parameter in the JobDescription API.
As far as I can tell, that covers everything raised in this issue. Let us know if there are any other issues/missing parameters that you'd like to see support for!
