### ISSUE TITLE
Add Cloudformation support for Events

### ISSUE THREAD

**Issue by gmcrocetti** [spulec/moto#2831]
During a serverless deploy (cloudformation) with a schedule (Events::Rule) the following log was raised: `No Moto CloudFormation support for AWS::Events::Rule`

It's an easy problem to reproduce: use cloudformation to create an Event Rule.
I'm using the latest version of moto (from `moto-ext`).

**Comment by gmcrocetti** [comment]
Hello @bblommers , thanks for your fast reply. I was working in a solution and it looks like our `Rule` model requires a `Name` property. The [docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-rule.html) doesn't require one as it can be automatically generated. If that's all true, are you okay with a single PR containing those two features (we still need to open a new issue) ?

**Comment by bblommers** [comment]
PR's are always welcome, @gmcrocetti! An implementation with some features missing is better than no implementation :)

**Comment by bblommers** [comment]
Closed with #2833

**Comment by gmcrocetti** [comment]
Hi @bblommers. I was trying this new feature today (after moto-ext release) and looks like the implementation in #2833 is missing a feature:

<img width="941" alt="image" src="https://user-images.githubusercontent.com/24530683/77978045-72eea900-72d7-11ea-9195-3ea0d7674181.png">

I'm able to solve this new problem but right now I'm not very confident if we need something else. Are we missing something else besides `get_cfn_attribute` ?

**Comment by bblommers** [comment]
Hi @gmcrocetti - your example works for me, but I guess there's another CF resource that tries to get the ARN of ```ScheduleSendEmailEventsRuleSchedule1```.
Implementing ```get_cfn_attribute``` on the Rule-object definitely fixes that - looks like the ARN is the only attribute that has to be implemented ([according to the docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-rule.html))

As far as I can see, the only other property that's missing from  the implementation is ```physical_resource_id```. It's a non-mandatory property, but good practice to implement anyway. We can just use the name of the Rule, similar to how this is implemented in [AWS Lambda](https://github.com/spulec/moto/blob/master/moto/awslambda/models.py#L256).

**Comment by bblommers** [comment]
Smallest test that that I can reproduce this with:
```
@mock_cloudformation
@mock_events
@mock_ec2
def test_stack_events_create_rule_with_target():
    events_template = {
        "AWSTemplateFormatVersion": "2010-09-09",
        "Resources": {
            "my-security-group": {
                "Type": "AWS::EC2::SecurityGroup",
                "Properties": {"GroupDescription": {"Fn::GetAtt": ["Event", "Arn"]}},
            },
            "Event": {
                "Type": "AWS::Events::Rule",
                "Properties": {
                    "State": "ENABLED",
                    "ScheduleExpression": "rate(5 minutes)",
                },
            }
        },
    }
    cf_conn = boto3.client("cloudformation", "us-west-2")
    cf_conn.create_stack(
        StackName="test_stack", TemplateBody=json.dumps(events_template),
    )

    rules = boto3.client("events", "us-west-2").list_rules()
    rules["Rules"][0]["Name"].should.contain("test_stack-Event-")
    #
    # TODO: Assert that the SecurityGroup has the correct description
```
