### ISSUE TITLE
Dependency conflict in Python 3.5 with mock package

### ISSUE THREAD

**Issue by mplewis** [spulec/moto#2842]
Hi! I'm using `pip-compile` via [pip tools](https://pypi.org/project/pip-tools/) to install deps in my project. This ensures all my deps are compatible, which pip on its own does not do.

When I use pip-compile to resolve my dependencies in Python 3.5, and my `requirements.in` includes `moto`, I get the following error:

```
pip-compile test/requirements-test.in

CRITICAL:pip._internal.index:Could not find a version that satisfies the requirement mock==4.0.2 (from moto==1.3.14->-r test/requirements-test.in (line 25)) (from versions: 0.5.0, 0.6.0, 0.7.0b1, 0.7.0b2, 0.7.0b3, 0.7.0b4, 0.7.0rc1, 0.7.0, 0.7.1, 0.7.2, 0.8.0, 1.0b1, 1.0.0, 1.0.1, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.2.0, 1.3.0, 2.0.0, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5)
```

This is because [mock](https://pypi.org/project/mock/) is a backport of `unittest.mock`, but it only exists in Python 3.6 and not 3.5. Meanwhile, `unittest.mock` is present in Python 3.3 and onwards.

Would it be possible to move moto to using `unittest.mock`? This would mean we can remove the dependency on pypi `mock`, which would allow moto to pip-compile on Python 3.5.

Happy to make this PR and make the necessary changes. Let me know.

**Comment by bblommers** [comment]
Hi @mplewis, is this still the case with the latest dev-release (1.3.15.dev559)? 

[This](https://github.com/spulec/moto/pull/2776) (and [this](https://github.com/spulec/moto/pull/2794)) recent PR's should ensure that the mock-version we use still supports Python 3.5

**Comment by mplewis** [comment]
I didn't realize mock was compatible with 3.6 in the v3 – I think this solves my issue. Thanks for the help!
