### ISSUE TITLE
Route53 ChangeResourceRecordSets should only handle 100 ResourceRecords at the time

### ISSUE THREAD

**Issue by jstangroome** [spulec/moto#2843]
Would it be reasonable for Moto to implement the same limitations imposed by the actual AWS API?

For example, Route53 ChangeResourceRecordSets Requests [cannot contain more than 1,000 ResourceRecord elements](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/DNSLimitations.html#limits-api-requests-changeresourcerecordsets).

Enforcing this in Moto would help find issues early in applications where logic needs to be added to divide changes into smaller batches, instead of learning the hard way late in the deployment cycle.

Or is this outside the intended scope of moto?

**Comment by bblommers** [comment]
Limitations like that are definitely in scope! Will mark this as an enhancement for people to pick up.
