### ISSUE TITLE
Support for S3FileSystem

### ISSUE THREAD

**Issue by TanguyCazalets** [spulec/moto#2844]
Hi,
Python 3.6.9
Moto 1.3.5 installed with pip

I have this issue where I want to use S3FileSystem to access files uploaded to a mocked s3 bucket. like follow : 
```python
def fill_mocked_s3_buckets(cls, bucket):
     client = boto3.client("s3")

     test_files = {foo_data, bar_data}
     for file in test_files:
         with open(file, "rb") as f:
             data_type = file
             key = f"s3://raw.data/analysis/{data_type].parquet"
             client.upload_file(Key=key, Bucket=bucket, Filename=file.as_posix())

     cls.print_uploaded_files_with_client(bucket) # this work fine

     cls.print_uploaded_files_with_filesystem(bucket) # this does not work 
```
This show that files where indeed uploaded
```python
 def print_uploaded_files(cls, bucket):
     client = boto3.client("s3")
     paginator = client.get_paginator("list_objects_v2")
     for page in paginator.paginate(Bucket=bucket):
         print(page["Contents"])
```
This return ('raw-data/analysis/', [], [])
```python
 def print_uploaded_files_with_filesystem(cls, bucket):
     file = f"s3://{bucket}/analysis/"
     s3 = s3fs.S3FileSystem()
     for path in s3.walk(file):
         print(path)
```
Finally when I try to access file with  with `s3.open(file, "rb") as utc_file:` I get a FileNotFoundError.

For test reason I want to make the S3FileSystem work.

Does Moto include support for S3FileSystem ? From this issue https://github.com/spulec/moto/issues/1596 I though it was the case, but I can't make it work

**Comment by bblommers** [comment]
Hi @TanguyCazalets, are you able to reproduce this with the newest version of moto (1.3.15.dev561)?

**Comment by TanguyCazalets** [comment]
HI I reproduced the error with moto 1.3.14. 
Hwever with moto 1.3.15.dev561 I get a new error : 
`E           botocore.exceptions.ClientError: An error occurred (IllegalLocationConstraintException) when calling the CreateBucket operation: The unspecified location constraint is incompatible for the region specific endpoint this request was sent to.`

**Comment by bblommers** [comment]
Hi @TanguyCazalets - I think there's an issue with the way you're uploading the file:
```
key = f"s3://raw.data/analysis/{data_type].parquet"
client.upload_file(Key=key, Bucket=bucket, Filename=file.as_posix())
```
The key typically doesn't have the ```s3:``` part.
When I do this in AWS itself, it creates the following file structure:
```s3://raw.data/s3://raw.data/analysis/..```

So boto3 itself doesn't recognize a key name in this format, but instead creates a separate folder inside ```raw_data``` called ```s3:```

When I upload file with the key ```analysis/x.parquet``` I can walk the bucket using S3FS.

**Comment by TanguyCazalets** [comment]
INDEED !
Thank you so much for you help, it's working perfectly now !

**Comment by bblommers** [comment]
Glad I could help!

**Comment by parthgala** [comment]
@spulec Does `moto` library support mocking out AWS calls via `s3fs` (which uses `aiobotocore`)?

**Comment by bblommers** [comment]
It should, @parthgala. Moto will mock every call to the boto/boto3 library, even if it's used indirectly.

**Comment by thiagodma** [comment]
Hi @bblommers ! I'm having trouble with moto and s3fs. The following snippet, when ran by pytest is giving an assertion error. If I check the file existence using boto3 it works but I have to make it work with s3fs. Any ideas on how to solve that?

```
# requirements
boto3==1.28.53
s3fs==2023.9.2
moto==4.2.7 
```

Here's my code:

```
import os
import s3fs
import boto3
import pytest
from moto import mock_s3

@pytest.fixture(scope="function")
def aws_credentials():
    """Mocked AWS Credentials for moto."""
    os.environ["AWS_ACCESS_KEY_ID"] = "testing"
    os.environ["AWS_SECRET_ACCESS_KEY"] = "testing"
    os.environ["AWS_SECURITY_TOKEN"] = "testing"
    os.environ["AWS_SESSION_TOKEN"] = "testing"
    os.environ["AWS_DEFAULT_REGION"] = "us-east-1"


@pytest.fixture(scope="function")
def s3(aws_credentials):
    with mock_s3():
        yield boto3.client("s3", region_name="us-east-1")


@mock_s3
def test_storage_handler_s3_file(s3):

    s3.create_bucket(Bucket="test-bucket")
    s3.put_object(Bucket="test-bucket", Key="test.json", Body='{"key": "value"}')

    s3fs_instance = s3fs.S3FileSystem()

    assert s3fs_instance.isfile("s3://test-bucket/test.json")
```

**Comment by bblommers** [comment]
@thiagodma Small correction on my comment from before: 

> Moto will mock every call to the boto/boto3 library `as long as there is no multithreading going on, because that is not supported by Moto`

`aiobotocore` does use multithreading, which makes it incompatible with the Moto decorators.

You could use the MotoServer instead. See for example how the `s3fs` tests are written:

https://github.com/fsspec/s3fs/blob/2c074502c2d6a9be0d3f05eb678f4cc5add2e7e5/s3fs/tests/test_s3fs.py#L76

**Comment by thiagodma** [comment]
@bblommers thanks! The link you provided was quite helpful!
