### ISSUE TITLE
Cloud formation "depends_on" 

### ISSUE THREAD

**Issue by zbrookle** [spulec/moto#2845]
When your cloud formation parser is lazily iterating through the provided resources, I don't think it's taking the depends_on variable into account, which is causing resources to be created in the wrong order, and ends up failing a cloud formation script. The example that I came up with was creating an autoscaling group before the launch configuration was created, even though the autoscaling group has a depends on flag for the launch configuration

**Comment by zbrookle** [comment]
@bblommers I actually wouldn't mind working on this because it's something pretty critical to my team's unit testing. Do you have any contribution guidelines? I didn't see any in the README

**Comment by spulec** [comment]
Your contribution would be great!

Nothing too specific beyond this: https://github.com/spulec/moto/blob/master/CONTRIBUTING.md

**Comment by zbrookle** [comment]
Ok great thanks! I’ll try to do this tomorrow then

**Comment by zbrookle** [comment]
@spulec I just submitted a pull request that should add this feature #2994
