### ISSUE TITLE
more-itertools version pin is very old

### ISSUE THREAD

**Issue by mpenkov** [spulec/moto#2865]
In your setup.py you're pinning the package to version 5.0.0, but they're already on version 8.2.0.

https://github.com/spulec/moto/blob/5ac9bb1885ebc4a7ac6573645e478d914c3e657a/setup.py#L54

It looks like you're doing this just for Python 2.7 support. Is that really necessary?

The pin is causing problems for me because it results in a version conflict with other packages that require a more up-to-date itertools.

**Comment by bblommers** [comment]
Thanks for raising this @mpenkov.
I'm going to close this in favour of #2836, where we're talking about supporting Python2 (dependencies) in a wider context. Feel free to join the conversation there
