### ISSUE TITLE
athena boto3 client not supported?

### ISSUE THREAD

**Issue by wierzba3** [spulec/moto#2872]
When I try to use moto to implement a unit test for a function that uses `boto3.client("athena")`, the code crashes with an error `NotImplementedError: The start_query_execution action has not been implemented`

Does this imply that this is not supported in moto? Or am I supposed to override / mock something?

**Comment by bblommers** [comment]
Hi @wierzba3, welcome to Moto!
That particular method (and most methods in Athena..) is not yet supported in moto. See this feature request: #1524 

PRs are always welcome, if you feel like contributing!

Will close this for now as a duplicate.
