### ISSUE TITLE
Question: Is there any way to save moto server state?

### ISSUE THREAD

**Issue by dtsvirkun** [spulec/moto#2882]
Hello, is there any way to save current moto server state?
For example, I created a lots of different resources (s3 buckets, etc) and everything is gone after stadalone (or docker container) server restart.

**Comment by bblommers** [comment]
Hi @dtsvirkun, not at the moment. Will mark this as an enhancement, as it would be a useful feature!

**Comment by spulec** [comment]
In case anyone wants to work on this, all of the resources are referenced from a relatively centralized place: https://github.com/spulec/moto/blob/master/moto/core/models.py#L510-L523

Given that, I don't think it would be too much work to try to pickle or json.dump them somewhere.

**Comment by lllama** [comment]
This is a very interesting idea. If anyone else is looking at this issue, then I think the lines of code to look at are now these:

https://github.com/spulec/moto/blob/master/moto/core/models.py#L555-L576

Looks like saving `model_data` is the key.

**Comment by mnesarco** [comment]
Hi @spulec , @lllama 
I am interested in some experiments for import/export the state. But the file you are referencing here : 

- https://github.com/spulec/moto/blob/master/moto/core/models.py#L510-L523
- https://github.com/spulec/moto/blob/master/moto/core/models.py#L555-L576


 has changed and it has only 405 lines now. So the point in code suggested by you to look at is not there anymore (lines between 510 and 576) Could you suggest the new place to get/inject the imported state?

Thanks a lot.

**Comment by mnesarco** [comment]
Please correct me if I am wrong.
Maybe I can do just this to export all the state:

```python
from moto.core.base_backend import model_data
import json
save_state_somewhere( json.dumps(model_data) )
```

**Comment by bblommers** [comment]
Moto 4.0.6 (just released) has the option to record requests, and replay them on another system/at another time, to ensure that the initial set of resources is the same.
It is also possible to seed Moto now, which means that the identifiers are deterministic given a specific seed.

See the documentation for this here:
http://docs.getmoto.org/en/latest/docs/configuration/recorder/index.html

I'll close this, but do let us know if there's any questions or feedback on this feature.
