### ISSUE TITLE
Feature - S3 - Validate Bucket policy

### ISSUE THREAD

**Issue by kalekseev** [spulec/moto#2892]
Start server `moto_server s3 -p9000` the script bellow must success, but it fails with 403 (Forbidden). The policy works in aws and minio.

```
import json

import boto3
import urllib3

client = boto3.client(
    "s3", region_name="ap-southest-2", endpoint_url=f"http://localhost:9000",
)
client.create_bucket(Bucket="mybucket")
policy = {
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": "*",
            "Action": ["s3:GetObject"],
            "Resource": f"arn:aws:s3:::mybucket/*",
        }
    ],
}

client.put_bucket_policy(Bucket="mybucket", Policy=json.dumps(policy))

client.put_object(Bucket="mybucket", Key="test.txt", Body=b"mybytes")
http = urllib3.PoolManager()
r = http.request("GET", "http://localhost:9000/mybucket/a.txt")
assert r.status == 404
r = http.request("GET", "http://localhost:9000/mybucket/test.txt")
assert r.status == 200
```

**Comment by bblommers** [comment]
Hi @kalekseev, thanks for raising this.
When using decorators it works as it should, but in server-mode it does throw an 403. Curious.

Will mark this as a bug.

**Comment by bblommers** [comment]
Did some more investigation - it looks like we're not validation bucket policies at all. Will mark that as an enhancement instead.

We do validate the object ACL: 
https://github.com/spulec/moto/blob/master/moto/s3/responses.py#L1023
So we'll have to validate the bucket policy before that

**Comment by kalekseev** [comment]
@bblommers thanks for info, would be good to have that mentioned in the readme.
