### ISSUE TITLE
Support for secretsmanager update_secret

### ISSUE THREAD

**Issue by caphrim007** [spulec/moto#2895]
I would like to explore the possibility of adding update_secret support to the secretsmanager endpoint and am filing this issue per the contributor guidelines.

As of moto 1.3.14 support for update_secret is not yet implemented. The following is raised when the secretsmanager client is used in my personal code

```
E.   NotImplementedError: The update_secret action has not been implemented
.tox/unit/lib/python3.7/site-packages/moto/core/responses.py:393: NotImplementedError
```

I would like to take a stab at adding this so that I can use moto to test in-house code that calls this method.

I'm new to the moto process though, so want to have a maintainer +1 this work before I put any serious effort into it. Preliminary toying with a fix seems relatively straightforward.

**Comment by bblommers** [comment]
Hi @caphrim007, that's a very useful feature! 

Let me know if you need any help.
