### ISSUE TITLE
Not able to connect to moto standalone server when run in docker

### ISSUE THREAD

**Issue by malathit** [spulec/moto#2912]
### Steps to reproduce the issue

Running moto server in docker

`docker run -it --rm michaelerasmus/docker-moto-server ec2`

Running curl from the host machine

`curl localost:5000/?Action=DescribeInstances`

### Description
All the online examples of running moto_server in docker runs the container in 'host' mode. However in my case I use the default 'bridge' network in docker. When I run the above curl from my laptop(outside the docker-moto-server) container, it gives 'Empty response' from server.

However when I run the cURL inside the container, it works
`curl localhost:5000/?Action=DescribeInstances`

```
<?xml version="1.0" encoding="UTF-8"?>
<ListAllMyBucketsResult xmlns="http://s3.amazonaws.com/doc/2006-03-01">
   <Owner>
      <ID>bcaf1ffd86f41161ca5fb16fd081034f</ID>
      <DisplayName>webfile</DisplayName>
   </Owner>
   <Buckets />
</ListAllMyBucketsResult>
```

Can somebody please help me figure out how can I access the moto server outside the docker container?

**Comment by malathi-thangarajan** [comment]
The issue was that the moto standalone server was listening in 127.0.0.1. When I run the docker comtainer like this to make the server listen at 0.0.0.0,

`docker run -it --rm -p5000:5000 michaelerasmus/docker-moto-server ec2 -H 0.0.0.0`

it worked.

**Comment by malathit** [comment]
The issue was that the moto standalone server was listening in 127.0.0.1. When I run the docker comtainer like this to make the server listen at 0.0.0.0,

`docker run -it --rm -p5000:5000 michaelerasmus/docker-moto-server ec2 -H 0.0.0.0`

it worked. This issue can be closed

**Comment by bblommers** [comment]
Thanks for following up with the fix @malathit!
