### ISSUE TITLE
NoSuchBucket error when endpoint-url contain dots

### ISSUE THREAD

**Issue by tomers** [spulec/moto#2915]
When endpoint-url parameter contain dots, e.g. `moto.microservice`, I get `NoSuchBucket` whenever I try to call any S3 operation.

```
# IP of moto.microservice is 202.0.0.5
some-docker:~$ ~/.local/bin/aws s3 --endpoint-url=http://202.0.0.5:5000 ls
2006-02-03 16:45:09 my-bucket
some-docker:~$ ~/.local/bin/aws s3 --endpoint-url=http://moto.microservice:5000 ls
An error occurred (NoSuchBucket) when calling the ListBuckets operation: The specified bucket does not exist
```
In the response, I notice that BucketName is set to `moto`, which is the first subdomain.

I found that the issue is caused by the following line:
https://github.com/spulec/moto/blob/master/moto/s3/utils.py#L31

**Comment by tomers** [comment]
I noticed `S3_IGNORE_SUBDOMAIN_BUCKETNAME` is a reasonable solution for this issue.

**Comment by bblommers** [comment]
Yup, closing this @tomers. I'm not sure there is a fix for this. When passing in an S3 bucket as a subdomain, there's no way for the server to know where the subdomain stops and the server-name starts.
```S3_IGNORE_SUBDOMAIN_BUCKETNAME``` is a reasonable solution - or not using any dots in the url :)
