### ISSUE TITLE
Odd behavior when running multiple test files.

### ISSUE THREAD

**Issue by johnwc** [spulec/moto#2923]
I'm finding that all my tests within a single test_ file runs successfully when run with pytest pointing at the single file. But, if I run pytest with no arguments, so that it runs all my tests in all test_ files, they all fail. I'm sure I've done something incorrect in my setup, just unsure what.

My structure is that I create mock class in the global scope, then start and stop them within pytest's start and teardown functions. At the moment, I need to monkeypatch a few functions to some of the classes in moto to add/extend missing functionality, like VPC Endpoints create/modify/describe. So I need to inject those new functions into the classes before moto initiates them within moto_*().start(). Otherwise they don't seem to be available to moto if I attempt to patch them after the call to start().

```python
from moto import mock_s3
import boto3
import pytest
from moto.ec2.responses import VPCs

MOCK_S3 = mock_s3()

def setup_function(function):
    # Patch before we start
    VPCs.create_vpc_endpoint = clnt_create_vpc_endpoint
    VPCs.describe_vpc_endpoints = clnt_describe_vpc_endpoints
    VPCs.modify_vpc_endpoint = clnt_modify_vpc_endpoint

    MOCK_S3.start()

def teardown_function(function):
    MOCK_S3.stop()

def test_one():
    <run boto calls>

def test_two():
    <run boto calls>
```

These all run fine at once, when just this test file is ran, but not when a set of files are ran.

**Comment by spulec** [comment]
When you say it doesn't work, can you clarify what that means? Is it that the modified VPC functions aren't there when running multiple files?

My first guess is that the VPC response has already been instantiated by the time it is getting to this file so the patching of the class happening here is too late.

**Comment by johnwc** [comment]
The mocks are not in place, I get aws access key errors.

**Comment by spulec** [comment]
Two thoughts:

- Instead of having `MOCK_S3` be at the module-level, can you instantiate it in the setup and attach it to `function` for use in `teardown_function`?
- The [docs](https://docs.pytest.org/en/latest/xunit_setup.html) say: `It is possible for setup/teardown pairs to be invoked multiple times per testing process.` I am wondering if that might be part of the issue. Can you add some prints/pdbs to confirm if the setup/teardown are being called the appropriate number of times?

**Comment by johnwc** [comment]
Sorry, this was actualy coming from another test file that another developer introduced. He put the boto3.client calls in the global scope of the file, instead of within the functions. This caused the boto module classes to be imported prior to the mock_*() calls in my test files, which kept moto from doing it's magic first.

Maybe there needs to be a check done in the sys.modules space within the mock_*() calls. If it finds that the boto modules that are to be mocked, it throws an error or warning.

```Python
import sys
if 'boto3' in sys.modules:
    raise Exception('boto3 was already imported, boto imports need to be done after calls to mock_ec2()')
```
