### ISSUE TITLE
ApiGateway UsagePlan api does not honour API Gateway behaviour with non existing api keys and usage plans

### ISSUE THREAD

**Issue by apalumbo** [spulec/moto#2928]
Instead of handling the request returning a 404 Not found error, the current version hangs with an unexpected error due to the access of non-existing keys in a python lists.
This breaks get_usage_plan and get_usage_plan_key on api gateway model

I created a PR to fix this issue #2927

**Comment by spulec** [comment]
Fixed with https://github.com/spulec/moto/pull/2927
