### ISSUE TITLE
placementConstraint is not stored in task definition

### ISSUE THREAD

**Issue by rifqifatih** [spulec/moto#2943]
Hi,
I'm trying to get the `placementConstraints` set on ecs `register_task_definition`. I assume this is not yet implemented because when I do `describe_task_definition`, it didn't return the `placementConstraints` that I described before.

I'm not sure if this will complicate the mocking behavior, but returning the assigned value should be ok, I guess.

Reproduce:
```
ecs_client.register_task_definition(family='family',
                                            containerDefinitions=[{'image': 'image',
                                                                   'name': 'name'}],
                                            placementConstraints=[{
                                                "type": "memberOf",
                                                "expression": "something"
                                            }])

taskdef = ecs_client.describe_task_definition(taskDefinition='family:1')
taskdef.get("placementConstraints")
```
Moto version: 1.3.14

**Comment by spulec** [comment]
Closed with https://github.com/spulec/moto/pull/2948
