### ISSUE TITLE
Unable to hit the api gateway implemented with moto.

### ISSUE THREAD

**Issue by usmankb** [spulec/moto#2951]
Hey ,I have been trying to write some tests for api gateway proxy service integrations like invoking dynamodb through api gateway.
I am not able to invoke the api gateway method implemented after adding all the integrations required.

Adding the test case snippet here.

```
@mock_apigateway
@mock_dynamodb_deprecated
def test_put_integration_proxy_validation():
    client = boto3.client("apigateway", region_name="us-west-2")
    response = client.create_rest_api(name="my_api", description="this is my api")
    api_id = response["id"]
    resources = client.get_resources(restApiId=api_id)
    root_id = [resource for resource in resources["items"] if resource["path"] == "/"][
        0
    ]["id"]

    client.put_method(
        restApiId=api_id, resourceId=root_id, httpMethod="PUT", authorizationType="NONE"
    )

    client.put_method_response(
        restApiId=api_id, resourceId=root_id, httpMethod="PUT", statusCode="200",
    )

    dynamodb_backend.create_table("test_1", hash_key_attr="name", hash_key_type="S")

    # Ensure that it works fine when providing the integrationHttpMethod-argument
    result = client.put_integration(
        restApiId=api_id,
        resourceId=root_id,
        httpMethod="PUT",
        type="AWS_PROXY",
        uri="arn:aws:apigateway:us-east-1:dynamodb:action/PutItem&Table=MusicCollection",
        integrationHttpMethod="PUT",
    )

    print(result)

    client.put_integration_response(
        restApiId=api_id,
        resourceId=root_id,
        httpMethod="PUT",
        statusCode="200",
        selectionPattern="",
        responseTemplates={"application/json": "{\"TableName\": \"test_1\"},{\"Item\": {\"name\":{\"S\": \"$context.name\"}}}"})

    client.create_deployment(restApiId=api_id, stageName="staging")

    data = requests.put(
        "https://{}.execute-api.us-east-1.amazonaws.com/staging".format(api_id),
        {"name": "the-key"},
    )

```

this returns me a 400 with content as b'The method is not implemented'

@spulec 
@bblommers 

Is there any way to get this done ?Please help me through this.I am 
@usmangani1

**Comment by spulec** [comment]
That code passes for me when running against the master branch. Can you run again the latest prerelease and confirm this isn't working? https://pypi.org/project/moto/1.3.15.dev806/

**Comment by usmankb** [comment]
> That code passes for me when running against the master branch. Can you run again the latest prerelease and confirm this isn't working? https://pypi.org/project/moto/1.3.15.dev806/

@spulec  I just pulled the master code and tried again.The same response is coming.What do you mean by passes? it runs fine though ,the only problem is the response.
I am receiving 404 url not found But I am expecting the aws proxy service to get hit once I hit this method(url).

**Comment by spulec** [comment]
Ah, sorry I misunderstood.

It looks like we currently only implement calls that are GETs: https://github.com/spulec/moto/blob/master/moto/apigateway/models.py#L555-L561

I will set this as a feature request to add more.
