### ISSUE TITLE
Feature: Logs: put_subscription_filter

### ISSUE THREAD

**Issue by benkeil** [spulec/moto#2955]
moto version: v1.3.14

I try to deploy a lambda with log group and permissions and a dynamoDb table to moto with terraform.

I get 2 errors:

`NotImplementedError: The put_subscription_filter action has not been implemented`
and
`AttributeError: 'DynamoHandler' object has no attribute 'describe_continuous_backups'`

Additional it looks like I can't create a global secondary index.

**Comment by bblommers** [comment]
DynamoDB:describe_continuous_backups is now part of moto >= 1.3.15.dev840

**Comment by bblommers** [comment]
Logs:put_subscription_filter is part of moto >= 1.3.15.dev844
