### ISSUE TITLE
SES verify_domain_identity incompatible with send_raw_email

### ISSUE THREAD

**Issue by staylor-ds** [spulec/moto#2959]
https://github.com/spulec/moto/blob/323877c15de6efaaa098efd282b65729fa78d3eb/moto/ses/models.py#L203

Should follow the following logic:
https://github.com/spulec/moto/blob/323877c15de6efaaa098efd282b65729fa78d3eb/moto/ses/models.py#L147

**Comment by bblommers** [comment]
Thanks for raising this @staylor-ds - this should now be fixed in moto >= 1.3.15.dev859
