### ISSUE TITLE
missing ContentLength in s3.Object.get() response when requesting partial content

### ISSUE THREAD

**Issue by gerazenobi** [spulec/moto#2964]
**Steps to reproduce:**
```python
from moto import mock_s3
import boto3

file_path = "..."
with mock_s3():
    bucket = "test"
    object_key = "key"
    s3 = boto3.resource("s3")
    s3.create_bucket(Bucket=bucket)
    with open(file_path, "rb") as file:
        s3.Object(bucket, object_key).put(Body=file)

    file = s3.Object(bucket, object_key)
    response = file.get(Range="bytes=0-1024")
    print(response["ContentLength"])
```
**Expected behavior:**
```bash
1025
```

**Actual behavior:**
```bash
KeyError: 'ContentLength'
```

**Additional information:**
This only happens when requesting partial content. Possibly other important response's headers are ignored as well since the `headers` argument is not being used within `_handle_range_header`, as seen [here](https://github.com/spulec/moto/blob/master/moto/s3/responses.py#L877).

**Versions**
- moto                    1.3.14
- boto                     2.49.0
- boto3                   1.13.3
- botocore              1.16.3

**Comment by RonRothman** [comment]
Greetings,

We're hitting this too, and it's breaking our tests. I see this has been open since May, and is labelled an "Enhancement." Is that just an oversight? Can we bump this up to "Bug?"

**Comment by bblommers** [comment]
Hi @RonRothman, my definition of a bug (in Moto's context) is anything that behaves differently from boto3.
In this case, the entire implementation is missing - and therefore the enhancement-label is more suitable IMO.

**Comment by RonRothman** [comment]
Thanks @bblommers, that makes sense. And I see that a fix is on the way--thanks for that as well!

**Comment by bblommers** [comment]
No problem @RonRothman!

This is now partof moto >= 1.3.16.dev79
