### ISSUE TITLE
Redshift restore_from_cluster_snapshot should fail if cluster already exist

### ISSUE THREAD

**Issue by kennedy** [spulec/moto#2967]
moto: `1.3.14` via pip running non-server
boto: `2.49.0`
boto3: `1.13.2`
botocore: `1.16.2`
python `3.8.2`
Windows 10

Following the documentation from AWS: [Redshift.Client.restore_from_cluster_snapshot](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/redshift.html#Redshift.Client.restore_from_cluster_snapshot)

## How to reproduce 

```python
@mock_redshift
def test_cluster_already_exist():
    mock_cluster_id = "mock_cluster"
    mock_cluster_snapshot_id = "mock_cluster_snapshot_1"
    restore_cluster_az = "us-east-1b"
    redshift_client = boto3.client('redshift')
    redshift_client.create_cluster(
        DBName="test-db",
        ClusterIdentifier=mock_cluster_id,
        ClusterType="single-node",
        NodeType="ds2.xlarge",
        MasterUsername="username",
        MasterUserPassword="password",
    )
    redshift_client.create_cluster_snapshot(
        SnapshotIdentifier=mock_cluster_snapshot_id, ClusterIdentifier=mock_cluster_id
    )
    redshift_client.restore_from_cluster_snapshot.when.called_with(
        ClusterIdentifier=mock_cluster_id,
        SnapshotIdentifier=mock_cluster_snapshot_id,
        AvailabilityZone=restore_cluster_az
    ).should.throw(ClientError, "ClusterAlreadyExists")
```

## Expectation

`client.restore_from_cluster_snapshot` should throw a `ClientError` exception saying a cluster with the same ID already exist

##  Actual

`client.restore_from_cluster_snapshot` does not throw a `ClientError` exception, but proceeds into creating the cluster.

**Comment by bblommers** [comment]
Thanks for raising this @kennedy - will mark this as an enhancement
