### ISSUE TITLE
Using patch cause moto have issues with AWS_PROFILE environment variable

### ISSUE THREAD

**Issue by red8888** [spulec/moto#2984]
Im not sure how this is happening but it might be something to do with how moto is patching things

This works:
```
def mytest():
    conn = boto3.client("secretsmanager", region_name="ap-southeast-1")
    conn.create_secret(Name="test", SecretString="test")
    secret = mymodule.myfunc("test")
```

This throws "**botocore.exceptions.ProfileNotFound: The config profile (myprofilename) could not be found**"
```
def mytest():
    conn = boto3.client("secretsmanager", region_name="ap-southeast-1")
    conn.create_secret(Name="test", SecretString="test")
    with patch("builtins.open", mock_open()):
        secret = mymodule.myfunc("test")
```

**Comment by spulec** [comment]
Can you add some more code so I can try to reproduce this (where is moto being activated, what is `mock_open`, etc)?

**Comment by bblommers** [comment]
Going to close this due to a lack of response - do let us know if it's still an issue though
