### ISSUE TITLE
Cloudformation six.moves.urllib_parse import error (probably should be six.moves.urllib.parse)

### ISSUE THREAD

**Issue by mmannerm** [spulec/moto#299]
I am getting the following error while trying to use the cloudformation mock on Python 2.7 on Mac OS X Yosemite:
```
File "/Library/Python/2.7/site-packages/moto/cloudformation/responses.py", line 4, in <module>
    from six.moves.urllib_parse import urlparse
ImportError: cannot import name urlparse
```

On my own test code if I import from six.moves.urllib.parse (dot instead of underscore), it will work fine.

**Comment by spulec** [comment]
Thank you!
