### ISSUE TITLE
AWS CodeBuild, DynamoDB & mock_dynamodb2 

### ISSUE THREAD

**Issue by theslloyd** [spulec/moto#2990]
Firstly, it should be said that all unit tests are working as expected when called locally. The simple premise here is to create a DynamoDB Resource and Table using the following code:

`    
dynamodb = boto3.resource("dynamodb", "eu-west-1")
table = dynamodb.create_table
`
This is then passed to a function that uses the table resource to retrieve a fake value from the mocked dynamo db like so 
`
    oracle = FactorsOracle(dynamodb)
    algorithm = DataClass(oracle)
    result = algorithm.get_value("EXAMPLE")
`
However when this runs in AWS CodeBuild, we receive the following error: 

`

@mock_dynamodb2
--
279 | def test_algorithm():
280 | table_name = "TableName"
281 | >       dynamodb = boto3.resource("dynamodb", "eu-west-1")
282 |  
284 | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
285 | /usr/local/lib/python3.7/site-packages/boto3/__init__.py:100: in resource
286 | return _get_default_session().resource(*args, **kwargs)
287 | /usr/local/lib/python3.7/site-packages/boto3/session.py:389: in resource
288 | aws_session_token=aws_session_token, config=config)
289 | /usr/local/lib/python3.7/site-packages/boto3/session.py:263: in client
290 | aws_session_token=aws_session_token, config=config)
291 | /usr/local/lib/python3.7/site-packages/botocore/session.py:839: in create_client
292 | client_config=config, api_version=api_version)
293 | /usr/local/lib/python3.7/site-packages/botocore/client.py:86: in create_client
294 | verify, credentials, scoped_config, client_config, endpoint_bridge)
295 | /usr/local/lib/python3.7/site-packages/botocore/client.py:328: in _get_client_args
296 | verify, credentials, scoped_config, client_config, endpoint_bridge)
297 | /usr/local/lib/python3.7/site-packages/botocore/args.py:85: in get_client_args
298 | client_cert=new_config.client_cert)
299 | /usr/local/lib/python3.7/site-packages/botocore/endpoint.py:273: in create_endpoint
300 | client_cert=client_cert,
301 | /usr/local/lib/python3.7/site-packages/botocore/httpsession.py:179: in __init__
302 | self._manager = PoolManager(**self._get_pool_manager_kwargs())
303 | /usr/local/lib/python3.7/site-packages/botocore/httpsession.py:187: in _get_pool_manager_kwargs
304 | 'ssl_context': self._get_ssl_context(),
305 | /usr/local/lib/python3.7/site-packages/botocore/httpsession.py:196: in _get_ssl_context
306 | return create_urllib3_context()
307 | /usr/local/lib/python3.7/site-packages/botocore/httpsession.py:71: in create_urllib3_context
308 | context.options \|= options
309 | /usr/local/lib/python3.7/ssl.py:507: in options
310 | super(SSLContext, SSLContext).options.__set__(self, value)
311 | /usr/local/lib/python3.7/ssl.py:507: in options
312 | super(SSLContext, SSLContext).options.__set__(self, value)
313 | E   RecursionError: maximum recursion depth exceeded while calling a Python object
314 | !!! Recursion detected (same locals & position)
`

I have attempted to follow the guidance provided by this issue that was raised previously:

https://github.com/spulec/moto/issues/1036

However even with the supplied 'fixes', the error still occurs. Here is the applied suggested fix and output from the build:

`
    session = boto3.Session(
        aws_access_key_id='FakeSession',
        aws_secret_access_key='FakeSession',
        aws_session_token='FakeSession'
    )
    dynamodb = session.resource("dynamodb")
`
However I receive the same error:
`

return _get_default_session().resource(*args, **kwargs)
--
368 | /usr/local/lib/python3.7/site-packages/boto3/session.py:389: in resource
369 | aws_session_token=aws_session_token, config=config)
370 | /usr/local/lib/python3.7/site-packages/boto3/session.py:263: in client
371 | aws_session_token=aws_session_token, config=config)
372 | /usr/local/lib/python3.7/site-packages/botocore/session.py:839: in create_client
373 | client_config=config, api_version=api_version)
374 | /usr/local/lib/python3.7/site-packages/botocore/client.py:86: in create_client
375 | verify, credentials, scoped_config, client_config, endpoint_bridge)
376 | /usr/local/lib/python3.7/site-packages/botocore/client.py:328: in _get_client_args
377 | verify, credentials, scoped_config, client_config, endpoint_bridge)
378 | /usr/local/lib/python3.7/site-packages/botocore/args.py:85: in get_client_args
379 | client_cert=new_config.client_cert)
380 | /usr/local/lib/python3.7/site-packages/botocore/endpoint.py:273: in create_endpoint
381 | client_cert=client_cert,
382 | /usr/local/lib/python3.7/site-packages/botocore/httpsession.py:179: in __init__
383 | self._manager = PoolManager(**self._get_pool_manager_kwargs())
384 | /usr/local/lib/python3.7/site-packages/botocore/httpsession.py:187: in _get_pool_manager_kwargs
385 | 'ssl_context': self._get_ssl_context(),
386 | /usr/local/lib/python3.7/site-packages/botocore/httpsession.py:196: in _get_ssl_context
387 | return create_urllib3_context()
388 | /usr/local/lib/python3.7/site-packages/botocore/httpsession.py:71: in create_urllib3_context
389 | context.options \|= options
390 | /usr/local/lib/python3.7/ssl.py:507: in options
391 | super(SSLContext, SSLContext).options.__set__(self, value)
392 | /usr/local/lib/python3.7/ssl.py:507: in options
393 | super(SSLContext, SSLContext).options.__set__(self, value)
394 | E   RecursionError: maximum recursion depth exceeded while calling a Python object
395 | !!! Recursion detected (same locals & position)
396 | ________________________

`

These are the appropriate pip versions I am using:

moto 1.3.14
boto  2.49.0
boto3 1.9.116
botocore 1.12.253
pytest 5.4.2
pytest-cov 2.8.1

Thank you in advance for any help, scratching my head with this one.

**Comment by bblommers** [comment]
Hi @theslloyd, thanks for raising th is. Looks like a fun bug..

It looks like an issue with the requests-library: https://github.com/psf/requests/issues/3752

Not sure why/what's going on though. Will mark it as debugging.

What version of the requests-library do you have locally and in CodeBuild?

**Comment by theslloyd** [comment]
Same version locally and it codebuild (tied to a version via a requirements.txt) 

requests                                     2.23.0

**Comment by theslloyd-personal** [comment]
Is there anything that came out of debugging?

**Comment by bblommers** [comment]
Haven't had time to look into it  yet @theslloyd - I don't use CodeBuild at the moment (which I assume is instrumental in reproducing this), so no promises from me in regards to timelines

**Comment by bblommers** [comment]
Hi @theslloyd - is this still an issue?

**Comment by theslloyd** [comment]
@bblommers fixed with an upgrade of requests library
