### ISSUE TITLE
S3: Allow custom urls / Add hint that custom urls will not work

### ISSUE THREAD

**Issue by TanjaBayer** [spulec/moto#2993]
In our project we are using a ceph s3 storage (hosted on prem) and we wanted to mock it with mock_s3.

Problem is our url looks like:
https://s3.*some-internal-naming-convention*.de

Using this internal URL always raised the following issue:

```BASH
botocore.exceptions.ClientError: An error occurred (InvalidAccessKeyId) when calling the CreateBucket operation: Unknown
```

Which led me in the completely wrong direction for looking for an error fix :smile: 

After using the endpoint_url: https://s3.amazonaws.com everything works as expected.

If you do not plan to allow urls like the one we use, that is completely okay, but if someone faces the issue in the future he will at least see this issue and will be faster in solving it than I was :smiley: 

Appart from that adding a hint in the Readme would maybe help some people

**Comment by bblommers** [comment]
Thanks for raising this @TanjaBayer.
Makes sense to support this - we should be able to read the custom URL from an env variable, and intercept accordingly. Will mark this as an enhancement.

**Comment by MasterXuBoya** [comment]
Gool Tips!I got the same problem,which takes me two days to fix the problem.

**Comment by zenithlight** [comment]
Would it work to add a `mock_s3_opts(endpoint_url)` decorator to support this use-case? I ran into this same issue as well.

**Comment by alor** [comment]
same issue here, I use boto3 to interact with DigitalOcean Spaces which have a different endpoint_url and took a good amount of hours to figure out why the mock was not working... 

is there any workaround to mock a request towards an url that is not amazon?

**Comment by bblommers** [comment]
I've started working on a possible solution - is anyone here able to test this out and verify it works for them?
Branch: feature/s3_custom_endpoint_envvar
`pip install https://github.com/bblommers/moto/archive/feature/s3_custom_endpoint_envvar.zip`


The custom endpoint has to be configured as an environment variable:
`os.environ["CUSTOM_ENDPOINTS"] = "https://s3.*some-internal-naming-convention*.de"`

For reference, this is the test case how I'm testing my solution:
https://github.com/spulec/moto/compare/master...bblommers:feature/s3_custom_endpoint_envvar?expand=1#diff-f8da4c1e0b6ca9c7a122a227097f1a3b6d0bec4a5480297711f963038d941aa0

**Comment by crbunney** [comment]
Just encountered the same issue.
My minimal test case is:
```python
from moto import mock_s3
import boto3


@mock_s3
def test_passes():
    s3 = boto3.resource("s3")
    bucket = s3.Bucket("my_bucket")
    bucket.create()


@mock_s3
def test_fails():
    s3 = boto3.resource("s3", endpoint_url="https://my-other-domain.co.uk")
    bucket = s3.Bucket("my_bucket")
    bucket.create()
```

I have a similar use case as @TanjaBayer - a 3rd party object store with an S3 compatible API that I'd like to use `boto3` to access and `moto` to mock it in the tests

**Comment by bblommers** [comment]
Thanks for reporting your findings @crbunney. Just did some more testing, and it looks like it only works for URL's that start with `s3.`
The test cases I used [can be found here](https://github.com/bblommers/moto-custom-s3-url-exampleE/blob/main/tests/test_s3.py), and the [resulting CI run here](https://github.com/bblommers/moto-custom-s3-url-exampleE/runs/4117739554?check_suite_focus=true).

I'll have another look at this to see if I can get it working with all URL's.

**Comment by bblommers** [comment]
@crbunney I've just updated my branch to allow all URL's - the tests are now passing for your actual endpoint URL.
Would you mind giving this another go?

**Comment by crbunney** [comment]
Yep, that works for me, cheers :)

**Comment by bblommers** [comment]
Developing against S3-equivalent endpoints is now supported, as of moto >= 2.2.16.dev12.
This feature can be activated by setting a specific environment variable: `MOTO_S3_CUSTOM_ENDPOINTS`

An example on how to use it can be found here: 
http://docs.getmoto.org/en/latest/docs/services/s3.html

Please let us know if you're running into any issues.
