### ISSUE TITLE
Add mock describe_network_acls

### ISSUE THREAD

**Issue by anardy** [spulec/moto#2997]
Hi,

Thank you for creating this library. I'm writting my tests and I need a `describe_network_acls`, but according to [IMPLEMENTATION_COVERAGE](https://github.com/spulec/moto/blob/master/IMPLEMENTATION_COVERAGE.md) these are not yet implemented. The [CONTRIBUTING](https://github.com/spulec/moto/blob/master/CONTRIBUTING.md) document asks me to create an issue first.

I'm trying to write this method, but will probably need some guidance along the way. As soon as possible, I will send PR referencing this issue.

**Comment by bblommers** [comment]
Hi @anardy, if I'm not mistaken, this method [is already implemented](https://github.com/spulec/moto/blob/master/moto/ec2/responses/network_acls.py#L83) - the coverage document might just be out of date.

There is no test for it yet, though, so if you want to make a PR to add a test case and update the coverage doc that's very welcome! :)

**Comment by anardy** [comment]
Thank you for reply and I'm sorry for the confusion. I thought that the method implemention should also modify the `models.py` file.

Follow below the test I wrote and I would like to know if it's correct.

```
@mock_ec2
def test_describe_network_acls():
    conn = boto3.client("ec2", region_name="us-west-2")

    vpc = conn.create_vpc(CidrBlock="10.0.0.0/16")
    vpc_id = vpc["Vpc"]["VpcId"]

    network_acl = conn.create_network_acl(VpcId=vpc_id)

    network_acl_id = network_acl["NetworkAcl"]["NetworkAclId"]

    resp = conn.describe_network_acls(NetworkAclIds=[network_acl_id])

    result = resp["NetworkAcls"]

    result.should.have.length_of(1)
    result[0]["NetworkAclId"].should.equal(network_acl_id)
```

**Comment by bblommers** [comment]
Hi @anardy, you're right, it should be in models.py, ideally.

The test looks good to me!

**Comment by bblommers** [comment]
Closing - this is now part of moto >= 1.3.15.dev875
