### ISSUE TITLE
Can not register container instance in moto ECS in standalone server mode

### ISSUE THREAD

**Issue by walkingpendulum** [spulec/moto#2998]
Issue here is that I can not use moto in server mode for stubbing ECS, because there is no way to create and register container instance in standalone ECS stub.

Internally ecs_backend (which is a EC2ContainerServiceBackend) calls ec2_backend (which is a EC2Backend) during ContainerInstance instantiation https://github.com/spulec/moto/blob/master/moto/ecs/models.py#L441. Then ec2_backend raises InvalidInstanceIdError, and there is no way to change this behavior when ECS runs in separate process as `moto_server ecs`.

Any ideas what should I do here?

**Comment by spulec** [comment]
I don't have a great answer right now, but as a workaround you should be able to run all of the services on a single service `moto_server` without passing a service.

**Comment by walkingpendulum** [comment]
thank you for fast response! this is a great answer :) it solves my issue completely. btw this feature is not mentioned in README or in boto_server cli help, but absolutly worth it.
