### ISSUE TITLE
Support for add_tags action in EMR

### ISSUE THREAD

**Issue by alexnastetsky** [spulec/moto#300]
The "add_tags" method of EmrConnection in boto is not supported in moto, and is desired.

**Comment by spulec** [comment]
I've added some basic tag logic (and some additional cluster endpoints) with https://github.com/spulec/moto/commit/95b1fa42b27f747f0b25bcc9cebb40ce26e9bbe5. Feel free to reopen if there are additional endpoints you are looking for.

**Comment by alexnastetsky** [comment]
Thanks for the fast turnaround, this works in 0.4.1 version.
