### ISSUE TITLE
SNS unsubscribe: NotFound exception not thrown

### ISSUE THREAD

**Issue by tomers** [spulec/moto#3000]
According to boto3 SNS documentation, there is an _NotFound_ exception thrown when unsubscribing a non-existent subscription:

Reference: https://docs.aws.amazon.com/sns/latest/api/API_Unsubscribe.html
```
Errors
...
NotFound
Indicates that the requested resource does not exist.
HTTP Status Code: 404
```

However, in _moto_'s code, such case is ignored:
Reference: https://github.com/spulec/moto/blob/master/moto/sns/models.py#L483
```
    def unsubscribe(self, subscription_arn):
        self.subscriptions.pop(subscription_arn, None)
```

The test code also seems to be bogus, and expect that error not to be thrown:
Reference: https://github.com/spulec/moto/blob/master/tests/test_sns/test_subscriptions_boto3.py#L140
```
    # Now delete hanging subscription
    client.unsubscribe(SubscriptionArn=subscription_arn)
    ...
    # Deleting it again should not result in any error
    client.unsubscribe(SubscriptionArn=subscription_arn)
```

**Comment by tomers** [comment]
I verified in real world test that indeed no exception is thrown.
Not sure why the documentation specifies NotFound error.
Closing this ticket.

**Comment by bblommers** [comment]
Thanks for raising this @tomers. I've reported it to AWS - hopefully they'll update their documentation!
