### ISSUE TITLE
Add mock for AWS ElastiCache

### ISSUE THREAD

**Issue by VijayantSoni** [spulec/moto#3002]
Add mock for AWS ElastiCache

**Comment by weldpua2008** [comment]
Are there some examples to start implementing new features?
I am interested in the feature.

**Comment by bblommers** [comment]
Hi @weldpua2008, there's a section on how to add a new service in our [CONTRIBUTING.md](https://github.com/spulec/moto/blob/master/CONTRIBUTING.md), and some examples as well.

PR's are always welcome, if you have the time! Let me know if you have any questions.
