### ISSUE TITLE
CloudFormation autoscaling group PropagateAtLaunch not setting properly

### ISSUE THREAD

**Issue by zbrookle** [spulec/moto#3009]
When creating a CloudFormation autoscaling group, PropagateAtLaunch for tags is being reported as 'False' even though it was set to 'True' in the template

**Comment by zbrookle** [comment]
I can also work on this

**Comment by zbrookle** [comment]
Upon further investigation it's actually the ecs service directly that's not returning the correct response, the moto backend has the correct response, but the value is getting lost somewhere in the interaction with boto3

**Comment by bblommers** [comment]
This is available as of moto >= 1.3.15.dev871
