### ISSUE TITLE
Add tag get_resources support for target groups

### ISSUE THREAD

**Issue by ben-nz** [spulec/moto#3011]
Hi there,

I would like to leverage the resource tagging endpoint to search for target groups. I have also noticed a small typo in the handling of tags for elbv2 in the code (is currently `elasticloadbalancer`, should be `elasticloadbalancing` as per [user guide](https://docs.aws.amazon.com/IAM/latest/UserGuide/list_elasticloadbalancingv2.html). I have linked a pull request.

Regards,
Ben

**Comment by bblommers** [comment]
This should be available as of moto >= 1.3.15.dev870

**Comment by ben-nz** [comment]
Thanks @bblommers ! While I was working on this I noticed an issue with using multiple filters in the resource tagging endpoint, will write up an issue in the next couple of days.
