### ISSUE TITLE
Moto without Boto(2)?

### ISSUE THREAD

**Issue by maxcountryman** [spulec/moto#3013]
I'm wondering if it's possible to use Moto without requiring `boto`? This seems to be causing some bizarre issues for us and so if there's some way of avoiding it that would be great.

**Comment by bblommers** [comment]
Hi @maxcountryman, we are considering deprecating boto alltogether, so that would solve your problem. See https://github.com/spulec/moto/issues/2950.
Don't think we have an ETA at this moment, though!

**Comment by maxcountryman** [comment]
Thanks, @bblommers--I'll close this for now then.
