### ISSUE TITLE
cloudformation validation tests failing

### ISSUE THREAD

**Issue by jweite** [spulec/moto#3023]
make test-only of current master results in failures on tests.test_cloudformation.test_validate.test_boto3_yaml_invalid_missing_resource and tests.test_cloudformation.test_validate.test_boto3_json_invalid_missing_resource.

Preliminary diagnosis indicates that cfnlint is returning a slightly different error message than the test asserts.  

Returned: ...Stack with id Missing top level template...
Expected: ...Stack with id Missing top level item...

Not sure if message being returned changed underneath moto or if it's perhaps specific to my env.

cfn-lint==0.32.1
moto source version = master (80b64f9)
environment:  python3.7 virtual env on macos.

**Comment by bblommers** [comment]
This was due to a new version of cfn-lint being released - our Travis tests were failing as well.
It was fixed in #3024.
