### ISSUE TITLE
IoT Core delete_thing_group does not behave like real boto3 for nonexistent group

### ISSUE THREAD

**Issue by bobobox** [spulec/moto#3026]
### moto version: 
1.3.15

### module: 
`mock_iot`

### action: 
`delete_thing_group`

### expected behavior:

boto3's response is the same whether or not the thing group existed or not. It does not throw any exception if requested to delete a nonexistent thing group.

### actual behavior:

moto throws a `ResourceNotFoundException` if the thing group does not exist: 

    botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the DeleteThingGroup operation: The specified resource does not exist

**Comment by bblommers** [comment]
This is now part of moto >= 1.3.16.dev55
