### ISSUE TITLE
SNS mocking with moto is not working correctly

### ISSUE THREAD

**Issue by red8888** [spulec/moto#3027]
FYI I opened an SO post before reporting this here: https://stackoverflow.com/questions/62015260/sns-mocking-with-moto-is-not-working-correctly

In my unit test:
```
@mock_sns
def test_my_function_that_publishes_to_sns():
    conn = boto3.client("sns", region_name="us-east-1")
    mock_topic = conn.create_topic(Name="mock-topic")
    topic_arn = mock_topic.get("TopicArn")

    os.environ["SNS_TOPIC"] = topic_arn
    # This works inside the unit test itself, obviously useless because I want
    # to mock sns for the function that uses sns, but it seems at least some part of it is working
    # conn.publish(TopicArn=os.environ["SNS_TOPIC"], Message="sdfsdsdf") #works 

    # call my_function
    my_module.my_method()
```

```
# inside my_module, my_function...
sns_client.publish(
            TopicArn=os.environ["SNS_TOPIC"], Message="my message",
        )
```

I get the error: botocore.errorfactory.NotFoundException: An error occurred (NotFound) when calling the Publish operation: Endpoint with arn arn:aws:sns:us-east-1:123456789012:mock-topic not found

Doesnt make sense, thats the topic moto is suppose to have created and mocked. Why is it saying it doesnt exist? If I call conn.publish(TopicArn=topic_arn, Message="sdfsdsdf") inside of the unit test itself it seems to mock it, but it doesnt mock it for my_module.my_method() which the unit test executes. Maybe its destroying the mocked topic too soon?

I tried this every which way and I get the exact same error:
```
# Using context manager
def test_my_function_that_publishes_to_sns():
    with mock_sns():
        conn = boto3.client("sns", region_name="us-east-1")
        mock_topic = conn.create_topic(Name="mocktopic")
        topic_arn = mock_topic.get("TopicArn")

        os.environ["SNS_TOPIC"] = topic_arn

        # call my_function
        my_module.my_method()


# Using decorator
@mock_sns
def test_my_function_that_publishes_to_sns():
    conn = boto3.client("sns", region_name="us-east-1")
    mock_topic = conn.create_topic(Name="mocktopic")
    topic_arn = mock_topic.get("TopicArn")

    os.environ["SNS_TOPIC"] = topic_arn

    # call my_function
    my_module.my_method()


# Using decorator and context manager
@mock_sns
def test_my_function_that_publishes_to_sns():
    with mock_sns():
        conn = boto3.client("sns", region_name="us-east-1")
        mock_topic = conn.create_topic(Name="mocktopic")
        topic_arn = mock_topic.get("TopicArn")

        os.environ["SNS_TOPIC"] = topic_arn

        # call my_function
        my_module.my_method()
```

**Comment by red8888** [comment]
issue was my_module.my_method() wasn't setting a region just doing `client = boto3.client("sns")`

It could not find it because it was defaulting to a diff region than us-east-1 which was hard coded into the unit test

**Comment by bblommers** [comment]
Good to hear it's been solved, and thank  you for providing the solution!
