### ISSUE TITLE
AWS IoT describe_thing_group is broken

### ISSUE THREAD

**Issue by lkong** [spulec/moto#3034]
Verison 1.3.14
**○ pip3 show moto**   
Name: moto
Version: 1.3.14
Summary: A library that allows your python tests to easily mock out the boto library
Home-page: https://github.com/spulec/moto
Author: Steve Pulec
Author-email: spulec@gmail.com
License: Apache
Location: /home/lkong/.local/lib/python3.8/site-packages
Requires: mock, idna, sshpubkeys, python-dateutil, boto, botocore, requests, PyYAML, Jinja2, docker, cfn-lint, cryptography, responses, six, boto3, xmltodict, aws-xray-sdk, python-jose, pytz, werkzeug, jsondiff
Required-by: 

**Exception:**
re.error: bad character in group name 'confirmationToken+' at position 25

**How to reproduce:**
```python
from moto import mock_iot
import unittest
import boto3
import pytest
class TestGroupController(unittest.TestCase):

    @mock_iot
    def test_add_get_group(self):
        """Test case for add_group

        add a group
        """
        iot_client = boto3.client('iot')

        response = iot_client.create_thing_group(
            thingGroupName='test_group_name')
        response = iot_client.describe_thing_group(
            thingGroupName='test_group_name')


if __name__ == '__main__':
    unittest.main()
```

**Comment by lkong** [comment]
It's also broken for describe_thing since it's depending on describe_thing_group

**Comment by bblommers** [comment]
Hi @lkong, if I'm not mistaken, this has been raised before in #2728.
It should be fixed in Moto >= 1.3.15.dev344 - are you able to upgrade and verify that this works in the latest release?

**Comment by lkong** [comment]
1.3.15.dev880 works, sorry for the duplicate issue.
I searched for the keyword in issues and it's not been mentioned before.

**Comment by bblommers** [comment]
No worries, happy to hear it's working now!
