### ISSUE TITLE
Public IP address not automatically assigned when calling `run_instances()`

### ISSUE THREAD

**Issue by madisonmay** [spulec/moto#304]
No public ip is mocked when instances are created with `run_instances`.  Is this expected / intended?  I was hoping the `ip_address` field would be mocked.

**Comment by spulec** [comment]
Thanks for opening the issue!

It was certainly a bug. I've added some basic support with https://github.com/spulec/moto/commit/136873d49ef07811c6014d2915997c8fbd59a35b. Feel free to reopen if more work still needs to be done for your use case.
