### ISSUE TITLE
EventsRule Cloudformation's update

### ISSUE THREAD

**Issue by gmcrocetti** [spulec/moto#3042]
Hey guys ! Happy to be here again :)

Rigth now I'm facing a issue related with the update of my stack. This issue was detected during a serverless deployment and after further investigation I'd figured out there's no implementation for `update_from_cloudformation_json` in Rule's model.

**Comment by bblommers** [comment]
Welcome back @gmcrocetti :) 

This is now available as of moto >= 1.3.15.dev885
