### ISSUE TITLE
CreateRoute to NetworkInterfaceId has not been implemented in Moto yet

### ISSUE THREAD

**Issue by postmart** [spulec/moto#3054]
I am getting `CreateRoute to NetworkInterfaceId has not been implemented in Moto yet` error when trying to create a route:

```
route = ec2_client.create_route(
            DestinationCidrBlock=pub_subnet.cidr_block,
            NetworkInterfaceId=eniA["NetworkInterface"]["NetworkInterfaceId"],
            RouteTableId=route_table["RouteTable"]["RouteTableId"],
        )
```

Please add support for `NetworkInterfaceId` as next hop in routes.

Thank you,

**Comment by bblommers** [comment]
This was implemented in #3063, so I'll close this. Let us know if there's still anything missing.
