### ISSUE TITLE
Add support for Egress Only Internet Gateway action

### ISSUE THREAD

**Issue by postmart** [spulec/moto#3060]
I am getting `NotImplementedError` when try to create an egress-only internet gateway:

`
NotImplementedError: The create_egress_only_internet_gateway action has not been implemented
`

Please add support for egress-only internet gateway if possible.

Thank you.

**Comment by bblommers** [comment]
Hi @postmart, this feature should now be available as of Moto >= 2.2.4.
I'll close this ticket for now, but please let us know if we've missed anything.
