### ISSUE TITLE
Make it work with terraform

### ISSUE THREAD

**Issue by benkeil** [spulec/moto#3068]
Version: I use the latest master.

It seems that you cant use Terraform with Moto. I use a local state and as soon as you have a state (`terraform.tfstate`) and try to apply again, everything is crashing. When you remove the file it works again.

It would be nice to use Moto together with terraform and terratest as THE solution to test serverless applications locally.

**Comment by bblommers** [comment]
Hi @benkeil, do you have a specific example where this fails? 

I know simple use cases work with state (just tested it with a single DynamoDB). No doubt there are specific features that are not supported yet, but we'd need to see the TF file to figure out on which feature it fails.

**Comment by benkeil** [comment]
I test now the other fixed bugs and try to add the corresponding terraform code.
