### ISSUE TITLE
if_not_exists() in UpdateExpression causes remainder of the expression to be ignored

### ISSUE THREAD

**Issue by flayman** [spulec/moto#3084]
Hi,

I'm using moto==1.3.14 with python 3.8.3. I've found some odd behaviour when implementing a DynamoDB atomic counter that begins at zero. Doing this requires the SET command in the UpdateExpression argument to Table.update_item(). I note that this is in fact the recommended way to implement a counter. The problem is that you must use the if_not_exists() function if you want the initial value to be set to something other than zero. I'd like a counter to return its first value as zero, so I start it at -1 and add 1. My arguments look like this:

```
Key= my_key_goes_here,
UpdateExpression="SET #c = if_not_exists(#c, :neg) + :n",
ExpressionAttributeNames={'#c': 'my_attribute'},
ExpressionAttributeValues={':n': 1, ':neg': -1},
ReturnValues="ALL_NEW"
```

I find that this works with a real boto3 resource, but the moto mocked resource seems to ignore the addition operation that comes after the if_not_exists function, so that I always get back `Decimal(-1)` for the attribute. 

I tried reversing the arguments with `UpdateExpression="SET #c = :n + if_not_exists(#c, :neg)"`. The result was even stranger. Now I get back a string that looks like this:

```
:n+if_not_exists(my_counter, :neg)
```

I found some earlier issues reported where strings were coming back when if_not_exists was used in an expression. It seems this can still happen under certain circumstances.

**Comment by bblommers** [comment]
Hi @flayman, there have been quite a few improvements to the UpdateExpression since the 1.3.14 release. Are you able to reproduce this with the latest dev version, https://pypi.org/project/moto/1.3.15.dev914/?

**Comment by flayman** [comment]
I would be willing to give it a try, but the only other active branch is called 'deprecate-httpretty', which doesn't seem to have anything to do with this problem. I searched the test code in that branch and in master and none of the tests cover this.

**Comment by flayman** [comment]
Okay, I have now tried the indicated development version and it does indeed give a different result, but it is still not correct. The parsing problem with operands reversed is no longer an issue. What I get now is that the counter starts at 1 when there's no existing record for that key. It's the same result as setting :neg = 0. However, if I set :neg = -2, then the first result comes back as -1 and each successive result is incremented. You could say that this case works as expected. I'm at a loss to understand why my case doesn't.

**Comment by flayman** [comment]
I deleted a previous response because it was erroneous. Yes, this pre-release version solves the problem with the operands ordered either way. Thanks.

**Comment by bblommers** [comment]
Glad it now works!
