### ISSUE TITLE
Feature Request: RDS - create_db_cluster

### ISSUE THREAD

**Issue by dhammond22222** [spulec/moto#3093]
Unable to mock a create_db_cluster with Moto.  Noticied it's not covered in the responses.py under rds or rds2.

`self = <moto.rds.responses.RDSResponse object at 0x118ea5048>

    def call_action(self):
        headers = self.response_headers
    
        try:
            self._authenticate_and_authorize_normal_action()
        except HTTPException as http_error:
            response = http_error.description, dict(status=http_error.code)
            return self._send_response(headers, response)
    
        action = camelcase_to_underscores(self._get_action())
        method_names = method_names_from_class(self.__class__)
        if action in method_names:
            method = getattr(self, action)
            try:
                response = method()
            except HTTPException as http_error:
                response = http_error.description, dict(status=http_error.code)
    
            if isinstance(response, six.string_types):
                return 200, headers, response
            else:
                return self._send_response(headers, response)
    
        if not action:
            return 404, headers, ""
    
        raise NotImplementedError(
>           "The {0} action has not been implemented".format(action)
        )
E       NotImplementedError: The create_db_cluster action has not been implemented`

**Comment by bblommers** [comment]
Thanks for raising this @dhammond22222 - marking this as an enhancement
