### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by garrettheel** [spulec/moto#3095]
👋  it looks like it has been a while since (over 6 months) since the last official release. Just wondering if there was a plan to release 1.3.15 soon? There are a bunch of great new features that I'd love to take advantage of

**Comment by calvin-barker** [comment]
I'd also love to see a new release, but right now I'm working around this issue by having this entry in my requirements-dev.txt to get moto-1.3.15.dev0 from the master branch:
`git+https://github.com/spulec/moto.git@master`

(works like this command)
`pip install git+https://github.com/spulec/moto.git@master`

**Comment by asherf** [comment]
@spulec @bblommers any chance to get 1.3.15 out anytime soon ?
That would be extremely helpful.

**Comment by bwitt** [comment]
@spulec @bblommers just to echo others' sentiment: it'd be great to have a release soon. the lack of a recent release is causing some headaches.  thanks!

**Comment by MattFisher** [comment]
Recognising that, as mentioned in #2681, there's pre-releases posted after each PR merge, it would still be helpful to have official releases fairly regularly.

Our CI pipeline uses Dependabot, which relies on semantic versioning to be able to automatically create and merge new PRs to update dependencies when new releases appear. It might be possible to configure some extra logic to special-case individual packages, but it puts an air of non-production-readiness about things that doesn't feel good.

Moto is awesome, and thanks for all your hard work!

**Comment by spulec** [comment]
If someone has some extra time to cleanup the changelog for a new release, I'll be happy to cut one.

**Comment by spulec** [comment]
Version `1.3.15` has now been released!

**Comment by bblommers** [comment]
Awesome. Thanks @spulec!

**Comment by jmehnle** [comment]
@spulec, thank you for putting in the time and effort to create a new release! It's so much appreciated!
