### ISSUE TITLE
Not able to SSH the EC2 intance 

### ISSUE THREAD

**Issue by uyadavv** [spulec/moto#3112]
Steps to Reproduce:
1. Created security group
2. Created EC2 Instance with security group using moto.
3. Now try to ssh the created EC2 instance using the below mentioned code:

import paramiko

key = paramiko.RSAKey.from_private_key_file('C:/Users/Desktop/key-test.pem')
client = paramiko.SSHClient()
client.set_missing_host_key_policy(paramiko.AutoAddPolicy())

try:
    client.connect(hostname='54.214.220.16', username="ec2-user", pkey=key)
    stdin, stdout, stderr = client.exec_command("cmd")
    print (stdout.read())
    client.close()
    
except Exception as e:
    print (e)

Expected Result:
Able to SSH the EC2 instance.

Actual Result:
[WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

**Comment by bpandola** [comment]
`moto` mocks the AWS API--it doesn't actually create any resources.  A mocked EC2 instance is just some metadata in memory for the purpose of allowing your AWS API calls to succeed and return data that looks like the real thing.  There's no EC2 instance to SSH to.  You would have to mock your `paramiko.SSHClient` calls separately, as they are far beyond the scope of what `moto` was designed to cover.

**Comment by bblommers** [comment]
Exactly - Moto only mocks the SDK methods, but doesn't provide any actual servers to SSH into. Closing
