### ISSUE TITLE
cloudformation/parsing.py has an incomplete `UNDOCUMENTED_NAME_TYPE_MAP`

### ISSUE THREAD

**Issue by richford** [spulec/moto#3127]
## Issue
[`cloudformation/parsing.py`](https://github.com/spulec/moto/blob/master/moto/cloudformation/parsing.py#L102) wisely has an `UNDOCUMENTED_NAME_TYPE_MAP` because the name type references in the [Amazon documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-name.html) are incomplete. However, there are additional resource types that should be added. For my purposes in particular, I would like to add
```python
{
    "AWS::Batch::ComputeEnvironment": "ComputeEnvironmentName",
    "AWS::Batch::JobDefinition": "JobDefinitionName",
    "AWS::Batch::JobQueue": "JobQueueName",
    "AWS::EC2::LaunchTemplate": "LaunchTemplateName",
}
```
and I will submit a PR to that effect.

But, combing through the [cloudformation documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-template-resource-type-ref.html), I noticed that the following resource types could also be added:
```python
{
    "AWS::AccessAnalyzer::Analyzer": "AnalyzerName",
    "AWS::AmazonMQ::Broker": "BrokerName",
    "AWS::AmazonMQ::Configuration": "Name",
    "AWS::Amplify::App": "Name",
    "AWS::Amplify::Branch": "BranchName",
    "AWS::Amplify::Domain": "DomainName",
    "AWS::ApiGateway::Authorizer": "Name",
    "AWS::ApiGateway::DomainName": "DomainName",
    "AWS::ApiGateway::RequestValidator": "Name",
    "AWS::ApiGateway::RestApi": "Name",
    "AWS::ApiGateway::Stage": "StageName",
    "AWS::ApiGateway::UsagePlan": "UsagePlanName",
    "AWS::ApiGateway::VpcLink": "Name",
    "AWS::ApiGatewayV2::Api": "Name",
    "AWS::ApiGatewayV2::Authorizer": "Name",
    "AWS::ApiGatewayV2::DomainName": "DomainName",
    "AWS::ApiGatewayV2::Model": "Name",
    "AWS::ApiGatewayV2::Stage": "StageName",
    "AWS::ApiGatewayV2::VpcLink": "Name",
    "AWS::AppConfig::Application": "Name",
    "AWS::AppConfig::ConfigurationProfile": "Name",
    "AWS::AppConfig::DeploymentStrategy": "Name",
    "AWS::AppConfig::Environment": "Name",
    "AWS::AppMesh::Mesh": "MeshName",
    "AWS::AppMesh::Route": "RouteName",
    "AWS::AppMesh::VirtualNode": "VirtualNodeName",
    "AWS::AppMesh::VirtualRouter": "VirtualRouterName",
    "AWS::AppMesh::VirtualService": "VirtualServiceName",
    "AWS::AppStream::Fleet": "Name",
    "AWS::AppStream::ImageBuilder": "Name",
    "AWS::AppStream::Stack": "Name",
    "AWS::AppSync::DataSource": "Name",
    "AWS::AppSync::FunctionConfiguration": "Name",
    "AWS::AppSync::GraphQLApi": "Name",
    "AWS::ApplicationAutoScaling::ScalingPolicy": "PolicyName",
    "AWS::Athena::DataCatalog": "Name",
    "AWS::Athena::NamedQuery": "Name",
    "AWS::Athena::WorkGroup": "Name",
    "AWS::Backup::BackupVault": "BackupVaultName",
    "AWS::CE::CostCategory": "Name",
    "AWS::Cassandra::Keyspace": "KeyspaceName",
    "AWS::Cassandra::Table": "TableName",
    "AWS::Chatbot::SlackChannelConfiguration": "ConfigurationName",
    "AWS::Cloud9::EnvironmentEC2": "Name",
    "AWS::CloudFormation::Macro": "Name",
    "AWS::CloudTrail::Trail": "TrailName",
    "AWS::CloudWatch::CompositeAlarm": "AlarmName",
    "AWS::CloudWatch::Dashboard": "DashboardName",
    "AWS::CloudWatch::InsightRule": "RuleName",
    "AWS::CodeBuild::Project": "Name",
    "AWS::CodeBuild::ReportGroup": "Name",
    "AWS::CodeCommit::Repository": "RepositoryName",
    "AWS::CodeGuruProfiler::ProfilingGroup": "ProfilingGroupName",
    "AWS::CodePipeline::Pipeline": "Name",
    "AWS::CodePipeline::Webhook": "Name",
    "AWS::CodeStarConnections::Connection": "ConnectionName",
    "AWS::CodeStarNotifications::NotificationRule": "Name",
    "AWS::Cognito::UserPool": "UserPoolName",
    "AWS::Cognito::UserPoolClient": "ClientName",
    "AWS::Cognito::UserPoolGroup": "GroupName",
    "AWS::Cognito::UserPoolIdentityProvider": "ProviderName",
    "AWS::Cognito::UserPoolResourceServer": "Name",
    "AWS::Config::ConfigurationAggregator": "ConfigurationAggregatorName",
    "AWS::Config::ConformancePack": "ConformancePackName",
    "AWS::Config::OrganizationConfigRule": "OrganizationConfigRuleName",
    "AWS::Config::OrganizationConformancePack": "OrganizationConformancePackName",
    "AWS::Events::EventBus": "Name",
    "AWS::Logs::Destination": "DestinationName",
    "AWS::Logs::LogStream": "LogStreamName",
    "AWS::ServiceDiscovery::HttpNamespace": "Name",
    "AWS::ServiceDiscovery::PrivateDnsNamespace": "Name",
    "AWS::ServiceDiscovery::PublicDnsNamespace": "Name",
    "AWS::ServiceDiscovery::Service": "Name",
}
```
...and probably much more. I just stopped alphabetically after services that start with "C" because I was tired and also unfamiliar with those services. So the dict could wind up being pretty long. In addition to referencing my PR to add the batch services, maybe this issue could spur comments from the core devs about how to handle the large number of custom name types. I'd be happy to submit a PR for the additional service types also but don't want to make it too unwieldy to maintain.

## Versions
`pip list | grep oto` returns
```bash
boto               2.49.0
boto3              1.14.20
botocore           1.17.20
moto               1.3.15.dev959
```

**Comment by bblommers** [comment]
Hi @richford, thanks for raising this. The full list would become quite wieldy indeed, so I don't think listing everything in one place is the way to go.

IMO, in order to keep this maintainable, the responsibility should be decentralized, and this user-friendly identifier should be supplied by the model itself.
Most Models already have a `physical_resource_id` to identify them in CloudFormation. We could simply extend this, and also add a `logical_resource_id` to each Model that would return the appropriate attribute.

Going one step further, we might not eve need the mapping from `AWS::AccessAnalyzer::Analyzer` -> `moto.access.model`. Have each BaseModel supply the name how it is known in CF, and we can build the list of supported models at runtime.

@spulec Any ideas on this?

**Comment by spulec** [comment]
I agree that moving this (and more) into the service models feels like a more maintainable approach long-term.

**Comment by richford** [comment]
That makes sense. Thanks @bblommers and @spulec for the input. It looks like we should then close #3128 without merging and address this issue as you prescribed. 

Given my limited knowledge of how moto works internally, the recommended approach is a bit over my head and I'll need some suggestions and pointers to get started. Happy to help but I just want to set expectations about how long it'll take me.

**Comment by bblommers** [comment]
Hi @richford, see the attached PR - hopefully that makes it clear what I had in mind. Feel free to push to that branch, or copy it into your own branch, whatever is easier.

**Comment by bblommers** [comment]
This is now part of moto >= 1.3.15.dev1015
