### ISSUE TITLE
ecs.create_service and ecs.describe_service do not handle tags correctly

### ISSUE THREAD

**Issue by mkielar** [spulec/moto#3138]
In #2450 and #2338 handling tags has been added, however boto3 supports setting and reading tags in `create_service` and `describe_service`.

## Actual:
While one can call this:
```
service_matching_response: Dict = ecs_client.create_service(
            cluster=cluster_response['clusterArn'],
            serviceName=service_name_matching,
            taskDefinition=task_definition_response['taskDefinitionArn'],
            desiredCount=2,
            tags=[{
                'key': 'environment',
                'value': 'dev-i1234'
            }]
        )['service']
```
and it creates the service, the response from that method does not contain `tags` key.
Similarly, when calling:
```
result: Dict = self._ecs_client.describe_services(
            cluster=services_in_event.cluster_arn,
            services=services_in_event.service_arns,
            include=['TAGS']
)
```
the result does not contain `tags` key.

## Expected:
`tags` and `include` should be handled properly and `tags` should be returned.

**Comment by ipmb** [comment]
Also applies to `describe_task_definition`

**Comment by gruebel** [comment]
@bblommers can you close this issue, the functionality was added with above PR.
