### ISSUE TITLE
ecs.update_service does not handle service_arns, just services names.

### ISSUE THREAD

**Issue by mkielar** [spulec/moto#3139]
## Actual:
When running:
```
ecs_client.update_service(
            cluster=cluster_arn,
            service=service_arn,
            desiredCount=0
)
```
I'm getting `ServiceNotFoundException` raised, even though I'm using service and cluster ARNs returned by a call to `describe_services`, after creating the services with moto.

## Expected:
Service/Cluster names and ARNs should both be supported.

## Walkaround:
I changed my application logic to make it testable with moto, and it worked, but I shouldn't have to do that, especially that both `boto3` and AWS API allow using Names/ARNs interchangeably.

**Comment by bblommers** [comment]
Thanks for raising this @mkielar - marking this as an enhancement.
