### ISSUE TITLE
feat: organizations.tag_resource (1.3.14)

### ISSUE THREAD

**Issue by jbpratt78** [spulec/moto#3143]
```
Name: moto
Version: 1.3.14
Summary: A library that allows your python tests to easily mock out the boto library
Home-page: https://github.com/spulec/moto
Author: Steve Pulec
Author-email: spulec@gmail.com
License: Apache
Location: /..../lib/python3.8/site-packages
Requires: cryptography, requests, boto, responses, PyYAML, Jinja2, cfn-lint, idna, boto3, aws-xray-sdk, python-jose, pytz, xmltodict, docker, werkzeug, botocore, jsondiff, python-dateutil, sshpubkeys, six, mock
Required-by:
```

My test:
```py
@mock_organizations
def test_get_account_tags() -> None:
    org = boto3.client("organizations")
    org.create_organization(FeatureSet="ALL")
    org.create_account(
        Email="example@example.com", AccountName="Test", RoleName="SuperAdmin"
    )
    acct_id = org.list_accounts()["Accounts"][0]["Id"]
    acct_tags = {"Test": "example"}
    org.tag_resource(
        ResourceId=acct_id,
        Tags=[{"Key": str(k), "Value": str(v)} for k, v in acct_tags.items()],
    )

    got_acct_tags = get_account_tags(account_id=acct_id, client=org)
    assert acct_tags == got_acct_tags
```

Error:
`E       NotImplementedError: The tag_resource action has not been implemented`

**Comment by bblommers** [comment]
Thanks for raising this @jbpratt78 - will mark it as an enhancement.

**Comment by jbpratt78** [comment]
@bblommers awesome! Happy to attempt to contribute the feature. Here is what I have gathered with EC2, S3, and ELBv2 (I will continue to look at some of the newer implementations as well), please let me know if I am off base or missing some things...
https://github.com/spulec/moto/blob/bb6da93891482ddcb87c23e6abddc0e451f72d30/moto/s3/models.py#L499-L507
https://github.com/spulec/moto/blob/bed769a387e667f7d6cb4dbf306963f70f54afbd/moto/elbv2/models.py#L389-L399
an implementation for `FakeAccount`, similar to one of the above.. https://github.com/spulec/moto/blob/bed769a387e667f7d6cb4dbf306963f70f54afbd/moto/organizations/models.py#L50
and adding the `organizations_backend` to `resourcegroupstaggingapi`?
https://github.com/spulec/moto/blob/bed769a387e667f7d6cb4dbf306963f70f54afbd/moto/resourcegroupstaggingapi/models.py#L25

**Comment by bblommers** [comment]
Hi @jbpratt78, the `tag_resource`-method has to be added to moto/organisations/responses.py first, similar to https://github.com/spulec/moto/blob/master/moto/elbv2/responses.py#L424
Responses.py will just parse the incoming request (and is responsible for validation, if any), and the actual storage/retrieval is then done in models.py

The FakeAccount should be already created behind the scenes, when you call `org.create_account`, so don't worry about that.

The `resourcegroupstaggingapi`-part is not required if you only care about adding tagging-capabilities to the `organisations`-service - but if you do have time/inclination to extend that service as well, that's always welcome!

**Comment by jbpratt78** [comment]
> Hi @jbpratt78, the `tag_resource`-method has to be added to moto/organisations/responses.py first, similar to [`master`/moto/elbv2/responses.py#L424](https://github.com/spulec/moto/blob/master/moto/elbv2/responses.py?rgh-link-date=2020-07-17T16%3A02%3A13Z#L424)
> Responses.py will just parse the incoming request (and is responsible for validation, if any), and the actual storage/retrieval is then done in models.py
> 
> The FakeAccount should be already created behind the scenes, when you call `org.create_account`, so don't worry about that.
> 
> The `resourcegroupstaggingapi`-part is not required if you only care about adding tagging-capabilities to the `organisations`-service - but if you do have time/inclination to extend that service as well, that's always welcome!

Ah, I knew I was missing some stuff. I will take a stab at this over the weekend, thank you for the guidance!

**Comment by jbpratt78** [comment]
It seems there has been some drift in how these have been implemented, as well as some of it is already, I guess. https://github.com/spulec/moto/blob/bed769a387e667f7d6cb4dbf306963f70f54afbd/moto/organizations/responses.py#L128-L141 https://github.com/spulec/moto/blob/bed769a387e667f7d6cb4dbf306963f70f54afbd/moto/organizations/models.py#L506-L537
as well as both of these calls (untag as well) (https://docs.aws.amazon.com/organizations/latest/APIReference/API_TagResource.html) return an empty body.

**Comment by jbpratt78** [comment]
Wooh! Seems on the dev branch my tests are passing. Sorry about all the confusion.

`shared_test.py::test_get_account_tags PASSED                                                                       [100%]
`

**Comment by bblommers** [comment]
Apologies for not realizing that myself! I should have checked, instead of assuming it wasn't there. 

FYI, we have pre-releases for every commit to master, so you should be able to use the latest version: https://pypi.org/project/moto/#history
