### ISSUE TITLE
Implementation: Task Sets

### ISSUE THREAD

**Issue by aaronhill** [spulec/moto#3151]
Add support for ECS `*_task_set` endpoints for support of `CODE_DEPLOY` and `EXTERNAL` ECS service `deploymentController`.

Endpoints include:
 * create_task_set
 * describe_task_sets
 * update_task_set
 * delete_task_set
 * update_service_primary_task_set

This implementation requires fixing a bug with moto ECS `create_service` which incorrectly assumes `taskDefinition` is a required attribute to support task set `taskDefinition` properly.

**Comment by bblommers** [comment]
This is now part of moto >= 1.3.15.dev979
