### ISSUE TITLE
Feature request: add a mock_ce for Cost Explorer

### ISSUE THREAD

**Issue by Lucas-C** [spulec/moto#3166]
Service: [AWS Cost Explorer](https://aws.amazon.com/fr/aws-cost-management/aws-cost-explorer/)

I am new to using `moto`, but this is a fantastic tool for writing my tests!
Many thanks for developping it :)

I discovered it with [this article](https://www.sanjaysiddhanti.com/2020/04/08/s3testing/) and so far I'm mostly using `mock_dynamodb`.

I have a need to mock a `ce` client and I wondered if a mock for this other AWS service could be added please?

**Comment by bblommers** [comment]
Hi @Lucas-C, thanks for raising this - will mark it as an enhancement
