### ISSUE TITLE
Creating ECS TaskSet via CF has not been implemented

### ISSUE THREAD

**Issue by pinkjosh** [spulec/moto#3167]
Trying to run a cloudformation template that provisions ECS Service, TaskDefinition, and TaskSet has resulted in following errors:

    1. NotImplementedError: The create_task_set action has not been implemented

The Service and TaskDefinition has been created successfully though. 

The error makes sense because I am using moto version 1.3.14 that was released in Nov'2019.  It looks like create_task_set feature has been added as recent as two days ago. 

Is there a way I could utilize this new feature or when is this going to be released?

**Comment by bblommers** [comment]
Hi @pinkjosh, a new dev-release is created for every commit to master. You can see the full list here: https://pypi.org/project/moto/#history
The TaskSet feature should be part of moto >= 1.3.15.dev979

**Comment by pinkjosh** [comment]
@bblommers , Thank you for your prompt response on this question.  So is it okay if we start using the devl release instead. I am asking this from the perspective of moto libraries best practices.

**Comment by bblommers** [comment]
Yes, @pinkjosh, it's encouraged to use the dev-releases. There's no defined schedule for official releases, so this is the best way to ensure you have the latest bugfixes/features.

**Comment by pinkjosh** [comment]
Thanks @bblommers  I just tried using following moto releases:

    moto==1.3.15.dev979
    moto==1.3.15.dev984

This time no errors were shown but a message thats basically said the same thing. My console output below:
    

    No Moto CloudFormation support for AWS::ECS::TaskSet
    python3.7/site-packages/moto/cloudformation/parsing.py:330: UserWarning: Tried to parse AWS::ECS::TaskSet but it's not supported by moto's CloudFormation implementation
      resource_type
    No Moto CloudFormation support for AWS::ECS::PrimaryTaskSet
    python3.7/site-packages/moto/cloudformation/parsing.py:330: UserWarning: Tried to parse AWS::ECS::PrimaryTaskSet but 
    it's not supported by moto's CloudFormation implementation
    
    resource_type
    No Moto CloudFormation support for AWS::ECS::TaskSet
    No Moto CloudFormation support for AWS::ECS::PrimaryTaskSet

**Comment by pinkjosh** [comment]
Thank you @bblommers 

No worries.  I tried working with TaskSet through mocked ECS boto3 calls and it appears to be working fine. I will proceed further.  Many thanks for your quick help.
