### ISSUE TITLE
CloudFormation create_stack Fails with Long Stack Name and S3 Bucket in Template

### ISSUE THREAD

**Issue by jweite** [spulec/moto#3168]
The following unit test fails:

`
@mock_cloudformation
def test_boto3_create_stack_s3_long_name():
    cf_conn = boto3.client("cloudformation", region_name="us-east-1")

    stack_name = "MyLongStackName01234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012"

    template = '{"Resources":{"HelloBucket":{"Type":"AWS::S3::Bucket"}}}'

    cf_conn.create_stack(StackName=stack_name, TemplateBody=template)

    cf_conn.get_template(StackName=stack_name)["TemplateBody"].should.equal(
        json.loads(template, object_pairs_hook=OrderedDict)
    )
`

Moto tries to use a bucket name that's longer than the 63 char max.  CloudFormation truncates the StackName portion of the bucket name such that it doesn't exceed the limit.

**Comment by bblommers** [comment]
This was fixed as of moto >= 1.3.15.dev1010
