### ISSUE TITLE
Different ECS behaviors for task-definition with boto3 versus cloudformation

### ISSUE THREAD

**Issue by pinkjosh** [spulec/moto#3171]
Fetching an cloudformation created ECS taskDefinition using moto ecs client includes empty ContainerDefinition.

I have one ECS TaskDefinition created through cloudformation that completes successfully. However, when I use moto ecs client to fetch this task definition, I see empty body for "ContainerDefinition" that I did set in my cloudformation template. I see that internal moto ECS models script does have a proper list retrieved for "ContainerDefinition" but the list is lost somewhere during parsing json response inside this models.py script of ecs. ( I noticed that parser expected camelCase property name in the ContainerDefinition json body whereas it finds PascalCase attributes naming and hence move forward without preparing ContainerDefinition list)

I digged deeper and found out that the ContainerDefinition resource properties has PascalCase namings whereas the parser models.py expected camelCase and hence ends up  pushing empty list for an earlier available ContainerDefinition. 

I then used an actual boto3 call to fetch a physically available TaskDefinition in my account (this TaskDefinition was created through boto3 cloudformation). 

The details of ContainerDefinition json retrieved using moto ecs client and actual boto3 client are provided below:

ContainerDefinition list below when fetching ECS TaskDefinition through actual boto3 ecs client: (camelCase attribute names)

    [{
	    'essential': True,
	    'image': '123456789012.dkr.ecr.us-east-1.amazonaws.com/domain/my-image',
	    'environment': [{
		'name': 'MyEnvironment',
		'value': 'Devl'
	    }, {
		'name': 'serverport',
		'value': '80'
	    }],
	    'healthCheck': {
		'command': ['CMD-SHELL', 'curl -f http://localhost/health || exit 1'],
		'interval': 30,
		'retries': 3,
		'startPeriod': 300
	    },
	    'logConfiguration': {
		'logDriver': 'awslogs',
		'options': {
			'awslogs-group': 'myapp-log-devl',
			'awslogs-stream-prefix': 'Service',
			'awslogs-region': 'us-west-1'
		}
	    },
	    'name': 'myapp-task-def-devl',
	    'portMappings': [{
		'containerPort': '80',
		'protocol': 'tcp'
	    }]
    }] 

ContainerDefinition list below when fetching ECS TaskDefinition through moto ecs client: (PascalCase attribute names)

        [{
	        'Essential': True,
	        'Image': '123456789012.dkr.ecr.us-east-1.amazonaws.com/domain/my-image',
	        'Environment': [{
		    'Name': 'MyEnvironment',
		    'Value': 'Devl'
	        }, {
		    'Name': 'serverport',
		    'Value': '80'
	        }],
	        'HealthCheck': {
		    'Command': ['CMD-SHELL', 'curl -f http://localhost/health || exit 1'],
		    'Interval': 30,
		    'Retries': 3,
		    'StartPeriod': 300
	        },
	        'LogConfiguration': {
		    'LogDriver': 'awslogs',
		    'Options': {
		  	  'awslogs-group': 'myapp-log-devl',
			  'awslogs-stream-prefix': 'Service',
			  'awslogs-region': 'us-west-1'
		    }
	        },
	        'Name': 'myapp-task-def-devl',
	        'PortMappings': [{
		    'ContainerPort': '80',
		    'Protocol': 'tcp'
	        }]
    }] 

Finally, I ran another test and created an ECS TaskDefinition through moto ecs client (no cloudformation) and verified that fetching TaskDefinition created that way returns me ContainerDefinition as expected and attributes have camelCase namings. 

Does moto cloudformation not support ECS TaskDefinition? Do I need to create TaskDefinition using explicit moto ECS client. 

P.S.: I am already using ECS moto client for creation of TaskSets as its not currently supported through moto cloudformation.

My environment:
      
    boto3 Version: 1.14.22
    botocore Version: 1.17.27
    moto Version: 1.3.15.dev979.   ( I am using this version in order to be able to run ecs.create_task_set()

**Comment by bblommers** [comment]
Hi @pinkjosh, thanks for raising this. You're on the money with the camelCase/PascalCase observation. We do store the containerDefinition internally, but we should convert it's properties to lowercase before sending this back to the client.

Marking it as a bug.

**Comment by pinkjosh** [comment]
@bblommers Requesting your comments if there is an update on this one.

**Comment by pinkjosh** [comment]
@bblommers Awesome. I will give it a try.

**Comment by bblommers** [comment]
Should be available as of moto >= 1.3.16.dev64 @pinkjosh
