### ISSUE TITLE
Support --filters option in secretsmanager:ListSecrets

### ISSUE THREAD

**Issue by chriskilding** [spulec/moto#3172]
We should support the new server-side `--filters` option in `secretsmanager:ListSecrets` calls.

Documentation here: <https://docs.aws.amazon.com/cli/latest/reference/secretsmanager/list-secrets.html#options>

One implementation consideration is that AWS sometimes reuse model structures between their APIs. There is a good chance this filter structure, a List of (String key, List\<String\> values), has been used elsewhere. Has this been implemented before in Moto?

**Comment by chriskilding** [comment]
Started implementation in https://github.com/spulec/moto/pull/3173

**Comment by chriskilding** [comment]
Completed :)

**Comment by bblommers** [comment]
This is now part of moto >= 1.3.15.dev1012
