### ISSUE TITLE
Implement ec2.register_image()

### ISSUE THREAD

**Issue by aiell0** [spulec/moto#3176]
# Issue Description
The boto3 function `ec2.register_image()` was not implemented and has the potential to cause loss of code coverage in test suites where it is used.

# Code
```
from moto import mock_ec2
import boto3

@mock_ec2
def register_new_image():
    ec2 = boto3.resource("ec2", region_name="us-east-1")
    response = ec2.register_image(
        Name="sometest",
        Architecture='x64',
        RootDaeviceName='/dev/sda1',
        VirtualizationType='hvm'
    )
    print(response.id)

register_new_image()
```

## Expected Result
`ami-12345678`

## Actual Result
`NotImplementedError: AMIs.register_image is not yet implemented`

## System Information
* boto3-1.14.28
* botocore-1.17.28
* moto-1.3.14 installed using pipenv and using python mocks.

**Comment by bblommers** [comment]
This is implemented by #3177, and is available as of moto >= 1.3.15.dev985
