### ISSUE TITLE
Implement UserId parameter for ModifySnapshotAttribute function.

### ISSUE THREAD

**Issue by aiell0** [spulec/moto#3178]
# Issue Description
The boto3 function `ec2modify_snapshot_attribute()` was not implemented completely and has the potential to cause loss of code coverage in test suites where it is used.

# Code
```
from moto import mock_ec2
import boto3

@mock_ec2
def snapshot_modify_attribute():
    ec2 = boto3.resource("ec2", region_name="us-east-1")
    snapshot = ec2.Snapshot("snap-b230e53a")
    snapshot.modify_attribute(
        Attribute="createVolumePermission",
        OperationType="add",
        UserIds=["123456789123"]
    )

snapshot_modify_attribute()
```

## Expected Result
```
{
    'ResponseMetadata': {
        '...': '...',
    },
}
```

## Actual Result
`moto.ec2.exceptions.MotoNotImplementedError: The UserId parameter for ModifySnapshotAttribute has not been implemented in Moto yet. Feel free to open an issue at https://github.com/spulec/moto/issues`

Don't mind if I do!

## System Information
* boto3-1.14.28
* botocore-1.17.28
* moto-1.3.14 installed using pipenv and using python mocks.

**Comment by bblommers** [comment]
This is now part of moto >= 1.3.15.dev1016
