### ISSUE TITLE
MessageAttributes missing on SNS message

### ISSUE THREAD

**Issue by benkeil** [spulec/moto#3193]
Version: latest

When I send a SNS message the subscriber does not get the MessageAttributes.

```
{
    Type: 'Notification',
    MessageId: 'b09ce1e6-8fbd-472a-972b-120b2212e8a3',
    TopicArn: 'arn:aws:sns:eu-central-1:123456789012:service-grades-stream',
    Subject: 'grades_changed_transformed',
    Message: 'xxxx',
    Timestamp: '2020-07-28T12:19:58.035Z',
    SignatureVersion: '1',
    Signature: 'yyyy,
    SigningCertURL: 'zzz',
    UnsubscribeURL: 'vvv'
  }
```

**Comment by gmcrocetti** [comment]
Hi @benkeil. After some investigation I was able to find a possible bug [here](https://github.com/spulec/moto/blob/fcc85a96453d7aa346ddd43e8fa4cbdf9dd120e9/moto/sns/models.py#L215) - sns -> lambda sending default message attributes (not your case, as it's empty). Can you further clarify which use case originated your problem ?

**Comment by bblommers** [comment]
With the lack of response, I'm going to assume this has been fixed already, so will close it.
Do let us know if there's still an issue here.
