### ISSUE TITLE
NotImplementedError: Filter dicts have not been implemented in Moto for 'instance-state-code'

### ISSUE THREAD

**Issue by aiswaryalakshmi** [spulec/moto#3195]
Can I expect filter dicts implementation for 'instance-state-code' in the near future?

**Comment by bblommers** [comment]
Hi @aiswaryalakshmi, Moto is a community-driven project, so there's no roadmap on what features will be delivered next. Typically people will implement a feature whenever they need this for their own project.

Will mark this as an enhancement.

**Comment by bpandola** [comment]
@aiswaryalakshmi As far as I can tell, this functionality has been available in moto for quite some time.  Can you provide a failing test case?

**Comment by bblommers** [comment]
If this error popped up in EC2.describe_instance_status(), it should be available as of moto >= 1.3.15.dev477, and was implemented in #2764

**Comment by bblommers** [comment]
Going to close this now, as I'm assuming it is working now.
