### ISSUE TITLE
S3 mock makes SimpleDB not work

### ISSUE THREAD

**Issue by dekked** [spulec/moto#32]
Apart from using S3 and DynamoDB, I am also using SimpleDB. During the unit tests I have enabled mocks for S3 and DynamoDB - but that made SimpleDB stop working.

Here is a snippet to reproduce the problem:

```python
import boto
from moto import mock_s3

mock = mock_s3()
mock.start()

sdb = boto.connect_sdb()
domain = sdb.get_domain('domain_name')
```

The call to *get_domain* makes boto fail with a **BadStatusLine** exception, but I am unsure why because moto shouldn't affect SimpleDB (AFAIK there is no support for it yet).

**Comment by spulec** [comment]
Going to close this in favor of #303
