### ISSUE TITLE
SNS KmsMasterKeyId not returned as part of get_topic_attributes response

### ISSUE THREAD

**Issue by hanjb** [spulec/moto#3216]
when sns mock is used to get topic attributes:

`response = client.get_topic_attributes(
    TopicArn='string'
)`

KmsMasterKeyId - The ID of an AWS-managed customer master key (CMK) for Amazon SNS or a custom CMK - is not included as part of the response.

**Comment by bblommers** [comment]
Thanks for raising this @hanjb - marking this as an enhancement

**Comment by bblommers** [comment]
This is now part of moto >= 1.3.16.dev68
