### ISSUE TITLE
External Hostname

### ISSUE THREAD

**Issue by benkeil** [spulec/moto#3223]
Version: master

I add via terraform a lambda function with an environment variable to a queue that gets also created via terraform. The queue url is then `http://localhost:5000/123456789012/componenttest_rcsws_generate_feed` which is not resolvable from inside the lambda function. I guess I need to set it to the internal IP of the host that runs the tests (e.g. `http://156.195.56.12:5000/123456789012/componenttest_rcsws_generate_feed`).

Is it possible to change the external displayed hostname?

**Comment by bblommers** [comment]
I'm going to assume this was resolved - let  us know if there are still any issues @benkeil
