### ISSUE TITLE
DynamoDB: Update item doesn't validate against attributes

### ISSUE THREAD

**Issue by meshuamam** [spulec/moto#3231]
Might be related to https://github.com/spulec/moto/issues/2396

Moto doesn't return an error when using putting the wrong attribute type.

Example:
When updating an attribute defined as:
```
table = dynamodb.create_table(
    ...
    AttributeDefinitions = [{
        'AttributeName': 'this_is_a_number',
        'AttributeType': 'N'
    }]
)
```
with "put item", using a string value such as "123123jkasdfsdf", moto doesn't return a 400 with a client error.

Expected:
"400 status" and a "The parameter cannot be converted to a numeric value" message (or similar)

Actual: 
2xx status

Version: 1.3.15.dev1023
Using through pynamodb
Installed as a mock, boto versions:
boto3==1.14.30  
boto==2.48.0   
botocore==1.17.30

**Comment by bblommers** [comment]
Thanks for raising this @meshuamam - marking this as an enhancement
