### ISSUE TITLE
verify_email_address doesn't allow sending mails

### ISSUE THREAD

**Issue by kam193** [spulec/moto#3240]
When I verify email using `verify_email_address`, it's not enough to send email - SESBackend respects only `verify_email_identity`.

How to reproduce:
```
conn = boto3.client("ses")
conn.verify_email_address(EmailAddress="sender@example.com")
# conn.list_verified_email_addresses() now have `sender@example.com`
conn.send_email(
        Destination={
            "ToAddresses": ["recipient1@example.com", "recipient2@example.com",],
        },
        Message={
            "Body": {
                "Html": {
                    "Charset": "UTF-8",
                    "Data": 'This message body contains HTML formatting.',
                },
                "Text": {
                    "Charset": "UTF-8",
                    "Data": "This is the message body in text format.",
                },
            },
            "Subject": {"Charset": "UTF-8", "Data": "Test email",},
        },
        Source="sender@example.com",
    )
```

This raises:
```
botocore.errorfactory.MessageRejected: An error occurred (MessageRejected) when calling the SendEmail operation: Email address not verified sender@example.com
```

It's occurred because of how SESBackend works. The verifing emails is handled:
https://github.com/spulec/moto/blob/9894e1785a610f1dd8c9bfce1fa416692b3e0c2f/moto/ses/models.py#L113-L115

But when it checks sender email, it uses:
https://github.com/spulec/moto/blob/9894e1785a610f1dd8c9bfce1fa416692b3e0c2f/moto/ses/models.py#L102-L107

where `addresses` is filled by `verify_email_identity` only.

**Comment by bblommers** [comment]
This is now part of moto >= 1.3.15.dev1028
