### ISSUE TITLE
mock_cognitoidp: The initiate_auth action has not been implemented

### ISSUE THREAD

**Issue by ChrisDSky** [spulec/moto#3241]
Hello,

moto version: 1.3.14

I am trying to create a mock-up of a cognito user pool in order to mimic authenticating an user and accessing groups and privileges.

I have created my user_pool and user_pool_client, however when I try to call initiase_auth, on the Cognito Client, I always get the exception:
Unknown Exception: The initiate_auth action has not been implemented

This is how I create the user pool:
```
    create_pool_kwargs = {
        "PoolName": "test_pool",
        "Schema": [
            {
                "Name": "email",
                "AttributeDataType": "String",
                "Required": True,
                "Mutable": True,
            }
        ],
        "AdminCreateUserConfig": {
            "AllowAdminCreateUserOnly": True,
            "UnusedAccountValidityDays": 1,
        },
    }

    user_pool = cognito_client.create_user_pool(**create_pool_kwargs)
```

This is how I create the user pool client:

```
    create_pool_kwargs = {
        "UserPoolId": user_pool_id,
        "ClientName": "test_pool_client",
        "ExplicitAuthFlows": [
            "ALLOW_CUSTOM_AUTH",
            "ALLOW_USER_PASSWORD_AUTH",
            "ALLOW_USER_SRP_AUTH",
            "ALLOW_REFRESH_TOKEN_AUTH",
            "ALLOW_ADMIN_USER_PASSWORD_AUTH"
        ]
    }

    user_pool_client = cognito_client.create_user_pool_client(**create_pool_kwargs)
```

Those 2 work fine.

However, I then create a random user:

```
        response = cognito_client.admin_create_user(
            UserPoolId=user_pool_id,
            Username="test",
            TemporaryPassword="temp_password",
            MessageAction='SUPPRESS'
        )
```

At that point, I have managed to get an user created.

However, I need to authenticate them straight away, and add them to groups, therefore, I call that piece of code:

```
                auth_parameters = {
                   "USERNAME": username,
                   "PASSWORD": password
                }

                response = cognito_client.initiate_auth(AuthFlow="USER_PASSWORD_AUTH",
                                                        ClientId=user_client_id,
                                                        AuthParameters=auth_parameters)
```

That call to initiate_auth gives me "The initiate_auth action has not been implemented"

Is it that Moto hasn't implemented that functionality yet ?

Thank you for future response.

Kind Regards,

Chris

**Comment by bblommers** [comment]
Hi @ChrisDSky, correct, that feature is not yet implemented. Will mark this as an enhancement in case somebody wants to submit a PR.

**Comment by ChrisDSky** [comment]
@bblommers , Thank you for your response. Good to know, I will keep it in mind :-).

Hopefully will be implemented soon. I love Moto :-)

**Comment by dmtmov** [comment]
+1 interested in this feature :)

**Comment by bblommers** [comment]
This has been part of moto as of 1.3.15.dev1037. Will close this, but let us know if there are still issues with this feature.
