### ISSUE TITLE
Proposal: store send SNS notifications

### ISSUE THREAD

**Issue by kam193** [spulec/moto#3252]
Since `moto` is a mock of original service for testing, it could be useful to have possibility to store messages sent to a topic and allow read them later. In my case, I have two systems that communicate via SNS notifications, and during unit tests of one system we would like to check that notification is sent. Currently, `moto` doesn't allow read notifications in other way as subscribing to them, which requires e.g. creating SQS queue or so. It's possible, but it makes tests more complex without need.

I propose to implement solution similar to SES, where moto stores sent emails in the backend [[1]](https://github.com/spulec/moto/blob/dcde2570b16cbe5183b358531faddcfe2c2b5a56/moto/ses/models.py#L144) and you can later import `ses_backend` and check them. `SNSBackend` or `Topic` could do the same e.g. by having `sent_notifications` property.

**Comment by spulec** [comment]
That makes sense to me. I would be in favor of that.

Marking as an enhancement.
