### ISSUE TITLE
Enhance mock_iot to support describe_endpoint and register_certificate_without_ca

### ISSUE THREAD

**Issue by zhil3** [spulec/moto#3275]
We wanna enhance the moto framework by adding two functions in **iot_mock** module.

Currently **describe_endpoint** and **register_certificate_without_ca** are what we need, and probably there will be more coming but depends on what we wanna implement in near future.

I have a branch already implemented the describe_endpoint with unittest working as well. 
Now working on register_certificate_without_ca. 

What we want is that we could push a branch so that we could git clone it in our pipeline, and have PR reviewed/merged as soon as possible that we don't have to keep a repo in our pipeline always.

Thank You.

**Comment by zhil3** [comment]
register_certificate_without_ca  is done with unittest as well

**Comment by bblommers** [comment]
Hi @zhil3, thanks for raising this. 

PR's are always welcome!

**Comment by zhil3** [comment]
@bblommers Thanks for the reply. But I don't have permission to push a branch thus how to raise the PR?

**Comment by zhil3** [comment]
Thanks @bblommers for the info. 
And could you please help up speedy up the PR process by any chances? 
We are kind of in an urgent status of using those functions inside our pipelines.

Thank You
