### ISSUE TITLE
[feature] allow lambda to run with podman as an alternative to docker

### ISSUE THREAD

**Issue by yuvalif** [spulec/moto#3276]
* allows you to containers not as root
* cgroups v2
* better support on centos8/fedora OSs

should be an alternative, and not a replacement, as docker is more widespread than podman

**Comment by bblommers** [comment]
Hi @yuvalif, thanks for raising this. Hadn't heard of Podman before. 

Is there a specific use case for Lambdas where Podman would give a noticable improvement? From what I can read, it would behave exactly the same in our limited use case. (I.e., run t he container, execute some python code and return the result.)

**Comment by yuvalif** [comment]
the main improvement is around installation and setup of docker (especially in case of centos8/fedora OSs), as well as the fact that non-privileged containers don't need root permissions in podman.
don't think there is functional advantage.

**Comment by yan12125** [comment]
I give it a try, and get blocked as Podman hasn't implemented all Docker APIs. After some patches to moto and docker-py, the blocker comes to the `put_archive` function [1][2].

I'm interested in this as I'm maintaining the Arch Linux package and I'd like to run the test suite of moto without extra privileges.

[1] https://github.com/spulec/moto/blob/9f0f230d130a839fb2de6bfc97af4182360fbcdb/moto/awslambda/models.py#L135
[2] https://github.com/containers/podman/issues/6050

**Comment by yan12125** [comment]
Podman 3.0 supports all needed Docker APIs, and only a few changes are needed in moto => #3702

**Comment by bblommers** [comment]
This is now supported in moto >= 1.3.17.dev276
