### ISSUE TITLE
KeyError when trying to query a table having GlobalSecondaryIndexes

### ISSUE THREAD

**Issue by lowdesertpunk** [spulec/moto#329]
The test introduced in lowdesertpunk/moto@1b95be35925cdba6d668e78c07106a3041b43d7f fails with a `KeyError` because it's trying to [use the primary key](https://github.com/spulec/moto/blob/0ca3b7f69dc3189abcb6d5725e85229e81af47d3/moto/dynamodb2/responses.py#L224) of the table defined in `KeySchema`

**Comment by spulec** [comment]
Thanks for opening the ticket!

I think this fix was sufficient. Feel free to reopen if it isn't.
