### ISSUE TITLE
Fails to install cryptography for `moto-1.3.15`

### ISSUE THREAD

**Issue by jamesgunnfiveai** [spulec/moto#3290]
Inside a python:3.8-slim docker container, `pip install moto` does not install `cryptography` on the latest moto release (moto-1.3.15). This causes subsequent commands to fail with `ModuleNotFoundError: No module named 'cryptography'` when invoking `moto` mocks.

To see this, jump into a fresh docker:
`docker run --rm -it python:3.8-slim /bin/bash`

Then inside run:
```
pip install moto
pip list
```
And note that `cryptography` is not installed.

Now run:
```
pip install moto==1.3.14
pip list
```

And note that `cryptography` is now installed.

An example of the failures seen when using the new release (ie. having only run `pip install moto`):
```
/usr/local/lib/python3.8/site-packages/moto/iam/__init__.py:2: in <module>
    from .models import iam_backend
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    from __future__ import unicode_literals
    import base64
    import hashlib
    import os
    import random
    import string
    import sys
    from datetime import datetime
    import json
    import re
    
>   from cryptography import x509
E   ModuleNotFoundError: No module named 'cryptography'

/usr/local/lib/python3.8/site-packages/moto/iam/models.py:12: ModuleNotFoundError
```

**Comment by ffe4** [comment]
Yup, encountered this issue as well while running a GitHub Actions test pipeline.

**Comment by bblommers** [comment]
Hi @jamesgunnfiveai, @ffe4, this is due to an attempt to reduce the number of dependencies in moto.
By default, moto only comes with the absolute basic set of dependencies. As `cryptography` is only required in acm, ec2 and iam, this dependency will only be installed explicitly when calling `pip install moto[ec2]`.

If you have multiple services and don't want to go through the trouble of specifying a list of services, you can use all dependencies:
`pip install moto[all]`

Relevant PR: https://github.com/spulec/moto/pull/3281/files

**Comment by jvtm** [comment]
AFAICT trying to use S3 `create_bucket()` triggers this error, via `moto/core/responses.py:141: in _authenticate_and_authorize_s3_action`.

**Comment by bblommers** [comment]
The linked PR adds some documentation on why this error occurs, and how to resolve it. Hopefully that clears things up - if not please let me know

**Comment by nigelmcnie** [comment]
Hi, just noting I ran into this earlier today when trying to mock just s3 and sqs. Based on the stack traces I was getting, I think I would have needed the awslambda dependency, and possibly the ec2 dep as well, which wasn't clear to me. My app doesn't use lambda or ec2. My temporary fix was to downgrade to 1.3.14, but I suspect that using moto[all] or moto[ec2,awslambda] in requirements.txt would have also worked.

I wonder if there's now a deeper issue here of an unclear relationship between the deps you declare and the services you use?

**Comment by bblommers** [comment]
> 
> 
> AFAICT trying to use S3 `create_bucket()` triggers this error, via `moto/core/responses.py:141: in _authenticate_and_authorize_s3_action`.

True @jvtm - just did some testing in that area. There's a bug where, in order to get S3 to work, you'd have to install dependencies for IAM. (So either `pip install moto[iam]` or `pip install moto[all]`.)

Will propose a fix shortly.

**Comment by jamesgunnfiveai** [comment]
Thanks all, can confirm it's the S3 issue that I'm hitting. The error in the bug report is triggered when trying to create a bucket (which I should have included on the original report, apologies).

Sounds like fixing the hidden S3 dependency on IAM will solve this bug for me.

**Comment by walkingpendulum** [comment]
I had the same error, `No module named 'cryptography'`. Switching from `pip install moto[server]` to `pip install moto[all]` made cryptography error gone, but now it raises `No module named 'flask'` :(

**Comment by RonRothman** [comment]
> this is due to an attempt to reduce the number of dependencies in moto.

@bblommers First of all, thank you for moto and for being sensitive to the number of dependencies it has. Much appreciated.

Like several others here, this change broke our builds. We (naively?) assume that projects only introduce breaking changes on major releases. Have you considered semver for moto? If you have and have decided against it, could you offer some guidance on how tightly we should depend on versions of moto, if we want to avoid similar breakages in the future. E.g., should we pin to a particular patch version?

**Comment by spulec** [comment]
This was unintentional. Apologies.

Things should be back to before with the newly released `1.3.16`.

**Comment by RonRothman** [comment]
Thanks for the quick fix. 👍

**Comment by davidszotten** [comment]
@spulec could you clarify if the issue is the missed s3 dependency on iam or that this was landed in a minor version release?

**Comment by jamesgunnfiveai** [comment]
Thanks for the speedy fix folks.

@davidszotten - if you look to https://github.com/spulec/moto/commit/ed9668107847233ec6f695a494269825e01ba932 you'll see that the dependency clean up was reverted for the 1.3.16 release, indicating the issue was landing the dependency changes in a patch release. Discussion on https://github.com/spulec/moto/pull/3293 indicates a future release will be made with a greater (major?) version bump for the dependency changes.
