### ISSUE TITLE
No module named 'yaml' for `moto-1.3.15`

### ISSUE THREAD

**Issue by arnaudh** [spulec/moto#3294]
Related to https://github.com/spulec/moto/issues/3290

Our CI build caught this error.
To reproduce:

```
$ python --version
Python 3.8.2
$ pip install moto
...
$ python -c 'from moto import cloudformation'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/arnaudhenry/.pyenv/versions/test-3.6.10/lib/python3.8/site-packages/moto/cloudformation/__init__.py", line 2, in <module>
    from .models import cloudformation_backends
  File "/Users/arnaudhenry/.pyenv/versions/test-3.6.10/lib/python3.8/site-packages/moto/cloudformation/models.py", line 4, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```

I understand this is because `moto-1.3.15` requires us to be explicit about some sub-dependencies (https://github.com/spulec/moto/issues/3290#issuecomment-688451034)

I fixed the above issue by running `pip install moto[all]` (we mock several AWS services, so didn't want to pick individual sub-dependencies).

Shouldn't this be considered a breaking change in the API, and so be reflected in the moto version i.e. `moto-2.0.0`?

**Comment by spulec** [comment]
This was unintentional. Apologies.

Things should be back to before with the newly released `1.3.16`.

**Comment by arnaudh** [comment]
Thank you @spulec.
I've already changed our dependency to be `moto[all]`, is it ok for us to use that instead of `moto` for the future?

**Comment by spulec** [comment]
@arnaudh yes! That is what we will ask everyone to do going forward after a more major release. In the meantime, I have made it so that `moto` and `moto[all]` both work.

**Comment by George-Lee** [comment]
Hi, this issue seems to have reappeared with moto 2.0.5

**Comment by bblommers** [comment]
@George-Lee Are you following the new installation method for 2.x, `pip install moto[service]`?

https://github.com/spulec/moto/issues/3722

**Comment by George-Lee** [comment]
Mea culpa, I must have missed that. Never mind! 😄
