### ISSUE TITLE
Don’t make breaking changes on a dot release

### ISSUE THREAD

**Issue by teotwaki** [spulec/moto#3295]
The latest .15 release has broken a bunch of projects I am currently working on. PRs that passed CI yesterday failed today after being merged.

Moto is a fantastic library, thus changing how dependencies are managed and introducing breaking changes in APIs that in a lot of cases are only used to mock the environment (bucket creation) is a surprising decision.

Might I suggest adopting something like semantic versioning to prevent these kind of issues in the future? Alternatively, is it the project's recommendation to hardcode the specific version we depend against, instead of >=,<?

**Comment by spulec** [comment]
This was unintentional. Apologies.

Things should be back to before with the newly released `1.3.16`.

**Comment by teotwaki** [comment]
Thank you for prioritising this @spulec. Very much appreciated!
