### ISSUE TITLE
moto vs flask/socketserver

### ISSUE THREAD

**Issue by memory** [spulec/moto#330]
I was _delighted_ to discover moto, but am running into some ugly issues trying to use it for our project, which is a Flask-restful application backed by S3 and DynamoDB.

Moto very successfully mocks out the boto.s3 and dynamodb calls when running unit tests on individual functions, but if we try to test the actual API endpoints of the app while using the mocked backends, terrible things happen:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/vagrant/target/python/local/lib/python2.7/site-packages/werkzeug/serving.py", line 602, in inner
    passthrough_errors, ssl_context).serve_forever()
  File "/vagrant/target/python/local/lib/python2.7/site-packages/werkzeug/serving.py", line 462, in serve_forever
    HTTPServer.serve_forever(self)
  File "/usr/lib/python2.7/SocketServer.py", line 238, in serve_forever
    self._handle_request_noblock()
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    request, client_address = self.get_request()
  File "/vagrant/target/python/local/lib/python2.7/site-packages/werkzeug/serving.py", line 475, in get_request
    con, info = self.socket.accept()
  File "/usr/lib/python2.7/socket.py", line 203, in accept
    return _socketobject(_sock=sock), addr
TypeError: __init__() got an unexpected keyword argument '_sock'
```

(platform: ubuntu trusty, python 2.7.6)

Are we swimming against the tide by trying to do this all in-app?  We could set up a pair of moto-servers, but that seems like it would make for a much more complicated and fragile test harness.

**Comment by spulec** [comment]
It certainly should not be swimming against the tide to do this.

It looks like HTTPretty is interfering with Werkzeug. HTTPretty patches `_socketobject`, but it appears that the object it is using to patch does not have the same `__init__` arguments as the real `_socketobject`.

If I get some time later in the week, I'll try to take a deeper look. If you want to take a shot, I would try adding a `_sock` argument to the HTTPretty [`fakesock.socket.__init__`](https://github.com/gabrielfalcao/HTTPretty/blob/691865d48bf322111a2f80731563b3b05ce76318/httpretty/core.py#L251)

**Comment by memory** [comment]
Yeah, I got that far down the rabbit hole since filing the issue: socket._socketobject and httpretty.fakesocket.socket have different init signatures.

Socket._socketobject.accept() is what consumes _sock as an argument:

```
    201     def accept(self):
    202         sock, addr = self._sock.accept()
    203         return _socketobject(_sock=sock), addr
```

...and neither passing that on to accept() unmodified nor replacing it with another fakesocket (with the same kwargs) produced a working server-- but this is my first time spelunking in python's socket code, so hopefully this is more obvious than it appears to me.

**Comment by spulec** [comment]
I started to dig a bit more into this, but was not able to recreate easily.

[This script](https://gist.github.com/spulec/14cdbbb4170000841bd6) seems to work for me with Moto master and httpretty==0.8.7. Any idea what is different between that script and your circumstance?

**Comment by ZsoltFabok** [comment]
I got the same issue when using SimpleHttpServer:

````python
 httpd_handler = TestServer
 httpd = SocketServer.TCPServer(('127.0.0.1', 18019), httpd_handler)
 httpd_thread = Thread(target=httpd.serve_forever)
 httpd_thread.setDaemon(True)
 httpd_thread.start()
````

**Comment by memory** [comment]
@ZsoltFabok thanks, that neatly saved me some effort factoring out a repeatable case :)

**Comment by spulec** [comment]
Some of this may be related to https://github.com/gabrielfalcao/HTTPretty/issues/209

**Comment by ZsoltFabok** [comment]
I'm not sure, because I tried different HTTPretty versions

**Comment by ZsoltFabok** [comment]
What I've figured out so far that one of the dependencies of moto may do something to `socket.py` because the error message suggests that it calls` __init__` with an unknown argument but the `socket.py`'s `__init__` has that argument.

**Comment by garrickp** [comment]
:+1: hitting this as well, trying to run a test server with boto connections mocked out.

**Comment by benjolitz** [comment]
I've been bitten by this issue today. I thought I broke my app completely, but now I can see that this is known.

**Comment by japo32** [comment]
Same here.

**Comment by SeanHayes** [comment]
This might be fixed now, try upgrading to the latest version of httpretty (httpretty>=0.8.14).

**Comment by japo32** [comment]
@SeanHayes , I'm hitting a different error with 0.8.14 :(
https://github.com/spulec/moto/issues/548

**Comment by spulec** [comment]
Is anyone still having this particular issue after upgrading to httpretty>=0.8.14. If not, I will close.

**Comment by maurodoglio** [comment]
This issue seems to be gone with httpretty==0.8.14 👍

**Comment by spulec** [comment]
Great.

If you are still having this issue, please use the `master` branch of moto and boto3. If that doesn't work, feel free to reopen.
