### ISSUE TITLE
Filter for tags not implemented on ec2 DescribeAddresses

### ISSUE THREAD

**Issue by wbwork** [spulec/moto#3309]
EC2 API allows to filter on tags for DescribeAddresses. For Moto this is not implemented yet. PR is in preparation.

### How to reproduce

```
    client = boto3.client('ec2')
    alloc_tags = client.allocate_address(Domain='vpc')
    client.create_tags(Resources=[alloc_tags['AllocationId']], Tags=[{'Key': 'ManagedBy', 'Value': 'MyCode'}])
    addresses = client.describe_addresses(Filters=[
        {'Name': 'domain', 'Values': ['vpc']},
        {'Name': 'tag:ManagedBy', 'Values': ['MyCode']}
    ])
    len(addresses).should.equal(1)
```

### What you expected to happen
Test succeeds

### What actually happens
moto.ec2.exceptions.FilterNotImplementedError: The filter 'tag:ManagedBy' for DescribeAddresses has not been implemented in Moto yet.

### Versions
Name: moto
Version: 1.3.15.dev0

Name: boto
Version: 2.49.0

Name: boto3
Version: 1.14.59

Name: botocore
Version: 1.17.59

**Comment by bblommers** [comment]
This is now part of moto >= 1.3.16.dev34
