### ISSUE TITLE
get_all_security_groups() doesn't return default SecurityGroup

### ISSUE THREAD

**Issue by endemics** [spulec/moto#331]
In http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-network-security.html#default-security-group, AWS states that there is a default SecurityGroup per region in classic.

However, Moto does not seem to report this default securitygroup:

reference boto code:

    >>> import boto.ec2
    >>> 
    >>> conn = boto.ec2.connect_to_region('us-east-1')
    >>> res = conn.get_all_security_groups()
    >>> len(res)
    1
    >>> print res[0]
    SecurityGroup:default

with moto:

    >>> import boto.ec2
    >>> from moto import mock_ec2
    >>> 
    >>> mock = mock_ec2()
    >>> mock.start()
    >>> conn = boto.ec2.connect_to_region('us-east-1')
    >>> res = conn.get_all_security_groups()
    >>> len(res)
    0

However, trying to create the default group fails with the error I would expect it the group was already created:

    >>> conn.create_security_group(name='default', description='default group')
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/gildas/virtenv/env.aws/local/lib/python2.7/site-packages/boto/ec2/connection.py", line 3003, in create_security_group
        SecurityGroup, verb='POST')
      File "/home/gildas/virtenv/env.aws/local/lib/python2.7/site-packages/boto/connection.py", line 1207, in get_object
        raise self.ResponseError(response.status, response.reason, body)
    boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
    <?xml version="1.0" encoding="UTF-8"?>
      <Response>
        <Errors>
          <Error>
            <Code>InvalidGroup.Duplicate</Code>
            <Message>The security group 'default' already exists</Message>
        
          </Error>
        </Errors>
      <RequestID>7a62c49f-347e-4fc4-9331-6e8eEXAMPLE</RequestID>
    </Response>

**Comment by spulec** [comment]
Thank you for reporting this!

Yes, you are correct. We had some code that would create the default group if you asked for it, but that strategy clearly has the flaws you demonstrated here. This should now be fixed with https://github.com/spulec/moto/commit/6c9bba2ca1813e3ff8336b594058115df009486d. Feel free to reopen if it was not sufficient.

**Comment by endemics** [comment]
Hi, thanks (with a bit of delay due to holidays :))

I haven't been able to test yet, however I've noticed in your diff that your comment for the default group is  'The default security group'.

Not sure if that's always the case or even if it should be raised as a separate issue, but in my case the default group comment is 'default group' instead. I guess that moto's behaviour should mimic the real behaviour and hence have the comment changed to 'default group'?

**Comment by spulec** [comment]
Yes, updated with https://github.com/spulec/moto/commit/bdfbdd8b1c17f528b0b3fa3a8c6cc2b7fd7406b1. Thanks!
