### ISSUE TITLE
S3 DeleteObject operation doesn't return x-amz-* headers

### ISSUE THREAD

**Issue by lsutic** [spulec/moto#3312]
The S3 DeleteObject operation should (when applicable) return `x-amz-*` headers. In particular `x-amz-version-id` and `x-amz-delete-marker`: https://docs.aws.amazon.com/AmazonS3/latest/API/API_DeleteObject.html

Moto doesn't.

See: https://github.com/spulec/moto/pull/3313 for fix

**Comment by bblommers** [comment]
Thanks again for raising this, and providing a PR, @lsutic. 

This should now be part of moto >= 1.3.16.dev6
