### ISSUE TITLE
RDS Instance, can't connect to the Database

### ISSUE THREAD

**Issue by ChrisDSky** [spulec/moto#3319]
Hello,

I am trying to create a DB Instance and connect to it via pymysql (or any other library to achieve it is welcomed).

I manage to create the DB Instance via create_db_instance, and here is the response from it:

` {'DBInstances': [{'DBInstanceIdentifier': 'test', 'DBInstanceClass': 'db.m1.small', 'Engine': 'postgres', 'DBInstanceStatus': 'available', 'MasterUsername': 'test', 'Endpoint': {'Address': 'test.aaaaaaaaaa.us-east-1.rds.amazonaws.com', 'Port': 1234}, 'AllocatedStorage': 10, 'InstanceCreateTime': datetime.datetime(2020, 9, 16, 11, 57, 21, 576000, tzinfo=tzutc()), 'PreferredBackupWindow': '03:50-04:20', 'BackupRetentionPeriod': 1, 'DBSecurityGroups': [], 'VpcSecurityGroups': [], 'DBParameterGroups': [{'DBParameterGroupName': 'default.postgres9.3', 'ParameterApplyStatus': 'in-sync'}], 'PreferredMaintenanceWindow': 'wed:06:38-wed:07:08', 'MultiAZ': False, 'EngineVersion': '9.3.3', 'AutoMinorVersionUpgrade': False, 'ReadReplicaDBInstanceIdentifiers': [], 'LicenseModel': 'None', 'OptionGroupMemberships': [{'OptionGroupName': 'default.postgres9.3', 'Status': 'in-sync'}], 'PubliclyAccessible': False, 'StatusInfos': [], 'StorageType': 'gp2', 'StorageEncrypted': False, 'DbiResourceId': 'db-M5ENSHXFPU6XHZ4G4ZEI5QIO2U', 'CopyTagsToSnapshot': False, 'DBInstanceArn': 'arn:aws:rds:us-east-1:1234567890:db:test', 'IAMDatabaseAuthenticationEnabled': False}], 'ResponseMetadata': {'RequestId': '523e3218-afc7-11c3-90f5-f90431260ab4', 'HTTPStatusCode': 200, 'HTTPHeaders': {'server': 'amazon.com'}, 'RetryAttempts': 0}}
`

But when I try to connect to it via pymysql library, it can't and keep spitting out `(2003, "Can't connect to MySQL server on 'test.aaaaaaaaaa.us-east-1.rds.amazonaws.com' ([Errno 8] nodename nor servname provided, or not known)")
`

Here is how I try to connect to it :

`pymysql.connect(
            host='test.aaaaaaaaaa.us-east-1.rds.amazonaws.com',
            port=1234,
            user='test',
            password='test',
            cursorclass=pymysql.cursors.DictCursor,
            db="test")`

Is it a limitation of Moto, or is it me who isn't doing it correctly ?

I am running Python 3.7.8

If I try to do 
`pymysql.connect(host='127.0.0.1', user='test', db='test')`, I get:

`(2003, "Can't connect to MySQL server on '127.0.0.1' ([Errno 61] Connection refused)"`

Thank you.

Chris

**Comment by bblommers** [comment]
Hi @ChrisDSky, Moto endeavours to mimick the AWS SDK only, to mock out any calls during unit tests - we don't create/mock any actual servers.

If you need an actual server and run an integration test against that, that would be outside the scope of Moto.

**Comment by ChrisDSky** [comment]
@bblommers , thanks for the response.

Correct me if I am wrong, but Moto can be started up as a Server....so wouldn't it then emulate a SQL database inside that server ?

**Comment by bblommers** [comment]
MotoServer allows people to mock SDK's in different languages (NodeJS, etc), by explicitly setting the endpoint-url in the respective SDK. 
For python it would look like this:
`boto3.client('s3', endpoint_url="http://motoserver:5000/")`

The functionality remains the same though, it's just a different entrypoint (standalone server vs in-memory decorators)

**Comment by ChrisDSky** [comment]
@bblommers , Ok thanks for the clarification. Still great work for Moto :-)

**Comment by kostaleonard** [comment]
As a long time user of Moto for mocking S3, I was also surprised to encounter this issue. The S3 implementation allows you to read from and write to the mocked filesystem with no problem, but RDS offers no database functionality. I would be very pleased if we added this feature as long as it is not too cumbersome. I'd love to contribute but probably can't right now, maybe I can put something together later this year.

**Comment by bblommers** [comment]
Hi @kostaleonard, reading and writing to a filesystem is a lot easier with plain Python :)

There are two ways to implement the database functionality, as far as I can see:
 - Write our own RDS server + parsers for each SQL dialect
 - Start a Docker-image that exposes the database (Postgres, Mysql, etc.)

The first option would be way too complicated. The second option goes against the idea of Moto as a simple, lightweight mocking tool. It would also complicates things for Aurora-users, because as far as I know, there is no way to download the Aurora engine and run it locally.

If you really need this functionality, I would suggest looking into LocalStack instead. They run on top of Moto, so they expose all the functionality that we offer, but also expose RDS instances to connect to. Granted, it has a bigger footprint in resource consumption and engineering effort, but it is better suited for integration style tests where you want to create an RDBMS and connect to it.

**Comment by kostaleonard** [comment]
@bblommers thanks for the recommendation, and you make good points. I see that it may be beyond the scope of Moto to implement database functionality, but maybe one day Moto will solve all of my problems. My pain point was likely just that I spent hours trying to connect to a non-existent database and I assumed based on the S3 implementation that there was robust mocking for all supported services. If I can figure out a way to alleviate that pain point for other users, I'll put in a PR.
