### ISSUE TITLE
IoT Core register_certificate_without_ca behavior doesn't match boto3

### ISSUE THREAD

**Issue by BenD10** [spulec/moto#3320]
**moto version:** 1.3.6
**boto3 version:** 1.14.60
Moto is installed via pipenv and used with pytest.

When using boto3, trying to use the [register_certificate_without_ca](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/iot.html#IoT.Client.register_certificate_without_ca) endpoint, trying to register a certificate that already exists will throw an exception.

```
An error occurred (ResourceAlreadyExistsException) when calling the RegisterCertificateWithoutCA operation: The certificate is already provisioned or registered
```

In moto, trying to register the same certificate twice will not result in this exception. I believe this exception is important for robustness testing.

Please let me know what you think, I'd be more than happy to submit a match for this before the end of the week if you agree.

**Comment by bblommers** [comment]
Hi @BenD10, thanks for raising this. Will mark this as an enhancement.

PR's are always welcome! FYI, this was the original PR that added the endpoint - might come in handy as a starting point: https://github.com/spulec/moto/pull/3279/files

**Comment by bblommers** [comment]
This is now part of moto >= 1.3.16.dev25
