### ISSUE TITLE
Moto generates incorrect certificate id for IoT Core

### ISSUE THREAD

**Issue by BenD10** [spulec/moto#3321]
**moto version:** 1.3.6
**boto3 version:** 1.14.60
Moto is installed via pipenv and used with pytest.

This is where moto generates the IoT certificate id:
https://github.com/spulec/moto/blob/master/moto/iot/models.py#L133

AWS actually generates this certificate ID by getting the SHA256 of the certificate in DER format. I've found this via https://stackoverflow.com/questions/55847788/how-does-aws-iot-generate-a-certificate-id and confirmed with an AWS support ticket. 

Part of our app relies on being able to deterministically generate the certificate ID, which currently is not possible to test with moto.

Please let me know what you think, I'd be more than happy to submit a match for this before the end of the week if you agree.

**Comment by bblommers** [comment]
Sounds good to me @BenD10 - looking forward to a PR! Let me know if you need any help with this.

**Comment by bblommers** [comment]
This is now part of moto >= 1.3.16.dev25
