### ISSUE TITLE
moto server dashboard 500 from data.json resource

### ISSUE THREAD

**Issue by wallowa** [spulec/moto#3322]
**How to reproduce the bug**: run moto docker in server mode and go to http://localhost:5000/moto-api/.
**Expected**: dashboard page with service status and available AWS resources (e.g., S3 objects).
**What happens**: visit http://localhost:5000/moto-api/ and get a mostly empty page (except for tabs at the top). Inspecting the page shows that /moto-api/data.json returns a 500. curl GET against that resource also returns a 500.
**Version**: Server mode using https://hub.docker.com/r/motoserver/moto latest (digest ef4e4172daf2) using docker-compose on the default port (5000). Passing MOTO_SERVICE="ec2 sns sqs s3"

**Comment by bblommers** [comment]
Hi @wallowa, can you share you docker-compose file? I can't seem to be able to reproduce it

I did find a bug where the `data.json` call returns a mostly empty list, but it does return a 200 for me.

**Comment by wallowa** [comment]
Thank you for the quick response. It turns out it was triggered by passing a bad policy json when subscribing an sqs queue to sns, though using a policy appears to be unnecessary in moto so I just removed it.
