### ISSUE TITLE
Support for IAM Policies on CloudFormation

### ISSUE THREAD

**Issue by apranav19** [spulec/moto#3324]
It seems that Moto's CloudFormation service does not support IAM::ManagedPolicy or IAM::Policy.

When I execute a create_stack operation on a CloudFormation template that creates and exports an IAM::ManagedPolicy, I see the following warnings & errors:

Warnings:
----------
```
/moto/cloudformation/parsing.py:295: UserWarning: Tried to parse AWS::IAM::ManagedPolicy but it's not supported by moto's CloudFormation implementation resource_type
```

Errors:
------
Can be reproduced by including the IAM::ManagedPolicy in the `Outputs` section as follows:
```
SampleManagedPolicyOutput:
    Description: some description
    Value: !Ref SampleManagedPolicy
```

```
moto/cloudformation/parsing.py", line 402, in parse_output output.value = clean_json(output_json["Value"], resources_map)
KeyError: 'Value'
```

Are there plans on implementing support for IAM: Policy or IAM: Managed Policy with Moto's CloudFormation service?

**Comment by bblommers** [comment]
Thanks for raising this @apranav19 - marking this as an enhancement.

I'm not aware of any plans, but PR's are always welcome!
