### ISSUE TITLE
Content type is appended when set as metadata

### ISSUE THREAD

**Issue by adarshk7** [spulec/moto#333]
```
k = Key(bucket)
k.key = 'test'
k.set_metadata('Content-Type', 'application/exe')
k.set_contents_from_string('hello')

our_key = bucket.get_key('test')
assert our_key.content_type == 'application/exe'
```

This should ideally pass.
Instead `our_key.content_type` is `text/plain; charset=utf-8, application/exe`

When I try this without using `moto` then the right `content_type` is set.

Also, `print(our_key.get_metadata('Content-Type'))` prints out `None`

**Comment by spulec** [comment]
The following works for me against `master`:

```python
@mock_s3
def test_setting_content_type():
    conn = boto.connect_s3()
    bucket = conn.create_bucket('mybucket')
    key = bucket.new_key("keyname")
    key.set_metadata("Content-Type", "application/exe")
    key.set_contents_from_string("abcdef")

    key = bucket.get_key("keyname")
    key.content_type.should.equal("application/exe")
```

Can you verify what version of moto you are running?

**Comment by adarshk7** [comment]
`bucket.new_key` works for me, thanks!

Using the `Key` constructor still yields the same result.
(I was using `0.3.9` and upgraded to `0.4.1`, but the results are the same with both versions using the constructor.)

**Comment by adarshk7** [comment]
**EDIT:**
Actually I made the mistake of testing it directly under `boto`. Now that I tried it again, it does not work with `moto` even when I used `bucket.new_key`, even on version `0.4.1`

**Comment by spulec** [comment]
The following code works for me with Moto `0.4.1` and HTTPretty `0.8.7`.

```python
@mock_s3
def test_setting_content_type():
    conn = boto.connect_s3()
    bucket = conn.create_bucket('mybucket')
    key = Key(bucket)
    key.key = 'keyname'
    key.set_metadata("Content-Type", "application/exe")
    key.set_contents_from_string("abcdef")

    key = bucket.get_key("keyname")
    assert key.content_type == "application/exe"
```

Can you let me know if that works for you?

**Comment by adarshk7** [comment]
It still doesn't work. I tried Moto 0.4.1 and HTTPretty 0.8.7 with both Python 3.4.2 and Python 2.7.6. In Python 3, as you know httpretty 0.8.7+ causes a hang, so it didn't reach the assert, but I printed `key.content_type` right before the `assert` and it printed out `text/plain; charset=utf-8, application/exe`

In Python 2 it didn't hang, but the result was an `AssertionError`.

**Comment by terrycain** [comment]
Is this still an issue or can this be closed?
