### ISSUE TITLE
responses does not work as expected due to passthru rule

### ISSUE THREAD

**Issue by escaped** [spulec/moto#3330]
Hey,

I just ran into an issue while using `responses` and `moto` at the same time. 

If you use `@responses.activate`, you would expect that all HTTP requests are blocked and an exception is raised when you request an URL which has not been specified using `responses.add`. This works well as long as you are not importing `moto`. As soon as you `import moto`, it runs `responses.add_passthru("http")` and basically whitelists "all" HTTP requests and no exception is raised anymore. So if you have a typo in your URL (be it the host or a (missing) query parameter or ...), the original request is not blocked and hits the real server. This behavior is illustrated here:

```python
import responses
import requests
import pytest
from requests.exceptions import HTTPError

import moto  # adds passthru rule


def my_func():
  response = requests.get('https://google.com')  # will hit the host
  response.raise_for_status()
  ...


@responses.activate
def test_simple():
    responses.add(responses.GET, 'https://gogle.com',  # there's a typo
                  json={'error': 'not found'}, status=404)

    with pytest.raises(HTTPError):  # and no error is raised
        my_func()
```

This behavior was introduce in https://github.com/spulec/moto/issues/1567 / https://github.com/spulec/moto/commit/aa896a0c2e001cbb99b8981e30809925e701f433#diff-c1702816f8e7b12840f59610766977e0R200

I am not sure, how this issue should be fixed. My intuition tells me, that this should not be the default behavior as this issue can kind of only be discovered by looking at the logs. Output of pytest:

```
--------------------------------------------------------------------------------------------- Captured log call ----------------------------------------------------------------------------------------------
INFO     responses:responses.py:636 request.allowed-passthru
```

**Comment by bblommers** [comment]
Thanks for raising this @escaped. There's a related issue here: #3264, but no specific solutions for either yet.

**Comment by escaped** [comment]
Oh... sorry for reporting the issue again; I did not see the other issue for some reason. I'll close this one in favour of #3264 :)
