### ISSUE TITLE
Adding additional context to exceptions

### ISSUE THREAD

**Issue by BenD10** [spulec/moto#3333]
Hi there!

When I worked on #3320, I missed that boto includes more context on the `ResourceAlreadyExistsException`, here's a sample from an actual boto3 call.

```
{
  "Error": {
    "Message": "The certificate is already provisioned or registered",
    "Code": "ResourceAlreadyExistsException"
  },
  "ResponseMetadata": {
    "RequestId": "59bf6dbc-47be-41ff-9955-a330e9774206",
    "HTTPStatusCode": 409,
    "HTTPHeaders": {
      "date": "Wed, 23 Sep 2020 13:41:05 GMT",
      "content-type": "application/json",
      "content-length": "268",
      "connection": "keep-alive",
      "x-amzn-requestid": "59bf6dbc-47be-41ff-9955-a330e9774206",
      "x-amzn-errortype": "ResourceAlreadyExistsException",
      "x-amz-apigw-id": "TUmBsEE2IAMF7Ow=",
      "x-amzn-trace-id": "Root=1-5f6b5071-7365b45c5d40173e6c367fdb"
    },
    "RetryAttempts": 0
  },
  "message": "The certificate is already provisioned or registered",
  "resourceId": "38d10ff04db5d***********052413340177cddba4c3b3",
  "resourceArn": "arn:aws:iot:us-east-1:***********:cert/38d10ff04db5d***********052413340177cddba4c3b3"
}
```

vs Moto
```
{
  "Error": {
    "Message": "The certificate is already provisioned or registered",
    "Code": "ResourceAlreadyExistsException"
  },
  "ResponseMetadata": {
    "HTTPStatusCode": 409,
    "HTTPHeaders": { "server": "amazon.com", "status": "409" },
    "RetryAttempts": 0
  },
  "message": "The certificate is already provisioned or registered"
}
```

Note the boto3 response contains `resourceId` and `resourceArn` as per the spec - https://github.com/boto/botocore/blob/develop/botocore/data/iot/2015-05-28/service-2.json#L13457

I can't find any examples of where is this done in moto, or if this is possible, does it require per-service specific error templates?

**Comment by BenD10** [comment]
I'd like to discuss some ideas/implementation first, and then I'll send along a PR.

**Comment by bblommers** [comment]
Hi @BenD10, we're using specific error templates in S3, for example. The error templates in S3 are in XML format, and are defined like this:
https://github.com/spulec/moto/blob/master/moto/s3/exceptions.py#L5

Custom errors can be raised like normal, like is done here: https://github.com/spulec/moto/blob/master/moto/s3/models.py#L1279
For IOT, I imagine it would eventually look like this:
```
raise ResourceAlreadyExistsException(resource_id=..., resource_arn=...)
```

(There are a few steps in between, but that's the simple explanation.)

The complication here is that `ResourceAlreadyExistsException` extends JsonRestError, and I don't think we have any example of a custom error in JSON-format. 

The rough process would _probably_ be:

1. Extend the default JSON response in the same way as is done in XML, by adding the `{% block extra %}{% endblock %}`-bit. 
2. Create the custom JSON template, similar to `ERROR_WITH_BUCKET_NAME` in s3/exceptions.py
3. Specify the new template in ResourceAlreadyExistsException, as is done in S3ClientError

Notes: 
The default JSON response is defined here:
https://github.com/spulec/moto/blob/master/moto/core/exceptions.py#L29


There are quite a few assumptions in here, but it should work. Let me know if you need any help :)
