### ISSUE TITLE
presigned urls API fails when KMS is mocked but not when it is a fake key

### ISSUE THREAD

**Issue by teague-lasser** [spulec/moto#3334]
I have a test that creates a presigned url and reads the file back out similar to the UT in moto. In my code there is a completely bogus `test_kms_arn` value passed along to the API as the kms arn. This test worked. I then added another test where I needed to mock KMS and produce a kms_arn for a different unit test. After I did this the test started failing.

I have a shared variable `KMS_KEY` that both of these tests reference. With a mock kms arn instead of just a made up key the presigned urls test started failing with `not implemented` when trying to pull from the URL.

It seems buggy for this behavior to be inconsistent between a "real" mock arn and a fake arn. I would expect either KMS to not work at all due to key validation failing or for it to mock the behavior out entirely since the encryption/decryption happens on AWS side and doesn't matter to moto's mocks.

Bonus round:

I was having trouble with the `batch.start_job` api as well, and I was confused as to why because I was following the unit test moto has pretty closely. It turns out the issue was *also* using a real mock ARN instead of a bogus ARN for KMS! Using fake kms arns has both my tests working nicely.

**Comment by bblommers** [comment]
Hi @teague-lasser, thanks for raising this.
Can you share a minimal reproducable example, by any chance?

**Comment by bblommers** [comment]
Going to close this due to a lack of response, but feel free to let me know if this is still an issue.
