### ISSUE TITLE
DynamoDB supports empty values

### ISSUE THREAD

**Issue by icevita** [spulec/moto#3339]
https://github.com/spulec/moto/blob/55e7caccfe2482c90e4fb52214ef9e031ccdda1e/moto/dynamodb2/responses.py#L24

https://aws.amazon.com/about-aws/whats-new/2020/05/amazon-dynamodb-now-supports-empty-values-for-non-key-string-and-binary-attributes-in-dynamodb-tables/

**Comment by bblommers** [comment]
Thanks for raising this @icevita! Will mark it as an enhancement.

**Comment by bblommers** [comment]
This is now supported as of moto >= 1.3.16.dev126
