### ISSUE TITLE
How to use mock_lambda?

### ISSUE THREAD

**Issue by aschuhl** [spulec/moto#3344]
I am having trouble with a creating a lambda using moto. Every time I get the exception 

> Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

I have `moto_server lambda` running and below is my test code:

```
@fixture
@mock_lambda
@mock_s3
def mocked_lambda_client(mocked_aws_credentials):
    s3_client = boto3.client("s3")
    s3_client.create_bucket(Bucket="test-bucket",)
    response = s3_client.put_object(Bucket="test-bucket", Key="test.zip", Body=b"")

    lambda_client = boto3.client("lambda")
    lambda_client.create_function(
        FunctionName="timeline_stream5_stg-local",
        Runtime="python3.6",
        Role="string",
        Handler="lambda_function.lambda_handler",
        Code={"S3Bucket": "test-bucket", "S3Key": "test.zip"},
    )

    return lambda_client
```

What I am missing?

**Comment by bblommers** [comment]
Hi @aschuhl, do you have the Docker-client running on your machine, with the appropriate permissions?

Which version of moto are you using? The latest version (1.3.16) should give a more explicit error when Docker can't be found/accessed.

**Comment by bblommers** [comment]
Going to close this due to a lack of response, but feel free to let me know if this is still an issue.
