### ISSUE TITLE
Docker tag for 1.3.16

### ISSUE THREAD

**Issue by g-dx** [spulec/moto#3357]
Hi,

Any chance we can get a new Docker tag pushed to https://hub.docker.com/r/motoserver/moto/tags for the `1.3.16` release rather than using `latest`?

Thanks again for all your hard work!

**Comment by saartochner** [comment]
This is important because we just saw that tests are failing with docker version 4.3.1 and not 4.3.0 (tests that use lambda clients)

**Comment by spulec** [comment]
Added; sorry about that.
