### ISSUE TITLE
How to access and alter `EC2ContainerServiceBackend` properties for my tests ?

### ISSUE THREAD

**Issue by Ellynas** [spulec/moto#3362]
I few days ago, I created an issue https://github.com/spulec/moto/issues/3352 that has been resolved and closed. I'm very grateful for that ! The related pull request https://github.com/spulec/moto/pull/3358 added `registeredAt` property in `client.describe_container_instances()` response.

I want to create a script that will "shut down" instances based on that param (ie: old instances with no running task will be stopped by my script)

If I want to test that, I will need to use moto to mock ecs to created my instances, then **alter the fake instances** so that they are "older" than what they really are. 

How can i access directly EC2ContainerServiceBackend.container_instances property so i can alter it to create my tests ?

So far I've tried :
```python
@mock_ecs
def test_private():
    ecs = boto3.client(
        "ecs",
        region_name=settings.AWS_REGION,
        aws_access_key_id=settings.AWS_ACCESS_KEY_ID,
        aws_secret_access_key=settings.AWS_SECRET_ACCESS_KEY,
    )

    ecs.create_cluster(clusterName="myCluster")
    # I'm certain that this uses EC2ContainerServiceBackend.create_cluster()
    # because I put a print in it to verify it's properly called

    print(type(ecs))  # outputs <class 'botocore.client.ECS'>

    print(ecs.container_instances) 
    # AttributeError: 'ECS' object has no attribute 'container_instances'
```

How is it that I can use the correct `create_cluster()` fuction and at the same time and on the same object not have access to it's properties ? And what do I have to do to gain access to those `EC2ContainerServiceBackend` properties ?

**Comment by Ellynas** [comment]
Alternative question : If I can't access `EC2ContainerServiceBackend.container_instances` to modify the instances "by hand" to make them virtually older than what they are, is there a way to make them older at creation ?

**Comment by bblommers** [comment]
Hi @Ellynas, the boto3-client (`ecs`) doesn't have access to the data itself. It only acts as a wrapper to access the data stored in AWS/Moto (depending on whether we're mocking it or not).

In order to access the data stored in Moto, you can do something similar to this:
```
from moto.ecs.models import ecs_backends
ecs_backend = ecs_backends[settings.AWS_REGION]
instance = ecs_backend.container_instances["myCluster"][container_instance_id]
instance.registered_at = ...
```

Note: I haven't tested this myself, so there might be typos - but it is the correct approach :)

**Comment by gruebel** [comment]
Hey @Ellynas,

I think you can solve this with using https://github.com/spulec/freezegun and the context manager syntax.

**Comment by Ellynas** [comment]
@bblommers and @gruebel , thank both of you for your help.
I considered using freezegun, but if possible I wanted to avoid relying on even more external libraries. I would've used it only if necessary.

But, it turned out @bblommers answer was exactly what I needed, all within moto. Thanks again, you're awesome !

**Comment by bblommers** [comment]
Happy to help!
