### ISSUE TITLE
`@freeze_time` decorator causes tests to be skipped

### ISSUE THREAD

**Issue by bpandola** [spulec/moto#3364]
It looks like every test in the test suite that is decorated with `@freeze_time` is getting skipped.

Examples:
https://github.com/spulec/moto/blob/master/tests/test_apigateway/test_apigateway.py#L19
https://github.com/spulec/moto/blob/master/tests/test_s3/test_s3.py#L493

Neither of these tests show in the latest Travis log: https://travis-ci.org/github/spulec/moto/jobs/733196068

I haven't had a chance to dig in and troubleshoot, but wanted to bring it to your attention.

**Comment by bblommers** [comment]
Hi @bpandola, those tests do show up in the log?
https://travis-ci.org/github/spulec/moto/jobs/733196068#L1446
https://travis-ci.org/github/spulec/moto/jobs/733196068#L6921

**Comment by bpandola** [comment]
@bblommers Hmm... that's my bad for looking at the list alphabetically instead of searching for the test itself.  I initially encountered this while working on #3365 and doing a search for that test (`elastic_block_store.test_copy_snapshot`) does in fact turn up nothing in the CI logs (as far as I can see).  Perhaps it was an isolated issue--with some other root cause--that incorrectly led me to the `@freeze_time` decorator as the culprit.  Sorry about that.  I appreciate you having a look.

**Comment by bblommers** [comment]
That is a little weird, that the test didn't run before. Looks like it does show up in the PR though.

Will close this - let me know if you run into any other issues.
