### ISSUE TITLE
New instance from reservation returning empty string instead of None

### ISSUE THREAD

**Issue by Jonnymcc** [spulec/moto#337]
I've looked into the code and am not sure what is going on here. When I create an instance with the moto.ec2.models.Instance class the vpc_id of the returned instance is None, which is expected. When I do conn.run_instances() I get a reservation with an instance where the vpc_id is the empty string. Any idea what is happening? Is it just me?

```
In [55]: i = Instance(back, '', '', '')

In [56]: i.vpc_id

In [57]: type(i.vpc_id)
Out[57]: NoneType
```
```
In [58]: res = conn.run_instances('',1,'','default')

In [59]: inst = reservation.instances[0]

In [60]: inst.vpc_id
Out[60]: ''

In [61]: type(inst.vpc_id)
Out[61]: str
```

**Comment by spulec** [comment]
Yes, that was a bug. Thank you!
