### ISSUE TITLE
[BUG] acm client: describe_certificate() does not work, unittest is broken as well.

### ISSUE THREAD

**Issue by nom3ad** [spulec/moto#3371]
While describing imported acm certificate,  if the certificate does not have any SANs, [get_extension_for_oid()](https://github.com/spulec/moto/blob/d00cefa25cfd338caaabcefc7a79e6e803f577cf/moto/acm/models.py#L296)  could throw a [cryptography.x509.ExtensionNotFound](https://cryptography.io/en/latest/x509/reference/#cryptography.x509.Extensions.get_extension_for_oid ).  

This is clearly not being handled.

The [unit test](https://github.com/spulec/moto/blob/d00cefa25cfd338caaabcefc7a79e6e803f577cf/tests/test_acm/test_acm.py#L129) should have failed here.  But unfortunately, it is overwritten by next function with same name. 

#3370 resolves this.

**Comment by bblommers** [comment]
This is now part of moto >= 1.3.16.dev60
