### ISSUE TITLE
Mock ecs_agent ?

### ISSUE THREAD

**Issue by Ellynas** [spulec/moto#3381]
I would like to test a script that uses `ecs.list_container_instances()` to check how many instances are registered on a particular cluster, and that terminates any instances that are "too old". 
Basically, the script (that was wrote by a college that is unavailable) will JUST use `ec2.instances.filter(InstanceIds=ids).terminate()` when necessary and that's it. 

From what I understand, those instances have an `ecs_agent` that is attached to them that will take care of registering / de-registering the container-instance to my cluster, i.e. I don't need to do that manually, I just use a lanchtemplate defined in AWS that hold all the proper information and it will launch the `ecs_agent`, which will use that information to register it's instance to my cluster, and de-register it if the instance is terminated.

Using moto, what should I do to mock that behavior, especially the automatic de-registration ? Do I need the create a custom launchtemplate and if yes, how should I define it and use it ? 

What happens now with moto is that `ec2.instances.filter(InstanceIds=ids).terminate()` will not update / de-register my instances, so I can't properly compare `ecs.list_container_instances()` before and after my script ran.

PS : I know this is not my first question here and that you may have better things to do, but you've been helpfull in the past and your help would be really useful again. I'm not an expert with AWS and I hope my questions doesn't sound too trivial.

**Comment by bblommers** [comment]
Hey @Ellynas, the goal of Moto is to mock the AWS SDK's itself. Additional software, such as the ECS agent, really falls outside the scope.

As such, Moto doesn't do anything with the launch template. (As far as I know, it doesn't even do any validation).

Your best bet is probably to patch/extend the moto.ec2.models.Instance.terminate() method manually, if you need that additional functionality.

PS: Don't worry about asking questions - that's the point of open source software, to help where possible :)

**Comment by Ellynas** [comment]
> the goal of Moto is to mock the AWS SDK's itself

I get it, it doesn't help me but I understand your stance :)

For my problem, I noticed the for every instance we start and we terminate, we also add it (and remove it on termination) to an auto-scaling group. 

So, in my tests, instead of verifying the list of running instances on a cluster, I take a peek on what's happening on the ASG before and after our cleanup script with `autoscaling.describe_auto_scaling_groups(AutoScalingGroupNames=[asg_name])`. it's not perfect, but for all our intents and purposes it works.

I think that's the easiest solution for us since those tests run in a submodule that is used by several Django apps, and it may be trickier/harder to have something like our own moto fork with a modified `moto.ec2.models.Instance.terminate()` method as you mentioned.

And as always, thanks for you input :)
