### ISSUE TITLE
Add request validation to EventBridge

### ISSUE THREAD

**Issue by lijok** [spulec/moto#3384]
EventBridge is supported using @moto.mock_events, however, the requests are not validated, and so you end up not receiving errors, when sending in incorrect requests, which, as an example, omit the 'Source' argument in the put_events request

**Comment by bblommers** [comment]
Thanks for raising this @lijok - will mark it as an enhancement.

**Comment by bblommers** [comment]
This is now part of moto >= 1.3.16.dev195

**Comment by lijok** [comment]
> This is now part of moto >= 1.3.16.dev195

Thank you very much @bblommers @gruebel
