### ISSUE TITLE
EC2 VPNGatewayId Param Casing

### ISSUE THREAD

**Issue by joshah-moors** [spulec/moto#3397]
Param casing of "VPNGatewayId" is not consistent with boto3 casing and user is unable to set this attribute while testing.

Update to be made in this file: moto/ec2/responses/vpn_connections.py
Line 10: "VPNGatewayId" -> "VpnGatewayId"

Boto3 docs of the same functionality to see the correct option is "VpnGatewayId":
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2.html#EC2.Client.create_vpn_gateway

**Comment by bblommers** [comment]
Thanks for raising this @joshah-moors! Will mark it as a bug

**Comment by bblommers** [comment]
This is now fixed as of moto >= 1.3.16.dev75
