### ISSUE TITLE
Wrong MD5 hash for SQS Message Attributes.

### ISSUE THREAD

**Issue by artemtere** [spulec/moto#3399]
The issue is described in 
* localstack https://github.com/localstack/localstack/issues/2976
* moto pull request https://github.com/spulec/moto/pull/3346#pullrequestreview-501657555

I've fixed this issue according to aws documentation https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-message-metadata.html#sqs-message-attributes

But I do not have rights to push new branch  to moto repo. Could anybody help me with that please?

**Comment by artemtere** [comment]
@bblommers May be you could help me with that?

**Comment by bblommers** [comment]
Hi @artemtere, if you fork Moto and create a branch in your own repository, you can create a PR to merge your (remote) branch into Moto's master.

**Comment by bblommers** [comment]
This is now fixed as part of moto >= 1.3.16.dev76. Thanks for providing the PR @artemtere!
