### ISSUE TITLE
Python 2.6 issues with wheels and dependencies

### ISSUE THREAD

**Issue by piskvorky** [spulec/moto#340]
My Travis tests failed on Python 2.6: piskvorky/smart_open#15 .

After some digging around it appears this is because of `moto`. Moto apparently depends on some `ordereddict` package, but that package is not installed (nor mentioned anywhere in the docs, AFAICS).

Do you think you could make `ordereddict` a dependency for moto, when installing on Python 2.6?

In other words, after I successfully run `pip install moto`, I'd expect moto to work, even on Python 2.6.

And thanks for the great package!

**Comment by spulec** [comment]
This should already be the case as far as I know: https://github.com/spulec/moto/blame/master/setup.py#L18-21

**Comment by piskvorky** [comment]
In that case, I don't know why it fails, but it does.

I just checked: compare the Travis fail on
https://travis-ci.org/piskvorky/smart_open/builds/57924387 (no explicit `pip install ordereddict`)
vs. Travis pass on
https://travis-ci.org/piskvorky/smart_open/builds/57924974 (does an explicit `pip install ordereddict`)

The only difference between the two is installing `ordereddict`: https://github.com/piskvorky/smart_open/pull/17/files

Any ideas?

**Comment by spulec** [comment]
Okay, I have confirmed the issue. It looks like something to do with the wheel distribution files. If you install with `pip install moto --no-use-wheel` it will work. I'm going to keep digging into the root cause.
