### ISSUE TITLE
eventName for a deleted record should be REMOVE instead of DELETE

### ISSUE THREAD

**Issue by wenjiezhou-rl** [spulec/moto#3400]
When using Moto to mock DynamoDB streams, a deleted record has the eventName = "DELETE" right now:
https://github.com/spulec/moto/blob/9eb58eea411214ded617ea45ce9a4407a8f95194/moto/dynamodb2/models/__init__.py#L243-L250

AWS's DynanoDB Stream specification states that this should actually be `"REMOVE"`:
https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_streams_Record.html#DDB-Type-streams_Record-eventName

I am on Moto version 1.3.16 and using the dynamodb2.start() and stop() methods

**Comment by bblommers** [comment]
Thanks for raising this @wenjiezhou-rl - marking this as a bug!

**Comment by bblommers** [comment]
This is now fixed as of moto >= 1.3.16.dev91
