### ISSUE TITLE
bug: dynamodb2 transact_get_items should return empty Map for item, if item not found

### ISSUE THREAD

**Issue by palloromk** [spulec/moto#3404]
AWS documentation https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_TransactGetItems.html
"If a requested item could not be retrieved, the corresponding ItemResponse object is Null, or if the requested item has no projected attributes, the corresponding ItemResponse object is an empty Map."

Short example:
Put into some table only one value
    "Get": {
      "Key": {
        "primaryKey": {
          "S": "primarykey1"
        }
      },
      "TableName": "TestTable"
    }
Then transact_get_items, from both AWS and moto dynomodb2
[
  {
    "Get": {
      "Key": {
        "primaryKey": {
          "S": "primarykey1"
        }
      },
      "TableName": "TestTable"
    }
  }
  {
    "Get": {
      "Key": {
        "primaryKey": {
          "S": "primarykey2"
        }
      },
      "TableName": "TestTable"
    }
  }
]

AWS response: [
  {
    "Get": {
      "Key": {
        "primaryKey": {
          "S": "primarykey1"
        }
      },
      "TableName": "TestTable"
    }
  },
  {}
]

Moto dynamodb2 response
[
  {
    "Get": {
      "Key": {
        "primaryKey": {
          "S": "primarykey1"
        }
      },
      "TableName": "TestTable"
    }
  }    # HERE THE SECOND EMPTY ITEM IS MISSING
]

**Comment by bblommers** [comment]
Thanks for raising this @palloromk!

**Comment by palloromk** [comment]
My first issue, so pretty exciting for me :D I am just a beginner.

**Comment by bpandola** [comment]
@palloromk Did you want to take a crack at fixing this?  I'm happy to do it myself, but didn't want to steal your thunder if you were planning to write the PR.  Let me know.  Thanks.

**Comment by bpandola** [comment]
@palloromk Sorry! Couldn't help myself... I went ahead and submitted a fix.

**Comment by bblommers** [comment]
This is now fixed as of moto >= 1.3.16.dev81
