### ISSUE TITLE
list secretsManager returns "VersionIdsToStages" field but the aws apis call it "SecretVersionsToStages"

### ISSUE THREAD

**Issue by DuaneKrause** [spulec/moto#3406]
The response to list_secrets from aws secretsmanager, has a field in the secret_list_entry that is misnamed. I discovered this when making a call to list_secrets via the latest localstack/localstack docker container 0.12.0 (which includes this library).

"VersionIdsToStages" should instead be "SecretVersionsToStages"

I think all that needs changing is the response model here:
https://github.com/spulec/moto/blob/14980371d796ef849b1ea401ce2c028911b537d1/moto/secretsmanager/models.py#L138

You can see the "SecretVersionsToStages" field in the "ResponseSyntax" example, in the aws api docs here:
https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_ListSecrets.html

And in the java sdk here:
https://github.com/aws/aws-sdk-java/blob/83f1a7c1bef7bab8f809f5123275848678fb807b/aws-java-sdk-secretsmanager/src/main/java/com/amazonaws/services/secretsmanager/model/transform/SecretListEntryJsonUnmarshaller.java#L101

localstack is including moto.secretsmanager here:
https://github.com/localstack/localstack/blob/d43a58d563a5a912de64d4e9c8bcac28a96d3857/localstack/services/secretsmanager/secretsmanager_starter.py#L2

**Comment by bblommers** [comment]
Thanks for raising this @DuaneKrause - marking it as an bug

**Comment by bblommers** [comment]
This is now fixed as of moto >= 1.3.16.dev92
