### ISSUE TITLE
Deprecation warnings using mock_s3 with python 3.8

### ISSUE THREAD

**Issue by qbiqing** [spulec/moto#3418]
Similar issue as https://github.com/spulec/moto/issues/2978 but using `mock_s3` instead.

## Versions
```
✗ pipenv run pip freeze | grep -E 'moto|boto'
boto==2.49.0
boto3==1.15.18
botocore==1.18.18
moto==1.3.16
```

## Examples
Given the following pytest setup:
```python
os.environ["AWS_ACCESS_KEY_ID"] = "testing"
os.environ["AWS_SECRET_ACCESS_KEY"] = "testing"

@pytest.fixture(scope="function")
def s3():
    bucket_name = "test"

    mock = mock_s3()
    mock.start()

    conn = boto3.resource("s3", region_name="us-east-1")
    conn.create_bucket(Bucket=bucket_name)

    yield boto3.client("s3", region_name="us-east-1")
```
Running a pytest with `s3` fixture yields the following warning:

```
  /usr/local/lib/python3.8/site-packages/boto/plugin.py:40: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp

-- Docs: https://docs.pytest.org/en/stable/warnings.html
```

## Expected behaviour
Similar to #2978, not mission critical, but annoying.

Since that other issue is closed, and the issue name is not completely relevant for my issue, I thought I'd open a new one. I commented on the other issue but got no response.

**Comment by bblommers** [comment]
Hi @qbiqing, it looks like that warning comes from the `boto` dependency. I don't think there's anything that we can do in Moto to remove that.

**Comment by qbiqing** [comment]
Just curious, how come #2978 could be fixed (or was it fixed?) because that has the exact same deprecation warning, also from `boto`.

**Comment by bblommers** [comment]
Hi @qbiqing, that issue lists two warnings - the first about the imp-module from boto, the second about the collections.abc import inside Moto.
The attached PR fixes the second warning only.

**Comment by davidszotten** [comment]
i believe this is now fixed by #3468

**Comment by qbiqing** [comment]
Awesome, thanks!

**Comment by bblommers** [comment]
That PR is now part of moto >= 1.3.16.dev132.

Are you able to reproduce the issue with that version, @qbiqing?

**Comment by qbiqing** [comment]
@bblommers I tried with moto==1.3.16dev132 and the issue has been fixed. I will close this. Thanks!
