### ISSUE TITLE
Adding support for AWS Media Services

### ISSUE THREAD

**Issue by jordan-dimov** [spulec/moto#3424]
I'm considering contributing support for mocking some of the AWS Media Services - more specifically, Media Live, Media Connect and Media Package. Probably not all end-points. 

I was wondering if anyone has already looked into supporting those, or if anyone else would find this useful. As I have not contributed to `moto` before, would appreciate some help or guidance (although the CONTRIBUTING document is already quite clear).

**Comment by bblommers** [comment]
PR's are always welcome, @jordan-dimov! Every little bit helps.

The [`Missing Services`-section](https://github.com/spulec/moto/blob/master/CONTRIBUTING.md#missing-services) should have all necessary information to get you started, but do let me know if you get stuck.

**Comment by bblommers** [comment]
This is now part of moto >= 1.3.16.dev209
