### ISSUE TITLE
Which Boto3 version for which Moto version ?

### ISSUE THREAD

**Issue by Ellynas** [spulec/moto#3426]
Recently, AWS changed their response for `ecs.list_container_instances(cluster="my_cluster")` and broke our code. 

Basically what happened is that now, ARNs are of format `arn:aws:ecs:region:aws_account_id:container-instance/CLUSTER/container_instance_ID` when they used to be `arn:aws:ecs:region:aws_account_id:container-instance/container_instance_ID` (and of course, we used something like `.split("/")[1]` to "extract" the container_instance_ID, except now it returned the CLUSTER and not the container_instance_ID.

Now, [aws documentation](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerInstance.html) doesn't mention this change, it just... happened. It may have been involuntary, but I doubt that.

All that got us thinking : in order to avoid such involuntary behavior in the future, is there a specific AWS version Moto targets and if yes, which one is it ? Is there something somewhere that tracks what moto version mocks a specific AWS versions perhaps ?

**Comment by bblommers** [comment]
Hi @Ellynas, great question! It's not the first time that a boto3-change just.. happened, without any communication, and broke moto.

We don't track version-compatibility at all, I'm afraid. It would be very useful, but I don't think we'd have to time to keep up with all releases.
As a rule, the latest versions should always play nice.

Do you know which boto3/botocore version introduced this ARN change?

**Comment by Ellynas** [comment]
From what I could gather it wasn't a change in boto3/botocore, but in AWS itself. That issue was first noticed in our alpha, then in our beta the next day, then in production a few days later. They all had fixed and different boto3 version that weren't updated after the first discovery of the bug, meaning that it was most certainly gradual change on AWS side that had nothing to do with boto3 version.

**Comment by bblommers** [comment]
Ah, right. That is curious. I've never seen any docs/release notes that would allow us track such changes unfortunately

**Comment by Ellynas** [comment]
Very recently (as in, minutes ago) was send by a colleague this site : https://awsapichanges.info/

I don't know what it's worth, but that's the closest thing I've seen to actual release notes.

**Comment by bblommers** [comment]
The ECS ARN change has also been discussed here: https://github.com/spulec/moto/issues/3497
Moto does have a solution now to represent both short and long format ARN's, as shown in that issue.

Changes like this are not versioned though, so there is no way for Moto to target a specific AWS version. The only versioning that we can see, and that we can act on, is the `boto3`/`botocore` releases. Changes to those library tend to be non-breaking changes though, they only add new features. 
(Any updates to boto3 are shown on the site that you mentioned: https://awsapichanges.info/)

As there is not much else for us to do here, I'm going to close this ticket. Let us know if you have any other questions!
