### ISSUE TITLE
botocore.parsers.ResponseParserError changing visibility on message not in flight

### ISSUE THREAD

**Issue by wallowa** [spulec/moto#3435]
How to reproduce the bug:

Run moto docker in server mode (I used the latest image at https://hub.docker.com/r/motoserver/moto)

Create a queue, send a message, receive the message, and try to set the visibility on the (now no longer valid) message:

`queue = boto3.resource('sqs', endpoint_url='http://moto:5000').create_queue(QueueName='test')`
`msg = base64.b64encode(json.dumps({'test': 'test'}).encode('utf-8')).decode('utf-8')`
`queue.send_message(MessageBody=msg)`
`sqs_msg = queue.receive_messages()[0]`
`sqs_msg.change_visibility(VisibilityTimeout=1)`

Expected:
`botocore.exceptions.ClientError`

What happens:
`*** botocore.parsers.ResponseParserError: Unable to parse response (syntax error: line 1, column 0), invalid XML received. Further retries may succeed:
b'Invalid request: The message referred to is not in flight.'`

Possible cause:
MessageNotInflight is the only exception in sqs/exceptions.py that does not inherit from RESTError. If I do make it inherit from RESTError, the issue goes away.

Version: Server mode using https://hub.docker.com/r/motoserver/moto latest (digest ef4e4172daf2) using docker-compose on the default port (5000).

**Comment by bblommers** [comment]
Thanks for raising this, @wallowa!

**Comment by bblommers** [comment]
Hi @wallowa, do you have a script to reproduce this behaviour against AWS itself? 
Executing the code in the OP gives me a standard 200 response, i.e. AWS allows changing the visibility of a message in flight.

**Comment by wallowa** [comment]
I think there might be a few issues.

First, to clarify the AWS behavior. AWS allows calling change_visibility on an SQS message even if the visibility timeout has expired:

In [205]: m = q.receive_messages()[0]
In [206]: m.change_visibility(VisibilityTimeout=1)
Out[206]: 
{'ResponseMetadata': {...
  'HTTPStatusCode': 200,
  ...}}
In [207]: m.change_visibility(VisibilityTimeout=1)
Out[207]: 
{'ResponseMetadata': {...
  'HTTPStatusCode': 200,
  ...}}

If the message has been deleted, then aws returns an InvalidParameterValue:

In [209]: m.delete()
Out[209]: 
{'ResponseMetadata': {...
  'HTTPStatusCode': 200,
  ...}}
In [210]: x = None
In [211]: try:
     ...:     m.change_visibility(VisibilityTimeout=1)
     ...: except Exception as ex:
     ...:     x = ex
     ...: 
In [212]: x
Out[212]: botocore.exceptions.ClientError('An error occurred (InvalidParameterValue) when calling the ChangeMessageVisibility operation: Value <snip> for parameter ReceiptHandle is invalid. Reason: Message does not exist or is not available for visibility timeout change.')

Moto, however, appears to try to return a MessageNotInFlight (if the message visibility has expired) or a ReceiptHandleIsInvalid (if the message was deleted). However, these exceptions should only be returned for the client change_message_visibility calls (https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sqs.html#SQS.Client.change_message_visibility) not the message change_visibility call (https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sqs.html#SQS.Message.change_visibility).

Moto change_visibility after previous change_visibility:

(Pdb) queue = boto3.resource('sqs', endpoint_url='http://moto:5000').create_queue(QueueName='test')
(Pdb) msg = base64.b64encode(json.dumps({'test': 'test'}).encode('utf-8')).decode('utf-8')
(Pdb) queue.send_message(MessageBody=msg)
{'MD5OfMessageBody': '3530e5c7802be9feb584de042055002f', 'MessageId': '75036826-ad85-6f54-8987-bd8347523c65', 'ResponseMetadata': {'RequestId': 'QPWTDSLBQVSUL2TSGNFQNER4LO7CT22MYF3LZ7ISVOHGG196U6WY', 'HTTPStatusCode': 200, 'HTTPHeaders': {'server': 'amazon.com', 'x-amzn-requestid': 'QPWTDSLBQVSUL2TSGNFQNER4LO7CT22MYF3LZ7ISVOHGG196U6WY', 'x-amz-crc32': '2679545730', 'content-type': 'text/html; charset=utf-8', 'content-length': '322', 'date': 'Tue, 09 Mar 2021 22:04:38 GMT'}, 'RetryAttempts': 0}}
(Pdb) sqs_msg = queue.receive_messages()[0]
(Pdb) sqs_msg.change_visibility(VisibilityTimeout=1)
{'ResponseMetadata': {'RequestId': 'VJVIZPMHOX7MPNCQREAP9UWQ6UNIB39X7LA88OUGAOQB49YZXV3B', 'HTTPStatusCode': 200, 'HTTPHeaders': {'server': 'amazon.com', 'x-amzn-requestid': 'VJVIZPMHOX7MPNCQREAP9UWQ6UNIB39X7LA88OUGAOQB49YZXV3B', 'x-amz-crc32': '1230351275', 'content-type': 'text/html; charset=utf-8', 'content-length': '179', 'date': 'Tue, 09 Mar 2021 22:04:50 GMT'}, 'RetryAttempts': 0}}
(Pdb) sqs_msg.change_visibility(VisibilityTimeout=1)
*** botocore.parsers.ResponseParserError: Unable to parse response (syntax error: line 1, column 0), invalid XML received. Further retries may succeed:
b'Invalid request: The message referred to is not in flight.'

Moto change_visibility after delete_message:

(Pdb) sqs_msg = queue.receive_messages()[0]
(Pdb) sqs_msg.delete()
{'ResponseMetadata': {'RequestId': 'NLL16SUGPSLMBOJ70QH19Y3DE3M6ZLVJ9U4U45J3ZFM735BP6LRV', 'HTTPStatusCode': 200, 'HTTPHeaders': {'server': 'amazon.com', 'x-amzn-requestid': 'NLL16SUGPSLMBOJ70QH19Y3DE3M6ZLVJ9U4U45J3ZFM735BP6LRV', 'x-amz-crc32': '654814131', 'content-type': 'text/html; charset=utf-8', 'content-length': '159', 'date': 'Tue, 09 Mar 2021 22:05:53 GMT'}, 'RetryAttempts': 0}}
(Pdb) sqs_msg.change_visibility(VisibilityTimeout=1)
*** botocore.errorfactory.ReceiptHandleIsInvalid: An error occurred (ReceiptHandleIsInvalid) when calling the ChangeMessageVisibility operation: The input receipt handle is invalid.

That is, moto appears to be returning the client change_message_visibility exceptions rather than the exception that should be returned for SQS.Message.change_visibility calls.

**Comment by wallowa** [comment]
Comparing AWS behavior to moto.

**Change_visibility after a message has become visible again**

AWS
```
In [47]: x.change_visibility(VisibilityTimeout=0)
Out[47]: 
{'ResponseMetadata': {...
  'HTTPStatusCode': 200,
  ...}}

In [48]: x.change_visibility(VisibilityTimeout=0)
Out[48]: 
{'ResponseMetadata': {...
  'HTTPStatusCode': 200,
  ...}}
```
moto:
```
(Pdb) x = queue.receive_messages()[0]
(Pdb) x.change_visibility(VisibilityTimeout=0)
{'ResponseMetadata': {'RequestId': '1U0WFGZUMKRHBNW3SHCMD6H8IAVTEXI5Q0K0F2L7AR82NKH2QWIO', 'HTTPStatusCode': 200, 'HTTPHeaders': {'server': 'amazon.com', 'x-amzn-requestid': '1U0WFGZUMKRHBNW3SHCMD6H8IAVTEXI5Q0K0F2L7AR82NKH2QWIO', 'x-amz-crc32': '3375092054', 'content-type': 'text/html; charset=utf-8', 'content-length': '179', 'date': 'Wed, 10 Mar 2021 19:28:11 GMT'}, 'RetryAttempts': 0}}
(Pdb) x.change_visibility(VisibilityTimeout=0)
*** botocore.parsers.ResponseParserError: Unable to parse response (syntax error: line 1, column 0), invalid XML received. Further retries may succeed:
b'Invalid request: The message referred to is not in flight.'
```
This shows two behaviors that are different:
1. There appears to be a bug in moto's MessageNotInflight class.
2. Moto does not appear to allow calling change_visibility on a message that's become visible again, though AWS does.

The class is currently
```
class MessageNotInflight(Exception):
    description = "The message referred to is not in flight."
    status_code = 400
```
But it should be:
```
    class MessageNotInflight(RESTError):
        code = 400

        def __init__(self):
            super().__init__(
                "MessageNotInflight", "Invalid request: The message referred to is not in flight."
            )
```

**Multiple deletes on a message**

AWS
```
In [49]: x.delete()
Out[49]: 
{'ResponseMetadata': {...
  'HTTPStatusCode': 200,
  ...}}

In [50]: x.delete()
Out[50]: 
{'ResponseMetadata': {...
  'HTTPStatusCode': 200,
  ...}}
```
Moto:
```
(Pdb) x = queue.receive_messages()[0]
(Pdb) x.delete()
{'ResponseMetadata': {'RequestId': 'Z1G1EYA4BFKB24XBTNN8Q3W27DPW9I7DE2QXESQ6V2I30RET72MB', 'HTTPStatusCode': 200, 'HTTPHeaders': {'server': 'amazon.com', 'x-amzn-requestid': 'Z1G1EYA4BFKB24XBTNN8Q3W27DPW9I7DE2QXESQ6V2I30RET72MB', 'x-amz-crc32': '1556951917', 'content-type': 'text/html; charset=utf-8', 'content-length': '159', 'date': 'Wed, 10 Mar 2021 19:28:57 GMT'}, 'RetryAttempts': 0}}
(Pdb) x.delete()
*** botocore.errorfactory.ReceiptHandleIsInvalid: An error occurred (ReceiptHandleIsInvalid) when calling the DeleteMessage operation: The input receipt handle is invalid.
```
