### ISSUE TITLE
Could use an example for use with django-storages S3Storage

### ISSUE THREAD

**Issue by stuaxo** [spulec/moto#3446]
Django storages is a popular way to use S3 by extending its `S3Boto3Storage` class, that utilises boto3.

I tried writing a test of mycustom storage, withing `@mock_s3`, then calling the code that calls `.save`on my storage, but it seems to always try and save to s3.

Any idea if S3Boto3Storage can work with mock_s3 ?

**Comment by stuaxo** [comment]
In the end I used `unittest.mock` with Property\Mocks for `S3Boto3Storage.connection` and `S3Boto3Storage.bucket`.

**Comment by stuaxo** [comment]
This seems to be working if I use a mock to overide the `.connection` and `.bucket` properties of `S3Boto3Storage`, still, it doesn't leave me 100% sure that somewhere else isn't going to call into the real boto though and end up putting information into a bucket.


```python
class CustomS3Storage(S3Boto3Storage):
    def get_default_settings(self):
        # Importing settings here makes it possible for tests to override_settings
        from django.conf import settings

        return dict(
            super().get_default_settings(),
            location=settings.CUSTOM_BUCKET_NAME,
            default_acl="private",
        )
```

```python
@pytest.yield_fixture
def storage():
    bucket_name = 'test-bucket'
    with mock_s3():
        storage = CustomS3Storage()
        session = boto3.session.Session()

        with patch(
            "storages.backends.s3boto3.S3Boto3Storage.connection",
            new_callable=PropertyMock,
        ) as mock_connection_property, patch(
            "storages.backends.s3boto3.S3Boto3Storage.bucket",
            new_callable=PropertyMock,
        ) as mock_bucket_property:
            # By default Motos mock_s3 doesn't stop S3Boto3Storage from connection to s3.
            # Patch the connection and bucket properties on it to use Moto instead.
            @lru_cache(None)
            def get_connection():
                return session.resource("s3")

            @lru_cache(None)
            def get_bucket():
                connection = get_connection()
                connection.create_bucket(
                    Bucket=settings.bucket_name,
                    CreateBucketConfiguration={
                        "LocationConstraint": settings.AWS_S3_REGION_NAME
                    },
                )

                bucket = connection.Bucket(bucket_name)
                return bucket

            mock_connection_property.side_effect = get_connection
            mock_bucket_property.side_effect = get_bucket
            yield storage
```

**Comment by bblommers** [comment]
Hi @stuaxo, it looks like Django uses the standard boto3-api under the hood, so Moto should just work as usual.

At what point do you import Django? The mocking is only successful if all boto3-clients are instantiated within the `mock_s3()` decorator.
In your example, you might have to change it to:
```
with mock_s3():
    import CustomS3Storage
    storage = CustomS3Storage()
    ....
```

(See this part of the README for more info: https://github.com/spulec/moto/blob/master/README.md#what-about-those-pesky-imports)

**Comment by stuaxo** [comment]
The storage is part of a management command that I call from call_command in my test.

Things didn't seem to work.

The properties that I override do seem to do some caching, so it may be that a previous test imported it.

https://github.com/jschneier/django-storages/blob/master/storages/backends/s3boto3.py#L337-L363

**Comment by bblommers** [comment]
A workaround could be to use moto in server mode, and set `AWS_S3_ENDPOINT_URL` to localhost?
That would definitely ensure that S3Boto3Storage talks to Moto.

**Comment by stuaxo** [comment]
Interesting, I didn't know this was a thing, (new to Moto), would this impose some overhead ?

I already have a local version of AWS in the form of Minio so I'd probably need to make sure it ran on a different port.

(Minio was how I saw it writing in the first place - I saw all the files appear there).

**Comment by bblommers** [comment]
The default use case is to communicate with an SDK in a different language, so the AWS Node/Java SDK can also be tested with moto.
It's a fairly basic Flask application that just exposes the existing moto-functionality, so any resources overhead is minimal. 

Getting it up and running is as simple as this:
```
pip install moto[server]
moto_server
```

**Comment by spulec** [comment]
Going to close this, but let us know if you have any more questions!

**Comment by stuaxo** [comment]
No probs, I'm going to stick with my current solution for now instead of running the server.

One thing I can't work out if it's a bug or not:

I create a file somedir1/somedir2/data.xml

When I open minio which I'm using as s3 I get somedir1/somedir2/somedir1/somedir2/data.xml 

An I misunderstanding something about s3 buckets?

**Comment by bblommers** [comment]
That's not something I've seen before, either with boto or moto.
Can you share the relevant code? Haven't worked with minio before, but I can do some debugging with Moto to see what's going on

**Comment by stuaxo** [comment]
Realised that moto is totally the wrong thing to report that bug (not even sure if it's a bug) - but django-storages is where I should have mentioned it :)

**Comment by tomviner** [comment]
> This seems to be working if I use a mock to overide the `.connection` and `.bucket` properties of `S3Boto3Storage`, still, it doesn't leave me 100% sure that somewhere else isn't going to call into the real boto though and end up putting information into a bucket.

Thanks for this, I was able to update and minimise it down to:
```python
from unittest.mock import PropertyMock, patch
import boto3
import pytest
from moto import mock_s3
from storages.backends.s3 import S3Storage

@pytest.fixture
def patch_s3_storage_backend(bucket_name):
    """By default Moto's mock_s3 doesn't totally stop S3Storage from connecting to s3.
    Patch the connection and bucket properties on it to use Moto instead."""
    with mock_s3():
        storage = S3Storage()
        session = boto3.session.Session()

        with patch(
            "storages.backends.s3.S3Storage.connection",
            new_callable=PropertyMock,
        ) as mock_connection_property, patch(
            "storages.backends.s3.S3Storage.bucket",
            new_callable=PropertyMock,
        ):
            mock_connection_property.return_value = session.resource("s3")
            yield storage
```

**Comment by trumpet2012** [comment]
Building on the great work of @tomviner and @stuaxo, this was my port for a non-pytest django test setup. Sharing in case it helps someone else.

We added this directly to our settings file that we use just for tests. It just needs to be run somewhere before your tests start. Note that `AWS_S3_REGION_NAME` and `UPLOADS_BUCKETS` are our settings so will need to be replaced with your corresponding values.

```python
from unittest.mock import PropertyMock, patch
import boto3
from moto import mock_aws

mock_aws().start()
s3 = boto3.resource("s3", region_name=AWS_S3_REGION_NAME)
bucket = s3.Bucket(UPLOADS_BUCKET)
bucket.create()
connection_patcher = patch(
    "storages.backends.s3.S3Storage.connection",
    new_callable=PropertyMock,
)
mock_connection_property = connection_patcher.start()
bucket_patcher = patch(
    "storages.backends.s3.S3Storage.bucket",
    new_callable=PropertyMock,
)
mocked_bucket = bucket_patcher.start()
mocked_bucket.return_value = bucket
mock_connection_property.return_value = s3
```
