### ISSUE TITLE
NotImplementedError: The update_state_machine action has not been implemented

### ISSUE THREAD

**Issue by rohang-stockland** [spulec/moto#3452]
Hi,

I have mocked the creation of state_machine but I am unable to update the state machine with the same ARN used for creation. I am getting NotImplementedError.

"The {0} action has not been implemented".format(action)
NotImplementedError: The update_state_machine action has not been implemented.

Thanks in Advance!

**Comment by rohang-stockland** [comment]
Hi,

I have mocked the creation of state_machine but I am unable to update the state machine with the same ARN used for creation. I am getting NotImplementedError.

"The {0} action has not been implemented".format(action)
NotImplementedError: The update_state_machine action has not been implemented.

Thanks in Advance!

**Comment by bpandola** [comment]
What version are you using?  Should be available in moto >= 1.3.16.dev93

**Comment by rohang-stockland** [comment]
Thanks for the help. I was using moto==1.3.16. Its working after upgrading moto to 1.3.16.dev93!
