### ISSUE TITLE
RDS: TagList missing in describe_db_instance

### ISSUE THREAD

**Issue by alvarogmj** [spulec/moto#3458]
There doesn't seem to be any support for tags in describe_db_instance. It seems to be on purpose, I couldn't find any test dealing with tags in this api call

The AWS API returns a TagList property when the instance is tagged.

(Edit: remove references to create_db_instance, which does in fact support the Tags property)

**Comment by bblommers** [comment]
This is now available as of moto >= 1.3.16.dev124
