### ISSUE TITLE
allow injecting exceptions (e.g. network connection failures)

### ISSUE THREAD

**Issue by snarfed** [spulec/moto#346]
first of all, thanks for writing moto. we love it!

it'd be nice to be able to mock certain kinds of failures as well as successes. specifically, we'd like to make some S3 calls (e.g. `key.get_contents_to_filename` and `set_contents_from_file`) raise exceptions like `SocketError` or `IncompleteRead` to test our error handling.

thanks in advance!

**Comment by spulec** [comment]
Thanks!

I think the easiest way to do this is to use something like [mock](http://www.voidspace.org.uk/python/mock/). I don't have a good sense how we could integrate that into Moto (or if we should). Going to close for now, but feel free to reopen if you have other ideas.
