### ISSUE TITLE
Does not work with latest `responses`

### ISSUE THREAD

**Issue by rossmacarthur** [spulec/moto#3460]
Moto has a hack where it sets the default responses mock's `_find_match` method to a custom one. The latest changes in `responses` have changed the return type of this method.

https://github.com/spulec/moto/blob/47dbad291e717059a93f5cf795a9be08cfc872cc/moto/core/models.py#L248-L267

See the [`responses`](https://github.com/getsentry/responses) change here https://github.com/getsentry/responses/commit/cf3c5a685ae95bee1a714fd36cfb77d448a4b5ec

**Comment by garribas** [comment]
We are also affected by this bug and had to force installation of previous version of `responses` (0.12.0), with 0.12.1 it fails as described in the bug report:
https://github.com/spulec/moto/blob/master/setup.py#L43

**Comment by bblommers** [comment]
This is now fixed as of moto >= 1.3.16.dev122

**Comment by Jlrine2** [comment]
This doesn't seem to work with 1.3.16.dev122, Though I was able to get it working by using on of the 1.3.17.devX installs (specifically dev240)
