### ISSUE TITLE
SQS calling receive_message will cause deleting the message

### ISSUE THREAD

**Issue by jiangchuanheglobal** [spulec/moto#3465]
I'm using the SQS of `moto = "^1.3.16"` installed by Poetry. somehow I found calling the `receive_message` will cause deleting the message from the queue which is inconsistent with boto3. Because I'm assuming `receive_message` shouldn't delete the message unless calling the `delete_message` method, like in this [example](https://boto3.amazonaws.com/v1/documentation/api/1.9.42/guide/sqs-example-sending-receiving-msgs.html).

Here's the code I'm using

```
    @mock_sqs
    def test_moto(self):
        conn = boto3.client("sqs", region_name="us-east-1")
        sqs = boto3.resource('sqs', 'us-east-1')
        queue = sqs.create_queue(QueueName='votes')
        queue.send_message(MessageBody="hello_world!\n")

        print(f"\n---->{conn.receive_message(QueueUrl='votes')}")
        print(f"\n---->{conn.receive_message(QueueUrl='votes')}")
```

The body message "hello_world" won't show up in the 2nd print.

**Comment by bblommers** [comment]
Hi @jiangchuanheglobal, SQS will consider this message 'in-flight'. For the next 30 seconds, the message will be unavailable. If the message is deleted before that time, you will not receive it again.
If the application does not delete the message, it is assumed that processing failed, and the message will be send again.

I've just ran the example above against AWS itself, and it behaves exactly the same.

See for more information: https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-visibility-timeout.html

Note: `receive_message(QueueUrl='votes')` doesn't actually work against AWS, as it requires the full URL (https://sqs.region.amazonaws.com/ACCOUNT_ID/votes). 
The fact that Moto does accept 'votes' as an argument is a bug.

**Comment by jiangchuanheglobal** [comment]
oh, okay, got it. Thank you very much for this detailed explanation!
