### ISSUE TITLE
XML encoding is missing

### ISSUE THREAD

**Issue by ayushghosh** [spulec/moto#3469]
When generating XML for the responses the values/attributes are not escaped. Thus it breaks when the payload contains characters that need to be escaped to be compliant.
Ex: I was using though https://github.com/localstack/localstack
When creating route53 record with escaped character &
`{
            "Comment": "CREATE/DELETE/UPSERT a record ",
            "Changes": [{
            "Action": "UPSERT",
                        "ResourceRecordSet": {
                                    "Name": "b.example.com",
                                    "Type": "TXT",
                                    "TTL": 300,
                                 "ResourceRecords": [{ "Value": "MyValue&NewValue"}]
}}]
}`

Response:
`
<ListResourceRecordSetsResponse xmlns="https://route53.amazonaws.com/doc/2012-12-12/">
   <ResourceRecordSets>
      <ResourceRecordSet>
                <Name>b.example.com.</Name>
                <Type>TXT</Type>
                    <TTL>300</TTL>
                <ResourceRecords>
                    <ResourceRecord>
                        <Value>MyValue&NewValue</Value>
                    </ResourceRecord>
                </ResourceRecords>
            </ResourceRecordSet>
   </ResourceRecordSets>
   <IsTruncated>false</IsTruncated>
</ListResourceRecordSetsResponse>
`

This generates error: Unable to parse response (not well-formed (invalid token): line 19, column 47), invalid XML received. Further retries may succeed:

I was able to make the jinja templates to work by escaping the attribute with "escape" filter

**Comment by bblommers** [comment]
Thanks for raising this @ayushghosh! Marking it as a bug.

**Comment by oidebrett** [comment]
I can recreate the issue with the following test case:

@mock_route53
def test_list_resource_records_with_ampersand():
    conn = boto3.client("route53", region_name="us-east-1")
    create_hosted_zone_response = conn.create_hosted_zone(
        Name="db.",
        CallerReference=str(hash("foo")),
        HostedZoneConfig=dict(PrivateZone=True, Comment="db"),
    )
    hosted_zone_id = create_hosted_zone_response["HostedZone"]["Id"]

    def create_resource_record_set(rec_type, rec_name):
        payload = {
            "Comment": "create {} record {}".format(rec_type, rec_name),
            "Changes": [
                {
                    "Action": "UPSERT",
                    "ResourceRecordSet": {
                        "Name": rec_name,
                        "Type": rec_type,
                        "TTL": 300,
                        "ResourceRecords": [{"Value": "MyValue&NewValue"}],
                    },
                }
            ],
        }
        conn.change_resource_record_sets(
            HostedZoneId=hosted_zone_id, ChangeBatch=payload
        )
        
    # record_type, record_name
    all_records = [
        ("TXT", "a.c.db.")
    ]
    for record_type, record_name in all_records:
        create_resource_record_set(record_type, record_name)

    response = conn.list_resource_record_sets(
        HostedZoneId=hosted_zone_id,
        StartRecordType=all_records[0][0],
        StartRecordName=all_records[0][1],
    )
    assert response["ResourceRecordSets"][0]["ResourceRecords"][0]["Value"] == "MyValue&NewValue"

And I think a simple fix is at line 151 in responses.py 
x["Value"].replace('&', '&amp;') for x in resource_records
    
I will look at this a little more this week and make a Pull Request for it. I wonder if there are any more characters that would need to be replaced?

**Comment by bblommers** [comment]
@oidebrett I haven't tested it, but you might get away with HTML encoding the payload? That should take care of all special characters. Might be worth testing with other chars as well after that (spaces etc)

**Comment by ayushghosh** [comment]
@bblommers @oidebrett I have created a PR for the fix which uses Jinja2 functionality itself for the work.
https://github.com/spulec/moto/pull/3473
Have been using this patch successfully in our setup of localstack to overcome the issue
Please review

**Comment by oidebrett** [comment]
Looks good @ayushghosh. Seems like a much better way to fix this.

**Comment by bblommers** [comment]
This is now fixed as of moto >= 1.3.16.dev129
