### ISSUE TITLE
dev release numbering doesn't work with pip-tools because it's not PEP 440 compliant

### ISSUE THREAD

**Issue by richunger** [spulec/moto#3478]
According to https://www.python.org/dev/peps/pep-0440/#summary-of-permitted-suffixes-and-relative-ordering
dev releases should be pre release numbers, not post. So, 1.3.16devX should be 1.3.17devX.

Practically, this means that pip-tools will take a requirements.in file with
moto>=1.3.16dev100
and output a requirements.txt file with
moto==1.3.16

Workaround is to specify an exact dependency in requirements.in:
moto==1.3.16dev100

but then you won't pick up new dev releases as they come out, or the final 1.3.17.

**Comment by richunger** [comment]
My clever colleague suggested a better workaround: `moto>=1.3.16dev100,!=1.3.16`

**Comment by bblommers** [comment]
Thanks for raising this @richunger - this is now fixed.
The first release post 1.3.16 is now 1.3.17.dev221
