### ISSUE TITLE
How to get the mock_lambda docker client?

### ISSUE THREAD

**Issue by YasunoriOka** [spulec/moto#3484]
I am using mock_lambda to perform the tests.
After running the test several times, the lambda cannot be called.
I get the following error.

`
botocore.handlers: DEBUG: Error loading quoted JSON
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/botocore/handlers.py", line 185, in decode_quoted_jsondoc
    value = json.loads(unquote(value))
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
`

Changing the IP address of the environment where the test is running will allow the test to run successfully.
Probably a limitation by Docker Hub.
https://docs.docker.com/docker-hub/download-rate-limit/

I think this could be resolved by logging in with the Docker Client used by mock_lambda.
How to get the mock_lambda docker client?

**Comment by bblommers** [comment]
Hi @YasunoriOka, if you use the decorators, you can use the following code:
```
f = lambda_backends[_lambda_region]._lambdas._functions[function_name][version or 'latest']
d_client = f.docker_client
d_client.login(..)
```
Notes:
 - Not sure how/if it's possible using the moto server
 - This is the internal API, so subject to change
 - I've only checked this on recent moto versions (>~ 1.3.16.dev110), but it should also work on older versions

**Comment by YasunoriOka** [comment]
Hi @bblommers ,It worked well.
Thank you very much.
