### ISSUE TITLE
DynamoDb schemas with moto: how can I avoid repeating myself (DRY principle)

### ISSUE THREAD

**Issue by boxabirds** [spulec/moto#3490]
Moto is really helpful and I'm looking to have a single version of the truth for my dynamodb schemas. Currently they're in a file called `dynamodb.yml` that contains a vanilla AWS Dynamo `Resources:` yaml fragment. I'd like that to be my single version of the truth.

What's the simplest way to ensure my unit tests use this information to avoid separate code for creating the schema? All the sample code I've found creates tables in a setup routine but that's repeating the schema. Db schemas are complex enough without needing to have two separate representations of them in two different formats. 

Guidance most appreciated!

**Comment by bblommers** [comment]
Hi @boxabirds, sounds like you can use CloudFormation to create the schema?
```
body = load_file("dynamodb.yml") # However you want to load the yaml-file..
conn = boto3.client("cloudformation", region_name="us-east-1")
conn.create_stack(StackName="unit_test_setup", TemplateBody=body)
```

**Comment by boxabirds** [comment]
Cool idea! Thanks! I’ll try it out and report back. Maybe then there could
be a wrapper that makes this part of a fixture.
