### ISSUE TITLE
Can't delete messages that are visible

### ISSUE THREAD

**Issue by Garrett-R** [spulec/moto#352]
Moto doesn't allow you to delete messages that are visible (i.e. their visibility timeout has expired).  You can reproduce this by spinning up moto with:

    moto_server sqs -p 5555

then executing this script, observing that the last assertion fails when it shouldn't.   

    import boto.sqs
    from boto.sqs.message import Message
    import time

    VISIBILITY_TIMEOUT = 5

    region = boto.sqs.regioninfo.RegionInfo(name='LOCAL', endpoint='localhost')
    sqs_conn = boto.connect_sqs('access-key', 'secret-key', is_secure=False, region=region, port=5555)
    new_queue = sqs_conn.create_queue('new-queue', visibility_timeout=VISIBILITY_TIMEOUT)

    m1 = Message()
    m1.set_body('Message 1!')
    new_queue.write(m1)

    assert new_queue.count() == 1

    m1_retrieved = new_queue.read()

    time.sleep(VISIBILITY_TIMEOUT+1)

    m1_retrieved.delete()

    assert new_queue.count() == 0

I verified on AWS that this script passes.  The offending line of code is [here](https://github.com/spulec/moto/blob/1f8253a1a1c3301806c47f9c6eeca86f5ec08edd/moto/sqs/models.py#L262).

**Comment by spulec** [comment]
Thanks for opening. You are correct. This should be fixed now.

**Comment by Garrett-R** [comment]
Awesome!
