### ISSUE TITLE
Ability to create snapshots with custom StartTime

### ISSUE THREAD

**Issue by sfc-gh-ssudakovich** [spulec/moto#3520]
The only way I was able to create an EBS snapshot is to call `ec2.create_snasphot`. This would use the current time from `utc_date_and_time` function. Sometimes it is useful to adjust the `StartTime`. What would be the best way to do that?

**Comment by bblommers** [comment]
Hi @sfc-gh-ssudakovich, are you using the decorators, or moto in Server Mode?

With the decorators, there are two options:
 - Use the `freezegun` dependency to hardcode all date/times for the duration of a specific test. [We use it in our internal tests as well](https://github.com/spulec/moto/blob/4c3f99d01968dc55e5c4d7d371f75fc578eb6600/tests/test_core/test_utils.py#L34)
 - Manually change the value of that specific property in the moto backends.
This would look something like:
```
from moto.ec2.models import ec2_backends
ec2_backend = ec2_backends[settings.AWS_REGION]
snapshot= ec2_backend.snapshots[snapshot_id]
snapshot.start_time = ...
```

Haven't tested this, so forgive any typos...

Let me know if this works for you.

**Comment by sergeyhush** [comment]
The `freezegun` solution worked perfectly. Thanks.
