### ISSUE TITLE
Moto doesn't have a __version__ dict

### ISSUE THREAD

**Issue by rallytime** [spulec/moto#353]
```
>>> import moto
>>> moto.__version__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute '__version__'
```
I ran across this bug when trying to implement some unit tests using boto and moto, and I need to check for a specific version of each before running some of my tests. I need some of the functionality in `moto >= 0.3.7`. It would be nice to be able to use `moto.__version__` to use with `LooseVersion` or something like that, like you can with other packages, like boto, for example:
```
def _has_required_boto():
    '''
    Returns True/False boolean depending on if Boto is installed and correct version.
    '''
    if not HAS_BOTO:
        return False
    elif LooseVersion(boto.__version__) < LooseVersion(required_boto_version):
        return False
    else:
        return True
```

**Comment by spulec** [comment]
Thanks for opening! I have added this and it should be available for the next version.

**Comment by rallytime** [comment]
Wonderful! Thanks so much for the quick fix. :)
