### ISSUE TITLE
@mock_s3 fails with mock==4.0.3 when decorating unittest.TestCase class

### ISSUE THREAD

**Issue by lewyh** [spulec/moto#3536]
Starting today, I am experiencing errors executing tests where `@mock_s3` is used to decorate a `unittest.TestCase` class. The version of the `mock` library installed as a dependency is now 4.0.3 (released 6 hours ago). By rolling back to 4.0.2, the tests work again.

**Code example**:
```
import unittest
import boto3
from moto import mock_s3


@mock_s3
class MockingIssue(unittest.TestCase):
    def test_mocking(self) -> None:
        conn = boto3.resource('s3', region_name='us-east-1')
        conn.create_bucket(Bucket='some_bucket')

        self.assertEqual(1, 1)
```

**Expected outcome**: Test passes

**Actual outcome**: Error as follows:
```
test_mock.py:7 (MockingIssue.test_mocking)
../../venv/lib/python3.7/site-packages/moto/core/models.py:102: in wrapper
    self.stop()
../../venv/lib/python3.7/site-packages/moto/core/models.py:86: in stop
    self.default_session_mock.stop()
../../venv/lib/python3.7/site-packages/mock/mock.py:1563: in stop
    return self.__exit__(None, None, None)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <mock.mock._patch object at 0x10f6fbd50>, exc_info = (None, None, None)

    def __exit__(self, *exc_info):
        """Undo the patch."""
>       if self.is_local and self.temp_original is not DEFAULT:
E       AttributeError: '_patch' object has no attribute 'is_local'

../../venv/lib/python3.7/site-packages/mock/mock.py:1529: AttributeError
```

This issue doesn't occur when decorating the test methods directly, however I have tests where I want to decorate the class (thereby affecting setUpClass methods).

**Environment**:
Python 3.7.7
moto==1.3.16
boto3==1.16.7
botocore==1.19.33
mock==4.0.3 (as installed when moto is installed via `pip`)

**Comment by bblommers** [comment]
Hi @lewyh, this was already raised in #3535, so I'll close this as a duplicate.
