### ISSUE TITLE
Asserts in LogResponse prevent boto3 ClientError when testing

### ISSUE THREAD

**Issue by cciotti** [spulec/moto#3548]
I have some code that fetches CloudWatch logs and in my tests I used moto to mock CloudWatch. I added a test that exceeded the 10,000 max events and instead of getting a `ClientError` from botocore, I got an assertion error from moto. This was not expected. I see in `LogResponse` [`get_log_events`](https://github.com/spulec/moto/blob/9eb58eea411214ded617ea45ce9a4407a8f95194/moto/logs/responses.py#L96) the statement `assert limit <= 10000`. There are a few in this class. Is this by design?

`boto3==1.16.28`
`moto==1.3.16`
`python 3.6.10`

**Comment by bblommers** [comment]
Looks like a dirty workaround, @cciotti. Thanks for raising it - marking it as an enhancement to implement proper error handling.
