### ISSUE TITLE
mock_elbv2: ResourceInUseException after trying to delete a target group that was a listener DefaultAction

### ISSUE THREAD

**Issue by npellegrin** [spulec/moto#3554]
**how to reproduce the issue**

When changing the DefaultAction of a loadbalancer's listener, the old TargetGroup cannot be deleted.

**code sample (simplified)**
```
target_group_arn_1 = client.create_target_group(...)["TargetGroups"][0]["TargetGroupArn"]
target_group_arn_2 = client.create_target_group(...)["TargetGroups"][0]["TargetGroupArn"]
listener_arn = client.create_listener(
        LoadBalancerArn=load_balancer_arn,
        Protocol='HTTP',
        Port=80,
        DefaultActions=[{'Type': 'forward', 'TargetGroupArn': target_group_arn_1}])["Listeners"][0]["LoadBalancerArn"]
client.modify_listener(
                            ListenerArn=listener_arn,
                            DefaultActions=[{
                                'Type': 'forward',
                                'TargetGroupArn': target_group_arn_2,
                            }])
client.delete_target_group(TargetGroupArn=target_group_arn_1)
```

**what you expected to happen**.

I would expect to delete the target group, because it is not attached to the listener anymore.

**what actually happens**

The following error is raised:

`botocore.errorfactory.ResourceInUseException: An error occurred (ResourceInUse) when calling the DeleteTargetGroup operation: The target group 'arn:aws:elasticloadbalancing:eu-west-3:1:targetgroup/TEST/50dc6c495c0c9188' is currently in use by a listener or a rule`

**analysis**

I've walked throught the moto's source code and I believe to have found rootcause (but feel free to tell me if not !)
In the file `moto/moto/elbv2/models.py` the ResourceInUseError is thrown because moto detects that the target group is in use in any of the `rules`:

```
    def _any_listener_using(self, target_group_arn):
        for load_balancer in self.load_balancers.values():
            for listener in load_balancer.listeners.values():
                for rule in listener.rules:
                    for action in rule.actions:
                        if action.data.get("target_group_arn") == target_group_arn:
                            return True
        return False
```

The `listener.rules` object is build like that:
```
    @property
    def rules(self):
        return self._non_default_rules + [self._default_rule]
```

The `self._default_rule` is created only when the listener is created:
```
        self._default_rule = FakeRule(
            listener_arn=self.arn,
            conditions=[],
            priority="default",
            actions=default_actions,
            is_default=True,
        )
```

But, when updating default actions, the object reference is replaced, without updating _default_rule:
```
        if default_actions is not None and default_actions != []:
            # Is currently not validated
            listener.default_actions = default_actions
```

Consequently, the `_default_rule` is never updated, the `rules` property still return a stale reference, and moto believes that the TargetGroup is still attached to the listener.

**Comment by bblommers** [comment]
Thanks for raising and debugging this, @npellegrin! Much appreciated.
Marking it as a bug.
