### ISSUE TITLE
Support Sagemaker Notebook Instance on Cloud Formation

### ISSUE THREAD

**Issue by vineeth-450** [spulec/moto#3568]
Moto's CloudFormation mock does not support AWS::SageMaker::NotebookInstance .

When I execute a create_stack operation on a CloudFormation template that creates AWS::SageMaker::NotebookInstance, the follwing warning is returned:
`UserWarning: Tried to parse AWS::SageMaker::NotebookInstance but it's not supported by moto's CloudFormation implementation`

Are there plans on implementing the above ?

**Comment by bblommers** [comment]
Thanks @vineeth-450 - looks like we're not supporting any SageMaker models at the moment.
Marking it as an enhancement.

**Comment by bblommers** [comment]
This is now part of moto >= 2.0.5.dev17
