### ISSUE TITLE
How do I store multiple aws secrets? 

### ISSUE THREAD

**Issue by red8888** [spulec/moto#3569]
I have this issue but looks like this was supposed to be fixed? https://github.com/spulec/moto/issues/1893

```
conn = boto3.client("secretsmanager", region_name="us-west-1")
secrets = ["one", "two", "three"]
for secret in secrets:
   conn.create_secret(Name=secret, SecretString="sdfsdfsd")
mymodule.method_that_gets_value_of_bunch_of_secrets("one", "two", "three")
```

The `method_that_gets_value_of_bunch_of_secrets()` gets the value of several secrets and does stuff

create_secret() can only store one secret it looks like- or maybe Im using it wrong? 

I want to create 3 secrets and have them available to my method

Im not using the list secrets method. I just want to store multiple secrets and call a method that gets their value

**Comment by bblommers** [comment]
What version are you using, @red8888? The following code retrieves all three secrets in 1.3.16:
```
import boto3
from moto import mock_secretsmanager


with mock_secretsmanager():
	conn = boto3.client("secretsmanager", region_name="us-west-1")
	secrets = ["one", "two", "three"]
	for secret in secrets:
		conn.create_secret(Name=secret, SecretString="sdfsdfsd")

	secs = conn.list_secrets()
	print(secs["SecretList"])
	for secret in secrets:
		print(conn.get_secret_value(SecretId=secret))
```

**Comment by bblommers** [comment]
Closing this due to a lack of response - feel free to reopen if there's still an issue with this
