### ISSUE TITLE
Return value of GlueClient.get_database does not return full AWS API Database object.

### ISSUE THREAD

**Issue by aaronfowles-emis** [spulec/moto#3571]
I could not find an existing issue so I'm creating this. Please let me know if there's anything else I can do 😄 .

## Description

The problem is that `boto3.Session().client("glue").get_database(Name="...")` does not return a payload with the correct [schema](https://docs.aws.amazon.com/glue/latest/webapi/API_GetDatabase.html).

We would also need to allow `boto3.Session().client("glue").create_database(CatalogId="...", DatabaseInput="...")` to fully use all fields of [DatabaseInput](https://docs.aws.amazon.com/glue/latest/webapi/API_CreateDatabase.html#API_CreateDatabase_RequestSyntax).

## Current behaviour
```python
import moto

with moto.mock_glue():
  glue = boto3.Session().client("glue")
  glue.create_database(
      CatalogId=glue_catalog_id,
      DatabaseInput={
          "Name": "myspecialdatabase",
          "Description": "...",
          "LocationUri": "...",
          "CreateTableDefaultPermissions": [],
          "TargetDatabase": {
              "CatalogId": "...",
              "DatabaseName": "myspecialdatabase",
          },
      },
  )
  print(glue.get_database(Name="myspecialdatabase"))

... 
{
  "Database": {
    "Name": "myspecialdatabase"
  }
}
```

## Desired Behaviour
```python
import moto

with moto.mock_glue():
  glue = boto3.Session().client("glue")
  glue.create_database(
      CatalogId=glue_catalog_id,
      DatabaseInput={
          "Name": "myspecialdatabase",
          "Description": "...",
          "LocationUri": "...",
          "CreateTableDefaultPermissions": [],
          "TargetDatabase": {
              "CatalogId": "...",
              "DatabaseName": "myspecialdatabase",
          },
      },
  )
  print(glue.get_database(Name="myspecialdatabase"))

... 
{
   "Database": { 
      "CatalogId": "...",
      "CreateTableDefaultPermissions": [ ],
      "CreateTime": ...,
      "Description": "...",
      "LocationUri": "...",
      "Name": "myspecialdatabase",
      "Parameters": {},
      "TargetDatabase": { 
         "CatalogId": "...",
         "DatabaseName": ""myspecialdatabase""
      }
   }
}
```

**Comment by bblommers** [comment]
This is now part of moto >= 1.3.16.dev196

**Comment by timforby** [comment]
This is still not fully solved, the CatalogId is not correctly handled. As seen in the Boto3 docs for [create_database](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/glue.html#Glue.Client.create_database) the call is made with CatalogId and DatabaseInput. 

This means that in the [glue/responses.py](https://github.com/spulec/moto/blob/004c971a27d00b7a76b42f88cf3b095f672fff17/moto/glue/responses.py#L21) the CatalagId should be placed in the DatabaseInput or handled like database_name.

My suggestion would be the following:

```python
    def create_database(self):
        database_input = self.parameters.get("DatabaseInput")
        database_name = database_input.get("Name")
        if 'CatalogId' in self.parameters:
            database_input["CatalogId"] = self.parameters.get("CatalogId")
        self.glue_backend.create_database(database_name, database_input)
        return ""
```

**Comment by jamesgunnfiveai** [comment]
I thought the AWS glue API returns `CatalogId` with a call to `get_database` regardless of whether `CatalogId` is specified in the request to get the database nor during creation. I don't believe that moto does this. Would it be possible to add this to moto to match the AWS API or is it not sensible given that the concept of "current AWS account" doesn't mean anything within moto?

**Comment by bblommers** [comment]
Hi @jamesgunnfiveai, [as of Moto v4 we do have a concept of current AWS account](http://docs.getmoto.org/en/latest/docs/multi_account.html), so if that needs to change to match AWS' behaviour.. PR's are always welcome!

**Comment by jamesgunnfiveai** [comment]
Thanks for the reference @bblommers, I'll take a look and see what I can cook up!

**Comment by timforby** [comment]
@jamesgunnfiveai if you do look into it take care that databases can also be resource links to other accounts, which means the catalogId can vary. Not sure if that has to be explicitly handled but just thought to mention it.

**Comment by jamesgunnfiveai** [comment]
Thanks folks for the pointers. In the end I resolved this blocking our deployment by avoiding cross-account glue access completely so I won't be adding this to moto. Hopefully the above info is useful for someone who does need it however.
