### ISSUE TITLE
Cannot mock S3 client with io

### ISSUE THREAD

**Issue by tnorlund** [spulec/moto#3573]
I'm attempting to mock my Lambda function that crawls through an S3 bucket and parses '.parquet' files. When I attempt to test this locally, I currently get this error:

`OSError: Could not open parquet input source '<Buffer>': Invalid: Parquet magic bytes not found in footer. Either the file is corrupted or this is not a parquet file.`

I'd like to 
1. upload the '.parquet' file to the mocked bucket
2. read the file from the bucket using `io.BytesIO( request.read() )`
3. test the function

I currently test the function like this:
```python
def test_processParquet( table_name, bucket_name, visits, browsers ):
  pd.DataFrame( {
    'id': [
        visit.date.strftime( '%Y-%m-%dT%H:%M:%S.' ) + \
        visit.date.strftime('%f')[:3] + 'Z'
        for visit in visits
    ],
    'title': [visit.title for visit in visits],
    'slug': [visit.slug for visit in visits],
    'ip': [visit.ip for visit in visits],
    'user': [visit.user for visit in visits],
    'app': [browsers[0].app for index in range( len( visits ) )],
    'height': [browsers[0].height for index in range( len( visits ) )],
    'width': [browsers[0].width for index in range( len( visits ) )]
  } ).to_parquet('test.parquet')
  dynamo_client = DynamoClient( table_name )
  s3_client = S3Client( bucket_name )
  s3_client.putObject( 'test.parquet', 'test.parquet' )
  processParquet( 'test.parquet', dynamo_client, s3_client )
  os.remove( 'test.parquet' )
```

The `processParquet` function access the S3 bucket like this:
```python
# Read the parquet file as a pandas DF
df = pd.read_parquet( io.BytesIO( request['Body'].read() ) )
```

How do I mock the reading of the file from the bucket?

**Comment by bblommers** [comment]
Hi @tnorlund, the `request['Body'].read()` should be all you need.

Do you have a small reproducible example, by any chance?

**Comment by tnorlund** [comment]
Here's the [repository](https://github.com/tnorlund/aws-analytics) and the [file](https://github.com/tnorlund/aws-analytics/blob/main/test/test_processing.py) in question. I ended up commenting it out because it fails. The `request['Body'].read()` doesn't print the contents of the file.

**Comment by tnorlund** [comment]
Thanks @bblommers! I'll close the issue.
