### ISSUE TITLE
importlib_resources is not mentioned in requirements

### ISSUE THREAD

**Issue by bnavigator** [spulec/moto#3576]
The package `importlib-resources` should be added to the appropriate place of your requirements setup, at least for Python < 3.7, as you use it here:

https://github.com/spulec/moto/blob/9bc6bded6e6472f04a45f0bc429acc926c2cdc08/moto/dynamodb2/parsing/reserved_keywords.py#L21-L24

**Comment by bblommers** [comment]
Thanks for raising this @bnavigator!
