### ISSUE TITLE
Route53 responses.py iterates over a list as a dict

### ISSUE THREAD

**Issue by dkhandeshi** [spulec/moto#358]
moto.route53.responses.py: line 58:
```
record_set['ResourceRecords'] = [x['Value'] for x in record_set['ResourceRecords'].values()]
```
`x` is a list not dict. this causes the code to fail when creating an rr change set and committing it.

**Comment by dkhandeshi** [comment]
Essentially it appears that if an RR is created with a single value (IP address for an A record), the `record_set` holds a single value of type `OrderedDict`. But if an A record were to be created with multiple IP addresses then the `record_set` holds a `list` of `OrderedDict`s.

**Comment by spulec** [comment]
Thanks for opening the issue! This should be fixed now.

**Comment by dkhandeshi** [comment]
Thanks for the rapid fix! Will there be a release soon?

BTW, there appears to be an issue with zone.get_() on A records with multiple IP addresses. The zone.get_a() call returns None. The above fix handles the creation of an A record with multiple IPs which cannot be be retrieved. I will see if I can post some code and open a separate issue to reproduce this.

**Comment by spulec** [comment]
Just pushed version `0.4.3`.

I wasn't able to recreate the issue with `zone.get_a()`. I originally thought I had, but then realized that I was not providing fully-qualified domains. If you are able to get some code up and open another issue, that would be great.
