### ISSUE TITLE
Implementation Coverage is wrong?

### ISSUE THREAD

**Issue by omar-ogm** [spulec/moto#3599]
Hi,

I'm new to this great library so please if my understanding about it is wrong just let me know.

I would like to point that I've found discordance between the examples on the README.md and the IMPLEMENTATION_COVERAGE.md.  

In the README.md there is an example that uses **describe_instances**

```
from . import add_servers
from moto import mock_ec2

@mock_ec2
def test_add_servers():
    add_servers('ami-1234abcd', 2)

    client = boto3.client('ec2', region_name='us-west-1')
    instances = client.describe_instances()['Reservations'][0]['Instances']
    assert len(instances) == 2
    instance1 = instances[0]
    assert instance1['ImageId'] == 'ami-1234abcd'

```

And then on the IMPLEMENTATION_COVERAGE.md the **describe_instances** is not marked as implemented.
Is the IMPLEMENTATION_COVERAGE not up to date or is this an error?

Thanks.

**Comment by bblommers** [comment]
Hi @omar-ogm, thanks for raising this!
`describe_instances()` is definitely supported. The IMPLEMENTATION_COVERAGE doc is generated automatically, so it's either out of date or there's a bug that causes it not to pick up that specific method. Will look into it.
