### ISSUE TITLE
Feature Request: make mock_resourcegroupstaggingapi compatible with loadbalancer resources.

### ISSUE THREAD

**Issue by sergeisantoyo** [spulec/moto#3606]
I need to create an unit test to verify that a tag gets well created in an ALB.

I found a similar test under tests/test_resourcegroupstaggingapi/test_resourcegroupstaggingapi.py.

Can someone tell me what version of moto I need to make this specific test pass? I tried to run it using moto 1.3.14 with no success.

**Comment by bblommers** [comment]
Hi @sergeisantoyo, looks like a basic version was already present in moto 1.3.5. 

Can you share your test case? That might be easier to debug what's going wrong.

**Comment by bblommers** [comment]
Closing this due to a lack of response - feel free to reopen if there's still an issue with this
