### ISSUE TITLE
sqs receive_message returns AttributeNames when not requested

### ISSUE THREAD

**Issue by clowtown** [spulec/moto#3607]
This behavior deviates from the [boto3 documentation](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sqs.html#SQS.Client.receive_message). No default option is listed for `AttributeNames`, however moto returns, unconditionally, attributes such as `ApproximateReceiveCount`. This leads to false positive unit tests in which attributes are relied upon, but are not available when interacting without moto.

https://github.com/spulec/moto/blob/2bdba88389e5c3ee83bcbf719bbbaa1da0f81ede/moto/sqs/responses.py#L549

python 3.6
moto== 1.3.16
boto==2.49.0
boto3=1.16.31
botocore=1.19.36

Below are two test cases:
`test_default_behavior` currently fails and **should not** according to boto3 execution of the same call.
`test_requested_message_attributes` currently passes and **should** according to boto3 execution of the same call.

```
import unittest
import boto3
from moto import mock_sqs

@mock_sqs
class TestIssue(unittest.TestCase):
    def test_default_behavior(self):
        sqs = boto3.resource("sqs")
        queue = sqs.create_queue(QueueName="a_queue")
        queue.send_message(MessageBody="health", DelaySeconds=0)
        session = boto3.session.Session()
        sqs_client = session.client("sqs")
        response = sqs_client.receive_message(
            QueueUrl=queue.url,
            MaxNumberOfMessages=1,
            # AttributeNames=[
            #     'ApproximateReceiveCount',
            # ],
            VisibilityTimeout=30,
            WaitTimeSeconds=2,
        )
        message = response["Messages"][0]
        self.assertEqual("health", message["Body"])
        self.assertIsNone(message["Attributes"])

    def test_requested_message_attributes(self):
        sqs = boto3.resource("sqs")
        queue = sqs.create_queue(QueueName="a_queue")
        queue.send_message(MessageBody="health", DelaySeconds=0)
        session = boto3.session.Session()
        sqs_client = session.client("sqs")
        response = sqs_client.receive_message(
            QueueUrl=queue.url,
            MaxNumberOfMessages=1,
            AttributeNames=[
                "ApproximateReceiveCount",
            ],
            VisibilityTimeout=30,
            WaitTimeSeconds=2,
        )
        message = response["Messages"][0]
        self.assertEqual("health", message["Body"])
        self.assertIsNotNone(message["Attributes"])
        self.assertIsNotNone(message["Attributes"]["ApproximateReceiveCount"])
        self.assertEqual("1", message["Attributes"]["ApproximateReceiveCount"])
```

**Comment by bblommers** [comment]
Thanks for raising this @clowtown - marking this as an enhancement

**Comment by clowtown** [comment]
@bblommers - why an enhancement? Is there some older behavior that this aligned with? The false positives on unit tests was my main concern and why I opened as an issuse.

**Comment by bblommers** [comment]
Hey @clowtown, the enhancements label indicates unimplemented behaviour, or a use case that's not yet accounted for (like not supplying a specific argument).

The other possible label is 'bug', for things that are wrong implementations of a specific use case.

**Comment by clowtown** [comment]
@bblommers - I won't debate semantics with enhancement or issue, but I still feel that it's a wrong implementation of the client method. I don't have any boto/aws history to dispute either case. so I'll see about submitting a pr for it this week.
