### ISSUE TITLE
mock_redshift get_cluster_credentials support

### ISSUE THREAD

**Issue by dreamorosi** [spulec/moto#3609]
On moto 1.3.16 the [Redshift `get_cluster_credentials()`](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/redshift.html#Redshift.Client.get_cluster_credentials) endpoint is not implemented.

As detailed in the documentation, the method:
> Returns a database user name and temporary password with temporary authorization to log on to an Amazon Redshift database.

and has signature:
```py
response = client.get_cluster_credentials(
    DbUser='string',
    DbName='string',
    ClusterIdentifier='string',
    DurationSeconds=123,
    AutoCreate=True|False,
    DbGroups=[
        'string',
    ]
)
```

My proposal is to implement the method in the following way:
* `ClusterIdentifier` parameter must pass validation against existing clusters, if not `ClusterNotFoundError` is raised.
* `DurationSeconds` must have a value between `900` and `3600`, if not `InvalidParameterValueError` is raised.
* `DbUser` can have any value, no validation on the value is applied; this is consistent with the moto's current implementation of `create_cluster`.
* `AutoCreate` default value is `False` (undocumented but tested against real Redshift Cluster);
*  * if `AutoCreate==False`; then returned `DbUser` is prefixed with `IAM:`.
*  * if `AutoCreate==True`; then returned `DbUser` is prefixed with `IAMA:`.
* `DbGroups` and `DbName` parameters are ignored.
* The password generated is an alphanumeric string with no actual value and length of 32 characters.

If the above is okay I am happy to open a PR.

**Comment by bblommers** [comment]
Sounds good to me @dreamorosi - PR's are always welcome!

**Comment by bblommers** [comment]
This is now part of moto >= 1.3.16.dev215
