### ISSUE TITLE
Python 2.7 deprecation

### ISSUE THREAD

**Issue by dreamorosi** [spulec/moto#3612]
In 6 months from now `boto3` will finally drop support for Python 2.7:
> Boto3 will no longer support Python 2.7 starting July 15, 2021. To continue receiving service updates, bug fixes, and security updates please upgrade to Python 3.6 or later. More information can be found here: https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-python-2-7-in-aws-sdk-for-python-and-aws-cli-v1/

Python 2.7 reached EOL already several months ago, what are `moto`'s plans on the topic?

**Comment by spulec** [comment]
As long as boto3 is still supporting it, I think it makes sense for us to do so as well.

After July, I am potentially open to dropping support, but don't have strong feelings one way or the other.

**Comment by bblommers** [comment]
Python 2.x is now no longer supported as of Moto 2.2.x.
