### ISSUE TITLE
Question: Support for KMS?

### ISSUE THREAD

**Issue by eshyong** [spulec/moto#362]
Is support for KMS on the roadmap? I'm not very familiar with the moto library but I'd be happy to help contribute towards KMS support.

**Comment by spulec** [comment]
I don't currently have any plans to add it. A pull request would be happily accepted. Alternatively, if there are a few key endpoints that you would like, feel free to add them to this ticket and I will take a shot at it when I get some time.

**Comment by eshyong** [comment]
Thanks for replying to my ticket! I don't currently have the bandwidth to implement this, and I have no immediate need, but I'd be more than happy to revisit this in the future.

**Comment by spulec** [comment]
Added some basic endpoints with #368.

**Comment by spulec** [comment]
Closing this out given #368. Feel free to open additional issues for other endpoints.
