### ISSUE TITLE
Upgrading from 1.3.14 to 1.3.16 : performance issues

### ISSUE THREAD

**Issue by laurabegin** [spulec/moto#3633]
Hi !

I use moto (Python mocks) to unit test lambda functions with the unittest framework. Until today, my versions were :
* moto : 1.3.14
* boto : 2.49.0
* botocore : 1.16.26
* boto3 : 1.13.25

All my 30 tests ran in 6 seconds approximately. I ran into an issue with a test that I found out had been fixed in the 1.3.16 version of moto. After upgrading to the newest version, all my tests now run in 40 seconds. I tried upgrading boto, boto3 and botocore to their latest versions but I still face the same performance issues. Now, my versions are : 
* moto : 1.3.16
* boto : 2.49.0
* botocore : 1.19.62
* boto3 : 1.16.62

In my tests, I only use @mock_s3, @mock_kinesis and @mock_dynamodb2. I set up one or two s3 buckets, one kinesis stream, and one or two dynamo tables per test file (I have 6) and I delete everything when I tear down the test.

Thanks a lot ! I can provide more details if needed.

**Comment by bblommers** [comment]
Hi @laurabegin, that's interesting. The only major performance change that we introduced that I can recall was a lazy loading of imports, which should reduce the overall time.

Is the increased test duration spread across all tests, or is there one specific slow test?
Can you share a reproducible test case?

**Comment by laurabegin** [comment]
Hi @bblommers, thanks for responding. You can close this issue, the slow performance was an issue on my end that coincidentally happened after upgrading moto. It was not related to moto.
