### ISSUE TITLE
Moto.dynamodb2 doesn't fail when using reserved keywords in ConditionExpression

### ISSUE THREAD

**Issue by jpverdejo-FF** [spulec/moto#3635]
# How to reproduce the issue?

Call `.update_item` method with a reserved keyword in a condition expression

```python
resource.update_item(
    Key={ "identity": id },
    UpdateExpression="set #state = :state",
    ExpressionAttributeNames={ "#state": "state" },
    ExpressionAttributeValues={ ":state": "VERIFIED" },
    ConditionExpression="attribute_exists(identity)",
)
```
In this case I'm using `identity`, which is a [reserved word](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/ReservedWords.html) in dynamo, directly in the expression.

This issue is happening consistently

# Expected

`update_item()` raises `AttributeIsReservedKeyword` since `identity` is used directly in the `ConditionExpression`, forcing me to use it as an attribute name like

```python
resource.update_item(
    Key={ "identity": id },
    UpdateExpression="set #state = :state",
    ExpressionAttributeNames={ "#state": "state", "#identity": "identity" },
    ExpressionAttributeValues={ ":state": "VERIFIED" },
    ConditionExpression="attribute_exists(#identity)",
)
```

# Actual

The item is updated correctly and it doesn't raise the exception

# Version used
Moto 1.3.16

**Comment by bblommers** [comment]
Thanks for raising this @jpverdejo-FF - will mark it as an enhancement

**Comment by jpverdejo-FF** [comment]
Thanks @bblommers and @Guriido!
