### ISSUE TITLE
How to set content length on S3 file

### ISSUE THREAD

**Issue by pwerth** [spulec/moto#3660]
I want to test a function that gets a formatted file size from an S3 object:

```
def get_formatted_file_size(key: str) -> str:

s3_client = boto3.client('s3')
response = s3_client.head_object(Bucket='my-bucket', Key=key)
file_size_bytes = response['ContentLength']
...
<< logic to return a formatted string like '125 KB' or '1.2 GB' >>
```

I would like to test this without actually uploading a large file, so I want to do something like:

```
@mock_s3
def test_get_formatted_file_size():
    s3 = boto3.resource('s3')
    s3.create_bucket(Bucket='my-bucket')
    s3.Object('my-bucket', 'test.txt').put(Body='')
    # AttributeError: can't set attribute
    moto.s3.models.s3_backend.buckets['my-bucket'].keys['test.txt'].size = 5500000
    assert get_formatted_file_size('test.txt') == '5.5 MB'
```

I have a similar unit test that requires knowledge of the `last_modified_at` field, and in that test I am able to dynamically set that property like:

```
moto.s3.models.s3_backend.buckets['my-bucket'].keys['test.txt'].last_modified = datetime.datetime(2020, 1, 1)
```

Is there an equivalent for setting content length? The code above generates an error, as I indicate in the comment

**Comment by bblommers** [comment]
Hi @pwerth, I can't test it out at the moment, but does this work?
`moto.s3.models.s3_backend.buckets['my-bucket'].keys['test.txt'].contentsize = 5500000`

This property is only set when the actual value is set, so you might need to use more than just an empty string:
`s3.Object('my-bucket', 'test.txt').put(Body='small value')`

**Comment by pwerth** [comment]
@bblommers Yes, it looks like `contentSize` was what I needed. Thanks! And btw, the empty string worked just fine.

**Comment by bblommers** [comment]
👍

**Comment by czechnology** [comment]
FYI, in newer versions you have to use:
```py
moto.s3.models.s3_backends["123456789012"]["global"].buckets["my-bucket"].keys['test.txt'].contentsize = 5500000
```
