### ISSUE TITLE
Feature Request: Starting of moto_server within Python

### ISSUE THREAD

**Issue by dagrimmy** [spulec/moto#3664]
Hello :)

Thanks for developing and improving this great and helpful library!

Versions we used: 
* moto==1.3.16
* moto[server]==1.3.16

Here's our feature request (I used the search function but didn't find a similar request):

* Current state: 
  * We are using a s3 moto standalone server for mocking our production s3 bucket
  * We don't want to start the moto s3 server outside of our Python code to keep our tests as self-contained as possible
  * This is why we currently run the moto with subprocess inside our Python tests:
     ```python
     nohup_out = os.path.join(SCRIPT_DIR, 'integration_test_nohup.out')
     command = [f"nohup moto_server s3 > {nohup_out} 2> {nohup_out}"]
     ```
* Our concerns with this:
  * We have to mess around with os stuff to make sure the server is running as expected and is killed after we're done with testing
* What we would like to have:
  * Starting and stopping of the moto server inside our Python code. 
  * Simplified, we run code that might look like this: 
    * `from moto import moto_server`
    * `server = moto_server.run("s3", "<host>:<port>")`
    * (do testing)
    * `server.stop()`

We don't care too much how the interface to the server looks like we would just be glad to have one to get aroud
os stuff.

This feature would really help us in our testing design!

It would be cool if you could give us feedback on this and tell us why it might (not) be a good idea :)

**We're also willing to write the code on our own and do a pull request if you think the feature would be good to have**

**Comment by bblommers** [comment]
Hi @dagrimmy, good to hear moto is useful to you!

It sounds like this is what you're after: https://github.com/spulec/moto/issues/1015
We don't support it yet, but the gist that's linked in that issue should be a good starting point to write your own service/wrapper/decorator/however you want to use it

**Comment by dagrimmy** [comment]
Thanks for the fast answer, we'll look into the linked issue :)

**Comment by bblommers** [comment]
Hi @dagrimmy, Moto 3.0.6 now includes a way to start the MotoServer programmatically.
See the documentation here: http://docs.getmoto.org/en/latest/docs/server_mode.html#start-within-python

It is still in beta while we collect feedback, so if you find any bugs or improvements, feel free to open a new issue!
