### ISSUE TITLE
Add KmsKeyId to Redshift Cluster

### ISSUE THREAD

**Issue by jnsf-cg** [spulec/moto#3665]
When creating a new [Redshift cluster](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-redshift-cluster.html#aws-resource-redshift-cluster-properties), specifying the `KmsKeyId` does not persist to the redshift backend. This results in the `KmsKeyId` not being returned when querying for clusters using the [describe_clusters](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/redshift.html#Redshift.Client.describe_clusters) boto3 function.

**Comment by bblommers** [comment]
This is now part of moto >= 1.3.17.dev246
