### ISSUE TITLE
better s3 post support for success_action_redirect

### ISSUE THREAD

**Issue by wynnw** [spulec/moto#3667]
The success_action_redirect value that is supported by s3 posts doesn't match how s3 works in production in a couple of ways that does not allow me to fully test my s3 integration code. Missing features are:

- automatic addition of the bucket and key values to the success_action_redirect query args. I can't find exact documentation for this behavior, but this page references it:
https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPOST.html

and it's how it works and we rely  on that behavior.

- automatic replacement of ${filename} in the form key value. Same issue as the above with documentation.

**Comment by bblommers** [comment]
This is now part of moto >= 1.3.17.dev248

**Comment by wynnw** [comment]
Thanks for the reviews! Great project, has saved us a lot of time - we're big fans.
