### ISSUE TITLE
cryptography 3.4 package requires Rust dependency, set max requirement to <=3.3.1

### ISSUE THREAD

**Issue by vfrank66** [spulec/moto#3673]
A dependency of moto is the cryptography package, as of 3.4 they now require a dependency on rust for installation. For anyone installing moto this now requires rust installation because the requirement for cryptography >= 2.3.

Please set a max crytography version to 3.3.1 so that we do not need rust to intsall moto.

cryptography github discussion:
https://github.com/pyca/cryptography/issues/5771

**Comment by bblommers** [comment]
Thanks for raising this @vfrank66. I wasn't aware of that release (and the discussion around it) at all.

IMO, it's not for Moto to decide the security vs usability argument for upstream projects. People who are able to, and prefer to be up to date, should be able to use the latest cryptography-release. Others who are not able to use Rust, can pin cryptography in their own requirements.

From our side, we just have to make sure we never require cryptography >= 3.4

@spulec Any thoughts on this?

**Comment by vfrank66** [comment]
@bblommers that is understandable. 

The only reason I bring it up here in moto, when it really should not be a moto problem, is we recently had a bunch of builds break on installing moto. We pin moto but not cryptography because we do not specifically use cryptography

**Comment by spulec** [comment]
Huh, well that was a fun thread to read through on a Sunday morning (the pyca thread, not this one).

I think I agree with @bblommers in terms of the solution. If some users can use the higher version, we should let them. I do wish we had a better way to handle this though or set a default. This issue being created will at least allow future users who stumble into this to understand the problem. We could also add something to the readme/docs.
