### ISSUE TITLE
How to create moto Standalone SQS server?

### ISSUE THREAD

**Issue by Igneous01** [spulec/moto#3678]
I have been searching for documentation and discussions on Stackoverflow and Github on how to properly setup a standalone SQS server with moto, but I am unable to find anything that explains how to get this working.

I have an sqs server started via `moto_server sqs` on the command line, and below is my sample code for sending a message to it:

`
def handler(event, context):

    sqs_client = boto3.client('sqs')
    http = urllib3.PoolManager()

    for record in event['Records']:
        payload = record['body']
        response = http.request('POST',
                                'http://localhost:1010/fake/webservice',
                                body = payload,
                                headers = {'Content-Type': 'application/json'},
                                retries = False)
        if response.status != 200:
            dead_queue_reponse = sqs_client.send_message(
                QueueUrl = 'http://localhost:5000',
                MessageGroupId = record['attributes']['MessageGroupId'],
                MessageBody = newPayload
            )

    return {
        'statusCode': response.status,
        'body': ''
    }
`

When I try testing this lambda locally by manually invoking the handler method with a fake event, it fails to send the message to the sqs queue with this error:

`Traceback (most recent call last):
  File "/Users/test/IdeaProjects/test_lambda.py", line 16, in <module>
    handler(event, None)
  File "/Users/test/IdeaProjects/sqs_lambda_function.py", line 50, in handler
    dead_queue_reponse = sqs_client.send_message(
  File "/Users/test/python38virtual/lib/python3.8/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/test/python38virtual/lib/python3.8/site-packages/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.QueueDoesNotExist: An error occurred (AWS.SimpleQueueService.NonExistentQueue) when calling the SendMessage operation: The specified queue does not exist for this wsdl version.
`

How do I fix this error?

**Comment by bblommers** [comment]
Hi @Igneous01,
- the boto3-client should point to the moto-server. It probably checks against the real AWS right now

`boto3.client('sqs', endpoint_url='http://localhost:5000')`

 - the queue URL identifies the queue itself, andshould be the URL as returned by the create-queue method. This will look something like `http://localhost:5000/queue/yourqueuename`

**Comment by Igneous01** [comment]
Hi @bblommers 

Thanks for clarifying! When I start up moto_server sqs, do I need to manually create queues in it before I can invoke things like `send_message` and `receive_message`?

Is there a way to do this through the command line? I'm not doing any sort of unit tests, just trying to test aws lambda code locally without direct connection to aws.

**Comment by bblommers** [comment]
Yes, you can use the AWS CLI. Similar to boto3, just use the regular command with an additional endpoint-url parameter:
`aws sqs create-queue ... --endpoint-url=http://localhost:5000`

(Not sure on the exact command, but the AWS docs should help with that)
