### ISSUE TITLE
Add sign and verify to KMS

### ISSUE THREAD

**Issue by rvodden** [spulec/moto#3683]
PR incoming :-)

**Comment by rvodden** [comment]
This is a touch more complex than I first thought - PR might be tomorrow :-)

**Comment by rvodden** [comment]
Have raised #3690 (draft).

**Comment by MichaelSnowden** [comment]
@rvodden any update on this? I'd love to test the sign methods of boto in my unit tests

**Comment by rvodden** [comment]
Gosh I forgot I was working on this! Let me find the branch and finish it off. I got it pretty close as I recall!

**Comment by cwkang1998** [comment]
@rvodden Any updates? Would love to help on this if needed.

**Comment by bblommers** [comment]
An initial version of this is now part of Moto 3.1.15. There are some limitations on what is supported - see http://docs.getmoto.org/en/latest/docs/services/kms.html.

I'll close this in the mean time, but if anybody wants to extend the functionality beyond what we have now, PR's are always welcome!
