### ISSUE TITLE
ECS task with no ENI attachments

### ISSUE THREAD

**Issue by ltagliamonte** [spulec/moto#3688]
It looks like that run_task and describe_tasks using `awsvpc` mode do not attach an ENI to the task.
the ENI info should be present under `attachments` -> `details` with value name `networkInterfaceId`
https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_Attachment.html

**Comment by bblommers** [comment]
Thanks for raising this @ltagliamonte - marking it as an enhancement!

**Comment by Balasundaram** [comment]
Hi @spulec @bblommers I am also interested in this as I am trying to mock run_task with networkconfiguration. Can this is prioritized ?

**Comment by bblommers** [comment]
Hi @Balasundaram, most of our features are actually contributed by the community, not necessarily by us.

So if this is something you really need, a PR is always welcome!
There is a [Contributing-section in our docs](http://docs.getmoto.org/en/latest/docs/contributing/index.html) - happy to help if you have any questions around this.
