### ISSUE TITLE
DynamoDB2 Table.get_item() doesn't behave like boto when item is not found

### ISSUE THREAD

**Issue by pior** [spulec/moto#370]
First, thank you for Moto. I regret I didn't find it earlier! 

I found that Moto is misbehaving when calling dynamodb2.Table.get_item() on a non-existent item, on a existent table.

On boto 2.38.0, dynamodb2.Table.get_item raises an ItemNotFound exception.

On moto 0.4.3, this is raising :

```
JSONResponseError: 404 Not Found
{u'__type': u'com.amazonaws.dynamodb.v20111205#ResourceNotFoundException'}
```

**Comment by spulec** [comment]
Thanks for opening! Fixed with #377
