### ISSUE TITLE
create_user_pool_domain not returning data if no cert config is given

### ISSUE THREAD

**Issue by baohx2000** [spulec/moto#3706]
Moto version 1.3.16

Per AWS docs, you should be able to create a domain without supplying domain config (a certificate)
Doing so, AWS will just use their internal cognito domain to create the login page.

Related code:
https://github.com/spulec/moto/blob/master/moto/cognitoidp/models.py#L192-L198

The above code should probably be something like:

```python
    def _distribution_name(self):
        if self.custom_domain_config and "CertificateArn" in self.custom_domain_config:
            hash = hashlib.md5(
                self.custom_domain_config["CertificateArn"].encode("utf-8")
            ).hexdigest()
            return "{hash}.cloudfront.net".format(hash=hash[:16])
        hash = hashlib.md5(self.user_pool_id).hexdigest()
        return "{hash}.amazoncognito.com".format(hash=hash[:16])
```

I am not a python dev so above may not be right.

**Comment by bblommers** [comment]
This is now part of moto >= 1.3.17.dev277

**Comment by baohx2000** [comment]
@bblommers just curious - how long before a docker image will be tagged for .17?
No huge hurry since I'm just building from the patch branch for the moment.
