### ISSUE TITLE
add update_usage_plan api for apigateway

### ISSUE THREAD

**Issue by rajendersaini** [spulec/moto#3719]
## Reporting Bugs

Apigateway has plans. The update_usage_plan is not implemented.

**Comment by rajendersaini** [comment]
I want to implement this feature. I downloaded the code following the steps given in the how to contribute guide. I want to know how to run a single test file?

**Comment by bblommers** [comment]
Hi @rajendersaini, to download the required dependencies:
`make init`
To run one test (file) :
`pytest -sv tests/test_apigateway/test_apigateway.py`
`pytest -sv tests/test_apigateway/test_apigateway.py::method_name`

**Comment by rajendersaini** [comment]
Thanks, @bblommers  - my code is ready. Just need to send the PR. I am not sure why tests in other components are failing besides API gateway.

**Comment by rajendersaini** [comment]
@bblommers  - how to push the branch? I do not have permission!

**Comment by bblommers** [comment]
Hi @rajendersaini, you can fork moto, and create a new branch in your own fork. You should then be able to create a PR.

**Comment by rajendersaini** [comment]
https://github.com/spulec/moto/pull/3727 - @bblommers

**Comment by bblommers** [comment]
This is now part of moto >= 2.0.1.dev291
