### ISSUE TITLE
dynamodb table.put_item doesn't override an existing item

### ISSUE THREAD

**Issue by Nivmorabin** [spulec/moto#3725]
1. The test behaves correctly on moto version 1.3.16
2. Put an item using table.put_item
3. Change the item's attribute and put the item again
4. Scan the table for the results

Current behavior:
The item appears twice.

Expected behavior:
The item appear once with the latest values.

Thanks ahead

**Comment by bblommers** [comment]
Hi @Nivmorabin. are you able to share a reproducible test case?

I just wrote a script that follows these steps, and I'm seeing the correct behaviour (only 1 item appears):
```
import boto3
from moto import mock_dynamodb2


@mock_dynamodb2
def m():
    name = "TestTable"
    conn = boto3.client("dynamodb", region_name="us-west-2")
    conn.create_table(
        TableName=name,
        KeySchema=[{"AttributeName": "h", "KeyType": "HASH"}, {"AttributeName": "r", "KeyType": "RANGE"}],
        AttributeDefinitions=[{"AttributeName": "h", "AttributeType": "S"}, {"AttributeName": "r", "AttributeType": "S"}],
        ProvisionedThroughput={"ReadCapacityUnits": 5, "WriteCapacityUnits": 5},
    )

    i = {
            "h": {"S": "hash"},
            "r": {"S": "range"},
            "s": {"S": "stuff"}
        }
    conn.put_item(TableName=name, Item=i)
    print(conn.scan(TableName=name)["Items"])
    i["s"]["S"] = "more stuff"
    conn.put_item(TableName=name, Item=i)
    print(conn.scan(TableName=name)["Items"])

if __name__ == "__main__":
    m()
```

**Comment by Nivmorabin** [comment]
Hi @bblommers,

Thanks, it indeed does not reproduce with you example,
I'll look deeper into our use case.

Thanks and sorry for troubling you,

Niv
