### ISSUE TITLE
DynamoDB mocks fail with Boto 3

### ISSUE THREAD

**Issue by kereyroper** [spulec/moto#374]
I worked around the issue by starting to migrate our newer test code to DynamoDB Local, so this is more of a public service bug report than an urgent issue.

Boto 3 is stricter about deserialization of responses conforming with the API, and Moto fails to return correct JSON for put_item. I have not investigated if there are similar issues with other APIs.

In particular, type information for "Attributes" is dropped.
http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_PutItem.html

Most folks probably don't use this response info in tests, since it is more valuable to do read-after-write for integration tests, so it wasn't needed to be correct previously.

**Comment by spulec** [comment]
Thank you for opening! This should be fixed now
