### ISSUE TITLE
cognito-idp: cognito:* claims not available in id and access tokens

### ISSUE THREAD

**Issue by pogocode** [spulec/moto#3741]
As far as I can tell, the tokens returned from the `admin_initiate_auth` do not include the `cognito:*` claims such as `cognito:groups`, `cognito:roles` that are documented at [Adding Groups to a User Pool](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-user-groups.html) and [Using Tokens with User Pools](https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-with-identity-providers.html).

I think that this may involve a change to the following code - I see that there is already facility to include extra data from readable attributes, but this probably doesn't cover this scenario:

https://github.com/spulec/moto/blob/5c04a4d8cc0631da147ee298dbe29e94370b7217/moto/cognitoidp/models.py#L121-L141

I'd be interested in attempting to implement this feature if it is indeed missing (and I've not just misunderstood the code).

**Comment by bblommers** [comment]
Hi @pogocode, thanks for raising this!
If I read it correctly, the 'readable attributes' are supplied by the user in the ReadAttributes-parameter when calling the `create_user_pool_client`-method.
Considering the `cognito:` claims will always be part of the ID token, it probably makes most sense to extend the `create_id_token` method with this information:
https://github.com/spulec/moto/blob/751c5ec362730f143adad902f7fcdb9a67fd2993/moto/cognitoidp/models.py#L143

PR's are always welcome! Let me know if you need any help.

**Comment by elisoncrum** [comment]
Inquiring about progress that @leothomas has possibly made on the contribution on adding the ability for `cognito:groups` to be displayed in the JWT since it is similar to his PR #4262.

**Comment by bblommers** [comment]
The `cognito:groups`-attribute is now part of the access token as of moto >= 2.2.16.dev16.

The AWS docs do not reference `cognito:roles` as part of the token, so that has not been added. Do let us know if that's an oversight, happy to reopen this if some attributes are still missing.
