### ISSUE TITLE
mocked S3 put_object hanging

### ISSUE THREAD

**Issue by crbunney** [spulec/moto#3745]
Not too sure how to best describe this, except that I have this code that seems to be stuck within the boto3 library when attempting to do a put_object operation:
```python
import boto3
from moto import mock_s3


def upload_to_bucket(filename: str, bucket_name: str):
    """Creates an S3 object with the given name in the given bucket, creating the bucket if needed"""
    s3_resource = boto3.resource("s3")

    max_attempts = 2
    remaining_attempts = max_attempts + 1
    while remaining_attempts:
        try:
            bucket = s3_resource.Bucket(bucket_name)
            bucket.put_object(Key=filename)
        except s3_resource.meta.client.exceptions.NoSuchBucket:
            if remaining_attempts:
                s3_resource.create_bucket(
                    Bucket=bucket_name,
                    CreateBucketConfiguration={"LocationConstraint": "eu-west-2"},
                )
                remaining_attempts -= 1
            else:
                raise


@mock_s3
def test_upload():
    upload_to_bucket("test", "test_bucket")
```

IntelliJ lets me pause execution when debugging, and having done that a few times it doesn't appear to be stuck in an obvious loop or hanging, but neither does the operation return. I can leave it for minutes at a time and it never finishes running or returns from that `bucket.put_object(Key=filename)`. 

No traceback or log output either.

Using pytest as the test runner

Environment includes:
```
boto3==1.17.19
botocore==1.20.19
moto==2.0.0
pytest==6.2.2
```

**Comment by crbunney** [comment]
Incidentally, this works as expected:
```python
def upload_to_bucket(filename: str, bucket_name: str):
    """Creates an S3 object with the given name in the given bucket, creating the bucket if needed"""
    s3_resource = boto3.resource("s3")

    try:
        s3_resource.create_bucket(
            Bucket=bucket_name,
            CreateBucketConfiguration={"LocationConstraint": "eu-west-2"},
        )
    except s3_resource.meta.client.exceptions.BucketAlreadyExists:
        pass

    s3_resource.Bucket(bucket_name).put_object(Key=filename)
```

which makes me wonder if it's something to do with the bucket being created within the exception handling code?

**Comment by bblommers** [comment]
Hey @crbunney, it looks like it never exits the while-loop, as `remaining_attempts` is only decreased once.
Works fine for me after putting a `remaining_attempts -= 1` underneath the `put_object()`-call.

**Comment by crbunney** [comment]
You are of course, completely correct. That also explains the way it was always in a different part of the code whenever I paused it.

Now I feel foolish 😳

**Comment by bblommers** [comment]
All good - helps to have a fresh set of eyes sometimes :)
