### ISSUE TITLE
ModuleNotFoundError: No module named 'jsondiff'

### ISSUE THREAD

**Issue by palleromk** [spulec/moto#3746]
Hello, 
I am using moto to test my aws applications, and encountered this problem when using moto.iotdata. It seems to me, that the jsondiff requirement is missing...
I tried with moto version 2.0.1 and 1.3.16dev202

traceback:
`
aws_credentials = None

    @pytest.fixture(scope='function')
    def iot_data(aws_credentials):
>       with moto.mock_iotdata():

test/__init__.py:83:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
.venv/lib/python3.8/site-packages/moto/__init__.py:8: in f
    module = importlib.import_module(module_name, "moto")
/usr/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
.venv/lib/python3.8/site-packages/moto/iotdata/__init__.py:2: in <module>
    from .models import iotdata_backends
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    from __future__ import unicode_literals
    import json
    import time
>   import jsondiff
E   ModuleNotFoundError: No module named 'jsondiff'

.venv/lib/python3.8/site-packages/moto/iotdata/models.py:4: ModuleNotFoundError
`

**Comment by bblommers** [comment]
Hi @palleromk, how are you installing moto?
For me jsondiff is installed when specifying the service: `pip install moto[iotdata]`

**Comment by palleromk** [comment]
I have a requirements.txt, where I have included `moto==2.0.1` (and I also tried with `moto==1.3.16dev202`. Then I install with 
`.venv/bin/pip install --no-cache-dir -Ur dev-requirements.txt`

**Comment by bblommers** [comment]
See [this issue](https://github.com/spulec/moto/issues/3722) - using `moto[iotdata]==2.0.1` should solve your problem

**Comment by palleromk** [comment]
Thank you, it did 👍🏻
