### ISSUE TITLE
Make Region configurable

### ISSUE THREAD

**Issue by tejas-sme** [spulec/moto#3761]
For boto3 s3 testing, I am trying to use moto in region other than us-east-1.  I get error because us-east-1 is hard coded in 
https://github.com/spulec/moto/blob/5aefbb1e51e0b97583bb96bd8c3c596dbca44a31/moto/cloudformation/__init__.py#L5

Is it possible to make region as a configurable variable so that I can use moto libraries?

**Comment by bblommers** [comment]
Hi @tejas-sme, moto should pick up whatever region is configured for AWS, regardless of whether you're using the .config file, env variables or the `region_name` variable when creating a boto3-client.

Can you post your test case, and the error message that you're seeing?

**Comment by bblommers** [comment]
Closing this due to a lack of response - feel free to reopen if the issue still persists
