### ISSUE TITLE
Moto SSM put parameter allows empty string as a value, real service does not

### ISSUE THREAD

**Issue by tokwiat** [spulec/moto#3794]
Hello,

I noticed that moto SSM service allows putting parameter with empty string. This is not available in boto or via AWS web UI.
Moto is running in server mode. 

1. boto3==1.17.35
2. botocore==1.20.35
3. moto==2.0.2

Code example that is invoking parameter creation using moto:
`client.ssm.put_parameter(
            Name='test',
            Description='string',
            Value='',
            Type='String',
            Overwrite=True
        )`

It creates the parameter and returns empty string when fetched.

This is, on the other hand, output from boto parameter creation:
`$ aws ssm put-parameter --name "/test" --value "" --profile saml
An error occurred (ValidationException) when calling the PutParameter operation: 1 validation error detected: Value '' at 'value' failed to satisfy constraint: Member must have length greater than or equal to 1.`

That makes inconsistency. Is this a feature somehow or should be fixed?

Regards

**Comment by bblommers** [comment]
Hi @tokwiat, thanks for raising this!
Will mark it as an enhancement to implement value-validation, as we don't have anything at the moment.

**Comment by tokwiat** [comment]
Ok, cool, thanks for answer.

**Comment by TSNoble** [comment]
I've just opened a PR which I think will fix the issue! @bblommers
