### ISSUE TITLE
feature: resource state transition

### ISSUE THREAD

**Issue by galvinograd** [spulec/moto#380]
It could be useful and more realistic if there where some sort state transition.
I think it's best if it would be implemented based on the times job flow has been pulled, for example, after 5 calls to describe_job_flow a specific job flow will transition from STARTING to WAITING.

What do you think?

**Comment by spulec** [comment]
We used to have something like this for EC2, but it ended up causing confusion among people.

One way for you to do this is to use some private Moto APIs:

```python
from moto.emr import emr_backends

emr_backends['us-east-1'].job_flows[job_id].state = "WAITING"
```

and then you can change it as needed.

I do wish we could find a better solution than this, but I don't want to have to add additional APIs or documentation to allow it. The simplicity of how the project interacts with the AWS APIs right now is nice.

**Comment by galvinograd** [comment]
I agree that unit tests should expect a simple and consistent behavior.

Although I think that in contrast to mocking, moto_server should reflect as accurately as possible AWS usage as it's mostly used for integration tests where the time axis plays an important role.
For example, a typical boto code would probably look like this: call a function, sleep, assert completed, repeat.

I think architecturally appending workers at moto_server startup that updates the backends' values solves that kind of logic separation.

What do you think? (I would be glad to implement it :)

**Comment by spulec** [comment]
If we were going to do this, I would want it to be opt in (`@mock_emr(slow_mode=True)`). I would also prefer using the resource creation/update time to determine the status to avoid having to add extra processes/threads. For example, ec2 instances can say they are available 30 seconds after they are created.

Thoughts?

**Comment by donato** [comment]
I'm going through a similar problem.

I have a helper which launches an EMR, does bootstrapping and then waits for the clusters state to go to "WAITING"

Any tips for testing this?

**Comment by spulec** [comment]
@donato you should be able to do something similar to the code I posted above.

**Comment by maxwellchandler** [comment]
Im having trouble using the 
`from moto.emr import emr_backends

emr_backends['us-east-1'].job_flows[job_id].state = "WAITING"`

suggestion in 2020. It doesnt seem like the moto backends have a job_flows attribute anymore. Is there a new way to update a the state of a job?

**Comment by maxwellchandler** [comment]
If anyone is still interested the best way to do this now is something like: `athena_backends['us-east-2'].executions.get(query_id).status = "SUCCEEDED"`

**Comment by dchudz** [comment]
> For example, ec2 instances can say they are available 30 seconds after they are created.

That sounds really smart! Then tests could fast-forward time if they want, but wouldn't need to hook into anything from moto to get the state updated.

Is this something the project might be open to someone implementing as optional behavior?

**Comment by bblommers** [comment]
Moto 3.1.8 now contains a state manager, that would allow you to artificially slow down how fast Moto moves through states, like how long it takes to get from `initializing` to `ready`, etc.

The general documentation can be found here:
http://docs.getmoto.org/en/latest/docs/configuration/state_transition/index.html

Note that while the framework is in place, it still has to be implemented for every model separately. The documentation contains a list of models that currently support this.

Given the age of this ticket, I'm going to close this now. Please open a new issue if you have any questions around this, or if you'd like to see support for a specific model.

**Comment by dchudz** [comment]
Very cool! Thanks!!
