### ISSUE TITLE
document how to use with unittest.TestCase

### ISSUE THREAD

**Issue by mdavis-xyz** [spulec/moto#3840]
I believe the README should contain an example of how to use `moto` with `unittest`. Perhaps another subsection with [usage](https://github.com/spulec/moto#usage).

As far as I can tell, the best way is:

```
import unittest
from moto import mock_s3

class MyTest(unittest.TestCase):
    mock_s3 = mock_s3()
    def setUp(self):
        self.mock_s3.start()

    def tearDown(self):
        self.mock_s3.stop()

    def test(self):
        ...
```

Can someone confirm that this is the best way? If so, I'll write a PR to add this to the README.

**Comment by bblommers** [comment]
Correct @mdavis-xyz - that's how we use it in some of our internal tests as well. Thanks for picking that up. PR's are always welcome!
