### ISSUE TITLE
Add CloudFormation support for remaining SageMaker resources

### ISSUE THREAD

**Issue by zachurchill-root** [spulec/moto#3846]
As a corollary to https://github.com/spulec/moto/issues/3568, it would be nice to also provide CloudFormation support for the following SageMaker resources: Models, Endpoint Configurations, Endpoints, and Notebook Lifecycle Configurations.

*Note:* Training Jobs [not currently supported](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_SageMaker.html) by CloudFormation.

**Comment by zachurchill-root** [comment]
Would it be better to break this issue into an issue for each SageMaker resource in order to link a PR per SageMaker resource? Or is it preferable to just knock all of these out in a single PR?

**Comment by bblommers** [comment]
Hey @zachurchill-root, I'm OK with just a single issue and single PR for all of them.
If it turns out to be easier to split the work in multiple PR's, just reference this issue in the PR's instead of closing it.

**Comment by bblommers** [comment]
All Sagemaker models should now be supported by our CloudFormation implementation as of moto >= 2.0.6.dev4
