### ISSUE TITLE
Support for SQS POST API (boto3)

### ISSUE THREAD

**Issue by rouge8** [spulec/moto#385]
Boto3 switches to using `POST` requests for the SQS API, which means the routing in `moto.sqs.urls` is no longer accurate:

```python
url_paths = {
    '{0}/$': QueuesResponse.dispatch,
    '{0}/(?P<account_id>\d+)/(?P<queue_name>[a-zA-Z0-9\-_]+)': QueueResponse.dispatch,
}
```

Boto3 makes all requests as `POST /`, which will always return the `QueuesResponse`.

**Comment by spulec** [comment]
Thanks for opening!

I was able to get some basic support working, but there may be remaining issues. Feel free to open more issues if you see anything.
