### ISSUE TITLE
Push to ecr repo created with moto server

### ISSUE THREAD

**Issue by malathit** [spulec/moto#3852]
Thanks for this project first. It helps me a lot for developing services that needs AWS.

I am running moto ecr service as follows
     
    moto_server ecr -p 5000 -H 0.0.0.0

Then I created an ecr repository with this command

     aws ecr create-repository --repository-name test --region us-east-1 --endpoint-url http://localhost:5000

Now is it possible to push a docker image to this repository? I tried using `aws ecr get-login` that provided credentials but failed when running the docker push command like this

```
# aws ecr get-login --region us-east-1 --registry-ids 012345678910 --endpoint-url http://localhost:5000
docker login -u AWS -p 012345678910-auth-token -e none https://012345678910.dkr.ecr.us-east-1.amazonaws.com

# docker login -u AWS -p 012345678910-auth-token -e none https://012345678910.dkr.ecr.us-east-1.amazonaws.com
Flag --email has been deprecated, will be removed in 17.06.
Error response from daemon: login attempt to https://012345678910.dkr.ecr.us-east-1.amazonaws.com/v2/ failed with status: 400 Bad Request

# docker push 012345678910.dkr.ecr.us-east-1.amazonaws.com/test
The push refers to repository [012345678910.dkr.ecr.us-east-1.amazonaws.com/test]
8ea3b23f387b: Preparing 
no basic auth credentials
```

Can somebody please help?

**Comment by bblommers** [comment]
Unfortunately this is out of scope for Moto, @malathit. The aim for us is to mock the AWS SDK itself, but that doesn't include mocking the Docker client/API/CLI.

**Comment by malathit** [comment]
@bblommers I just assumed that when ECR `create-repository` command is used, a private registry is created in the background. But I just went through the source code and there is no mention of private registry. Luckily, I found that the `put-image` command actually adds an image to the repository. In the case of [ECR by AWS][1] this command is used by AWS to add metadata of the image uploaded via the docker push command. 

```
# aws ecr put-image --repository-name test --region us-east-1 --image-manifest test --endpoint-url http://localhost:5000 --image-tag v1
{
    "image": {
        "registryId": "012345678910",
        "repositoryName": "test",
        "imageId": {
            "imageDigest": "sha256:a6698ae96409579a4f8ac96f5e5f276467b3f62d184c9e6db537daeedb9dd939",
            "imageTag": "v1"
        },
        "imageManifest": "test"
    }
}

# aws ecr list-images --repository-name test --region us-east-1 --endpoint-url http://localhost:5000
{
    "imageIds": [
        {
            "imageDigest": "i don't know",
            "imageTag": "v1"
        }
    ]
}

```

Luckily my code doesn't need to push or pull image from the ECR repo. This method might not work if that is the case. 

  [1]: https://docs.aws.amazon.com/cli/latest/reference/ecr/put-image.html

**Comment by bblommers** [comment]
Thanks for sharing that @malathit - I wasn't aware of the `aws ecr put-image` command.
It's the `docker login`/'docker push`/`docker pull` commands that are not supported using Moto.
