### ISSUE TITLE
nextToken Pagination does not work for Iot list_job_executions_for_thing

### ISSUE THREAD

**Issue by rohit-dua** [spulec/moto#3857]
### Issue

The nextToken param does not work for the function `list_job_executions_for_thing` in the iot service.

### The Bug
[This boolean condition](https://github.com/spulec/moto/blob/c9dd9cc7f9ffe6de600a39fbf028db805ed4a0c2/moto/iot/models.py#L1320) will always return True since the same variable `job_executions` is being overwritten in the line above. Hence the pagination will never work.

### Solution
Change the var `job_executions` to something like `job_executions_filtered` for the return value
```
        token = next_token
        if token is None:
            job_executions_filtered = job_executions[0:max_results]
            next_token = str(max_results) if len(job_executions) > max_results else None
        else:
            token = int(token)
            job_executions_filtered = job_executions[token : token + max_results]
            next_token = (
                str(token + max_results)
                if len(job_executions) > token + max_results
                else None
            )

        return job_executions_filtered, next_token
```

**Comment by bblommers** [comment]
Thanks for raising this, and for providing a fix, @rohit-dua!
We should pick this up after #3752 is merged, and we can refactor this to use the decorator, instead of messing around with the next_token manually.
