### ISSUE TITLE
support for cloudmap / servicediscovery?

### ISSUE THREAD

**Issue by andytechdad** [spulec/moto#3859]
Hi

Is there a roadmap for support service discovery / cloud map? I'm using it more and more and would be good to have our various functions covered by unit tests

Happy to help implement it if needs be, just not sure the best way to get started with a new service.

**Comment by bblommers** [comment]
Hi @andytechdad, Moto is very much a community-driven project, so there's no timeline or roadmap for specific services - just whenever somebody feels like implementing it. So if you want to contribute, PR's are always welcome!

There's a section in our documentation on how to start with a new service here: https://github.com/spulec/moto/blob/master/CONTRIBUTING.md#missing-services 
Let me know if you need any help.
