### ISSUE TITLE
Creating subnets/security groups with specific IDs

### ISSUE THREAD

**Issue by Comradephate** [spulec/moto#386]
Hello!

In my provisioning process I assign security groups and subnets by ID, which means those security group and subnet IDs need to exist in moto, which doesn't seem to be a trivial thing to do.

Is there a more testable way to provision instances that won't necessitate calling out security groups and subnets by ID, or is there a solution to this within moto that I haven't found yet?

Thanks!

Some ipdb snippets below:
```
app_lib.py(126)create_devapp()
    125     # TODO : pull all of this data to a config file or at least the top of the file
--> 126     subnets = ['subnet-xxxxxx', 'subnet-xxxxxxx', 'subnet-xxxxxxx', 'subnet-xxxxxx']
    127     subnet = choice(subnets)

ipdb> c
> /Users/jaron/code/devapp_tool/devapp_lib.py(138)create_devapp()
    137         import ipdb; ipdb.set_trace()
--> 138         res = ec2.run_instances(image_id=my_ami.text,
    139                                 key_name='xxx',

ipdb> c
> /Users/jaron/code/devapp_tool/devapp_lib.py(150)create_devapp()
    149         import ipdb; ipdb.set_trace()
--> 150         logger.error("Failed to create %s" % devapp)
    151         logger.error(str(e))

ipdb> print e
EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
  <Response>
    <Errors>
      <Error>
        <Code>InvalidSubnetID.NotFound</Code>
        <Message>The subnet ID 'subnet-xxxxxx' does not exist</Message>

      </Error>
    </Errors>
  <RequestID>7a62c49f-347e-4fc4-9331-6e8eEXAMPLE</RequestID>
</Response>
ipdb>
ERROR
```

**Comment by spulec** [comment]
One hacky way to do it is to create a security group and then do something like:

```python
from moto.ec2 import ec2_backends
current_sg = ec2_backends['us-east-1'].groups.values()[0]
current_sg.id = MY_DESIRED_SG_ID
ec2_backends['us-east-1'].groups[MY_DESIRED_SG_ID] = current_sg
```

to modify the group's id in memory. Unfortunately that is the best solution we have right now

**Comment by Comradephate** [comment]
Oh, cool.  That's not too bad.

I was working my way through the code to see if I could patch something in, but I'm a little out of my depth, so this will work if I can't figure out a better way.

Thanks!
