### ISSUE TITLE
Support for mocking non-global resources?

### ISSUE THREAD

**Issue by Lacrymology** [spulec/moto#3860]
Boto3 says sessions are not thread-safe and that you should use a different `boto3.sessionSession` for each thread:

https://boto3.amazonaws.com/v1/documentation/api/latest/guide/resources.html#multithreading-and-multiprocessing
https://boto3.amazonaws.com/v1/documentation/api/latest/guide/session.html#multithreading-or-multiprocessing-with-sessions

we're using `moto` for our tests, but only the global session gets mocked, and I've found no way of either mocking _every_ session, or somehow passing the session we want to mock, so our tests don't pass because the sessions the code use aren't mocked anymore.

Is there a workaround for this?

thanks

**Comment by bblommers** [comment]
Hi @Lacrymology, Moto resets the global session to ensure that it gets reinitialized every time. AFAIK, it doesn't really mock a session as such - it just mocks the HTTP requests that are made within every session.

Do you have a reproducible failing test case that you can share?

**Comment by Lacrymology** [comment]
@bblommers to be honest, our setup is quite complex, and I'm not sure I can produce a minimal example. I just know that our tests that included calling aws resources failed with things like "bucket doesn't exist", and it got fixed when I modified the function we've got to return a thread-local session so it just returns `boto3` when running in a test.

I'll look up if there's some setup we're doing on the global session I haven't fixed

**Comment by bblommers** [comment]
Is this still an issue, @Lacrymology?

**Comment by bblommers** [comment]
I'm going to close this due to a lack of response. Do let us know if there still is an issue here, and we can reopen.
