### ISSUE TITLE
ElasticsearchDestinationConfiguration not supported in moto implementation of firehose

### ISSUE THREAD

**Issue by Srikanth9142** [spulec/moto#3862]
# ElasticsearchDestinationConfiguration not supported by moto for firehose.

In Kinesis Firehose creation from the documentation of https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/firehose.html#Firehose.Client.create_delivery_stream mentioned about the ElasticSearch as the destination. But if we implement using mock_firehose raised the error

   stream = self.kinesis_backend.create_delivery_stream(
          stream_name, **stream_kwargs
        )
E       UnboundLocalError: local variable 'stream_kwargs' referenced before assignment

../../venv/lib/python3.8/site-packages/moto/kinesis/responses.py:182: UnboundLocalError

- DIving deeper into the file
https://github.com/spulec/moto/blob/master/moto/kinesis/responses.py#L154 There is no support for ElasticSearchDestinationConfiguration although boto3 supports that.

**Comment by bblommers** [comment]
Correct @Srikanth9142 - that's not supported yet. At the very least, it should throw a NotYetImplemented-exception, instead of this cryptic message.
Marking it as an enhancement.

**Comment by bblommers** [comment]
This should be fixed as of Moto >= 2.2.2, so I'll close this.
Do let us know if anything else is still bugged/missing.
