### ISSUE TITLE
Provide instructions on how to write decorators like @mock_{resource}

### ISSUE THREAD

**Issue by brno32** [spulec/moto#3865]
I apologize, but this isn't a bug report or a feature request, and there doesn't appear to be a discussion group anywhere. If someone can point me to somewhere where it's more appropriate to ask questions like this, I'll be happy to oblige.

This is one of the best testing libraries I've ever worked with and I want to use its principles to mock other APIs I work with.

My main questions is how the decorators (or context managers) work under the hood. I've spent a few hours reading the code, but I'll admit there's too much abstraction involved for me to follow some of the details. I'm looking for how I can recreate the terrific convenience of decorators like `mock_s3` as opposed to having to directly patch imports for every module in my code which imports them.

e.g., it's great how in this library you can do this

```python
@mock_s3
def test_some_biz_logic():
    biz_logic_caller()
```

as opposed to having to do

```python
@patch("biz_logic.boto3", mock_boto3):
def test_biz_logic_caller():
    biz_logic_caller()
```

where a `@patch` is needed for every module involved where `boto3` is imported.

I posted an SO post here https://stackoverflow.com/questions/67138758/use-decorator-to-mock-an-import-within-the-wrapped-function

Am I right that the patching here https://github.com/spulec/moto/blob/master/moto/core/models.py#L508 is somehow globally patching the boto module?

**Comment by bblommers** [comment]
Hi @brno32, the actual 'magic' that makes Moto work is the way we patch the outgoing HTTP requests here: https://github.com/spulec/moto/blob/master/moto/core/models.py#L394

We don't patch the boto3-module itself, as it has some useful validation methods that we want to keep. At some point, boto3 will make an HTTP request to the AWS backend - and that's where we intercept and return our own data.

The `self._client_patcher` that you linked to only changes some input parameters as required, but in the end it just returns the real boto3-client: https://github.com/spulec/moto/blob/master/moto/core/models.py#L475

-----------------

As to your actual problem - I don't have enough knowledge of MagicMocks to know whether it's possible to achieve this.

One workaround you could consider is reassigning the Api directly:
```
class MockApi:
    pass


def mock_api(func):
    def wrapper(*args, **kwargs):
        from api_library import api_impl
        original = api_impl
        api_impl = MockApi()
        func(*args, **kwargs)
        api_impl = original

    return wrapper
```

**Comment by brno32** [comment]
Thanks a lot for the info @bblommers!

I saw `httpretty` as a dependency, so I suspected the HTTP calls were being patched, but I don't follow how the state persists in the virtual instance. `moto` is still patching `boto` in order to intercept data (even if it ultimately returns the boto client in the end), and that's where I'm struggling to follow the code. I'll keep trying, though!

---

Regarding your suggestion to assign the api directly, this doesn't work, as it doesn't replace the import that the wrapped `func` makes from within its own module.

**Comment by bblommers** [comment]
Just found the actual HTTP request interceptor: https://github.com/spulec/moto/blob/master/moto/core/models.py#L273
The state itself is persisted in global variables, such as this one: https://github.com/spulec/moto/blob/master/moto/s3/models.py#L1777

--------------------
Didn't think about the import issue.. maybe it's easier to mock the import itself, in that case?
```
def mock_api(func):
    def wrapper(*args, **kwargs):
        import sys
        sys.modules['api_library'] = __import__('mock_library') # mock_library.py should contain a mocked Api-class
        func(*args, **kwargs)
        del sys.modules['api_library']  # the next import.. will reload the original file

    return wrapper

```
Source: https://stackoverflow.com/questions/8658043/how-to-mock-an-import

**Comment by brno32** [comment]
Thanks for pointing those parts of the code out. I'll keep reading and see if I can wrap my head around how it works!

---

Your suggestion worked! Does `moto` do something similar? I'm still impressed that the patched `botocore` module seems to work universally. I don't see any references to `sys.modules` in the source code

**Comment by bblommers** [comment]
> Does `moto` do something similar?

We let the `responses`-library handle all our HTTP request interceptors - and from what I can see, that just uses the normal `mock.patch` behind the scenes. Not sure why it works/yours doesn't

**Comment by brno32** [comment]
Not sure either. But I figured it out using `responses`, and I'm storing state in an exported, instantiated class like `moto` does. Thank you for the help!

**Comment by bblommers** [comment]
Glad you got it working!
