### ISSUE TITLE
enforce dynamodb range key size limit

### ISSUE THREAD

**Issue by mdavis-xyz** [spulec/moto#3866]
Dynamodb has a range key [size limit](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Limits.html) of 1024 bytes.
Moto does not enforce this.

# Steps to Reproduce

```
import boto3
from moto import mock_dynamodb2

table_name = 'my-table'
limit = 1024

with mock_dynamodb2():
    client = boto3.client('dynamodb')
    response = client.create_table(
        AttributeDefinitions=[
            {
                'AttributeName': 'my_hash',
                'AttributeType': 'S'
            },
            {
                'AttributeName': 'my_range',
                'AttributeType': 'S'
            },
        ],
        TableName=table_name,
        KeySchema=[
            {
                'AttributeName': 'my_hash',
                'KeyType': 'HASH'
            },
            {
                'AttributeName': 'my_range',
                'KeyType': 'RANGE'
            },
        ]
    )
    
    
    boto3.resource('dynamodb').Table(table_name).put_item(
        Item={
            'my_hash': 'abc',
            'my_range': 'x' * (limit + 1)
        }
    )
```

# Expected Behavior

This script throws an exception at `put_item` because the range key is too large

Here's what happens when you do this on the real dynamodb:

```
botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the PutItem operation: One or more parameter values were invalid: Aggregated size of all range keys has exceeded the size limit of 1024 bytes
```

# Actual behavior

Script does not throw exception.

# Solution

I'm not sure if the solution should be similar to #1874 .

Should I just put an `if` statement inside `def put_item()` [here](https://github.com/spulec/moto/blob/9b3e9328227c795bfe5896a89b19cd4989407b14/moto/dynamodb2/models/__init__.py#L598)?

**Comment by mdavis-xyz** [comment]
While we're at it, we can implement the min limit (1 byte) too, and the limits for the hash key.

**Comment by mdavis-xyz** [comment]
We also probably need to do the same for update table.

Should I use a custom setter function instead?

**Comment by bblommers** [comment]
Hi @mdavis-xyz, thanks for raising this!
Would be nice if the solution is similar to #1874, so have that validation a single place: https://github.com/spulec/moto/blob/master/moto/dynamodb2/models/__init__.py#L62

At the moment, the LimitedSizeDict does not have any context, i.e. it doesn't know what date it stores and which key is hash/range.

Best solution IMO is to repurpose it into something like:
```
class DynamoItemAttributes(dict):
    def __init__(self, hash_key_name, range_key_name=None):
        self.hash_key_name = hash_key_name
        ....

    def __setitem__(self, key, value):
         if key == self.hash_key_name && ...:
            raise KeySizeTooLarge  # whatever it's named
```

**Comment by mdavis-xyz** [comment]
Actually that file doesn't do any boto calls, only moto. Do I need to write tests there? Or tests/test_dynamodb/test_dynamodb.py? Or  `test_dynamodb_table_with*_range_key.py`?

**Comment by bblommers** [comment]
`/test_dynamodb2/test_dynamodb.py` is probably the best place. 
Line 204 has an example on (IMO) the best way to validate boto exceptions

**Comment by mdavis-xyz** [comment]
Note that when I tried testing against the real dynamodb with `{"N": "1"*2048}` I got:

> botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the PutItem operation: Number overflow. Attempting to store a number with magnitude larger than supported range

So there's [an additional limit](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Limits.html#limits-data-types) for numbers.

For binary or string hash keys, the exact error is:

> One or more parameter values were invalid: Size of hashkey has exceeded the maximum size limit of2048 bytes

Note the lack of space in `of2048`.

For binary and string range keys, the exact error is:

> One or more parameter values were invalid: Aggregated size of all range keys has exceeded the size limit of 1024 bytes

I also tested how string length is calculated for emojis. It seems to match utf-8. (e.g. `len(s.encode())`)

**Comment by mdavis-xyz** [comment]
I've written some unit tests, but am unable to run them (against the existing code).

`make init` does not work. It doesn't work on my Ubuntu laptop, or my clean Amazon Linux VM.
I've tried manually `pip install`ing the `requirements*.txt`, but that doesn't work because most requirements are in setup.py.

Can someone please look at my tests to confirm these are good tests?
https://github.com/mdavis-xyz/moto/commit/4cafc261d964f27191dfd7f840e6e8f445f7859e

Do new contributors usually struggle to get their environment set up?
I believe that there should be a Dockerfile for running tests, since `make` is so unpredictable. (I've never encountered *any* open source project with a `Makefile` that runs perfectly the first time, on a normal machine. It's always fiddly and not as robust as it seems.) But my test Dockerfile isn't working. It's stuck on a pip install for some reason. Also, because the dependencies are specified within `setup.py`, that means that if we were to have a Dockerfile for testing, every time a test (or any file) is changed, all dependencies would need to be installed again from scratch, just to re-run one test. If the dependencies were all in a requirements.txt file, that could be optimised, to make running subsequent tests in docker quick.

**Comment by bblommers** [comment]
I'll have a look later at the tests, @mdavis-xyz.

There's a known issue running Python 3.8 and 3.9, as our dependencies currently do not support that. Haven't encountered any issues with 3.7 or lower

**Comment by bblommers** [comment]
Assuming your issues with `make init` were a massive error trace about `lxml` not installing/not being available - that's now fixed in master. Feel free to rebase and try again


> I believe that there should be a Dockerfile for running tests, since `make` is so unpredictable.

The lxml issue was related to a wrong dependency, so installing it in Docker would just move the problem around.
In general, I agree - `make` isn't always as easy it it should be. But moto is not particularly complex, so bugs excluded(!), there's no reason it shouldn't work first time.

**Comment by bblommers** [comment]
Overall, your tests look good to me, btw. Looks like it covers all use cases.

The only nitpick is that the `@requires_boto_gte("2.9")`-decorators are not required. I know they were there before, because of overzealous copy/pasting across the years, but it was only required for some tests using the `mock_dynamodb_deprecated`-decorator

**Comment by mdavis-xyz** [comment]
I was getting the xml dependency errors before, yes.

Now I get a new error:

```
$ make init
Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    import setuptools
ImportError: No module named setuptools
make: *** [Makefile:13: init] Error 1
```

It seems it's using the wrong version of python. But even then, shouldn't it `pip install setuptools` for me?

Should I raise a new ticket to discuss `make` and running tests in docker?

**Comment by mdavis-xyz** [comment]
Note my docker approach is now giving me:

```
Installed /usr/local/lib/python3.7/site-packages/boto3-1.17.57-py3.7.egg
error: MarkupSafe 1.1.1 is installed but MarkupSafe>=2.0.0rc2 is required by {'Jinja2'}
make: *** [Makefile:13: init] Error 1
The command '/bin/sh -c make init' returned a non-zero code: 2
```

**Comment by mdavis-xyz** [comment]
The unit tests are failing in CICD because I've got an emoji in a hard-coded string.
The error points to https://www.python.org/dev/peps/pep-0263/

But I can't understand that page. It seems like a proposal of many suggestion implementations. What am I supposed to put at the top of the file to make it work?

**Comment by bblommers** [comment]
Does it work when you create a new virtual env from scratch?
```
virtualenv venv
source venv/bin/activate
make init
```

**Comment by mdavis-xyz** [comment]
From master, no. I get the issue in #3875.

From PR #3876 I got an error, because I re-used the same virtual env between those two attempts. 

> error: MarkupSafe 1.1.1 is installed but MarkupSafe>=2.0.0rc2 is required by {'Jinja2'}

So should I change #3876 to use MarkupSafe>=2.0.0rc2?

When I use #3876 from a clean virtual env, `make init` runs successfully.

**Comment by mdavis-xyz** [comment]
Ok, I think I've written most of what's required for this PR, but I'm getting unit test failures, including failures of unrelated dynamodb tests. So I must have broken something. But the pytest output doesn't tell me what. It seems the actual code must run in some other process on a Flask server or something? So the logs aren't visible.

How do I debug this?

https://github.com/mdavis-xyz/moto/tree/ddb_key_limits

**Comment by mdavis-xyz** [comment]
Ah nevermind. The trick to debugging this seems to be to use pdb. I saw I had my < and > the wrong way around.

**Comment by mdavis-xyz** [comment]
Ok, I've written most of the code. But the tests are failing and I can't tell why.

I think the specific exceptions I'm throwing need to be caught and then rethrown as a ValidationError. But I don't know where to do that.

https://github.com/mdavis-xyz/moto/tree/ddb_key_limits

**Comment by bblommers** [comment]
These exceptions are caught here: https://github.com/mdavis-xyz/moto/blob/ddb_key_limits/moto/dynamodb2/responses.py#L299

It should be made more generic, I guess, to catch any subclasses of MockValidationExceptions

**Comment by mdavis-xyz** [comment]
I need help with PR #3888 .

One unit test is failing for python 2.7, because of an issue with non-ascii encodings.
I've checked and the issue is not with boto itself.

I can't figure out where the issue is, since the traceback for the test failure is after an API response is received, containing the error message.

@bblommers  can you help me?

**Comment by bblommers** [comment]
Fixed @mdavis-xyz - there was a bug in how it computes the size of (non-utf8) items:
https://github.com/spulec/moto/pull/3888/commits/4594c26ea87b0cf3ea9c846cc1a5eabd7e60ed91

**Comment by bblommers** [comment]
This is now part of moto >= 2.0.6.dev15
