### ISSUE TITLE
Adding EKS Support?

### ISSUE THREAD

**Issue by ferruzzi** [spulec/moto#3870]
Apologies, I didn't see a link to a community mailing list/chat/etc.  I have a usecase where I need to mock a portion of EKS and it doesn't look like that is implemented yet.  Just wanted to make sure there wasn't someone working on that before I go and duplicate work.  If it's not being worked on, I'll look into adding the service.

**Comment by bblommers** [comment]
Hi @ferruzzi, I'm not aware of anyone working on that service, so a PR would be welcome.

Some notes on how to add new services can be found here: https://github.com/spulec/moto/blob/master/CONTRIBUTING.md#missing-services

Let me know if you need any help.

**Comment by ferruzzi** [comment]
Sounds good.  I am going to need it to test a contribution I am adding to the Apache Airflow project.  Assuming the code is to your standards and all that, what's a general approval time on a well-executed PR?

**Comment by bblommers** [comment]
No promises here, but approval tends to happen within 24h. That only creates a dev- release though - there's no fixed timeline on when a full release will be cut.

**Comment by ferruzzi** [comment]
Fair enough.  We would need the code to be publicly available quickly after approval (1-2 weeks).  If the turnaround is going to be longer then we'll have to implement the mocking within the Airflow test package.  What dictates when the next full release gets cut?  Anything I can help with there?  I'd really prefer this was mutually beneficial; if I'm already doing the work to mock the service, it may as well be useful.  Thanks for your time!

**Comment by bblommers** [comment]
Release times really depend on how much has been merged (i.e., whether it's worth it) and maintainer time.
1-2 weeks shouldn't be a problem though. Just remind me after approval, and I'll get on it 👍

**Comment by ferruzzi** [comment]
That sounds great, can definitely work with that.

**Comment by bblommers** [comment]
A single PR is fine, @ferruzzi! Easier to create and easier to review

**Comment by ferruzzi** [comment]
Hi, I'm plugging away at this.  I have the four endpoints done for clusters, working on nodegroups now.  I've run into a snag I can't seem to figure out and could use a hand.  When implementing `list_nodegroups()`, I ran the scaffold.py script to generate the bones as I did previously and have added the following:

in responses.py:
```
    def list_nodegroups(self):
        cluster_name = self._get_param("clusterName")
        max_results = self._get_int_param("maxResults", DEFAULT_MAX_RESULTS)
        next_token = self._get_param("nextToken", DEFAULT_NEXT_TOKEN)
        nodegroups, next_token = self.eks_backend.list_nodegroups(
            cluster_name=cluster_name,
            max_results=max_results,
            next_token=next_token,
        )

        return 200, {}, json.dumps(dict(nodegroups=nodegroups, nextToken=next_token))
```

in models.py:
```
    def list_nodegroups(self, cluster_name, max_results, next_token):
        cluster = self.clusters[cluster_name]
        nodegroup_names = sorted(cluster.nodegroups.keys())
        start = nodegroup_names.index(next_token) if next_token else 0
        end = min(start + max_results, cluster.nodegroup_count)
        new_next = "null" if end == cluster.nodegroup_count else nodegroup_names[end]

        return nodegroup_names[start:end], new_next
```

In my test, when I execute `result = client.list_nodegroups(clusterName=cluster_name)`, the`self._get_param("clusterName")` call in response.py returns None causing it to fail with a KeyError at `cluster = self.clusters[cluster_name]`

Have I missed a step on this one somehow?  Why might the querystring not include the value?  Doing a step-trace, it looks like the cluster_name value is carried through up until that check.

**Comment by bblommers** [comment]
That looks pretty standard, so not sure why the clusterName is missing. Do you have a branch that I can look at?

**Comment by ferruzzi** [comment]
I will get you one, I want to clean a few things up quick.  If it helps any, this is the value of querystring when `self._get_param("clusterName")` gets called from `responses.py` and can't find `clusterName`.  I don't know, maybe that might tell you something useful in the meantime.


```OrderedDict([('User-Agent', 'Boto3/1.17.57 Python/3.8.7 Darwin/19.6.0 Botocore/1.20.57'), ('X-Amz-Date', '20210518T165745Z'), ('Authorization', 'AWS4-HMAC-SHA256 Credential=foobar_key/20210518/us-west-2/eks/aws4_request, SignedHeaders=host;x-amz-date, Signature=4ded9d2af14deec5ffa73a4443feb6956c2a78ee90919499b92d9ade6820a7b7')])```

**Comment by ferruzzi** [comment]
PR Submitted:  https://github.com/spulec/moto/pull/3981

**Comment by bblommers** [comment]
This is now part of moto >= 2.0.10
