### ISSUE TITLE
any plans to add amazon comprehend?

### ISSUE THREAD

**Issue by saraducks** [spulec/moto#3895]
This is a request, I couldn't find the appropriate place to ask hence posting here. For one of my projects, I am using comprehend for PII detection. I need to mock comprehend for the tests, but I don't see that has been implemented yet as per the implementation coverage. Any plans to add the amazon comprehend? Happy to help if no one has taken over.

**Comment by bblommers** [comment]
Hi @saraducks, I'm not aware of anyone working on this at the moment, so a PR would be very welcome!

This section in the documentation has some guidance on how to get started with a completely new service: https://github.com/spulec/moto/blob/master/CONTRIBUTING.md#missing-services

**Comment by bblommers** [comment]
Not that I'm aware of, @smanjil!
