### ISSUE TITLE
Cannot launch VPC instance with security group defined in the NIC

### ISSUE THREAD

**Issue by Comradephate** [spulec/moto#391]
Hello,

Launching code looks like this:
''''
        interface = NetworkInterfaceSpecification(subnet_id=subnet,
                                                  groups=['sg-xxxxxx'],
                                                  associate_public_ip_address=True)
        interface = NetworkInterfaceCollection(interface)
        res = ec2.run_instances(image_id=my_ami.text,
                                key_name='xxxx',
                                user_data='xxxxxx',
                                instance_type='c3.2xlarge',
                                instance_profile_name='xxxx',
                                network_interfaces=interface)
''''

I can successfully launch instances with no security group on the NIC.

It appears that the following line is where it fails:

eni = NetworkInterface(self, subnet, private_ip_address, group_ids=group_ids, **kwargs) within create_network_interface within /moto/ec2/models.py

With the following: AttributeError("'NoneType' object has no attribute 'ec2_backend'",)

In the meantime I've just changed how I'm launching because for my specific use case it doesn't matter, but as launching with the sg attached to the NIC is valid, I thought I'd submit a bug report.

I attempted to trace the issue further to submit a patch, but couldn't figure it out.  I'll do my best to keep looking.

**Comment by spulec** [comment]
Thanks for opening! This should be fixed in `master` now.

**Comment by Comradephate** [comment]
Hah, that would do it.  I spent longer than I'd like to admit looking at that code, didn't catch that.

Thanks for the quick response!

**Comment by spulec** [comment]
No problem. Thanks for using Moto!
