### ISSUE TITLE
WaitTimeSeconds not honored by moto_server (simulating SQS)

### ISSUE THREAD

**Issue by collinstocks** [spulec/moto#392]
WaitTimeSeconds not honored by moto_server (simulating SQS)

I don't know how easy this is to fix, given that Python is generally synchronous. There are some asynchronous web server libraries out there.

It looks as though you are using flask in threaded mode. I'm not sure how many threads that gives you, but it should be possible to increase that as needed using a command line argument.

**Comment by jotes** [comment]
I can try to dig into it if @spulec agrees.

**Comment by spulec** [comment]
PR welcome. I would prefer not to mess with additional threads, but just have the process wait until the time has passed

**Comment by collinstocks** [comment]
@spulec Simply waiting until the time has passed will prevent other connections which could potentially put items into the queue, thus defeating the entire purpose of implementing the wait....

**Comment by jotes** [comment]
@collinstocks @spulec Hi, can we close this issue? Is my patch working okay for you?

**Comment by spulec** [comment]
Fixed with #398
