### ISSUE TITLE
Add support for Jinja version 3.0.0

### ISSUE THREAD

**Issue by charlesoconor** [spulec/moto#3922]
Flask has released a new version that requires Jinja>=3.0.0. There are a lot of improvements in this version upgrade. Currently, this library is requiring that Jinja < 3.0.0.

**Comment by bblommers** [comment]
Hi @charlesoconor, we only require Jinja<3 for Python 2. There's no upper limit on Jinja for Py 3.x

From setup.py:
```
"Jinja2>=2.10.1",
"Jinja2<3.0.0; python_version < '3'",
```
