### ISSUE TITLE
SES get_dkim_tokens creates duplicate domain

### ISSUE THREAD

**Issue by mdavis-xyz** [spulec/moto#3947]
# Steps to reproduce:

```
from moto import mock_ses
import boto3
import unittest

class TestMoto(unittest.TestCase):
    def test_moto(self):
        domain = 'example.com'
        with mock_ses():
            client = boto3.client('ses')
        
            response = client.list_identities(IdentityType='Domain')
            self.assertEqual(sum([(domain == i) for i in response.get('Identities', [])]), 0)
        
            ret = client.verify_domain_identity(Domain=domain)
            response = client.list_identities(IdentityType='Domain')
            self.assertEqual(sum([(domain == i) for i in response.get('Identities', [])]), 1)
        
            response = client.verify_domain_dkim(Domain=domain)
            response = client.list_identities(IdentityType='Domain')
            self.assertEqual(sum([(domain == i) for i in response.get('Identities', [])]), 1)
                
```

Save as `test.py` and run with `python3 -m unittest test.py`

# Expected behavior

The test passes.

i.e. when `verify_domain_dkim` is called, it checks whether the domain already exists in the list,
and doesn't re-add it as a duplicate.

To confirm the expected behavior, comment out `with mock_ses()` and run against real AWS.

# Actual behavior

The script fails. The final assertion fails.

`verify_domain_dkim` seems to have created a second domain, without checking whether it's already added.

**Comment by bblommers** [comment]
Thanks for raising this and for providing the test case @mdavis-xyz - that's very helpful. 
Looks like we're storing domains as a simple list, instead of as a set. Marking it as a bug.
