### ISSUE TITLE
Support SSM AWS Region Query

### ISSUE THREAD

**Issue by Amri91** [spulec/moto#3949]
## Steps to reproduce

moto: 2.0.7
boto3: 1.17.75

```python3
from moto import mock_ssm
import boto3
import unittest

class TestMoto(unittest.TestCase):
    def test_ssm_region_query(self):
        with mock_ssm():
            self.assertEqual(
                boto3.client('ssm').get_parameter(
                    Name='/aws/service/global-infrastructure/regions/us-west-1/longName'
                )['Parameter']['Value'],
                'US West (N. California)',
            )
```

Save as test.py and run with python3 -m unittest test.py

## Expected behavior

The test passes.

## Actual behavior

The test fails.

## Context

I am trying to access the recently added global ssm paramters: [https://aws.amazon.com/blogs/aws/new-query-for-aws-regions-endpoints-and-more-using-aws-systems-manager-parameter-store/](https://aws.amazon.com/blogs/aws/new-query-for-aws-regions-endpoints-and-more-using-aws-systems-manager-parameter-store/)

Unfortunately get_parameters_by_path returns an empty list.

```
client.get_parameters_by_path(
    Path='/aws/service/global-infrastructure/regions'
)
```

I tried this

```
client.put_parameter(
    Name='/aws/service/global-infrastructure/regions/us-west-1/longName',
    Value='US West (N. California)'
)
```

but it is giving me this error

```jsx
botocore.exceptions.ClientError: An error occurred (AccessDeniedException) when calling the PutParameter operation: No access to reserved parameter name: /aws/service/global-infrastructure/regions/us-west-1/longName.
```

and trying to access the parameter directly gives me this

```jsx
botocore.errorfactory.ParameterNotFound: An error occurred (ParameterNotFound) when calling the GetParameter operation: Parameter /aws/service/global-infrastructure/regions/us-west-1/longName not found.
```

**Comment by bblommers** [comment]
Thanks for raising this @Amri91. We're not storing any default parameters atm - marking this as an enhancement.
