### ISSUE TITLE
using freezegun with moto version 2.0.8 stop working

### ISSUE THREAD

**Issue by yaronbenezra** [spulec/moto#3954]
Hi ,

Hope you can help,
i am using freezegun to stop time when I am sending message to SNS and received it from the SQS subscribe to it 
when i am adding with freeze_time("2015-01-01 12:00:00") the message is not getting to the Q, without all work

Regards,
Yaron

**Comment by bblommers** [comment]
Hi, AWS automatically drops/deletes messages older than 43200 seconds. Moto replicates this behavior as of 2.0.8

Are you only freezing the time when sending the message, or also when receiving it?  As long as there's less then 43200 seconds between those two, it should work.

**Comment by bblommers** [comment]
Happy to hear that! I'll close this for now, but let me know if you run into any other issues
