### ISSUE TITLE
Missing "ConsumedCapacity" from dynamodb2's get_item() response when "ReturnConsumedCapacity" specified but the item doesn't exist

### ISSUE THREAD

**Issue by bensfly** [spulec/moto#3959]
For dynamodb client, when calling get_item(..., ReturnConsumedCapacity='TOTAL') for an item that doesn't exist, moto does not include the key 'ConsumedCapacity' in the response, while boto3 does (when not being mocked).

Note that when the item requested DOES exist, then ReturnConsumedCapacity IS included as expected.

How to reproduce:
```
import boto3
from moto import mock_dynamodb2

with mock_dynamodb2():
    conn = boto3.client("dynamodb", region_name="us-east-1")
    conn.create_table(
            TableName='test_table',
            KeySchema=[{'AttributeName': 'u', 'KeyType': 'HASH'}],
            AttributeDefinitions=[{'AttributeName': 'u', 'AttributeType':  'S'}]
        )
    response = conn.get_item(TableName='test_table', Key={'u': {'S': 'does_not_exist'}}, ReturnConsumedCapacity='TOTAL')
    assert 'ConsumedCapacity' in response    # Fails, but should succeed!
```
Expected Response:
```
{
  'ConsumedCapacity': {
    'TableName': 'test_table',
    'CapacityUnits': 0.5
  },
  'ResponseMetadata': ...
}
```
Actual Response:
```
{
  'ResponseMetadata': ...
}
```

Reference ([Boto3 Documentation](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/dynamodb.html#DynamoDB.Client.get_item)):
ConsumedCapacity (dict) --
The capacity units consumed by the GetItem operation. The data returned includes the total provisioned throughput consumed, along with statistics for the table and any indexes involved in the operation. ConsumedCapacity is only returned if the ReturnConsumedCapacity parameter was specified. 

Installed packages:
moto==2.0.8
boto3==1.17.78

**Comment by bensfly** [comment]
Likely relevant moto code ([moto/dynamodb2/responses.py: Line 374](https://github.com/spulec/moto/blob/d6384fcb35dd1f3e546b6049cb5d7e9fad9243e1/moto/dynamodb2/responses.py#L374)):
```
class DynamoHandler(BaseResponse):
    ....

    def get_item(self):
        ...
        if item:
            item_dict = item.describe_attrs(attributes=None)
            item_dict["ConsumedCapacity"] = {"TableName": name, "CapacityUnits": 0.5}
            return dynamo_json_dump(item_dict)
        else:
            # Item not found
            return 200, self.response_headers, "{}"```

**Comment by bensfly** [comment]
It looks like this is part of a larger issue that this function ignores the existence of the parameter ReturnConsumedCapacity entirely, and returns ConsumedCapacity if items exist and does not if items do not exist.
This is in contrast to boto3's behavior where it returns ConsumedCapacity if the parameter ReturnConsumedCapacity is specified, and does not if it remains the default of "NONE".

Reference ([Boto3 Documentation](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/dynamodb.html#DynamoDB.Client.get_item)):
ReturnConsumedCapacity (string) --
Determines the level of detail about provisioned throughput consumption that is returned in the response:

INDEXES - The response includes the aggregate ConsumedCapacity for the operation, together with ConsumedCapacity for each table and secondary index that was accessed. Note that some operations, such as GetItem and BatchGetItem , do not access any indexes at all. In these cases, specifying INDEXES will only return ConsumedCapacity information for table(s).
TOTAL - The response includes only the aggregate ConsumedCapacity for the operation.
NONE - No ConsumedCapacity details are included in the response.

**Comment by bpandola** [comment]
See also #2851
