### ISSUE TITLE
SSM Parameter Store Should Only Support 100 Versions

### ISSUE THREAD

**Issue by bigahen** [spulec/moto#3963]
Per https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-paramstore-versions.html - 

AWS SSM Parameter Store only supports 100 versions. After this point, the lowest version is deleted every time a new version is created. 

This functionality is not currently implemented in SimpleSystemManagerBackend. 

To reproduce, simply add 101 versions to a parameter and then fetch the history. Only the most recent 100 should be returned, instead all 101 are returned.

**Comment by bblommers** [comment]
Thanks for raising this @bigahen - marking this as an enhancement.

Some relevant information from that link, for whoever ends up implementing this:
```
An exception to this is when there are already 100 parameter versions in history, and a parameter label is assigned to the oldest version of a parameter. In this case, that version isn't removed from history, and the request to create a new parameter version fails. This safeguard is to prevent parameter versions with mission critical labels assigned to them from being deleted. To continue creating new parameters, first move the label from the oldest version of the parameter to a newer one for use in your operations.
```
