### ISSUE TITLE
No support for AWS::ElasticLoadBalancingV2::ListenerRule

### ISSUE THREAD

**Issue by sahilshah6196** [spulec/moto#3966]
## Reporting Bugs

There is no support for: `AWS::ElasticLoadBalancingV2::ListenerRule`

Here is the warning:
`WARNING  moto:parsing.py:219 No Moto CloudFormation support for AWS::ElasticLoadBalancingV2::ListenerRule`

**Comment by sahilshah6196** [comment]
Working on a fix for this

**Comment by bblommers** [comment]
This is now part of moto >= 2.0.9
