### ISSUE TITLE
New Service: wafv2

### ISSUE THREAD

**Issue by v-dev** [spulec/moto#3971]
Hello! I would like to add support for a few wafv2 APIs. Who do I talk to about this?

So far, I ran `scripts/scaffold.py` and had success with a basic mock of `list-web-acls`. Wondering if I should now open a PR, or include more models and/or APIs such as `get-web-acl` and other CRUD operations?

My end goal is to have these used within [localstack](https://github.com/localstack/localstack).

Thank you.

**Comment by bblommers** [comment]
Hi @v-dev, welcome to Moto!

I'd recommend to open a PR now, just to get some early feedback. You can mark it as a draft and keep working on it in the background, if you want to add other models/operations etc.
