### ISSUE TITLE
Wrong error message when pushing logs to non-existent stream in existing group

### ISSUE THREAD

**Issue by mdavis-xyz** [spulec/moto#3978]
# MWE

```
import boto3
from moto import mock_logs
from time import time

mock_logs().start()

group_name = 'my-group-2'
stream_name = 'my-stream'

client = boto3.client('logs')

client.create_log_group(logGroupName=group_name)

# I forgot to do this in my real code
# so the error from moto/boto should tell me this is the part I forgot
#client.create_log_stream(
#    logGroupName=group_name,
#    logStreamName=stream_name
#)

client.put_log_events(
    logGroupName=group_name,
    logStreamName=stream_name,
    logEvents=[
        {
            'timestamp': int(time()),
            'message': 'test'
        },
    ]
)
```

# Expected behavior

If you run the above script without `moto`, you get:

> botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the PutLogEvents operation: The specified log **stream** does not exist.

# actual behavior

If you run the above script with `moto`, you get:

> botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the PutLogEvents operation: The specified log **group** does not exist

The group *does* exist. The problem with the `put_log_events` call is that the *stream* does not exist. This difference in error message makes it hard to figure out why the whole script does not pass.

**Comment by bblommers** [comment]
Thanks @mdavis-xyz - marking it as an enhancement
