### ISSUE TITLE
Mock lambda with body > 6Mb does not respond with 6Mb limit error

### ISSUE THREAD

**Issue by dazza-codes** [spulec/moto#3988]
The sample lambda function should try to return a response that is too large:

```python
def lambda_handler(event, context):
    import sys

    x = ["xxx" for x in range(10 ** 6)]
    assert sys.getsizeof(x) > 6291556
    return {"statusCode": 200, "body": x}
```

When this is called in a moto lambda mock, it returns successfully.  It should return an error that the response exceeds the 6MB limit.

https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-limits.html notes that synchronous functions have limits:
- 6Mb for synchronous invoke payload and response
- the bytes value of `6291556` is from a live AWS Lambda error message

The error message is

```
'{\n "errorMessage": "Response payload size exceeded maximum allowed payload size (6291556 bytes).",\n "errorType": "Function.ResponseSizeTooLarge"\n}'
```

Or

```json
{
    "errorMessage": "Response payload size exceeded maximum allowed payload size (6291556 bytes).",
    "errorType": "Function.ResponseSizeTooLarge",
}
```

**Comment by Nick01a** [comment]
hacked the system)
