### ISSUE TITLE
AWS Batch moto uses docker: how come?

### ISSUE THREAD

**Issue by orenmazor** [spulec/moto#3997]
Hi there, this is not a bug report.

Instead, I'm curious about the design of the aws batch backend. 

why is it using actual threads? why does it require docker? how come there's no option for it to be dumber? i.e. I'd be perfectly content with a backend that simply simulates that a job ran and immediately responds with a result, like athena does for queries.

one of my favourite things about moto, and why I use it instead of things like localstack, is that I'm perfectly happy with mocked responses and something that doesnt require more moving parts in my testing. as is, to use batch in my tests, I need to use d-in-d in gitlab cicd. not difficult, but seems like overkill?

**Comment by bblommers** [comment]
Hi @orenmazor, most of our features are submitted by the community, so I imagine that the first person to require Batch needed a 'smarter' version that runs on Docker.

It does make sense to have a simpler/faster version of Batch, so PR's are always welcome :)

**Comment by bblommers** [comment]
Moto 3.1.8 now has the option to mock Batch in a simple (docker-less) manner.
To enable this, use `@mock_batch_simple` instead of `@mock_batch` around your tests.

Documentation: http://docs.getmoto.org/en/latest/docs/services/batch.html

I'll close this, but do let us know if you're running into any issues with this!

**Comment by orenmazor** [comment]
this is awesome. thanks so much @bblommers, I'll give this a whirl sometime soon. it'll make my test suite setup so much cleaner!
