### ISSUE TITLE
Build support for EFS functionality

### ISSUE THREAD

**Issue by pagreene** [spulec/moto#4010]
Our architecture depends heavily on EFS, which has relatively few actions to implement. I would like to propose contributing an implementation of support for EFS, submitting this issue as per: https://github.com/spulec/moto/blob/master/CONTRIBUTING.md.

**Comment by bblommers** [comment]
Hi @pagreene, welcome to Moto! PR's are always welcome.

There's a section in the documentation [here](https://github.com/spulec/moto/blob/master/CONTRIBUTING.md#missing-services) with some guidelines on how to get started. Every service is different, so some investigation might still be necessary, but it can at least get you started.

Let me know if you run into any issues -  happy to help.

**Comment by bblommers** [comment]
I'll close this issue, as the initial EFS implementation has now been released.
Feel free to open additional issues/PR's for any other services/methods that are missing.

**Comment by pagreene** [comment]
Sounds good, thanks!
