### ISSUE TITLE
Tags are not being propagated to cloudformation resources

### ISSUE THREAD

**Issue by sahilshah6196** [spulec/moto#4013]
## Reporting Bugs

Per [boto3 documentation](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/cloudformation.html#CloudFormation.Client.create_stack) if `Tags` are passed when `create_stack` is called, those tags must also be propagated to the resources created in that stack.
`Tags (list) --
Key-value pairs to associate with this stack. AWS CloudFormation also propagates these tags to the resources created in the stack. A maximum number of 50 tags can be specified.`

I do not think moto is propagating these tags to the resources created when creating the stack.

**Comment by sahilshah6196** [comment]
@bblommers Is that correct? Also, if so, is there a way to get passed it?

**Comment by bblommers** [comment]
Hi @sahilshah6196, that's partially correct. Tags are propagated to EC2 resources, but not to any other services.

See this section of the CF logic: https://github.com/spulec/moto/blob/master/moto/cloudformation/parsing.py#L603

There's no way around that currently, afaik. Will mark it as an enhancement to have a more centralized approach to storing tags.

**Comment by sahilshah6196** [comment]
> Hi @sahilshah6196, that's partially correct. Tags are propagated to EC2 resources, but not to any other services.
> 
> See this section of the CF logic: https://github.com/spulec/moto/blob/master/moto/cloudformation/parsing.py#L603
> 
> There's no way around that currently, afaik. Will mark it as an enhancement to have a more centralized approach to storing tags.

Ah! I see. Thanks for the info

**Comment by skinitimski** [comment]
For what it is worth, in my experience CloudFormation itself does not always propagate tags to resources, and is especially poor at updating tags.

**Comment by bblommers** [comment]
@sahilshah6196 Was there a specific service/resource that you wanted fixed?
Given the fact that AWS is not consistent in this approach either, and the work involved to completely copy that behaviour, we might be better off reducing the scope to only what is needed now.
