### ISSUE TITLE
KeyError from multipart_upload.parts.all

### ISSUE THREAD

**Issue by cdraper-CS** [spulec/moto#4018]
I'm trying to mock some code that creates a multipart upload, then aborts it without writing any parts, then lists the parts. The expected error is 'NoSuchUpload' but instead I am getting a KeyError as shown in stacktrace below. ​

I'm using moto 2.0.9,  boto3 1.17.97 and botocore 1.20.97.

Reproduce:
```
from moto import mock_s3
import boto3
import os
s3 = boto3.client('s3')

bucket_name='my-bucket'

@mock_s3
def test_mocked():
    os.environ['AWS_SECRET_ACCESS_KEY']='some-value'
    os.environ['AWS_ACCESS_KEY_ID']='some-value'
    os.environ['AWS_SHARED_CREDENTIALS_FILE']='random-234-test'
    os.environ['AWS_CONFIG_FILE']='random324test'
    bucket = boto3.resource('s3').Bucket(bucket_name)
    bucket.create()
    test_mpu()

def test_mpu():
    bucket = boto3.resource('s3').Bucket(bucket_name)
    s3_object = bucket.Object('my/test')
    multipart_upload = s3_object.initiate_multipart_upload()
    multipart_upload.abort()
    list(multipart_upload.parts.all())
```

`python -c 'from testmpu import test_mpu; test_mpu()'` gives 'NoSuchUpload' as expected; `python -c 'from testmpu import test_mocked; test_mocked()'` gives a KeyError as in attached.
[motoerror.txt](https://github.com/spulec/moto/files/6674148/motoerror.txt)

**Comment by bblommers** [comment]
Thanks for raising this and providing the test case @cdraper-CS - that's very useful. Marking it as a bug.
