### ISSUE TITLE
CloudWatch put_metric_alarm does not handle TreatMissingData parameter

### ISSUE THREAD

**Issue by Vilsepi** [spulec/moto#4020]
On moto 2.0.9, when creating a CloudWatch metric alarm, you can pass the `TreatMissingData` parameter, but it is not stored by moto.

**What is expected to happen:** When describing alarms, an alarm should have the `TreatMissingData` property which was passed when creating that alarm.

**What actually happens:** When describing alarms, none of the alarms have `TreatMissingData`, even though it was passed when creating those alarms.

**How to reproduce the issue:**

This code should pass but instead fails the assert.

```
import os
import pytest
from moto import mock_cloudwatch
import boto3

@pytest.fixture(scope="function")
def aws_credentials():
    os.environ["AWS_ACCESS_KEY_ID"] = "testing"
    os.environ["AWS_SECRET_ACCESS_KEY"] = "testing"
    os.environ["AWS_SECURITY_TOKEN"] = "testing"
    os.environ["AWS_SESSION_TOKEN"] = "testing"

@pytest.fixture(scope="function")
def cloudwatch(aws_credentials):
    with mock_cloudwatch():
        yield boto3.client("cloudwatch", region_name="eu-west-1")

def test_moto_issue2(cloudwatch):
    cloudwatch.put_metric_alarm(
        AlarmName="MyAlarm",
        ActionsEnabled=True,
        AlarmActions=["foo_alarm_arn"],
        MetricName="DDoSDetected",
        Namespace="AWS/DDoSProtection",
        Statistic="Maximum",
        Dimensions=[
            {
                "Name": "ResourceArn",
                "Value": "foo_resource_arn"
            }
        ],
        Period=60,
        EvaluationPeriods=1,
        DatapointsToAlarm=1,
        Threshold=0.0,
        TreatMissingData="notBreaching",
        ComparisonOperator="GreaterThanThreshold"
    )
    alarm = cloudwatch.describe_alarms()["MetricAlarms"][0]
    assert alarm["TreatMissingData"] == "notBreaching"

```

I looked at the [responses.py](https://github.com/spulec/moto/blob/03b2009a1c065196be1256836473e8d72c4f65ab/moto/cloudwatch/responses.py#L18) and it seems like it's missing that parameter. Is this code written by hand or generated from AWS interface specifications, i.e. should this be added by hand or by fetching a newer API spec from AWS?

**Comment by bblommers** [comment]
Hi @Vilsepi, some boilerplace code can be generated when creating a service from scratch, but afterwards everything has to be added manually unfortunately. Marking it as an enhancement to add this parameter.

**Comment by gruebel** [comment]
@bblommers you can assign me to it, I will also add tags functionality to CloudWatch  resources.
