### ISSUE TITLE
Issue with python moto library in poetry base project

### ISSUE THREAD

**Issue by irshad-japy** [spulec/moto#4025]
we did added moto dependency "poetry add moto==2.0.9" , its installed already, but still in python file "from moto import mock_s3" is not recognized.
![image](https://user-images.githubusercontent.com/86293640/122904347-e01fab80-d36d-11eb-945b-0add1aad10a0.png)
[](url)

I have recently started using poetry to get benefits like no conflicts with libraries.

**Comment by bblommers** [comment]
Hi @irshad-japy, are you getting errors in your IDE? It works fine for me in Powershell:

```
poetry new test
cd test
poetry add moto==2.0.9
poetry shell
python
>> from moto import mock_s3
```

**Comment by bblommers** [comment]
Going to close this due to a lack of response - feel free to reopen if there's still an issue
