### ISSUE TITLE
Account ID is 10 instead of 12 digits?

### ISSUE THREAD

**Issue by michael-robbins** [spulec/moto#4028]
Staring at examples like this: https://github.com/spulec/moto/blob/master/moto/ssm/utils.py

I can see that we're using 10 digit account IDs, but AWS use 12 digit account IDs... which makes any ARN regex matching not work.

Am I missing something obvious here? (like we do this for a good reason that isn't mentioned in the doco/anywhere)?

**Comment by bblommers** [comment]
Hey @michael-robbins, thanks for raising this.

All services should be using the same centralized accountID that's defined here: https://github.com/spulec/moto/blob/master/moto/core/models.py#L32
That was only introduced relatively recently though, so not all services have been refactored to use it yet.

Do you have any other examples of rogue account IDs?

**Comment by michael-robbins** [comment]
Just doing a cursory search seems the one I cared about is one of the 'few' left to migrate: https://github.com/spulec/moto/search?q=1234567890
