### ISSUE TITLE
Support ELB tags

### ISSUE THREAD

**Issue by pitluga** [spulec/moto#403]
I'd like to be able to add tags to our ELBs. There is a boto issue that's been open for about a year adding tags https://github.com/boto/boto/issues/2549, so it doesn't seem like it will be added there. Boto3 has this feature, but only supports API versions `2014-09-01`, `2014-10-01`, `2015-03-01`, and `2015-04-15`. Moto's responses use API version `2012-06-01` so boto3 cannot parse moto's responses.

Any guidance on how to add this feature? Should we upgrade the ELB responses to the most recent version provided it works with boto 2.36? I didn't want to do a bunch of work that wouldn't get merged in.

I was thinking of doing two PRs, one upgrading moto to support boto3 for ELBs and a second adding ELB tags. Sound like a plan?

**Comment by spulec** [comment]
Sounds perfect

**Comment by spulec** [comment]
Fixed with #408
