### ISSUE TITLE
HTTP Endpoint for Serving Files in S3?

### ISSUE THREAD

**Issue by jamiejackson** [spulec/moto#4044]
Is moto able to serve files via HTTP (the way that AWS S3 can)? I'm considering using moto in place of real S3 for local development but I'm not sure if it only mocks the AWS APIs.

(I'm not sure if this is an appropriate place to ask questions; I couldn't find any mailing list, IRC, etc., info in the readme.)

**Comment by bblommers** [comment]
Hi @jamiejackson, yes, this is supported, and yes, this is probably the best place to ask :)

Are you planning on using the decorators? Have a look at this example test case, to see how this works:
```
@mock_s3
def test_s3_http_access():
    s3 = boto3.resource("s3", region_name="us-east-1")

    public_bucket_name = "test-bucket"
    private_bucket_name = "private-test-bucket"
    bucket = s3.Bucket(public_bucket_name)
    bucket.create(ACL="public-read")
    bucket.put_object(Body=b"ABCD", Key="file.txt")
    private_bucket = s3.Bucket(private_bucket_name)
    private_bucket.create()
    private_bucket.put_object(Body=b"private ABCD", Key="privatefile.txt")

    params = {"Bucket": private_bucket_name, "Key": "privatefile.txt"}
    presigned_url = boto3.client("s3").generate_presigned_url(
        "get_object", params, ExpiresIn=900
    )

    # Presigned URLs are supported
    response = requests.get(presigned_url)
    assert response.status_code == 200

    # Public URLs are supported
    public_url = "https://{}.s3.amazonaws.com/file.txt".format(public_bucket_name)
    assert requests.get(public_url).status_code == 200

    # Private URLs throw a 403 without auth
    private_url = "https://{}.s3.amazonaws.com/privatefile.txt".format(private_bucket_name)
    assert requests.get(private_url).status_code == 403
```

**Comment by jamiejackson** [comment]
Thanks for the reply, @bblommers. I've used moto for Python testing, but this use case would involve the standalone moto service, to be used by a non-Python app. It might be convenient to do local development (manual experiments, etc.) against that instead of either using a native filesystem (which is a little weird to have the app try to adapt to either scenario) or using a real, external S3.

A little more detail on the use case. In local development, in my (non-Python CMS) application, I'd like to be able to create a content page that contains an image which is also uploaded (to S3) through the CMS. When I view the page in a browser, I would like to be able to see the image load from the mock S3 (via the HTTPS endpoint). Therefore, the standalone moto server would need to provide me an HTTP endpoint that serves bucket content (e.g., pseudo-URL: http://localhost:9999/bucket1/path/to/uploaded/file.png).

**Comment by bblommers** [comment]
That makes sense - that's a fairly straightforward use case for Moto. The pseudo-url is exactly the one you'd call to access any uploaded files.
Using the AWS CLI as an example to create the file in the first place:

```
pip install moto
moto_server
```
```
aws --endpoint-url=http://127.0.0.1:5000 s3api create-bucket --bucket publicbucket --acl public-read --region us-east-1
aws --endpoint-url=http://127.0.0.1:5000 s3api put-object --bucket publicbucket --key server.py --body moto/server.py
curl http://localhost:5000/publicbucket/server.py
```

(I used the CLI because it's easiest to setup, but any SDK would work - as long as the `endpoint-url` points to the local server.)

**Comment by jamiejackson** [comment]
Thanks for the help, @bblommers!

I hit a wall with my app server not supporting `endpoint-url` yet, but may revisit this if the project fixes this (or if I get time enough to submit a PR). https://luceeserver.atlassian.net/browse/LDEV-3594
