### ISSUE TITLE
Is there a way to inject fixtures before start mock

### ISSUE THREAD

**Issue by ZuluPro** [spulec/moto#406]
I would like to create a full mocked environment, with AMIs, kernels and etc, already here before a test.

For example, to get a new AMIs, I must create it from a fake instance. I would like to be able to create them without use fake boto connection.

I search in moto's unit tests but didn't find, I saw in unittest for create an image:
`conn.create_image(instanceA.id, "test-ami-A", "this is a test ami")`

I would like something more like this:
````
fixtures = {
  'us-east-1': {
    'images': [{'architecture': 'x86', 'platform': 'linux'}]
  }
}

MockAWS(fixtures=fixtures)
```

or

```
@mock_s3(fixtures=fixtures)
def test_my_model_save():
    ...
```

**Comment by spulec** [comment]
You should be able to use cloudformation for this. If that doesn't work, feel free to reopen.

**Comment by ZuluPro** [comment]
Yes, Cloudformation could help me to produce fixtures, but I'm looking for a way without use Boto.
A real option for set set of objects in MockAws.

I'm volunteer to make the patch if it's planned.

**Comment by spulec** [comment]
Just curious, what is the reason for not using boto?

**Comment by ZuluPro** [comment]
Because 
- My tests are launched as user and I would like to be able to create environment where I can specify every components' attributes.
- I would like a strict mode to Moto, if an element like an image is not found when instance creation, it raises an error.

Boto does not allow to create everything such as images or size. And the way to do it is a tedious for a lot of stuff. I looked at moto's unit test before.

I would like to create a bunch of specific images, size and more. Objects which shouldn't be entirely managed by users.

**Comment by spulec** [comment]
My fear is that we will largely be recreating cloudformation. Is there any way we could tie it into that?

If you want to take a shot at a small implementation for AMIs or something like that, we can see how the code looks.
