### ISSUE TITLE
How to raise an Exception

### ISSUE THREAD

**Issue by KiraPC** [spulec/moto#4062]
This is not a bug but a support request.

Is there a way to raise a specific exception with moto?

I mean, I have a client, and when it is called by some arguments, I would like to raise an Exception.

Thanks you

**Comment by bblommers** [comment]
Hi @KiraPC, Moto should throw the same exceptions as AWS does, if all the requirements are met (missing parameters, invalid values, etc).
There's no build-in method to force an error though.

Which exception do you need to raise, on which service/method?

**Comment by KiraPC** [comment]
Hi @bblommers thanks you for the quickly response.

No specific exception, I was just thinking about some possibile scenarios in my application tests.

Anyway, I got the point, I'll try to figured out in another way.
