### ISSUE TITLE
Cognito-idp - Duplicate and/or empty data in Attributes

### ISSUE THREAD

**Issue by alastairmccormack** [spulec/moto#4069]
# Issue
When using `cognito-idp.admin_create_user` and subsequent `get-user` requests, the Attributes response object contains fields that were not specified during `admin_create_user`. Some of the fields duplicate the supplied attributes but with different values.

This issue seems to be caused by https://github.com/spulec/moto/pull/4038.

It seems that the contributor has assumed a number of attributes and also provides empty values even if the attribute was given during the create.

When creating a user pool, there are no default attributes so should not be assumed.

# Steps to reproduce

- Create User: 
```
    result = conn.admin_create_user(
        UserPoolId=user_pool_id,
        Username=username,
        UserAttributes=[
            {"Name": "thing", "Value": 'test1'},
            {"Name": "family_name", "Value": 'test2'}
        ],
    )
```

# Expected result

```
pprint.pprint(result['User']['Attributes'])
[{'Name': 'thing', 'Value': 'test1'},
 {'Name': 'family_name', 'Value': 'test2'},
 {'Name': 'sub', 'Value': 'd7872c09-f6ff-4fae-a1f8-b56b740c8084'},
```

# Actual result

```
pprint.pprint(result['User']['Attributes'])
[{'Name': 'thing', 'Value': 'test1'},
 {'Name': 'family_name', 'Value': 'test2'},
 {'Name': 'sub', 'Value': 'd7872c09-f6ff-4fae-a1f8-b56b740c8084'},
 {'Name': 'email_verified', 'Value': True},
 {'Name': 'name', 'Value': ''},
 {'Name': 'family_name', 'Value': ''}]
```
# Version
2.0.11

# Last working version
2.0.10

# Impact
Breaking existing tests

**Comment by bblommers** [comment]
Thanks for raising @alastairmccormack  - this was fixed in #4070
