### ISSUE TITLE
AWS Rekognition support

### ISSUE THREAD

**Issue by Robmosh91** [spulec/moto#4071]
HI,

first, thanks for this awesome project which helped me a lot.
Currently I'm looking for a way to mock the AWS Rekognition Service and would like to contribute to its implementation.

Can you give any guidance on how to start? 
If anybody else would like to contribute, I'm happy to co-work on this.

**Comment by bblommers** [comment]
Hi @Robmosh91, that sounds good - new services are always welcome!
There's some documentation how to add new services here: 
https://github.com/spulec/moto/blob/master/CONTRIBUTING.md#missing-services

Hopefully that's useful. Feel free to ask any questions if you get stuck, or just open a draft PR if there's something specific that doesn't work.

**Comment by bblommers** [comment]
With Moto 3.1.4.dev3 we now have an initial Rekognition implementation, with support for the features `start_text_detection` and `get_text_detection`.

I'll close this, but feel free to open a new issue or PR if you'd like to see any other features!
