### ISSUE TITLE
Add PrivateIpAddress field for Elastic Ip Model

### ISSUE THREAD

**Issue by clowe-r7** [spulec/moto#4088]
When associating mocked elastic ips to a mocked resource (ec2, rds, etc), the elastic ip model should include a PrivateIpAddress field which would be shown in a response from the ec2 client `describe_addresses` method as in the example in the boto3 docs here https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2.html#EC2.Client.describe_addresses

Version:
moto==2.0.4

**Comment by bblommers** [comment]
Thanks for raising this @clowe-r7 - marking it as an enhancement to add this field
