### ISSUE TITLE
Support tags on autoscaling groups

### ISSUE THREAD

**Issue by pcorliss** [spulec/moto#409]
Autoscaling group tags don't appear to be supported yet.

**Comment by spulec** [comment]
Thanks for opening! You are correct.

I'll add it to the list. If someone else gets some time and wants to take a stab at it, it shouldn't be that complicated.

**Comment by spulec** [comment]
This was added with https://github.com/spulec/moto/commit/b3096af0989db4edc1b8f03051c99c48c7ac81e7
