### ISSUE TITLE
Improve response time `//moto-api/reset`

### ISSUE THREAD

**Issue by AndreiBarsan** [spulec/moto#4090]
Hi everyone, 

I am using moto 2.2.0 on Python 3.8. I am testing code which uses s3fs, and testing it using `moto_server s3`. This is necessary as moto seems to have problems working with async file systems unless it runs as a standalone server.

There seems to be a large (5-6 second) overhead when calling `reset` the first time in my fixture, even after not having touched the emulated S3 at all. Subsequent calls return very quickly. Here is an example from a test run:

```
.2021-07-26 16:19:39,453 WARNING Returning from s3 base...
127.0.0.1 - - [26/Jul/2021 16:19:46] "POST //moto-api/reset HTTP/1.1" 200 -
```

I can't paste the exact setup since a lot of the code is internal, but the problematic fixture is the following:

```python
@pytest.fixture(name="s3_base")
def _s3_base(monkeypatch, s3_session_base, mocked_s3_uri):
    try:
        with monkeypatch.context() as m:
            # This ensures we always fail if we accidentally bypass moto in tests which should mock AWS, while the
            # monkeypatch context also prevents interference with (exceptional) tests that actually need to touch the
            # real S3, e.g., to check whether a bucket exists.
            m.setenv("AWS_SECRET_ACCESS_KEY", "fake_secret_access_key")
            m.setenv("AWS_ACCESS_KEY_ID", "fake_access_key_id")
            yield
    finally:
        logging.warning("Returning from s3 base...")
        requests.post(mocked_s3_uri + "/moto-api/reset")
        logging.warning("Server reset OK")
```
`s3_session_base` basically provides the moto server wrapped in a fixture, similar to the code in the `s3fs` code base.

The gap between making the POST request in the `finally` block and the moto server actually acknowledging it is ~7 seconds. Everything else, including moto server setup, is fast, less than 100ms or so.

My original goal was to allow the moto server to be reused throughout a module, and just reset it for every test, but right now it seems like just re-creating the server for every single test is faster, which seems odd.

Any pointers as to what could be causing the moto server to respond so slowly? Maybe something I could have misconfigured?

**Comment by bblommers** [comment]
Hi @AndreiBarsan, I've just tested this locally, and I'm seeing about the same response times. So it's not due to a misconfiguration - Moto just happens to be slow.

The basic algorithm to execute this reset is like this:
```
for each service:
    import module
    for each region:
        reset module x for region y
```

The majority of the clock cycles are spend on importing each individual module. Because of this, it is really just the first call that is slow - subsequent calls are quick, as everything is loaded into memory at that point:
```
logger.warning("Returning from s3 base...")
requests.post("http://localhost:5000/moto-api/reset")
logger.warning("Server reset OK")
requests.post("http://localhost:5000/moto-api/reset")
logger.warning("Server reset OK")
...
2021-07-27 14:39:30,054 — test_4090 — WARNING — Returning from s3 base...
2021-07-27 14:39:35,831 — test_4090 — WARNING — Server reset OK
2021-07-27 14:39:35,950 — test_4090 — WARNING — Server reset OK
```

> My original goal was to allow the moto server to be reused throughout a module, and just reset it for every test
>
This still sounds like the best approach IMO. Can you reset it immediately after initializing `s3_session_base`, to warmup the server?

**Comment by AndreiBarsan** [comment]
I will try that, thank you for the context and replication @bblommers!

Would it make sense to make reset aware of what services have actually been used? In my case I am exclusively testing `s3` functionality with small objects. Specifically, I am launching `moto_server` as `moto_server s3 ...` so maybe it could keep track of that service only?

**Comment by bblommers** [comment]
Yeah, that makes sense @AndreiBarsan. Either that, or simply add a specific endpoint to reset only a single service (`requests.post("http://localhost:5000/moto-api/resetservice/s3")`).
I'll mark this issue as an enhancement, if anyone wants to pick this up.

**Comment by bblommers** [comment]
Hi @AndreiBarsan, as of Moto 2.2.7 we've made a number of performance improvements in ServerMode, and that includes improving the reset-API. 

>
> Specifically, I am launching moto_server as moto_server s3 ... so maybe it could keep track of that service only?

Moto now only resets the services that can be found in memory, so a similar approach to this, and it should be significantly faster for your usecase.
Are you able to upgrade and test this out?

**Comment by AndreiBarsan** [comment]
This is fantastic @bblommers! Works like a charm with the new update. The teardowns now take negligible amounts of time. Thank you!

Before:
```python -m pytest ... --maxfail=4 --durations=10 -n 4
====================================================================== test session starts ======================================================================
platform linux -- Python 3.8.7, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /home/andrei/... configfile: setup.cfg
plugins: ...
gw0 [143] / gw1 [143] / gw2 [143] / gw3 [143]
.........................................................................................................................s.....................           [100%]
============================================================= slowest 10 durations ==============================================================
5.23s teardown <moto test>
5.20s teardown <moto_test>
5.16s teardown <moto test>
5.08s teardown <moto test>
0.92s setup    <moto test>
0.83s setup    <moto test>
0.81s setup    <moto test>
...
========================================================= 142 passed, 1 skipped in 18.17s ========================================================
```

After:
```
python -m pytest ... --maxfail=4 --durations=10 -n 4
====================================================================== test session starts ======================================================================platform linux -- Python 3.8.7, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /home/andrei/..., configfile: setup.cfg
plugins: ...
gw0 [143] / gw1 [143] / gw2 [143] / gw3 [143]
.....................................................................................................................s.........................           [100%]
===================================================================== slowest 10 durations ======================================================================
0.78s setup    <moto test>
0.67s setup    <moto test> 
0.66s setup    <moto test>
0.65s setup    <moto test>
0.51s call     <unrelated test>
...
================================================================ 142 passed, 1 skipped in 12.71s ===============================================================
```
