### ISSUE TITLE
URL Bases regular expressions not escaping dots

### ISSUE THREAD

**Issue by Cox65** [spulec/moto#4099]
All url bases patterns defined per services don't escape dots which brings to wrong backend identification when moto tries to match urls against patterns.
For example, if you mock both S3 and IoT services and you try to create a bucket starting with "iot" it will fail as it will match with the IoT Service url base.

Here is how to reproduce the issue.
``` python
import boto3
from moto import mock_iot, mock_s3


class TestMockS3:
    @mock_iot
    @mock_s3
    def test_s3_mock(self):
        s3_client = boto3.client("s3", "eu-west-1")
        s3_client.create_bucket(
            ACL="private",
            Bucket="iot-bucket",
            CreateBucketConfiguration={"LocationConstraint": "eu-west-1"},
        )
```
Following error is raised:
**botocore.exceptions.ClientError: An error occurred (404) when calling the CreateBucket operation: Not Found**

In urls.py of IoT service:
`url_bases = ["https?://iot.(.+).amazonaws.com"]` matches with https://iot-bucket.s3.eu-west-1.amazonaws.com
It should be:
`url_bases = ["https?://iot\.(.+)\.amazonaws\.com"]`

The same regexp mistake in url_bases is applicable to all other services.

**Comment by bblommers** [comment]
Thanks for raising this and providing the fix, @Cox65!

**Comment by bblommers** [comment]
As a temporary workaround, it does work when changing the order of the decorators:
```
@mock_s3
@mock_iot
def test_s3_mock(self):
    s3_client = boto3.client("s3", "eu-west-1")
    s3_client.create_bucket(
        ACL="private",
        Bucket="iot-bucket",
        CreateBucketConfiguration={"LocationConstraint": "eu-west-1"},
    )
```
Which might mean that #3793 could fix this - but it doesn't fix the underlying issue of the faulty regexes. I'll send in a PR to fix those soon.

**Comment by Cox65** [comment]
Thanks for the workaround. In our case, we cannot really change the order of decorators because it's not as simple as the example I provided here. We are using some fixtures, etc...

As a temporary workaround we did this in our conftest.py:

``` python
# WORKAROUND until this issue is fixed https://github.com/spulec/moto/issues/4099
from moto.iot.urls import url_bases as iot_url_bases
iot_url_bases[0] = r"https?://iot\.(.+)\.amazonaws\.com"
```
