### ISSUE TITLE
Add support for ConfigService API list_tags_for_resource()

### ISSUE THREAD

**Issue by kbalk** [spulec/moto#4101]
moto's ConfigService code has some logic for tags, but it's incomplete.  It doesn't include the APIs for:

- [list_tags_for_resource()](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/config.html#ConfigService.Client.list_tags_for_resource)
- [tag_resource()](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/config.html#ConfigService.Client.tag_resource)
- [untag_resource()](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/config.html#ConfigService.Client.untag_resource)

Would you be willing to add support for these APIs?

**Comment by bblommers** [comment]
Hi @kbalk! I'll mark it as an enhancement.

As a word of warning, note that most of our features are added by the community, i.e. whoever needs it most will create a PR for it. So there's no timeline on when we get support for these features.

**Comment by kbalk** [comment]
I understand, in fact I've started working on the code, but was waiting for a response before I created a PR.

**Comment by bblommers** [comment]
Nice - let me know if you need any help 👍

**Comment by kbalk** [comment]
@bblommers The moto implementation of ConfigService defines "InvalidLimit", but the boto3 documentation specifies "InvalidLimitException".  Would it be ok if I replaced the current instances of InvalidLimit with InvalidLimitException?

I understand this would not be backward-compatible.

**Comment by kbalk** [comment]
@bblommers `CONTRIBUTING.md` indicated Python 2 must be supported, but `setup.py` implies that's not the case.  I could update `CONTRIBUTING.md` to remove that note.

Also, I was using f-strings, but they were introduced in Python 3.6 and it looks like you're still supporting Python 3.5?

**Comment by kbalk** [comment]
https://github.com/spulec/moto/pull/4117

**Comment by bblommers** [comment]
> 
> 
> @bblommers The moto implementation of ConfigService defines "InvalidLimit", but the boto3 documentation specifies "InvalidLimitException". Would it be ok if I replaced the current instances of InvalidLimit with InvalidLimitException?
> 
> I understand this would not be backward-compatible.

Sounds good to me! The closer we are to how AWS behaves, the better.

> 
> 
> @bblommers `CONTRIBUTING.md` indicated Python 2 must be supported, but `setup.py` implies that's not the case. I could update `CONTRIBUTING.md` to remove that note.
> 
> Also, I was using f-strings, but they were introduced in Python 3.6 and it looks like you're still supporting Python 3.5?
Our setup.py says we support 3.5, yes - but we don't really do any testing to verify that.
So feel free to use f-strings. I'll remove the Py2 and Py3.5 references later today. Thanks for checking!

**Comment by bblommers** [comment]
Fixed with #4117
