### ISSUE TITLE
Regions not supported in SQS

### ISSUE THREAD

**Issue by asgoel** [spulec/moto#411]
Is there region support in moto SQS right now? It seems like not.

```
mock_sqs = moto.mock_sqs()
mock_sqs.start()
sqs = boto3.resource("sqs", "us-west-1")
sqs.create_queue(QueueName="test")
sqs_client = boto3.client("sqs", "us-west-1")
url = sqs_client.get_queue_url(QueueName="test")["QueueUrl"]
print(url)
```
will give me: `http://sqs.us-east-1.amazonaws.com/123456789012/test`.

Let me know if I'm doing something wrong or missing something.

**Comment by spulec** [comment]
Thanks for opening this. There was a bug in the url attribute where us-east-1 had been hardcoded.
