### ISSUE TITLE
Cloudformation: ExecuteChangeSet should also change the status of the stack

### ISSUE THREAD

**Issue by xiaket** [spulec/moto#4141]
Hi there,

I was working on a Cloudformation library and I'm using moto to test the behaviour of cfn stacks. One thing I came across is the status of the stack is not changed after an `ExecuteChangeSet` call. In the following pseudo code:

```
    cfn.create_stack(
        StackName=stack.name,
        TemplateBody=old_json,
    )
    assert stack.status == "CREATE_COMPLETE"
    cfn.update_stack(
        StackName=stack.name,
        TemplateBody=new_json,
    )
    assert stack.status == "UPDATE_COMPLETE"
```

I'm expecting the `stack.status` in the last line to be `UPDATE_COMPLETE`, this is inline with Cloudformation behaviour. However, this assertion failed as `stack.status` is still `CREATE_COMPLETE` , that's because in this method:

https://github.com/spulec/moto/blob/79f0cc9e9e845461c337d1d297727483cfd0b651/moto/cloudformation/models.py#L683

We are merely adding events, and we have not changed the status of the stack.

Happy to create a PR to address this issue, please let me know what you think. Thanks!

**Comment by bblommers** [comment]
A PR would be very welcome, @xiaket! Looks like that's indeed not properly implemented in `execute_change_set`.
