### ISSUE TITLE
Feature Request: sso-admin create_account_assignment & delete_account_assignment

### ISSUE THREAD

**Issue by Arianna2028** [spulec/moto#4146]
I'm using boto3 to add and remove account assignments in AWS SSO and would like to mock the behavior using moto. The implemented endpoints list shows there is no sso-admin service yet, and I don't see any sso-related issues, so assuming there is no other work being done on that I'd like to tackle a couple initial endpoints for it.

**Comment by bblommers** [comment]
Hi @Arianna2028, welcome to Moto!
There are no plans to tackle SSO at the moment, so if you want to contribute, a PR would be very welcome!
There is a [section in our Contributing-doc](https://github.com/spulec/moto/blob/master/CONTRIBUTING.md#missing-services) that has some pointers on how to get started with a complete new service, hopefully that is enough to get you going. Let me know if you get stuck/have any questions at all.

**Comment by bblommers** [comment]
Hope you don't mind @Arianna2028 - I decided to give this a shot myself. The attached PR includes a very basic implementation for SSO-Admin. Let us know if there's anything missing, or if there are any other endpoints required!

**Comment by Arianna2028** [comment]
Hey, thanks! I don't mind at all-- thanks for tackling. Time seems to have gotten away from me here.
