### ISSUE TITLE
Handle UPSERT for route53

### ISSUE THREAD

**Issue by WyseNynja** [spulec/moto#415]
http://boto.readthedocs.org/en/latest/route53_tut.html#updating-a-record

I have this code that works with boto, but not with moto:

```
change = change_set.add_change('UPSERT', fqdn, type='CNAME', ttl=300)
change.add_value(cname)
log.debug("change: %s", change)
```

I think we need to add 'UPSERT' to https://github.com/spulec/moto/blob/master/moto/route53/responses.py#L57

It might also be a good idea to have an else at the end of that that raises an exception so invalid change types error as expected

**Comment by spulec** [comment]
Thanks for opening. This would be a great addition. Unfortunately, that is not a feature I currently use so it won't likely be high on my personal todo list. If someone else gets some time, a pull request would gladly be accepted.

**Comment by WyseNynja** [comment]
I'll work on a PR.

Does that place look like the right spot to add the support? Any other spots I missed?

**Comment by spulec** [comment]
Yes, I think that is the only spot

**Comment by codesplicer** [comment]
+1, just tried to do this too

**Comment by spulec** [comment]
Closed with #584

**Comment by romanek-adam** [comment]
When is it expect it to be released?

**Comment by spulec** [comment]
Version `0.4.24` is now out.
