### ISSUE TITLE
CloudWatchLog's put_subscription_filter() only accepts lambda destination ARNs

### ISSUE THREAD

**Issue by kbalk** [spulec/moto#4151]
The Log service API call [`put_subscription_filter`](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/logs.html#CloudWatchLogs.Client.put_subscription_filter) accepts a destination_arn that can be a kinesis stream, a logical destination (?), a kinesis firehose or a lambda.  The moto code assumes the destination ARN is a lambda ... period.

I have a destination ARN that's a kinesis firehose.  moto doesn't have a firehose backend, although localstack does.  moto does have a kinesis stream backend.

I might be willing to work on the code for this, but I could use some guidance.  If we're running localstack, is it possible to somehow use that as a backend for firehose?

**Comment by bblommers** [comment]
Hi @kbalk, I'm not aware of an (easy) way to use LocalStack instead of our backend.

The best way forward would probably be to make the Lambda-validation more strict:
https://github.com/spulec/moto/blob/master/moto/logs/models.py#L777
```
if destination_arn.split(":")[2] == "lambda":
    from moto.awslambda import lambda_backends  # due to circular dependency
    lambda_func = lambda_backends[self.region_name].get_function(destination_arn)

    # no specific permission check implemented
    if not lambda_func:
        raise InvalidParameterException(
                "Could not execute the lambda function. "
                "Make sure you have given CloudWatch Logs permission to execute your function."
        )
```

That way we:
 - Keep the existing validation
 - Support non-Lambda destination arns
 - Can add validation for Kinesis/Firehose, later down the line when we do support those services

**Comment by kbalk** [comment]
@bblommers I'll take a look at this.  There's another PR I think I want to work on before I work on this issue.  Thank you for your input and suggestion!

**Comment by kbalk** [comment]
@bblommers Would it be ok if I added firehose support?  I would try to support the same APIs that LocalStack does with the exception of not allowing ElasticSearch as a destination delivery stream (since moto doesn't support ElasticSearch).

**Comment by bblommers** [comment]
@kbalk Sounds good to me! I'm not too familiar with firehose and to what extend it's supported by LS, but all enhancements are welcome.

**Comment by kbalk** [comment]
#4246
