### ISSUE TITLE
ECRBackend delete_repository ignoring force argument

### ISSUE THREAD

**Issue by victor-mariano-leite** [spulec/moto#4155]
## Bug Description

Recently in issue #4128 has been made a improvement to the delete_repository method in the ECRBackend class (moto==2.2.1 >=), but when we try to delete a repository with images inside, the `force` execution flow has not been implemented, which has broken our test/CI pipelines this week raising:

```
botocore.errorfactory.RepositoryNotEmptyException: An error occurred (RepositoryNotEmptyException) when calling the DeleteRepository operation: The repository with name 'abc-job-dev' in registry with id '123456789012' cannot be deleted because it still contains images
```

When we run this mocked code:

```
ecr_client = boto3.client("ecr")
ecr_client.delete_repository(
   repositoryName=job.image,
   force=True,  # remove all repository images
)
```

Basically, the temporary solution has been to hardcode moto to 2.2.0.

**Comment by bblommers** [comment]
Thanks for raising this @victor-mariano-leite - will mark it as a bug.

**Comment by gruebel** [comment]
@bblommers you can assign me, will create a PR today
