### ISSUE TITLE
MotoServer: Cloudformation Update Stack should fail with 400 ValidationError instead of returning 200 success when using the same input

### ISSUE THREAD

**Issue by modamod** [spulec/moto#4157]
I am using motoserver to test a package I am building in golang,

During testing I noticed that the update stack action returns 200 success instead of throwing a 400 ValidationError when using the same template input.

Below is roughly the code in python along with the output I got from Motoserver and the expected output

Code
```python
import boto3
import time


client = boto3.Session(region_name="us-east-1").client("cloudformation", endpoint_url='http://localhost:5000')
paramters = [{
    "ParameterKey": "TopicName",
    "ParameterValue": "ParameterValue"
}]
template_body = open("fixtures/templates/valid_template.yaml").read()
stack_name = "TestStack"
# client.create_stack(StackName=stack_name, TemplateBody=template_body, Parameters=paramters)
# time.sleep(1)

# Should fail since I am updating the stack with the same paramters and template body
result = client.update_stack(StackName=stack_name, TemplateBody=template_body, Parameters=paramters)
print(result)
```

MotoServer Response
```
{'StackId': 'arn:aws:cloudformation:us-east-1:123456789:stack/TestStack/b8366e49-805b-416e-958d-8b21baa27ec1', 'ResponseMetadata': {'RequestId': 'b9b4b068-3a41-11e5-94eb-example', 'HTTPStatusCode': 200, 'HTTPHeaders': {'server': 'amazon.com', 'content-type': 'text/html; charset=utf-8', 'content-length': '347', 'access-control-allow-origin': '*', 'date': 'Mon, 09 Aug 2021 22:54:51 GMT'}, 'RetryAttempts': 0}}
```

AWS API Response
```
Traceback (most recent call last):
  File "C:\Users\extreme pc\git\modamod\ami-inspector\sample.py", line 12, in <module>
    client.create_stack(StackName=stack_name, TemplateBody=template_body, Parameters=paramters)
  File "C:\Users\extreme pc\venv\lib\site-packages\botocore\client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "C:\Users\extreme pc\venv\lib\site-packages\botocore\client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.AlreadyExistsException: An error occurred (AlreadyExistsException) when calling the CreateStack operation: Stack [TestStack] already exists
```

**Comment by bblommers** [comment]
Thanks for raising this and providing the expected exception, @modamod. Doesn't look like we're doing any validation in that area at the moment.

**Comment by teddylear** [comment]
@bblommers I can take a shot at this if that's alright. im assuming the approach should be to store CloudFormation stack names on creation and then throw the given error if one exists?

**Comment by bblommers** [comment]
Hi @teddylear, the bug appears when updating a stack without any changes. So we'll have to store the template on creation (if we do not already do that), and validate that the template is different when calling `update`. 

Not sure how AWS behaves if you try to call `update` with the same template but different parameters - you might have to do some testing around that.

PR's are always welcome!

**Comment by teddylear** [comment]
@bblommers Made first PR, please let me know if I'm missing anything or if there is anything I should change. Thanks!
