### ISSUE TITLE
Add support for 'block_device-map' on instance creation

### ISSUE THREAD

**Issue by garrickp** [spulec/moto#418]
Currently on instance creation, only a "ghost" default block map is added, even if the 'block_device_map' argument is provided to 'run_instances'.

It would be good to have this default block device added to the EBSBackend instance, and better to respect the 'block_device_map' argument (adding to the instance block_device_mapping, and adding to the EBSBackend volumes member) on instance creation.

**Comment by spulec** [comment]
Thanks for opening. This would be a great addition. Unfortunately, that is not a feature I currently use so it won't likely be high on my personal todo list. If someone else gets some time, a pull request would gladly be accepted.

**Comment by sf-mkirilov** [comment]
Hi @spulec, just before starting to work on this one I want to make sure that duplicate issue wasn't already solved. Can you please confirm?

**Comment by spulec** [comment]
@sf-mkirilov correct; it looks like this hasn't been implemented yet.
