### ISSUE TITLE
Stuck while installing requirements using `make init`

### ISSUE THREAD

**Issue by mhihasan** [spulec/moto#4190]
I am trying to install depedencies after cloning this repo using `make init`
It is waiting endlessly showing,
```bash
Collecting botocore>=1.12.201
  Using cached botocore-1.21.21-py3-none-any.whl (7.8 MB)
Collecting boto3>=1.9.201
  Using cached boto3-1.18.20-py3-none-any.whl (131 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking

```
What should I do?
Thanks

**Comment by bblommers** [comment]
Hi @mhihasan, that's an issue that popped up with the latest pip release - there's a incompatibility within our dependencies that is difficult to resolve.
Downgrading it to a known working version should fix the issue:
```
pip install pip==21.1.3
```

There is an outstanding issue raised with them, and they are working on a solution.

**Comment by mhihasan** [comment]
cool, it is working now. thanks

**Comment by bblommers** [comment]
FYI @mhihasan - I've just pushed a change so that Moto should now also work with the latest version of pip
