### ISSUE TITLE
Error while running tests

### ISSUE THREAD

**Issue by mhihasan** [spulec/moto#4193]
After cloning the repo, I have run `make init`, and then `make tests`.
5 of the s3 tests, which are in `test_s3/test_s3.py`, are failing due to `create_bucket` operation showin ,

```python
An error occurred (IllegalLocationConstraintException) when calling the CreateBucket operation: The unspecified location constraint is incompatible for the region specific endpoint this request was sent to.
```

Is there anything I am missing? Or should I fix this and create PR?

Thanks

**Comment by bblommers** [comment]
As far as I know, that occurs when the region for the default profile is set to anything other then 'us-east-1'.

It runs fine on our CI, so the tests themselves are OK - don't worry about that.

**Comment by mhihasan** [comment]
Do you mean profiles inside `~/.aws/credentials`? I have no default profile in this file, all are named profile.

**Comment by mhihasan** [comment]
And, why is this default system setting affecting the tests? Because, different persons might have different settings in their machine? Isn't it better to set those environment variable during test envrionment instead of getting it from system?

**Comment by bblommers** [comment]
> 
> 
> Isn't it better to set those environment variable during test envrionment instead of getting it from system?

Most of the tests explicitly specify the region in code (`s3 = boto3.client("s3", region_name=DEFAULT_REGION_NAME)`) - it's just those 5 that don't have a region specified, and nobody got around to adding them yet.
If you feel like fixing it, either as a separate PR or as part of the sagemaker PR, that would be appreciated!
