### ISSUE TITLE
Requests made using `httpx` package doesn't get intercepted by moto.

### ISSUE THREAD

**Issue by SiddChugh** [spulec/moto#4197]
Moto Version: 2.2.1

[Httpx](https://github.com/encode/httpx) Version: 0.18.2

```python
r = requests.post(url, data=data, files=files)
```

```python
r = httpx.post(url, data=data, files=files)
```

The post request using `requests` package is intercepted by `moto` package and the test passes. However, if we make the same request using `httpx` package, we get a `broken pipe` error. 

Is the `httpx` package not supported by `moto`?

**Comment by bblommers** [comment]
Hi @SiddChugh, we don't do anything with `httpx` - we don't use it internally, and we don't intercept any of its requests.

Do you have a reproducible test case for the `broken pipe` error? For a simple GET request, it seems to work fine:
```
@mock_sqs
@pytest.mark.network
def test_passthrough_requests():
    conn = boto3.client("sqs", region_name="us-west-1")
    conn.create_queue(QueueName="queue1")

    res = requests.get("https://httpbin.org/ip")
    assert res.status_code == 200

    r = httpx.get("https://httpbin.org/ip")
    print(r)
    print(r.text)
```
(Fine, meaning, it passes through as it's not supposed to be intercepted.)

**Comment by SiddChugh** [comment]
Thanks for the quick response. 
Sorry, I should have clarified. 
The problem exists when you send `files` over the network.
Try replacing 
```python
res = requests.get("https://httpbin.org/ip")
```
with 
```python
res = requests.get("https://httpbin.org/ip", files=files)
```
and 
```python
 r = httpx.get("https://httpbin.org/ip")
```
with 
```python
 r = httpx.get("https://httpbin.org/ip", files=files)
```
and see if the problem persists....

**Comment by bblommers** [comment]
That works as well, in a simple example:
```
@mock_sqs
def test_httpx():
    conn = boto3.client("sqs", region_name="us-west-1")
    conn.create_queue(QueueName="queue1")

    with open('test_utils.py', 'rb') as f:
        res = requests.get("https://httpbin.org/ip", files={'test.txt': f})
        print(res)
    with open('test_utils.py', 'rb') as f:
        res = httpx.post("https://httpbin.org/ip", files={'test.txt': f})
        print(res)
```

**Comment by bblommers** [comment]
Closing this, as there doesn't seem to be much we can do here.
