### ISSUE TITLE
Add support for Google Cloud Storage (boto.connect_gs)

### ISSUE THREAD

**Issue by rdodev** [spulec/moto#42]
First, really nice little mocking library you got going.

Second, it would be super nice if you could add support for mocking boto.connect_gs().

Thanks.

**Comment by dmlayton** [comment]
I would love to get this working, but figuring out how mock_s3 works. connect_s3 does not appear to be the entry point.

**Comment by terrycain** [comment]
Do we still need this?

**Comment by JackDanger** [comment]
Due to Boto3's lack of plans to support Google Cloud Storage I'm going to close this for now: https://github.com/boto/boto3/issues/579
