### ISSUE TITLE
 S3 .get(Range=...) doesn't return ETag

### ISSUE THREAD

**Issue by mdavis-xyz** [spulec/moto#4203]
# Summary

When specifying a `Range` parameter for an S3 `.get()`, the response doesn't include metadata like `ETag`.
(It works without the `Range` parameter.)

# Steps to reproduce

```
import boto3
from moto import mock_s3


with mock_s3():

    bucket = 'fake-bucket'
    key = 'my-file'

    boto3.client('s3').create_bucket(
        Bucket=bucket,
        CreateBucketConfiguration={
            'LocationConstraint': 'ap-southeast-2'
        },
    )

    obj = boto3.resource('s3').Object(bucket, key)

    obj.put(Body=b"1234")

    resp = obj.get()
    assert resp['ETag'] == obj.e_tag

    resp = obj.get(Range="bytes=0-1")
    assert resp['ETag'] == obj.e_tag

```

# Expected behavior

Response includes the following top-level keys:

* ResponseMetadata
* AcceptRanges
* LastModified
* ContentLength
* ETag
* ContentRange
* ContentType
* ServerSideEncryption
* Metadata
* Body

# actual behavior

Response includes the following top level keys:

* ResponseMetadata
* ContentLength
* ContentRange
* Metadata
* Body

So the final line in the script throws a KeyError.

```
Traceback (most recent call last):
  File "mwe.py", line 26, in <module>
    assert resp['ETag'] == obj.e_tag
KeyError: 'ETag'
```

# Installation

I `pip install`ed moto.

Python 3.8.10

boto                   2.49.0              
boto3                  1.18.26             
botocore               1.21.26             
moto                   2.2.3

**Comment by bblommers** [comment]
Thanks for raising this @mdavis-xyz - will mark it as an enhancement to return all attributes.

**Comment by ashtuchkin** [comment]
I see this issue as well.

For reference, we probably need to update function `_handle_range_header` in https://github.com/spulec/moto/blob/master/moto/s3/responses.py to start with `response_headers = headers`, so that all the other headers (including ETag) are passed through.

**Comment by vbarbaresi** [comment]
Good catch @ashtuchkin, it was as simple as that: just changing this variable name fixed the issue. I opened #4502
