### ISSUE TITLE
First request to moto server is slow

### ISSUE THREAD

**Issue by thrau** [spulec/moto#4207]
The moto server starts up instantly when running `python -m moto.server`, but the first request will take a long time. For example:

```
 % time awslocal --endpoint=http://localhost:5000 s3 ls
awslocal --endpoint=http://localhost:5000 s3 ls  0,40s user 0,09s system 6% cpu 7,764 total
```

This call to the `s3` service took 7.7 seconds. Subsequent calls are faster (about 450 ms on my machine)

This has to do with the way moto lazy-loads the backends and searches for a backend based on the host url.
Currently, moto will, in the worst case, import all moto backends on the first http request sent to the moto server because of this method: https://github.com/spulec/moto/blob/7acdfe4febbdfd97389fdbcd0e63fad6ae581903/moto/server.py#L57-L72
Here, `backends.search_backend` needs to import the backend using `_import_backend` to check whether the host matches the backend `url_bases` defined in `moto.<backend>.urls`.
In this case, the host will be `localhost`, so this part here: https://github.com/spulec/moto/blob/7acdfe4febbdfd97389fdbcd0e63fad6ae581903/moto/server.py#L147-L151
will import all backends in alphabetical order (including cloudformation, which alone takes about 2.5 seconds on my machine to import), just to find that there's no backend for the host "localhost".

As discussed with @bblommers, having a static index between the backends and the `url_bases` would be useful to further defer calls to importlib until the backend is actually needed.

**Comment by bblommers** [comment]
This should be fixed in 2.2.7 👍
