### ISSUE TITLE
removing inexisting permissions on lambda does not raise exceptions

### ISSUE THREAD

**Issue by Guriido** [spulec/moto#4227]
Hello,
I figured out that removing permissions that do not exist from lambdas does not raise any error in the mock environment.

Using the real environment, it raises a `botocore.errorfactory.ResourceNotFoundException`.

Is this a feature not developed yet?

```python
import boto3
from moto import mock_lambda

@mock_lambda
def test__remove_inexistant_permission():

    lambda_name = 'hoge'

    # creating here a dummy lambda
    # ...

	# removing permission that does not exist
    _ = boto3.client('lambda').remove_permission(
        FunctionName=lambda_name,
        StatementId="thisIDdoesNotExist"
    )
	
	# one more time just for sure...
	_ = boto3.client('lambda').remove_permission(
        FunctionName=lambda_name,
        StatementId="thisIDdoesNotExist00"
    )

    assert 1 == 2  # <- pytest fails here instead of higher

```

my environment:
```
>>> botocore.__version__
'1.21.24'
>>> moto.__version__
'2.0.11'
>>> boto3.__version__
'1.18.24'
>>> 
```

**Comment by Guriido** [comment]
Thank you for your answer @bblommers ! I am not familiar yet with moto source code, but I may be interested in creating a PR for adding this. 
Regarding the development policy of moto, would it be okay to implement the error handling for this case in particular?
(that is, are contributors expected to implement exhaustive parts of boto3 simulation, like in this case, all errors regarding lambda permissions etc)

**Comment by bblommers** [comment]
A PR would be always welcome, @Guriido! Contributors are not _expected_ to implement anything, but everything helps if it brings Moto closer to feature parity with AWS.

Some context that might be useful when implementing this:
Errors will always be simulated by raising one of Moto's custom exceptions, similar to this: https://github.com/spulec/moto/blob/master/moto/awslambda/models.py#L179
I do not know whether we can reuse any of our exceptions, or whether we have to define a new one - that will depend on the exact exception that AWS raises.

The unit test would look like this:
```
# setup with creating function..
...
# invoke remove_permission with invalid value
with pytest.raises(ClientError) as ex:
    remove_permission(..)
err = ex.value.response["Error"]
err["Code"].should.equal(..)
err["Message"].should.equal(..)
```

Let me know if there's anything else you need - happy to help out.
