### ISSUE TITLE
SQS:GetQueueAttributes failing when Optional AttributeNames param not passed

### ISSUE THREAD

**Issue by tkalus** [spulec/moto#4235]
In updating to `moto 2.2.5`, I surfaced an issue with moto's [`sqs.get_queue_attributes`](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sqs.html#SQS.Client.get_queue_attributes) where the mock was failing when the optional `AttributeNames` parameter was not passed.

Here's a brief test that passes with `2.2.4`, but fails with `2.2.5` -- testing in a `pyenv` managed Python 3.9.5 virtualenv on macOS.

`$ cat test_sqs.py`
```
"""Illustrate breakage of sqs:GetQueueAttributes()."""

import json
import os

import boto3
import pytest
from moto import mock_sqs


@pytest.fixture(scope="function")
def aws_credentials():
    """Mock AWS Credentials for moto."""
    os.environ["AWS_ACCESS_KEY_ID"] = "testing"
    os.environ["AWS_SECRET_ACCESS_KEY"] = "testing"
    os.environ["AWS_SECURITY_TOKEN"] = "testing"
    os.environ["AWS_SESSION_TOKEN"] = "testing"


@pytest.fixture(scope="function")
def sqs(aws_credentials):
    """Mock SQS CLient."""
    with mock_sqs():
        yield boto3.client("sqs", region_name="us-east-1")


@pytest.fixture(scope="function")
def sqs_queue(sqs):
    """Mock SQS Queue."""
    queue_url = sqs.create_queue(QueueName="test-queue")["QueueUrl"]

    yield {"QueueUrl": queue_url}

    # cleanup
    sqs.delete_queue(QueueUrl=queue_url)


def batch_send_sqs_events(queue_url, events):
    """Batch send a bunch of events on SQS."""
    sqs_resource = boto3.resource("sqs", region_name="us-east-1")
    sqs_queue = sqs_resource.Queue(queue_url)
    for event in events:
        sqs_queue.send_message(MessageBody=json.dumps(event))
    return len(events)


def test_get_queue_attributes_no_param(sqs, sqs_queue):
    """
    Illustrate breakage where Optional `AttributeNames` is NOT passed.
    
    Function: SQS:GetQueueAttributes
    """
    queue_url = sqs.get_queue_url(QueueName="test-queue")["QueueUrl"]
    input_event_count = 43
    events = [{"something": "test"} for x in range(input_event_count)]

    batch_send_sqs_events(queue_url, events)

    queue_attrs = sqs.get_queue_attributes(QueueUrl=queue_url)
    assert (
        int(queue_attrs["Attributes"]["ApproximateNumberOfMessages"])
        == input_event_count
    )


def test_get_queue_attributes_passed_param(sqs, sqs_queue):
    """
    Illustrate functioning where optional `AttributeNames` param is passed.

    Function: SQS:GetQueueAttributes
    """
    queue_url = sqs.get_queue_url(QueueName="test-queue")["QueueUrl"]
    input_event_count = 43
    events = [{"something": "test"} for x in range(input_event_count)]

    batch_send_sqs_events(queue_url, events)

    queue_attrs = sqs.get_queue_attributes(QueueUrl=queue_url, AttributeNames=["All"])
    assert (
        int(queue_attrs["Attributes"]["ApproximateNumberOfMessages"])
        == input_event_count
    )
```

Problem with commit e865362 where code appending the `"All"` string to `attribute_names` was removed.  Parent commit that appends `"All"` to `attribute_names` as default when param is empty appears to function properly:
https://github.com/spulec/moto/blob/21021a6a039dcd7430b45d91c3437ebd814fa845/moto/sqs/models.py#L638-L640

Both tests pass with `moto==2.2.4`. `test_get_queue_attributes_no_param` does not pass with `moto==2.2.5`.

Steps to repro:
```
$ ls
test_sqs.py
$ pip install pytest moto==2.2.4
$ pytest
# ... observe tests passing ...
$ pip install --upgrade moto==2.2.5
$ pytest
# ... observe tests failing ...
 ```

**Comment by bblommers** [comment]
Hi @tkalus, thanks for raising this, and welcome to Moto!
The `test_get_queue_attributes_no_param` does not pass against AWS either, I've just tested this - AWS does not return any attributes when omitting the AttributeNames-parameter.

Moto should not fail as it does, though, it should just return an empty response - so I'll mark it as a bug to fix this.

**Comment by tkalus** [comment]
Hey @bblommers, thanks for taking care of this -- and thanks for the pointer on the API change!
I tracked `AttributeNames` becoming a _semi_-required parameter for `sqs.get_queue_attributes()` on 2021-07-01 with `boto3 1.17.104` ([CHANGELOG](https://github.com/boto/boto3/blob/develop/CHANGELOG.rst#117104) and docs [before](https://boto3.amazonaws.com/v1/documentation/api/1.17.103/reference/services/sqs.html#SQS.Client.get_queue_attributes) and [after](https://boto3.amazonaws.com/v1/documentation/api/1.17.104/reference/services/sqs.html#SQS.Client.get_queue_attributes)).

🤔 might be why my code has been seeing some interesting -- errors -- with recent updates. 😂
