### ISSUE TITLE
AWS Pinpoint support

### ISSUE THREAD

**Issue by vekerdyb** [spulec/moto#4250]
The current version has no AWS Pinpoint support.

When I have time I will look into adding the basics, but meanwhile I wanted to open this ticket in case anybody else wanted to contribute :)

**Comment by bblommers** [comment]
Hi @vekerdyb, welcome to Moto!
A PR is always appreciated if you have time - let us know if you need any help.

**Comment by bblommers** [comment]
An initial implementation for Pinpoint will be part of Moto 3.0.7, and contains the following endpoints:

- create_app
- delete_app
- delete_event_stream
- get_app
- get_application_settings
- get_apps
- get_event_stream
- list_tags_for_resource
- put_event_stream
- tag_resource
- untag_resource
- update_application_settings

Please let us know in a new issue if there are any other features that you'd like to see.
