### ISSUE TITLE
Mock region

### ISSUE THREAD

**Issue by as1s** [spulec/moto#4252]
Can you allow mock regions in the mocks? 
I have this set
`os.environ['AWS_DEFAULT_REGION'] = 'any-region'`

and error it produces:
```
E       KeyError: 'any-region'
../../../.local/lib/python3.8/site-packages/moto/dynamodb2/responses.py:79: KeyError
```

**Comment by bblommers** [comment]
Hi @as1s! Technically it should be possible to support this. If you don't mind me asking - what's the reasoning behind having a non-existent region?

**Comment by as1s** [comment]
Extra level of protection so that tests do not write to the real environment.

**Comment by bblommers** [comment]
Ah, gotcha, that makes sense. The current implementation acts as a validation in itself, to verify that the specified region is correct/supported, and it would be good to keep that.

I'll mark it as an enhancement to implement it in a way that doesn't break this behaviour:

```
os.environ['MOTO_ALLOW_NONEXISTENT_REGION'] = True # defaults to False
os.environ['AWS_DEFAULT_REGION'] = 'any-region'
```

**Comment by as1s** [comment]
Also in your Pytest usage example it would be good to show set up of default region env var in the credentials fixture.
Often region in lambda code is not specified when creating client and uses default region.
I hope this makes sense.
