### ISSUE TITLE
Possible additions to CONTRIBUTING.md

### ISSUE THREAD

**Issue by kbalk** [spulec/moto#4275]
Some suggestions for `CONTRIBUTING.md` to help contributors to moto:

- Promote the use of TaggingService.
- Describe how to run in test server mode and the environment variable `TEST_SERVER_MODE`.  You can work it out by looking at the github workflow file, but it might be nice to spell out the steps.  It's useful to know if your tests fail in server mode.  Better yet, add a rule to the Makefile to invoke it.   
- Within a unit test - don't test an exception to indicate something is not yet implemented.  If an exception is raised that isn't defined in an `exceptions.py` file and a unit test attempts to check that scenario, the test will fail when run in server mode.  Mention the use of `SkipTest`.
- It would be nice to encourage the use of a "NotImplementedError" exception where it makes sense, but it's not something that can be tested in server mode and that lowers your test coverage a little bit.  Maybe a generic error that can be defined with an understanding of `TEST_SERVER_MODE`?
- Provide some general guidelines on how to organize tests - I see monolithic test files and sometime test functions that handle a lot of tests.  I'm used to writing one test per function, but to be consistent, I've been combining multiple tests per API.  It all works, but it would be nice to see test files that aren't so large and test functions that are smaller.
- When importing the backend from another service, declare the import within the block of code where it's needed and not at the top of the file.  I don't know if recent changes have negated that need to improve performance.

These are some of the gotchas I've discovered the hard way or learned though code review comments.

**Comment by bblommers** [comment]
Hey @kbalk, thanks for pointing this out - user feedback is always useful.

>
>  If an exception is raised that isn't defined in an exceptions.py file and a unit test attempts to check that scenario, the test will fail when run in server mode.

To turn this into a more general rule:
Always verify exceptions by using `with raises(botocore.exceptions.ClientError)` (or any of it's subclasses), to ensure the exception is thrown in the correct format.

>
> It would be nice to encourage the use of a "NotImplementedError" exception

There is definitely value in letting the user know that something is missing. If we're talking about a specific parameters that are not yet supported, I'd favour a non-intrusive way of letting them know though - maybe just logging a warning.
With a warning, the user might be able to work around unexpected results. With an exception, the user would have to change the parameters to get it to work, which is not possible if that call is part of the business logic.

Completely agree on everything else.
