### ISSUE TITLE
Batch job definitions do not capture tags

### ISSUE THREAD

**Issue by oakbramble** [spulec/moto#4284]
I am working with a lambda function which creates a job definition and then cleans up old definitions which have the same tags as the job definition it has just created.

When using moto 2.2.6 to test this, I have run into the issue that the moto job definition does not seem to capture the tags of the job definition. This is the structure of the job definition I get with moto, which does not include tags:

```
"jobDefinitions": [
        {
            "jobDefinitionName": "test_repo-latest",
            "jobDefinitionArn": "arn:aws:batch:eu-west-1:123456789012:job-definition/test_repo-latest:1",
            "revision": 1,
            "status": "ACTIVE",
            "type": "container",
            "parameters": {},
            "retryStrategy": {"attempts": 1},
            "containerProperties": {
                "image": "123456789012.dkr.ecr.eu-west-1.amazonaws.com/test_repo:latest",
                "vcpus": 1,
                "memory": 128,
                "command": ["ls"],
                "jobRoleArn": "arn:aws:iam::123456789012:role/test_customer-test_cloud-test_environment-user-iam-role",
                "volumes": [
                    {
                        "name": "efs",
                        "efsVolumeConfiguration": {
                            "fileSystemId": "fs-de240457",
                            "rootDirectory": "/",
                        },
                    }
                ],
                "environment": [],
                "mountPoints": [{"containerPath": "/efs", "sourceVolume": "efs"}],
                "privileged": False,
                "ulimits": [],
                "resourceRequirements": [],
                "secrets": [],
            },
        }
    ],
```
As opposed to the structure I get when I `describe_job_definitions` with boto3 1.18.36, seen [here](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/batch.html#Batch.Client.describe_job_definitions) in the docs, which includes `tags`, either populated with the given tags, or as an empty dict.

Assuming I haven't just misunderstood how this is working, I would propose adding tags to `JobDefinition`, in the same way that `parameters` is added [here](https://github.com/spulec/moto/blob/9859d66ff8fb7375fadf89fe976452d8c841459b/moto/batch/models.py#L182). If you think this change makes sense, I would be happy to work on it.

**Comment by bblommers** [comment]
Hi @oakbramble, thanks for raising this! That's definitely something that's still missing from Moto, so if you'd like to contribute, that would be very welcome.
Tags should be stored and retrieved using the centralized TaggingService-class - you can see an example usage of this here: https://github.com/spulec/moto/blob/master/moto/firehose/models.py#L245

Let me know whether that makes sense, or need anymore guidance.
