### ISSUE TITLE
Add SWF support

### ISSUE THREAD

**Issue by jbbarth** [spulec/moto#429]
I'd really like to see SWF support in moto, so I started hacking on the easiest endpoints here: https://github.com/botify-labs/moto/tree/feature/add-swf, with some implementation notes here: https://github.com/botify-labs/moto/wiki

I have a few questions before continuing:
- do you think it would be possible to include it in moto? or should I make a separate library?
- is there any kind of automatation to ease endpoint integration from boto docs or source code? not that it's a problem but if there's something...
- are there general guidelines for implementing errors? I saw some parts of moto use boto exceptions directly, while other reimplement their own ones
- if an integration upstream is possible, should I open a PR now as "WIP" for early comments? should I make separate incremental pull requests as I implement endpoints?

Thanks for any feedback and keep up the good work with moto ;-)

**Comment by spulec** [comment]
- Yes, I would love it.
- Nothing easy now, all manual :/
- We try not to use boto exceptions anymore. For a example of what we do now, see [here](https://github.com/spulec/moto/blob/master/moto/ec2/exceptions.py).
- If you want to open it now, feel free and I can try to give some early feedback.

Let me know if there is anything else I can do to help!

**Comment by spulec** [comment]
This was added with #451
