### ISSUE TITLE
How to handle API args with bools in nested dicts

### ISSUE THREAD

**Issue by kbalk** [spulec/moto#4290]
I was running one of our own Terraform tests that issued a Firehose CreateDeliveryStream() call.  Terraform used the value of "false" in two of the nested dicts, which causes the moto API logic to fail.

When I wrote the Firehose code I used `_get_param()` to read in each of the parameters.  I didn't read in each individual field of the dicts because that would be onerous and an issue when the API is updated.  My questions:

- Should I use a different BaseResponse method or is this an issue with `_get_param()`?
- How do I debug this, i.e. feed in a response that uses "false"?

```
{"DeliveryStreamName":"query-log-stream-P8V0BH6695TQ7HD",
 "DeliveryStreamType":"DirectPut",
 "ExtendedS3DestinationConfiguration":{
    "BucketARN":"arn:aws:s3:::tardigrade-route53-zone-azopjsrk",
    "BufferingHints":{"IntervalInSeconds":300,"SizeInMBs":5},
    "CompressionFormat":"UNCOMPRESSED",
    "DataFormatConversionConfiguration":{"Enabled":false},
    "EncryptionConfiguration":{"NoEncryptionConfig":"NoEncryption"},
    "Prefix":"AWSLogs/000000000000/route53querylogs/us-east-1/",
    "ProcessingConfiguration":{"Enabled":false,"Processors":[]},
    "RoleARN":"arn:aws:iam::000000000000:role/query-log-firehose-P8V0BH6695TQ7HD",
    "S3BackupMode":"Disabled"
 }
}
```

**Comment by kbalk** [comment]
I'm so sorry ... I should have read the error message more carefully ... it was an issue of using the wrong port.  My apologies.

**Comment by bblommers** [comment]
All good - happy to hear it's resolved :slightly_smiling_face: 

For future reference, in order to feed an exact response into Moto, you can make a direct URL request to our Flask server:
```
import moto.server as server
backend = server.create_backend_app("ec2")
test_client = backend.test_client()

res = test_client.post(
    "/?Action=CreateDeliveryStream",
    data="...",
)
```

Tests like this are usually located in `{service}/test_server.py`

**Comment by kbalk** [comment]
Another thing to add to the contributors readme document.  I will have a PR for firehose as the timestamps need to be in ISO format.  When I ran our Terraform script I also saw an error related to put_log_subscription() not finding the right state for the delivery stream.  I need to verify that's the case and not something else.
