### ISSUE TITLE
False positive: AMI ID missing warning when using a LaunchTemplate

### ISSUE THREAD

**Issue by jonapich** [spulec/moto#4298]
I am using an AMI LaunchTemplate that contains an AMI ID from the `ec2_backend.describe_images()` helper:

```
for ami in ec2_backend.describe_images():
    if ami.description.startswith("Canonical, Ubuntu, 16.04 LTS") and ami.architecture == "x86_64":
        break

ec2_client = boto3.client("ec2")
ec2_resource = boto3.resource("ec2")

template = ec2_client.create_launch_template(
    LaunchTemplateName="test",
    LaunchTemplateData=dict(ImageId=ami.id, InstanceType="m3.medium"),
)["LaunchTemplate"]

instances = ec2_resource.create_instances(
    LaunchTemplate=template,
    MaxCount=1,
    MinCount=1
)
```

Here, the "create_instances" call will trigger a warning about the `Image Id` being None:

```
PendingDeprecationWarning: Could not find AMI with image-id:None, in the near future this will cause an error.
```

Expected result: Moto should not complain since the AMI ID in the template matches the one in the "ec2_backend".

**Comment by jonapich** [comment]
After some tracing I can see that [this piece of code](https://github.com/spulec/moto/blob/45b2684eb6024d2b2bfa901afe651d565b25767b/moto/ec2/responses/instances.py#L48) seems to only care about the `ImageId` param passed to the `create_instances` call, and doesn't try to see if the template specifies one as well.

However, the ami id is not in the template definition argument. So the code would have to pull the template using its template id and check the AMI ID there; I'm not sure how to do that, but with some guidance I can probably do a PR.

**Comment by bblommers** [comment]
Hi @jonapich, thanks for raising this! A PR would be very welcome if you want to fix this.

From what I can tell, this would be the best way of approaching this:

1. Retrieve the `LaunchTemplate`-parameter here: https://github.com/spulec/moto/blob/45b2684eb6024d2b2bfa901afe651d565b25767b/moto/ec2/responses/instances.py#L48 (either using `self._get_param(..)` or `self._get_dict_param(..)`, depending on the format if the input)
2. Pass the launch template into `add_instances` (https://github.com/spulec/moto/blob/45b2684eb6024d2b2bfa901afe651d565b25767b/moto/ec2/models.py), and into the `Instance`-class (https://github.com/spulec/moto/blob/45b2684eb6024d2b2bfa901afe651d565b25767b/moto/ec2/models.py#L511)
3. In the Instance-constructor, it should be possible to then retrieve the necessary AMI from the launch template:
```
self.launch_template_args = kwargs.get("launch_template")
self.launch_template = self.ec2_backend.get_launch_template(template_id=self.launch_template_args[".."])
if not self.image_id:
  self.image_id = self.launch_template.get("ImageId")
```
Note: this is partial pseudocode, just to give an idea - hopefully it's enough to get you started. Let me know if you have any other questions, I'd be happy to dive a little deeper into this.
