### ISSUE TITLE
Getting objects with Storage Class = Glacier successfully

### ISSUE THREAD

**Issue by btruong66** [spulec/moto#4299]
Hello,

I'm writing a test case to check if a functionality restoring an object from glacier works successfully or not.

However, getting an object with StorageClass='GLACIER' works successfully despite expectations of  returning an InvalidObjectStateError error as per documentation:
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Client.get_object

 
```
mock_s3_client.put_object(Bucket="bucket", Key="test.txt", Body="contents", StorageClass='GLACIER')
    response_get = mocked_s3_client.get_object(Bucket='bucket', Key='test.txt')
```

**Comment by bblommers** [comment]
Hi @btruong66, welcome to Moto, and thanks for raising this!
I'll mark this as an enhancement to implement this validation.
