### ISSUE TITLE
kms.create_key response is missing description, when not specified

### ISSUE THREAD

**Issue by rtoma** [spulec/moto#4304]
Hi,

Thanks for developing moto!

I am using version 2.2.6.  Working on adding tests to code that does:

```
        key_metadata = client.create_key(KeyUsage=key_usage,
                                         CustomerMasterKeySpec=customer_master_key_spec,
                                         Origin=origin)['KeyMetadata']
```

As you see, no description is given.

I expect the metadata to contain the `Description` field as to an empty string.

Actual behaviour: the dict does not contain the `Description` field.

--

I believe this is a bug. Quoting the boto3 `kms.create_key` parameter docs :

(tldr; default value is an empty string.)

> Description (string) --
A description of the KMS key.
Use a description that helps you decide whether the KMS key is appropriate for a task. The default value is an empty string (no description).

Same doc section says the response will contain the field:

```
{
    'KeyMetadata': {
        .....
        'Description': 'string',
        .....
```

--

Obviously, the workaround is to pass `Description=''`, but I assume moto is supposed to work without requiring code changed to code-under-test.

Thanks, again

**Comment by bblommers** [comment]
Thanks for raising this @rtoma! Will mark it as a bug
