### ISSUE TITLE
SES coverage status documentation

### ISSUE THREAD

**Issue by mdavis-xyz** [spulec/moto#4310]
The top-level README of this project says:

| Service Name              | Decorator             | Development Status              | Comment                     |
|---------------------------|-----------------------|---------------------------------|-----------------------------|
| SES                       | @mock_ses             | all endpoints done              |                             |

But the [implementation coverage page](https://github.com/spulec/moto/blob/master/IMPLEMENTATION_COVERAGE.md) says:

> ses
> 25% implemented

And lists many  endpoints not implemented.

So is that a typo on the top-level README? Should it instead say 'core endpoints done', not 'all endpoints done'?

**Comment by bblommers** [comment]
> Should it instead say 'core endpoints done', not 'all endpoints done'?

Yes, it should @mdavis-xyz - thanks for bringing this to our attention :+1:
