### ISSUE TITLE
ListUserTags output is incorrect

### ISSUE THREAD

**Issue by farrellit** [spulec/moto#4341]
ListUserTags should have a result `member` under `Tags`, currently there is `item` instead.

https://docs.aws.amazon.com/IAM/latest/APIReference/API_ListUserTags.html

Discovered while using localstack with Go SDK.   Expected the SDK to successfully list user tags, but since output doesn't match the spec, it doesn't find the tags in the response. 

Installed moto via docker localstack.

**Comment by bblommers** [comment]
Thanks for raising this @farrellit - the Python SDK is a bit more forgiving with the exact XML format, that's why we don't tend to notice mistakes like this.
