### ISSUE TITLE
Are you Hacktoberfest-ing?

### ISSUE THREAD

**Issue by shakram02** [spulec/moto#4374]
Any plans to make this repo [Hacktoberfest](https://hacktoberfest.digitalocean.com/resources/maintainers)-able?

**Comment by nom3ad** [comment]
@bblommers  I could see many of the issues labelled as `hacktoberfest-accepted`. 

But https://hacktoberfest.digitalocean.com/faq says that only PRs are counted as valid contributions
```
Do issues/commits count?	|  No, only pull requests count.
```
Or those issues are just labelled for any potential contributions?

**Comment by bblommers** [comment]
Looks like this is the end of another Hacktoberfest. There was a noticable uptick in contributions this month, with plenty of bug fixes and enhancements being added to Moto. 

Thank you to everyone who contributed! :tada:
