### ISSUE TITLE
Reopen https://github.com/spulec/moto/pull/3908 (idna version based on Python version)

### ISSUE THREAD

**Issue by aetracht** [spulec/moto#4394]
That PR was closed because `requests` had a similar limitation of the `idna` version.  However, that appears to no longer be the case:

https://github.com/psf/requests/blob/main/setup.py#L46-L47 (from [July 7](https://github.com/psf/requests/commit/33cf965f7271ab4978ed551754db37865c4085db))

So, it now makes sense to update the moto setup.py to choose the version of idna based on the Python version.

See my comment https://github.com/spulec/moto/pull/3908/commits/ae4d20610227b46590ad248535c021208b2bfaed#r726688476

**Comment by bblommers** [comment]
Hi @aetracht, Moto no longer supports Python 2, so we don't have to worry about that anymore.

I'll leave this open as a reminder to up the max version though - we only allow `idna<3`, and it looks like `requests` now allows `idna<4`
