### ISSUE TITLE
head_object response should always contain ContentType

### ISSUE THREAD

**Issue by ExplodingCabbage** [spulec/moto#4416]
When using boto3 for real, the return value of a `head_object` call *always* contains a `ContentType` key, at least as far as I can tell. Even if you upload a completely empty file without specifying a content type and then call `head_object`, its `ContentType` will have been populated with `binary/octet-stream`.

However, in `moto`, this key is not guaranteed to be present. For example, if you run:

```
import moto
import boto3
from io import BytesIO

with moto.mock_s3():
    s3_resource = boto3.resource("s3", region_name="us-east-1")
    s3_resource.create_bucket(Bucket="testbucket")
    s3_resource.Bucket("testbucket").upload_fileobj(
        BytesIO(b'foobar'), Key="testobject"
    )
    s3_client = boto3.client("s3", region_name="us-east-1")
    print(
        "metadata:",
        s3_client.head_object(
            Bucket="testbucket",
            Key="testobject",
        ),
    )
```

then the dict that gets printed will not contain a `ContentType` key at all.

This leads to `KeyError`s when testing code that assumes the `ContentType` key will be present and reads it unconditionally (which is a safe assumption with the real boto3 implementation!).

It'd be helpful to ensure this value is always set, even if just to a hard-coded default value like `binary/octet-stream`.

**Comment by bblommers** [comment]
Hi @ExplodingCabbage, welcome to Moto, and thanks for raising this! Good point - will mark it as an enhancement to always return this attribute.
