### ISSUE TITLE
paginate decorator requiring parameters that are not required

### ISSUE THREAD

**Issue by kbalk** [spulec/moto#4446]
Note:  What I'm trying to do is internal to moto and not a typical scenario, so it's a low priority issue.

I have the following code that I was planning to use in a new Route53 API implementation:

```
        from moto.logs import logs_backends  # pylint: disable=import-outside-toplevel
        response = logs_backends[region].describe_log_groups()
```

This code snippet results in a pagination_wrapper() error:

```
        ....
        paginator = Paginator(
            max_results=limit,
            max_results_default=pagination_config.get("limit_default"),
            starting_token=input_token,
            page_ending_range_keys=pagination_config.get("page_ending_range_keys"),
            param_values_to_check=kwargs,
            fail_on_invalid_token=fail_on_invalid_token,
        )
>       results = func(*args, **kwargs)
E       TypeError: describe_log_groups() missing 1 required positional argument: 'log_group_name_prefix'
```

`log_group_name_prefix` is not a required argument.  The same call to `describe_log_groups()` invoked as an API call works fine and does not require the `log_group_name_prefix` argument.

I think the API call `describe_log_groups()` should set a default value of `None` to `log_group_name_prefix`.  If this is acceptable, I can make this change with the code changes I'm making now.

**Comment by bblommers** [comment]
Makes sense @kbalk
