### ISSUE TITLE
mock_ec2 instance launch_time timestamp format does not match boto instance launch_time format

### ISSUE THREAD

**Issue by codesplicer** [spulec/moto#445]
When using boto 2.38.0 and moto 0.4.15 I get the following:

```
In [1]: print real_inst.launch_time
Out[1]: u'2015-10-29T07:31:44.000Z'
```
But when doing the same with a moto mocked ec2 instance:
```
In [2] print mock_inst.launch_time
Out[2]: u'2015-10-29T12:22:24Z'
```

It appears the moto mock instance is missing millisecond precision from its time format.

**Comment by spulec** [comment]
thanks!
