### ISSUE TITLE
Document whether moto is concurrency safe or not

### ISSUE THREAD

**Issue by mdavis-xyz** [spulec/moto#4471]
I'm trying to test some code which does multiprocessing. I'm getting unexpected results, and I suspect that moto might not support multiprocessing.

```
from multiprocessing import Process

from moto import mock_s3
import boto3

with mock_s3():
    bucket = 'mybucket'
    key = 'mykey'
    client = boto3.client('s3')
    boto3.client('s3').create_bucket(
        Bucket=bucket,
        CreateBucketConfiguration={
            'LocationConstraint': 'ap-southeast-2'
        },
    )
    
    # upload object in another process
    data = b"abc"
    
    def upload(data):
        client = boto3.client('s3')
        client.put_object(
            Bucket=bucket,
            Key=key,
            data=data
        )
    proc = Process(target=upload, args=(data,))
    proc.start()
    proc.join()
    
    resp = boto3.client('s3').get_object(
            Bucket=bucket,
            Key=key
        )
    assert resp['Body'].read() == data
```

If I spawn a new process and create a resource in moto, will the parent process be able to find that resource? In the example above, it can't.

I understand that implementing this is super hard to do. The purpose of this ticket is just to ask that you clarify in the documentation whether or not moto supports testing of code which uses multiprocessing or multi-threading.

Note that the [boto3 documentation](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/clients.html#multithreading-or-multiprocessing-with-clients) says that there are some gotchas. You have to instantiate the client new within each thread/process, and not share it between them. I'm not sure whether that constraint affects moto or not.

**Comment by bblommers** [comment]
Moto stores the state in a global variable, and TIL that global state is not shared between processes. 
Rather, when a new process is started, it copies the existing global state (that's why the bucket still exists), but it is completely separate from then onwards. See https://stackoverflow.com/a/18779028

**Comment by bblommers** [comment]
Follow-up to this: the above code does work when using threads:
```
thread = threading.Thread(target=upload, args=(data,))
thread.start()
thread.join()
```

Nevertheless, Moto was not designed to support concurrent access, so if it does work it's accidental. :slightly_smiling_face: 
This has been added to the docs now, in the FAQ section. I'll close this, but let me know if you have anymore questions.
