### ISSUE TITLE
dynamodb2 Item.partial_save() always causes KeyError: 'UpdateExpression'

### ISSUE THREAD

**Issue by jonathanq** [spulec/moto#449]
When calling partial_save on an Item, I always get a KeyError: 'UpdateExpression'

It seems in dynamodb2/responses.py - update_item() method, it expects that "UpdateExpression" exists on the body: https://github.com/spulec/moto/blob/master/moto/dynamodb2/responses.py#L376 - so it throws a KeyError every time.

The Item.partial_save() call from boto dynamodb2 (tested with 2.38.0) - does not set "UpdateExpression", but it does set "Expected": https://github.com/boto/boto/blob/develop/boto/dynamodb2/items.py#L410

Deep in update_item in boto layer1.py - UpdateExpression is an optional value: https://github.com/boto/boto/blob/develop/boto/dynamodb2/layer1.py#L2756

The body of the request from boto 2.38.0 is:
```
{
  'Expected': {
    'time_modified': {
      'Exists': True, 
      'Value': {
        'S': '2013-07-04T19:59:24.627485'
        }
    }, 
    'value': {
      'Exists': True, 
      'Value': {
        'SS': [
          'somevalue 
          'someothervalue'
        ]
      }
    }
  }, 
  'AttributeUpdates': {
    'time_modified': {
      'Action': 'PUT', 
      'Value': {
        'S': '2015-11-05T00:35:14.374159'
      }
    }, 
    'value': {
      'Action': 'PUT', 
      'Value': {
        'SS': [
          'somenewvalue'
        ]
      }
    }
  }, 
  'TableName': 'test-table', 
  'Key': {
    'id': {
      'S': '1234'
    }
  }
}
```
The querystring that created that body was:
```
{u'{"Expected": {"value": {"Value": {"SS": ["somevalue", "someothervalue"]}, "Exists": true}, "time_modified": {"Value": {"S": "2013-07-04T19:59:24.627485"}, "Exists": true}}, "AttributeUpdates": {"value": {"Action": "PUT", "Value": {"SS": ["somenewvalue"]}}, "time_modified": {"Action": "PUT", "Value": {"S": "2015-11-05T00:35:14.374159"}}}, "TableName": "test-table", "Key": {"id": {"S": "1234"}}}': [u'']}
```

**Comment by spulec** [comment]
Thanks for opening this.

I've added some basic support AttributeUpdates. Feel free to reopen if more is needed.

**Comment by jonathanq** [comment]
I was trying out the fix, I modified my local version of moto/dynamodb2/models.py - update_with_attribute_updates in order to let Sets work (which was the original problem I was having)

```
    def update_with_attribute_updates(self, attribute_updates):
        for attribute_name, update_action in attribute_updates.items():
            action = update_action['Action']
            new_value = list(update_action['Value'].values())[0]
            if action == 'PUT':
                # TODO deal with other types
                if isinstance(new_value, list) or isinstance(new_value, set):
                    self.attrs[attribute_name] = DynamoType({"SS": new_value})
                else:
                    self.attrs[attribute_name] = DynamoType({"S": new_value})
```

There may be a better way of checking for the types. And this really only helps with StringSets in Dynamo.

**Comment by spulec** [comment]
Added with https://github.com/spulec/moto/commit/4aa14960d2e8fee2acd714a33ede0bddac163c57
