### ISSUE TITLE
batch job definitions do not support setting vcpus or memory in resource requirements

### ISSUE THREAD

**Issue by richford** [spulec/moto#4505]
Batch job definition memory and vCPU requirements can now be specified under the `resourceRequirements` key of the `containerProperties` dict. (See [here](https://docs.aws.amazon.com/batch/latest/userguide/job_definition_parameters.html#ContainerProperties-resourceRequirements) for details). Apparently, the [memory](https://docs.aws.amazon.com/batch/latest/userguide/job_definition_parameters.html#ContainerProperties-memory) and [vcpus](https://docs.aws.amazon.com/batch/latest/userguide/job_definition_parameters.html#ContainerProperties-vcpus) parameters at the top level of the `containerProperties` are now deprecated.

When I create a job definition, moto will not let me specify the memory using the resource requirements parameter.

## How to reproduce
To reproduce, use the following MWE python code:
```python
import boto3
from moto import mock_batch

@mock_batch
def test_jobdef():
    client = boto3.client("batch")
    response = client.register_job_definition(
        jobDefinitionName="testmwe",
        type="container",
        containerProperties={
            "image": "ubuntu",
            "resourceRequirements": [
                {
                    "value": "33",
                    "type": "MEMORY"
                },
                {
                    "value": "7",
                    "type": "VCPU"
                },
            ],
        }
    )

    response = client.describe_job_definitions(
        jobDefinitionName="testmwe",
    )

    print(response.get("jobDefinitions")[0])
```

## Expected behavior
Print the job definition with container properties matching the ones we created above.

## What actually happens
The full traceback I get is:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/richford/projects/oss_third_party/moto/moto/core/models.py", line 113, in wrapper
    result = func(*args, **kwargs)
  File "/Users/richford/projects/oss_third_party/moto/mwe.py", line 7, in test_jobdef
    response = client.register_job_definition(
  File "/Users/richford/miniconda3/envs/moto-dev/lib/python3.8/site-packages/botocore/client.py", line 388, in _api_call
    return self._make_apixconda3/envs/moto-dev/lib/python3.8/site-packages/botocore/client.py", line 708, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ClientException: An error occurred (ClientException) when calling the RegisterJobDefinition operation: containerProperties must contain memory
```

## What version of moto am I using
I installed the latest from GitHub with `pip install -e .` and `make init`. The command `pip list | grep oto` yields
```
boto                          2.49.0
boto3                         1.19.6
botocore                      1.22.6
moto                          2.2.12.dev0
```

## How it might be fixed
I believe this can be fixed entirely within `moto/batch/models.py` and associated tests. I will submit a PR to that effect.

**Comment by bblommers** [comment]
Hi @richford, thanks for raising this!

How does AWS behave when specifying the oldstyle `"memory": 512` - does it throw a warning? Ideally we replicate that behaviour as well

**Comment by richford** [comment]
@bblommers, good point. I see no warning when I use the old style using, which is weird considering the documentation.
