### ISSUE TITLE
Can't perform GET/PUT operations against server from inside docker container

### ISSUE THREAD

**Issue by eschkufz** [spulec/moto#4521]
Minimal Reproducible Example:

Run a moto server
```
python3 -m moto.server -p5001
```
Verify that the server is accepting requests
```
$ curl localhost:5001
# Prints: 
# bcaf1ffd86f41161ca5fb16fd081034fwebfile
```
Now try connecting to the server from inside a docker container:
```
$ curl host.docker.internal:5001
# Prints:
# <?xml version="1.0" encoding="UTF-8"?>
# <Error>
#   <Code>NoSuchBucket</Code>
#    <Message>The specified bucket does not exist</Message>
#    <BucketName>host</BucketName>
#    <RequestID>7a62c49f-347e-4fc4-9331-6e8eEXAMPLE</RequestID>
# </Error># curl host.docker.internal:5001
```

Why `host.docker.internal` instead of `localhost`?

Inside of a docker container, `localhost` points to a privately visible URL. Docker provides a special hostname `host.docker.internal` which maps to `localhost` on the machine which is running the container. `curl host.docker.internal:5001` escapes the container its running in and connects to the moto server running on the machine which is also running the container. 

What's going on?

`subdomain_based_buckets` has special cases for connection requests from `localhost` (as well as a few other cases such as `localstack` --- see https://bitbucket.org/atlassian/localstack/issues/8/creating-s3-bucket-using-aws-cli-from). There's no special case for `host.docker.internal` so the mock assumes that it refers to bucket name.

What's the solution?

Add a new case below line 198 of `moto/s3/responses.py`:
```
        if (
            not host
            or host.startswith("localhost")
            or host.startswith("localstack")
            or host.startswith("host.docker.internal")
            or re.match(r"^[^.]+$", host)
            or re.match(r"^.*\.svc\.cluster\.local:?\d*$", host)
        ):
```

**Comment by eschkufz** [comment]
See PR #4522 for fix.

**Comment by bblommers** [comment]
Thanks for raising this and providing the MWE @eschkufz :+1:
