### ISSUE TITLE
Delete Markers unsupported?

### ISSUE THREAD

**Issue by muad-dweeb** [spulec/moto#455]
It seems that deleting an object in Mock S3 also deletes its version list instead of appending a delete marker. Is this intentional?

**Comment by spulec** [comment]
Nope, it just hasn't been implemented yet.

**Comment by muad-dweeb** [comment]
Would you be interested in a Pull Request for this feature? My team needs the functionality for testing. 
@adamfeuer @hollylemos

**Comment by spulec** [comment]
Absolutely

**Comment by spulec** [comment]
Added with https://github.com/spulec/moto/commit/9a861a367d777865465bd7b92820c0ca4de245ff
