### ISSUE TITLE
Intermittent issues accessing moto server via Spark/Java

### ISSUE THREAD

**Issue by jbvsmo** [spulec/moto#4564]
I have implemented a unit test suite for Pyspark jobs where it stores data on mocked s3 with moto server.

The issue is that one or two out of 30 tests fails randomly always with this error message:

```
com.amazonaws.AmazonClientException: Unable to unmarshall error response (White spaces are required between publicId and systemId.). Response Code: 500, Response Text: INTERNAL SERVER ERROR
```

The setup is complex, but in short, I have a `python -m moto.server -p 5000` process running and spark is configured to use `http://localhost:5000` as the URL. The python code also accesses this same server using the `moto.settings.TEST_SERVER_MODE = True` hack.

As you can see above, the error comes from the Amazon SDK for Java that Spark is using internally and it points to moto server returning HTTP error 500. That is the traceback I get from the moto server

```python
127.0.0.1 - - [11/Nov/2021 16:39:48] "GET /fake-bucket-s3-moto/?max-keys=5000&prefix=normalized-data%2Fspecifications%2Fregions%2F.spark-staging-8c30316e-0fff-4349-9a69-4334721a0df5%2F HTTP/1.1" 200 -
Unable to find appropriate backend for MM.9dQpfH5c.amazonaws.com.Remember to add the URL to urls.py, and run script/update_backend_index.py to index it.
127.0.0.1 - - [11/Nov/2021 16:39:48] "POST /fake-bucket-s3-moto/?delete HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 319, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 308, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib/python3.7/site-packages/moto/server.py", line 188, in __call__
    backend_app = self.get_application(environ)
  File "/usr/local/lib/python3.7/site-packages/moto/server.py", line 163, in get_application
    app = self.create_app(backend)
  File "/usr/local/lib/python3.7/site-packages/moto/server.py", line 236, in create_backend_app
    backend = list(backends.get_backend(service).values())[0]
  File "/usr/local/lib/python3.7/site-packages/moto/backends.py", line 49, in get_backend
    module_name, backends_name = BACKENDS[name]
KeyError: None
[Fatal Error] :1:55: White spaces are required between publicId and systemId.
21/11/11 16:39:48 ERROR FileFormatWriter: Aborting job 8144745e-3da8-423b-aecf-dd4db8000704.
```

I cannot give a minimal program that reproduces the error because it will happen in different places and sometimes the full test suite runs without a hiccup. I don't think it is likely the Amazon client for Java to be sending the wrong data, but it always seems to happen in this "POST delete" 

Python 3.7
Moto 2.2.13

**Comment by bblommers** [comment]
Hi @jbvsmo! 
What does `MM.9dQpfH5c.amazonaws.com` refer to - is that a randomly generated bucket name? 
Both Moto and AWS are a bit picky with bucket names, so I wonder if the random failures are related to buckets that contain upper case chars/dots in the name.

**Comment by jbvsmo** [comment]
I have zero idea what that means. Seems like it is misinterpreting some other field.

The bucket is called `fake-bucket-s3-moto` as you can see on the 1st request above the error.

What can I enable to get more meaningful information on the request?

**Comment by bblommers** [comment]
There is no real logging within MotoServer, unfortunately. If the Java SDK sends all these requests, it's probably easiest to use their logs to see what kind of requests are send: 
https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-logging.html (Specifically the `Verbose Wire Logging` section)

Does it always happen with the same test?
Or rather, can you reproduce it while only running a single test?

If you want to dump the logs, I'd be happy to look into it, but the smaller the log file, the easier it will be to find something obviously.

**Note: Make sure there is no personal information in the logs, as debug-logs will print everything**

**Comment by bblommers** [comment]
With the lack of response, I'm going to assume, this is either fixed or unreproducible. I'll close this - do let us know if there is still an issue here though, happy to reopen.
