### ISSUE TITLE
No module named 'yaml' in tag 2.2.14(moto/cloudformation)

### ISSUE THREAD

**Issue by yaronbenezra** [spulec/moto#4570]
Hi,

Can you please help?,

/python3.8/site-packages/moto/cloudformation/models.py:3: in <module>
    import yaml
E   ModuleNotFoundError: No module named 'yaml'

Note:
downgrade to Tag  2.2.13 bug does not exist

Regards,
Yaron

**Comment by bblommers** [comment]
Thanks for raising this @yaronbenezra. How are you installing Moto?

Can you show the full stacktrace?

**Comment by yaronbenezra** [comment]
Hi 
Thanks for the quick replay
i have this in the pipfile:
moto = {extras = ["all"],version = "*"}
Regards,
Yaron

**Comment by bblommers** [comment]
That is a bug indeed - and somehow that slipped through all our tests.

Having said that, it should be fixed as of moto>=2.2.15. Can you confirm that version works for you @yaronbenezra?

**Comment by yaronbenezra** [comment]
All is ok now, Thanks!
