### ISSUE TITLE
@mock_cognitoidp  @mock_cognitoidentity stop working from version 2.2.13

### ISSUE THREAD

**Issue by yaronbenezra** [spulec/moto#4578]
Hi Hope you can help

Those mock fail to work from version 2.2.13
    @mock_cognitoidp
    @mock_cognitoidentity

whats append is that we call the real Cognito service 

Best Regards,
Yaron

**Comment by bblommers** [comment]
Hi @yaronbenezra, do you have a reproducible test case for this, by any chance?

**Comment by yaronbenezra** [comment]
yes i can test with a fix if you have to see if all work

**Comment by yaronbenezra** [comment]
i found the issue can you fix :
working version 2.2.12
  def get_id(self):
        identity_id = {"IdentityId": get_random_identity_id(self.region)}
        return json.dumps(identity_id)

fail version 2.2.13

 def get_id(self, identity_pool_id: str):
        identity_id = {"IdentityId": get_random_identity_id(self.region)}
        self.pools_identities[identity_pool_id]["Identities"].append(identity_id) --> this in my case is empty dict {}
        return json.dumps(identity_id)

in the int you are setting:
class CognitoIdentityBackend(BaseBackend):
    def __init__(self, region):
        super(CognitoIdentityBackend, self).__init__()
        self.region = region
        self.identity_pools = OrderedDict()
        self.pools_identities = {}

if your test is like this 👍 
@mock_cognitoidentity
@mock_cognitoidp
def test_yaron():
    cognito_identity = boto3.client('cognito-identity', config=Config(retries={'mode': 'standard'}))
    identity_id_response = cognito_identity.get_id(
        IdentityPoolId="yaron",
        Logins={
            f'cognito-idp.dafsdf.amazonaws.com/yaron': "Sdgfsdg"
        }
    )
    assert identity_id_response


you will fail

**Comment by bblommers** [comment]
Hi @yaronbenezra, as far as I can tell, your code is supposed to fail, because the `IdentityPoolId` does not exist?
Moto should validate this, and throw a proper exception, but it should never work with the code provided.

This code does work:
```
@mock_cognitoidentity
@mock_cognitoidp
def test_yaron():
    cognito_identity = boto3.client('cognito-identity')
    # Create IdentityPool first
    identity_pool_data = cognito_identity.create_identity_pool(
        IdentityPoolName="test_identity_pool", AllowUnauthenticatedIdentities=True
    )

    identity_id_response = cognito_identity.get_id(
        IdentityPoolId=identity_pool_data["IdentityPoolId"],
        Logins={
            f'cognito-idp.dafsdf.amazonaws.com/yaron': "Sdgfsdg"
        }
    )
```

**Comment by yaronbenezra** [comment]
Thanks! 
I understand what you are saying and I will fix the test code.
Note:
I copy here just a snip from the test, the test call to a real lambda that read existing pool id (so there we didn't create the pool it already existed)and in the past, it just gets this  {"IdentityId": get_random_identity_id(self.region)} and the test continues to the real purpose 

Thanks for the quick replay 
Yaron

**Comment by yaronbenezra** [comment]
bblommers thanks for your help!
