### ISSUE TITLE
DynamoDB ConditionExpression emulation does not support special characters in item attribute names

### ISSUE THREAD

**Issue by BrandonLWhite** [spulec/moto#4580]
The `dynamodb2.comparisons.ConditionExpressionParser._lex_one_node` does not match on attribute names that contain special characters such as `$` and instead raises a `ValueError` exception. 

DynamoDB does support special characters in attribute names.  In our application we have some names that start with dollar signs.  I imagine there are several other printable special symbols/characters that are legal too.

I think that `attribute_regex = r"(:|#)?[A-z0-9\-_]+"` should be updated to permit `$` and other printable special chars.

Version:
`moto==2.2.12`

**Comment by bblommers** [comment]
Thanks for raising this @BrandonLWhite - will mark it as a bug to support special chars here :+1:

**Comment by bblommers** [comment]
Hi @BrandonLWhite, do you have a test case that you can share that demonstrates this issue? I've just looked into it, and can't reproduce it with a simple example:
```
client.update_item(
        TableName=name,
        Key={"pk": {"S": "item_with_ds"}},
        UpdateExpression="SET #a = :v",
        ExpressionAttributeNames={"#a": "$attr"},
        ExpressionAttributeValues={":v": {"S": "some value"}},
        ConditionExpression="attribute_not_exists(#a)",
        ReturnValues="UPDATED_NEW",
    )
```

**Comment by bblommers** [comment]
I'm going to close this due to a lack of response. If there is a reproducible test case, do let us know!
