### ISSUE TITLE
ConditionExpression on delete_item exception bug

### ISSUE THREAD

**Issue by BriannaBrown-hub** [spulec/moto#4581]
I believe this issues is related to a comment on a prior issue I found [here](https://github.com/spulec/moto/issues/1587#issuecomment-540113365).

The expression below always returns a `ConditionalCheckFailedException` even when the key attributes exists when mocking with moto. I have confirmed that the ConditionExpression works as expected with `boto3`, however when I mock with `moto` an exception is thrown. 

```
table.delete_item(
                Key={
                    'some_key': 'value',
                },
                ConditionExpression="attribute_exists(some_key)"
            )
```

Here is the full exception message:
```
ConditionalCheckFailedException('An error occurred (ConditionalCheckFailedException) when calling the DeleteItem operation: A condition specified in the operation could not be evaluated.')
```

**To reproduce the issue:**

- `create_table` using `mock_dynamodb2`
- Insert an item into the table.
- define a `delete_item` expression including a `ConditionExpression` that references an `attribute_exists` for one of the keys defined when the table was created.
- Call the method passing in the key of the item inserted into the table in a prior step.

**Expected outcome:**

A `ConditionalCheckFailedException` only be thrown when the specified key truly does not exist and that the item with matching key is successfully deleted.

**Actual outcome:**

Item is not deleted and `ConditionalCheckFailedException` is thrown.

**Moto Version:** 2.2.11

**Comment by bpandola** [comment]
@BriannaBrown-hub Can you provide a complete failing test-case?  I added your `ConditionExpression` to our existing `delete_item` test and it succeeds.

**Comment by BriannaBrown-hub** [comment]
@bpandola thanks for the response! In recreating the complete failing test-case I realized my error. Apologies, I will go ahead and close this ticket.
