### ISSUE TITLE
pagination_decorator not passing kwargs to function

### ISSUE THREAD

**Issue by kbalk** [spulec/moto#4584]
I might be interpreting this incorrectly or maybe I missing something:

`pagination_decorator` (`moto/utilities/paginator.py`) pops the kwargs (used for the pagination model) for the function that it is decorating before invoking the function.  This means that the values for those named arguments cannot be validated within the function because those arguments will no longer have a value.

The named arguments could be validated in `responses.py` before the decorator and function are invoked.  But if the other functions are processing parameters in `models.py`, then it's inconsistent.

**Comment by bblommers** [comment]
That is correct @kbalk. The reasoning was that these kwargs can be validated within the paginator, and the model doesn't have to worry about them at all. I'm open to changing it if causes problems for you though.

**Comment by kbalk** [comment]
I just moved the check to the response logic, so it's not causing me problems, it's just not consistent with the other checks in the code I wrote.

I can understand if the paginator did the limit check, but at the moment it doesn't.  I think there are now three suggestions for paginator:

- check for a limit that exceeds the allowable value for limit,
- pass an exception function instead of using "fail_on_invalid_token" true/false,
- rename the "page_ending_range_keys" config value.

None are important or critical, just a "nice to do sometime, if ever" sort of thing.    ;-)

**Comment by kbalk** [comment]
This is the second time I've gone down a rabbit hole on this:   `param_values_to_check=kwargs`.  If you have a kwargs that is a list, you get a error:  `*** TypeError: unhashable type: 'list'`, which makes no sense at all and when you finally step through the code, and if you read the message:

``` 
 # We pop the pagination arguments, so the remaining kwargs (if any)
 # can be used to compute the optional parameters checksum.
```

It finally makes sense.  So annoying.  Because then you have to avoid using kwargs for those arguments simply to get around this issue.

**Comment by bblommers** [comment]
Sounds like improving this decorator is becoming a "should have" instead of "nice to do sometime, if ever", if it's giving you so much grieve. Appreciate the debugging on this @kbalk.
