### ISSUE TITLE
sqs: successfull send_message with MessageGroupID on standard queues

### ISSUE THREAD

**Issue by kthristov** [spulec/moto#4594]
According to AWS documentation MessageGroupId is not required for standard queues and if you send it fails with message: 

`botocore.exceptions.ClientError: An error occurred (InvalidParameterValue) when calling the SendMessage operation: Value default for parameter MessageGroupId is invalid. Reason: The request include parameter that is not valid for this queue type.`

That doesn't happen when MessageGroupId is sent on a standard queue with moto:

```python

sqs = boto3.client('sqs', region_name=Region)
queue = sqs.create_queue(
    QueueName='input_test_queue',
    Attributes={
        'VisibilityTimeout': '5'
    }
)

queue_url  = queue["QueueUrl"]
sqs.send_message(
            QueueUrl=queue_url,
            MessageBody=json.dumps({}),
            MessageGroupId="MessageGroup"
        )

```

Code above should fail but works successfully.

moto version == 2.0.11

**Comment by bblommers** [comment]
Thanks for raising this @kthristov - marking it as an enhancement to implement this validation
