### ISSUE TITLE
mock_kms doesn't respect the kms policy (AccessDeniedException)

### ISSUE THREAD

**Issue by lagrianitis** [spulec/moto#4600]
Hello, 

I am trying to write a unit test, to validate insufficient permissions of the KMS key policy. To do this I wrote a python unit test
where I mock the creation of a KMS key and the attachment of a KMS policy with Deny all actions to the key.
However, when I run `describe_key()` instead of expected `AccessDeniedException` ClientError exception, I retrieve the key information. It looks like the KMS policy is being ignored.

How to reproduce the issue:
Run `pytest test.py` against the following code:

```python test.py
from moto import mock_kms
import pytest
import boto3
import json
from botocore.exceptions import ClientError

@mock_kms
def test_kms():
    client = boto3.client("kms")
    new_key = client.create_key(
        Description="test-key",
        Origin="AWS_KMS"
    )
    key_id = new_key["KeyMetadata"]["KeyId"]
    policy = {
        "Version": "2012-10-17",
        "Id": "",
        "Statement": [
            {
                "Sid": "test",
                "Effect": "Deny",
                "Principal": "*",
                "Action": [
                    "kms:*"
                ],
                "Resource": "*"
            }
        ]
    }
    client.put_key_policy(
        Policy=json.dumps(policy),
        PolicyName="default",
        KeyId=key_id
    )
    with pytest.raises(ClientError) as err:
        client.describe_key(KeyId=key_id)

    assert "AccessDeniedException" in str(err.value)

```

- Tell us **what you expected to happen**
   The unit test to PASS as it should ` pytest.raises` as ClientError with `AccessDeniedException` message

- Tell us **what actually happens**.
   Received: `Failed: DID NOT RAISE <class 'botocore.exceptions.ClientError'>`

   The API actually allows the describe_key() operation and it output the key details, instead of an exception

 - Tell us **what version of Moto you're using**
```
    moto==2.2.13
    boto==2.49.0
    botocore==1.20.73
    boto3==1.17.73

    Moto is installed in my local MacBook using pip install moto
    Python 3.9.7
    pip 21.3
    pytest==6.0.0
```

**Comment by bblommers** [comment]
Correct @lagrianitis - we don't do anything with the policy at the moment. Will mark it as an enhancement to parse and enforce KMS policies

**Comment by bblommers** [comment]
A basic enforcement is now in place as of moto >= 4.0.12.dev39. Moto will throw an AccessDeniedException if the following conditions are met:
 - The principal is set to "\*"
 - The resource is set to "\*"
 - The Action matches `describe_key`

The implementation has been kept to a bare minimum on purpose, to ensure we don't throw an AccessDeniedException unless absolutely necessary. Please let us know if you have a use-case that is not yet covered.
