### ISSUE TITLE
How to get mock JWK for a mocked cognito user pool?

### ISSUE THREAD

**Issue by JamieMcKernanKaizen** [spulec/moto#4601]
So far I have successfully been able to create a mocked user pool and user with moto. The trouble I'm having now is with [this part of the guide that AWS provides on verifying JWT:](https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-verifying-a-jwt.html#amazon-cognito-user-pools-using-tokens-step-2).

It says to get the public keys from `https://cognito-idp.{region}.amazonaws.com/{userPoolId}/.well-known/jwks.json`. Is there any mechanic in moto that allows me to get these public keys for a mocked user pool?

**Comment by bblommers** [comment]
Hi @JamieMcKernanKaizen, welcome to Moto!
You can use Moto to mock this request, as long as you use the requests-module.

This is the method used in our tests:
```
def fetch_public_keys():
    keys_url = "https://cognito-idp.{}.amazonaws.com/{}/.well-known/jwks.json".format(
        "us-west-2", "someuserpoolid"
    )
    response = requests.get(keys_url).json()
    return response["keys"]
```
As long as this is called while the mock is active, it will return the mocked public keys.

**Comment by JamieMcKernanKaizen** [comment]
> Hi @JamieMcKernanKaizen, welcome to Moto! You can use Moto to mock this request, as long as you use the requests-module.
> 
> This is the method used in our tests:
> 
> ```
> def fetch_public_keys():
>     keys_url = "https://cognito-idp.{}.amazonaws.com/{}/.well-known/jwks.json".format(
>         "us-west-2", "someuserpoolid"
>     )
>     response = requests.get(keys_url).json()
>     return response["keys"]
> ```
> 
> Just make sure that this is called while the mock is active, and it will return the mocked public keys.

Thanks, this works perfectly :)
