### ISSUE TITLE
Cant open a PR

### ISSUE THREAD

**Issue by dedanaronson** [spulec/moto#4605]
Hey,

Sorry for being such a newbie 🆕 

I developed locally a part of the glue interface and trying to create a PR in order to get a code review to get some community code review so i will be able to continue and develop the rest of the Job interface

when trying to: 
`git push --set-upstream origin glue-job-interface`

I get the following error:
```
ERROR: Permission to spulec/moto.git denied to dedanaronson.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by bblommers** [comment]
Hi @dedanaronson! The standard workflow would to be fork the repo, and create a new branch on your own fork.

Anywhere on github.com/spulec/moto, there is a 'Fork'-button in the top-right . Clicking that will fork the repo, i.e. give you a local copy that you can work on.
When you have your own fork, you can:

1. Check-out your own fork locally
2. Create a new branch on your own fork
3. Push changes to that branch
4. Then open a PR, to merge the changes from your branch into spulec

Hope that helps - let me know if you get stuck at any point.

**Comment by dedanaronson** [comment]
@bblommers 
Just created the following PR:
https://github.com/spulec/moto/pull/4606

Would love to get your review on it :-)
