### ISSUE TITLE
Support for sns publish_batch

### ISSUE THREAD

**Issue by tkasu** [spulec/moto#4612]
AWS Recently announce support for publishing messages in a batch to a SNS topic:
https://aws.amazon.com/blogs/compute/publishing-messages-in-batch-to-amazon-sns-topics/

This is supported by boto:
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sns.html#SNS.Client.publish_batch

 But as this was just published few days ago, as of `moto==2.2.16` this is not yet supported by moto:
 
 ```python
 import os

import boto3
from moto import mock_sns


@mock_sns
def main():
    os.environ["AWS_DEFAULT_REGION"] = "us-east-1"
    sns = boto3.client("sns")

    sns.publish_batch(
        TopicArn="arn:aws:sns:us-east-1:123456789012:mystack-mytopic-NZJ5JSMVGFIE",
        PublishBatchRequestEntries=[
            {
                "Id": "id1",
                "Message": "Message content 1",
            },
            {
                "Id": "id2",
                "Message": "Message content 2",
            },
        ]
    )


if __name__ == "__main__":
    main()  # Will throw `NotImplementedError: The publish_batch action has not been implemented`
 ```

I tested that the above works to a real topic with `boto3==1.20.10` without `mock_sns` decorator.

**Comment by bblommers** [comment]
Thanks for raising this and providing the test case @tkasu - marking it as an enhancement to implement this

**Comment by racheliurui** [comment]
Waiting it to be implemented in ap-southeast-2, noticed document in boto3 1.20.10 but failed when trying to run it in lambda

**Comment by tkasu** [comment]
> Waiting it to be implemented in ap-southeast-2, noticed document in boto3 1.20.10 but failed when trying to run it in lambda

Currently, Python3 lambda runtimes use boto3-1.18.55:
https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html

However, if you package boto3 as a lambda dependency, it will work 🙂.

**Comment by mswezey23** [comment]
Any updates or ETA? :)
