### ISSUE TITLE
Deprecation warning on 3.10 for setuptools - PEP 386

### ISSUE THREAD

**Issue by matschaffer** [spulec/moto#4615]
I ran into this warning today on 3.10

```
../../local/lib/python3.10/site-packages/moto/core/models.py:22
  /usr/local/lib/python3.10/site-packages/moto/core/models.py:22: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
    from distutils.version import LooseVersion
```

https://www.python.org/dev/peps/pep-0632/ recommends switching to https://pypi.org/project/packaging/ for version comparisons.

Though https://www.python.org/dev/peps/pep-0386/ seems to say we could maybe use `pkg_resources` as well.

**Comment by bblommers** [comment]
Thanks for raising this @matschaffer - markign it as an enhancement to replace this with something else.
