### ISSUE TITLE
Delete thing with certificates

### ISSUE THREAD

**Issue by boazsilverman** [spulec/moto#4616]
## Thing deleted when error should have been thrown

When a thing has certificates attached to it, according to AWS it cannot be deleted, and all certificates must be detached first.
However, in the code here the thing is deleted. The function delete_thing iterates over all the thing's certificates and deletes them, while it should return an InvalidRequestException if any certificates are found.

**Comment by bblommers** [comment]
Thanks for raising this @boazsilverman - will mark it as a bug

**Comment by boazsilverman** [comment]
Great job, thanks!
If I'm not mistaken (and I very well might be, as I'm not deep in the
code), there is a comment in line 698 which seems to be outdated
# detach all principals
The new commit correctly doesn't detach principals, rather raises.. If this
isn't correct, sorry to inconvenience you

Keep up this fantastic library!

**Comment by bblommers** [comment]
Yes, good spot - thanks for letting us know @boazsilverman
