### ISSUE TITLE
Error executing `PutObjectCommand` via Javascript

### ISSUE THREAD

**Issue by Shoeboxam** [spulec/moto#4652]
I'm relatively green to S3, so please excuse any miscommunication. I am having issues executing a PutObjectCommand to put a new object in moto server from the node.js AWS S3 V3 API.

Here's my Javascript code:
```javascript
import {
    PutObjectCommand,
    S3Client
} from "@aws-sdk/client-s3";

let client = new S3Client({
    endpoint: "http://127.0.0.1:5000",
    credentials: {
        accessKeyId: "unimportant",
        secretAccessKey: "unimportant"
    }
});
let command = new PutObjectCommand({
    Bucket: "mybucket",
    Key: "mykey",
    Body: "ABC",
    ACL: 'public-read',
}));
await client.send(command).catch(err => console.log(err.stack));
```

The error I get:

```
Error: getaddrinfo ENOTFOUND mybucket.127.0.0.1
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:72:26)
```

Based on this error, I wonder if the PutObjectCommand is inserting a bucket subdomain into the endpoint, and the moto server isn't handling the subdomain? Other commands work properly (ListBucketsCommand, CreateBucketCommand, GetObjectCommand). Is this supported by Moto, or am I using the interfaces incorrectly?

I'm on `moto==2.2.9`, installed from pip. I start moto with `moto_server s3`. 
My npm version is `"@aws-sdk/client-s3": "^3.27.0"`

Thank you!

**Comment by bblommers** [comment]
Hi @Shoeboxam! Yes, it looks like the Javascript SDK uses domain-style buckets by default, which wouldn't work in localhost.

The SDK does support path-style buckets (i.e., `localhost/bucket/key`), which is supported by Moto, using this config:
https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-s3/interfaces/s3clientconfig.html#forcepathstyle

I'm not familiar with the Javascript SDK at all, but it looks like that would fix the problem.

**Comment by Shoeboxam** [comment]
That fixed it! Here's the revised snip:

```javascript
let client = new S3Client({
    endpoint: "http://127.0.0.1:5000",
    forcePathStyle: true,  
    credentials: {
        accessKeyId: "unimportant",
        secretAccessKey: "unimportant"
    }
});
```

Thanks!
