### ISSUE TITLE
LocalSecondaryIndexes does not work for querying in dynamodb

### ISSUE THREAD

**Issue by krupnov** [spulec/moto#4660]
Hi,

I am using the moto3 for testing inside my projects. It us really cool and thank you guys for your effort.

But recently I have discovered there is a problem with querying LocalSecondaryIndexes in DynamoDb. 

I use mock_dynamodb2 and create a local index in a table. After adding some items into the table I try to query the index to get values that are greater than a specific value. But all items are returned. If you are interested I can provide a full testing example.

Also I noticed there is no tests that check my use case in the repository.

Could  you please take a look?

**Comment by krupnov** [comment]
Also. It is not possible to call dynamodb client create table with  "GlobalSecondaryIndexes": [] or "LocalSecondaryIndexes": [] in a real boto3 implementation. 

Could it be also fixed?

Thank you.

**Comment by krupnov** [comment]
Sorry. My bad. Found a bug in my code. Sorry guys. And double checked your code. Looks like there is no difference between local and global index querying. Sorry :)

**Comment by bblommers** [comment]
All good - happy to hear it's working now @krupnov :)

> Also. It is not possible to call dynamodb client create table with "GlobalSecondaryIndexes": [] or "LocalSecondaryIndexes": [] in a real boto3 implementation.
> 

I'll reopen the issue to get this fixed, as that is arguably a bug in our implementation!
