### ISSUE TITLE
Add support for EC2 create_snapshots 

### ISSUE THREAD

**Issue by Vitaly-Frolov** [spulec/moto#4669]
Hi, 
I know that currently there isn't support for the create_snapshots function,
Can you please update on the status of this feature?

**Comment by bblommers** [comment]
Hi @Vitaly-Frolov, welcome to Moto! I'm not aware of any plans to implement this, but I'll mark it as an enhancement for people who want to work on this.
If this is something you need, PR's are always welcome!

**Comment by teddylear** [comment]
@Vitaly-Frolov @bblommers I can give this a shot if that's alright.

**Comment by bblommers** [comment]
Definitely @teddylear. There's some documentation here that could be helpful: http://docs.getmoto.org/en/latest/docs/contributing/index.html

**Comment by teddylear** [comment]
Actually not sure if I'll have time to work on this, if someone else wants to pick it up feel free.
