### ISSUE TITLE
IoT models hard-codes account ID as 1

### ISSUE THREAD

**Issue by dhmistry3** [spulec/moto#4675]
the cert that is created when doing something such as client('iot').create_keys_and_certificate(setAsActive=True) has an account id hard-coded to 1 instead of retrieving the accountid that other things do.

https://github.com/spulec/moto/blob/master/moto/iot/models.py#L139

I changed it to

`self.arn = "arn:aws:iot:%s:%s:cert/%s" % (region_name, ACCOUNT_ID, self.certificate_id)`

and added ACCOUNT_ID import from moto.core and it worked.

**Comment by bblommers** [comment]
Good spot @dhmistry3 - thanks for raising this!
