### ISSUE TITLE
sqs receive_message gives subject as null

### ISSUE THREAD

**Issue by evohnave** [spulec/moto#4676]
Sometime between moto=2.2.11 and moto==2.2.17 the "Subject" of an sqs message was deleted so that 

`messages = sqs.receive_message(QueueUrl=sqs_queue_url)`  
`body = eval(messages.get('Messages')[0].get('Body'))`  

results in  

>   File "\<string\>", line 7, in \<module\>
> 
> NameError: name 'null' is not defined

Investigation of the `"Message"."Body"` shows that, in 2.2.11, `"Subject"` is "my subject" and, in 2.2.17, `"Subject"` is `null` , i.e., inside of `"Body"`,  

> ...`"Subject": "my subject",\n  "Timestamp"`...
  
   vs  

> ...`"Subject": null,\n  "Timestamp"`...  

and `eval` chokes on evaluating "null".

My code never provided the "Subject", so it appears to me to be a `moto` thing.

**Comment by bblommers** [comment]
Hi @evohnave, thanks for raising this! Marking it as a bug
