### ISSUE TITLE
error in ecs_client.register_container_instance

### ISSUE THREAD

**Issue by yduan-polo** [spulec/moto#4689]
## Reporting Bugs

Following https://github.com/spulec/moto/blob/master/tests/test_ecs/test_ecs_boto3.py#L1528 to test run_task, but https://github.com/spulec/moto/blob/master/tests/test_ecs/test_ecs_boto3.py#L1544 gave an error. 

botocore.exceptions.ClientError: An error occurred (400) when calling the RegisterContainerInstance operation: <?xml version="1.0" encoding="UTF-8"?>
E           <Response>
E             <Errors>
E               <Error>
E                 <Code>InvalidInstanceID.NotFound</Code>
E                 <Message>The instance ID 'i-fc5688f32c13b2a07' does not exist</Message>
E               </Error>
E             </Errors>
E             <RequestID>7a62c49f-347e-4fc4-9331-6e8eEXAMPLE</RequestID>
E           </Response>

**Comment by bblommers** [comment]
Hi @yduan-polo, can you post the full test case that is failing for you?

**Comment by yduan-polo** [comment]
See below the test case. 




@mock_ec2
@mock_ecs
def test_full_refresh_model_adheres_to_boto_method_signatures():
    """
    Ensure that the boto3 client methods for ECS are invoked
    using expected, valid parameters.
    """

    region = 'eu-west-1'
    ecs_client = boto3.client('ecs', region_name=region)
    ec2_client = boto3.resource("ec2", region_name="us-east-1")

    test_cluster_name = 'TEST-CLUSTER'
    _ = ecs_client.create_cluster(clusterName=test_cluster_name)

    EXAMPLE_AMI_ID = "ami-12c6146b"
    test_instance = ec2_client.create_instances(
        ImageId=EXAMPLE_AMI_ID, MinCount=1, MaxCount=1
    )[0]

    instance_id_document = json.dumps(
        ec2_utils.generate_instance_identity_document(test_instance)
    )

    response = ecs_client.register_container_instance(
        cluster=test_cluster_name, instanceIdentityDocument=instance_id_document
    )

    container_family_prefix = 'test_ecs_task'
    container_name = 'test_ecs_container'
    test_task_definition = dict(
        family=f'{container_family_prefix}_daily',
        containerDefinitions=[
            {"name": f"{container_name}", "image": "hello-world:latest", "memory": 400,}
        ],
    )
    response = ecs_client.register_task_definition(**test_task_definition)
    task_definition_arn = response['taskDefinition']['taskDefinitionArn']

    configs = Configs(
        cluster_arn=test_cluster_name,  # this has to adhere to ARN format
        scheduler_role_arn='arn:aws:iam::xxxxxxxxxxxx:role/TEST-ROLE',
        task_subnets=['subnet-00000','subnet-00001','subnet-00002'],
        task_security_groups=['sg-00000'],
        task_role_arn='arn:aws:iam::xxxxxxxxxxxxxx:role/TEST-Role',
        exec_role_arn='arn:aws:iam::xxxxxxxxxxxxxx:role/TEST-Role',
        container_name=container_name,
        container_family_prefix=container_family_prefix,
        eventbridge_rule_name_prefix='test_rule_name_prefix',
        dry_run='false',
        cloudwatch_log_target='/STG/DATA_ENGINEERING/DATA_WAREHOUSE',
        ssm_slack_monitor_url='/STG/DATA-ENG/DATA-WAREHOUSE/SLACK_URL/monitor-dataeng-stg',
        ssm_google_sheet_credential='/STG/DATA-ENG/DATA-WAREHOUSE/GOOGLE_SHEETS_CREDENTIALS',
        ssm_slack_team_url='/STG/DATA-ENG/DATA-WAREHOUSE/SLACK_URL/team-data-eng',
        dbt_profile_target='stg'
    )


    task_response = run_refresh_task(
        ecs_client=ecs_client,
        user='bar',
        model='model',
        configs=configs
    )

**Comment by bblommers** [comment]
Hi @yduan-polo, the EC2-instance needs to be created in the same region as the ECS-client:
```
region = 'eu-west-1'
ecs_client = boto3.client('ecs', region_name=region)
ec2_client = boto3.resource("ec2", region_name=region)  # NOT in us-east-1
```
As far as I know, that corresponds to how AWS behaves, as ECS in the EU can never find an instance created in the US.

**Comment by yduan-polo** [comment]
yes, they must be in the same region. Sorry, that's my mistake, didn't spot it.
