### ISSUE TITLE
`IoTDataPlaneResponse.publish` fails to correctly pass payload to `IotDataPlaneBackend.publish` method

### ISSUE THREAD

**Issue by iggyzap** [spulec/moto#4694]
Hi,

When trying to implement a unit test that validates that MQTT message was sent via `boto3.client('iot-data')` client to specific topic, I found out that `IoTDataPlaneResponse.publish` fails to pass down `payload` correctly to `IotDataPlaneBackend.publish` method.

I was able to mock IotDataPlaneBackend backend for interaction in interest and even record publish calls, but payload was empty.

This is due to the fact that aws IoT client posts payload as http post body, but `IoTDataPlaneResponse.publish` expects payload to be passed as parameter (code below):
```python
class IoTDataPlaneResponse(BaseResponse):
...
    def publish(self):
        topic = self._get_param("topic")
        qos = self._get_int_param("qos")
        payload = self._get_param("payload")
        self.iotdata_backend.publish(topic=topic, qos=qos, payload=payload)
        return json.dumps(dict())
```
Image from debugger:
<img width="773" alt="image" src="https://user-images.githubusercontent.com/4525023/146213115-d3d82245-1f82-405b-ba36-7d0cdb4e9cd4.png">

I would expect when payload was posted to an MQTT topic then it will become available and passed down as payload to `IoTDataPlaneResponse.publish` method.

Following version of moto is used:
```json
"moto": {
            "hashes": [
                "sha256:2b3fa22778504b45715868cad95ad458fdea7227f9005b12e522fc9c2ae0cabc",
                "sha256:79aeaeed1592a24d3c488840065a3fcb3f4fa7ba40259e112482454c0e48a03a"
            ],
            "index": "pypi",
            "version": "==1.3.14"
        }

```

**Comment by bblommers** [comment]
Hi @iggyzap, thanks for raising this! Will mark it as a bug.
