### ISSUE TITLE
ec2 Run instance does not create the default volume

### ISSUE THREAD

**Issue by slemesle** [spulec/moto#470]
When trying to retrieve the default volume after a run instance, using block_device_mapping, the volume_id is just an random volume_id not corresponding to any volume. 

Is it possible to create the volume in this case ?

**Comment by spulec** [comment]
Can you go into a bit more detail about what you are trying to accomplish? It is my understanding that this is somewhat of a 'ghost volume' that is created and is not available in calls like `get_all_volumes`.

**Comment by slemesle** [comment]
So, I try to add tags to the root volume of a fresh new instance. 
When I try `get_all_volumes` with the `volume_id` returned by Moto in the `block_device_mapping`, Moto returns an empty `VolumeSet`. I've looked at the code and saw that the `volume_id` in this case is generated. 

Here is the code in the init of `Instance` class [code](https://github.com/spulec/moto/blob/master/moto/ec2/models.py#L322)

```python
 self.block_device_mapping = BlockDeviceMapping()
        # Default have an instance with root volume should you not wish to override with attach volume cmd.
        # However this is a ghost volume and wont show up in get_all_volumes or snapshot-able.
        self.block_device_mapping['/dev/sda1'] = BlockDeviceType(volume_id=random_volume_id(), status='attached',
                                                                 attach_time=utc_date_and_time())
```

So there is no Volume to find when trying to access it, although EC2 API allows to find it and my boto code use it to place some tags on it.

**Comment by spulec** [comment]
You are correct. It looks like the comment in that code is inaccurate.

**Comment by spulec** [comment]
Fixed with https://github.com/spulec/moto/commit/44f0377cc478c6f5ed22e586cc0e4af291eb292b

Thanks for opening!
