### ISSUE TITLE
Moto ECR mock throws away user-provided registry IDs

### ISSUE THREAD

**Issue by sichinumi** [spulec/moto#4705]
The Moto ECR mock does not respect registry ID parameters with any ECR APIs - instead it uses a hard-coded default (the account ID itself). This causes incorrect state/output when test authors need to mock behavior around specific registry IDs.

Example code - just a create_repository call with a specific, non-default registry ID:

```
client = boto3.client('ecr', region_name='us-west-2')
client.create_repository(
        registryId='222222222222',
        repositoryName='myRepoName'
    )
print(client.describe_repositories())
```

Example output showing that the repository was created under the wrong registry ID:

```
{'repositories': [{'repositoryArn': 'arn:aws:ecr:us-west-2:123456789012:repository/myRepoName', 'registryId': '123456789012', 'repositoryName': 'myRepoName', 'repositoryUri': '123456789012.dkr.ecr.us-west-2.amazonaws.com/myRepoName', 'createdAt': datetime.datetime(2021, 12, 21, 0, 53, 14, tzinfo=tzlocal()), 'imageTagMutability': 'MUTABLE', 'imageScanningConfiguration': {'scanOnPush': False}, 'encryptionConfiguration': {'encryptionType': 'AES256'}}], 'ResponseMetadata': {'HTTPStatusCode': 200, 'HTTPHeaders': {'server': 'amazon.com'}, 'RetryAttempts': 0}}
```

The output says the registry ID is 123456789012 which is the default account ID. My input of registry ID of 222222222222 was ignored.

Reading the source code this seems like it's by design - we hard-code the registry ID here: https://github.com/spulec/moto/blame/43269fc8af7872aebb648233c551053d499503b4/moto/ecr/models.py#L75

In addition we don't even accept a registry ID for create_repository: https://github.com/spulec/moto/blame/43269fc8af7872aebb648233c551053d499503b4/moto/ecr/models.py#L407-L414

This is with Moto v2.2.19 (latest I believe) and Boto3 v1.20.21.

**Comment by sichinumi** [comment]
Worth noting that our tests were previously working with Moto v1.3.16, so this seems to be a regression... but reading through the same code in 1.3.16 we seem to have the same issues, we don't actually ingest registry ID anywhere. Still trying to figure out what changed.

It is odd that we have all this code that does sanity checks/filters on registry ID, like this: https://github.com/spulec/moto/blame/43269fc8af7872aebb648233c551053d499503b4/moto/ecr/models.py#L395-L398 when it's impossible to actually use a non-default registry ID... maybe I'm missing something about how registry IDs are set?

**Comment by sichinumi** [comment]
Ah figured it out, this was always broken even in 1.3.16, there is just very poor enforcement of registry ID across the board. In 1.3.16 it was possible to create a repository with a unique registry ID, put an image there, and then call describe_images while passing in that registry ID - and this would all work behind the scenes, even though the registry ID itself was never saved, and the repository was technically invalid. This is because in the describe_images call in 1.3.16, we matched a repository by name without applying a registry ID filter: https://github.com/spulec/moto/blob/63ce647123755e4c4693a89f52c254596004c098/moto/ecr/models.py#L275-L280

However in 2.2.19 there is a new method called _get_repository which actually performs this registry ID filter, which now throws when we call describe_images: https://github.com/spulec/moto/blame/43269fc8af7872aebb648233c551053d499503b4/moto/ecr/models.py#L365-L370

The issue is still the same, under the hood the registry IDs have always been ignored and hard-coded, we just now throw on certain API calls if users actually pass in custom registry IDs, whereas before we silently passed.

**Comment by bblommers** [comment]
Thanks for raising this @sichinumi, and for doing the investigation - that will make it much quicker to fix it. 
Raising is as a bug.
