### ISSUE TITLE
Cancel spot fleet request without terminate incorrectly removes the fleet entirely

### ISSUE THREAD

**Issue by cheshirex** [spulec/moto#4715]
https://github.com/spulec/moto/blob/c301f8822c71a402d14b380865aa45b07e880ebd/moto/ec2/models.py#L6549

I'm working with localstack on moto and trying to simulate a flow of:

- create spot fleet with X instances
- cancel the fleet without terminating instances
- cancel the fleet with terminating instances

However, I see the referenced line is deleting the fleet from moto's dictionary *regardless* of whether the instances are being terminated. This results in the last part of my flow failing.

The actual AWS behaviour is that the fleet goes to cancelled_running state without affecting the instances when a spot fleet request is cancelled without terminating instances, and only actually gets cancelled when all the instances are terminated. It is therefore possible to submit another termination request to AWS with the flag to terminate instances.

Thanks!

**Comment by bblommers** [comment]
Hi @cheshirex, thanks for raising this. It does look like our implementation of this feature is a bit... spotty.

Marking it as a bug to pimplement this flag properly.
