### ISSUE TITLE
s3 get_object to return TagCount

### ISSUE THREAD

**Issue by mdavis-xyz** [spulec/moto#4751]
# Summary

The `get_object()` function in boto with the real S3 returns `TagCount` if there are any tags on the object.
With moto, `TagCount` is never returned, but should be.

# Steps to reproduce

Try this with `if True` to use moto, and `if False` to not use moto.

```
import urllib.parse
from pprint import pprint
import os

import boto3
from moto import mock_s3


bucket = 'mybucket'
key = 'test-tags'

tags = {'a': 'b'}

if True:
    mock_s3().start()
    boto3.client('s3').create_bucket(
        Bucket=bucket,
        CreateBucketConfiguration={
            'LocationConstraint': os.getenv('AWS_DEFAULT_REGION', 'ap-southeast-2')
        },
    )



client = boto3.client('s3')
client.put_object(
    Bucket=bucket,
    Key=key,
    Tagging=urllib.parse.urlencode(tags),
    Body=b"123"
)

resp = client.get_object(
    Bucket=bucket,
    Key=key,
)

pprint(resp)
assert resp['TagCount'] == len(tags)

```

# expected results

When you run the above with `if False` (to use real S3), the returned tag count is 1.
When you run the above with `if True` (to use moto) the returned tag count is 1.
In both cases the assertion passes.

# Actual results.

When you run the above with `if False` (to use real S3), the returned tag count is 1.
When you run the above with `if True` (to use moto) there is no `TagCount` in the response and the assertion line throws a `KeyError`.

# Notes

I'm using moto 2.2.16

If the object has no tags, the real boto does not return any `TagCount` field.

**Comment by bblommers** [comment]
Thanks for raising this @mdavis-xyz - marking it as an enhancement to add this field.
