### ISSUE TITLE
SNS Message Attributes incorrectly converted to float values

### ISSUE THREAD

**Issue by JordanReiter** [spulec/moto#4757]
Relevant code in `moto/sns/responses.py` ([lines 64-74](https://github.com/spulec/moto/blob/72fdaa3552079e0db53bb53078cebfe426319b65/moto/sns/responses.py#L64-L74))

                if data_type == "Number":
                    try:
                        transform_value = float(value["StringValue"])
                    except ValueError:
                        raise InvalidParameterValue(
                            "An error occurred (ParameterValueInvalid) "
                            "when calling the Publish operation: "
                            "Could not cast message attribute '{0}' value to number.".format(
                                name
                            )
                        )

Using `float` converts any number to a float, even numbers which were originally integers. This is not how AWS behaves; it correctly distinguishes between integers and float values.

### To reproduce

First create a SNS topic and subscribe an SQS queue to that topic with `RawMessageDelivery` attribute set to true.

Then:

        sns_client.publish(
            TopicArn=topic_arn,
            Message=message,
            MessageAttributes={
                'integer': {
                    'DataType': 'Number',
                    'StringValue': '123'
                },
                'float': {
                    'DataType': 'Number',
                    'StringValue': '12.34'
                },
                **extra
            },
            MessageGroupId=task_id
        )
        messages_resp = sqs_client.receive_message(
            QueueUrl=queue_url,
            MessageAttributeNames=['All']
        )
        message = messages_resp['Messages'][0]
        message_attributes = message['MessageAttributes']

### Expected:

Message attributes should look like:

```
{
     'float': {'DataType': 'Number', 'StringValue': '12.34'},
    'integer': {'DataType': 'Number', 'StringValue': '123'}
}
```

### Actual:

Message attributes are returned as:
```
{
    'float': {'DataType': 'Number', 'StringValue': '12.34'},
    'integer': {'DataType': 'Number', 'StringValue': '123.0'}
}
```

### Solution:

When outputting the response, it should detect whether or not it is an integer or a decimal/float-like object

One possible implementation:

                    try:
                        try:
                            transform_value = int(value["StringValue"])
                        except ValueError:
                            transform_value = float(value["StringValue"])

If the value is int-like, then `int` will work. If it has a decimal point, it will fail and fall over to use `float` to convert.

It may even be better to use `decimal.Decimal` to convert the value, especially considering it is frequently used to store float-like values (see, e.g. DynamoDB).

**Comment by JordanReiter** [comment]
If you don't have anyone available to make these updates I'd be happy to do so. I have contributed to moto in the past and could resolve this as well as issue #4756.

**Comment by bblommers** [comment]
Hi @JordanReiter, thanks for raising this. A PR would be very welcome! The suggested solutions look good to me.
