### ISSUE TITLE
Moto raises boto exceptions when used with boto3

### ISSUE THREAD

**Issue by gffhcks** [spulec/moto#476]
I'm using Moto with Boto3, and it seems to work quite well - as long as you don't care about exceptions:

```python
import moto
import unittest
import botocore.exceptions

class TestMotoExceptions(unittest.TestCase):

    @moto.mock_iam
    def test_create_already_exists(self):
        username = 'foo'
        client = boto3.client('iam')
        client.create_user(UserName=username)
        self.assertRaises(client.create_user(UserName=username), botocore.exceptions.ClientError)

```

Boto3 raises a `botocore.exceptions.ClientError` exception, with the response error code equal to `'EntityAlreadyExists'`, if you try to create a user twice. I'm handling this exception in my code. But Moto raises a `boto.exception.BotoServerError` for this same situation; my code doesn't expect that, so the exception is never handled.

Is there a way around this, other than either adding extra exception handlers just for testing, or using the original Boto?

**Comment by spulec** [comment]
Thanks for opening. This should be fixed in master now.

**Comment by gffhcks** [comment]
@spulec Just tested it out and it is raising the correct exception (botocore.exceptions.ClientError). However, it is not giving the correct Error Code - `exception.response['Error']['Code']` is set to `Conflict`, when actual AWS calls return `EntityAlreadyExists`. This is important in my case, because I'm using the error code to distinguish the case from other possible errors:

```python
    try:
        self.client.create_user(UserName=self.name)
        LOGGER.info('Created user \'%s\'', self.name)
    except botocore.exceptions.ClientError as exception:
        if exception.response['Error']['Code'] != 'EntityAlreadyExists':
            print("Error code: {}".format(exception.response['Error']['Code']))
            raise
        LOGGER.info('User \'%s\' already exists', self.name)
```

Should this issue be reopened, or should I open a new one?

**Comment by spulec** [comment]
You are correct. Just fixed. Thank you.
