### ISSUE TITLE
Cloudfront - get_distribution() does not return same config passed to create_distribution()

### ISSUE THREAD

**Issue by pll** [spulec/moto#4768]
When passing in a fully-formed Cloudfront Distribution Configuration, the response back from `create_distribution()` does not contain all of the information passed in.  Calling `get_distribution()` with the Id passed back from `create_distribution() also exhibits the same issue (which makes sense...

I initially noticed the issue with the `DistributionConfig.Comment`  field missing from the response of `get_distribution()`, but it appears other items are missing as well, such as `Aliases.Items`, which I passed in with a list of 10 items, but the reply came back with an empty list.  

The behavior I expected was that moto would, when passed a cf dist config in a call to `create_distribution()`,  simply copy what it's been given into the distribution created. But this is not what appears to be happening. Perhaps my expectations are incorrect, and if so, please reset them for me :)

I have attached test script here, as well as the mock distribution configuration I am using.  The output of the script looks like this:

```
$ /tmp/test-moto-cf.py
Comment taken from config file passed to create_distributions():
Comment from mock dist:            ---> Boring comment <---

Calling create_distributions() with config file
Should be a comment in the following line:
Comment from create_distributions: --->  <---

Assigning comment to response['Distribution']['DistributionConfig']['Comment']
Should be a really clever comment in the following line:
Assigned Comment:                  ---> A Really clever Comment <---


Should be a comment in the following line too:
Comment from get_distribution():   --->  <---

```

Thanks.
Paul

[moto_cloudfront_test.zip](https://github.com/spulec/moto/files/7876112/moto_cloudfront_test.zip)

**Comment by bblommers** [comment]
Hi @pll, the current Cloudfront implementation only supports a subset of input parameters for now. I'll mark it as an enhancement to also implement the others.

Considering the sheer number of parameters available, this might be a staggered effort - are the `DistributionConfig.Comment` and `Aliases.Items` fields the only ones you are missing for your usecase?

**Comment by pll** [comment]
Hi @bblommers,

Thanks for the rapid reply!

I found a work-around, and possibly better field to trigger off of than `DistributionConfig.Comment`, for now. But I'll definitely need the `DistributionConfig.Aliases` structure. If you have to prioritize between the two, then `Aliases` gets my vote over `Comment`.

Out of curiosity, how is it that `create_distribution()` doesn't populate the entire `DistributionConfig` sub-structure with whatever data it's passed? Are subsequent calls within `create_distribution()` to create that structure, and moto just doesn't have those yet? (in my ignorance, I assumed whatever was passed into `create_distribution()` for a dist config would just be copied to to the `DistributionConfig` sub-structure. Clearly I'm wrong :)

Thanks again.
Paul

**Comment by bblommers** [comment]
There's quite a bit of logic when we receive the input around setting sensible defaults, validation, etc. The output isn't always guaranteed to be the same as the input either. Converting the dict into Python-objects makes it much easier to program the logic around this.

For the majority of services, this isn't really an issue, as the input-structure is small and straightforward. If there are dozens of input fields, like with CF, it is much more time consuming to do the whole dict->object->dict conversion, so mapping the fields/parameters usually happens on an as-needed basis.

**Comment by pll** [comment]
Thanks for the explanation.  I've tried digging into the moto code myself to see if I could figure it out, but it's a little beyond my skill level at this point.  Perhaps looking at diffs for this one change might be helpful.  I need a "moto hacking for dummies" intro :)

Thanks again!
