### ISSUE TITLE
boto3 + elb + describe_tags = NotImplementedError in moto

### ISSUE THREAD

**Issue by a1exsh** [spulec/moto#479]
Hi,

I'm hitting an error when trying to add tests to some existing code that is using boto3 client library with moto: `NotImplementedError: The describe_tags action has not been implemented`: https://travis-ci.org/zalando/zmon-aws-agent/jobs/95541858

This happens with the ELB client.  The problem appears to be that even though the XML request/response for this API are well defined, the old boto interface doesn't provide a method for this particular call.

Do you see a good way around this sort of issues short of re-implementing moto with boto3 interfaces?

**Comment by 2mf** [comment]
I think that is not boto3 related but add_tags, describe_tags and remove_tags seems to be not yet implemented in moto. 
I implemented those for kinesis and it seems there are more places missing the endpoints.

**Comment by a1exsh** [comment]
Well, I see some general `create/delete/describe_tags` methods in `ec2` backend, but I'm not sure if these can/should be used in `elb`.  At least `VALID_TAG_RESOURCE_FILTER_TYPES` doesn't list `elb`.
