### ISSUE TITLE
Is there interesting in using Pipenv for dependency management?

### ISSUE THREAD

**Issue by felipe1982** [spulec/moto#4798]
I have been using `pipenv` with the following Pipfile successfully, mostly on adding a feature to moto.

```Pipfile
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
black = "==19.10b0"
click = "*"
flake8 = "==3.7.8"
freezegun = "*"
inflection = "==0.3.1"
lxml = "*"
prompt-toolkit = "*"
pylint = "*"
pytest = "*"
pytest-cov = "*"
pytest-xdist = "*"
regex = "==2019.11.1"
sure = "*"
moto = {editable = true, extras = ["all,server"], path = "."}
docker = "*"
Flask = "*"
pipfile = "*"

[dev-packages]

[requires]
python_version = "3.8"
```

Is there a better approach? Is using `requirements.txt` still the better option? 
#1665 some issues from the past...

**Comment by bblommers** [comment]
Hey @felipe1982! Personally I don't have any strong feelings either way. The `requirements.txt` may be the old way of doing it, but I've never had a need to use anything else instead.
Are there any benefits to using the Pipfile-approach for Moto?

**Comment by bblommers** [comment]
I'm going to close this. I'm not averse to making changes here, but it doesn't look like there is a lot of support for this move.
