### ISSUE TITLE
s3 list_object_versions ignores Prefix on DeleteMarkers.

### ISSUE THREAD

**Issue by FZetting** [spulec/moto#4821]
Hi,
after deleting some objects in a bucket with versioning, when I search with client.list_object_versions(Bucket='myBucket', Prefix='MyKey') only objects with the key "MyKey" should appear in the result. For "Versions" this is true, for "DeleteMarkers" the prefix is ignored.
If I do the same with MinIo the expected result appears.

**Comment by FZetting** [comment]
It looks like the error is on my side. I'll search a bit further and if it's an error I'll open the error again.

**Comment by FZetting** [comment]
Unfortunately there was my error and the previous mentioned bug.

And now i have also some code to show the issue.

``
    from moto import mock_s3
    import boto3


    def create_objects(client, bucket_name):
        for pos in range(2):
            client.put_object(Bucket=bucket_name, Key=f'obj_{pos}', Body=f'This is object {pos}'.encode('utf-8'))

        for pos in range(2):
            client.put_object(Bucket=bucket_name, Key=f'hist_obj_{pos}', Body=f'This is history object {pos}'.encode('utf-8'))
            for hist_pos in range(2):
                client.put_object(Bucket=bucket_name, Key=f'hist_obj_{pos}',
                                  Body=f'This is history object {pos} {hist_pos}'.encode('utf-8'))

        for pos in range(2):
            client.put_object(Bucket=bucket_name, Key=f'del_obj_{pos}', Body=f'This is deleted object {pos}'.encode('utf-8'))
            client.delete_object(Bucket=bucket_name, Key=f'del_obj_{pos}')


    if __name__ == "__main__":
        BUCKET_NAME = "tests_bucket"
        s3_mock = mock_s3()
        s3_mock.start()
        # client = boto3.client("s3", endpoint_url="http://localhost:5000")
        client = boto3.client("s3")
        client.create_bucket(Bucket=BUCKET_NAME)
        client.put_bucket_versioning(Bucket=BUCKET_NAME, VersioningConfiguration={
            'MFADelete': "Disabled",
            'Status': "Enabled"})
        create_objects(client, BUCKET_NAME)

        objs = client.list_object_versions(Bucket=BUCKET_NAME)
        hist_objs = client.list_object_versions(Bucket=BUCKET_NAME, Prefix="hist_obj")
        del_objs = client.list_object_versions(Bucket=BUCKET_NAME, Prefix="del_obj_0")

**Comment by bblommers** [comment]
Thanks for raising this and for providing a test case @FZetting - marking it as a bug :+1:
