### ISSUE TITLE
ELB response gives empty list for missing load balancer instead of thrown exception

### ISSUE THREAD

**Issue by gilzellner** [spulec/moto#484]
# Boto behaviour:

In [9]: conn.get_all_load_balancers()
Out[9]: [LoadBalancer:STICKYLB]

In [10]: conn.get_all_load_balancers(load_balancer_names='aaa')
BotoServerError: BotoServerError: 400 Bad Request
        <Message>Cannot find Load Balancer aaa</Message>

# moto behaviour: 
In [14]: conn.get_all_load_balancers()
Out[14]: [LoadBalancer:STICKYLB]

In [14]: conn.get_all_load_balancers(load_balancer_names='aaa')
Out[14]: []

**Comment by spulec** [comment]
Thanks for opening!

Fixed with https://github.com/spulec/moto/commit/5d421dc343046bda58220b047133d5b418248ee8
