### ISSUE TITLE
create_capacity_provider for ECS

### ISSUE THREAD

**Issue by OzNetNerd** [spulec/moto#4858]
Hi there. I was just wondering if you'll be adding support for `create_capacity_provider`?

Thank you.

**Comment by bblommers** [comment]
Hi @OzNetNerd, thanks for raising this - I'll mark it as an enhancement. 
This is not in the pipeline at the moment, so if this is something you need with high priority, PR's are always welcome! 

http://docs.getmoto.org/en/latest/docs/contributing/index.html
