### ISSUE TITLE
“python_requires” should be set with “>=3.6”, as moto 3.0.3 is not compatible with all Python versions.

### ISSUE THREAD

**Issue by PyVCEchecker** [spulec/moto#4859]
Currently, the keyword argument **python_requires** of **setup()** is not set, and thus it is assumed that this distribution is compatible with all Python versions. 
However, I found it is not compatible with **Python<3.6**. My local Python version is 2.7, and I encounter the following error 

```
>>> import moto
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/moto/__init__.py", line 14
    f"Module {element} has been deprecated, and will be repurposed in a later release. "
                                                                                       ^
SyntaxError: invalid syntax
```
I noticed that **\_\_init\_\_.py** used the syntax feature **f-string**. The feature is only compatible with Python 3.6 and above, resulting in runtime error in Python 2.7.

Way to fix:
modify **setup()** in **setup.py,** add **python_requires** keyword argument:
```python
setup(…
     python_requires=">=3.6"
     …)
```
Thanks for your attention.
Best regrads,
PyVCEchecker

**Comment by bblommers** [comment]
Thanks for raising this @PyVCEchecker  - you're right, we should expose that argument. Will raise a PR shortly.

FWIW: The last Moto version that supported Python 2.7 was `2.1.0` - see the Changelog here: https://github.com/spulec/moto/blob/master/CHANGELOG.md
