### ISSUE TITLE
Add support for AWS Textract

### ISSUE THREAD

**Issue by ecumene** [spulec/moto#4863]
[Add support for AWS Textract](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/textract.html
)

I only really need...
[get_document_text_detection()](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/textract.html#Textract.Client.get_document_text_detection)
[start_document_text_detection()](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/textract.html#Textract.Client.start_document_text_detection)

I've read the CONTRIBUTE.md and it doesn't seem like it would be too much effort for me to add this. Anyone want to weigh in?

**Comment by bblommers** [comment]
Hi @ecumene, welcome to Moto! Our [scaffolding-script](https://docs.getmoto.org/en/latest/docs/contributing/new_feature.html) should help a lot with the plumbing - it's not guaranteed to get everything right, but at least it will be in the right direction.

If you do get stuck, you can always open a draft PR - I'd be happy to have a look to see what's missing.
