### ISSUE TITLE
Expose logic of get_amis.py in moto as a test.utils.something

### ISSUE THREAD

**Issue by timsnyder** [spulec/moto#4865]
Would you guys be opposed to making this code

https://github.com/spulec/moto/blob/871591f7f17458c10ce039d6e2f36abe3430fec5/scripts/get_amis.py#L47-L65

a utility function somewhere in moto so that users who want/need to create their own MOTO_AMIS_PATH can reuse it?  I'm tempted to just copy/paste this tiny bit of code but that makes me 🤮 

Also, are you opposed to documenting MOTO_AMIS_PATH?  I was able to find it looking through the code but I'd be happy to document it as a part of a PR for this if y'all think it is a good idea.

**Comment by bblommers** [comment]
Hi @timsnyder, that is a very good suggestion, both the utility and documenting it.

The utility method would IMO make most sense in `moto/ec2/utils.py`.

Documenting the `MOTO_AMIS_PATH` would make most sense as a docstring of the `EC2Backend`-class here: https://github.com/spulec/moto/blob/master/moto/ec2/models.py#L8603
On release, any docstring will be automatically converted and added to the RTD for that specific service: http://docs.getmoto.org/en/latest/docs/services/ec2.html

A good example of what the RTD docs could look like is AWSLambda: http://docs.getmoto.org/en/latest/docs/services/lambda.html
All that documentation is defined in the `LambdaBackend`-class.

**Comment by timsnyder** [comment]
Thanks @bblommers.  I'll submit a PR shortly.
