### ISSUE TITLE
Is https://hub.docker.com/r/motoserver/moto the official Docker image host for this project?

### ISSUE THREAD

**Issue by hasryan** [spulec/moto#4866]
Please forgive this question if it's obvious, but I'm wondering if https://hub.docker.com/r/motoserver/moto is the official host for images generated for this project?

I didn't find any mention of the Docker Hub link above or the `motoserver/moto` images in the README or on the docs site, and it was only when I used a search engine that I found https://hub.docker.com/r/motoserver/moto . I do see a few issues that reference these images but don't see an official suggestion to use them. That Docker Hub page links back here but I don't know how easy it is to spoof things like that.

I investigated this repository and found that there does appear to be tooling to push these images in the Github Actions configuration. I think the tags in Docker Hub correspond to the Releases here: https://github.com/spulec/moto/actions/workflows/release.yml . It certainly appears that https://hub.docker.com/r/motoserver/moto is a legitimate host for these images but I was being cautious and trying to ensure the digest ID for the version I wanted to use matched the Release action logs, but it seems the Release action does not echo out the digest.

If https://hub.docker.com/r/motoserver/moto is the official location for images generated by this project, I wonder if it would be possible to surface this in the README? And, if possible, to ensure the digest ID assigned for these tagged images in the Docker Hub are output in the Release logs so that it's clear the hashes there match the hashes that were built here.

**Comment by bblommers** [comment]
Hi @hasryan, welcome to Moto!

That is indeed the official host, and where we release to as part of our workflow. I'll mark it as an enhancement to document this better, and track the hashes.

Thank you for raising this!

**Comment by bblommers** [comment]
As of Moto 3.0.4, the digest is automatically added to the Changelog as part of the release process: 
https://github.com/spulec/moto/blob/master/CHANGELOG.md

The documentation page about ServerMode now explicitly says where the image is hosted:
http://docs.getmoto.org/en/latest/docs/server_mode.html#run-using-docker
