### ISSUE TITLE
moto 3.0.4 requires capacity units when billing mode parameter is not inputted

### ISSUE THREAD

**Issue by hayata-yamamoto** [spulec/moto#4872]
## Reporting Bugs

I've faced dynamodb2 `create_table` error. It was 

```
botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the CreateTable operation: One or more parameter values were invalid: ReadCapacityUnits and WriteCapacityUnits must both be specified when BillingMode is PROVISIONED
```

It's seemed to be related to #4849 , I guess. This problem was solved by using moto==3.0.3. Since [AWS API](https://docs.aws.amazon.com/ja_jp/amazondynamodb/latest/APIReference/API_CreateTable.html#API_CreateTable_RequestParameters) and [boto3](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/dynamodb.html#DynamoDB.ServiceResource.create_table) docs declare as this `billing mode` parameter is not required, we hope moto follow this specification again. 

**Reproduction**

Define below test case and execute, then this type of error will occur

```python 
import unittest 
from moto import dynamodb2
import boto3

class SampleTest(unittest.TestCase): 
    mock_dynamodb = mock_dynamodb2()

    def setUp(self) -> None:
        self.dynamodb = boto3.resource("dynamodb")
        self.dynamodb.create_table(
            TableName="users",
            KeySchema=[{"AttributeName": "user_id", "KeyType": "HASH"}],
            AttributeDefinitions=[{"AttributeName": "user_id", "AttributeType": "S"}],
        )
```

**Comment by bblommers** [comment]
Hi @hayata-yamamoto, Moto follows AWS' behaviour here - without the mock, AWS will throw the exact same exception. I've just tested this out with this setup:
```
class SampleTest(unittest.TestCase):

    def create_table(self):
        self.dynamodb = boto3.resource("dynamodb")
        self.dynamodb.create_table(
            TableName="users",
            KeySchema=[{"AttributeName": "user_id", "KeyType": "HASH"}],
            AttributeDefinitions=[{"AttributeName": "user_id", "AttributeType": "S"}],
        )

    @mock_dynamodb2
    def test_mocked(self):
        self.create_table()

    def test_real(self):
        self.create_table()
```

The behaviour between the two tests is the same.

The `SampleTest` that you provided does not mock anything, btw, as the decorator is never explicitly started. 
If you're using unittest-style classes, the best option is to use the class-decorator to ensure all methods are mocked:
```
@mock_dynamodb2
class SampleTest(unittest.TestCase):
    def setUp()
    def test_x():
```

**Comment by hayata-yamamoto** [comment]
@bblommers 
I appreciate your response. as you mentioned, `start` operation was lacked. 

> The behaviour between the two tests is the same.

I've checked the same result on my environment. Well..., this behaviour is exactly mocking AWS. 
Should we use moto==3.0.4 to mock dynamodb precisely? 

If this yes, I'll close this issue. Thanks!

**Comment by bblommers** [comment]
> 
> Should we use moto==3.0.4 to mock dynamodb precisely?
> 
As a general rule, I'd advice to always use the latest version. We are always adding features and validations to match AWS as closely as possible.

3.0.4 doesn't match AWS Dynamo for 100% yet, but it's better than older Moto versions :slightly_smiling_face:

**Comment by hayata-yamamoto** [comment]
OK, I got!
