### ISSUE TITLE
elb: moto returns none instead of throw an exception for bad health check

### ISSUE THREAD

**Issue by gilzellner** [spulec/moto#488]
Boto:

In [24]: health_check = boto.ec2.elb.HealthCheck(target='TP:8080')

In [25]: health_check
Out[25]: HealthCheck:TP:8080

In [26]: lb = conn.create_load_balancer(name='templb',zones=['us-east-1b'], listeners=[[80, 8080, 'http']])

In [27]: lb.configure_health_check(health_check)
BotoServerError: BotoServerError: 400 Bad Request

Moto: 
returns none, doesn't throw exception

**Comment by spulec** [comment]
Fixed with #489
