### ISSUE TITLE
S3 get_object_tagging should return version id

### ISSUE THREAD

**Issue by mdavis-xyz** [spulec/moto#4887]
The `get_object_tagging` call for S3 should return VersionId for versioned buckets, but it is currently omitted.
(For unversioned buckets it should be omitted.)

# MWE

Run this with `if True` to see `moto`'s behavior, and `if False` to see the real AWS behavior.

```
import boto3
from moto import mock_s3
import urllib.parse
import os

bucket = 'mybucket'
key = 'test-tags'

if True:
    mock_s3().start()
    client = boto3.client('s3')
    client.create_bucket(
        Bucket=bucket,
        CreateBucketConfiguration={
            'LocationConstraint': os.getenv('AWS_DEFAULT_REGION', 'ap-southeast-2')
        },
    )
    
    response = client.put_bucket_versioning(
        Bucket=bucket,
        VersioningConfiguration={
            'Status': 'Enabled'
        },
    )

client = boto3.client('s3')
resp = client.put_object(
    Bucket=bucket, 
    Key=key, 
    Body=b"", 
    Tagging=urllib.parse.urlencode({'mytag': 'x'}))
version = resp['VersionId']


resp = client.get_object_tagging(
    Bucket=bucket,
    Key=key,
    VersionId=version
)
assert 'VersionId' in resp
assert resp['VersionId'] == version

resp = client.get_object_tagging(
    Bucket=bucket,
    Key=key
    # not specifying version id
)
assert 'VersionId' in resp
assert resp['VersionId'] == version
```

Expected behavior: Assertions all pass. VersionId is returned in the response to get_object_tagging for versioned buckets (even if not passed as an argument)

**Comment by bblommers** [comment]
Thanks for raising this @mdavis-xyz - marking it as an enhancement to add this field :+1:

**Comment by bblommers** [comment]
What version of Moto are you running, @mdavis-xyz? I've just tried to reproduce this, and the above test case passes for me on the master-branch

**Comment by mdavis-xyz** [comment]
I was using 2.2.16. I've just upgrade to 3.0.4 and it works.
Woops, my fault. I should have checked that before raising the ticket.

**Comment by bblommers** [comment]
No problem @mdavis-xyz  - happy to hear it's fixed!
