### ISSUE TITLE
VPC endpoint not created as part of cloudformation create stack

### ISSUE THREAD

**Issue by kvudathu** [spulec/moto#4897]
Hi, 

I'm using the latest version of moto(3.0.5).

I have a simple cft template that creates GWLB vpc endpoint and subnet given service name, vpcId, az and CIDR block for the subnet. Everything works fine when deploying in AWS. 

With the current moto version, when I use the same template to create these mock resources via cloudformation.create_stack, only subnet is created. 

I know that that GWLB vpc endpoint is a new service by AWS. Since moto already supports ec2.create_vpc_endpoints, I was wondering if y'all are working on adding the feature to create_stack as well or is it bug?

**Comment by bblommers** [comment]
Hi @kvudathu, can you post a minimum CloudFormatation template here?

**Comment by kvudathu** [comment]
[testcft.txt](https://github.com/spulec/moto/files/8166574/testcft.txt)
Here is the base template, I do create mock GWLB and Service name corresponding it (via moto) before calling cloudformation create stack.

**Comment by bblommers** [comment]
Thanks for posting the template @kvudathu - can confirm that this has not been implemented yet. We'll add it to the list.

**Comment by kvudathu** [comment]
@bblommers Thank you so much! When will the next moto version release which includes this commit?

**Comment by bblommers** [comment]
@kvudathu Moto 3.0.6 has just been released :+1:
