### ISSUE TITLE
Invalid instance ID error behaves differently from AWS

### ISSUE THREAD

**Issue by cheshirex** [spulec/moto#4903]
https://github.com/spulec/moto/blob/ea81377cd0ce669dbb01d2141ef6f7e92c9b757d/moto/ec2/exceptions.py#L238

When I terminate more than one non-existent ID in AWS, I get the error:
An error occurred (InvalidInstanceID.NotFound) when calling the TerminateInstances operation: The instance IDs 'i-0f5d8ccc56c69fae4, i-0eecca434287a1a33, i-05a2b7d81718e0678' do not exist

But this error currently only reports a single instance ID at once.

Not a major issue, but the behaviour difference did trip me up at first.

Thanks!

**Comment by bblommers** [comment]
Thanks for raising this @cheshirex :+1:

**Comment by bblommers** [comment]
Hi @cheshirex, what version of Moto are you using?
Against the latest version, I am seeing the correct error message:
`The instance ID '['instance-1', 'i-34f0548abfb5d2a97', 'instance-2']' does not exist`

(Where `i-34f0548abfb5d2a97` is an existing instance ID)

**Comment by cheshirex** [comment]
(Sorry, I missed the notification -- I need to configure my email to not bury github notifications)

Looks like I have a hardcoded older version of localstack, so yes, that's going to be out of date. I'll nitpick here and point out the singular vs plural difference is still there, but I highly doubt that will realistically bother anyone.

Thanks!

**Comment by bblommers** [comment]
> I'll nitpick here and point out the singular vs plural difference is still there, but I highly doubt that will realistically bother anyone.
> 

Very good point - I actually missed that! That's fixed now :+1:
