### ISSUE TITLE
boto.s3.bucket.Bucket.generate_url broken behavior

### ISSUE THREAD

**Issue by zonk1024** [spulec/moto#491]
When making a request to the url generated by `boto.s3.bucket.Bucket.generate_url` the request fails.  I dropped in some print statements, and I can see the following:

```
get_key CALLED: bucket_name=None key_name=u'company.ops.dist/things_staging/manifest.json' version_id=None new key_name=u'company.ops.dist/things_staging/manifest.json'
_key_response CALLED:
    request=<HTTPrettyRequest("", total_headers=6, body_length=0)>
    query={}
    full_url=u'https://s3.amazonaws.com/company.ops.dist/'
    headers={u'status': 200, u'date': 'Mon, 14 Dec 2015 19:50:24 GMT', u'connection': u'close', u'server': u'Python/HTTPretty'}
    method='HEAD'
get_key CALLED: bucket_name=None key_name=u'company.ops.dist/' version_id=None new key_name=u'company.ops.dist/'
```

I'm currently working on a solution, but seems to stem from having two types of valid urls like so:
`full_url=u'https://company.ops.dist.s3.amazonaws.com/things_staging/manifest.json'`
`full_url=u'https://s3.amazonaws.com/company.ops.dist/things_staging/manifest.json?Signature=D02qIYycGRGtUZ9luQ0WJQIipG0%3D&Expires=1450131983&AWSAccess
KeyId=abc'`

The one with the signature is from `generate_url()`.

Please advise?

**Comment by zonk1024** [comment]
It's `parse_key_name(pth)` and `bucket_name_from_url(url)`, which I'm thinking should be bundled into some type of S3Url class.  ??

**Comment by zonk1024** [comment]
More information: http://docs.aws.amazon.com/AmazonS3/latest/dev/VirtualHosting.html

The `bucket_name` and `key_name` parsing should really take into account the requests' host headers, domain, and path.

**Comment by zonk1024** [comment]
I have a potential fix at https://github.com/zonk1024/moto .  Please let me know if I'm off for coding style/whatnot and if/when you want me to submit a pull request.

Thanks.

**Comment by spulec** [comment]
If the tests are working, a PR would certainly be welcome

**Comment by spulec** [comment]
From my current testing of the code, this seems to be working now. Feel free to reopen if you see otherwise.
