### ISSUE TITLE
[BUG] CloudFormation Mock: An error occurred (Unknown) when calling the CreateStack operation: Unknown

### ISSUE THREAD

**Issue by leonardoviveiros** [spulec/moto#4925]
## CloudFormation Mock: An error occurred (Unknown) when calling the CreateStack operation: Unknown

- OS: `Linux 5.13.0-30-generic #33~20.04.1-Ubuntu SMP Mon Feb 7 14:25:10 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
- Python: 3.8
- `moto` installed via pip
- boto3==1.21.14
- botocore==1.24.14
- moto==3.0.7

When running the unit test below, with`@mock_sts` and `@mock_cloudformation`, we encounter an exception.
```python
    cloudformation_client = boto3_session.client('cloudformation', region_name=region)
    cloudformation_client.create_stack(
                StackName='stack',
                TemplateURL='template public accessible in our bucket',
                Parameters=[{
                            'ParameterKey': 'ExternalId',
                            'ParameterValue': '123'
                            }],
                Capabilities=['CAPABILITY_IAM', 'CAPABILITY_NAMED_IAM'],
            )
```
This exception happens:
```
  File "/home/myuser/dev/mysdk-sdk-python/mysdksdk/client.py", line 1537, in _deploy_cloudformation_mysdk_service_role
    cloudformation_client.create_stack(
  File "/home/myuser/.local/share/virtualenvs/mysdk-sdk-python-1KRJ608P/lib/python3.8/site-packages/botocore/client.py", line 395, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/myuser/.local/share/virtualenvs/mysdk-sdk-python-1KRJ608P/lib/python3.8/site-packages/botocore/client.py", line 725, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (Unknown) when calling the CreateStack operation: Unknown

```

If we change the code, to instead of receiving TemplateURL='template public accessible in our bucket', pass the same content on TemplateBody='', the error don't happen.

Is there any way to workaround this?

**Comment by bblommers** [comment]
Hi @leonardoviveiros, Moto mocks all AWS requests. Even if you do not explicitly want to mock S3, it should still not connect to AWS' S3, to avoid any mistakes.

What happens if you add `mock_s3` as well, and upload the template to S3 as part of you test setup?

**Comment by leonardoviveiros** [comment]
@bblommers that's a great workaround and it actually fixed it. Thanks for the fast response.

Now I can use the normal s3 template URL, and I'm creating the S3 bucket using moto

```
  s3 = boto3.client('s3', region_name='us-east-2')
  s3.create_bucket(Bucket='tenchi-assets', CreateBucketConfiguration={'LocationConstraint': 'us-east-2'})
  s3.put_object(Bucket='my-assets', Key='my-service-role.template', Body=json.dumps(DUMMY_TEMPLATE))
```

And then I can proceed with my testing without changing my code.


I tried to workaround this before your answer and succeeded by changing the code to use TemplateBody, but then I ended up with bigger complexity to fetch the template and then pass its content to cloudformation. The solution you proposed is way better IMHO.

You can close it you you won't change the way it works with cloudformation+s3.

**Comment by leonardoviveiros** [comment]
@bblommers that's a great workaround and it actually fixed it. Thanks for the fast response.

Now I can use the normal s3 template URL, and I'm creating the S3 bucket using moto

```
  s3 = boto3.client('s3', region_name='us-east-2')
  s3.create_bucket(Bucket='my-assets', CreateBucketConfiguration={'LocationConstraint': 'us-east-2'})
  s3.put_object(Bucket='my-assets', Key='my-service-role.template', Body=json.dumps(DUMMY_TEMPLATE))
```

And then I can proceed with my testing without changing my code.


I tried to workaround this before your answer and succeeded by changing the code to use TemplateBody, but then I ended up with bigger complexity to fetch the template and then pass its content to cloudformation. The solution you proposed is way better IMHO.

You can close it you you won't change the way it works with cloudformation+s3.

**Comment by bblommers** [comment]
It's a feature @leonardoviveiros, not a bug :slightly_smiling_face: 

Happy to hear this now works!
