### ISSUE TITLE
No longer possible to mock out models

### ISSUE THREAD

**Issue by cachedout** [spulec/moto#493]
I should preface by saying this by admitting that I certainly know that this is by no means supported behavior and so it's not a bug in the classical sense. It is, however, a fairly reasonable use case and so I'm giving it here as an illustration of what I think should be supported in some other way.

We have a need to test failure handling for various EC2 functions. i.e., do we correctly handle a `BotoServerError` that might be returned. Therefore, we construct a number of tests that are roughly as follows:

```
   @mock_ec2
    def test_present_with_failure(self):
        with patch('moto.ec2.models.VPCBackend.create_vpc', side_effect=BotoServerError(400, 'Mocked error')):
            vpc_present_result = <do some boto things with our wrappers on top>
            self.assertFalse(vpc_present_result['result'])
            self.assertTrue('Mocked error' in vpc_present_result['comment'])
```

It used to be the case where this worked wonderfully. With the most recent release of moto, however, this no longer works. What's returned now is something akin to the following:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/site-packages/httpretty/core.py", line 637, in fill_filekind
    headers
  File "/usr/lib/python2.7/site-packages/moto/core/responses.py", line 95, in dispatch
    return cls()._dispatch(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/moto/core/responses.py", line 136, in _dispatch
    return self.call_action()
  File "/usr/lib/python2.7/site-packages/moto/core/responses.py", line 152, in call_action
    response = method()
  File "/usr/lib/python2.7/site-packages/moto/ec2/responses/vpcs.py", line 9, in create_vpc
    vpc = self.ec2_backend.create_vpc(cidr_block)
  File "/usr/lib/python2.7/site-packages/mock/mock.py", line 1062, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/mock/mock.py", line 1118, in _mock_call
    raise effect
BotoServerError: BotoServerError: 400 Mocked error
```

Again, I totally understand this isn't supported behavior but I have two questions:

1) Is it possible to accomplish this using recognized techniques with moto?

2) If not, can this be implemented?

**Comment by thedrow** [comment]
You need to modify the tests to assert that an exception is raised with the provided message.

**Comment by cachedout** [comment]
This is certainly possible but it ends up mitigating the functionality that I'm actually trying to test for. That said, it may be close enough to at least approximate the desired behavior. I'll give it a try and see if I can get that to work. Thanks, @thedrow

**Comment by thedrow** [comment]
I think I wrote those tests btw so if you need any help let me know.

**Comment by cachedout** [comment]
@thedrow Many thanks. I won't be able to look at this again for a while, so if you're feeling up to it, don't wait for me. I'll hopefully be able to come back to it in a couple weeks.

**Comment by spulec** [comment]
Agreed that modifying the tests is going to be the best way to go. Our goal is to make Moto more closely resemble real AWS. Feel free to reopen if more questions.
