### ISSUE TITLE
Unable to contribute / ERROR: Permission to spulec/moto.git denied

### ISSUE THREAD

**Issue by AlanDonohoe** [spulec/moto#4955]
Hello 👋

I am working on adding support for [Rekognition](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/rekognition.html).

But when I try and push my branch to moto's repo, I get this error:
```
ERROR: Permission to spulec/moto.git denied to MY HANDLE...
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Settings seem to be OK on my side:

```
git remote -v
origin  git@github.com:spulec/moto.git (fetch)
origin  git@github.com:spulec/moto.git (push)
```

Am I missing something?

Any ideas?

Thank you.

**Comment by bblommers** [comment]
Hi @AlanDonohoe! This can be solved  by creating a copy of Moto's repo, using the `Fork`-button in the topright corner of https://github.com/spulec/moto.

After checking our your own copy/fork, you can create feature-branches there - and then create a PR from your branch into `spulec/moto/master`.

Let me know if you run into any issues with that.

**Comment by AlanDonohoe** [comment]
Hi @bblommers Fantastic, thank you!
