### ISSUE TITLE
EKS CreateCluster response encryptionConfig property should be a List/Array

### ISSUE THREAD

**Issue by scottaubrey** [spulec/moto#4979]
# Description

When using moto server, the `CreateCluster` EKS API, the Cluster response object should contain `encryptionConfig` as a List of at-most-one `EncryptionConfig` maps/objects  (as per example here: https://docs.aws.amazon.com/eks/latest/APIReference/API_CreateCluster.html#API_CreateCluster_ResponseSyntax and documented [here](https://docs.aws.amazon.com/eks/latest/APIReference/API_Cluster.html#AmazonEKS-Type-Cluster-encryptionConfig) and [here](https://docs.aws.amazon.com/eks/latest/APIReference/API_EncryptionConfig.html)). Moto returns just a map/object.

The issue causes an error for me when using the terraform AWS provider to create a cluster without encryption_config set - terraform attempts to retry because response marshalling failed, then reports the cluster already exists. The incorrect response is the same no matter which client makes the request though (see aws-cli below), it's a matter of how strictly it matches the documented response and how it behaves when it doesn't match.

### How to reproduce the issue

Start the motoserver v3.1.3 (latest at reporting time) in docker:
```
docker run --rm -d --name moto-bug-test -p 5000:5000 motoserver/moto:3.1.3 
```

Create basic IAM role:
```
aws --region=us-east-1 --endpoint-url=http://localhost:5000 iam create-role \
          --role-name test-cluster \
          --assume-role-policy-document '{"Version": "2012-10-17", "Statement": [{"Action": "sts:AssumeRole", "Effect": "Allow", "Principal": {"Service": "eks.amazonaws.com"}}]}'
```

Run create-cluster with just enough setup and `--debug` to show server responses.
``` 
aws --debug --region=us-east-1 --endpoint-url=http://localhost:5000 eks create-cluster \
          --name test \
          --role-arn $(aws --region=us-east-1  --endpoint-url=http://localhost:5000 iam get-role --role-name test-cluster | jq -r .Role.Arn) \
          --resources-vpc-config "subnetIds=$(aws --region=us-east-1 --endpoint-url=http://localhost:5000 ec2  describe-security-groups |  jq -r '.SecurityGroups[0].GroupId')" 2>&1 | grep -A1 'DEBUG - Response body' | tail -n1 | sed "s/b'//" | sed "s/'//" | jq .cluster.encryptionConfig
```

NOTE: I'm parsing the debug logs here, because the aws client output actually seem to massage the '{}' response from moto to a '[]' before displaying it.

### What I expected to happen

`clusterConfig` should be '[]'

### what actually happens

`clusterConfig` is '{}'

**Comment by bblommers** [comment]
Thanks for raising this @scottaubrey!
