### ISSUE TITLE
When creating ec2 instances from launch template via run_instances, the instances aren't tagged

### ISSUE THREAD

**Issue by dkatzbuc** [spulec/moto#4987]
I'm using moto in pytest. I have created a launch template using `create_launch_template`. This template is created with `TagSpecifications` for instance and volume.

Upon using `run_instances` to create new instances based on this launch template, their tags are empty. Is this to be expected?

**Comment by bblommers** [comment]
Hi @dkatzbuc, thanks for raising this - doesn't look like this behaviour is implemented yet. Marking it as an enhancement.
