### ISSUE TITLE
elbv2 describe_tags return ResourceArn empty instead of the correct one

### ISSUE THREAD

**Issue by linhmeobeo** [spulec/moto#4988]
## Reporting Bugs

I am using the latest version of moto for elbv2. After create_load_balancer with moto, which return resource 'LoadBalancerArn': 'arn:aws:elasticloadbalancing:us-east-1:123456789012:loadbalancer/app/loadbalancer/50dc6c495c0c9188'
I ran describe_load_balancers() which returned correct resource,. But when I did describe_tags (ResourceArns =<list of ARN from describe_load_balancers), it returned something similar to this:
{'TagDescriptions': [{'ResourceArn': '', 'Tags': [{'Key': 'aaa', 'Value': ''}]}, {'ResourceArn': '', 'Tags': [{'Key': 'bbb', 'Value': ''}, ..}
So 'ResourceArn': '' is returned, instead of the correct ResourceArn.
With this, my test suddenly failed. It was succeed before the change.

**Comment by bblommers** [comment]
Thanks for letting us know @linhmeobeo - will raise a PR to fix this shortly
