### ISSUE TITLE
NotImplementedError: The update_user_attributes action has not been implemented

### ISSUE THREAD

**Issue by deanq** [spulec/moto#5001]
The documentation shows this function as available and useful for updating current user's attributes without using the `admin_ update_user_attributes` counterpart. But when invoked, this error comes up. Could the documentation be updated to reflect this status?

**Comment by deanq** [comment]
Ugh. I thought I was posting on boto's github. Sorry.

**Comment by bblommers** [comment]
It looks like you're in the right place @deanq - not all services/features are supported yet in Moto, and that is the generic error used in Moto when a method is not yet supported.
(The full list of what we do support can be found here: http://docs.getmoto.org/en/latest/docs/services/cognito-idp.html)

I'll mark this as an enhancement. PR's are always welcome, if you'd like to contribute!
