### ISSUE TITLE
Not able to trigger lambda function using s3 ObjectCreated Event

### ISSUE THREAD

**Issue by gyuvaraj10** [spulec/moto#5002]
Not able to trigger lambda function using s3 ObjectCreated Event

1. I have created an s3 bucket within moto server with the following notification
{
    "LambdaFunctionConfigurations": [
        {
            "Id": "s3eventtriggerslambda",
            "LambdaFunctionArn": "arn:aws:lambda:eu-west-1:000000000000:function:test-lambda",
            "Events": ["s3:ObjectCreated:*"]
        }
    ]
}
2. I have created a lambda that reads the created objects.
3. I uploaded a file to s3 bucket and verified moto dashboard logs to check if the lambda invocation happened but see that the lambda was not invoked.

**Comment by bblommers** [comment]
Hi @gyuvaraj10, welcome to Moto! The S3-triggering functionality is indeed not yet implemented. There is already an outstanding issue for this though, #1541, so I'll close this as a duplicate.

**Comment by gyuvaraj10** [comment]
Is this automated triggering functionality not available only with S3 and SQS ? or the automated functionality itself not available with Moto?

**Comment by bblommers** [comment]
None of it is implemented at the moment. We persist the notification configuration, but we don't do anything with it.

**Comment by bblommers** [comment]
@gyuvaraj10 FYI:

A first iteration of this is now available as of moto >= 3.1.5.dev7.
We currently only support targets AWSLambda and SQS, for events s3:ObjectCreated:Copy and s3:ObjectCreated:Put.

An up-to-date list of what's supported can be found here: http://docs.getmoto.org/en/latest/docs/services/s3.html

Feel free to open a new issue/PR if there is a another target or event that you'd like to see support for!
