### ISSUE TITLE
Moto error

### ISSUE THREAD

**Issue by kaladurga** [spulec/moto#5018]
I'm facing the issue when running unittest cases in python

cls = <class 'jinja2.environment.Template'>, args = ()

    def __newobj__(cls, *args):
>       return cls.__new__(cls, *args)
E       TypeError: __new__() missing 1 required positional argument: 'source'

/usr/local/lib/python3.9/copyreg.py:95: TypeError

updated to moto 3.1.4 version still facing same issue

**Comment by bblommers** [comment]
Hi @kaladurga, do you have small reproducible example for your test case? Can you share the other dependencies used in this project, particularly the version of `responses`?

**Comment by kaladurga** [comment]
No I haven't used the responses vesrion

**Comment by kaladurga** [comment]
These are the dependencies which I have used 
moto 2.3.0
mock
unittest2 1.1.0
pytest 6.0.0

**Comment by bblommers** [comment]
`responses` is a dependency from Moto, so it will be installed. We'll also still need a test case, something reproducible that will always throw this error.

**Comment by bblommers** [comment]
Closing this - there's not much we can do without something reproducible.
