### ISSUE TITLE
Moto missing new EC2 Subnet attribute "Ipv6Native"

### ISSUE THREAD

**Issue by davidaah** [spulec/moto#5021]
The EC2 Subnet data model was updated to support the launch of IPv6-only subnets as seen in the `Response Syntax` here: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2.html#EC2.Client.describe_subnets

As part of this release a new attribute was added to indicate that a subnet is IPv6 only.

While it would be nice to add full support for ipv6 only subnets to moto over time, in the short term it would be great if the relevant describe responses included this new attribute with value set to False

**Comment by bblommers** [comment]
Hi @davidaah, thanks for raising this - will mark it as an enhancement.

If you want to contribute this to Moto, PR's are always welcome!
