### ISSUE TITLE
EnabledCloudwatchLogsExports Rds Functionality Gap

### ISSUE THREAD

**Issue by kevho48** [spulec/moto#5026]
Mocking the RDS inputs for `EnabledCloudwatchLogsExports` does nothing because support for this is missing in 
https://github.com/spulec/moto/blob/master/moto/rds/responses.py

Currently using the latest version of Moto (3.1.5.dev4)

**Comment by bblommers** [comment]
Hi @kevho48, thanks for raising this - will mark it as an enhancement.

Just to clarify - do you only need this field to show up in the response, or do you also want the actual logs to show up in CloudWatch? Both are possible, of course, but the first would be easier to implement for whoever picks this up.
