### ISSUE TITLE
CognitoIDP: The global_sign_out action has not been implemented

### ISSUE THREAD

**Issue by farmankazmieshaafi** [spulec/moto#5047]
self = <moto.cognitoidp.responses.CognitoIdpResponse object at 0x000002058799AA60>

    def call_action(self):
        headers = self.response_headers

        try:
            self._authenticate_and_authorize_normal_action()
        except HTTPException as http_error:
            response = http_error.description, dict(status=http_error.code)
            return self._send_response(headers, response)

        action = camelcase_to_underscores(self._get_action())
        method_names = method_names_from_class(self.__class__)
        if action in method_names:
            method = getattr(self, action)
            try:
                response = method()
            except HTTPException as http_error:
                response_headers = dict(http_error.get_headers() or [])
                response_headers["status"] = http_error.code
                response = http_error.description, response_headers

            if isinstance(response, str):
                return 200, headers, response
            else:
                return self._send_response(headers, response)

        if not action:
            return 404, headers, ""

>       raise NotImplementedError(

**Comment by bblommers** [comment]
Thanks for raising this @farmankazmieshaafi - will mark it as an enhancement to add this feature!
