### ISSUE TITLE
Unable to check if s3 prefix exists

### ISSUE THREAD

**Issue by JavierLopezT** [spulec/moto#5053]
I am trying to check if a s3 prefix exists. My code so far is:

```
    from moto import mock_s3
    
    mock_s3().start()
    import boto3
    S3_BUCKET = "bucket_name"
    S3_PREFIX = "signal/.hoodie"
    
    s3 = boto3.client("s3", region_name="us-east-1")
    s3.create_bucket(Bucket=S3_BUCKET)
    s3_mock_body_value = "1".encode()
    s3.put_object(Bucket=S3_BUCKET, Key=f"{S3_PREFIX}/1.commit", Body=s3_mock_body_value)
    
    if 'Contents' in s3.list_objects_v2(Bucket=S3_BUCKET, Prefix=S3_PREFIX):
        print(True)
    else:
        print(False)
```

I always get False because the response from `list_objects_v2` is

  ```
  {'ResponseMetadata': {'RequestId': 'O1P49EN9PP88YMLMN4DJFWUOML67GIM079RZUTXDTDM84DFSLZM2',
      'HTTPStatusCode': 200,
      'HTTPHeaders': {'x-amzn-requestid': 'O1P49EN9PP88YMLMN4DJFWUOML67GIM079RZUTXDTDM84DFSLZM2'},
      'RetryAttempts': 0},
     'IsTruncated': False,
     'Name': 'bucket_name',
     'Prefix': 'signal/.hoodie/',
     'MaxKeys': 1000,
     'KeyCount': 0}
```
Same problem with `boto3.resource('s3').Bucket(S3_BUCKET).objects.filter(Prefix=S3_PREFIX)`. I can't check on the `HTTPStatusCode` because even if the key has not been created previously, I get a 200 code. I can't use the boto3 function `get_object_head()` because within the folder there is an arbitrary amount of files and I don't know their names.

Any solution?

**Comment by bblommers** [comment]
Hi @JavierLopezT, which version of Moto are you on? I can't reproduce this, unfortunately - using your example, the key is always returned for me.

For reference, these are our internal unit tests using the Prefix-argument, and they all return the correct data as far as I can tell:

https://github.com/spulec/moto/blob/96996b6b4673f5673478758571c296a2a65c9eb0/tests/test_s3/test_s3.py#L463

https://github.com/spulec/moto/blob/96996b6b4673f5673478758571c296a2a65c9eb0/tests/test_s3/test_s3.py#L1113

**Comment by JavierLopezT** [comment]
> 

Thanks for replying. I am using moto 3.1.5

**Comment by bblommers** [comment]
I've created a small project to reproduce this here:
https://github.com/bblommers/moto-s3-list-objects/blob/main/test/test_s3.py

The CI configuration, that just installs Moto and executes the one test:
https://github.com/bblommers/moto-s3-list-objects/blob/main/.github/workflows/test.yml

The test result can be found here, where you can see the `Contents`-key is indeed returned:
https://github.com/bblommers/moto-s3-list-objects/runs/6149389015?check_suite_focus=true

**Comment by JavierLopezT** [comment]
Thank you very much for your time. I guess I had a typo/error somewhere because indeed your code works perfectly. Now I know where to look at if I have more doubts before asking. Thank you very much again and have a nice day
