### ISSUE TITLE
Moto mock_all raises TypeError

### ISSUE THREAD

**Issue by valentin994** [spulec/moto#5061]
When runing python -m pytest:
```py
@mock_all  
def test_foo(): 
  assert 1 == 1
```
E   TypeError: __init__() takes 1 positional argument but 2 were given

List of packages installed:

- anyio                 3.5.0
- attrs                 21.4.0
- aws-lambda-powertools 1.25.9
- aws-xray-sdk          2.9.0
- awscli                1.23.0
- biopython             1.79
- boto3                 1.22.0
- botocore              1.25.0
- certifi               2021.10.8
- cffi                  1.15.0
- charset-normalizer    2.0.12
- colorama              0.4.4
- coverage              6.3.2
- cryptography          36.0.2
- dnspython             2.2.1
- docutils              0.15.2
- email-validator       1.2.0
- fastapi               0.75.2
- fastjsonschema        2.15.3
- future                0.18.2
- h11                   0.12.0
- httpcore              0.14.7
- httpx                 0.22.0
- idna                  3.3
- iniconfig             1.1.1
- Jinja2                3.1.1
- jmespath              1.0.0
- mangum                0.15.0
- MarkupSafe            2.1.1
- moto                  3.1.6
- numpy                 1.22.3
- packaging             21.3
- pip                   22.0.4
- pluggy                1.0.0
- py                    1.11.0
- pyasn1                0.4.8
- pycparser             2.21
- pydantic              1.9.0
- pyparsing             3.0.8
- pytest                7.1.2
- pytest-cov            3.0.0
- pytest-mock           3.7.0
- python-dateutil       2.8.2
- python-multipart      0.0.5
- pytz                  2022.1
- PyYAML                5.4.1
- requests              2.27.1
- responses             0.20.0
- rfc3986               1.5.0
- rsa                   4.7.2
- s3transfer            0.5.2
- setuptools            62.1.0
- six                   1.16.0
- sniffio               1.2.0
- starlette             0.17.1
- tomli                 2.0.1
- typing_extensions     4.2.0
- urllib3               1.26.9
- Werkzeug              2.1.1
- wrapt                 1.14.0
- xmltodict             0.12.0

**Comment by valentin994** [comment]
closing, i forgot to brackets on it.

**Comment by Lilja** [comment]
Is this the intended usage? As the documentation states:

http://docs.getmoto.org/en/latest/docs/services/index.html?highlight=multiple#implemented-services

```python3
@mock_all
def test_all_supported_services_at_the_same_time():
    ...
```

fyi @bblommers

**Comment by bblommers** [comment]
Good catch @Lilja - the parentheses should indeed be there. I've updated the docs to reflect this.
