### ISSUE TITLE
Upgrade flake8 to allow type-ignore comments

### ISSUE THREAD

**Issue by iainelder** [spulec/moto#5062]
Can we upgrade flake8 to the latest version? That's 4.0.1 at the time of writing.

We need to upgrade for compatibility with the mypy static type checker. Mypy's use was approved in #4944.

Mypy supports the use of [control comments](https://mypy.readthedocs.io/en/stable/common_issues.html#spurious-errors-and-locally-silencing-the-checker) to silence type errors.

In my [organizations-fixes](https://github.com/iainelder/moto/tree/organizations-fixes) branch I'm experimenting with adding types to the organizations models. I've added some control comments where the types are not strictly correct and I don't want to fix it yet.

An example from OrganizationsBackend:

```python
    def create_organizational_unit(self, **kwargs: Any) -> ot.CreateOrganizationalUnitResponseTypeDef:
        # TODO: Arg type needs to be FakeOrganization, but it can sometimes be None.
        new_ou = FakeOrganizationalUnit(self.org, **kwargs)  # type: ignore[arg-type]
        self.ou.append(new_ou)
        self.attach_policy(PolicyId=utils.DEFAULT_POLICY_ID, TargetId=new_ou.id)
        return {"OrganizationalUnit": new_ou.describe()}
```

flake8, well, "flakes out" at this:

```
moto/organizations/models.py:418:62: F821 undefined name 'ignore'
moto/organizations/models.py:418:62: F821 undefined name 'arg'
```

In requirements-dev.txt flake8 is pinned to 3.7.8.

That [version of flake8](https://github.com/PyCQA/flake8/blob/3.7.8/setup.cfg#L16) depends on pyflakes:

```text
    pyflakes >= 2.1.0, < 2.2.0
```

In my virtualenv it resolves pyflakes to v2.1.1.

That version of pyflakes is incompatible with mypy's control comments to ignore type errors.

This was fixed in [pyflakes 2.2.0](https://github.com/PyCQA/pyflakes/blob/2.2.0/NEWS.rst).

> * Allow type ignore to be followed by a code `# type: ignore[attr-defined]`

flake8 v4.0.1 generates about 60 linting errors on the moto code. If we upgrade flake8, those will have to be addressed as well.

**Comment by bblommers** [comment]
Make sense @iainelder. I'll create a PR that fixes the linting issues on the new flake8.

**Comment by iainelder** [comment]
Thanks for the quick resolution! I'll check how mypy works soon and confirm.

**Comment by iainelder** [comment]
Now flake8 plays nicely with mypy's type-ignore comments. Thanks!
