### ISSUE TITLE
Not throwing error when describing an image that has been deleted recently breaks boto3

### ISSUE THREAD

**Issue by ianw** [spulec/moto#5067]
Hello,

We have some CI that has started failing and I've tracked it down to https://github.com/spulec/moto/commit/752eee1941de3214eea01d9649f33456aedf097c#diff-9dba1b3c572ca75c4c0f539c78301a8c8300e8b42825d4e4286b95eb99827944R229

The code that broke is roughly

```python
self.ec2 = boto3.resource('ec2', region_name='us-west-2')
# skip lots
image = self.ec2.Image(image_id)
try:
    if image.state == 'deleted':
        break
    except botocore.exceptions.ClientError:
        # Probably not found
         break
```

After https://github.com/spulec/moto/commit/752eee1941de3214eea01d9649f33456aedf097c# this has started failing with

```
Traceback (most recent call last):
  File "/home/zuul/src/opendev.org/zuul/nodepool/nodepool/tests/unit/test_driver_aws.py", line 490, in test_aws_resource_cleanup
    if image.state == 'deleted':
  File "/home/zuul/src/opendev.org/zuul/nodepool/.tox/py38/lib/python3.8/site-packages/boto3/resources/factory.py", line 386, in property_loader
    return self.meta.data.get(name)
AttributeError: 'NoneType' object has no attribute 'get'
```

I have traced it down to the changes in ```moto/ec2/_models/amis.py``` there, and reverting to raise an exception again fixes the jobs.

This error comes from boto3 @ https://github.com/boto/boto3/blob/cb464294ee8b787e78af0e3ee92a86d43951b52a/boto3/resources/factory.py#L386

To say I'm not familiar with the details of boto call wrapping is an understatement, but I can see that ```image.state``` calls into ```self.load()``` in ```boto3``` code that does

```python
        def property_loader(self):
            if self.meta.data is None:
                if hasattr(self, 'load'):
                    self.load()
                else:
                    raise ResourceLoadException(
                        f'{self.__class__.__name__} has no load method'
                    )

            return self.meta.data.get(name)
```

I believe that this ```self.load()``` to try and populate the data then ends up in ```moto/ec2/_models/amis.py``` and ultimately this sends back a [DescribeImagesReponse] (https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeImages.html) via the function https://github.com/spulec/moto/blob/d12254309d8c50b13713ba6282419f6e8b6a252e/moto/ec2/responses/amis.py#L39 

I traced it's blank return:

```xml
<DescribeImagesResponse xmlns="http://ec2.amazonaws.com/doc/2013-10-15/"><requestId>59dbff89-35bd-4eac-99ed-be587EXAMPLE</requestId><imagesSet></imagesSet></DescribeImagesResponse>
```

So previously this would raise an exception, which we would catch and continue on.  Now I have a object that I can't seem to do much with -- trying to access any property results in the ```AttributeError``` as ```boto``` seems to assume it has loaded something?

The change says

> Don't throw an error when describing an image that has been deleted recently (behaviour confirmed against AWS)

I don't really have much more context than that, and I'm really not sure what the correct path is here.  I feel like maybe this is a consistency issue with ```moto``` in that the deleted images should continue to be filled out in the response with a "deleted" state?  Or perhaps the prior behaviour was actually more correct, in that deleted images have disappeared and should raise an error?

I am trying to extract this into something smaller.  It is all open source, the actual code hitting this is https://opendev.org/zuul/nodepool/src/commit/dae31ef620827f3841c669dd986ab8672bbc2bc3/nodepool/tests/unit/test_driver_aws.py#L490 and a sample failure is at https://zuul.opendev.org/t/zuul/build/e141fb7802564ba790783d227db5648b/ (Artifacts->Unit Test Report)

**Comment by bblommers** [comment]
Hi @ianw, thanks for raising this! 

To give some background here, this functionality was tested by taking the following steps in AWS:
 - Copy a public AMI
 - Delete that AMI
 - Try to describe the AMI

Describing the recently deleted AMI acts exactly as you described - it returns `None`

For reference, this is a test case in boto3 that I've just created, that shows this behaviour:
```
def test_image_deletion():
    ec2 = boto3.resource('ec2', region_name='us-east-1')
    ec2_client = boto3.client('ec2', region_name='us-east-1')
    # A public Amazon image
    original_image = "ami-08c954b5b118f85d1"

    dest_image_id = ec2_client.copy_image(Name="testcopy", SourceImageId=original_image, SourceRegion="us-east-1")["ImageId"]

    image = ec2.Image(dest_image_id)
    print(image)
    print(image.state)

    image.deregister()
    try:
        print(image)
        print(image.state)
    except AttributeError:
        print("We do not know the image state - it is None")
        print(image)

    resp = ec2_client.describe_images(ImageIds=[dest_image_id])
    print(resp)

    snapshot = ec2_client.describe_snapshots(
        Filters=[
            {
                'Name': 'description',
                'Values': [
                    f'Copied for DestinationAmi {dest_image_id}*',
                ]
            },
        ])["Snapshots"][0]
    ec2_client.delete_snapshot(SnapshotId=snapshot["SnapshotId"])
```

If you run this against AWS, you'll notice that `describe_images` returns an empty list.

There is an inconsistency in how AWS behaves there, that may have caught you out:

 - Describing an unknown image throws an error
 - Describing a recently deleted (<48hours) image returns nothing
 - Describing an image deleted long ago (>5 days) throws an error, ImageNotFound

When testing this, I've never ran into a response from AWS where `image.state == 'deleted'`. If you do have a reproducible test case where this happens, I'd be happy to see it - maybe there are some subtleties in how AWS behaves that I've missed.

**Comment by ianw** [comment]
Thanks for those detailed notes.  I feel like the ```AttributeError``` from boto is more oversight than a planned response to this situation, but of course this isn't moto's fault.  But thank you, as it validates catching this exception is the right thing to do.

The ```image.state == 'deleted'``` came in via https://review.opendev.org/c/zuul/nodepool/+/830527/3/nodepool/tests/unit/test_driver_aws.py

I will try to see if @jeblair has insight into where that came from and if it was seen in a tracing session.

**Comment by jeblair** [comment]
I ran a test with a snapshot from an image upload (which is what our system is doing) and am also unable to produce a `deleted` result.  I think we should assume that is an error.

**Comment by ianw** [comment]
Thank you both for the helpful feedback.

I kept investigating, and I think that https://github.com/boto/boto3/issues/2531 describes this issue on the boto3 side.  It seems right now we just need to catch the AttributeError.
