### ISSUE TITLE
Unable deploy AWS API Gateway v2 in server mode

### ISSUE THREAD

**Issue by dickensas** [spulec/moto#5069]
I am using moto in server mode deploy lambda, s3, apigatewayv2 
```
moto_server
 * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
```
I am using terraform CDKTF to create the stage code in tyhpescript
http://localhost:5000/restapis/axl0ydav4s/mylambda/_user_request_/sayhello
how can I invoke the URL in this format ?

**Comment by bblommers** [comment]
Hi @dickensas, are you unable to deploy this, or do you make a HTTP request to the mocked gateway?

The latter is not yet supported for APIGatewayv2. I'll mark it as an enhancement, but this would be quite an undertaking, so it would take a while before this is implemented.

Have you looked into LocalStack? Their functionality is similar to Moto, but with much better integration between APIGateway and Lambda. The downside is that is much more resource-heavy, but if the integration is absolutely necessary, that may be a good alternative.
https://docs.localstack.cloud/aws/apigatewayv2/

**Comment by dickensas** [comment]
Hi
I went through API Gateway V2 in localstack, it is only available in pro version.

So as per your comment if it is not implemented yet, that answers my question

But if it cannot be invoked vi URL, is it possible to invoke via python or any other language? I don't want to invoke the lamba but I want to invoke the api gateway via code so that my testing will be completed without skipping the API gateway

**Comment by bblommers** [comment]
> Hi I went through API Gateway V2 in localstack, it is only available in pro version.
> 

Ah, my bad, I didn't realize that.

> But if it cannot be invoked vi URL, is it possible to invoke via python or any other language? I don't want to invoke the lamba but I want to invoke the api gateway via code so that my testing will be completed without skipping the API gateway

No, that's not possible at all at the moment. The only way to test the gateway is via [the implemented boto3-methods](https://github.com/spulec/moto/blob/master/IMPLEMENTATION_COVERAGE.md).

**Comment by dickensas** [comment]
Great may be I will put effort and implement it for you as a contribution
