### ISSUE TITLE
Feature Request: EMR Serverless

### ISSUE THREAD

**Issue by dacort** [spulec/moto#5071]
Hi, AWS employee here! 👋 

[EMR Serverless](https://docs.aws.amazon.com/emr/latest/EMR-Serverless-UserGuide/emr-serverless.html) is a new deployment option for EMR, currently in preview. It'd be great to get coverage for some of the API actions [listed here](https://docs.aws.amazon.com/emr-serverless/latest/APIReference/API_Operations.html) including starting/stopping applications, and actions around job runs.

I'll likely start working on a PR soon. I do have one question: Since the service is in preview, and thus the models are not available in boto yet, will that be problematic?

**Comment by bblommers** [comment]
Hi @dacort, welcome to Moto! Support for new services is always welcome - great to hear that you want to contribute here.

My usual advice when starting a completely new service is to use our scaffold-script - but considering that creates a template based on data coming from `boto`, that will not help you.

We do already have support for [EMRContainers](https://github.com/spulec/moto/tree/master/moto/emrcontainers), so you could use that as a template.

The biggest issue I can see is around testing - all our functionality is covered by boto3-tests, so writing those will not be possible until the service comes available.

Let me know if you have any questions on how to get started - happy to help out.

**Comment by dacort** [comment]
Thanks @bblommers!

Thankfully, we are providing a model file during the preview and looks like Moto picks it up just fine! 
![image](https://user-images.githubusercontent.com/1512/165641897-4880d5b7-7053-476f-b062-c477ab9a61c0.png)

So looks like I can at least get started locally and get that PR button ready.

**Comment by andormarkus** [comment]
@dacort Do you want to finish [your branch](https://github.com/dacort/moto/tree/feature/emr-serverless) or can I pick it up and continue? Testing since boto3 1.24.0 release should not be a problem.

**Comment by dacort** [comment]
Hey @andormarkus! If you have time within the next week to pick it up, go for it! I probably won't be able to work on this again until the middle of June. All my changes are current on that branch. :)

**Comment by andormarkus** [comment]
Hi @dacort 

I have refactored the `*_application` methods and make than work. Only `update_application` method remains for tomorrow. 
Tomorrow I will submit the first PR which will cover all of the `application` methods and start to work on the `job` methods.
