### ISSUE TITLE
Add SES v2 coverage docs

### ISSUE THREAD

**Issue by mdavis-xyz** [spulec/moto#5075]
Amazon released AWS SES v2 [earlier this week](https://aws.amazon.com/about-aws/whats-new/2022/04/amazon-ses-v2-supports-email-size-40mb-inbound-outbound-emails-default/). In boto3 this appears as `boto3.client('sesv2')`.

The moto implementation coverage does not mention it yet. Please update the coverage doc to say it is not covered.

Of course it would be good if the functionality was added to moto so that it is covered. But that's a big deal. I'll raise another ticket for that.

**Comment by bblommers** [comment]
Thanks for raising this. We'll  update the implementation doc on our next release, potentially this weekend.

**Comment by bblommers** [comment]
This is actually already covered - the [implementation coverage document](https://github.com/spulec/moto/blob/master/IMPLEMENTATION_COVERAGE.md) has an `Unimplemented`-section at the bottom that lists SESv2.

I agree that it's quite hidden - but considering the length of services that we do not cover, I dont' know whether there's a better way to represent this - happy to hear any suggestions around this. I'll close this in the mean time.

**Comment by mdavis-xyz** [comment]
Ah, I see. For implemented services the service name is the section name. For unimplemented services the string `ses` is *inside* the collapsed section. So when I searched for `ses` with ctrl-f, my browser skipped over it. (I didn't realise that was the behavior of ctrl-f in Firefox.)
