### ISSUE TITLE
Add cloudwatch logs support

### ISSUE THREAD

**Issue by asg1612** [spulec/moto#508]
Cloudwatch logs is not implement. I think that add it is very interesting.

I'll try add it.

**Comment by vlcinsky** [comment]
+1

I would be glad to use it in rewriting tests at https://github.com/jorgebastida/awslogs

**Comment by zactimeinc** [comment]
Any progress on this?

**Comment by thehesiod** [comment]
it's critical if you for example use lambdas and hook them up to event sources, the only way to get the logs would be via cloudwatch I believe

**Comment by JackDanger** [comment]
@zactimeinc & @thehesiod If one of you wanted to take a stab at starting to implement I'd help out, too! If somebody implements just one endpoints I'm sure we could all pitch in

**Comment by thehesiod** [comment]
I'm going to see how far I get with my lambda, if moto supports triggering a lambda from an SNS event I'll probably try working on it

**Comment by thehesiod** [comment]
started working on it here: https://github.com/spulec/moto/pull/1048

**Comment by spulec** [comment]
Initial support added with https://github.com/spulec/moto/pull/1048
