### ISSUE TITLE
Describe EC2 Vpc endpoints doesn't support vpc-endpoint-type filter.

### ISSUE THREAD

**Issue by kunalvudathu** [spulec/moto#5103]
This happens on line 202
![image](https://user-images.githubusercontent.com/92550453/167168166-94b94167-5670-4d38-9577-ea2374cb674f.png)

![image](https://user-images.githubusercontent.com/92550453/167168009-be85eeea-44e0-4425-9ee0-f84798b4a1e7.png)

**Comment by bblommers** [comment]
Thanks for raising this @kunalvudathu - marking it as an enhancement to add this filter.

**Comment by kunalvudathu** [comment]
@bblommers Thank you so much!!
