### ISSUE TITLE
rds - should not return "DBClusterIdentifier" if the instance is not in a cluster

### ISSUE THREAD

**Issue by kentnsw** [spulec/moto#5113]
Creating an issue here in case you can't see the comment on the PR.

When describe_db_instances(), the API implementation should not return "DBClusterIdentifier" property in the JSON if the instance is not in a cluster.

Please see comments on https://github.com/spulec/moto/pull/5101

**Comment by bblommers** [comment]
Thanks for raising this @kentnsw!
