### ISSUE TITLE
Performing a Query on a Table with LocalSecondaryIndexes Results in an Error

### ISSUE THREAD

**Issue by im-auld** [spulec/moto#513]
The resulting error:

`ValueError: Invalid index: recipient_timestamp_index for table: staging_notifications_us. Available indexes are: `

Code used to create the table in Moto:

```
def mock_dynamo_notification_table():
    return Table.create(
        settings.NOTIFICATIONS_TABLE_NAME,
        schema=[
            HashKey('recipient_id'),
            RangeKey('uniq'),
        ],
        throughput={
            'read': 5,
            'write': 5
        }, indexes=[
            AllIndex('recipient_timestamp_index', parts=[
                HashKey('recipient_id', data_type=NUMBER),
                RangeKey('timestamp'),
            ])
        ])
``` 

Fix submitted in PR [509](https://github.com/spulec/moto/pull/509)

Note this fix doesn't use the index as there is currently no support for QueryFiltering. I'll address that in a separate issue/PR

**Comment by spulec** [comment]
Fixed with #509
