### ISSUE TITLE
ModuleNotFoundError: No module named 'jose' while mocking cognito_idp

### ISSUE THREAD

**Issue by maharajamihir** [spulec/moto#5143]
## python-jose package dependency not included for [models.py](https://github.com/spulec/moto/tree/6ae0aa52728311158c4556ac38caffc717af21dc/moto/cognitoidp/models.py)

First of all this is my first issue so forgive me if it doesn't match your contributing guidelines.
### What happened:
I am getting a ModuleNotFound Error after importing 
```python
from moto import mock_s3, mock_cognitoidp
```
and putting 
```python
@mock_cognitoidp
class TestMain(TestCase):
```
above my testcase.

### Traceback:
```
ImportError: Failed to import test module: test_main
Traceback (most recent call last):
  File "/usr/lib/python3.10/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "<PATH_TO_DIR>/tests/test_main.py", line 19, in <module>
    class TestMain(TestCase):
  File "<PATH_TO_DIR>/.env/lib/python3.10/site-packages/moto/__init__.py", line 30, in f
    module = importlib.import_module(module_name, "moto")
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<PATH_TO_DIR>/.env/lib/python3.10/site-packages/moto/cognitoidp/__init__.py", line 1, in <module>
    from .models import cognitoidp_backends
  File <PATH_TO_DIR>/.env/lib/python3.10/site-packages/moto/cognitoidp/models.py", line 10, in <module>
    from jose import jws
ModuleNotFoundError: No module named 'jose'
```

### What did I expect to happen:
I expected this dependency to already get installed while installing the moto library and using mock_cognitoidp. 

#### Quickfix: 
I installed python-jose additionally and then it worked, which suggests that it was just forgotten as a dependency for mocks. 

#### General fix
From what I saw, the problem lies in the import in [this](https://github.com/spulec/moto/tree/6ae0aa52728311158c4556ac38caffc717af21dc/moto/cognitoidp/models.py) file. 

Maybe the problem is, that in [setup.py](https://github.com/spulec/moto/blob/6ae0aa52728311158c4556ac38caffc717af21dc/setup.py) in line 84, all services which start with "mock_" are not assigned any extra dependencies, while "mock_cognito" would actually require ```_dep_python_jose```. 

I am not sure if this exactly is where the problem lays. I hope I provided all the needed information and helps solving the issue. Let me know if you need more info.

### Additional information:
Python version:  Python 3.10.4 (tried with python 3.9 and had same problem)
pip version: pip 22.0.4
boto3==1.23.1
botocore==1.26.1
moto==3.1.9

and during my quickfix I installed:
python-jose==3.3.0

**Comment by bblommers** [comment]
Hi @maharajamihir, in order to reduce the number of dependencies, we require users to specify which services they use on installation.

If you only use CognitoIDP and S3, you can install Moto like this:
`pip install moto[cognitoidp,s3]`

This will install all required dependencies for Cognito and S3 (such as python-jose), but skips other dependencies required for other services.

Note that if you have many services,, or if limiting the dependencies is not a concern, you can simply install dependencies for all services:
`pip install moto[all]`

**Comment by maharajamihir** [comment]
Alright thanks!
