### ISSUE TITLE
mock_lambda moto.awslambda.exceptions.InvalidRoleFormat

### ISSUE THREAD

**Issue by bronzeson** [spulec/moto#5145]
Using moto v2.3.0
Installed in pipenv with pipenv install moto

I am trying to unit test a piece of code that calls lambda_client.invoke() by using @mock_lambda
but I am getting errors around iam roles.

Code I'm testing:
```
  def invoke_lambda():
      lambda_client = boto3.client('lambda')
      request = {'message': 'Hello World!'}
      lambda_response = lambda_client.invoke(
          FunctionName='hello-world-lambda',
          InvocationType='Event',
          Payload=json.dumps(request)
      )
      response = lambda_response['Payload'].read()
      print(response)
      return response
```

Test code:
```
  def lambda_event():
      code = '''
          def lambda_handler(event, context):
              return event
          '''
      zip_output = io.BytesIO()
      zip_file = zipfile.ZipFile(zip_output, 'w', zipfile.ZIP_DEFLATED)
      zip_file.writestr('lambda_function.py', code)
      zip_file.close()
      zip_output.seek(0)
      return zip_output.read()


    @mock_lambda
    @responses.activate
    def test_code(self):
        conn = boto3.client('lambda', 'us-west-2')
        conn.create_function(
            FunctionName='functionToBeTested',
            Runtime='python3.8',
            Role='test-iam-role',
            Handler='lambda_function.lambda_handler',
            Code={
                'ZipFile': self.lambda_event(),
            },
            Publish=True,
            Timeout=30,
            MemorySize=128
        )
```

Then when I try to run the test with pipenv run pytest, I get 
```
E           moto.awslambda.exceptions.InvalidRoleFormat: An error occurred (ValidationException) when calling the None operation: 1 validation error detected: Value 'arn:aws:iam::accountid:role/role_name' at 'role' failed to satisfy constraint: Member must satisfy regular expression pattern: arn:(aws[a-zA-Z-]*)?:iam::(\d{12}):role/?[a-zA-Z_0-9+=,.@\-_/]+
```
I have also tried to change the iamrole from 'test-iam-role' to something that passes this validation ('arn:aws:iam::000000000000:role/role_name') but then I get:
```
E               moto.awslambda.exceptions.CrossAccountNotAllowed: An error occurred (AccessDeniedException) when calling the None operation: Cross-account pass role is not allowed.
```

What am I doing wrong?
Thanks in advance!

**Comment by bpandola** [comment]
You need to make sure your IAM Role is also present in`moto`.   See the following code from our Lambda tests for an example on how to do this:  [Make sure IAM Role is available for lambda:CreateFunction](https://github.com/spulec/moto/blob/6ae0aa52728311158c4556ac38caffc717af21dc/tests/test_awslambda/utilities.py#L166)

**Comment by bronzeson** [comment]
That worked! Thank you! Is that documented somewhere? I didn't see it.

Also, is there some way to assert that a mock lambda was called with the correct event input?

**Comment by bblommers** [comment]
I don't believe there is documentation for this specific feature, @bronzeson. But in general we try to mimick AWS' behaviour as closely as possible, and try to throw the same exceptions as AWS if the input behaviour is invalid.

Invoking a Lambda-function starts a Docker-container, where the Lambda-code is then executed. This is a black box, similar to AWS, so it is not possible to assert the correct input directly. The output and execution logs of the Lambda are available via CloudWatchLogs, just as in AWS, so you can use that to verify indirectly whether the execution was successful.

Note that, if you use the decorators, it is not possible to connect to other services from within a Docker. There is some documentation on that here: http://docs.getmoto.org/en/latest/docs/services/lambda.html

**Comment by bronzeson** [comment]
Thanks again this was super helpful. Feel free to close!
