### ISSUE TITLE
Add support for AWS Glue Schema Registry

### ISSUE THREAD

**Issue by blacktooth** [spulec/moto#5146]
Support for AWS Glue doesn't include the schema registry APIs like `CreateSchema`, `RegisterSchemaVersion`, `GetSchemaVersion` etc. Schema Registry APIs were added to Glue in 2020. Is this feature on the roadmap of moto? Are you open to contributions?

**Comment by bblommers** [comment]
Hi @blacktooth! There is no roadmap as such - most of our PR's come from contributors who need a specific feature.
So if you want to create a PR for this, that would be very welcome! 

We have a [Contributor Section](http://docs.getmoto.org/en/latest/docs/contributing/index.html) in our documentation that should get you started. Feel free to ask any questions if you get stuck!

**Comment by hiimanii** [comment]
Hi @bblommers, can you review the [pull request](https://github.com/spulec/moto/pull/5301). Do you have any comments?

**Comment by bblommers** [comment]
Hi @blacktooth, @hiimanii, were there any remaining Glue features/methods that you would like to see in Moto? Or did the PR's cover everything you need?

**Comment by blacktooth** [comment]
The PRs covered everything we need for now! Thanks for your support on reviews! We will open a new issue in case we want to add more APIs.

**Comment by bblommers** [comment]
Sounds good to me @blacktooth - thanks!
