### ISSUE TITLE
route53 public hosted zone is not supported

### ISSUE THREAD

**Issue by pinkjosh** [spulec/moto#5163]
creating a hosted zone with a hosted zone configuration for PrivateZone=False always create a private hosted zone (PrivateZone=True) when looking into the private zone flag of retrieved hosted zone created for a given test VPC.

Request:
`self.route53.create_hosted_zone(Name="Zone1", VPC={"VPCRegion": "us-east-1", "VPCId": "vpc-1234567"},
                                        CallerReference="TestReference",
                                        HostedZoneConfig={"Comment": "TestComment",
                                                          "PrivateZone": False})`

Config information in when fetched above created Hosted Zone:

`'Config': {
            'Comment': 'TestComment',
            'PrivateZone': True
        }`

When I try create hosted zone without providing VPC and HostedZoneConfig info, no hosted zone is created.

**Comment by bblommers** [comment]
Hi @pinkjosh, do you have an example test case that showcases the problem?

**Comment by pinkjosh** [comment]
Let me provide you the test class for this test:

`import unittest
from collections import Counter
import boto3
from moto import mock_ec2, mock_sts, mock_route53, mock_acm, mock_iam
from generator.aws_api import AWSApi


@mock_acm
@mock_sts
@mock_route53
@mock_ec2
@mock_iam
class MyTestCase(unittest.TestCase):
    def setUp(self):
        self.ec2_resource = boto3.resource("ec2", "us-east-1")


    def test_hosted_zone(self):
        self.ec2_resource = boto3.resource("ec2", "us-east-1")
        vpc_resource = self.ec2_resource.create_vpc(CidrBlock='10.10.10.10/24')
        vpc_resource.create_tags(Tags=[{'Key': 'Name', 'Value': 'vpc-123456'}])
        self.route53.create_hosted_zone(Name='testzone.testdomain.com.',
                                        VPC={"VPCRegion": "us-east-1", "VPCId": vpc_resource.id},
                                        CallerReference="TestReference",
                                        HostedZoneConfig={"Comment": "TestComment","PrivateZone": False})
        hosted_zones = self.route53.list_hosted_zones_by_vpc(VPCId=vpc_resource.id, VPCRegion='us-east-1')
        self.assertEqual('testzone.testdomain.com.', hosted_zones['HostedZoneSummaries'][0]['Name'])
        hosted_zone_details=self.route53.get_hosted_zone(Id=hosted_zones['HostedZoneSummaries'][0]['HostedZoneId'])
        self.assertFalse(hosted_zone_details['HostedZone']['Config']['PrivateZone'])`

**Comment by bblommers** [comment]
This is not something I can test against AWS atm, but it looks like the docs specifically say that when passing a VPC, the hosted zone has to be private.

https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/route53.html#Route53.Client.create_hosted_zone

On the VPC-parameter: `(Private hosted zones only)`

**Comment by bblommers** [comment]
Finally I had some time to verify this against AWS, and it looks like AWS behaves the same: if a VPC is provided, then the `PrivateZone` is marked as True. The actual value in the `HostedZoneConfig` is ignored.

I'll close this - let me know if I've missed anything though.
