### ISSUE TITLE
Force setup of last used for an IAM User access key

### ISSUE THREAD

**Issue by bruno-gialis-al** [spulec/moto#5188]
## iam.get_access_key_last_used() never return a date-time

iam.get_access_key_last_used() never return a last date-time (field LastUsedDate never exist).

Is it a way to "force" setup of this attribute by mocking an access or other? I don't find any information on this into documentation...

I'm tried this basic code, but it don't work...
```python
import boto3
from moto import mock_iam
from moto import mock_ec2

mock_iam = mock_iam()
mock_iam.start()
mock_ec2 = mock_ec2()
mock_ec2.start()

c_iam = boto3.client("iam")
c_iam.create_user(Path="my/path",UserName="fakeUser")
key = c_iam.create_access_key(UserName="fakeUser")

c_ec2=boto3.client("ec2", 
  aws_access_key_id=key["AccessKey"]["AccessKeyId"], 
  aws_secret_access_key=key["AccessKey"]["SecretAccessKey"]
)
c_ec2.describe_instances()

c_iam.get_access_key_last_used(AccessKeyId=key["AccessKey"]["AccessKeyId"])

mock_iam.stop()
mock_ec2.stop()

```

Thanks.

Regards.

**Comment by bblommers** [comment]
Hi @bruno-gialis-al, that value is always set to None at the moment, because we do not track access keys at all.

You could access the internal API directly to set this value:
```
from moto.backends import get_backend
timestamp = datetime.utcnow()
iam_backend = get_backend("iam")["global"]
iam_backend.users[username].access_keys[0].last_used = timestamp
```

Note that this is an internal API, and as such subject to change - but hopefully it is useful nonetheless.

In the meantime, I'll mark this ticket as an enhancement, and see if we can implement this functionality properly.

**Comment by bruno-gialis-al** [comment]
Thanks for the tips waiting for an official way to do it !

**Comment by bblommers** [comment]
This feature is now available as of Moto >= 4.0.0.dev3, as part of the MultiAccount support - see the documentation here: http://docs.getmoto.org/en/latest/docs/multi_account.html

The full release schedule for Moto 4 can be found here: https://github.com/spulec/moto/issues/5366

Please let us know if you have any feedback.

**Comment by bblommers** [comment]
Moto 4.0.0 is now released, so this now works as you would expect - `get_access_key_last_used` will return the correct data automatically. Please raise a new issue if you still encounter any issues.

**Comment by bruno-gialis-al** [comment]
It work fine, thanks !
