### ISSUE TITLE
Ability to tag and remove a tag for an EKS resource

### ISSUE THREAD

**Issue by mmerrill3** [spulec/moto#5203]
This is a feature request to leverage moto for mocking tag functions in the EKS client, including
tag_resource()
untag_resource()
list_tags_for_resource()

According to the latest published dev docs, this is not implemented yet at http://docs.getmoto.org/en/latest/docs/services/eks.html

**Comment by bblommers** [comment]
Thanks for raising this @mmerrill3 - will mark it as an enhancement to add these methods.

If this is something you'd like to tackle yourself, PR's are always welcome!

**Comment by mmerrill3** [comment]
Yeap, I was going to give it a whirl.  You can assign to me.

**Comment by mmerrill3** [comment]
@bblommers could your approve the workflow since its my first contribution to this project?
