### ISSUE TITLE
create_vpc should never create a default vpc

### ISSUE THREAD

**Issue by jbmchuck** [spulec/moto#5205]
Currently if no VPCs exist the create_vpc call will create a default VPC.  AFAICT in AWS CreateVpc never creates default VPCs - a separate call CreateDefaultVpc is used for this.

Repro:

    #!/usr/bin/env python3

    import boto3
    import moto

    @moto.mock_ec2
    def delete_all_vpcs_then_create_non_default_vpc():
        client = boto3.client("ec2", region_name="us-east-1")
        initial_vpcs = client.describe_vpcs().get("Vpcs", [])
        assert(len(initial_vpcs) != 0)
        for initial_vpc in initial_vpcs:
            client.delete_vpc(VpcId=initial_vpc["VpcId"])
        no_vpcs = client.describe_vpcs()["Vpcs"]
        assert(len(no_vpcs) == 0)
        client.create_vpc(CidrBlock="10.0.0.0/24")
        created_vpcs = client.describe_vpcs()["Vpcs"]
        assert(len(created_vpcs) == 1)
        assert(created_vpcs[0]["IsDefault"] == False)

    delete_all_vpcs_then_create_non_default_vpc()

...

    Traceback (most recent call last):
      File "/.../mototest/./test.py", line 20, in <module>
        delete_all_vpcs_then_create_non_default_vpc()
      File "/.../mototest/venv/lib/python3.10/site-packages/moto/core/models.py", line 120, in wrapper
        result = func(*args, **kwargs)
      File "/.../mototest/./test.py", line 18, in delete_all_vpcs_then_create_non_default_vpc
        assert(created_vpcs[0]["IsDefault"] == False)
    AssertionError

**Comment by bblommers** [comment]
Hi @jbmchuck, thanks for raising this! Looks like our implementation is indeed wrong here. Marking it as a bug.

**Comment by jbmchuck** [comment]
Thanks - I created a PR here, I *think* this fix is at the right level: https://github.com/spulec/moto/pull/5209

**Comment by bblommers** [comment]
This has now been fixed with #5212
