### ISSUE TITLE
How to retrieve aws claims

### ISSUE THREAD

**Issue by rajshahdev** [spulec/moto#5214]
right now I developed an authentication system with respect to Cognito and from that, I am fetching aws claims (basically fetching sub UUID) now I want to implement the test cases also but I am confused about how can I do it with respect to moto.

so how can i mock this Cognito and fetch aws claims

in python the actual code i am doing 

```
from starlette.requests import Request
def verify_sub_group(request: Request) -> bool:
    requester_sub = request.scope['aws.event']['requestContext']['authorizer']['claims']['sub']
```

how to mock request.scope?

P.S:- I am passing jwt token at every request so from that it takes the data(like sub, email, etc)

Appreciate it if you can help me!!

**Comment by rajshahdev** [comment]
@bblommers please help me!

**Comment by bblommers** [comment]
It's not quite clear to me what you're asking, @rajshahdev. Moto only mocks AWS SDK requests, such as the ones made by boto3 - are there specific boto3-requests that are not mocked correctly?
