### ISSUE TITLE
s3_backend breaking change in minor version

### ISSUE THREAD

**Issue by Lilja** [spulec/moto#5232]
Hi!

We are currently running `3.0.5` in our codebase and we have the following function in our tests:

```python3
def change_moto_s3_object_last_modified(bucket, key, value: Union[datetime, timedelta, int]):
     obj = moto.s3.s3_backend.buckets[bucket].keys[key]
```

We recently did a update of dependencies in the project which used `3.1.13`.

Doing so broke the build:

`AttributeError: module 'moto.s3' has no attribute 's3_backend`.

The way I see this is that we are importing something that is not having any undeescores, therefore we aren't importing anything internal from the lib.
I suspect the culprit could be https://github.com/spulec/moto/commit/79a2a9d4232ffd7e4ff7279b9516d1722a32dc74.

Are we importing internals of moto into our the tests and we should not use the library like that? I'm not sure of the desired outcome of this issue should be. Feel free to close if you see fit.

Thank you for an amazing library.

**Comment by bblommers** [comment]
Hi @Lilja, this is indeed considered part of the internal API. Only the decorators and non-beta API's under `moto.moto_api` are guaranteed to not have breaking changes.

The aim of Moto is only to mock the boto3 clients/resources, as having an API to mock everything would be too much work to create/maintain. Overriding the internal API's to customize (for example) the last modified date can be useful, and we do let people know it's an option, but always with the caveat that things may change.

I agree that it would've been more clear if everything was prefixed with `_` - I'll think of a way to implement this properly.

In the meantime, you should be able to access the same functionality using `s3_backends["global"]`. The `s3_backend` was just a shortcut, and removed to simplify things.

Let me know if you have any other questions.

**Comment by Lilja** [comment]
thank you @bblommers ❤️
