### ISSUE TITLE
Implement  filter 'status' for DescribeSnapshots

### ISSUE THREAD

**Issue by jinty** [spulec/moto#525]
My automated tests started failing with:

   NotImplementedError: The filter 'status' for DescribeSnapshots has not been implemented in Moto yet. Feel free to open an issue at https://github.com/spulec/moto/issues

so, here it is...

**Comment by spulec** [comment]
Are you on the newest version of moto? If so, which filter are you trying to use?

**Comment by jinty** [comment]
On Sun, Feb 14, 2016 at 02:04:18PM -0800, Steve Pulec wrote:
> Are you on the newest version of moto? If so, which filter are you trying to use?

I'm using moto 0.4.23, and the filter is 

```
    for snapshot in conn.get_all_snapshots(
        filters={
            'status': 'completed',
            'tag:zgres:db_id': self.app.database_identifier}):
```

Sorry for the late response, this got lost in my mail.


> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/spulec/moto/issues/525#issuecomment-183989920

-- 
Brian Sutherland

**Comment by spulec** [comment]
Thanks for opening!

**Comment by akak548** [comment]
My tests are still failing when trying to filter based on snapshot status. I am running moto version 0.4.27 and bot3 version 1.4.0 The code is straight forward.

```
response = ec2_client.describe_instances(
    Filters=[
        {
            'Name': 'status',
            'Values': 'completed'   
        }
    ]
)
```
