### ISSUE TITLE
Pass kwargs to create_multipart_upload

### ISSUE THREAD

**Issue by ddelange** [spulec/moto#5252]
Hi 👋 

We have some kwargs going into [`create_multipart_upload`](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Client.create_multipart_upload) (using `smart_open` [under the hood](https://github.com/ddelange/pypicloud/blob/cb97fcb6a3f31cd278d88103c6284f36df8e26d0/pypicloud/storage/s3.py#L214-L222), tested with real s3):
```py
kwargs = {'ACL': 'authenticated-read', 'StorageClass': 'STANDARD_IA', 'Metadata': {'summary': 'summary', 'name': 'mypkg', 'version': '1.1'}}
s3.create_multipart_upload(Bucket=..., Key=..., **kwargs)
```
Can this currently be mocked? It looks like the [mocked method](https://github.com/spulec/moto/blob/a2c2c06243b49207797ab0798dbfa8c1f6cb6477/moto/s3/models.py#L1926) does not take any CamelCase arguments 🤔

Currently, these kwargs seem to be ignored, as they go [missing](https://github.com/stevearc/pypicloud/runs/6998719205?check_suite_focus=true#step:4:2520) in a round trip.

**Comment by bblommers** [comment]
Hi @ddelange, looks like the ACL-parameter is currently not supported, not. Will raise a PR to fix this shortly.

**Comment by ddelange** [comment]
Awesome, thanks for the quick response! And how about StorageClass kwarg? This one [also](https://github.com/stevearc/pypicloud/runs/6998719205?check_suite_focus=true#step:4:2488) went missing in tests when I introduced multipart

**Comment by bblommers** [comment]
@ddelange The test in the attached PR already asserts that StorageClass is propagated to the resulting object. I didn't have to make any changes around StorageClass to make this work.

Do you have a boto3-style test case that demonstrates the bug?

**Comment by ddelange** [comment]
ah awesome, I missed that! in that case all good :)

**Comment by bblommers** [comment]
Also, when I ran our own test against AWS, it returned two grants when passing `ACL=authenticated-read`. That is reflected in the attached PR as well.

It looks like your test case only expects one. So there may still be a discrepancy there.
```
Traceback (most recent call last):
  File "/pypicloud/tests/test_storage.py", line 189, in test_object_acl
    "Permission": "READ",
AssertionError: Element counts were not equal:
First has 0, Second has 1:  {'Grantee': {'Type': 'Group', 'URI': 'http://acs.amazonaws.com/groups/global/AuthenticatedUsers'}, 'Permission': 'READ'}
```

Happy to look into that as well, but for that I would also need a simplified (boto3-style) test case, if Moto is returning too many grants in some cases.

**Comment by ddelange** [comment]
I assume that is default behaviour from Amazon. Our test [expects](https://github.com/ddelange/pypicloud/blob/4969dae81110e5c324cee813bec8f2d7817e5acb/tests/test_storage.py#L179-L191) it as well, the exception coming from `assertCountEqual` is just slightly unintuitive :)

**Comment by bblommers** [comment]
Ah. gotcha, I missed that. I'll merge in that case - let me know if you run into any other issues!

**Comment by ddelange** [comment]
Many thanks! Looking into StorageClass going missing, most likely not on your side.

**Comment by ddelange** [comment]
Yup, test was passing an empty `BytesIO()` to `smart_open`. Adding some bytes solved StorageClass showing up 👍
