### ISSUE TITLE
mock_kinesis decorator fails to work if instantiation done in classmethod setUpClass

### ISSUE THREAD

**Issue by jtprince** [spulec/moto#527]
Here's the essence of my test:

``` python

@mock_kinesis
class StreamWriterTest(SimpleTestCase):
    @classmethod
    def setUpClass(self):
        stream_name = "Test__" + random_string(16)
        self.writer = StreamWriter(StreamName=stream_name)

    @classmethod
    def tearDownClass(self):
        self.writer.client.delete_stream(StreamName=self.writer.stream_name)

    def test_write(self):
        """ Should write the item to the stream. """
        response = self.writer.write({1: 2, 3: 4})
        expected_keys = ['ShardId', 'ResponseMetadata', 'SequenceNumber']

        self.assertTrue(all(key in response for key in expected_keys))
```

This ends up using the "live" AWS interface (I can watch it create the stream on my AWS account).

When I instantiate with setUp (i.e., not with a classmethod), then the mock_kinesis call works as expected.  Normally I would use setUp, but I want to mirror my live test which only instantiates once using the classmethod.

**Comment by spulec** [comment]
I'm having trouble reproducing this. Are you on the newest version?

**Comment by adamehirsch** [comment]
I've got the same issue, for what that's worth. Just changed a unittest-based `setUp()` method into `setUpClass()` and suddenly the script is touching my live AWS account:


```
@mock_kinesis
class PopStoriesConsumerTestCase(unittest.TestCase):

    kinesis = None

    @classmethod
    def setUpClass(self):
        self.kinesis = boto3.client('kinesis')
        self.kinesis.create_stream(StreamName=app.config['LISTENED_STREAMNAME'],
                                   ShardCount=1)
```

**Comment by spulec** [comment]
I think this might be the same issue as https://github.com/spulec/moto/issues/416

**Comment by spulec** [comment]
Closing in favor of #416
