### ISSUE TITLE
fail on import of ses_backend from moto.ses 

### ISSUE THREAD

**Issue by yaronbenezra** [spulec/moto#5272]
Hi,

from version 3.1.12 we fail on this error :
 from moto.ses import ses_backend
E   ImportError: cannot import name 'ses_backend' from 'moto.ses' (/root/.local/share/virtualenvs/build-3vGKWv3F/lib/python3.8/site-packages/moto/ses/__init__.py)

can you help?

**Comment by Slash7GNR** [comment]
@bblommers I'm from @yaronbenezra and you solution worked, thanks for your help!

**Comment by bblommers** [comment]
Happy to help!
