### ISSUE TITLE
Calling emr run_job_flow with AutoTerminationPolicy causes TypeError

### ISSUE THREAD

**Issue by matthewlv30** [spulec/moto#5276]
## Reporting Bugs

When calling `run_job_flow` with `AutoTerminationPolicy` as a parameter like. `{"IdleTimeout" : 123} `causes a TypeError with Exception TypeError: Unknown type long. However AutoTerminationPolicy expect a dict with integer value.

**Comment by bblommers** [comment]
Thanks for raising this @matthewlv30, and thanks for raising this! Marking it as a bug.

**Comment by bblommers** [comment]
I'm going to close this, as the bug itself is now fixed - Moto no longer fails when providing this parameter.
