### ISSUE TITLE
Possible to assert against the arguments I sent to an AWS call?

### ISSUE THREAD

**Issue by simonw** [spulec/moto#5277]
I'm trying out Moto for a new project - I really like it! The S3 emulation layer is fantastic.

My project uses Textract and I was hoping I would be able to run an assertion that checks exactly what arguments I sent when I ran the following code:

```python
response = textract.start_document_text_detection(
    DocumentLocation={
        "S3Object": {
            "Bucket": bucket,
            "Name": key,
        }
    },
    OutputConfig={
        "S3Bucket": bucket,
        "S3Prefix": "textract-output",
    },
)
```
Is there a way to run this kind of assertion in Moto at the moment?

Here's how I did something similar with `pytest-mock`: https://til.simonwillison.net/pytest/pytest-mock-calls

**Comment by simonw** [comment]
Here's my current test: https://github.com/simonw/s3-ocr/blob/0.3/tests/test_s3_ocr.py#L34-L45

I'd like to assert inside that test that `textract.start_document_text_detection()` was called with a specific set of arguments.

**Comment by bblommers** [comment]
Hi @simonw, capturing arguments is not possible in Moto. For most services this is not a problem, as they follow a CRUD-pattern: if you want to verify that a Create was successfull, you can use the accompanying Read-feature (for example, use `list_buckets` to verify that a `create_bucket`-call was successful). 

Considering Textract does not store or process the input, using the `pytest-mock` approach might be the best solution here. 
Alternatively, you could use `Mock.assert_called_with` to achive the same result.

**Comment by simonw** [comment]
Thanks for the answer! I'll look into using `Mock.assert_called_with`.
