### ISSUE TITLE
Use standalone moto server with another library than boto

### ISSUE THREAD

**Issue by gigimon** [spulec/moto#528]
Hello

I'm want using moto standalone server with libcloud for testing my applications. But I have a problem in api version in responses from moto because moto has different api version header in responses.
For examples:
CreateImageResposne - 2012-12-01
CopyImageResponse - 2013-07-15
DescribeInstancesResponse - 2012-12-02
DescribeKeyPairsResponse - 2013-10-15

Maybe we can use one api version in all responses? I can help You with this changes

**Comment by spulec** [comment]
Yes, pull request welcome.

**Comment by gigimon** [comment]
I'm open a PR https://github.com/spulec/moto/pull/530 please see
