### ISSUE TITLE
Delete Vpc Endpoint won't delete vpc endpoint

### ISSUE THREAD

**Issue by kunalvudathu** [spulec/moto#5295]
The response when calling delete vpc endpoints gives 200 but the mock endpoint is not deleted. Following is snippet of my code:

```

        endpoint_info = ec2.create_vpc_endpoint(
            VpcEndpointType='GatewayLoadBalancer',
            VpcId=mock_resource_info['VpcId'],
            ServiceName=mock_resource_info['ServiceName'],
            SubnetIds=[subnet_id]
        )['VpcEndpoint']
        describe_endpoint_info = describe_vpc_endpoints_in_an_account(ec2)
        self.assertEqual(len(describe_endpoint_info), 1)
        self.assertEqual(describe_endpoint_info[0]['VpcEndpointId'], endpoint_info['VpcEndpointId'])

        print(endpoint_info['VpcEndpointId'])
        resp = ec2.delete_vpc_endpoints(
            VpcEndpointIds=['vpc-123456']
            )
        describe_endpoint_info = describe_vpc_endpoints_in_an_account(ec2)
        self.assertEqual(len(describe_endpoint_info), 0)
```
## Reporting Bugs

Please be aware of the following things when filing bug reports:

1. Avoid raising duplicate issues. *Please* use the GitHub issue search feature
   to check whether your bug report or feature request has been mentioned in
   the past.
2. When filing bug reports about exceptions or tracebacks, please include the
   *complete* traceback. Partial tracebacks, or just the exception text, are
   not helpful.
3. Make sure you provide a suitable amount of information to work with. This
   means you should provide:

   - Guidance on **how to reproduce the issue**. Ideally, this should be a
     *small* code sample that can be run immediately by the maintainers.
     Failing that, let us know what you're doing, how often it happens, what
     environment you're using, etc. Be thorough: it prevents us needing to ask
     further questions.
   - Tell us **what you expected to happen**. When we run your example code,
     what are we expecting to happen? What does "success" look like for your
     code?
   - Tell us **what actually happens**. It's not helpful for you to say "it
     doesn't work" or "it fails". Tell us *how* it fails: do you get an
     exception? A hang? How was the actual result different from your expected
     result?
   - Tell us **what version of Moto you're using**, and
     **how you installed it**. Tell us whether you're using standalone server
     mode or the Python mocks. If you are using the Python mocks, include the
     version of boto/boto3/botocore.

   If you do not provide all of these things, it will take us much longer to
   fix your problem.

**Comment by bblommers** [comment]
Hi @kunalvudathu, the `vpc_endpoint` will still exist, but with attribute `State="Deleted"`. Looking at the docs, this is also how AWS behaves? As the `describe_vpc_endpoints` does return endpoints with that state: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2.html#EC2.Client.describe_vpc_endpoints
