### ISSUE TITLE
Add possibility to record and replay state of moto

### ISSUE THREAD

**Issue by szopen321** [spulec/moto#5299]
It would come in handy to be able to record changes to moto state and later restore the exact same state.

**Comment by szopen321** [comment]
Proposed solution https://github.com/spulec/moto/pull/5300

**Comment by bblommers** [comment]
The first iteration of the Moto Recorder is now available as of moto >= 4.0.4.dev13.
Documentation can be found here: http://docs.getmoto.org/en/latest/docs/configuration/recorder/index.html

Let me know if you have any feedback - I'll start working on the `set_seed` implementation next!

**Comment by bblommers** [comment]
The option to seed Moto is now available as of moto >= 4.0.6.dev7 - see the documentation in the link above.
