### ISSUE TITLE
Feature request: Implement IAM back end part of update_assume_role_policy to validate policies

### ISSUE THREAD

**Issue by mmerrill3** [spulec/moto#5317]
Hello,
The current implementation of update_assume_role_policy for IAM can validate the policy passed in.
I would like to validate this data, so that invalid policies will receive an exception

**Comment by bblommers** [comment]
Thanks for raising this @mmerrill3. What kind of validation did you have in mind? Do you have an example of an invalid policy that should fail?

**Comment by mmerrill3** [comment]
Hi @bblommers , I was thinking to reuse the policy validator function that is used already in the IAM package, the IAMPolicyDocumentValidator.  That should be fine.  It does a pretty decent job of validating the sections of the IAM policy.  I'm not looking to do a deep inspection of all the values.  For instance, if the account really exists in the principal or the resources.  I think the general regular expressions used are enough.  

I have a feature branch with the updates and the unit test changes ready, I'll issue a PR this week for this.  You can assign to me.
