### ISSUE TITLE
Some /aws/service/ ssm parameters not available

### ISSUE THREAD

**Issue by hans-d** [spulec/moto#5325]
Eg, `/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-ebs` is not available as a ssm parameter, nor can it be added (understandable) like a regular parameters due to `AccessDeniedException`.

See eg https://aws.amazon.com/blogs/compute/query-for-the-latest-amazon-linux-ami-ids-using-aws-systems-manager-parameter-store/

Having these parameters set, or being able to add those kind of values (server mode), would be appreciated.

**Comment by bblommers** [comment]
Moto does bootstrap `/aws/service/global-infrastructure/`, but it would indeed be nice if we could extend that to include everything under `/aws/service`.

Marking it as an enhancement.
