### ISSUE TITLE
Jinja2 template name must be string or Template type

### ISSUE THREAD

**Issue by TimothyLoyer** [spulec/moto#5342]
Moto [creates template names based on the Python memory `id()`](https://github.com/spulec/moto/blob/c0ce38dba888af7abccec7edec629747f5e15e21/moto/core/responses.py#L112), causing them to be set as integers. Newer versions of [Jinja specify that the name must be a string or a Jinja Template](https://jinja.palletsprojects.com/en/3.1.x/api/#jinja2.Environment.get_template). This can result in unexpected behavior in other packages which are expecting a string.

It seems like wrapping the call to `id()` with `str()` could be enough to remedy this issue.

**Comment by bblommers** [comment]
Thanks for raising this and linking the docs @TimothyLoyer - marking it as a bug.
