### ISSUE TITLE
DynamoDB `get_item()` should raise `ClientError` for empty key

### ISSUE THREAD

**Issue by ppena-LiveData** [spulec/moto#5345]
### What I expect to happen:
When an empty key is provided for a `get_item()` call, AWS's DynamoDB returns an error like this:
> botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the GetItem operation: One or more parameter values are not valid. The AttributeValue for a key attribute cannot contain an empty string value. Key: <KEY_NAME_HERE>

### What is happening:
Moto does not raise an exception and just returns no found results.

### Suggested fix:
Add this right after [line 436 in moto/dynamodb/responses.py](https://github.com/ppena-LiveData/moto/blob/d28c4bfb9390e04b9dadf95d778999c0c493a50a/moto/dynamodb/responses.py#L436) (i.e. right after the `key = self.body["Key"]` line in `get_item()`):
```python
        if any(not next(iter(v.values())) for v in key.values()):
            empty_key = [k for k, v in key.items() if not next(iter(v.values()))][0]
            raise MockValidationException(
                "One or more parameter values are not valid. The AttributeValue for a key attribute cannot contain an "
                "empty string value. Key: " + empty_key
            )
```

NOTE: I'm not sure if `put_has_empty_keys()` is correct with its empty check, since it has `next(iter(val.values())) == ""`, but if the value can be a `bytes`, then that check would not work for that case, since `b'' != ''`. Also, I was thinking of creating a PR, but I wasn't sure where to add a test, since there are already 164 tests in [tests/test_dynamodb/test_dynamodb.py](https://github.com/ppena-LiveData/moto/blob/f8f6f6f1eeacd3fae37dd98982c6572cd9151fda/tests/test_dynamodb/test_dynamodb.py).

**Comment by bblommers** [comment]
Hi @ppena-LiveData, thanks for raising this! Marking it as an enhancement to add this validation.

If you want to, a PR would always be welcome.
As far as the implementation goes, my preference would be to only calculate the empty keys once. That also has the benefit of being more readable:
```
empty_keys = ...
if empty_keys:
    raise Exception(...empty_keys[0])
```
The test structure is indeed a work in progress, with tests all over the place, but the best location is probably `test_dynamodb/exceptions/test...py`.

**Comment by ppena-LiveData** [comment]
OK, I've created a PR.

For posterity: this is unrelated to this issue, but since I asked about it in my first comment, I tested using a `Binary`/`B` key instead of a `String`/`S`, and by the time `moto` gets the item, the value is a base64ed string (not bytes), so the `== '""` check in `put_has_empty_keys()` should be fine.

**Comment by abbasyadollahi** [comment]
Running into this issue as well for other DynamoDB API calls. For example when calling `transact_write_items`, no checks are being made as to whether the key values are empty or not. Given a mocked DynamoDB client, the following call works without issue, whereas it should fail with the following exception.

> botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the TransactWriteItems operation: One or more parameter values are not valid. The AttributeValue for a key attribute cannot contain an empty string value. Key: type

```python
dynamodb.transact_write_items(
    TransactItems=[
        {
            "Update": {
                "TableName": "test_table",
                "Key": {"id": {"S": "123"}, "type": {"S": ""}},
                "UpdateExpression": "SET value = :v",
                "ExpressionAttributeValues": {":v": {"N": "0"}}
            }
        }
    ]
)
```

**Comment by bblommers** [comment]
Hi @abbasyadollahi, #7089 contains the additional validation that fixes your issue. This will be part of the upcoming 4.2.11 release.
