### ISSUE TITLE
Release Moto 4.x

### ISSUE THREAD

**Issue by bblommers** [spulec/moto#5366]
The release of Moto 4.x is ~~due soon~~ now released, and will contain the following changes:

Multi-Account support ([see the documentation](http://docs.getmoto.org/en/latest/docs/multi_account.html))
Removal of the `mock_dynamodb2` and `mock_rds2` decorators
The ThreadedMotoServer will be considered out of beta, and the API considered stable

The following dependencies will get a minimum version:
`responses >= 0.13.0`

Timeline
--------------

A new development release will be created for every change, with some time in between every release to catch any bugs.
The table below contains the ~~approximate~~ exact timeline:

| Feature                                                    | Release Date        | Version        |
|------------------------------------------------------|--------------------------|-----------------|
| Multi-Account support                             | 13/08/2022            | 4.0.0.dev3   |
| Removal deprecated decorators             | 16/08/2022            | 4.0.0.dev4   |
| Set minimum version of responses         | 17/08/2022            | 4.0.0.dev5   |
| ThreadedMotoServer                              | 18/08/2022            | 4.0.0.dev10 |
|                                                                 |                               |                     |
| Full Release                                             |20/08/2022            | 4.0.0            |

Feedback
-----------------

We encourage everyone to test these changes as early as possible, and let us know about any bugs you may encounter by raising a new issue.

Breaking Changes
---------------------------

Introducing the Multi-Account support means changing the complete data structure, to ensure the data for each account is logically separated.
We know a lot of users access the internal API to have better control over the mocked data. Before, you may have done something like this to access internal models:
```
from moto.ec2.models import ec2_backends

ec2_backend = ec2_backends["us-west-1"]
```

As of verion 4, you will also have to specify which Account ID you want to access:
```
from moto.ec2.models import ec2_backends

ec2_backend = ec2_backends[ACCOUNT_ID]["us-west-1"]
```

The variable `moto.core.ACCOUNT_ID` is also removed, in favor of `moto.core.DEFAULT_ACCOUNT_ID`.

### Issue Change Log

| Date            | Change                                                                                            |
|-----------------|----------------------------------------------------------------------------------------|
| 09 Aug 22   | Added this table & Added the note on removal of `ACCOUNT_ID` |
| 13 Aug 22   | Added release-date for MultiAccount support                                 |
| 16 Aug 22  | Added the Removal of Deprecated Decorators release                   |
| 20 Aug 22  | Full v4 release                                                                                  |

**Comment by bblommers** [comment]
MultiAccount support is now available as of Moto >= 4.0.0.dev3

**Comment by bblommers** [comment]
The deprecated decorators are now removed as of Moto >= 4.0.0.dev4

**Comment by bblommers** [comment]
Moto 4 is now released! Please raise a new issue if you encounter any bugs/problems with this version, as usual.

**Comment by berzi** [comment]
@bblommers Please mention how to replace usages of the removed deprecated `mock_dynamodb2` decorator. All I can find by googling is an issue that proposed how to ignore deprecation warnings... instead of upgrading to whatever the current practice should be, which is the only option as of 4.0.0.

**Comment by bblommers** [comment]
> 
> Is it as simple as replacing `mock_dynamodb2` with `mock_dynamodb`?

Yes, it is @berzi  - I'll mention it above as well for clarity. Thanks for bringing this to our attention.
FYI, the full history/reasoning behind this change can be found here: https://github.com/spulec/moto/issues/4526
