### ISSUE TITLE
moto conflicts with flask 2.2.2 since it requires werkzeug < 2.2.0, when using poetry

### ISSUE THREAD

**Issue by c0state** [spulec/moto#5374]
The current latest `moto` version `3.1.17` conflicts with `flask` version `2.2.2`. This was noticed when using [poetry](https://python-poetry.org/) but is generally a version conflict regardless of the dependency manager.

To reproduce the issue, create a project with `flask` 2.2.2 and use the current latest `moto` version `3.1.17` in said project. It will throw a package dependency conflict (this error was in poetry but other tools will probably complain likewise):
```
Resolving dependencies...

  SolverProblemError

  Because no versions of moto match >3.1.17,<4.0.0
   and moto (3.1.17) depends on werkzeug (>=0.5,<2.2.0), moto (>=3.1.17,<4.0.0) requires werkzeug (>=0.5,<2.2.0).
  And because flask (2.2.2) depends on Werkzeug (>=2.2.2)
   and no versions of flask match >2.2.2,<3.0.0, moto (>=3.1.17,<4.0.0) is incompatible with flask (>=2.2.2,<3.0.0).
  So, because qsi-conclave depends on both flask (^2.2.2) and moto (^3.1.17), version solving failed.
```

**Comment by c0state** [comment]
Also, was there a reason `werkzeug` was pinned to `2.2.0`? It seem like `<3` might be a fair version specifier?

**Comment by bblommers** [comment]
Thanks for raising this @c0state - we'll pin flask to <2.2.x for now as well.

Background on why we had to pin werkzeug can be found in #5341
