### ISSUE TITLE
Boto3 compatibility?

### ISSUE THREAD

**Issue by reiven** [spulec/moto#540]
Hi @spulec , i'm just wondering how current moto version is compatible with boto3?
I see some issues reported about that.

Thanks in advance

**Comment by spulec** [comment]
In general, Moto doesn't rely on anything specific to Boto. It only mock AWS endpoints so there should be no issue with different boto versions. Feel free to open an issue if something isn't working though.

**Comment by hangtwenty** [comment]
Maybe we should add something to the README saying in bold letters:

> In general, Moto doesn't rely on anything specific to Boto. It only mock AWS endpoints so there should be no issue with different boto versions. Feel free to open an issue if something isn't working though.

What do you think? :D

**Comment by spulec** [comment]
@hangtwenty added with https://github.com/spulec/moto/commit/e2774f3404248bc47404ffa3cfca413daedfc983. Thanks for the idea.
