### ISSUE TITLE
ConcurrentRunsExceededException when mocking for more than one Glue Job

### ISSUE THREAD

**Issue by Marinette** [spulec/moto#5402]
Hi all,
 
I am using moto v 3.1.2

I ran into this issue when trying to use moto to mock my Glue start_job_run() calls.
This happens when I want to use the same JobName to run two different start_job_runs().
The first one will succeed but the second one will give me error:

`Exception: An error occurred (ConcurrentRunsExceededException) when calling the StartJobRun operation: Job with name somejobname already running`

I initialized the job like so:
```
@pytest.fixture(autouse=True)
def glue_job(mock_aws: Any) -> Any:
    import boto3

    glue = boto3.client("glue")
    glue.create_job(
        Name="somejobname",
        Role="some-role",
        ExecutionProperty={"MaxConcurrentRuns": 5},
        Command={
            "Name": "some-name",
            "ScriptLocation": "some-location",
            "PythonVersion": "some-version",
        },
    )
```

I believe this error could be due to:
https://github.com/spulec/moto/blob/a6f7cb7957948de134c47b435f2263698b0eebeb/moto/glue/models.py#L901

The job state is set to RUNNING but never set back to READY, thus mocking only works for the first StartJobRun call, even if we set MaxConcurrentRuns.

**Comment by bblommers** [comment]
Hi @Marinette, thanks for raising this! Sounds like there are two issues: 
 - we need to support the `MaxConcurrentRuns`-property
 - and we need to implement a [state transition](http://docs.getmoto.org/en/latest/docs/configuration/state_transition/index.html) for Glue jobs so that the state will be set to READY automatically.

Marking it as an enhancement.

If this is something you're interested in, PR's are always welcome!

**Comment by bblommers** [comment]
With moto >= 4.0.4.dev12, Glue now respects the MaxConcurrentRuns-property.
Using state transitions, it is also possible to choose how long a job run takes. See https://docs.getmoto.org/en/latest/docs/configuration/state_transition/index.html for more information about that feature.

I'll close this, but let us know if you run into any other issues!
