### ISSUE TITLE
Mock KMS requires a mock key to be created

### ISSUE THREAD

**Issue by AGnias47** [spulec/moto#5415]
I'm unable to use KMS encrypt without first creating a mock key. Because the operation is being mocked, I would expect the `KeyId` parameter of `encrypt` to accept any string. However, it seems to only work when a mock key is created. Is this the expected behavior of the mock? Inspecting the key that is created, it does seem to be an actual mock, just seems to be an unnecessary step to use the mock encrypt function.

## Expected moto behavior

The following should succeed

```python
@moto.mock_kms
def test_kms():
    client = boto3.client("kms")
    mock_creds = {"A": "B", "C": "D", "E": "F"}
    encrypted = client.encrypt(Plaintext=json.dumps(mock_creds), KeyId="24six0one")
    assert isinstance(encrypted, dict)
```

## Actual moto behavior

Get the following error:
```
botocore.errorfactory.NotFoundException: An error occurred (NotFoundException) when calling the Encrypt operation: Invalid keyId 24six0one
```

## Current Fix

```python
@moto.mock_kms
def test_kms():
    client = boto3.client("kms")
    mock_creds = {"A": "B", "C": "D", "E": "F"}
    kms_key = client.create_key()
    encrypted = client.encrypt(Plaintext=json.dumps(mock_creds), KeyId=kms_key["KeyMetadata"]["KeyId"])
    assert isinstance(encrypted, dict)
```

**Comment by bblommers** [comment]
Hi @AGnias47, that is the expected behaviour.
We want to resemble the AWS-behaviour as closely as possible, and that includes verifying that Keys are created, and throwing the exact same error message if it hasn't been created yet.

**Comment by AGnias47** [comment]
Understood, thanks for the quick response and clarification!
