### ISSUE TITLE
Regex in put_integration doesn't match with sagemaker runtime integration

### ISSUE THREAD

**Issue by arnaudstiegler** [spulec/moto#5418]
## Reporting Bugs

Moto version: 4.0.0

When using sagemaker runtime as integration for an API Gateway, the endpoint URI will be:
`arn:aws:apigateway:{region}:runtime.sagemaker:path/endpoints/{endpoint_name}/invocations`

However, in `APIGatewayBackend.put_integration`, the URI gets matched [here](https://github.com/spulec/moto/blob/master/moto/apigateway/models.py#L1610) with the following regex:

`re.match("^arn:aws:apigateway:[a-zA-Z0-9-]+:[a-zA-Z0-9-]+:(path|action)/", uri)`

Because `[a-zA-Z0-9-]+` can't match `sagemaker.runtime`, the function throws an invalid ARN request even though the ARN should be valid

**Comment by bblommers** [comment]
Thanks for raising this @arnaudstiegler, and welcome to Moto!

If you want to contribute a fix for this, PR's are always welcome.
