### ISSUE TITLE
create_endpoint_config doesn't support Serverless deployment

### ISSUE THREAD

**Issue by arnaudstiegler** [spulec/moto#5443]
It is currently not possible to use moto to mock `create_endpoint_config` if the endpoint config involves using serverless deployment.

To reproduce:
```
from moto import mock_sagemaker
import boto3

with mock_sagemaker():
    client = boto3.client("sagemaker")
    endpoint_conf_name = 'test'
    
    client.create_endpoint_config(
        EndpointConfigName=endpoint_conf_name,
        ProductionVariants=[
            {'VariantName': 'dummy',
                'ModelName': 'dummy',
                'ServerlessConfig': {
                'MemorySizeInMB': 1024,
                'MaxConcurrency': 20
            }}
        ],
    )
```

Stacktrace:
```
self = <moto.sagemaker.models.FakeEndpointConfig object at 0x7f90f8934850>, production_variants = [{'ModelName': 'test', 'ServerlessConfig': {'MaxConcurrency': 20, 'MemorySizeInMB': 6144}, 'VariantName': 'default-variant-test'}]

    def validate_production_variants(self, production_variants):
        for production_variant in production_variants:
>           self.validate_instance_type(production_variant["InstanceType"])
E           KeyError: 'InstanceType'

ml_framework/venv/lib/python3.7/site-packages/moto/sagemaker/models.py:401: KeyError
```

The error is triggered when moto creates a new `FakeEndpointConfig`: https://github.com/spulec/moto/blob/930c58bd1366b073e8630a82fa7f34624babd867/moto/sagemaker/models.py#L399-L401

When deploying using `ServerlessConfig`, there is no `InstanceType` present in the ProductionVariant (see documentation: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sagemaker.html#SageMaker.Client.create_endpoint_config)

Ideally, we should condition based on whether we have `InstanceType` or `ServerlessConfig` in the ProductionVariant, and add some checks on the Serverless Config parameters.

Happy to get a PR out to fix this :)

**Comment by bblommers** [comment]
Hi @arnaudstiegler, thanks for raising this. PR's are always welcome - let me know if you need any help or pointers.

**Comment by arnaudstiegler** [comment]
Sounds good, will work on this

**Comment by arnaudstiegler** [comment]
@bblommers Is there a guide for contribution? Can I simply open a PR against the repo or should I fork it instead?
