### ISSUE TITLE
Pin Cryptography library

### ISSUE THREAD

**Issue by jlopezscala** [spulec/moto#5454]
Hey there!

This can be a totally invalid issue but not sure where else I could post this.

There is a [new release](https://cryptography.io/en/latest/changelog/#v38-0-0) of Cryptography library which `moto` is using [today](https://github.com/spulec/moto/blob/master/setup.py#L32).
It looks like major versions are being pulled because of the versioning schema change from the `cryptography` library.

Today some of my CIs failed after trying to pull the latest version of `cryptography` that deprecated OpenSSL 1.1.0.
Should the library be pinned?

I can pin `cryptography` on my end, of course (I should, and I did haha). This is not an issue for me but probably worth bringing up.

Thanks!

## Expected behavior
Not to pull majors

## Current behavior
Major to `3.3.1` is being pulled using `pip install moto`
```
Collecting cryptography>=3.3.1 (from moto->-r tests/requirements.txt (line 9))
  Downloading https://files.pythonhosted.org/packages/6d/0c/5e67831007ba6cd7e52c4095f053cf45c357739b0a7c46a45ddd50049019/cryptography-38.0.1.tar.gz (599kB)
```

Just concerned that next `cryptography` version is BACKWARDS INCOMPATIBLE, a bit of a headache for some

**Comment by bblommers** [comment]
Hi @jlopezscala, generally we do not want to pin versions unless absolutely necessary - as a library, we should not be the deciding factor in what versions are being used by the user.

What kind of issues did you have with the latest version of `cryptography`?

**Comment by jlopezscala** [comment]
@bblommers Hey there! Thanks for jumping into my question so fast!

Looks like my `pip` was not up-to-date. The latest version of `cryptography` requires a newer version of `rustc` compiler to be installed on the system where the `pip install moto` command is running. This is easily solved by upgrading `pip` as per `cryptography` docs, I quote from their changelog:

> Updated the minimum supported Rust version (MSRV) to 1.48.0, from 1.41.0. Users with the latest pip will typically get a wheel and not need Rust installed, but check [Installation](https://cryptography.io/en/latest/installation/) for documentation on installing a newer rustc if required.

 That's totally ok, it's my bad for using an older `pip`. 

My concern is that the [next version](https://cryptography.io/en/latest/changelog/#main) of `cryptography` claim to be BACKWARDS INCOMPATIBLE. Wouldn't that cause an issue for `moto` users if any major library update is being pulled by `moto`?

**Comment by bblommers** [comment]
So, I've just traced all our cryptography-uses in Moto, and it doesn't look like the changes impact the way we use the library.

Dropping support for older OpenSSL/LibreSSL versions will affect some users of course, but it will be up to them to ensure their systems are up-to-date (or pin cryptography manually).

Thanks for the heads-up though! I wasn't aware of these changes at all.

**Comment by jlopezscala** [comment]
Great! Thanks for your answers and your time looking at it!
