### ISSUE TITLE
upload_file doesn't work with moto 

### ISSUE THREAD

**Issue by openSourcerer9000** [spulec/moto#5455]
So I have a process which uploads files to S3. I've tried it using an actual AWS account and it works just fine. I'm trying to write a test for it, which looks like this:

```
other_file.py

def putprocess(authFile):
    keys = readFromRootKey_csv(authFile)
    s3 = boto3.resource(
        's3',
        **keys,
        region_name = region
    )
    print('S3 successfully authenticated')

    s3.meta.client.upload_file(str(file),bucket,s3path)
    print(f'successfully put to {bucket}/{s3path}')
```
```
test_file.py

from other_file.py import putprocess

@pytest.fixture(scope='function')
def aws_credentials():
    """Mocked AWS Credentials for moto."""
    os.environ['AWS_ACCESS_KEY_ID'] = 'testing'
    os.environ['AWS_SECRET_ACCESS_KEY'] = 'testing'
    os.environ['AWS_SECURITY_TOKEN'] = 'testing'
    os.environ['AWS_SESSION_TOKEN'] = 'testing'
    os.environ['AWS_DEFAULT_REGION'] = 'sa-east-1'

@pytest.fixture(scope='function')
def s3(aws_credentials):
    with mock_s3():
        yield boto3.resource('s3', region_name='sa-east-1')

class TestClass():
    @mock_s3
    def test_put_s3(self,s3):
        # conn = boto3.resource('s3', region_name=rep_plan.region)
        s3.meta.client.create_bucket(Bucket=rep_plan.bucket,
            CreateBucketConfiguration={'LocationConstraint':rep_plan.region})

        putprocess(mocked_authFile_with_phony_credentials)

        bkt = s3.Bucket(rep_plan.bucket)

        print( list( bkt.objects.all() ) ) # this prints []

        assert 'Expected/S3/filepath' \
            in [obj.key for obj in bkt.objects.all()]
```

Note: 
 - the process works just fine in the real AWS environment
 - the authentication and put success printouts print from the putprocess()
 - the mock bucket seems to be shown to exist, as the real AWS throws an error when trying to read a nonexistent bucket
 - the test run is not somehow connecting and uploading to my real S3 bucket by accident

 ## So the problem is either:
 - boto3 isn't properly mocked for the put operation
 - <Resource>.Bucket('name').objects.all() doesn't work properly in moto

I'm wondering, is moto a one-to-one mapping of boto3? Or is each method manually ported over to moto?

I'm also not using AWS CLI, I'm using only a credentials key to be able to deploy this. Is there a different recommended way of mocking this than feeding it fake credentials?

moto v 4.0.2

**Comment by bblommers** [comment]
Hi @openSourcerer9000, each method is manually ported over. Both the `put_object` and the `objects.all()`-methods should work though, as they are fairly standard operations.  

Faking the credentials should technically not even be necessary, it's just recommended to ensure that you're not accidentally connecting to AWS if there's a problem with the mocks.

Having said that, I'm not able to reproduce the problem. I've hardcoded the region/bucket/path in order to get your example to work, but everything else is the same - and this mocks absolutely fine:
```
bucket = "testbucket"
s3path = "'Expected/S3/filepath'"

def putprocess(authFile):
    keys = {"aws_access_key_id": "sth", "aws_secret_access_key": "sth"}  #readFromRootKey_csv(authFile)
    s3 = boto3.resource('s3',**keys,region_name = 'sa-east-1')
    print('S3 successfully authenticated')

    s3.meta.client.upload_file("test_5455.py",bucket,s3path)
    print(f'successfully put to {bucket}/{s3path}')



@pytest.fixture(scope='function')
def aws_credentials():
    """Mocked AWS Credentials for moto."""
    os.environ['AWS_ACCESS_KEY_ID'] = 'testing'
    os.environ['AWS_SECRET_ACCESS_KEY'] = 'testing'
    os.environ['AWS_SECURITY_TOKEN'] = 'testing'
    os.environ['AWS_SESSION_TOKEN'] = 'testing'
    os.environ['AWS_DEFAULT_REGION'] = 'sa-east-1'

@pytest.fixture(scope='function')
def s3(aws_credentials):
    with mock_s3():
        yield boto3.resource('s3', region_name='sa-east-1')

class TestClass():
    @mock_s3
    def test_put_s3(self,s3):
        # conn = boto3.resource('s3', region_name=rep_plan.region)
        s3.meta.client.create_bucket(Bucket=bucket, CreateBucketConfiguration={'LocationConstraint':'sa-east-1'})

        putprocess(None)
        bkt = s3.Bucket(bucket)
        print( list( bkt.objects.all() ) ) # this prints [s3.ObjectSummary(bucket_name='testbucket', key="'Expected/S3/filepath'")] !
        assert s3path in [obj.key for obj in bkt.objects.all()]
```

**Comment by bblommers** [comment]
At what point are you creating the `boto3.resource` inside the `put_process`-method? If the resource is created before the mock is started, then you will run into issues - see http://docs.getmoto.org/en/latest/docs/getting_started.html#what-about-those-pesky-imports

**Comment by openSourcerer9000** [comment]
The actual boto3.resource call is inside a helper function which gets called from putprocess(). There are no boto3 calls outside of functions, which seems to be the edge case the docs warn about? 

boto3 does get imported from my module, which would happen outside of the mock context. 

Is this supposed to be in double strings like this? `s3path = "'Expected/S3/filepath'"`
I tried wrapping my full S3 filepath as well but there's no difference.

In your case shouldn't objects.all() find the py file `"'Expected/S3/filepath/test_5455.py'"`?

**Comment by openSourcerer9000** [comment]
I don't think it could be the case that it's not using moto for these boto3 calls, as it wouldn't be able to connect using bad credentials. 

Trying with the real boto3, it actually doesn't throw an error until the bkt.objects.all() call. I added that call inside the end of putprocess to make sure, and it indeed finds `[]` inside the bucket without throwing an error.

```
    bkt = s3.Bucket(bucket)
    print('whats in the bucket',list(bkt.objects.all())) #prints [] once again
```

**Comment by bblommers** [comment]
> The actual boto3.resource call is inside a helper function which gets called from putprocess(). There are no boto3 calls outside of functions, which seems to be the edge case the docs warn about?

The edge case is when the client or resource is created before the mock starts. It has to be initialized while the mock is active.

> Is this supposed to be in double strings like this? 

That was a typo actually, but it does not affect the behaviour. (S3 might have something to say about the validity of a key with that name, but Moto is OK with it)

> In your case shouldn't objects.all() find the py file "'Expected/S3/filepath/test_5455.py'"?

The `test_5455.py` only references the filename on my own filesystem, but the uploaded file is called `"'Expected/S3/filepath'"` - that is as expected.

Are you able to create a repo with a CI/CD integration that shows the error? Considering I can't reproduce it yet, having access to the full code/dependencies that lead to this error will make debugging much easier.

**Comment by openSourcerer9000** [comment]
Ah gotcha, I didn't notice that was the file it gets written to in your example.

So this _does_ work just fine:

```
    @mock_s3
    def test_putModel_s3(self,rep_plan,s3):
        s3.meta.client.create_bucket(Bucket=rep_plan.bucket,
            CreateBucketConfiguration={'LocationConstraint':rep_plan.region})

        #this was wrapped in putprocess:
        keys = {"aws_access_key_id": "sth", "aws_secret_access_key": "sth"}
        news3 = boto3.resource(
            's3',
            **keys,
            region_name = rep_plan.region
        )

        news3.meta.client.upload_file(str(mc/'S3rootkey.csv'),rep_plan.bucket,
            f'file/path/S3rootkey.csv' )

        bkt = s3.Bucket(rep_plan.bucket)
        objects = [obj for obj in bkt.objects.all()]
        print(objects)
        assert len(objects)
```

Suggesting that something is different calling to boto3 from the functions defined in the other module. However, I don't believe it's just trying to use the real boto3 since it never throws an error from the bad credentials. I'll try and recreate the issue in a minimal repo.

**Comment by openSourcerer9000** [comment]
Alright, I feel silly, my test was just failing the old fashioned way. When I was running the whole class's process on the real S3, it does a preprocessing step which populates the files. I hadn't properly mocked that process before isolating the put method for a test.

**Comment by bblommers** [comment]
Happy to hear it works @openSourcerer9000!
