### ISSUE TITLE
Tests fail unless we use both a decorator and a context manager for `mock_dynamodb` with our pytest fixture

### ISSUE THREAD

**Issue by jtherrmann** [spulec/moto#5461]
## Version information

We've installed `moto 4.0.2`, `boto3 1.24.70`, and `botocore 1.27.70` with `pip`. We're running Python 3.9.13.

## Description of the problem

We're using `mock_dynamodb` [here](https://github.com/ASFHyP3/hyp3/blob/213f39ab3ae1dd2415b6d35d4cb458ff5066cacd/tests/conftest.py#L26) to mock a pytest fixture representing our database tables. If we remove either the `@mock_dynamodb` decorator or the `with mock_dynamodb():` context manager, we start seeing the following error for all of our tests that use the fixture:

```
botocore.exceptions.ClientError: An error occurred (UnrecognizedClientException) when calling the CreateTable operation: The security token included in the request is invalid.
```

raised from [this line](https://github.com/ASFHyP3/hyp3/blob/213f39ab3ae1dd2415b6d35d4cb458ff5066cacd/tests/conftest.py#L33) of the fixture:

```python3
jobs_table = DYNAMODB_RESOURCE.create_table(
```

Although, interestingly, we can move the `from dynamo import DYNAMODB_RESOURCE` line to just before the `with mock_dynamodb():` statement and our tests still pass, so the import does not need to occur within the context manager.

The `DYNAMODB_RESOURCE` object is defined [here](https://github.com/ASFHyP3/hyp3/blob/develop/lib/dynamo/dynamo/util.py#L8):

```python3
DYNAMODB_RESOURCE = boto3.resource('dynamodb')
```

And [here](https://github.com/ASFHyP3/hyp3/blob/develop/tests/test_dynamo/test_user.py#L4) is an example of one of our failing tests, `test_get_user`, which fails with `ERROR at setup of test_get_user`.

## Complete traceback

```
___________________________________________________________ ERROR at setup of test_get_user ____________________________________________________________

table_properties = <conftest.table_properties.<locals>.TableProperties object at 0x7ff3cd2fb1f0>

    @pytest.fixture
    def tables(table_properties):
        with mock_dynamodb():
            from dynamo import DYNAMODB_RESOURCE
    
>           class Tables:

tests/conftest.py:31: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/conftest.py:32: in Tables
    jobs_table = DYNAMODB_RESOURCE.create_table(
../../jth-apps/miniconda3/envs/hyp3/lib/python3.9/site-packages/boto3/resources/factory.py:580: in do_action
    response = action(self, *args, **kwargs)
../../jth-apps/miniconda3/envs/hyp3/lib/python3.9/site-packages/boto3/resources/action.py:88: in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
../../jth-apps/miniconda3/envs/hyp3/lib/python3.9/site-packages/botocore/client.py:514: in _api_call
    return self._make_api_call(operation_name, kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <botocore.client.DynamoDB object at 0x7ff3e2ed62e0>, operation_name = 'CreateTable'
api_params = {'AttributeDefinitions': [{'AttributeName': 'job_id', 'AttributeType': 'S'}, {'AttributeName': 'user_id', 'AttributeTy...HASH'}], 'Projection': {'ProjectionType': 'ALL'}}], 'KeySchema': [{'AttributeName': 'job_id', 'KeyType': 'HASH'}], ...}

    def _make_api_call(self, operation_name, api_params):
        operation_model = self._service_model.operation_model(operation_name)
        service_name = self._service_model.service_name
        history_recorder.record(
            'API_CALL',
            {
                'service': service_name,
                'operation': operation_name,
                'params': api_params,
            },
        )
        if operation_model.deprecated:
            logger.debug(
                'Warning: %s.%s() is deprecated', service_name, operation_name
            )
        request_context = {
            'client_region': self.meta.region_name,
            'client_config': self.meta.config,
            'has_streaming_input': operation_model.has_streaming_input,
            'auth_type': operation_model.auth_type,
        }
        request_dict = self._convert_to_request_dict(
            api_params, operation_model, context=request_context
        )
        resolve_checksum_context(request_dict, operation_model, api_params)
    
        service_id = self._service_model.service_id.hyphenize()
        handler, event_response = self.meta.events.emit_until_response(
            'before-call.{service_id}.{operation_name}'.format(
                service_id=service_id, operation_name=operation_name
            ),
            model=operation_model,
            params=request_dict,
            request_signer=self._request_signer,
            context=request_context,
        )
    
        if event_response is not None:
            http, parsed_response = event_response
        else:
            apply_request_checksum(request_dict)
            http, parsed_response = self._make_request(
                operation_model, request_dict, request_context
            )
    
        self.meta.events.emit(
            'after-call.{service_id}.{operation_name}'.format(
                service_id=service_id, operation_name=operation_name
            ),
            http_response=http,
            parsed=parsed_response,
            model=operation_model,
            context=request_context,
        )
    
        if http.status_code >= 300:
            error_code = parsed_response.get("Error", {}).get("Code")
            error_class = self.exceptions.from_code(error_code)
>           raise error_class(parsed_response, operation_name)
E           botocore.exceptions.ClientError: An error occurred (UnrecognizedClientException) when calling the CreateTable operation: The security token included in the request is invalid.

../../jth-apps/miniconda3/envs/hyp3/lib/python3.9/site-packages/botocore/client.py:938: ClientError
```

## How to reproduce

On a Linux machine, clone our repo and set up the conda environment:

```
git clone git@github.com:ASFHyP3/hyp3.git
cd hyp3/
git switch moto-upgrade
conda env create -f environment.yml
conda activate hyp3
```

Run the tests (they should pass):

```
make tests
```

Then edit `tests/conftest.py`, go to `def tables(table_properties):` at line 28, and remove either the `@mock_dynamodb` decorator or the `with mock_dynamodb():` context manager and re-run `make tests`. Several tests should fail with `ClientError` as described above.

## Questions

* Can anyone shed light on why we would need to use both the decorator and the context manager with our fixture in order to pass our tests?
* Can anyone suggest a way to refactor our usage of `boto3` and/or `moto` in order to allow us to use the decorator or the context manager alone?

**Comment by bblommers** [comment]
Hi @jtherrmann, that was an interesting debugging session. To answer the first question: not sure, I've never seen that behaviour before. The PR in your repo already mentions the `pesky imports`-section, and I'm assuming that a 'wrong' order of imports leads somehow to this.

Having said that, we do have a utility-method to patch any resources that were created before the mock initializes, which acts as a workaround. (See http://docs.getmoto.org/en/latest/docs/getting_started.html#patching-the-client-or-resource)

This patch would fix the issue, i.e. remove the need to have a decorator and a context-manager:
```
--- a/tests/conftest.py
+++ b/tests/conftest.py
@@ -3,6 +3,7 @@ from os import environ, path
 import pytest
 import yaml
 from moto import mock_dynamodb
+from moto.core import patch_resource
 
 
 @pytest.fixture
@@ -23,11 +24,11 @@ def get_table_properties_from_template(resource_name):
     return table_properties
 
 
-@mock_dynamodb
 @pytest.fixture
 def tables(table_properties):
     with mock_dynamodb():
         from dynamo import DYNAMODB_RESOURCE
+        patch_resource(DYNAMODB_RESOURCE)
 
         class Tables:
             jobs_table = DYNAMODB_RESOURCE.create_table(
```

This change does slow down the test execution immensely, specifically the `test_put_jobs_priority_overflow`. I haven't figured out why that is the case though.

**Comment by jtherrmann** [comment]
@bblommers Thanks for the prompt reply! We may experiment with `patch_resource`, or just leave it as-is, given your warning about the efficiency hit. If we ever find the root cause, we'll try to remember to report back here. Feel free to close the issue or leave it open, whichever you prefer.

**Comment by bblommers** [comment]
> If we ever find the root cause, we'll try to remember to report back here. 

That would be appreciated! It is quite weird behaviour, but I don't have the bandwidth to delve too deeply into it unfortunately.
