### ISSUE TITLE
The config profile (default) could not be found

### ISSUE THREAD

**Issue by iffystiffy** [spulec/moto#5469]
I am getting this error every time I try to mock the aws_credentials from the tutorial, I keep getting the "botocore.exceptions.ProfileNotFound: The config profile (adfs) could not be found" error. I reinstalled moto a few times and I am not sure why I keep getting this error and its hindering my progression.
![image](https://user-images.githubusercontent.com/4148339/189965015-a564780c-853d-4b22-be9f-7048a0427de0.png)

**Comment by nesskeo** [comment]
![image](https://user-images.githubusercontent.com/4148339/189965268-7b7f6dd5-21ff-4520-bb4c-759cf8910221.png)

**Comment by nesskeo** [comment]
![image](https://user-images.githubusercontent.com/4148339/189965414-24b4c09c-2010-41b8-8a01-1ba76d0c912b.png)
Here is the example code I tried to follow from the setup document. I tried even doing a os.enviro['AWS_PROFILE'] = 'adfs' with no luck

**Comment by bblommers** [comment]
Hi @iffystiffy, that looks like an error coming from boto3 itself. If you remove the `with mock_s3` part, it will still throw an error if the profile does not exist.

Note that the profile does not need to be mocked for Moto to work. Setting the fake credentials as environment variables is enough to ensure the test will never connect to to AWS.. (Also, as far as I know, our documentation never mentions mocking a profile - but please correct me if I'm wrong.)

**Comment by iffystiffy** [comment]
Right now I reinstalled boto3 botocore from 1.27.68 to 1.27.71 and I am still getting the "botocore.exceptions.ProfileNotFound: The config profile (adfs) could not be found" error. I am not sure where the 'adfs' profile is created because all the packages are pretty much brand new.

**Comment by bblommers** [comment]
Did you also remove the `os.environ["AWS_PROFILE"] = "asdf"`? That part is definitely not on the official website (docs.getmoto.org)

**Comment by iffystiffy** [comment]
yeah I got rid of `os.environ["AWS_PROFILE"] = "asdf"` as well with no luck.

**Comment by iffystiffy** [comment]
I was following this tutorial https://www.learnaws.org/2020/12/01/test-aws-code/ word for word

**Comment by bblommers** [comment]
Did you configure AWS previously? Whatever profile is missing, must be configured somewhere.

Did you try running the test without Moto? I'm fairly certain that the error will still occur then, as it sounds like a botocore configuration issue.

**Comment by MarkoM-dot** [comment]
@bblommers I have yet another workaround for this issue [here](https://github.com/MarkoM-dot/moto-profile). Hopefully you can reproduce the issue.

But as I can see from the comments, I think you should be aware that moto creates the `Session` object as soon as moto is imported and this I think is undesirable behavior. The session gets created as class variable in `AccountSpecificBackend` and so is evaluated on import. If you happen to have `AWS_PROFILE` env variable at this moment regardless if it is an empty string, the exception will be raised.

Hope this helps someone.

**Comment by bblommers** [comment]
Hi @MarkoM-dot, that's true - it would be better to only instantiate the Session when it's actually used. I've raised https://github.com/getmoto/moto/pull/8369 to improve this.
