### ISSUE TITLE
API Gateway support?

### ISSUE THREAD

**Issue by Miserlou** [spulec/moto#547]
Was just curious if there was any intention of adding API Gateway support to this library?

We're looking at using moto for testing [Zappa](https://github.com/Miserlou/Zappa), so this ability would be a great benefit to us.

I realize that this is a pretty monumental task considering all the quirks that API GW has, but maybe you've got a trick up your sleeve.

**Comment by spulec** [comment]
I've been watching Zappa closely and am interested in using it for a few projects.

I've added basic support for API Gateway with #558. Feel free to open additional issues for specific endpoints that don't exist.

**Comment by Miserlou** [comment]
Woah, this is awesome.

**Comment by spulec** [comment]
Going to close this out. Feel free to open additional issues for other endpoints.
