### ISSUE TITLE
Run ECS task locally

### ISSUE THREAD

**Issue by marshall7m** [spulec/moto#5472]
# Feature
Similar to how moto supports running Lambda Function as seen [here](https://docs.getmoto.org/en/latest/docs/services/lambda.html), it would be great if moto had the ability to run local docker containers to simulate ECS task definitions. Ideally, a user would be able to send a RunTask request to the moto server and moto will be able to parse the ECS task definition that's registered within the moto server or AWS and run the task.

# Ideas

A:
Steps:

1. User registers ECS task defintion
2. User executes the RunTask API with the moto endpoint URL
3. Moto responds with mock RunTask response
4. Moto server gets the task definition content via client.describe_task_definition()
5. Task definition is saved to tmp file (e.g /tmp-path/task-definition.json)
6. Using [ecs-cli](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/cmd-ecs-cli-local-create.html), run `ecs-cli local create --force --task-def-file/tmp-path/task-definition.json --output $OUT_FILEPATH` (`OUT_FILEPATH` can be a shared docker volume path so users can read the docker-compose file from other containers)
7. Moto server runs `docker compose` command to execute the generated docker-compose.yml file

If this seems within the scope of moto, I'd be more than happy to get a PR going!

**Comment by bblommers** [comment]
Hi @marshall7m, thanks for raising this!, I've given this some thought, and although I like the approach and usefulness, I'm going to declare this out of scope.

The `ecs-cli` library is platform dependent, so executing that would have to be inside another Docker-container (or packaging the libraries for all three platforms...)

There are similar services where Moto veers from mocking territory into emulation land, but that workflow would become too intensive to justify it being part of a 'mocking library'.
It would also generate a lot of maintenance that I'm not ready to take on.

I'm going to close this, but feel free to continue the conversation if you have other idea/suggestions around this. topic

**Comment by marshall7m** [comment]
Hi @bblommers, thanks for taking the time to think about it! After you mentioned it, I agree with your point that this idea is out of the scope of moto.

In terms of other services that emulate running ECS tasks locally, could you mention what those are? From my research, I found Local Stack to be the only service that does, although it comes with the caveat that users need the Pro subscription in order to work with ECS.

**Comment by bblommers** [comment]
Besides LocalStack, I'm not aware of any other libraries/services in this space, @marshall7m. There are other AWS test libraries, but they tend to focus specifcally on Serverless applications, i.e. AWSLambda/S3/etc - nothing more.
