### ISSUE TITLE
Lambda Permission does not support PrincipalOrgID condition

### ISSUE THREAD

**Issue by groverlalit** [spulec/moto#5489]
### Moto Version
3.1.17
   
### Issue:
Unable to create Lambda policy with PrincipalOrgID condition.
   
### Current behavior

1. Create a lambda function with custom policy via add_permission API (ref: [test_add_function_permission](https://github.com/spulec/moto/blob/3d913f8f1568e4232ffaab06e261b88bb1142a75/tests/test_awslambda/test_lambda_policy.py#L18))
2. Use `SourceArn` attribute 
3. Make `get_policy` API

- API Call

`conn.add_permission(
        FunctionName=name_or_arn,
        StatementId="2",
        Action="lambda:InvokeFunction",
        Principal="lambda.amazonaws.com",
        SourceArn=f"arn:aws:lambda:us-west-2:{ACCOUNT_ID}:function:helloworld",
    )
`

- Policy Created (AS expected):

`
{
    "Version": "2012-10-17",
    "Id": "default",
    "Statement": [
        {
            "Action": "lambda:InvokeFunction",
            "Principal": "432143214321",
            "Effect": "Allow",
            "Resource": "arn:aws:lambda:eu-west-1:123456789012:function:function-default-policy",
            "Sid": "1",
            "Condition": {
                "ArnLike": {
                    "AWS:SourceArn": "arn:aws:lambda:us-west-2:account-id:function:helloworld"
                }
            }
        }
    ]
}
` 

### How to produce this issue?

1. Create a lambda function with policy with Condition using PrincipalOrgID context key.
2. In `add_permission` API use `PrincipalOrgID` attribute to grant permissions (to all the Amazon Web Services accounts under this organization). 
3. Make `get_policy` API 

- API Call

`conn.add_permission(
            FunctionName=name_or_arn,
            StatementId="StatementId",
            Action="lambda:ListTags",
            Principal="arn:aws:iam::123456789012:user/SomeUser",
            PrincipalOrgID='o-a1b2c3d4e5'
        )`

- Policy created (NOT Expected):

`{
    "Version": "2012-10-17",
    "Id": "default",
    "Statement": [
        {
            "Action": "lambda:ListTags",
            "Principal": "arn:aws:iam::123456789012:user/SomeUser",
            "PrincipalOrgID": "o-a1b2c3d4e5",
            "Effect": "Allow",
            "Resource": "arn:aws:lambda:eu-west-1:123456789012:function:function-default-policy",
            "Sid": "1"
        }
    ]
}`

- Expected Policy:

`{
            "Sid": "StatementId",
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::123456789012:user/SomeUser"
            },
            "Action": "lambda:ListTags",
            "Resource": "arn:aws:lambda:eu-west-1:123456789012:function:function-default-policy",
            "Condition": {
                "StringEquals": {
                    "aws:PrincipalOrgID": "o-t1y3bu06fa"
                }
            }
        }`

**Comment by bblommers** [comment]
Thanks for raising this @groverlalit - marking it as an enhancement to process this field properly

**Comment by groverlalit** [comment]
Thank you!
