### ISSUE TITLE
Bucket.download_file downloads file with metadata

### ISSUE THREAD

**Issue by andrescevp** [spulec/moto#5490]
I am uploading a file and then downloading the same file.

The upload works fine, I am checking the content and is there where it fails

The file:
```
ID|COUNTRY
1|Foo
...
```

The upload code

```
s3_client.upload_file(file_name, bucket, object_name, ExtraArgs={"Metadata": {"foo": "boo"}, "ChecksumAlgorithm": "SHA256"})
```

The test failing

```
body = conn.Object(S3_BUCKET, "my_key.csv").get()['Body'].read().decode("utf-8")
assert body.startswith('ID|COUNTRY'), body
>>>
assert False
E        +  where False = <built-in method startswith of str object at 0x55a06e2966e0>('ID|COUNTRY')
E        +    where <built-in method startswith of str object at 0x55a06e2966e0> = '2f3\r\nID|COUNTRY...'
```

I would expect to have exactly the same body as I am saving via `pandas.to_csv`

The `2f3` is a random value as far I could see...

The downloaded files look like
```
E       AssertionError: 2f3 # this is new content
E         ID|COUNTRY
E         1|US
E         ...
E         # this is new content
E         0 # this is new content
E         x-amz-checksum-sha256:0QMsyrLjuMEaWcVrl26PZwuf0axTOR2XdUcU1uD0ayQ= # this is new content - from the meta? and where is my extra meta?
```

I am working around with...

```
# only in test suite
with open(_tmp_file, 'rb') as tf:
    content = tf.readlines()[1:(len(tf.readlines())-3)]
with open(_tmp_file, 'wb') as tfw:
    tfw.write(b'')
    tfw.writelines(content)
```

**Comment by bblommers** [comment]
Thanks for raising this @andrescevp - looks like the ChecksumAlgorithm-parameter confuses Moto somehow. Marking it as a bug.

**Comment by andrescevp** [comment]
@bblommers awesome, thanks, I am bit short of time to create a proper PR sorry.

**Comment by andrescevp** [comment]
@bblommers this test fails later in CI/DI. `AWS_DEFAULT_REGION` is set in the envs and a custom region is set in the client.

```            error_code = parsed_response.get("Error", {}).get("Code")
            error_class = self.exceptions.from_code(error_code)
>           raise error_class(parsed_response, operation_name)
E           botocore.exceptions.ClientError: An error occurred (IllegalLocationConstraintException) when calling the CreateBucket operation: The unspecified location constraint is incompatible for the region specific endpoint this request was sent to.```

**Comment by bblommers** [comment]
The `IllegalLocationConstraintException` occurs when using a non-default (i.e., not `us-east-`) region in the S3-client.
If you do want to use a non-default region, it is necessary to pass in the following config: 
```
bucket.create(
    CreateBucketConfiguration={"LocationConstraint": "us-west-1"}
)
```
Note that the same validation occurs when using AWS - so we're throwing the same error.
