### ISSUE TITLE
pypi.org shows wrong apache license

### ISSUE THREAD

**Issue by HannikMathe** [spulec/moto#5505]
When i use [CycloneDX](https://github.com/CycloneDX/cyclonedx-python) to create the BOM file moto shows [Apache](https://de.wikipedia.org/wiki/Apache-Lizenz) as license but the expected license would be [Apache License 2.0](https://www.apache.org/licenses/LICENSE-2.0).

As comparison to the [pypi moto site](https://pypi.org/project/moto/) you can see [boto3](https://pypi.org/project/boto3/) has the Apache License 2.0 set.

**Comment by bblommers** [comment]
Thanks for raising this @HannikMathe
