### ISSUE TITLE
SQS queue url missing region

### ISSUE THREAD

**Issue by Jasonca2** [spulec/moto#5510]
I've noticed that the queue url that is returned when creating a mock sqs queue is missing the region from the url. This causes failures when trying to publish sns messages to a topic that the queue is subscribed to. 

I'm using the latest version of moto. Was a change made recently causing the region to be left off of the url of an sqs queue?

**Comment by bblommers** [comment]
Hi @Jasonca2, there haven't been any changes to SQS recently, other than the introduction of MultiAccount support in v4.

Could the URL change be caused by this change in botocore? https://github.com/boto/botocore/issues/2705

**Comment by Jasonca2** [comment]
Never mind, I was passing in the queue url as the endpoint when creating the subscription instead of the arn of the queue.

**Comment by mikegrima** [comment]
@bblommers I was thinking of modifying line 25 in the SQS responses.py file to read:
```
    # region_regex = re.compile(r"://(.+?)\.queue\.amazonaws\.com")
    region_regex = re.compile(r"://sqs\.(.+?)\.amazonaws\.com") 
```

However that didn't resolve the warning. I think this might just be an issue with boto 🤷

**Comment by mikegrima** [comment]
Upgrading to the latest boto3 fixed my issue so maybe we don't need to do anything?

**Comment by bblommers** [comment]
These warnings? https://github.com/boto/botocore/issues/2705
They should indeed be fixed in the latest versions of boto3 @mikegrima. In the end, I don't believe we had to do anything to fix it - it was just boto3 changing an internal endpoint, and emitting a warning in case people relied on that endpoint to be in a specific format.
