### ISSUE TITLE
Large upload to S3 leaks file handle when deleting key, aborting MP upload

### ISSUE THREAD

**Issue by hannes-ucsc** [spulec/moto#5551]
Unfortunately, my proposed fix for https://github.com/spulec/moto/issues/5544 is incomplete. There are still situations in which the backend leaks the `SpooledTemporaryFile` instance that's created for large keys and MP upload parts. The situations I can think of are:

- deleting a key
- overwriting a key (not sure)
- overwriting an MP upload part
- aborting an MP upload
- completing an MP upload (not sure)

Here's a reproduction for the first one:

```python
$ python -Wall
Python 3.9.12 (main, Oct  8 2022, 00:52:50) 
[Clang 14.0.0 (clang-1400.0.29.102)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import gc
>>> from moto.s3.models import S3Backend
>>> s3 = S3Backend('us-west-1', '1234')
>>> s3.create_bucket('my-bucket','us-west-1')
<moto.s3.models.FakeBucket object at 0x102706820>
>>> s3.put_object('my-bucket','my-key', 'x' * 10_000_000)
<moto.s3.models.FakeKey object at 0x1026eeb50>
>>> s3.delete_object('my-bucket','my-key', 'x' * 10_000_000)
(True, {})
>>> s3.reset()
/Users/hannes/workspace/hca/azul/.venv/lib/python3.9/site-packages/moto/core/base_backend.py:33: ResourceWarning: unclosed file <_io.BufferedRandom name=3>
  model.instances = []
ResourceWarning: Enable tracemalloc to get the object allocation traceback
>>> gc.collect()
14426
>>> 
```

This is with Moto version 4.0.7.

I think a solution might be to add `FakeKey.dispose()`, put the closing of the value buffer there and then call that method in the appropriate places, like `S3Backend.delete_object()`, `.abort_multipart_upload()`, `.reset()`,`FakeMultipart.set_part()` et al.

**Comment by bblommers** [comment]
Thanks for the info @hannes-ucsc. I did add a test for the `delete_object`-method, but it looks like that test was faulty, if the problem still exists. Will have another look.
