### ISSUE TITLE
DynamoDB raising "Invalid UpdateExpression" for a valid expression

### ISSUE THREAD

**Issue by ivoire** [spulec/moto#5552]
PR #5504 is too strict and will raise an exception for valid DynamoDB update expressions.

For instance, according to the [documentation](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.UpdateExpressions.html#Expressions.UpdateExpressions.SET.AddingNestedMapAttributes), updating two different elements of a map in a single requests is allowed by aws but rejected by moto:

`SET #pr.#5star[1] = :r5, #pr.#3star = :r3` is valid but rejected by moto since 4.0.6.dev13

For instance, this code will work in aws but will be rejected by moto > v4.0.6:

```python
import boto3
from moto import mock_dynamodb

def run():
    mock = mock_dynamodb()
    mock.start()
    dynamodb = boto3.resource("dynamodb")
    dynamodb.create_table(
        TableName="example_table",
        KeySchema=[{"AttributeName": "id", "KeyType": "HASH"}],
        AttributeDefinitions=[
            {"AttributeName": "id", "AttributeType": "S"},
        ],
        BillingMode="PAY_PER_REQUEST",
    )
    record = {
        "id": "example_id",
        "d": {"hello": "h", "world": "w"},
    }
    table = dynamodb.Table("example_table")
    table.put_item(Item=record)
    updated = table.update_item(
        Key={"id": "example_id"},
        UpdateExpression="set d.hello = :h, d.world = :w",
        ExpressionAttributeValues={":h": "H", ":w": "W"},
        ReturnValues="ALL_NEW",
    )
    print(updated)
    mock.stop()

run()
```

**Comment by bblommers** [comment]
Thanks for raising this and adding a repro case @ivoire!
