### ISSUE TITLE
Dynamodb update_item does not raise ValidationException when changing the partition key

### ISSUE THREAD

**Issue by LiamCato** [spulec/moto#5554]
Hi,

The `update_item` method on the `resource("dynamodb").Table("table_name")` object should raise ValidationException if the user tries to change the partition key.

Specifically it should raise:

`botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the UpdateItem operation: One or more parameter values were invalid: Cannot update attribute pk. This attribute is part of the key`

However when using moto's `mock_dynamodb` context manager it does not.

A test case to replicate the issue is shown below:

```
from boto3 import client, resource
from moto import mock_dynamodb


def test_foo(
):
    table_name = "mytable"
    with mock_dynamodb():
        dynamodb_client = client("dynamodb", region_name="us-east-2")
        dynamodb_client.create_table(
            TableName=table_name,
            KeySchema=[
                {
                    "AttributeName": "pk",
                    "KeyType": "HASH",
                },  # Partition key
            ],
            AttributeDefinitions=[
                {"AttributeName": "pk", "AttributeType": "S"},
            ],
            BillingMode="PAY_PER_REQUEST",
        )
        table = resource("dynamodb", region_name="us-east-2").Table(table_name)
        base_item = {"pk": "test", "foo": 1, "bar": "two"}
        table.put_item(Item=base_item)

        table.update_item(
            Key={"pk": "test"},
            UpdateExpression="SET #attr1 = :val1",
            ExpressionAttributeNames={"#attr1": "pk"},
            ExpressionAttributeValues={":val1": "different"},
        )

```

This test passes with no errors when it should fail as it is attempting to change the value of the partition key (`pk`).

**Comment by bblommers** [comment]
Thanks for raising this and adding a repro case @LiamCato!
