### ISSUE TITLE
Error when calling elbv2.ModifyLoadBalancerAttributes

### ISSUE THREAD

**Issue by tbarizien** [spulec/moto#5555]
The mock elbv2 api doesn't support the following attribute on the ModifyLoadBalancerAttribute endpoint : `routing.http.xff_header_processing.mode`

The [aws documentation](https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_LoadBalancerAttribute.html) lists it as a valid attribute, but it is not present in the [valid attributes list](https://github.com/spulec/moto/blob/56ca48cfdd983711decdb8e175328a33fd84a364/moto/elbv2/models.py#L518) of the `FakeLoadBalancerClass` resulting in an error when trying to update it.

Would be nice to have it included.

Tested with : moto-3.1.17

**Comment by bblommers** [comment]
Thanks for raising this @tbarizien - marking it as an enhancement to add any missing properties here.
