### ISSUE TITLE
Support acm-pca module

### ISSUE THREAD

**Issue by blimmer** [spulec/moto#5558]
It would be great to support ACM PCA (Amazon Certificate Manager Private Certificate Authority) in `moto`. Specifically, since there are no EventBridge events for when a PCA is about to expire, I needed to create a lambda to `describe_certificate_authority` to check when the PCA will expire.

I don't have the bandwidth to immediately submit a PR adding this behavior, but I wanted to file an enhancement request in the meantime, since I didn't see an existing issue.

Thank you for `moto`, it's great! :heart:

**Comment by bblommers** [comment]
Thanks for raising this @blimmer! Marking it as an enhancement to add this service.

**Comment by bblommers** [comment]
Hi @blimmer, an initial implementation of ACMPCA is now available in moto >= 4.0.11.dev20.
The `describe_certificate_authority`-method will return the `NotBefore`/`NotAfter`-attributes based on the values within the provided certificate.

Please let us know if you run into any issues with this.

**Comment by blimmer** [comment]
This worked great - thank you!
