### ISSUE TITLE
Question about services not covered by moto

### ISSUE THREAD

**Issue by jfagoagas** [spulec/moto#5572]
This is not an issue, it's only a question about a service not covered by `moto`.

For example, for the AWS service Access Analyzer which is not covered what is the intended way to mock a client for that service?

Is there any way in `moto` to mock the `session` module?

Thanks!

**Comment by bblommers** [comment]
Hi @jfagoagas! There's no builtin way to mock services that are not covered.

Personally I just use the standard `patch` in these scenarios - if you intercept the boto3-calls at the right time, you can decide whether you want to mock this call manually, or want Moto to intercept this.

Example:
```
import boto3
import botocore
from unittest.mock import patch

orig = botocore.client.BaseClient._make_api_call
def mock_make_api_call(self, operation_name, kwarg):
    if operation_name == 'ListFindings':
        # Your Operation here!
        return True
    return orig(self, operation_name, kwarg)


def test_list_findings():
    client = boto3.client("accessanalyzer")

    with patch('botocore.client.BaseClient._make_api_call', new=mock_make_api_call):
        resp = client.list_findings(analyzerArn="asdfasdfasdf")
        assert resp == True
```
Note that this does not use Moto, to keep it simple, but:
If you use any `moto`-decorators in addition to the `patch`, the call to `orig(self, operation_name, kwarg)` will be intercepted by Moto.

**Comment by jfagoagas** [comment]
AWESOME @bblommers !! Thanks for your guidance ❤️

**Comment by bblommers** [comment]
Happy to help @jfagoagas! I'll close this, but let me know if you have any other questions.

**Comment by jfagoagas** [comment]
Hi @bblommers, I was thinking about the piece of code you shared and I think it could be really useful for other users to have this into the `moto` documentation.

Can I make a PR with that? I have tests for the Access Analyzer API, something like a little guidance like the `where to patch` or the `pesky imports`.

What do you think?

Thanks!

**Comment by bblommers** [comment]
Makes sense @jfagoagas - this question comes up fairly often, so having it documented would be useful.

Can you add it to the `Implemented Services`-section? That would make most sense IMO, so that the menu looks like this:

##### Implemented Services
###### Implemented Services
###### Patching other Services

##### Contributing to Moto
...

**Comment by jfagoagas** [comment]
Thanks @bblommers, yes make sense including it there.
