### ISSUE TITLE
Bug when deleting individual lambda function versions

### ISSUE THREAD

**Issue by tudor-sutu** [spulec/moto#5573]
Hello,

Deleting lambda function versions, while using Qualifier parameter, is not deleting the right function, but instead, the qualifier value is used as the array index of the version list.

## How to reproduce
Given a test lambda function, with 10 versions, from 1 to 10, delete all function versions, one after another

```
session = boto3.Session(
    profile_name="saml", region_name=getenv("AWS_REGION", "eu-west-1")
)
client = session.client("lambda")
for version in range(10):
	client.delete_function(FunctionName="Test_function", Qualifier=version)
```

will eventually run into a ResourceNotFoundException:

> /test_lambda_cleaner.py::TestLambdaCleaner::test_lambda_cleaner Failed with Error: An error occurred (ResourceNotFoundException) when calling the DeleteFunction operation: Function not found: arn:aws:lambda:eu-west-1:123456789012:function:Test_function:7
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/mock.py", line 1817, in _inner
    return f(*args, **kw)
  File "venv/lib/python3.10/site-packages/moto/core/models.py", line 111, in wrapper
    result = func(*args, **kwargs)
  File "venv/lib/python3.10/site-packages/freezegun/api.py", line 809, in wrapper
    result = func(*args, **kwargs)
  File "lambda/tests/test_lambda_cleaner.py", line 79, in test_lambda_cleaner
    clean_functions()
  File "/lambda_cleaner.py", line 81, in clean_functions
    rsp = client.delete_function(
  File "/venv/lib/python3.10/site-packages/botocore/client.py", line 514, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "venv/lib/python3.10/site-packages/botocore/client.py", line 938, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the DeleteFunction operation: Function not found: arn:aws:lambda:eu-west-1:123456789012:function:Test_function:7

Going step by step, these are the objects in memory:
| Qualifier| Versions Array | What happened |
| ------------- | ------------- |------------- |
| Start | [$Latest,1,2,3,4,5,6,7,8,9,10] | |
| 1 | [$Latest,X,2,3,4,5,6,7,8,9,10] | Deleted version 1 - ok |
| 2 | [$Latest,2,X,4,5,6,7,8,9,10] | Deleted version 3 (array index 2) instead of version 2 |
| 3 | [$Latest,2,X,5,6,7,8,9,10] | |
| 4 | [$Latest,2,5,6,X,8,9,10] | |
| 5 | [$Latest,2,5,6,8,X,10] | |
| 6 | [$Latest,2,5,6,8,X] | |
| 7 | ResourceNotFoundException | Array has too few elements |

My conclusion is the mock deletion function is not matching function_name:qualifier, in the version array, but just deleting the version at the array index

## pip libraries
boto3              1.24.89
botocore           1.27.89
certifi            2022.9.24
cffi               1.15.1
charset-normalizer 2.1.1
cryptography       38.0.1
docker             6.0.0
freezegun          1.2.2
idna               3.4
Jinja2             3.1.2
jmespath           1.0.1
MarkupSafe         2.1.1
moto               4.0.7
packaging          21.3
pip                22.2.2
pycparser          2.21
pyparsing          3.0.9
python-dateutil    2.8.2
pytz               2022.4
requests           2.28.1
responses          0.22.0
s3transfer         0.6.0
setuptools         63.2.0
six                1.16.0
toml               0.10.2
types-toml         0.10.8
urllib3            1.26.12
websocket-client   1.4.1
Werkzeug           2.1.2
xmltodict          0.13.0

**Comment by bblommers** [comment]
Thanks for raising this @tudor-sutu! Looks like our implementation is a bit wonky, indeed. Marking it as a bug.

**Comment by tudor-sutu** [comment]
Thank you for the quick response! :)
