### ISSUE TITLE
Style: formats can be done with f-strings

### ISSUE THREAD

**Issue by wonhyeongseo** [spulec/moto#5579]
[x] Avoid raising duplicate issues.

- Guidance on **how to reproduce the issue**.
I am using VSCode on WSL and with a query on the search tool as below,
![image](https://user-images.githubusercontent.com/29195190/196421189-94b5e439-dc50-4f4e-8d4d-3216805761d4.png)
there are 2116 format strings that can be f-strings.

- What does "success" look like for your code?
Ideally all of the strings would be replaced by f-strings.

- Tell us **what version of Moto you're using**, and **how you installed it**.
I installed moto via localstack.
`pip list` shows me `moto-ext 4.0.7.dev0 /home/wseo/localstack-dev/moto`

**Comment by bblommers** [comment]
Done! Thanks for raising this @wonhyeongseo
