### ISSUE TITLE
{AttributeError}type object 'FakeTrainingJob' has no attribute 'arn_formatter'

### ISSUE THREAD

**Issue by vittoema96** [spulec/moto#5580]
I've encountered what I think is a bug.

Whenever I try to call describe_training_job on a sagemaker client, and I give a training job name that doesn't exist, like so:

```
@mock_sagemaker 
def test_fail_describe(self): 
       boto3.client('sagemaker').describe_training_job(TrainingJobName='non_existent_training_job')
```

What I get is an `{AttributeError}type object 'FakeTrainingJob' has no attribute 'arn_formatter'`, 
but i was expecting a ValidationError.

The problem seems to be in moto/sagemaker/models.py at line 1868

**Comment by bblommers** [comment]
Thanks for raising this @vittoema96! Marking it as a bug.
