### ISSUE TITLE
Regression when using mock_batch_simple since 4.0.7

### ISSUE THREAD

**Issue by bmaisonn** [spulec/moto#5595]
Since moto 4.0.7 we noticed some regressions in our unit tests using `mock_batch_simple`. All the jobs container details are empty while they weren't in version 4.0.6.

For instance this code is now failing because there's no 'command' key in the dictionary.

```python
    result = batch.describe_jobs(jobs=job_ids)['jobs']
    commands = [job['container']['command'] for job in result]
```

We think this [change](https://github.com/spulec/moto/pull/5539) is the source of the issue but I'm not sure that changing the behavior of `mock_batch_simple` was intended here.

Can you confirm this, we can try to fix if needed ?

**Comment by bblommers** [comment]
Hi @bmaisonn, thanks for raising this - that was indeed an oversight. A PR would be very welcome! Let me know if you need any help with that.
