### ISSUE TITLE
Resetting the Moto_server state after completion of pytest cases.

### ISSUE THREAD

**Issue by Balasundaram** [spulec/moto#5608]
Greetings Team,

I was able to setup moto_server with latest version and had my tests use the moto_server. I have multiple tests using aws services like Dynamodb, secretmanager with sometimes same tablename/secret etc.. So when I run it together, I am getting ResourceInUse etc.. exceptions. I was wondering if there is a way to reset the state of the moto_server post every run/test. Apologies for a basic question as I am a new user of moto.

Thanks
Bala

**Comment by bblommers** [comment]
Hi @Balasundaram, welcome to Moto! You can make a POST-request to `http://localhost:5000/moto-api/reset` (assuming you're using the default server/port) to remove all the data.
