### ISSUE TITLE
remove_role_from_instance_profile action has not been implemented

### ISSUE THREAD

**Issue by ninz** [spulec/moto#563]
Is there a plan to implement remove_role_from_instance_profile in moto? I get the following error when testing:

`File "/home/ninz/repos/tangent/venv/local/lib/python2.7/site-packages/moto/core/responses.py", line 162, in call_action
    raise NotImplementedError("The {0} action has not been implemented".format(action))
NotImplementedError: The remove_role_from_instance_profile action has not been implemented
`

**Comment by spulec** [comment]
Thanks for opening!
