### ISSUE TITLE
event.delete_rule (EventBridge api) should raise ResourceNotFoundException instead of AttributeError

### ISSUE THREAD

**Issue by vivainio** [spulec/moto#5631]
Currently, if you try to run client.delete_rule(Name="foo") and the rule doesn't exist, it raises AttributeError instead of ResourceNotFoundException (because it's trying read "arn" from None):

```
    def delete_rule(self, name):
        arn = self.rules.get(name).arn
        if self.tagger.has_tags(arn):
            self.tagger.delete_all_tags_for_resource(arn)
        return self.rules.pop(name) is not None
```

Looks like the same problem applies to bunch of other methods in moto\events\models.py

**Comment by bblommers** [comment]
Thanks for raising this @vivainio! Marking it as a bug.

**Comment by bblommers** [comment]
Hi @vivainio, I've just tried this against AWS - deleting an unknown rule returns an empty response, it does not raise a ResourceNotFoundException. I'll raise a PR shortly to mimick this behaviour.

What other methods did you see with the same problem?

**Comment by vivainio** [comment]
@bblommers I didn't test a lot of them, but skimming through that models.py file should give you a good list

**Comment by bblommers** [comment]
I did @vivainio, but I didnt' see any other methods with this problem - they all seem to throw a ResourceNotFoundException, as expected. Hence the question :slightly_smiling_face:
