### ISSUE TITLE
Support for Lambda Function URL emulation

### ISSUE THREAD

**Issue by marshall7m** [spulec/moto#5637]
I'm pretty sure this falls outside the scope of moto, but I thought it's worth a try. It would be great if moto could support Lambda Function URLs to be emulated within a docker container. The user can make the API call for creating the function URL to moto and moto can spin up a separate docker container that will act as the Function URL. The function URL container can then transform requests into API Gateway [V2](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html#http-api-develop-integrations-lambda.proxy-format) payload and invoke the Lamda Function within the standalone moto server.

If this has a space within moto, I'd be happy to make a PR.

**Comment by bblommers** [comment]
That is indeed out of scope, @marshall7m. Moto is mostly focused on mocking/emulating features that boto3 exposes - Function URL's aren't part of that.

**Comment by marshall7m** [comment]
I see, thanks for the quick answer @bblommers
