### ISSUE TITLE
Please pin cfn-lint to newer release

### ISSUE THREAD

**Issue by mwgamble** [spulec/moto#5639]
In order to install a project where cfn-lint is a dependency, poetry downloads every single possible version of cfn-lint allowed by all the version ranges specified by dependencies in your project. Moto currently has a version restriction of `>0.4.0`. For a project like cfn-lint that issues new releases regularly (and at this stage probably has over 100 releases satisfied by that constraint), this results in poetry taking a significantly long time when using a private package registry.

I know this isn't moto's fault, but is there any chance you could bump the version constraint so that less versions need to be checked? 0.4.0 is very very old nowadays.

**Comment by bblommers** [comment]
Hi @mwgamble, as a library, Moto should be as compatible as possible. If people need an older version of cfn-lint, for whatever reason, Moto should not be a blocker by requiring an newer version unless absolutely necessary. So I don't want to pin a dependency, just as a crutch to help out a (what looks to be suboptimal) dependency resolver.

**Comment by bblommers** [comment]
I'm not too familiar with Poetry - will it's resolver always work it's way up, starting with the oldest version possible? I know Pip just starts with the latest version, and if that release does not satisfy some constraints, it will try the version before that, ad infinitum, which seems like a smarter solution.

Version 0.4.0 of `cfn-lint` does not have any classifiers indicating a Python version - those were only added to later releases. I wonder if that's part of the problem, that Poetry can't figure out whether 0.4.0 is an appropriate release.

**Comment by mwgamble** [comment]
That seems like a reasonable assessment.

FWIW cfn-lint 0.4.0 is over four years old. Is it reasonable to maintain compatibility with versions that old when there are new releases on such a regular cadence? Surely most users won't be using a version that old as that.

**Comment by bblommers** [comment]
> Surely most users won't be using a version that old as that.

You'd think! But in my experience, any project/business of a certain age will have weird rules/constraints in place that forces developers to pin dependencies.

I'll pin `cfn-lint` to 0.40.0 instead. That's does have Python classifiers, is 'only' 2 years old, and still gives people a large range of versions to use.

**Comment by mwgamble** [comment]
Thank you so much :heart:
