### ISSUE TITLE
Cannot create s3 bucket with more than 2 characters

### ISSUE THREAD

**Issue by l-hendriks** [spulec/moto#564]
Just installed moto and works flawlessly. I use the standalone server to mock tests for NodeJS. I have the server running (`moto_server s3 -p 4568`). Then I do this:

    var aws = require('aws-sdk'),
        s3 = new aws.S3({
            'accessKeyId': 'a',
            'secretAccessKey':'b',
            'endpoint':'http://localhost:4568',
            'region': 'eu-west-1'
        });

    s3.createBucket({
            Bucket:'ab'
        }, function(e,a){
            console.log(e);
            console.log(a);
            done();
        });

If `Bucket` is one or two characters long this works. But if it is more than 2 characters long I get this error:

```
{ [UnknownEndpoint: Inaccessible host: `somethingLong.localhost'. This service may not be available in the `eu-west-1' region.]
  message: 'Inaccessible host: `somethingLong.localhost\'. This service may not be available in the `eu-west-1\' region.',
  code: 'UnknownEndpoint',
  region: 'eu-west-1',
  hostname: 'somethingLong.localhost',
  retryable: true,
  originalError:
   { [NetworkingError: getaddrinfo ENOTFOUND somethingLong.localhost a-b.localhost:4568]
     message: 'getaddrinfo ENOTFOUND somethingLong.localhost a-b.localhost:4568',
     code: 'NetworkingError',
     errno: 'ENOTFOUND',
     syscall: 'getaddrinfo',
     hostname: 'somethingLong.localhost',
     host: 'somethingLong.localhost',
     port: 4568,
     region: 'eu-west-1',
     retryable: true,
     time: Fri Mar 11 2016 14:23:14 GMT+0100 (CET) }
```

Why is this?

**Comment by spulec** [comment]
Can you try this again against `HEAD`. Some recent changes have likely fixed it.

**Comment by l-hendriks** [comment]
Thanks for the notification, I'll check this somewhere this week when I have time

**Comment by l-hendriks** [comment]
Yup, it works! Thanks!

**Comment by johncalvinyoung** [comment]
@spulec Could you document what changed here? I found this issue after experiencing something very like it on Moto 1.0.1--I figured out before I resubmitted the bug that if I turned on `force_path_style: true` in the AWS SDK for Ruby (2.10.7) it'd work with moto standalone, but without it it would always time out on networking attempting to create a larger bucket. I'm not as familiar with the behavior of the s3 API...was there some code in moto_server that would change the default client behavior, perhaps with a different redirect? Would a default request ever work?

**Comment by noah10** [comment]
I've also found this with moto 1.1.25, and also worked around it by using s3ForcePathStyle: true. (Slightly different syntax since I'm using nodejs.)
