### ISSUE TITLE
Lambda returns a different format for last_modified field than aws would

### ISSUE THREAD

**Issue by tungol** [spulec/moto#5640]
Here's moto:
```
'LastModified': '2022-11-04 21:12:48',
```

Here's a real response from AWS:
```
"LastModified": "2022-09-29T01:32:03.000+0000",
```

They're both valid ISO format, so maybe it's fine, but I figured I'd mention.

**Comment by bblommers** [comment]
Thanks for raising this @tungol. As long as the downstream SDK's can handle our format, it's indeed not a big issue, but we might as well ensure it's in-line with what AWS returns.
