### ISSUE TITLE
Impossible jsonschema dependency

### ISSUE THREAD

**Issue by jusdino** [spulec/moto#5655]
When trying to install recent versions of `moto` in a fresh python environment, it ends up failing, due to apparently impossible dependency requirements on the `jsonschema` library. This should illustrate:
```~$ pyenv virtualenv 3.10.4 tmp
~$ pyenv activate tmp
pyenv-virtualenv: prompt changing will be removed from future release. configure `export PYENV_VIRTUALENV_DISABLE_PROMPT=1' to simulate the behavior.
(tmp) ~$ pip install pip-tools
Collecting pip-tools
  Downloading pip_tools-6.9.0-py3-none-any.whl (52 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.4/52.4 KB 736.4 kB/s eta 0:00:00
Collecting click>=7
  Downloading click-8.1.3-py3-none-any.whl (96 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.6/96.6 KB 1.5 MB/s eta 0:00:00
Requirement already satisfied: setuptools in ./src/pyenv/versions/3.10.4/envs/tmp/lib/python3.10/site-packages (from pip-tools) (58.1.0)
Collecting build
  Downloading build-0.9.0-py3-none-any.whl (17 kB)
Requirement already satisfied: pip>=21.2 in ./src/pyenv/versions/3.10.4/envs/tmp/lib/python3.10/site-packages (from pip-tools) (22.0.4)
Collecting wheel
  Downloading wheel-0.38.4-py3-none-any.whl (36 kB)
Collecting pep517>=0.9.1
  Using cached pep517-0.13.0-py3-none-any.whl (18 kB)
Collecting tomli>=1.0.0
  Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
Collecting packaging>=19.0
  Using cached packaging-21.3-py3-none-any.whl (40 kB)
Collecting pyparsing!=3.0.5,>=2.0.2
  Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
Installing collected packages: wheel, tomli, pyparsing, click, pep517, packaging, build, pip-tools
Successfully installed build-0.9.0 click-8.1.3 packaging-21.3 pep517-0.13.0 pip-tools-6.9.0 pyparsing-3.0.9 tomli-2.0.1 wheel-0.38.4
WARNING: You are using pip version 22.0.4; however, version 22.3.1 is available.
You should consider upgrading via the '/home/jx006324/src/pyenv/versions/3.10.4/envs/tmp/bin/python3.10 -m pip install --upgrade pip' command.
(tmp) ~$ echo 'moto[all]==4.0.9' >requirements.in
(tmp) ~$ pip-compile requirements.in 
Could not find a version that matches jsonschema<5.0.0,>=3.0,>=4.0.0,~=3.2 (from cfn-lint==0.71.0->moto[all]==4.0.9->-r requirements.in (line 1))
Tried: 0.2, 0.2, 0.3, 0.3, 0.4, 0.4, 0.5, 0.5, 0.6, 0.6, 0.7, 0.7, 0.8.0, 0.8.0, 1.0.0, 1.0.0, 1.1.0, 1.1.0, 1.2.0, 1.2.0, 1.3.0, 1.3.0, 2.0.0, 2.0.0, 2.1.0, 2.1.0, 2.2.0, 2.2.0, 2.3.0, 2.3.0, 2.3.0, 2.4.0, 2.4.0, 2.4.0, 2.5.0, 2.5.0, 2.5.1, 2.5.1, 2.5.1, 2.6.0, 2.6.0, 3.0.0, 3.0.0, 3.0.1, 3.0.1, 3.0.2, 3.0.2, 3.1.0, 3.1.0, 3.1.1, 3.1.1, 3.2.0, 3.2.0, 4.0.0, 4.0.0, 4.0.1, 4.0.1, 4.1.0, 4.1.0, 4.1.1, 4.1.1, 4.1.2, 4.1.2, 4.2.0, 4.2.0, 4.2.1, 4.2.1, 4.3.0, 4.3.0, 4.3.1, 4.3.1, 4.3.2, 4.3.2, 4.3.3, 4.3.3, 4.4.0, 4.4.0, 4.5.0, 4.5.0, 4.5.1, 4.5.1, 4.6.0, 4.6.0, 4.6.1, 4.6.1, 4.6.2, 4.6.2, 4.7.0, 4.7.0, 4.7.1, 4.7.1, 4.7.2, 4.7.2, 4.8.0, 4.8.0, 4.9.0, 4.9.0, 4.9.1, 4.9.1, 4.10.0, 4.10.0, 4.10.1, 4.10.1, 4.10.2, 4.10.2, 4.10.3, 4.10.3, 4.11.0, 4.11.0, 4.12.0, 4.12.0, 4.12.1, 4.12.1, 4.13.0, 4.13.0, 4.14.0, 4.14.0, 4.15.0, 4.15.0, 4.16.0, 4.16.0, 4.17.0, 4.17.0
Skipped pre-versions: 0.1a0, 3.0.0a1, 3.0.0a1, 3.0.0a2, 3.0.0a2, 3.0.0a3, 3.0.0a3, 3.0.0a4, 3.0.0a4, 3.0.0a5, 3.0.0a5, 3.0.0a6, 3.0.0a6, 3.0.0b1, 3.0.0b1, 3.0.0b2, 3.0.0b2, 3.0.0b3, 3.0.0b3, 4.0.0a1, 4.0.0a1, 4.0.0a2, 4.0.0a2, 4.0.0a3, 4.0.0a3, 4.0.0a4, 4.0.0a4, 4.0.0a5, 4.0.0a5, 4.0.0a6, 4.0.0a6, 4.1.0a1, 4.1.0a1
There are incompatible versions in the resolved dependencies:
  jsonschema<5.0.0,>=4.0.0 (from openapi-schema-validator==0.3.4->openapi-spec-validator==0.5.1->moto[all]==4.0.9->-r requirements.in (line 1))
  jsonschema<5.0.0,>=4.0.0 (from openapi-spec-validator==0.5.1->moto[all]==4.0.9->-r requirements.in (line 1))
  jsonschema<5.0.0,>=4.0.0 (from jsonschema-spec==0.1.2->openapi-spec-validator==0.5.1->moto[all]==4.0.9->-r requirements.in (line 1))
  jsonschema<5,>=3.0 (from cfn-lint==0.71.0->moto[all]==4.0.9->-r requirements.in (line 1))
  jsonschema~=3.2 (from aws-sam-translator==1.54.0->cfn-lint==0.71.0->moto[all]==4.0.9->-r requirements.in (line 1))
```

If I try to do a `pip install moto[all]==4.0.9`, pip will run for a very long time, downloading many library versions before eventually failing to resolve dependency versions.

**Comment by bblommers** [comment]
Hi @isuftin, Moto does not have jsonschema as a direct dependency, so there's not much we can do here. 

The SAM translator project has an open issue to loosen their `jsondiff` dependency, which should fix it: https://github.com/aws/serverless-application-model/pull/2441

See also #5485

**Comment by jusdino** [comment]
Oh, I missed that older moto issue because it was closed.

I see a couple of PRs in motion in SAM translator that should help and it looks like `moto` now expects `cfn-lint>=0.40.0`, which has been updated to require `aws-sam-translator>=1.54.0`. So we just wait for the sam translator updates then. Awesome!

**Comment by mwgamble** [comment]
> Moto does not have jsonschema as a direct dependency, so there's not much we can do here.

@bblommers Is this accurate? What if some of these dependencies on AWS SAM stuff (direct or indirect) were made optional? How critical are they to basic operation of moto in common use cases?

**Comment by bblommers** [comment]
@mwgamble Some background on where we use these dependencies: 

The `openapi-spec-validator` is only used in the APIGateway module, and therefore only installed with `moto[apigateway]`.
The `cfn-lint` is only used in `CloudFormation.validate_template`, but it is installed with the base `moto`.

As far as I can tell, we should be able to restrict the `cfn-lint`-module to only install with `moto[cloudformation]`. That should reduce the chance of this happening again.
Feel free to open an issue/PR for this, if you want. It would be a change in behaviour, so I would only want to release that as a minor release, not a patch, but it would make sense to change this.

**Comment by mwgamble** [comment]
@bblommers I'd be happy to work on a patch for that :+1: However I wanted to ask, for moto v5, could we make the dependency fully optional? There are going to be a lot of users who want to install `moto[cloudformation]`, but have no intention whatsoever of calling `CloudFormation.validate_template`.

**Comment by bblommers** [comment]
Thanks @mwgamble. I actually don't have any numbers of how many people use `validate_template`, but regardless: Moto should be as painfree/easy to use as possible. So I don't want to add another config option like `moto[cf-validate]`, or requiring people to install our dependencies manually.
