### ISSUE TITLE
transact_write_items limit

### ISSUE THREAD

**Issue by OakmanByte** [spulec/moto#5666]
Hello, currently you have a set limit for number of transaction items at 25(by the old AWS standard): https://github.com/spulec/moto/blob/52892f5481cdb4bc04d6eb4908bbee773d4333a8/moto/dynamodb/models/__init__.py#L1651
However with the new support of 100 transaction items from AWS:
https://aws.amazon.com/about-aws/whats-new/2022/09/amazon-dynamodb-supports-100-actions-per-transaction/
Are there any plans of updating the code to reflect this new limit?

//Thank you

**Comment by bblommers** [comment]
Hi @OakmanByte, thanks for raising this and linking the announcement! We'll update accordingly. :+1:

**Comment by rafcio19** [comment]
@bblommers lemme take a look, assign it to me
