### ISSUE TITLE
EC2 client describe_images returning default AMIs even with MOTO_AMIS_PATH set

### ISSUE THREAD

**Issue by dblanchette** [spulec/moto#5677]
## Context

We are setting `MOTO_AMIS_PATH` in a pytest plugin. Our test uses `describe_images` on an EC2 client.

## Expected

We expect the images set in the file at the path set in the environment variables `MOTO_AMIS_PATH` to be the only ones returned.

## Actual behavior

The images from `MOTO_AMIS_PATH` are there, but there are also other images that are hard-coded in the library.

## Affected versions

Present in 4.0.9, was not present in 3.1.18. moto installed with poetry (reproduced with moto installed manually in a virtual environment)

Seems to have been introduced by #5427 

Code here: https://github.com/spulec/moto/blob/6ab2497a12d8f0a5fe9be91387bc6b589d78e295/moto/ec2/models/amis.py#L157

## Reproduction steps

Run the following script
```python
import json
import os
from pathlib import Path

test_ami = [
    {
        "ami_id": "ami-760aaa0f760aaa0fe",
        "name": "infra-eks-20211110080547-bionic",
        "description": "An AMI",
        "owner_id": "123456789012",
        "public": False,
        "virtualization_type": "hvm",
        "architecture": "x86_64",
        "state": "available",
        "platform": None,
        "image_type": "machine",
        "hypervisor": "xen",
        "root_device_name": "/dev/sda1",
        "root_device_type": "ebs",
        "sriov": "simple",
        "creation_date": "2021-11-10T08:13:01.000Z"
    }
]

test_ami_path = Path(__file__).parent / "test_ami.json"

with test_ami_path.open("w") as fp:
    json.dump(test_ami, fp)

os.environ["MOTO_AMIS_PATH"] = str(test_ami_path)

import moto
import boto3

with moto.mock_ec2():
    ec2_client = boto3.client("ec2")
    images = ec2_client.describe_images()["Images"]
    print(f"Found {len(images)} images!")
    assert len(images) == 1
```
With moto 3.1.18:
```
$ python ./reproduce_step.py 
Found 1 images!
```
With moto 4.0.9:
```
$ python ./reproduce_step.py 
Found 18 images!
Traceback (most recent call last):
  File "./reproduce_step.py", line 39, in <module>
    assert len(images) == 1
AssertionError
```

## Conclusion

A workaround is to use the old version for now. Thanks for your help resolving this issue!

**Comment by bblommers** [comment]
Thanks for raising this @dblanchette. The documentation is not explicit in whether `MOTO_AMIS_PATH` should come instead of, or in addition to, the existing AMI's. But considering the previous behaviour was 'instead of', then this is indeed a regression.

**Comment by rafcio19** [comment]
@bblommers lemme take a look, assign it to me

**Comment by dblanchette** [comment]
I'm late in saying this, but thanks for the quick fix, much appreciated!
