### ISSUE TITLE
S3 access via spark shows "Path does not exist" after update

### ISSUE THREAD

**Issue by jbvsmo** [spulec/moto#5680]
I've been using Spark to read data from S3 for a while and it always worked with the following (pyspark) configuration:

```
spark.read. \
  .option('pathGlobFilter', f'*.json') \
  .option('mode', 'FAILFAST') \
  .format('json')
  .read('s3://moto-bucket-79be3fc05b/raw-data/prefix/foo=bar/partition=baz/service=subscriptions')
```

The `moto-bucket-79be3fc05b` bucket contents: 
`raw-data/prefix/foo=bar/partition=baz/service=subscriptions/subscriptions.json`

Before I upgraded to latest moto, Spark was able to find all files inside the "directory", but now it fails with:

```pyspark.sql.utils.AnalysisException: Path does not exist: s3://moto-bucket-79be3fc05b/raw-data/prefix/foo=bar/partition=baz/service=subscriptions```

I never updated Spark and it is static to version `pyspark==3.1.1` as required by AWS Glue.

I updated moto to v4.0.9 from v2.2.9 (I was forced to upgrade because some other requirement needed flask>2.2).

Unfortunately, I don't know exactly what is the AWS http request that spark sends to S3 to list a path, but on python code I do verify the path exists before sending to spark, so I know for sure the files are there in the correct location. I tried adding a `/` at the end of the read string, but nothing changes.

If I pass the full file path (with `subscriptions.json` at the end), spark does indeed read it. So that narrows down a bit because I'm certain spark is using the correct bucket and really accessing moto.

**Comment by jbvsmo** [comment]
My tests without changing code, just moto versions:
- moto 2.2.9 -> works fine
- moto 2.3.2 -> works fine
- moto 3.0.7 -> works fine
- moto 3.1.0 -> works fine
- moto 3.1.18 -> Fail: Path does not exist
- moto 4.0.9 -> Fail: Path does not exist

I will try checking all versions from 3.1.1 to 3.1.18. Being a minor version that starts failing, this must be a regression instead of a intentionally breaking change

**Comment by jbvsmo** [comment]
v3.1.7 - Pass
v3.1.8 - Fail

https://github.com/spulec/moto/compare/3.1.7...3.1.8

Maybe this is the issue? It is the only change I see relevant with s3 context:

https://github.com/spulec/moto/compare/3.1.7...3.1.8#diff-a14f7ca014b23638947c5f417dacb9a4d59eef3aee9a8041e2c855e8587643cdR335

It comes from here: https://github.com/spulec/moto/pull/5097/files

Is it possible that by fixing something related to `+` sign which involves url encoding it broke how spark sends something like a `/` encoded? That is the only explanation I have right now

**Comment by jbvsmo** [comment]
I looked more in depth into this and opened the moto server to check the requests. I see that my strings have a space inside a timestamp. Where above I wrote `foo=bar/partition=baz` would be a series of 5 partitions key=value where one them is something like `timestamp=2020-01-01 01:01:01` that gets encoded to `2Ftimestamp%3D2020-01-01+01%3A01%3A01`. Similar to what python `urllib.parse.quote_plus()` would do.

And this behavior is accepted by the real AWS servers.

I ask this PR 5097 is reverted so a real plus sign must be converted to `%3B` by the client, not moto

**Comment by bblommers** [comment]
Thanks for raising this and investigating @jbvsmo - much appreciated.

The linked PR does fix a legitimate bug, so simply reverting it would break other things. But I'm sure there's a solution that would allow all scenarios, in all versions of werkzeug (what the original PR was trying to fix).

**Comment by jbvsmo** [comment]
@bblommers Thank you for the reply

The `+` sign in a query string means a space, never a plus sign. So if werkzeug is not encoding it, then it must be a bug on their side. Can't moto just require `wekzeug>=2.1.0` and not try to fix the issue, as it breaks any strings with spaces encoded as the `+` sign

**Comment by bblommers** [comment]
@jbvsmo This should now be resolved with moto >= 4.0.11.dev11, and part of the `LATEST` Docker image. It should work for all werkzeug versions - please let  us know if you're still running into any issues though.

**Comment by jbvsmo** [comment]
I installed from github master and it seems to have fixed the issue for me. I couldn't run my full test suite that takes hours, but the couple tests I did were fine. Thank you.

Do you have a release date?

**Comment by bblommers** [comment]
Happy to hear that @jbvsmo! There is no fixed date yet, but I'm expecting we'll cut a release in the first week of December.
