### ISSUE TITLE
Moto isn't checking validity of the Batch job names

### ISSUE THREAD

**Issue by bmaisonn** [spulec/moto#5704]
This is more an enhancement request.

As of now moto accepts to submit batch jobs with characters that aren't accepted by the real infra like '.'

![image](https://user-images.githubusercontent.com/7989822/203530752-31a73448-09f2-4ed0-b499-7e95015a8ab9.png)

![image](https://user-images.githubusercontent.com/7989822/203530924-a1e097a3-cd94-425d-94c5-ab7fe1ee48ce.png)

Would it possible to perform the same kind of check in moto ?

**Comment by bblommers** [comment]
Adding it to the list!

Do you want to submit a PR for this yourself @bmaisonn?

**Comment by bmaisonn** [comment]
hey @bblommers, yeah i'll raise a pr for it
