### ISSUE TITLE
S3 not found error differs from AWS response

### ISSUE THREAD

**Issue by tobami** [spulec/moto#571]
When trying to access a key that is not present, moto returns this:

```python
{
    'ResponseMetadata': {
        'HTTPStatusCode': 404, 'HostId': '', 'RequestId': ''
    },
    'Error': {
        'Message': 'Not Found',
        'Code': '404'
    }
}
```
vs AWS S3 returning this:

```python
{
    'ResponseMetadata': {
        'HTTPStatusCode': 404, 'HostId': 'my-host-id', 'RequestId': 'some-request-id'
    },
    'Error': {
        'Message': 'The specified key does not exist.',
        'Code': 'NoSuchKey',
        'Key': 'my-s3-prefix/object-id'
    }
}
```
`Error.Code` is were the important difference lies. Handling of '404' vs 'NoSuchKey' will be very different. moto's '404'  also doesn't let you differentiate between bucket not found and key not found.

**Comment by spulec** [comment]
Thanks!

**Comment by tobami** [comment]
Thanks for fixing!

**Comment by serebrov** [comment]
I've just updated moto to 1.0.0 from 0.4.31 and there is an issue with `404` vs `NoSuchKey` exists response.
I have a following call to check for S3 object existence:

```
    try:
        boto3.session.Session(
            region_name=current_app.config['AWS_REGION'],
        ).resource('s3').Object(
            current_app.config['AWS_S3_BUCKET'],
            key=key,
        ).load()
        return True
    except BotoClientError as e:
        if e.response['Error']['Code'] == "404":
            return False
        else:
            raise
```

It worked before with `e.response['Error']['Code'] == "404"` both with moto and real AWS S3.
After moto update, the mocked `e.response` looks this way:

```
{
    "ResponseMetadata": {
        "HTTPStatusCode": 404,
        "RetryAttempts": 0,
        "HTTPHeaders": {
            "Content-Type": "text/plain"
        }
    },
    "Error": {
        "Message": "The specified key does not exist.",
        "Code": "NoSuchKey",
        "RequestID": "7a62c49f-347e-4fc4-9331-6e8eEXAMPLE"
    }
}
```

While the real AWS response looks like this:

```
{
    "Error": {
        "Message": "Not Found",
        "Code": "404"
    },
    "ResponseMetadata": {
        "RequestId": "0DE3423DC5314379",
        "RetryAttempts": 0,
        "HTTPStatusCode": 404,
        "HostId": "...",
        "HTTPHeaders": {
            "content-type": "application/xml",
            "server": "AmazonS3",
            "date": "Mon, 15 May 2017 13:10:51 GMT",
            "transfer-encoding": "chunked",
            "x-amz-request-id": "...",
            "x-amz-id-2": "..."
        }
    }
}
```

So I have the reverse situation to the original issue here - AWS responds with `Error.Code = 404` and moto responds with `Error.Code = NoSuchKey`.

Probably, the AWS response differs for different operations. Above I am using [Object.load](https://boto3.readthedocs.io/en/latest/reference/services/s3.html#S3.Object.load) which only sends `HEAD` request without actual object retrieval.
