### ISSUE TITLE
How to get mock JWKs uri with Moto in Docker

### ISSUE THREAD

**Issue by duc-cm** [spulec/moto#5727]
May be it relates to [#4601 question](https://github.com/spulec/moto/issues/4601)
But I do not know how to request such URL from Java to Moto in Docker.

When I call JWKs uri like this `https://cognito-idp.us-west-2.amazonaws.com/someuserpoolid/.well-known/jwks.json`,
it will go to the real AWS Cognito Idp and return an error.

Is there anything like `http://localhost:5000/${cognito_user_pool_id}/.well-known/jwks.json`

**Comment by bblommers** [comment]
Hi @duc-cm! I believe this question is already answered here: https://github.com/spulec/moto/issues/5225

Does that help you?

**Comment by duc-cm** [comment]
Sorry for my bad search. It solved my problem.

Thank you @bblommers

**Comment by bblommers** [comment]
Thanks for letting us know that solved it, @duc-cm.

Ultiimately this is our fault for not explaining this behaviour anywhere - I'm going to reopen this issue as a reminder for me to add some documentation.
