### ISSUE TITLE
describe_parameters depends on filter order, but shouldn't

### ISSUE THREAD

**Issue by mdavis-xyz** [spulec/moto#5741]
# Summary

When calling `ssm` `describe_parameters`, you can pass in a list of filters.
I have seen different behavior based on the order of my filters.
With certain orders, the values returned do not match the filters.

# MWE

Let's create two parameters, then filter them.
Run this script. Then comment out `with mock_ssm():` and unindent all lines below that, and run again, to test against real AWS.

```
import boto3
from moto import mock_ssm

with mock_ssm():
    client=boto3.client('ssm')
    param_names = []
    for x in 'ab':
        param_name = f"test_my_param_01_{x}"
        param_names.append(param_name)
        assert isinstance(x, str)
        client.put_parameter(
            Name=param_name,
            Value=f"Contents of param {x}", 
            Type='String',
            Tags=[
                {
                    'Key': 'hello',
                    'Value': 'world'
                },
                {
                    'Key': 'x',
                    'Value': x
                }
            ]
        )
    
    response = client.describe_parameters(
        ParameterFilters=[
            {
                "Key": "tag:x",
                "Option": "Equals",
                "Values": ['b']
            },
            {
                "Key": "tag:hello",
                "Option": "Equals",
                "Values": ['world']
            },
        ]
    )
    assert len(response['Parameters']) == 1, "not 1 result when hello is second"
    
    response = client.describe_parameters(
        ParameterFilters=[
            {
                "Key": "tag:hello",
                "Option": "Equals",
                "Values": ['world']
            },
            {
                "Key": "tag:x",
                "Option": "Equals",
                "Values": ['b']
            },
        ]
    )
    assert len(response['Parameters']) == 1, "not 1 result when hello is first"
    
    client.delete_parameters(Names=param_names)
```

## Expected behavior

When running against real AWS (no moto), the script runs without throwing any AssertionError. In both cases `describe_parameters` returns exactly 1 parameter, not 2.

## Actual behavior

When running with moto, the first assertion passes. Moto successfully evaluated the filter and deduced that only one parameter matches that filter.

Then we swap the order of the filter, and do the same thing again.
Moto now gives a different behavior. It returns both parameters. Even though one of them has a tag that mismatches the filter.

**Comment by mdavis-xyz** [comment]
Here's the culprit:

https://github.com/spulec/moto/blob/8f074b0799e4e5303f219549e177d52b016c2dfb/moto/ssm/models.py#L1612

That line returns True from the middle of the for loop. But that function is supposed to only return False from the for loop, and True at the end.

A solution would be something like:

```
            elif key.startswith("tag:"):
                what = key[4:] or None
                if not any((tag["Key"] == what and tag["Value"] in values) for tag in parameter.tag):
                    return False
```

**Comment by bblommers** [comment]
Thanks for investigating and posting the solution, @mdavis-xyz!
