### ISSUE TITLE
[dynamodb] Incorrect handling of array indices when removing multiple items from a list attribute

### ISSUE THREAD

**Issue by JonathanRohland-TNG** [spulec/moto#5748]
## [dynamodb] Incorrect handling of array indices when removing multiple items from a list attribute

We have noticed an issue with the dynamodb mock implementation related to update-queries with a remove-expression, in particular when multiple entries are removed from the same array:
For a remove expression like `REMOVE RelatedItems[1], RelatedItems[2]`, the entries at indexes 1 and 2 should be removed from the array (see [AWS Docs](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.UpdateExpressions.html#Expressions.UpdateExpressions.SET), I have also verified the expected behavior against the DynamoDB API).

Instead of removing the entries at index 1 and 2, moto will first remove the entry with index 1, then shift the remaining array entries and then remove the entry at index 2 (which previously was at index 3).

I have been able to reproduce this with moto 4.0.11 an boto3 1.26.23 using the following script:
```python
import boto3
from moto import mock_dynamodb

@mock_dynamodb
def test_multiple_remove_operations():
    session = boto3.Session()
    dynamodb = session.resource("dynamodb")
    table_name = "remove-test"

    dynamodb.create_table(
        TableName=table_name,
        KeySchema=[
            {"AttributeName": "key", "KeyType": "HASH"},
        ],
        AttributeDefinitions=[
            {"AttributeName": "key", "AttributeType": "S"},
        ],
        BillingMode="PAY_PER_REQUEST",
    )

    table = dynamodb.Table(table_name)
    table.put_item(
        Item={
            "key": "woop",
            "bla": ["1", "2", "3", "4", "5"],
        },
    )

    table.update_item(Key={"key": "woop"}, UpdateExpression="REMOVE bla[0], bla[1], bla[2]")

    result = table.get_item(Key={"key": "woop"})
    item = result["Item"]
    assert item["bla"] == ["4", "5"]
```

This results in the following AssertionError:
```
E       AssertionError: assert ['2', '4'] == ['4', '5']
E         At index 0 diff: '2' != '4'
E         Full diff:
E         - ['4', '5']
E         + ['2', '4']
```

**Comment by bblommers** [comment]
Thanks for raising this and providing the repro, @JonathanRohland-TNG! Marking it as a bug.
