### ISSUE TITLE
cloudformation update_stack response ResponseParserError

### ISSUE THREAD

**Issue by aiell0** [spulec/moto#575]
This is a follow-up to #550:

The update_stack mocking function was not updated with the fixes made in #550, and as a result, is attempting to parse JSON as XML, obviously returning an error. I don't have the resources to fix this at the moment, but from looking at the rest of the changes made in that ticket, doesn't seem like it would be very tough to fix.

I'll take a crack at it when I get a chance, but that may not be for a couple weeks.

**Comment by spulec** [comment]
Fixed with #590
