### ISSUE TITLE
Timestream Write Add a convienient way to access record

### ISSUE THREAD

**Issue by tuscaonline** [spulec/moto#5755]
Hi,

For the @mock_timestreamwrite can you add a convienient way to access to the table data?

Thank

**Comment by bblommers** [comment]
Hi @tuscaonline, this is how we verify the table data in our own tests:

```
from moto.core import DEFAULT_ACCOUNT_ID as ACCOUNT_ID
from moto.timestreamwrite.models import timestreamwrite_backends

backend = timestreamwrite_backends[ACCOUNT_ID]["us-east-1"]
records = backend.databases["mydatabase"].tables["mytable"].records
```
Does that work for you?

**Comment by tuscaonline** [comment]
Oh thank you very much. 
Can you add it to the manual ? It would be perfect

**Comment by bblommers** [comment]
Done!
http://docs.getmoto.org/en/latest/docs/services/timestream-write.html
