### ISSUE TITLE
RDS create_option_group supports only mysql engine

### ISSUE THREAD

**Issue by mayk0gan** [spulec/moto#5759]
`rds_client.create_option_group(
        OptionGroupName="default:postgres-13",
        EngineName="postgres",
        MajorEngineVersion="13",
        OptionGroupDescription="Default option group for postgres 13",
 )`

Raises: `botocore.exceptions.ClientError: An error occurred (InvalidParameterValue) when calling the CreateOptionGroup operation: Invalid DB engine: non-existent

/Users/may/Library/Caches/pypoetry/virtualenvs/venv-F1avdFZI-py3.9/lib/python3.9/site-packages/botocore/client.py:915: ClientError`

According to the tests, indeed only mysql engine is being checked, but RDS supports multiple engines (sqlserver, oracle, postgres, aurora-postgres, etc..). Link: https://github.com/spulec/moto/blob/4eb3944b1d9d8f513f1cb96425f60ae41039a831/tests/test_rds/test_rds.py
   - Tell us **what you expected to happen**. When we run your example code,
     what are we expecting to happen? What does "success" look like for your
     code?

I want to be able to test different database engines.

   - Tell us **what actually happens**. It's not helpful for you to say "it
     doesn't work" or "it fails". Tell us *how* it fails: do you get an
     exception? A hang? How was the actual result different from your expected
     result?

It throws a `ClientError` exception

   - Tell us **what version of Moto you're using**, and
     **how you installed it**. Tell us whether you're using standalone server
     mode or the Python mocks. If you are using the Python mocks, include the
     version of boto/boto3/botocore.

moto                                3.1.18
aioboto3                            10.2.0
boto3                               1.24.59
boto3-stubs                         1.26.27

**Comment by bblommers** [comment]
Thanks for raising this @mayk0gan - that's definitely a bug. We do allow other engines, but our list is not complete:

https://github.com/spulec/moto/blob/3c7bdcc5ea4d30681c5d8712926adedc294948fe/moto/rds/models.py#L1595:L1608

**Comment by bblommers** [comment]
Interestingly enough, I'm not able to create option groups for Postgres in the UI:
![Screenshot from 2022-12-14 11-13-29](https://user-images.githubusercontent.com/6058517/207594495-d8cdc275-7a03-4706-a3a8-497c5060a5d2.png)


But it does work in the CLI.

As far as I can tell, there is no documentation on what is allowed, so  I'll update the available engine versions based on what the CLI allows.
