### ISSUE TITLE
Route 53's create_hosted_zone mock does not align with AWS behaviour w.r.t. SOA record

### ISSUE THREAD

**Issue by codeocelot** [spulec/moto#5762]
## Reporting Bugs

[According to AWS docs,](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/SOA-NSrecords.html) "For each public hosted zone that you create, Amazon Route 53 automatically creates a name server (NS) record and a start of authority (SOA) record".   Moto currently does not create an SOA record when `create_hosted_zone` is called.  This makes it awkward to use moto in places where one does expect an SOA record to be created when the hosted zone is created.

Luckily, this doesn't look like a hard thing to add to the project.  If this is something you'd like to have in moto, I'm happy to open a PR with this change.

**Comment by bblommers** [comment]
A PR would be very welcome @codeocelot! We have some docs for new developers on how to get started: http://docs.getmoto.org/en/latest/docs/contributing/index.html

Let me know if you have any questions around this.

**Comment by codeocelot** [comment]
No problem @bblommers.  Just submitted #5763.  And to you a heartfelt thank you for maintaining this project, it's a great bit of code.
