### ISSUE TITLE
sqs not able to receive messages with message attributes

### ISSUE THREAD

**Issue by rita005** [spulec/moto#5769]
Hi.

When using:
    @aws-sdk for c#
    moto-server using the docker image

We are trying to mock sqs for integration testing in our api. We are able to create and connect to it, but when we try to receive messages with attributes, the ReceiveMessagesAsync hangs without giving any exception. We have tried to send messages with no message attributes and with different attributes than the requested ones and we are able to receive the messages.

We are creating our sqs via AWS cli:
```
aws sqs create-queue --queue-name test --endpoint-url http://localhost:8090/
```

Here is our API code to receive the messages:

```
var attributesList = new List<string> { "attribute1" };
var request = new ReceiveMessageRequest
            {
                QueueUrl = queueUrl,
                MaxNumberOfMessages = maxMessages,
                WaitTimeSeconds = waitTimeSeconds,
                MessageAttributeNames = attributesList
            };
var messageResponse = await _sqsClient.ReceiveMessageAsync(request);
```

Here is the message sent:

```
aws sqs send-message --queue-url http://localhost:8090/123456789012/test --message-body file://message-body.json --delay-seconds 10 --message-attributes file://message-attributes.json --endpoint-url http://localhost:8090/ 
```

Our message-body file:
```
{"Id": "81507a96-950c-41bb-967b-5811e1574e4f"}
```

And our message-atributes file:
```
{ "attribute1":{ "DataType":"String","StringValue":"att1"} }
```

It's important to notice that this workflow has the expected behavior when using aws sqs.

**Comment by bblommers** [comment]
Thanks for raising this @rita005 - this typically happens when Moto does not return a response in the exact same format as AWS.  
The AWS CLI and boto3 are quite forgiving in that respect, but other SDK's not quite.

I'll do some debugging to see if I can find out what's happening.

**Comment by rita005** [comment]
Tested the latest version with the c# aws sdk and it's working perfectly.
Thank you for your work!
