### ISSUE TITLE
Bug: global_sign_out does not actually sign out

### ISSUE THREAD

**Issue by deanq** [spulec/moto#5790]
The current test code for `global_sign_out` only checks against a refresh token action. If you do a sign out and try to access a protected endpoint, like say `get_user(AccessToken)`, it should result to `NotAuthorizedException`. This is not the case as of the current version of moto. I have noticed that all tests against sign out actions are limited to just checking if a refresh token is possible. That should be diversified beyond just a token refresh action.

I have tested my code against actual AWS Cognito without moto, and they do raise the `NotAuthorizedException` when you try to use an access token that has been signed out.

```
# add this to the file: /tests/test_cognitoidp/test_cognitoidp.py

@mock_cognitoidp
def test_global_sign_out():
    conn = boto3.client("cognito-idp", "us-west-2")
    result = user_authentication_flow(conn)

    conn.global_sign_out(AccessToken=result["access_token"])

    with pytest.raises(ClientError) as ex:
        conn.get_user(AccessToken=result["access_token"])

    err = ex.value.response["Error"]
    err["Code"].should.equal("NotAuthorizedException")
```

**Comment by bblommers** [comment]
Thanks for raising this and for providing the test case @deanq! Marking it as a bug.
