### ISSUE TITLE
Feature Request: Implementation for `CancelRotateSecret` is missing for secretsmanager

### ISSUE THREAD

**Issue by geektype** [spulec/moto#5807]
Currently the `secretsmanager` component is missing implementation for a few endpoints, `CancelRotateSecret` is one of them. I use this library extensivley and just recently came accross the requirement for this feature, happy to take a crack and submit a PR.

**Comment by bblommers** [comment]
Sounds good to me, @geektype! PR's and support for more features are always welcome. There is a section in the docs on how to get started: 
https://docs.getmoto.org/en/latest/docs/contributing/index.html

Let us know if you need any help!
