### ISSUE TITLE
Filter dicts have not been implemented in Moto for '%s' yet - mock_ec2

### ISSUE THREAD

**Issue by aiell0** [spulec/moto#581]
I am attempting to use the describe_instances function in boto3. I am supplying a filter that returns a string, and am receiving the following message:

NotImplementedError: (u"Filter dicts have not been implemented in Moto for '%s' yet. Feel free to open an issue at https://github.com/spulec/moto/issues", u'Architecture')

So I am following the suggestion and opening an issue. I will take a crack at this if I have time, but figured the community should know this is not supported at the current moment.

**Comment by spulec** [comment]
Fixed with #592

**Comment by spulec** [comment]
Can you try using `architecture` with a lowercase `a`? Does an upper-case `a` work with the Amazon API?
