### ISSUE TITLE
Multiple iot-data publish calls lead to None topic

### ISSUE THREAD

**Issue by lorenzo-eng** [spulec/moto#5811]
Calling
`boto3.client('iot-data', region_name='eu-central-1').publish(
        topic = my_topic,
        payload = my_payload,
        qos = 1
)`

More than once, causes the topic for all calls after the first one to be `None` inside `moto.iotdata.models.iotdata_backends[moto.core.DEFAULT_ACCOUNT_ID][MY_REGION].published_payloads`

### Example:

```python
import boto3
from moto import (
    mock_iotdata
)
import moto.core

with mock_iotdata():
    iot = boto3.client('iot-data', region_name='eu-central-1')
    iot.publish(
        topic = f"hello/world",
        payload = "something",
        qos = 1
    )
    iot.publish(
        topic = f"new/world",
        payload = "nothing",
        qos = 1
    )
    iot.publish(
        topic = f"old/world",
        payload = "anything",
        qos = 1
    )

    mock_backend = moto.iotdata.models.iotdata_backends[moto.core.DEFAULT_ACCOUNT_ID]['eu-central-1']
    print(mock_backend.published_payloads)
```
### Output:
```
[('hello/world', 'something'), (None, 'nothing'), (None, 'anything')]
```

### Debug attempt
I tried to understand what was going on and I found out that inside `botocore_subber.py` there is a `matchers.pop(found_index)` call that removes a regex to select the appropriate callback to dispatch the publish function so that only the first time the right dispatcher gets called.
I don't completely understand the goal of that call so it might be correct, but if I comment it out, the topic gets filled correctly.

### versions
```
Python 3.8.10
moto==4.0.12
```

Thanks

**Comment by bblommers** [comment]
Thanks for raising this and providing the repro-case @lorenzo-eng! Marking this as a bug.

**Comment by bblommers** [comment]
Hi @lorenzo-eng, just wanted to give you a heads-up: `published_payloads` will contain tuples of `(str, bytes)` as of Moto 4.1.13. 
Because it is possible to pass bytes to the `publish`-function, it is not always possible for Moto to decode the output - which is why we'll just store the raw incoming data instead. So your example output will become:
```
[('hello/world', b'something'), (None, b'nothing'), (None, b'anything')]
```

Related PR: #6509
