### ISSUE TITLE
S3 Bucket.get_key(<NAME>).size is equal to 0

### ISSUE THREAD

**Issue by Zulunko** [spulec/moto#59]
With a bucket "bucket" and a key with name "name", the following is equal to 0 regardless of the contents of the key:

```
bucket.get_key(name).size
```

Tested with the following:

```
@mock_s3
def test_get_key_size():
    conn = boto.connect_s3('the_key', 'the_secret')
    b = conn.create_bucket("test")
    k = Key(b, "hi")
    k.set_contents_from_string("hello")
    k.size.should.equal(5)
    b.get_key("hi")
    b.get_key("hi").size.should.equal(5)
```

The test fails on the last assertion (it gets 0 while expecting 5).

**Comment by matt-pazien** [comment]
I am currently experiencing the same issue with motor-0.4.25
