### ISSUE TITLE
Bump httppretty version

### ISSUE THREAD

**Issue by joshblum** [spulec/moto#593]
Would it be possible to bump the version of https://github.com/gabrielfalcao/HTTPretty? There is a bug in the current version which seems to be fixed. If there was no depreciation of python3 support in the newer version can this library bump which version it uses?

https://github.com/gabrielfalcao/HTTPretty/issues/224
https://github.com/gabrielfalcao/HTTPretty/issues/223

**Comment by spulec** [comment]
If there was no depreciation of python3 support, yes. Unfortunately, it looks like that isn't the case right now. Feel free to bump your version locally, but I don't see how we can break python3 support for our users. Going to close, but feel free to reopen if you have some ideas.
