### ISSUE TITLE
Incorrect behavior for BETWEEN and GT 

### ISSUE THREAD

**Issue by bastova** [spulec/moto#601]
I noticed a very strange behavior when trying to query my test dynamodb table with BETWEEN and GT comparison operators. Let's say I have 3 Items which I put into my table 'test-table': 
```
    data1 = {
      'uuid': 'foo',
      'storage_tag': 1,
      'id': 10
    }
    data2 = {
      'uuid': 'foo',
      'storage_tag': 1,
      'id': 30
    }
    data3 = {
      'uuid': 'foo',
      'storage_tag': 1,
      'id': 50
    }
```
Querying on **hash-key 'uuid'** and **range-key 'id'** with filters: **[uuid__eq : 'foo', id__between : (min, max)]** has the following results:
1. min = 5, max = 35 => [] // empty list
2. min = 10, max = 35 => [data1, data2]
3. min = 2, max = 35 => [data2]

It seems that the call with filter 'between' appends an extra 0 to the min value if the two numbers are of different digit-lengths. 

Querying on **hash-key 'uuid'** and **range-key 'id'** with filters: **[uuid__eq : 'foo', id__gt : val]** has the following results:
1. val = 5 => [data3]

In case of 'gt', it both appends a 0 to the 5 and also includes 50 in the result.

*****
I am running moto's local dynamodb in a vagrant instance. I was using awscli to query the table, here is an example query:
`aws dynamodb query --table-name test-table --key-conditions '{ "uuid" : {"AttributeValueList": [{"S":"foo"}], "ComparisonOperator": "EQ"}, "id" : {"AttributeValueList": [{"N":"5"}, {"N":"35"}], "ComparisonOperator": "BETWEEN"}}' --endpoint-url http://localhost:8001`

I am not sure whether it's an incompatibility bug between moto and vagrant or a bug in moto alone. As a suggestion, you could try adding a unit test with min and max values having different digit-lengths and see if you can reproduce this issue.

**Comment by prateekr** [comment]
I ran into the same problem using moto (ver: 0.4.23) dynamodb2 as a standalone server.  The error can be replicated using the code posted below:

```python
from boto.dynamodb2.fields import HashKey, RangeKey
from boto.dynamodb2.types import STRING, NUMBER
from boto.dynamodb2.table import Table
from boto.dynamodb2.layer1 import DynamoDBConnection

conn = DynamoDBConnection(proxy='localhost', proxy_port=8001, is_secure=False)
schema = [HashKey('uuid', STRING), RangeKey('id', NUMBER)]
table_name = 'test_table'
table = Table.create(table_name=table_name, schema=schema, connection=conn)
table.put_item({'uuid': 'test1', 'id': 0})
table.put_item({'uuid': 'test1', 'id': 10})
table.put_item({'uuid': 'test1', 'id': 50})

>>> [item['id'] for item in table.query_2(uuid__eq='test1')]
[Decimal('0'), Decimal('10'), Decimal('50')]
>>> [item['id'] for item in table.query_2(uuid__eq='test1', id__gte=5)]
[Decimal('50')]
>>> [item['id'] for item in table.query_2(uuid__eq='test1', id__gte=9)]
[]
>>> [item['id'] for item in table.query_2(uuid__eq='test1', id__gte=10)]
[Decimal('10'), Decimal('50')]
```

**Comment by spulec** [comment]
Thanks!

**Comment by prateekr** [comment]
Thanks for the quick fix!
