### ISSUE TITLE
Problem when running moto with boto3 on proxy

### ISSUE THREAD

**Issue by ptimsonbbc** [spulec/moto#605]
When I run the following unit test on my proxied network

```
import boto3
import unittest
from moto import mock_s3

class Test(unittest.TestCase):

    @mock_s3
    def test_create_bucket(self):
        s3 = boto3.resource('s3')
        s3.create_bucket(Bucket='mybucket')

if __name__ == '__main__':
    unittest.main()
```

The script hangs on boto3.resource('s3').
However when I disconnect from the network it works and if I use boto2 it works

Any ideas? Cheers!

**Comment by kapilt** [comment]
did you set no_proxy env var for the metadata server address 169.254.169.254?

**Comment by ptimsonbbc** [comment]
@kapilt Great thanks. For anyone else viewing this add this to your script:
`os.environ['no_proxy'] = '169.254.169.254'`
