### ISSUE TITLE
moto hangs if there's a = in the key name

### ISSUE THREAD

**Issue by mbomio** [spulec/moto#611]
Hi, moto is hanging when I try to create a key with a `=` in its name.

``` python
import boto

@mock_s3
def test_hanging_moto():
    conn = boto.connect_s3()
    bucket = conn.create_bucket('my-bucket')
    k = bucket.new_key('d=01012016/000000')
    k.set_contents_from_string('somedata')
```

Thanks!

**Comment by mbomio** [comment]
I was able to debug the issue a little bit further. Seems liek the real issue is that I am getting an:
```

**Comment by spulec** [comment]
Hmmm, this seems to work for me. What version of boto are you using?

**Comment by mbomio** [comment]
Hi @spulec. I am using `boto==2.39.0`

**Comment by spulec** [comment]
Hmm, I'm still not able to recreate this. Can you run a `pip freeze` so we can see if it is another version of something else?

**Comment by mbomio** [comment]
sure, here it goes:
```
pip freeze
BeautifulSoup==3.2.1
beautifulsoup4==4.3.2
boto==2.39.0
coverage==4.0.3
DateTime==4.0.1
Flask==0.10.1
httpretty==0.8.10
itsdangerous==0.24
Jinja2==2.8
MarkupSafe==0.23
moto==0.4.23
nose==1.3.7
nose-testconfig==0.9
nosexcover==1.0.10
numpy==1.11.0rc1
pandas==0.14.0
python-dateutil==2.3
pytz==2014.4
requests==2.3.0
six==1.10.0
Werkzeug==0.11.9
xmltodict==0.10.1
zope.interface==4.1.3
```

**Comment by mbomio** [comment]
@spulec  also tried upgrading to `boto 2.41.0` but same thing happens.

**Comment by spulec** [comment]
Are you using the latest version of moto? Which version of python?

**Comment by mbomio** [comment]
I am using python 2.7 and `moto==0.4.23`

**Comment by spulec** [comment]
Can you try upgrading to the most recent version of moto? I'm not able to reproduce this against the newest version.

**Comment by spulec** [comment]
Going to close out. If this is still happening against the `master` branch of moto, feel free to reopen.
