### ISSUE TITLE
Stand-alone Server Mode + boto3

### ISSUE THREAD

**Issue by snordhausen** [spulec/moto#614]
Hi!

I'm trying to get boto3 to connect to a moto stand-alone server as part of an integration test. I had this running properly with the old boto2 by simply following moto's README. But for boto3, I just cannot find an official way of doing this. The best I was able to come up with was a global monkey-patching of botocore's Endpoint class like this:

```
from botocore import endpoint

class MyEndpoint(endpoint.Endpoint):
    def __init__(self, host, *args, **kwargs):
        super(MyEndpoint, self).__init__('http://127.0.0.1:5000', *args, **kwargs)

endpoint.Endpoint = MyEndpoint
```

But that's really inelegant because I have to modify the code prior to the integration test.

Note that it is only the stand-alone moto that is problematic. The moto.mock_XXX decorators are working just fine.

**Comment by spulec** [comment]
It looks like you should be able to do something like

```python
import os
os.environ["HTTP_PROXY"] = "http://127.0.0.1:5000"
os.environ["HTTPS_PROXY"] = "https://127.0.0.1:5000"
```

**Comment by benregn** [comment]
You can pass an `endpoint_url` to `boto3.resource` (and to `boto3.client`):

```python
boto3.resource(
    service_name='s3',
    region_name='us-west-1',
    endpoint_url='http://localhost:5000',
)
```

**Comment by spulec** [comment]
Thanks for that! I added it to the readme
