### ISSUE TITLE
how to mock boto3.client('scheduler'..) ?

### ISSUE THREAD

**Issue by davit555** [spulec/moto#6146]
I couldn't find a way to doing this even after downloading the last version...

**Comment by bblommers** [comment]
Hey @davit555, thanks for raising this. That service is not supported yet - will mark it as an enhancement.

Which methods were you after specifically?

Just to let you know, if this is an urgent requirement, you can patch boto3 manually until we add support for this:
https://docs.getmoto.org/en/latest/docs/services/patching_other_services.html

**Comment by davit555** [comment]
hey thank you for your quick reply, didn't know about patching other services through moto )


basically I was trying to mock the 

https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/scheduler/client/create_schedule.html

https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/scheduler/client/delete_schedule.html

methods
