### ISSUE TITLE
Add support for tag filters to DescribeNetworkInterfaces in mock_ec2

### ISSUE THREAD

**Issue by codesplicer** [spulec/moto#619]
Hi,

Get the following when running a test I've setup: 

``` python
NotImplementedError: The filter 'tag:component' for DescribeNetworkInterfaces has not been implemented in Moto yet.
```

Happy to submit a PR for this if you could give me a few pointers as to where this needs to be added.

**Comment by spulec** [comment]
It looks like we will need another conditional [here](https://github.com/spulec/moto/blob/master/moto/ec2/models.py#L239). A PR would happily be accepted.
