### ISSUE TITLE
SQS Queue URL is pointing to AWS

### ISSUE THREAD

**Issue by mariusgrigaitis** [spulec/moto#626]
I'm trying to mock SQS using moto_server

Currently if you create SQS Queue, you get QueueUrl like this:

```
{
    "QueueUrl": "http://sqs.us-east-1.amazonaws.com/123456789012/<queue_name>"
}
```

An implementation of SQS client when it has only QueueName is as following:

1) url = client.getQueueUrl(QueueName=queue_name)
2) client.sendMessage(QueueUrl=url, MessageBody=body)

Problem is that client (SDK) with endpoint of moto_server sends getQueueUrl to mocked SQS but sendMessage request goes to non-mocked AWS (goes to sqs.us-east-1.amazonaws.com)

Would it make sense to have different URL returned by getQueueURL? Maybe the same one as request host?

**Comment by spulec** [comment]
I think that makes sense. Would be happy to accept a PR doing that.
