### ISSUE TITLE
manually input an ec2 event

### ISSUE THREAD

**Issue by TKim18** [spulec/moto#641]
Currently trying to make a unit test to see if my Python script correctly returns scheduled EC2 events. There is no way to schedule an EC2 event to my knowledge (different from setting a rule on AWS CloudWatch because it's propagated by AWS itself) so I want to manually input the event in the output format of the ec2 describe_instance_status call (similar to the EC2_INSTANCE_STATUS XML seen at the bottom of https://github.com/spulec/moto/blob/master/moto/ec2/responses/instances.py). Is there any way to perform this or perhaps simulate such an EC2 event through moto?

**Comment by spulec** [comment]
Not ideal, but you can do something like this to manually modify the backend.

```python
from moto.ec2.models import ec2_backends
ec2_backends['us-east-1'].reservations[reservation_id] ...
```

Please reopen if that doesn't work.
