### ISSUE TITLE
Must require older jinja or remove requirement

### ISSUE THREAD

**Issue by jhaberstroh-sharethis** [spulec/moto#6431]
I searched github issues for jinja, nothing found.

When I call moto_server after just having pip-installed it, I get the following error:
```
Traceback (most recent call last):
  File "/Users/john/opt/anaconda3/bin/moto_server", line 5, in <module>
    from moto.server import main
  File "/Users/john/opt/anaconda3/lib/python3.9/site-packages/moto/server.py", line 10, in <module>
    from moto.moto_server.werkzeug_app import (
  File "/Users/john/opt/anaconda3/lib/python3.9/site-packages/moto/moto_server/werkzeug_app.py", line 8, in <module>
    from flask import Flask
  File "/Users/john/opt/anaconda3/lib/python3.9/site-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
ImportError: cannot import name 'escape' from 'jinja2' (/Users/john/opt/anaconda3/lib/python3.9/site-packages/jinja2/__init__.py)
```

A question on SO attributes this to removal in Jinja 3.1.0:
https://stackoverflow.com/questions/71718167/importerror-cannot-import-name-escape-from-jinja2

I am using pip-installed `moto==4.1.11` and `jinja==3.1.2`, and `flask==1.1.2`. My flask version is packaged with Anaconda, so it didn't upgrade:
```
❯ pip install flask
Requirement already satisfied: flask in ./opt/anaconda3/lib/python3.9/site-packages (1.1.2)
```
This is resolved in newer version of `flask`, so maybe it would make sense to require `flask>=2.0`?
https://github.com/pallets/flask/issues/4494

**Comment by bblommers** [comment]
Hi @jhaberstroh-sharethis, I don't know where your jinja-requirement comes from, but `flask==1.1.2` requires `jinja < 3`: https://github.com/pallets/flask/blob/1.1.x/setup.py

I'm sure there are people are force to use an older `flask` though, for whatever reason, and I don't want to force them to upgrade. Ensuring that the right `jinja` version is installed (for whatever `flask`-version you have) sounds like the better solution.
