### ISSUE TITLE
SQS add_permission() Is Not Implemented

### ISSUE THREAD

**Issue by nadersalehi** [spulec/moto#647]
Running this code under moto raises 'NotImplementedError' for the add_permission() function:

`

```
@mock_sns
@mock_sqs
def my_test():
    sns = boto3.resource('sns', region_name=region_name)
    topic = sns.create_topic(Name=registrar_topic)

    account_id = topic.arn.split(':')[4]

    sqs = boto3.resource('sqs', region_name=region_name)
    queue = sqs.create_queue(QueueName='my_dns_queue')
    queue.add_permission(Label='SNSSendMessage',
                         AWSAccountIds=[account_id],
                         Actions=['SendMessage'])
```

`

Below is a snippet of the stack trace:

self = <botocore.retryhandler.ExceptionRaiser object at 0x7f53ab86acd0>
attempt_number = 1
caught_exception = NotImplementedError(u'The add_permission action has not been implemented',)

```
def _check_caught_exception(self, attempt_number, caught_exception):
    # This is implementation specific, but this class is useful by
    # coordinating with the MaxAttemptsDecorator.
    # The MaxAttemptsDecorator has a list of exceptions it should catch
    # and retry, but something needs to come along and actually raise the
    # caught_exception.  That's what this class is being used for.  If
    # the MaxAttemptsDecorator is not interested in retrying the exception
    # then this exception just propogates out past the retry code.
```

> ```
>   raise caught_exception
> ```
> 
> E       NotImplementedError: The add_permission action has not been implemented

**Comment by spulec** [comment]
Thanks for opening. This particular feature is not a priority of mine since it isn't something I use, but very happy to accept pull requests if anyone has time.

**Comment by spulec** [comment]
Added with https://github.com/spulec/moto/commit/75f0deb8289dbd21dc377d164995765042b4623a
