### ISSUE TITLE
KMS DescribeKey functionality

### ISSUE THREAD

**Issue by griffinb** [spulec/moto#650]
The AWS documentation states that `DescribeKey` takes a required `KeyId` parameter that can be `a globally unique identifier, a fully specified ARN to either an alias or a key, or an alias name prefixed by "alias/".`  When I try using `moto` to mock KMS and call the `describe_key` function using `boto3`, I get this error when I use the key's ARN:

`nose.proxy.ClientError: An error occurred (Unknown) when calling the DescribeKey operation: None`

However, if I change my code to use the key's globally unique identifier, `moto` works as expected.  Using `boto3` in a Python interpreter and making the calls with either the key's globally unique identifier or the key's ARN results in the same behavior as the AWS docs say.

**Comment by rocky4570** [comment]
I have put a pull request in for this as had same issue allows describe on alias and arn/keyid. See https://github.com/spulec/moto/pull/721

**Comment by spulec** [comment]
Fixed with #721
