### ISSUE TITLE
moto 0.4.24 and later fail (AWS returned an error)

### ISSUE THREAD

**Issue by deinarson** [spulec/moto#660]
Hi folks,
   Our tests started failing after updating from 0.4.23.  Both 0.4.24 and 0.425 exhibit this issue and 0.4.23 works fine.  We are using boto 2.39.0 and evidently python 2.7 (2.7.11). (_Out of interest I ran tcpdump and there are no attempts to connect out._). Were we supposed to have change something between versions? I see we changed httpretty ( httpretty (0.8.10) installed )

## Error 

	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/site-packages/moto/core/models.py", line 71, in wrapper
	    result = func(*args, **kwargs)
	  File "/usr/local/lib/python2.7/site-packages/moto/core/models.py", line 71, in wrapper
	    result = func(*args, **kwargs)
	  File "/usr/local/lib/python2.7/site-packages/moto/core/models.py", line 71, in wrapper
	    result = func(*args, **kwargs)
	  File "/docker/test/test_ctack.py", line 316, in test__check_1_exist
	    create.create_(conn, params, template) # Create -1
	  File "create.py", line 683, in create_
	    raise VInternalException("ERROR: Unable to create the stack, AWS returned an error.", error)
	VInternalException: ERROR: Unable to create the , AWS returned an error., 
	DESCRIPTION: BotoServerError: 400 Bad Request
	<?xml version="1.0" encoding="UTF-8"?>
	  <Response><Errors><Error>
	        <Code>ValidationError</Code>
	        <Message>HealthCheck Target must begin with one of HTTP, TCP, HTTPS, SSL</Message>
	      </Error></Errors><RequestID>7a62c49f-347e-4fc4-9331-6e8eEXAMPLE</RequestID>
	</Response>

**Comment by deinarson** [comment]
After running git blame, this stops working at `Test key head version_id support using boto3's head_object.`  commit ebb00a3bfe2676cae985b4801102bf808f546283

**Comment by deinarson** [comment]
Take two:  
After running `git blame` I see that this starts at commit a600deb96a2391454ac913d8731469e2e2e91235
 `Fix merge conflicts and add EC2 Instance delete. Closes #576.`

I am now looking at the code, but this seems to be a big commit.

**Comment by 2rs2ts** [comment]
I wrote this. Can you show what you are trying to do? The error you're seeing implies that you've misconfigured your ELB's health check in your CloudFormation template.

**Comment by deinarson** [comment]
Hi Andrew
  Thanks for your time... Sorry this isn't my code so its a little fuzzy to me, but it seems that the "Ref" in the CF template are not getting interpreted? 

`data` is a dict that contains the various required bits, one of them being `"Healthcheck"` which is set to `data["Healthcheck"]="http:8080/info"`.

The unittest fails on this:

    connections.connection_s3.create_stack(
        stackname, template_body=template_body, template_url=template_url, parameters=get_params(data),
        notification_arns=[], disable_rollback=True, timeout_in_minutes=None, capabilities=None)


In the template we have everything else hard coded.

    "HealthCheck" : {
       "Target" : { "Ref" : "Healthcheck" },
       "HealthyThreshold" : "2",
       "UnhealthyThreshold" : "5",
       "Interval" : "120",
       "Timeout" : "60"
    },

If I change { "Ref" : "Healthcheck" },  to "HTTP:80" everything passes. But this works up to the aforementioned commit.  fwiw, I have done other debugging/hacking to no avail.

Thanks for your time, it is much appreciated.

**Comment by deinarson** [comment]
Hi Andrew,
   Sorry for taking your time, it seems the answer was staring me in the face.  HTTP must be in all caps.

Thank you for your time, 
Cheers!
