### ISSUE TITLE
IAM responses only return canned ARNs

### ISSUE THREAD

**Issue by mikegrima** [spulec/moto#663]
The IAM responses are only returning hard-coded account number and role data, not role data that gets dynamically created with the tests.

For example, when listing IAM roles, it returns a role with the ARN:

```
arn:aws:iam::123456789012:role/application_abc/component_xyz/S3Access
```

This should be dynamically listed based on the roles that get created.

An example for where this is being set is here: https://github.com/spulec/moto/blob/68de6feb019e49fc7cf337940feb9c1caa86b9b5/moto/iam/responses.py#L373

**Comment by mikegrima** [comment]
@spulec You can assign this to me. When I have some time, I will submit the PR.

**Comment by mikegrima** [comment]
Took a stab at it... It is unfortunately a lot more difficult than I anticipated.

The problem is that it's hard to inject an account id.  This is not included in the connection object and there is no straightforward way to add it to the object after it is created.  

If I am able to do that, then generating a dynamic ARN is easy.

**Comment by spulec** [comment]
Hmmmm....we could allow the user to pass it to the decorator, but that seems like it could get messy and repetitive. I've been punting on having a config file, but that would be another solution.

**Comment by spulec** [comment]
I made this more dynamic with https://github.com/spulec/moto/commit/bba197e29f7fdd635fcbcb2cd18993d839f93f39, but the account ids are still hardcoded. It should be a bit easier to monkey-patch as a module-level constant though.

I've been thinking more about creating some type of real sessions and accounts with Moto in the future, which I think will provide a better solution.
