### ISSUE TITLE
HTTPretty broken

### ISSUE THREAD

**Issue by aop** [spulec/moto#667]
Why is httpretty==0.8.10 required in setup.py?

As per [this](https://github.com/spulec/moto/issues/95) problem there is a fix in httpretty 0.8.14. We should update to that asap

**Comment by spulec** [comment]
You can feel free to manually override this requirement yourself, but newer versions of HTTPretty are not necessarily going to [work with Python3](https://github.com/gabrielfalcao/HTTPretty#disclaimer). For that reason, I would prefer to not change the default.
