### ISSUE TITLE
Moto sqs does not mock dead letter queue

### ISSUE THREAD

**Issue by ronin13** [spulec/moto#675]
I don't see support of dead letter queue, ie. RedrivePolicy in the code. 

So, something such as queue.attributes['RedrivePolicy'] raise KeyError.

**Comment by spulec** [comment]
You are correct, Moto does not support that feature yet. I would be happy to accept a PR if someone gets some time.

**Comment by bblommers** [comment]
This is supported by now - see https://github.com/spulec/moto/blob/d8097b24dc25c5435e99802cc41921ae5947f778/tests/test_sqs/test_sqs.py#L73
