### ISSUE TITLE
Support: `EventBridgeConfiguration` for `S3.Client.put_bucket_notification_configuration` request parameter

### ISSUE THREAD

**Issue by tsugumi-sys** [spulec/moto#6790]
According to boto3 document, we can support `EventBridgeConfiguration` for `put_bucket_notification_configuration` request.

<img width="593" alt="image" src="https://github.com/getmoto/moto/assets/61897166/ae94c4ba-e58a-40d3-b503-20e35ead0d46">

https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3/client/put_bucket_notification_configuration.html

However, moto does not support this. How about supporting EventBridge notifications?

https://github.com/getmoto/moto/blob/ca9d8fc4208f0f7aab6c3e9769977598731a0937/moto/s3/models.py#L1248-L1269

**Comment by bblommers** [comment]
Makes sense @tsugumi-sys. 

Do you need to actually send the notifications to EventBridge as well? Then we'll also have to extend the `send_event`-method:

https://github.com/getmoto/moto/blob/ca9d8fc4208f0f7aab6c3e9769977598731a0937/moto/s3/notifications.py#L44

**Comment by tsugumi-sys** [comment]
> Do you need to actually send the notifications to EventBridge as well? Then we'll also have to extend the send_event-method:

Actually sending the notifications to EventBridge is also needed for [this issue](https://github.com/getmoto/moto/issues/5906) :)
So I want to try it here!

**Comment by tsugumi-sys** [comment]
@bblommers 
I haven't committed for a while, but I've started trying on this task again.
