### ISSUE TITLE
S3 tags are not persisted

### ISSUE THREAD

**Issue by johnmcteague** [spulec/moto#683]
Running a moto server (on port 5012 in this example), when I create bucket and add tags, the tags are not persisted.

Assuming moto_server is running using the s3bucket_path mode on http://localhost:5012, the following code prints None with v0.4.25

```
s3 = boto3.resource('s3',endpoint_url="http://localhost:5012")

bucketName = ''.join(random.choice(string.ascii_lowercase) for _ in range(20))
bucket = s3.Bucket(bucketName)
bucket.create()

tagging = bucket.Tagging()

tagging.put(
        Tagging={
            'TagSet': [
                {
                    'Key': 'foo',
                    'Value': 'bar'
                }
            ]
        }
    )

bucket2 = s3.Bucket(bucketName)

tags = bucket2.Tagging().tag_set

print tags
```

**Comment by rocky4570** [comment]
Yes I found the same issue and started some preliminary work on it but got side tracked.

**Comment by johnmcteague** [comment]
I have a bunch of patches for this and others. Waiting on corporate red tape to give thumbs up to contributing back.

**Comment by spulec** [comment]
A patch would be much appreciated!

**Comment by spulec** [comment]
This seems to be fixed now; feel free to reopen if you see otherwise
