### ISSUE TITLE
Help with s3 server

### ISSUE THREAD

**Issue by amitsaha** [spulec/moto#685]
I am running `moto_server s3` locally. Now consider the following script to create a bucket:

```
import boto
from moto import mock_s3

@mock_s3
def create_bucket():
    conn = boto.connect_s3()
    conn.create_bucket('my_bucket')

create_bucket()

```

This is what I see on the server side when I run the above script _once_:

```
127.0.0.1 - - [26/Aug/2016 07:43:57] "PUT http://my_bucket1.s3.amazonaws.com/ HTTP/1.1" 200 -
127.0.0.1 - - [26/Aug/2016 07:43:58] "PUT http://my_bucket1.s3.amazonaws.com/ HTTP/1.1" 200 -
127.0.0.1 - - [26/Aug/2016 07:43:58] "PUT http://my_bucket1.s3.amazonaws.com/ HTTP/1.1" 200 -
127.0.0.1 - - [26/Aug/2016 07:44:00] "PUT http://my_bucket1.s3.amazonaws.com/ HTTP/1.1" 200 -
127.0.0.1 - - [26/Aug/2016 07:44:07] "PUT http://my_bucket1.s3.amazonaws.com/ HTTP/1.1" 200 -
127.0.0.1 - - [26/Aug/2016 07:44:12] "PUT http://my_bucket1.s3.amazonaws.com/ HTTP/1.1" 200 -
127.0.0.1 - - [26/Aug/2016 07:44:27] "PUT http://my_bucket1.s3.amazonaws.com/ HTTP/1.1" 200 -
```

My client script ends with:

```
Traceback (most recent call last):
  File "s3.py", line 10, in <module>
    create_bucket()
  File "/usr/local/lib/python2.7/dist-packages/moto/core/models.py", line 71, in wrapper
    result = func(*args, **kwargs)
  File "s3.py", line 8, in create_bucket
    conn.create_bucket('my_bucket1')
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/connection.py", line 616, in create_bucket
    data=data)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/connection.py", line 668, in make_request
    retry_handler=retry_handler
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1071, in make_request
    retry_handler=retry_handler)
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1030, in _mexe
    raise ex
httplib.BadStatusLine: ''
```

When I go to 127.0.0.1:500 from the browser, I see:

```
NoSuchBucket The specified bucket does not exist 127 7a62c49f-347e-4fc4-9331-6e8eEXAMPLE 
```

I am using boto 2.42.0 and moto 0.4.25.   Any ideas what may be happening?

**Comment by spulec** [comment]
What version of HTTPretty are you using?

**Comment by amitsaha** [comment]
@spulec I have 0.8.10 installed

**Comment by spulec** [comment]
This looks to be working for me on the newest version of moto. Can you try that?

**Comment by amitsaha** [comment]
Doesn't seem like. Will it possible to share how you are testing this? I may be doing something wrong..

**Comment by spulec** [comment]
Are you creating a `~/.boto` as specified in the README?

**Comment by amitsaha** [comment]
No, since it says "If you want to use boto with this (using the simpler decorators above instead is strongly encouraged)," - and I am using the decorator..Not sure if I misunderstood something?

**Comment by spulec** [comment]
Yes, sorry. There are two different ways to use moto: everything stored in memory in the one process or with a separate standalone server mode (`moto_server`). I generally advise people to use the former. 

If you added a `conn.get_all_buckets()` to the end of your function and printed the results, it should show that a bucket has been created.

**Comment by spulec** [comment]
Going to close this out. Feel free to reopen if you need more help.
