### ISSUE TITLE
mock_cloudwatch does not implement get_metric_statistics

### ISSUE THREAD

**Issue by ex-nerd** [spulec/moto#696]
Docs:
- http://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_GetMetricStatistics.html
- http://botocore.readthedocs.io/en/latest/reference/services/cloudwatch.html#CloudWatch.Client.get_metric_statistics

**Comment by MainAero** [comment]
+1

**Comment by spulec** [comment]
Thanks! Adding as a feature request.
