### ISSUE TITLE
Describe snapshots filter NotImplementedError

### ISSUE THREAD

**Issue by akak548** [spulec/moto#709]
My tests are still failing when trying to filter based on snapshot status. I have read over ticket #525 and verified that I am running moto 0.4.27 and boto3 1.4.0 The code is straight forward.

```
response = ec2_client.describe_instances(
    Filters=[
        {
            'Name': 'status',
            'Values': 'completed'   
        }
    ]
)
```

**Comment by spulec** [comment]
Are you trying to filter snapshots or instances (the title says the former, the code seems to do the latter)?

**Comment by spulec** [comment]
Closing this out; feel free to reopen with more info.
