### ISSUE TITLE
GPL Dependency

### ISSUE THREAD

**Issue by jzelinskie** [spulec/moto#717]
At some point you guys added `sure` as a dependency. Sure is licensed under the GPL and thus cannot be use in a number of projects. We depend on this library, but cannot ship GPL code. Are you interested in working around this issue at all?

**Comment by andrewgross** [comment]
IANAL. Is it an issue to use `moto`, even though it is not used in the packaged version of the projects(available on PyPI?  It is only used in the development of the project, but it is not bundled with the code.

**Comment by jzelinskie** [comment]
If that's the case, can you remove `sure`'s existence from moto's `setup.py`? Right now we basically have a script that searches for the GPL in the PyPi license data of each package in our requirements.txt and the latest `moto` is bringing `sure` into our project.

**Comment by andrewgross** [comment]
Hmm, I think that could be doable.  A quick search doesn't have `sure` anywhere but in `test_` files.

**Comment by andrewgross** [comment]
We already have `sure` listed in `requirements-dev.txt`, but it seems like we re-list it in `setup.py`.  Given that we don't even lock a `sure` version in `setup.py`, and that it is the only testing requirement, I think it can be safely removed.  I will try a PR with it.

**Comment by andrewgross** [comment]
Same with `freezegun`.

**Comment by spulec** [comment]
Fixed with #719
