### ISSUE TITLE
Like to propose the idea of infrastructure failures being added to moto.

### ISSUE THREAD

**Issue by rocky4570** [spulec/moto#722]
Moto is a great tool for doing tests etc, but it doesnt provide the ability to test for failures in ones code which occur in AWS, well at least not what I have seen? Such as an ERROR on volume state or API limit request exceeded. It would be good to inject errors being reported back by moto in a way which can be configurable to the moto user.

I must admit I havent done any analysis on whether there is a simple method to manipulate the models in the backend (tried once eg after an instance was created, but didnt work as hoped) - I dont want to go too deep into monkey patching - as one might as well go back to mocking the situation, however would be good to have a simplified way, just as we can mock EC2 instances.

A thought would be at the decorator level for the service being used - such as @mock_ec2(error_rate=50) or such so that in this case a random failure rate of up to 50% on creations (EBS etc) could be generated.

Dont know if any others have a need for this?

**Comment by spulec** [comment]
It isn't something I've heard from others. I'm struggling to find a simple way to do this.

I would be open to a proposal though if someone comes up with a good idea.

**Comment by stevemac007** [comment]
I would like to see the way of simulating errors on the API, a lot of the python in our codebase exists to handle error situations to provide a more reliable interface to AWS.

Controlling the simulation of the errors on AWS API calls would be excellent.

**Comment by spulec** [comment]
Good to know. Proposals welcome

**Comment by evanstachowiak** [comment]
I'd definitely like to see this implemented as well.

I would propose being able to pass in a response when registering a call. For instance, I'm implementing `register_task_definition`. It already accesses a parameterized containerDefinitions, why not be able to override response_object as well? The default can behave as is and if one wanted to test failures, then pass in a custom response object.

Thoughts?

**Comment by rocky4570** [comment]
I was looking at using the decorator as is obvious location and explicit in definition, as cant interfere with the AWS API.

@mock_ec2(ebs_failures=10, ec2_failures=10)

Something like that and values are based on percentage - which could be injected with random values for truly testing your code. Standard mocks would not have any errors. Server version could just have them locked in to mimic true functionality or part of the server config.

API Limit Exceeded messages could just be coded in - though some major work retro fitting it in. Each response would need to save context for a period of time.

**Comment by spulec** [comment]
Going to close this out; feel free to open new issues with proposals.
