### ISSUE TITLE
Dynamodb has_item causes scan problems

### ISSUE THREAD

**Issue by helenst** [spulec/moto#731]
Calling `has_item` for an item that doesn't exist, and then calling `scan()` causes `AttributeError: 'dict' object has no attribute 'attrs'`

Example of behaviour that causes this:

``` python
from moto import mock_dynamodb
import boto


with mock_dynamodb():
    conn = boto.connect_dynamodb()
    table = conn.create_table(
        name='mytable',
        schema=conn.create_schema(
            hash_key_name='name',
            hash_key_proto_value=str,
        ),
        read_units=1,
        write_units=1
    )
    print(list(table.scan()))
    table.has_item('something')
    print(list(table.scan()))
```

`has_item` calls down to `Table.get_item` in `dynamodb/models.py`. This accesses `self.items`, which is a `defaultdict` whose default value is an empty dict. This results in an empty dict being set in `self.items`. The `scan()` call in `dynamodb/responses.py` does not handle dicts (or anything other than an Item)

Replacing the error line in `dynamodb/responses.py` with the following code appears to work:

``` python
"Items": [item.attrs for item in items if item],
```

I'm not very familiar with this library (only started using it today) but happy to submit a PR if that seems like the right thing to do.

**Comment by spulec** [comment]
Yes, that sounds like the right solution. A PR would be great!
