### ISSUE TITLE
EC2 security groups - can add same rule twice

### ISSUE THREAD

**Issue by oridistor** [spulec/moto#737]
I need to simulate the situation where I get an error from AWS when I try to add a rule that already exists in the system (as my code catches that exact error when calling authorize_security_group) but the moto mock system just adds the new same rule next to the original one instead of doing a set test.

This means that moto behaves differently from boto in this exact situation.

**Comment by spulec** [comment]
Thanks!

**Comment by oridistor** [comment]
Thanks for fixing it! 

But, for better testing (I myself need to ignore the duplicate errors on my side, and make sure they are those duplicate errors) it would be better if we would get an exception which extends EC2ResponseError with the error_code of "InvalidPermission.Duplicate", that way I can test that my code does what I expect it to do and not anything else.

**Comment by spulec** [comment]
Ah, thanks. I think it should work now with https://github.com/spulec/moto/commit/8a803cdbaf3dfc2c515e3d71df5412bc1dbe16b8

**Comment by oridistor** [comment]
Thanks! Looks good!
