### ISSUE TITLE
Missing S3 canned ACL: aws-exec-read

### ISSUE THREAD

**Issue by danielkza** [spulec/moto#740]
I get the following exception:

```
AssertionError: Unknown canned acl: aws-exec-read
```

But it exists, at least according to the [boto3 documentation](http://boto3.readthedocs.io/en/latest/reference/services/s3.html#S3.Bucket.put_object).

**Comment by spulec** [comment]
I haven't had a chance to actually implement it, but fixed it so that it won't throw an exception.
