### ISSUE TITLE
example from README fails in python3 - comparing bytes to (unicode) string

### ISSUE THREAD

**Issue by dtenenba** [spulec/moto#747]
Running the first example in the README under python 3.5.2, the assertion fails:

``` python
assert conn.get_bucket('mybucket').get_key('steve').get_contents_as_string() == 'is awesome'
```

Because 'is awesome' is a (unicode) string, and `conn.get_bucket('mybucket').get_key('steve').get_contents_as_string()` returns an object of type `bytes`. 

``` python
mock = moto.mock_s3()
mock.start()
conn = boto.connect_s3()
conn.create_bucket('mybucket')
model_instance = MyModel('steve', 'is awesome')
model_instance.save()
actual = conn.get_bucket('mybucket').get_key('steve').get_contents_as_string()
actual # returns "b'is awesome'"
actual.__class__ # returns "bytes"
```

**Comment by spulec** [comment]
Thanks for opening.

We don't officially support Python 3.5 as of yet. I would be happy to accept some PRs though if anyone is interested in adding it.

**Comment by spulec** [comment]
I've updated the README. It should be good now. Let me know if there are still issues.
