### ISSUE TITLE
SNS endpoint creation

### ISSUE THREAD

**Issue by mpappas86** [spulec/moto#751]
When you attempt to create two SNS platform_endpoints with the same token in boto, it normally throws a client error the second time, telling you that the endpoint has already been created. (See http://stackoverflow.com/questions/22227262/aws-boto-sns-get-endpoint-arn-by-device-token). However moto doesn't check if there are any pre-existing platform_endpoints with your token, it just happily creates new ones, so I'm unable to test my error handling for this case using moto. Can you ensure that attempting to create a second platform_endpoint with an already used token throws a ClientError similar to boto's behavior? Thanks!

**Comment by mpappas86** [comment]
Similarly, no exception is thrown on `PlatformEndpoint.publish` calls against a disabled PlatformEndpoint - instead the message is published. Can this also throw the standard boto exception?

**Comment by spulec** [comment]
Thanks for opening this! It should be fixed now.
