### ISSUE TITLE
TypeError: 'Mock' object is not iterable

### ISSUE THREAD

**Issue by anandthati** [spulec/moto#752]
Hello,
I am using @mock_s3 decorator in my test case since I am using boto3. 
In my views code I am trying to iterate over s3 function and so I am hitting this error
TypeError: 'Mock' object is not iterable
<Mock name='mock().get_versions()' id='140001632087568'>

Anyone faced the same issue and solved it???

**Comment by nfvs** [comment]
Hard to tell what that all means without more context.

In any case that looks like a python error, not moto, since Mock is part of the python std lib.

**Comment by spulec** [comment]
Moto doesn't use Mock so I'm guessing the error is somewhere else. Feel free to reopen with more details.
