### ISSUE TITLE
Moto (still) breaks `responses` mocking in tests

### ISSUE THREAD

**Issue by estyrke** [spulec/moto#7558]
Given the following minimal test case:
```python
import pytest
import requests
import responses
from moto import mock_aws


@pytest.fixture()
def mocked_responses():
    with responses.RequestsMock() as rsps:
        yield rsps


@mock_aws
def test_moto_and_responses(mocked_responses):
    response = mocked_responses.get(
        "http://example.com/foo",
        body="{}",
        status=200,
        content_type="application/json",
    )

    resp = requests.get("http://example.com/foo")

    assert len(mocked_responses.calls) == 1
    assert resp.json() == {}
```

I expect this to work, but the passthru added by moto (in custom_responses_mock.py) makes the request go through to the real example.com instead.

I am new to `responses`, so maybe I'm using it incorrectly? Apparently I can get around it by using the responses_mock from moto.core.models but it feels like the wrong solution...

The use case here is that I want to test a larger chunk of code that both uses boto3 _and_ makes regular http(s) requests to our backend.

**Comment by estyrke** [comment]
I noticed that there are a few older issues relating to this, so I'm wondering if there has been a regression or if my code is wrong...

**Comment by bblommers** [comment]
Hi @estyrke, that happens because `moto` steals/resets the existing `responses`. The workaround is to tell `moto`: hey, I have an existing mock active, please fall back to that.

```
from moto.core.models import override_responses_real_send


@pytest.fixture()
def mocked_responses():
    with responses.RequestsMock() as rsps:
        override_responses_real_send(rsps)
        yield rsps


@mock_aws
def test_moto_and_responses(mocked_responses):
    .. as before
```

**Comment by estyrke** [comment]
Excellent! Thank you for the quick response! I assume an `override_responses_real_send(None)` should go after the yield as well?

**Comment by bblommers** [comment]
Yes, good catch @estyrke - you should indeed reset it after yield.

Happy to hear this is resolved!
