### ISSUE TITLE
Use pytest for tests, to support running all tests with multiple boto version

### ISSUE THREAD

**Issue by nfvs** [spulec/moto#756]
py.test is much more powerful to run tests, and one of the features I think would really help would be fixtures.

AFAICT currently all tests run only on one boto version; with py.test you can define a fixture with parameters, which will trigger all tests that use that fixture with all parameters.

Example
```python
@pytest.fixture(params=['boto', 'boto3'])
def boto_version(boto_param):
    if boto_param == 'boto3':
        import boto3
        return boto3
    import boto as boto_
    return boto_

def test_whatever(boto_version):
    boto_version.dynamodb_backend2.create_table('TestTable')
    ...
```

```
> python -m pytest
tests/test_dynamodb/test_dynamodb.py::test_whatever[boto] PASSED
tests/test_dynamodb/test_dynamodb.py::test_whatever[boto3] PASSED
```

It also allows much more, like skipping certain tests for certain parameters.

@spulec if you think this is worthwhile pursuing I'm happy to create a branch and modify a single set of tests (e.g. dynamodb) to use it, and then you can evaluate it for yourself.

**Comment by spulec** [comment]
My understanding is that the boto and boto3 client are not very compatible so it would take significantly more changes than that. Feel free to open a branch for dynamodb though. It does sound like a nice idea.

**Comment by spulec** [comment]
Going to close this out. Feel free to reopen if you want to discuss more.
