### ISSUE TITLE
DynamoDB update_item() does not support ADD and DELETE actions

### ISSUE THREAD

**Issue by eavrunin** [spulec/moto#766]
The action list here https://github.com/spulec/moto/blob/master/moto/dynamodb2/models.py#L113 only includes SET and REMOVE.

Mostly this fails silently (that is, the code runs but the field is not updated), but it can also raise `ValueError: need more than 1 value to unpack` from the decorator if I have an UpdateExpression like `SET set_field=:set_val ADD add_field :add_val`.

**Comment by spulec** [comment]
Sorry about the silent failure. A pull request would be very welcome if anyone has time to implement.
