### ISSUE TITLE
Modifications: Fix s3bucketpath handling for IP based requests #765

### ISSUE THREAD

**Issue by rocky4570** [spulec/moto#780]
With regards to change https://github.com/spulec/moto/pull/765.

This change causes problems when using moto (s3) on Windows machines as inet_pton is not part of the socket module. Results in AttributeError: 'module' object has no attribute 'inet_pton'

Fix is to use inet_pton but requires installing (win-inet-pton) and placing in moto/s3/responses.py:

import os
if os.name == 'nt':
    import win_inet_pton
import socket

But this isn't really a good option IMHO, as forces additional requirements to contain a library for architecture type for the 1 check being done to determine if sub-domain.

**Comment by jgelens** [comment]
Replacing the ip logic with a regex for ipv4 and ipv6 IP's would maybe work?

**Comment by spulec** [comment]
Fixed with #784
