### ISSUE TITLE
Issue in retrieving messages from SQS using boto3

### ISSUE THREAD

**Issue by varadharajan** [spulec/moto#782]
Consider the below code block.

```python
  @mock_sqs
  def test_foo(self):

    sqs = boto3.resource('sqs', 'us-east-1')
    queue_ = sqs.create_queue(QueueName="test")
    queue_.send_message(MessageBody="foobar")
    queue_.send_message(MessageBody="barfoo")

    assert len(queue_.receive_messages()) == 2
```

This test will fail with the below error in moto 0.4.30, boto3 1.4.1.

`
E     AssertionError: assert 1 == 2
`
I observed that, second call to receive_message function will retrieve the second message whereas ideally, the first call itself should retrieve both the messages. As of now, i had to do something like:

```python
  def __assert_sqs_queue_length(self, queue_name = None, count=0):
    sqs = boto3.resource('sqs', region_name='us-east-1')
    queue = sqs.create_queue(QueueName=queue_name)
    queue_length = 0
    while True:
      msgs_ = queue.receive_messages()
      if msgs_:
        queue_length+=len(msgs_)
      else:
        break
    assert queue_length == count
```

**Comment by rocky4570** [comment]
We had similar issues with Boto3. Until we looked at the doco - which has the following:

MaxNumberOfMessages (integer) --
The maximum number of messages to return. Amazon SQS never returns more messages than this value but might return fewer. Values can be from 1 to 10. Default is 1.

http://boto3.readthedocs.io/en/latest/reference/services/sqs.html#SQS.Client.receive_message. Though trying to find this passage again stumbled upon:

https://github.com/boto/boto3/issues/324

**Comment by varadharajan** [comment]
@rocky4570  Thanks a lot for that link. I was not aware of that before.
