### ISSUE TITLE
SQS DEFAULT_ACCOUNT_ID is incorrect format for SenderId

### ISSUE THREAD

**Issue by bkruger99** [spulec/moto#792]
DEFAULT_ACCOUNT_ID is an incorrect format for the SQS SenderId.  It be something alone the lines of:
AIDAIT2UOQQY3AUEKVGXU  (autoscale)
AROAIL6GAI2XEC672SWG2:awslambda_39_20161007224708400
AROAIL6GAI2XEC672SWG2:i-12345678901234567

See pull request: 
     #791

**Comment by spulec** [comment]
Fixed with #791
