### ISSUE TITLE
HTTPS requests fail when using Moto

### ISSUE THREAD

**Issue by spg** [spulec/moto#794]
Running `python mycript.py` fails. Here's `myscript.py`:
```python
import requests
from moto import mock_s3


@mock_s3
def req():
    requests.get("https://www.google.ca")


if __name__ == "__main__":
    req()
```

Here's the error from running `myscript.py`:
```shell
(sslpytesterror)➜ python myscript.py
Traceback (most recent call last):
  File "myscript.py", line 11, in <module>
    req()
  File "/Users/spg/.virtualenvs/sslpytesterror/lib/python2.7/site-packages/moto/core/models.py", line 71, in wrapper
    result = func(*args, **kwargs)
  File "myscript.py", line 7, in req
    requests.get("https://www.google.ca")
  File "/Users/spg/.virtualenvs/sslpytesterror/lib/python2.7/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/spg/.virtualenvs/sslpytesterror/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/spg/.virtualenvs/sslpytesterror/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/spg/.virtualenvs/sslpytesterror/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/Users/spg/.virtualenvs/sslpytesterror/lib/python2.7/site-packages/requests/adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))
```

Commenting out the `@mock_s3` annotation fixes the problem.

Clearly, using `mock_s3` causes problems with HTTPS calls. Is this by design?

thanks :)

**Comment by rocky4570** [comment]
Solution here if there is no fix is to use moto in the context manager form rather than decorator. 

I suspect its because moto relies on HTTPretty to capture requests from boto/boto3 api calls. Also have to ensure http_proxy is not set when using it else can get errors from HTTPretty.

def req():
    x = requests.get("https://www.google.ca")
    with mock_s3():
            s3 = boto3.resource("s3", region_name="np-santa-1")
            for buckets in s3.buckets.all():
                print s3.name
                print x.<whatever>
    x = requests.get("https://github.com/spulec/moto/issues/794")

Hope this helps.

**Comment by spulec** [comment]
Yes, unfortunately this can be the case.

Going to close this in favor of https://github.com/spulec/moto/issues/514, which starts to talk about solutions.

**Comment by alexcasalboni** [comment]
@spulec isn't #514 about Python 3 only?

Unfortunately, you can't always use context managers but you may want to use requests_mock instead:

``` Python

from moto import mock_s3
import requests
import requests_mock

@requests_mock.mock()
@mock_s3
def req(m):
    m.get('https://www.google.ca', text='<expected response>')
    r = requests.get('https://www.google.ca')
    print r.text  # prints "<expected response>"

if __name__ == "__main__":
    req()
```

**Comment by spulec** [comment]
The original problem of #514 was about python 3, yes, but the solution is to look at alternative ways forward away from HTTPretty.

**Comment by alexcasalboni** [comment]
Isn't HTTPretty supposed to mock only URLs related to AWS? Looking at the code, it seems like it maps only certain URL patterns and it shouldn't mess up with other random URLs. Is it worth documenting that any other HTTP call wrapped by moto requires explicit mocking as well?

**Comment by spulec** [comment]
Yeah, we can do that. I'm hoping to prioritize getting us away from HTTPretty shortly.

**Comment by shmuelamar** [comment]
found a solution for moto blocking all http/https requests. currently moto uses `responses` so we can add prefix to ignore (passthrough)

this worked for me:

```python
import requests
from moto import mock_s3
import responses

# need to add prefix see https://github.com/getsentry/responses/blob/master/responses.py#L528
responses.mock.add_passthru('http://www.google.ca')


@mock_s3
def req():
    requests.get('http://www.google.ca')


if __name__ == "__main__":
    req()
```

**Comment by danielsamuels** [comment]
Is there an updated version of the above? I'm trying to push some test results to an external API with a URL which looks like http://xxxxxxx-nnnnnn.eu-west-2.elb.amazonaws.com/ as part of `tearDown`, but moto/responses is capturing the request and returning a 400 (weirdly only on Jenkins, but not locally).

I've tried the following:

```python
from moto.core.models import responses_mock
responses_mock.add_passthru(self.api_url)
```

and 

```python
import responses
responses.mock.add_passthru(self.api_url)
```

but I'm still seeing the request get captured. Is there a way to wrap it in a disabling context manager, or perhaps add the passthrough some other way?

**Comment by bblommers** [comment]
Hey @danielsamuels, Moto will capture all requests to `*amazonaws.com` as a security precaution, to ensure that people don't accidentally muck with their real AWS architecture.

Can you use the context manager?
```
def tearDown():
   pass

def test_mystuff():
    with mock_s3(), mock_sts, mock_whatever():
        # only requests made in here will be captured by moto
```

**Comment by danielsamuels** [comment]
> Can you use the context manager?

Unfortunately not, we set `@mock_s3` on all test cases in conftest.py to avoid ever hitting real S3, so I can't escape it here.

**Comment by bblommers** [comment]
Sorry for the delay @danielsamuels . I can't think of a way of doing this atm. I'd suggest creating a new issue here, as a feature request to configure a passthrough for specific AWS urls.
