### ISSUE TITLE
Can't create bucket with / in it

### ISSUE THREAD

**Issue by paul-lavelle** [spulec/moto#800]
I'm trying to mock out some of my stuff and our keys are of the form /foo/bar/... and trying to create the bucket with:

        self.conn.create_bucket("/foo/bar/...)

Is this something that the api will support? The error message is OSError: [Errno 9] Bad file descriptor

**Comment by 2mf** [comment]
I really wonder if AWS really allows '/' in bucket names. I know myself from the web interface, the characters are quite limited but the actual API allows a lot more. 
On the other hand wouldn't that break the general bucket behavior ?!
e.g.:
   `this.is.a.test   --> domain:  this.is.a.test.s3.amazonaws.com` (ugly but still works)
   `this/is/a/test   --> domain:  this/is/a/test.s3.amazonaws.com` (not working)

`create_bucket` creates a bucket and not a key.

**Comment by snordhausen** [comment]
A "/" in the bucket name is not allowed, see http://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html for details.

And as already mentioned: You are creating a bucket, not a key. So just call your bucket "foobar" and create the keys (which may contain slashes) after that.

**Comment by paul-lavelle** [comment]
thanks for the quick responses. I'm new to boto/aws and was reviewing the calls. The boto calls definitely have the / in it but I must be misinterpreting what the api is actually intended to do.

**Comment by spulec** [comment]
Yup, I don't think you can start a bucket with a slash. Going to close, but feel free to reopen if I missed something.
