### ISSUE TITLE
The filter 'vpcId' for DescribeSubnets has not been implemented in Moto yet.

### ISSUE THREAD

**Issue by afgane** [spulec/moto#801]
Any chances of adding this in the near future?

**Comment by afgane** [comment]
Also getting `The filter 'state' for DescribeSubnets has not been implemented in Moto yet.`.

**Comment by spulec** [comment]
This is not a feature I currently need, but pull requests welcome if someone else has time to implement.

**Comment by afgane** [comment]
I can perhaps give it a try. Can you give a pointer what file to start with?

**Comment by spulec** [comment]
Awesome.

[This](https://github.com/spulec/moto/blob/master/moto/ec2/utils.py) should be the main file that will need changing. Look at the `filters_from_querystring` function and the `EC2_RESOURCE_TO_PREFIX` constant.

You should be able to add a new test [here](https://github.com/spulec/moto/blob/master/tests/test_ec2/test_subnets.py) to verify any changes.

**Comment by bblommers** [comment]
I imagine this wasn't quite the 'near future' you asked for, but it is now available in moto >= 1.3.16.dev123 :)
