### ISSUE TITLE
dynamodb2.models.cast_value exception with [0,1] float RangeKey query

### ISSUE THREAD

**Issue by kmshelley** [spulec/moto#812]
Hello,

I am new to moto so I apologize if this is user-error or duplicate.

I have a table with a Global Secondary Index range key of probability values (strictly between 0 and 1) defined as:

```
from boto.dynamodb2.fields import HashKey, RangeKey, GlobalAllIndex
from boto.dynamodb2.types import NUMBER
GlobalAllIndex('id-probability-index', parts=[HashKey('id'), RangeKey('probability', data_type=NUMBER)])
```

Calling query_2 for `probability__between = [0, 0.66]` returns: 
```
File "/usr/local/lib/python2.7/site-packages/moto/dynamodb2/models.py", line 59, in cast_value
    return int(self.value)
ValueError: invalid literal for int() with base 10: '0.66000000000000003108624468950438313186'
```

Looking at the code it looks like only ints are returned. Changing cast_value from:
```
def cast_value(self):
  if self.type == 'N':
    return int(self.value)
  else:
    return self.value
```
 to:
```
def cast_value(self):
  if self.type == 'N':
    if float(self.value) % 1 == 0:
      return int(self.value)
    return float(self.value)
  else:
    return self.value
```
fixed the issue for me, but I'm not sure if I'm missing something else here. I am using moto 0.4.30.

Thanks!

**Comment by spulec** [comment]
Thanks for opening.

I've pushed a fix that I think will help. Let me know if it doesn't.

**Comment by kmshelley** [comment]
Thanks, that fixed it!
