### ISSUE TITLE
mock_kinesis missing AT_TIMESTAMP shard iterator support

### ISSUE THREAD

**Issue by gregsterin** [spulec/moto#813]
https://github.com/spulec/moto/blob/fca0d3885b84ae9f4350001e74b453d3961b6d6c/moto/kinesis/utils.py

has no AT_TIMESTAMP.

However Kinesis API supports such a shard iterator:

http://docs.aws.amazon.com/kinesis/latest/APIReference/API_GetShardIterator.html

**Comment by spulec** [comment]
Noted. Pull requests welcome to add the feature if someone has time.
