### ISSUE TITLE
Support for DynamoDB Streams?

### ISSUE THREAD

**Issue by jong-eatsa** [spulec/moto#815]
I'm wondering if you have any plans to support DynamoDB Streams

**Comment by spulec** [comment]
No plans now as it isn't something I use, but pull requests are very much welcome if someone has time.

**Comment by terrycain** [comment]
@jong-eatsa if you have some example code you want to work, preferably with some example data, I'll have a look

**Comment by bblommers** [comment]
@jong-eatsa @spulec This should be implemented now!

**Comment by spulec** [comment]
Closed with #2457
