### ISSUE TITLE
Implement verify_email_address method in ses

### ISSUE THREAD

**Issue by ncknuna** [spulec/moto#818]
While the `send_email` method in ses is mocked by moto, responses come back with:

botocore.errorfactory.MessageRejected: An error occurred (MessageRejected) when calling the SendEmail operation: Email address not verified

When attempting to use the `verify_email_address` method to fix this issue, a NotImplementedError gets raised:

moto/core/responses.py:193: NotImplementedError

This makes it very difficult to test the core functionality of ses using moto.

**Comment by spulec** [comment]
Noted. Pull requests are very much welcome if anyone has time.

**Comment by terrycain** [comment]
Pretty sure this works now, its in the codebase. @JackDanger close please
