### ISSUE TITLE
Python 3 support is not reliable because of HTTPretty

### ISSUE THREAD

**Issue by oz123** [spulec/moto#820]
HTTPretty is doing stuff which is not compatible with Python 3. This means that moto will not work with Python 3 reliably.
I found a case where code which also uses ftplib from the standard library breaks with moto, and that is because of HTTPretty.
To make things short:

`httpretty.core.fakesock.socket.makefile` is broken with Python 3.

See the signature here https://github.com/gabrielfalcao/HTTPretty/blob/master/httpretty/core.py#L373
This is only Python2 compatible. In Python 3 the signature is:

`socket.makefile(mode='r', buffering=None, *, encoding=None, errors=None, newline=None)`.

This is very unfortunate, and cause the code to break.

**Comment by spulec** [comment]
Yes, that is true unfortunately. I'm not sure we have a lot of options. We can formally drop support for python 3 in moto or work to move away from HTTPretty.

**Comment by spulec** [comment]
I'm going to close this in favor of #514, but let me know if you think it is different.
