### ISSUE TITLE
Volume.availability_zone is an empty string

### ISSUE THREAD

**Issue by mylons** [spulec/moto#823]
given some code like this being called from within a function decorated by `@mock_ec2`:
```

def ec2_volumes():
    ec2 = boto3.resource('ec2')
    client = boto3.client('ec2')

    volumes = []
    op_kwargs = {'Size': 500,
                 'VolumeType': 'gp2',
                 'AvailabilityZone': 'us-west-2'}

    for i in range(2):
        ebs = client.create_volume(**op_kwargs)
        volumes.append(ec2.Volume(ebs['VolumeId']))

    for volume in volumes:
        # tag volume for easy clean up
        volume.create_tags(Tags=[{'Key': 'name', 'Value': 'zenyatta-ebs'},
                                 {'Key': 'Owner', 'Value': 'd8a'}])

    return volumes
```
I notice that `ebs['AvailabilityZone']` is an empty string. Per the boto3 docs: http://boto3.readthedocs.io/en/latest/reference/services/ec2.html#EC2.Client.create_volume it should be populated.

EDIT: upon further inspection this is a ton of work. contrary to the readme, moto is relying heavily on pre-boto3 functionality.

**Comment by spulec** [comment]
The following code works for me

```python
@mock_ec2
def test_boto3_ec2_volumes():
    ec2 = boto3.resource('ec2')
    client = boto3.client('ec2', region_name='us-west-2')

    volumes = []
    op_kwargs = {'Size': 500,
                 'VolumeType': 'gp2',
                 'AvailabilityZone': 'us-west-2a'}

    volume = client.create_volume(**op_kwargs)
    volume['AvailabilityZone'].should.equal("us-west-2a")
```

I think the case you are seeing will come up when the boto3 client is for a different region than the AZ where you are creating the volume. I'm guessing we should be raising an error instead.
