### ISSUE TITLE
Add support for AWS Cognito

### ISSUE THREAD

**Issue by whummer** [spulec/moto#842]
Hi, are there any plans to add support for AWS Cognito? http://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/
Cheers

**Comment by spulec** [comment]
Thanks for opening.

I don't have any immediate plans as this isn't a service I've used much. PRs very much welcome though if anyone else has time.

**Comment by terrycain** [comment]
@whummer if you have some example code you want to work, preferably with some example data, I'll have a look

**Comment by dmulter** [comment]
I need it too. First I'll get things working for real, then I should have code+data examples I can share to help @terrycain

**Comment by spulec** [comment]
Add initial support with #1548

Feel free to open additional issues if specific endpoints would be helpful
