### ISSUE TITLE
Support CloudFormation stack policies?

### ISSUE THREAD

**Issue by rouge8** [spulec/moto#845]
Implementing `set_stack_policy`/`get_stack_policy` to set/return the policy document would probably be straightforward, but it might cause more confusion than it's worth if moto isn't able to check/verify the policies when performing stack updates. Thoughts?

**Comment by 2rs2ts** [comment]
It's a huge undertaking to implement the logic that enforces the policy. You'd have to reverse-engineer the logic that CloudFormation uses to determine whether your update will violate the policy.

Depending on whether it's acceptable to support those methods but not support enforcing the policy, this may be something that's better taken care of by mocking your own code.

**Comment by rouge8** [comment]
Agreed 100%. I don't know if it's better to support the API calls and warn about not enforcing the policy (similar to existing warnings for some of the CloudFormation calls) or to do neither.

> this may be something that's better taken care of by mocking your own code

Can't believe I didn't think of that though 😳

**Comment by spulec** [comment]
I'm happy to have the API calls and not have them enforced (we do this in a few other places with IAM permissions). PR welcome.

Agreed that adding the underlying functionality would be quite a task...
