### ISSUE TITLE
Getting more publicity and users for Moto. 

### ISSUE THREAD

**Issue by clozinski** [spulec/moto#856]
How can we get more publicity and users for Moto?
I saw that your Awesome Python pull request
https://github.com/vinta/awesome-python/pull/805
is still open since Dec 2016. Bummer. 

So how can we get you more publicity and users?
How about a link exchange with my site?

https//Pylang.info

is the world's largest Python directory. It starts off with the Awesome Python information, and adds additional links. It lists not just libraries, but also blogs videos, articles and other interesting content. It is a much deeper and richer hierarchy than the github pages. I invite you to watch the lightening talk video on the web site.

Warm Regards 
Christopher Lozinski

**Comment by spulec** [comment]
No thank you
