### ISSUE TITLE
New flask dependency breaks moto when pip installing from git URL

### ISSUE THREAD

**Issue by 2rs2ts** [spulec/moto#862]
I specify (in a requirements file) my moto dependency with a git URL because I usually need some feature that's not in a release yet. e.g.

`git+https://github.com/2rs2ts/moto@b9ea947aa0572234051d9ba22b77b862daa3b524#egg=moto`

With the new flask dependency in `extras_require` I don't get this flask dependency automatically and my tests fail with `ImportError`s. I only use the decorators, not the standalone mode, so it's kind of a pain that I have to install flask just to get moto to work.

Maybe I am missing something, like a way to install the extras even with this git URL specifier, but if there isn't some way I'm using pip wrong then I think my (minor) complaint stands :)

**Comment by spulec** [comment]
That is my bad. With https://github.com/spulec/moto/commit/2bd4567801a733297588ec7a8167c1af5c2edd75, we should no longer be using flask outside of server mode. If you still see an error, let me know where the import is coming from.

**Comment by 2rs2ts** [comment]
Thanks, will do!
