### ISSUE TITLE
boto3 redshift not working -- JSON response

### ISSUE THREAD

**Issue by srinivas795** [spulec/moto#868]
When I try to test create redhift cluster, parameter group and subnet group with boto3, I get the following error:
ResponseParserError: Unable to parse response (not well-formed (invalid token): line 1, column 0), invalid XML received:
{"RequestId": "6876f774-7273-11e4-85dc-39e55ca848d1", "Error": {"Message": "Cluster testRedshift not found.", "Code": "ClusterNotFound", "Type": "Sender"}}

**Comment by spulec** [comment]
Thanks for opening this. Can you try again after I've pushed https://github.com/spulec/moto/commit/3cdb4afad0f6a42c790c39c56e2b6f0680d54ff7

It isn't the ideal solution, but should work for now.
