### ISSUE TITLE
moto mock s3 copy() doesnt work

### ISSUE THREAD

**Issue by leetoleetu** [spulec/moto#869]
moto version 0.4.31

@pytest.mark.unit_test
def test_copy():
    conn = boto3.client('s3', region_name="us-east-1")
    with moto.mock_s3():
        conn.create_bucket(Bucket='bucket1')
        conn.create_bucket(Bucket='bucket2')
        conn.put_object(Bucket='bucket1', Key='hello.txt', Body=b'hello world')
        conn.copy({'Bucket': 'bucket1', 'Key': 'hello.txt'}, 'bucket2', 'hello2.txt')

### ../venv/lib/python3.4/site-packages/boto3/s3/inject.py:267: in copy
    return future.result()
../venv/lib/python3.4/site-packages/s3transfer/futures.py:73: in result
    return self._coordinator.result()
../venv/lib/python3.4/site-packages/s3transfer/futures.py:233: in result
    raise self._exception
../venv/lib/python3.4/site-packages/s3transfer/tasks.py:255: in _main
    self._submit(transfer_future=transfer_future, **kwargs)
../venv/lib/python3.4/site-packages/s3transfer/copies.py:105: in _submit
    **head_object_request)
../venv/lib/python3.4/site-packages/botocore/client.py:253: in _api_call
    return self._make_api_call(operation_name, kwargs)
../venv/lib/python3.4/site-packages/botocore/client.py:530: in _make_api_call
    operation_model, request_dict)
../venv/lib/python3.4/site-packages/botocore/endpoint.py:141: in make_request
    return self._send_request(request_dict, operation_model)
../venv/lib/python3.4/site-packages/botocore/endpoint.py:168: in _send_request
    request, operation_model, attempts)
../venv/lib/python3.4/site-packages/botocore/endpoint.py:233: in _get_response
    response_dict, operation_model.output_shape)
../venv/lib/python3.4/site-packages/botocore/parsers.py:211: in parse
    parsed = self._do_parse(response, shape)
../venv/lib/python3.4/site-packages/botocore/parsers.py:612: in _do_parse
    member_shapes, final_parsed)
../venv/lib/python3.4/site-packages/botocore/parsers.py:668: in _parse_non_payload_attrs
    member_shape, headers[header_name])
../venv/lib/python3.4/site-packages/botocore/parsers.py:260: in _parse_shape
    return handler(shape, node)
../venv/lib/python3.4/site-packages/botocore/parsers.py:149: in _get_text_content
    return func(self, shape, text)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <botocore.parsers.RestXMLParser object at 0x7fe257b52978>, shape = <Shape(ContentLength)>
text = "b'\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00'"

    @_text_content
    def _handle_integer(self, shape, text):
>       return int(text)
E       ValueError: invalid literal for int() with base 10: "b'\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00'"

../venv/lib/python3.4/site-packages/botocore/parsers.py:418: ValueError

**Comment by spulec** [comment]
```python
def test_copy():
    conn = boto3.client('s3', region_name="us-east-1")
    with moto.mock_s3():
        conn.create_bucket(Bucket='bucket1')
        conn.create_bucket(Bucket='bucket2')
        conn.put_object(Bucket='bucket1', Key='hello.txt', Body=b'hello world')
        conn.copy({'Bucket': 'bucket1', 'Key': 'hello.txt'}, 'bucket2', 'hello2.txt')
```

The previous code works for me on python 3.5.2 against the `master` branch of Moto.

**Comment by leetoleetu** [comment]
Any idea why this may not be working with python 3.4? Any workarounds?

**Comment by spulec** [comment]
Were you able to get the code I posted working on python 3.5 or python 3.4?

**Comment by leetoleetu** [comment]
Was able to get the code working in 3.5 but not in 3.4

**Comment by spulec** [comment]
I just ran it on python 3.4.5 as well and it seemed to work. Can you give me more details about your environment? Exact python version, OS, a `pip freeze`, etc?

**Comment by kokon** [comment]
FYI, I run the above code, and see the same issue. My python version is 3.6.1, with moto==0.4.31.

Upgrading to moto 1.0.1 fixed the problem.

**Comment by spulec** [comment]
Okay, I'm going to assume the most recent version of moto solves this then. If someone is seeing otherwise, please let me know.
