### ISSUE TITLE
Bug: Cloudformation Template's AWS::NoValue incorrectly represented as None

### ISSUE THREAD

**Issue by Dawil** [spulec/moto#870]
In the CF/parsing file, https://github.com/spulec/moto/blob/master/moto/cloudformation/parsing.py#L308, an "AWS::NoValue" is represented with a `None`. One way in which this can manifest incorrect behavior is in the elb/models file, https://github.com/spulec/moto/blob/master/moto/elb/models.py#L118:

    policies = properties.get('Policies', [])
    port_policies = {}
    for policy in policies:

which can throw `TypeError: 'NoneType' object is not iterable` when trying to iterate on policies, if they are a python `None`. The correct behavior is that when a property is designated "AWS::NoValue" it isn't present in the `properties` object shown above. That way `.get('Policies', [])` would always return an array, instead of sometimes a `None`.

Depending on how the change is implemented this may require many changes in many places. The `_parsed_resources` object is often accessed with no exception checking occurring.

I'm able to make use of a simple work around in my case, so I haven't spent much time trying to fix it, but I thought I'd mention it in case other people needed this.

**Comment by spulec** [comment]
Thanks for opening this. It should be fixed now.
