### ISSUE TITLE
cloudtrail support

### ISSUE THREAD

**Issue by Fak3** [spulec/moto#877]
Hi, I noticed that there is no mock for [cloudtrail](http://boto3.readthedocs.io/en/latest/reference/services/cloudtrail.html) service. It would be wonderful to have one :)

**Comment by spulec** [comment]
Noted. It isn't a service I use a lot so not high on my personal list, but would be happy to accept a PR if anyone gets time.

**Comment by thehesiod** [comment]
actually it's critical if you for example use lambdas and hook them up to event sources, the only way to get the logs would be via cloudtrail I believe

**Comment by terrycain** [comment]
@Fak3 if you have some example code you want to work, preferably with some example data, I'll have a look
