### ISSUE TITLE
StartAfter not working correctly in s3.list_objects_v2

### ISSUE THREAD

**Issue by tobowers** [spulec/moto#880]
using moto 0.4.31 installed via `pip install`

The StartAfter key doesn't appear to be working when using the s3 list_objects_v2 API.

The following boto3 code will show the error when running against a moto server:
```
moto_server s3 -p 5000
```

minimal code that breaks:
```python
import boto3
s3 = boto3.client('s3',
                    endpoint_url='http://localhost:5000'
                    )

s3.create_bucket(Bucket='bob')
s3.put_object(Body="123", Bucket="bob", Key="0000")
s3.put_object(Body="123", Bucket="bob", Key="0001")
s3.put_object(Body="123", Bucket="bob", Key="0002")
s3.put_object(Body="123", Bucket="bob", Key="0003")

assert len(s3.list_objects_v2(Bucket='bob')['Contents']) == 4 # succeeds
assert len(s3.list_objects_v2(Bucket='bob', StartAfter="0002")['Contents']) == 1 #errors, returning 4
```

The server is returning all objects (ignoring the StartAfter). Same code succeeds against S3 itself.

**Comment by tobowers** [comment]
update: running this against the master branch succeeds.

**Comment by spulec** [comment]
Great, thanks for the update. I'm going to close this out then and hopefully get a new release out shortly.
