### ISSUE TITLE
missing features from awslambda mock

### ISSUE THREAD

**Issue by ajk8** [spulec/moto#883]
In the process of writing tests for some lambda function management code, I've noticed that a number of features are not implemented. Interestingly, there are no exceptions raised by `moto`. Instead, the calls are pushed through to AWS, and time out due to insufficient permissions (thank goodness!). These calls include:

* awslambda.add_permission
* awslambda.remove_permission
* awslambda.update_function_code
* awslambda.update_function_configuration

These were problematic enough for my testing that I didn't go any deeper. A quick look at the code suggests that there are other functions that would be missing as well.

Rounding out the implementation for awslambda is one thing, but the fact that some calls are caught and others are passed through to lambda proper is another. If a user has default credentials set up, they may end up making costly calls to the real service while developing tests. Any chance of a quick solution to that secondary problem?

**Comment by ajk8** [comment]
On a related note, despite the fact that it appears to be implemented in `moto`, I'm getting the same behavior from `awslambda.delete_function`.

It occurs to me that it's possible that I misinterpreted the error initially. I'm not totally sure that this is a pass-through to lambda-proper. Here's the error:

```python
ConnectionClosedError: Connection was closed before we received a valid response from endpoint URL: "https://lambda.us-east-1.amazonaws.com/2015-03-31/functions/arn%3Aaws%3Alambda%3A123456789012%3Afunction%3Abar".
```

Is there something within `moto` that could be catching that but failing to return?  Here's some potentially helpful log output:

```python
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 169.254.169.254
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 169.254.169.254
INFO:boto3.resources.action:Calling iam:create_role with {'RoleName': 'baz-foo-role', 'AssumeRolePolicyDocument': '"some": "policy"'}
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): iam.amazonaws.com
INFO:mylogger:creating lambda function: bar
INFO:boto3.resources.action:Calling iam:get_role with {u'RoleName': 'baz-foo-role'}
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): iam.amazonaws.com
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): lambda.us-east-1.amazonaws.com
INFO:mylogger:successfully created lambda function: arn:aws:lambda:123456789012:function:bar
INFO:mylogger:deleting lambda function: arn:aws:lambda:123456789012:function:bar
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): lambda.us-east-1.amazonaws.com
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (2): lambda.us-east-1.amazonaws.com
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (3): lambda.us-east-1.amazonaws.com
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (4): lambda.us-east-1.amazonaws.com
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (5): lambda.us-east-1.amazonaws.com
```

**Comment by spulec** [comment]
Yes, that is not actually going to AWS, but being stopped by Responses.

Keeping this ticket open for the feature requests. Thanks!
