### ISSUE TITLE
Need git tag for 0.4.31

### ISSUE THREAD

**Issue by JackDanger** [spulec/moto#890]
Apologies that I can't create a mergeable PR to fix this but the latest release (0.4.31) doesn't have a corresponding git tag and was therefore tough to find.

The commit for that release: 4eaf5d527ef5d619aedbc48c9e09d3364239b41d

What's needed:
```
git tag 0.4.31 4eaf5d527ef5d619aedbc48c9e09d3364239b41d
git push origin 0.4.31:0.4.31
```

**Comment by spulec** [comment]
Oops, thanks. Added.

**Comment by JackDanger** [comment]
Thanks!
