### ISSUE TITLE
Autoscaling attach_instances action has not been implemented

### ISSUE THREAD

**Issue by terminatingcode** [spulec/moto#893]
Autoscaling method attach_instances is not currently implemented.

`NotImplementedError: The attach_instances action has not been implemented`

**Comment by spulec** [comment]
Noted, thanks.

**Comment by JackDanger** [comment]
@terminatingcode Would you like to try implementing this missing action? If you make a branch and do what you can I'd be happy to help with writing the tests and finishing the feature off. It would be great to have this!

**Comment by captainkerk** [comment]
solution proposed in: https://github.com/spulec/moto/pull/1264

**Comment by JackDanger** [comment]
Fixed in #1264 thanks to @captainkerk just swooping in and fixing stuff for everybody. Way to go, @captainkerk!
