### ISSUE TITLE
Interference with other network code

### ISSUE THREAD

**Issue by luci1900** [spulec/moto#9]
I've found an interesting issue.

I've just replaced S3 locks in my program with Redis locks to reduce contention and they break on tests, because moto intercepts all sockets.

Perhaps it should only intercept sockets to amazon domains?

**Comment by cgwaldman** [comment]
Hi
I'm seeing the "moto breaks redis" problem discussed above   :(

Moto version:
from git,  commit d8d55dc Sat Jan 24 08:59:14 2015 -0500

>>> httpretty.version
u'0.8.0'

**Comment by spulec** [comment]
This is almost certainly an issue with HTTPretty. Can you narrow down a test case and open an issue there if that is true?

**Comment by cgwaldman** [comment]
I just opened https://github.com/gabrielfalcao/HTTPretty/issues/212

also noted a related issue https://github.com/gabrielfalcao/HTTPretty/issues/194  which has been untouched for 3 months

**Comment by cgwaldman** [comment]
Given that "HTTPretty monkey patches Python's socket core module", I don't think I'm going to be able to use moto.  Pity.

**Comment by JackDanger** [comment]
After finding folks choosing to avoid the use of Moto and HTTPretty due to the socket monkey-patching (and finding myself unable to do so) I decided to bypass HTTPretty just inside my Redis/Memcached clients. Here's how I did it:

```
    class BypassHTTPretty():
        def __enter__(self):
            self.reenable_later = httpretty.is_enabled()
            if httpretty.is_enabled():
                httpretty.disable()

        def __exit__(self, type, value, traceback):
            if self.reenable_later:
                httpretty.enable()

    def redis_set(key, value):
        with BypassHTTPretty():
          redis.set(key, value)
```
Also posted here: https://github.com/gabrielfalcao/HTTPretty/issues/212

**Comment by spulec** [comment]
Sorry about that. I'm working to move away from socket monkey-patching in the very near future.

Another option for the time being is to use Moto in standalone server mode: https://github.com/spulec/moto#stand-alone-server-mode
