### ISSUE TITLE
moto_server Lambda endpoint for list_functions broken

### ISSUE THREAD

**Issue by thehesiod** [spulec/moto#906]
You get a 404 because the regex is `{0}/\d{{4}}-\d{{2}}-\d{{2}}/functions/?$` which gets translated to a flask regex of `'/\\d{4}-\\d{2}-\\d{2}/functions' (4422992400)`  and botocore does the request with `/functions/`

**Comment by thehesiod** [comment]
looking more into it the lambda is the only one that has d{}, and it seems these get escaped rendering them completely broken

**Comment by spulec** [comment]
I think this is fixed in master with https://github.com/spulec/moto/commit/81836b698107debc9dffe056530820c9694c8c77, but let me know if that is not the case.
