### ISSUE TITLE
S3: PUT request should fail when no 'Content-Length' header is present, but doesn't

### ISSUE THREAD

**Issue by CianciuStyles** [spulec/moto#908]
I've discovered an inconsistency between the AWS behaviour and the moto one when trying to upload an empty file to S3 with a PUT request: as stated in http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUT.html#RESTObjectPUT-requests, the Content-Length header is required in such request, and should fail with a 411 Length Required response if not provided. This is happening if I contact the "real" AWS API using the requests Python library (which, for some reason, is not setting this header when the file is empty), but the moto mocked one just returns 200 OK.

My version of moto is 0.4.27.

**Comment by JackDanger** [comment]
@CianciuStyles I've addressed this in #924 - that branch should fix your problem!

**Comment by CianciuStyles** [comment]
Yes, I think your changes will fix the problem. Thanks @JackDanger!
