### ISSUE TITLE
Filters with wildcards do not work for image names

### ISSUE THREAD

**Issue by william-richard** [spulec/moto#910]
According to many docs, blog posts and personal experience, aws allows you to use limited regexes/wildcards in filter queries.  Specifically, http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Filtering.html#Filtering_Resources_CLI says that you can use `*` to match 0 or more characters, and `?` to match exactly one character.  moto doesn't seem to correctly replicate that behavior.

I have only tested this for EC2 image names, but I dug into the code a little to try to fix this, and it seems like moto may have the correct behavior for ec2 instance tags, but not filters for other attributes.

Here is an example test:
```
import boto3
from moto import mock_ec2

with mock_ec2():
    ec2 = boto3.resource('ec2')
    instance = ec2.create_instances(ImageId='ami-1234abcd', MinCount=1, MaxCount=1)[0]
    image = instance.create_image(Name='test-image')
    filter_result = list(ec2.images.filter(Owners=['111122223333'], Filters=[{'Name':'name', 'Values':['test*']}]))
    assert filter_result == [image]
```

I have done similar tests with boto3 which I think would pass the assertion.  I have not attempted to test this using the standalone moto server.

I installed moto using pip, and here are my versions of moto and boto:
```
boto (2.46.1)
boto3 (1.4.4)
botocore (1.5.31)
moto (0.4.31)
```

**Comment by spulec** [comment]
Thanks for opening!

This should be fixed now, but let me know if you still see any issues against `master`.
