### ISSUE TITLE
Publish new version of Moto?

### ISSUE THREAD

**Issue by JackDanger** [spulec/moto#915]
Moto is amazing and a lot has happened since the last release: https://github.com/spulec/moto/compare/4eaf5d527ef5d619aedbc48c9e09d3364239b41d...master

How about a new version release so we can use all this great new stuff? Thanks so much for your work, @spulec!

**Comment by rud-bookbites** [comment]
Just used the latest `master` version to move forward:

`pip install https://github.com/spulec/moto/archive/df84675ae67e717449f01fafe3a022eb14984e26.zip`

**Comment by srikiraju** [comment]
+1 to this. We could use a new cut of this without httpretty.

**Comment by spulec** [comment]
Thanks for the kind words.

I have some dedicated free time on Friday (long train ride) where I'm planning to get a new release cut 🤞

**Comment by spulec** [comment]
Version `1.0.0` is now available. I would appreciate any testing and feedback!

**Comment by h1f1x** [comment]
Awsome. Thank you very much!
