### ISSUE TITLE
Proposal: Add Support For Local Dynamo DB (And Possibly Other AWS Services)

### ISSUE THREAD

**Issue by kylie-a** [spulec/moto#917]
First off I'd like to thank you for creating and maintaining such a wonderfully useful library. It's made our tests run much faster and minimized side effects.

However as we are growing as an org we have also added other new tools to our workflow, one of them being Docker. We have also started using the [Localstack](https://github.com/atlassian/localstack) images which provide a local AWS environment. When running some new tests that specifically connect to these images I receive the following error:

`ConnectionError: Connection refused: POST http://localstack:4569/`

I have been able to by pass this by modifying the `dynamodb2.urls` file like so:

```
from __future__ import unicode_literals
from .responses import DynamoHandler

url_bases = [
    "https?://dynamodb.(.+).amazonaws.com",
    "https?://sts.amazonaws.com",
    "https?://localstack:(\d+)",  # This does the trick
]

url_paths = {
    "{0}/": DynamoHandler.dispatch,
}

```

This however is very specific to our implementation. So I propose adding support for local AWS resources (the Docker images I linked aren't the only ones to replicate Dynamo) via a configuration file or environment variables, whichever you think would be more maintainable. I am more than willing to do the work required to get this feature added. I believe as container tech becomes more and more commonplace more organizations will have use for something like this. My initial idea was something like this:

```
from __future__ import unicode_literals
import os
from .responses import DynamoHandler

url_bases = [
    "https?://dynamodb.(.+).amazonaws.com",
    "https?://sts.amazonaws.com",
]

# Where MOTO_DYNAMODB2_URLS is a <some delimiter> separated list of URL bases to use 
custom_urls = os.environ.get("MOTO_DYANMODB2_URLS", [])
url_bases.extend(custom_urls.split(",")

url_paths = {
    "{0}/": DynamoHandler.dispatch,
}
```
This is just an initial idea, I'm not committed to this in anyway. I feel there could be a better way to do this so it would be possible to add custom URL's for all of the AWS services that Localstack provides in one setting/config file. I'm not familiar enough with the code base to know if there is a more central location this could be achieved.

Thanks again for providing such  a useful tool.

**Comment by SectorNine50** [comment]
Random fun fact, no idea if it changes anything, but it looks like Localstack actually uses Moto in their code:

```python
def start_moto_server(key, port, name=None, backend_port=None, async=False, update_listener=None):
    cmd = '%s/bin/moto_server %s -p %s -H %s' % (LOCALSTACK_VENV_FOLDER, key,
        backend_port or port, constants.BIND_HOST)
    if not name:
        name = key
    print("Starting mock %s (port %s)..." % (name, port))
    if backend_port:
        start_proxy(port, backend_port, update_listener)
    return do_run(cmd, async)

**Comment by spulec** [comment]
In the `master` branch, we do a new thing where we try to find the service based on the request headers: https://github.com/spulec/moto/blob/03c4d9fe204264cfe1c4378835db8c149ff1f281/moto/server.py#L56-L72

My understanding is that changing the line to `if host in ["localhost", "localstack"]` would be sufficient for your use case. As you note, that isn't very generic though. If we added a setting [here](https://github.com/spulec/moto/blob/master/moto/settings.py) and then added that to the server.py, I would feel good about that.

**Comment by JackDanger** [comment]
@im-auld  what do you think about @spulec's suggestion here? It sounds like we could get this added so you wouldn't have to customize things

**Comment by spulec** [comment]
Going to close this out for now. If someone is interested in creating a PR with the suggested solution, I am open to merging.
