### ISSUE TITLE
PySpark rdd methods (collect, toLocalIterator) under moto return empty arrays

### ISSUE THREAD

**Issue by acmiyaguchi** [spulec/moto#929]
PySpark are bindings to [Spark](http://spark.apache.org/) clusters. PySpark methods that interact with RDD's on the localhost are empty until the moto context. Below is a simple method of reproducing the issue.

```
Python 2.7.13 (default, Jan 19 2017, 14:48:08) 
[GCC 6.3.0 20170118] on linux2
Type "help", "copyright", "credits" or "license" for more information.

Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /__ / .__/\_,_/_/ /_/\_\   version 2.0.1
      /_/

Using Python version 2.7.13 (default, Jan 19 2017 14:48:08)
SparkSession available as 'spark'.

>>> import moto
>>> moto.__version__
u'0.4.31'
>>> data = [{'a': 1}]
>>> spark.createDataFrame(data).collect()
[Row(a=1)]
>>> with moto.mock_s3():
...     spark.createDataFrame(data).collect()
... 
[]
```

The moto should not conflict with the rpc between python and the java process.

**Comment by spulec** [comment]
Can you try testing this against the `master` branch of Moto? My guess is that it is no longer an issue.

**Comment by acmiyaguchi** [comment]
Awesome! It's working for me now, I'm curious about the root cause of the problem though. Do you know what patch in particular solved the issue?

**Comment by spulec** [comment]
I'm not positive; there was a large refactor of the S3 code.
