### ISSUE TITLE
Ability to set last-modified of s3 keys

### ISSUE THREAD

**Issue by thehesiod** [spulec/moto#933]
with the current S3 API it's impossible to set the last-modified time of an S3 key, however this is very useful for testing.

I found a hacky way of doing this via:
```python
key = self._moto_svc._main_app.app_instances['s3'].view_functions['ResponseObject.key_response'].callback.__self__.backend.buckets[BUCKET_NAME].keys[KEY_NAME]
key.last_modified = LAST_MODIFIED
```

however it would be really useful if there was a better way to access the underlying bucket to be able to set properties like this.

**Comment by spulec** [comment]
Not a lot nicer, but you should be able to do the same thing with:

```python
key = moto.s3.models.s3_backend.buckets[BUCKET_NAME].keys[KEY_NAME]
```

I'm open to ideas on this, but would probably be against creating an entirely separate API. Any other thoughts?

**Comment by georgepsarakis** [comment]
@spulec seems straightforward. Since `FakeKey.last_modified` is public API, someone can easily change it for testing. I would suggest that you create something like a `contrib` package in the project and contributors can add there any utility functions that wrap useful operations. What do you think?

**Comment by thehesiod** [comment]
Cool. If that works feel free to close this. Would be nice to be documented.

**Comment by spulec** [comment]
Got it, I have some ideas for this going forward.

**Comment by johncalvinyoung** [comment]
@spulec any hope of getting a way to do this in standalone server mode? I'm using `moto` with a Rails app and test suite, and we're depending on last-modified logic for some tests I'd love to do in moto.

**Comment by czechnology** [comment]
FYI, in newer versions you have to use:
```py
key = moto.s3.models.s3_backends["123456789012"]["global"].buckets[BUCKET_NAME].keys[KEY_NAME]
```
