### ISSUE TITLE
S3 backend missing `DeleteMarker` support

### ISSUE THREAD

**Issue by thehesiod** [spulec/moto#936]
This touches various APIs like `list-object-versions`, `delete-object`, `copy-object` and the like.  From what I see it will require a re-architecture of the S3 backend.  It's a critical feature for versioned buckets.

**Comment by spulec** [comment]
Noted, adding as a feature request.

Thanks

**Comment by georgepsarakis** [comment]
@thehesiod just opened a pull request, any suggestions or comments are welcome.

**Comment by thehesiod** [comment]
probably the unittest should do a list-object-versions to ensure it gets back the delete markers too

**Comment by thehesiod** [comment]
cool, this will help a lot!  

btw another fix needed is this: https://github.com/thehesiod/moto/commit/4da99724b9d802dc6012b610786e424549047582#diff-547a069fa8bb15a3e30833ff94d0997aR351

IIRC list-object-versions is not filtering by prefix

If that gets fixed too I'll try moving back to moto, thanks!
