### ISSUE TITLE
cloudformation update from TemplateUrl

### ISSUE THREAD

**Issue by quagly** [spulec/moto#937]
cloudformation stack update using template url fails with 'TypeError'  Here is a test that demonstrates create template from url working but update template from url fails with TypeError.

<pre><code>
from __future__ import unicode_literals

import boto3
from moto import mock_cloudformation, mock_s3

import json
import sure  # noqa

dummy_template = {
    "AWSTemplateFormatVersion": "2010-09-09",
    "Description": "Stack 1",
    "Resources": {
        "EC2Instance1": {
            "Type": "AWS::EC2::Instance",
            "Properties": {
                "ImageId": "ami-d3adb33f",
                "KeyName": "dummy",
                "InstanceType": "t2.micro",
                "Tags": [
                    {
                        "Key": "Description",
                        "Value": "Test tag"
                    },
                    {
                        "Key": "Name",
                        "Value": "Name tag for tests"
                    }
                ]
            }
        }
    }
}

dummy_update_template = {
    "AWSTemplateFormatVersion": "2010-09-09",
    "Parameters": {
        "KeyName": {
            "Description": "Name of an existing EC2 KeyPair",
            "Type": "AWS::EC2::KeyPair::KeyName",
            "ConstraintDescription": "must be the name of an existing EC2 KeyPair."
        }
    },
    "Resources": {
        "Instance": {
            "Type": "AWS::EC2::Instance",
            "Properties": {
                "ImageId": "ami-08111162"
            }
        }
    }
}

dummy_template_json = json.dumps(dummy_template)
dummy_update_template_json = json.dumps(dummy_template)

@mock_cloudformation
@mock_s3
def test_create_stack_from_s3_url():
    s3 = boto3.client('s3')
    s3_conn = boto3.resource('s3')
    s3_conn.create_bucket(Bucket="foobar")

    s3_conn.Object(
        'foobar', 'template-key').put(Body=dummy_template_json)
    key_url = s3.generate_presigned_url(
        ClientMethod='get_object',
        Params={
            'Bucket': 'foobar',
            'Key': 'template-key'
        }
    )

    cf_conn = boto3.client('cloudformation', region_name='us-west-1')
    cf_conn.create_stack(
        StackName='stack_from_url',
        TemplateURL=key_url,
    )

    cf_conn.get_template(StackName="stack_from_url")['TemplateBody'].should.equal(dummy_template)

@mock_cloudformation
@mock_s3
def test_update_stack_from_s3_url():
    s3 = boto3.client('s3')
    s3_conn = boto3.resource('s3')
    s3_conn.create_bucket(Bucket="foobar")

    s3_conn.Object(
        'foobar', 'template-create-key').put(Body=dummy_template_json)
    create_key_url = s3.generate_presigned_url(
        ClientMethod='get_object',
        Params={
            'Bucket': 'foobar',
            'Key': 'template-create-key'
        }
    )

    cf_conn = boto3.client('cloudformation', region_name='us-west-1')
    cf_conn.create_stack(
        StackName='stack_from_url',
        TemplateURL=create_key_url,
    )

    cf_conn.get_template(StackName="stack_from_url")['TemplateBody'].should.equal(dummy_template)

    s3_conn.Object(
        'foobar', 'template-update-key').put(Body=dummy_update_template_json)
    update_key_url = s3.generate_presigned_url(
        ClientMethod='get_object',
        Params={
            'Bucket': 'foobar',
            'Key': 'template-update-key'
        }
    )

    cf_conn.update_stack(
        StackName='stack_from_url',
        TemplateURL=update_key_url,
    )
    cf_conn.get_template(StackName="stack_from_url['TemplateBody'].should.equal(dummy_update_template)
</code></pre>

**Comment by spulec** [comment]
Yes, unfortunately I don't think this is supported yet. Will add as a feature request.

**Comment by bblommers** [comment]
This was implemented with #1377, so I'll close this.
