### ISSUE TITLE
NotImplementedError: The get_login_profile action has not been implemented

### ISSUE THREAD

**Issue by Fak3** [spulec/moto#944]
Hi. I tried to mock the IAM [get_login_profiles()](http://boto.cloudhackers.com/en/latest/ref/iam.html#boto.iam.connection.IAMConnection.get_login_profiles), but got NotImplementedError

**Comment by spulec** [comment]
Thanks for opening; adding as a feature request.

**Comment by JackDanger** [comment]
This is now implemented in #1021 
Thanks for reporting this!
