### ISSUE TITLE
Mocked S3 requests are reaching AWS

### ISSUE THREAD

**Issue by tombazza** [spulec/moto#945]
When trying to run the below snippet through py.test, I am finding that files and buckets are actually being created on S3:

```python
import boto
import boto.s3.key
import moto

TEST_BUCKET_NAME = "test-bucket"

@moto.mock_s3
def test_get_url_for_externalfile():
    conn = boto.connect_s3()
    bucket = conn.create_bucket(TEST_BUCKET_NAME)
    file_contents = "This is a test string."

    item = boto.s3.key.Key(bucket)
    item.key = "demo/test.txt"
    item.set_contents_from_string(file_contents)
```

I would not expect this code to actually store a file on S3, however it appears to be creating the file with the contents from this test. This is evident in the results I am seeing from the above test:

```
E           S3CreateError: S3CreateError: 409 Conflict
E           <?xml version="1.0" encoding="UTF-8"?>
E           <Error><Code>BucketAlreadyExists</Code><Message>The requested bucket name is not available. The bucket namespace is shared by all users of the system. Please select a different name and try again.</Message><BucketName>test-bucket</BucketName><RequestId>3C777FFBF3DC3930</RequestId><HostId>ZSjq4tpIm/s//kNZh3Guj9pFRURLXukjom6K/ivUgFfZAxYKwPksF0fx2UoJNOddVJJevy9W6CM=</HostId></Error>
```

Using `boto` v2.46.1, `moto` v1.0.0 installed via pip.

**Comment by tombazza** [comment]
After performing some further investigation, it appears that the v1.0.0 release of `moto` no longer supports using the `@mock_<service>` decorator for `boto` v2. The official advice is to upgrade to `boto3`, or use the `@mock_<service>_deprecated` decorator.

From the CHANGELOG:

```
BACKWARDS INCOMPATIBLE
* The normal @mock_<service> decorators will no longer work with boto. It is suggested that you upgrade to boto3 or use the standalone-server mode. If you would still like to use boto, you must use the @mock_<service>_deprecated decorators which will be removed in a future release.
* The @mock_s3bucket_path decorator is now deprecated. Use the @mock_s3 decorator instead.
```

If you must still use `boto` v2 I would advise you to lock your version of `moto` to v0.4.31. This change was not documented in the README documentation of this repo at the time of writing.

**Comment by JackDanger** [comment]
@tombazza You're totally right. I'll try to immediately respond to incoming issues with this solution so folks can perform a one-line change and be unblocked. Apologies for not realizing this was the issue when you first posted it!
