### ISSUE TITLE
can't use responses

### ISSUE THREAD

**Issue by itajaja** [spulec/moto#948]
with v1, since moto vendors in `responses`, it's impossible to use `responses` for mocking non-aws calls. example:

```py
with _responses.RequestsMock() as rsps:
    rsps.add(rsps.GET, 'http://foo')
    with moto.mock_sns():
       requests.get('http://foo')
```

this used to work on < v1, on v1 it raises a connection refused error because basically requests is patched twice by two different modules

**Comment by spulec** [comment]
Hmmmm, sorry about that.

I can't think of a great solution for this.... any ideas?

**Comment by Brett55** [comment]
I think I've come across this as well using v1.0.1. I basically can't hit any websites that are non-aws. I get connection refused errors.

**Comment by itajaja** [comment]
I just opened a pr on responses repo: https://github.com/getsentry/responses/pull/150

since responses is vendored in, I can open a pr that applies these modification on this repo, but it'd be nice nontheless if the changes will be applied upstream
