### ISSUE TITLE
S3 Mock's error code is not 404 when a key does not exist

### ISSUE THREAD

**Issue by gordonshieh94** [spulec/moto#953]
I'm writing a unit test for a wrapper to S3. One of my tests will attempt to fetch a Key `Object` that does not exist on S3. I get an exception as expected, but the `ClientError.response['Error']['Code']` is not 404. But instead the string "NoSuchKey"

Our wrapper follows the example from here http://boto3.readthedocs.io/en/latest/guide/migrations3.html#accessing-a-bucket

![image](https://cloud.githubusercontent.com/assets/7716105/26172832/8e0a955a-3afe-11e7-87ba-0d013da0d5c3.png)

**Comment by peterbe** [comment]
For what it's worth, the `exception.response['Error']['Code']` is `'404'` if you do a `s3client.head_object(Bucket='...', Key='doesnotexist')`
But if you instead do a `s3client.get_object(Bucket='...', Key='doesnotexist')` then `exception.response['Error']['Code']` is `'NoSuchKey'`. 

Isn't moto respecting that?

**Comment by JackDanger** [comment]
@gordonshieh94 This is now fixed on Moto master. Thanks for your help!

**Comment by gordonshieh94** [comment]
Thank's for fixing this so quickly! Working as expected now.
