### ISSUE TITLE
 add_instance_groups

### ISSUE THREAD

**Issue by LitQ** [spulec/moto#956]
"The {0} action has not been implemented".format(action))
NotImplementedError: The add_instance_groups action has not been implemented
When i'm try use this method
botocore.exceptions.ClientError: An error occurred (500) when calling the AddInstanceGroups operation (reached max retries: 4): <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>

**Comment by spulec** [comment]
Thanks, adding as a feature request.

**Comment by JackDanger** [comment]
@LitQ Can you check if this is still a problem? This appears to be fixed in the latest Moto

**Comment by spulec** [comment]
Closing this out; feel free to reopen if it is still happening
