### ISSUE TITLE
Add support to Fn::ImportValue in the CloudFormation parsing

### ISSUE THREAD

**Issue by hltbra** [spulec/moto#962]
At the moment, moto supports [Ref, Fn::FindInMap, Fn::GetAtt, Fn::If, and Fn::Join](https://github.com/spulec/moto/blob/e3bff8b926aaf8a0737063fbc1a4e7bac888b0e9/moto/cloudformation/parsing.py#L105-L170).

More information on Fn::ImportValue: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-importvalue.html

**Comment by hltbra** [comment]
In order to implement this fully, moto will need to implement `Export` for Outputs (I don't think it does now, please correct me if I am wrong).

CloudFormation docs: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html

**Comment by spulec** [comment]
Added with #975
