### ISSUE TITLE
ProjectionExpression with ExpressionAttributeNames causes pop index out of range error.

### ISSUE THREAD

**Issue by byron70** [spulec/moto#966]
boto==2.45.0
boto3==1.4.4
botocore==1.5.45
moto==0.4.31

Issue:
-------------------------------------
When a ProjectionExpression and ExpressionAttributeNames are used in tandem with KeyConditionExpression, the resulting query fails due to logic within moto.dynamodb2.responses.query.  Logic requires expressions to be ordered correctly, specifying ExpressionAttributeNames causes the ordering and indexes to be incorrect and can result in IndexError `pop index out of range` or other unintended results. 

Failure occurs on this line.
[https://github.com/spulec/moto/blob/0.4.31/moto/dynamodb2/responses.py#L290](https://github.com/spulec/moto/blob/0.4.31/moto/dynamodb2/responses.py#L290) as a result of the key_map looking like this:

```<type 'list'>: [u'date', u'fail', u'id', u'date', u'percent', u'timestamp']```

The hash key index would result in 2.  This index would be used to lookup the matching expression in in line 290 above, where expressions is: 

```<type 'list'>: [u'(#n0 = :v0', u'#n1 = :v1)']```

No index 2 would exist.

Example Failure: 
-------------------------------------
```
        args = {
            'TableName': 'mytable',
            'KeyConditionExpression': (
                Key('id').eq('myid')
            ),
            'ProjectionExpression': 'id, #date, #percent, #fail, #timestamp',
            'ExpressionAttributeNames': {
                '#date': 'date',
                '#percent': 'percent',
                '#fail': 'fail',
                '#timestamp': 'timestamp'
            }
        }
        args['KeyConditionExpression'] &= Key('date').eq(123456789)
```

Workaround: 
-----------------------------------------
Expressions attributes for the hash and range keys, generated by boto look like `('#n0', 'id')` and `('#n1', 'date')`, these can be forced to the top of the key mapping list once it is sorted by prefixing ExpressionAttributeNames with `z` forcing them to the bottom of the list, so a valid index for the hash and range key are returned. 

```
        args = {
            'TableName': 'mytable',
            'KeyConditionExpression': (
                Key('id').eq('myid')
            ),
            'ProjectionExpression': 'id, #zdate, #zpercent, #zfail, #ztimestamp',
            'ExpressionAttributeNames': {
                '#zdate': 'date',
                '#zpercent': 'percent',
                '#zfail': 'fail',
                '#ztimestamp': 'timestamp'
            }
        }
        args['KeyConditionExpression'] &= Key('date').eq(123456789)
```

**Comment by terrycain** [comment]
This still an issue? Moto is now on version 1.1.22

**Comment by spulec** [comment]
Going to close; feel free to reopen if this is still happening against the latest version.
