### ISSUE TITLE
SQS client.receive_messages hangs when WaitTimeSeconds is not set

### ISSUE THREAD

**Issue by Brett55** [spulec/moto#968]
Using version 1.0.0

I've found that with SQS client, calling client.receive_message() without WaitTimeSeconds param causes the statement to hang for a 5-10 mins before returning None. If I supply any WaitTimeSeconds param such as "20" it works fine.

Seems to related to this block https://github.com/spulec/moto/blob/master/moto/sqs/models.py#L346-L352

**Comment by Brett55** [comment]
Perhaps changing linee 346 to:

`if result or (unix_time() > polling_end):`

**Comment by JackDanger** [comment]
Fixed by @Brett55 in #969

**Comment by Brett55** [comment]
@JackDanger Wanted to contact you direct but this will have to suffice, I noticed that when I upgraded to version 1.0.0 of Moto, that tests are hitting AWS direct (SQS and SNS). I confirmed this by rolling back to 0.4.31 and master branch from github. I will look into this further, but I'd imagine this is not expected

**Comment by JackDanger** [comment]
@Brett55 That's a known but under-publicized change of Moto 1.0. What you need to do is replace `@mock_sqs` with `@mock_sqs_deprecated` (and same for other service) everywhere that Boto is used. `@mock_sqs` is now only for Boto3 support.

**Comment by Brett55** [comment]
Thanks for response, okay, that makes sense. It seems that moto 0.4.31
works with both boto 2 and 3 and moto 1.0.0 you must be explicit on
@mock_sqs vs @mock_sqs_deprecated?

**Comment by JackDanger** [comment]
@Brett55 That's correct.
