### ISSUE TITLE
S3 Notification to Lambda Configuration

### ISSUE THREAD

**Issue by RAbraham** [spulec/moto#973]
Hi,
It would be great if I could use `moto` to simulate S3 notifications to an AWS Lambda. An e.g. use case is every time an object is created in S3, invoke a Lambda. My Deployment scripts have code which normally looks like this which sets up the notification configuration

```python
conf = .. my aws keys etc..
lambda_client = client(conf, 'lambda', region_name=region_name)
s3 = resource(conf, 's3', region_name=region_name)
lambda_client.add_permission(**s3_permission_params)
bucket_notification = s3.BucketNotification(bucket_name)
bucket_notification.put(
        NotificationConfiguration={'LambdaFunctionConfigurations': [
            lambda_configuration_params,
 ]})
```

Currently, is it supported that `moto` will automatically invoke the lambda if I use `mock_s3` and put an object in the in-memory s3 that `moto` creates? I searched the repo a bit but I couldn't find any. I just wanted to make sure. 

Great library btw, thanks for the contribution.

Regards,
Rajiv

**Comment by spulec** [comment]
Thanks for opening. This is not currently supported, but I will turn this issue into a feature request.

**Comment by mikegrima** [comment]
I'm actually almost done with this feature. PR coming soon.

**Comment by mikegrima** [comment]
#1516 Should address this feature gap.
