### ISSUE TITLE
Cannot mock SNS publishing

### ISSUE THREAD

**Issue by adambullmer** [spulec/moto#979]
Seems like the SNS client isn't being mocked out properly. In this stupid simple example the client is reaching out to aws to actually publish to that SNS topic.
I would expect `mock_sns` to accept whatever garbage I throw at is so long as the required parameters are passed.

The packages were all installed with pip into a virtualenv.

| Component | Version   |
|-------------|----------|
| Python         | `2.7.13`  |
| Moto            |`1.0.1`     |
| boto             | `2.47.0` |
| Boto3           | `1.4.3`   |
| botocore      | `1.4.93` |

```py
>>> from moto import mock_sns
>>> with mock_sns():
        import boto3
        sns = boto3.client('sns')
        sns.publish(TopicArn="A:VERY:BAD:ARN", Message="some random message")

---------------------------------------------------------------------------
ClientError                               Traceback (most recent call last)
<ipython-input-2-c8a650b0e815> in <module>()
      2     import boto3
      3     sns = boto3.client('sns')
----> 4     sns.publish(TopicArn="A:VERY:BAD:ARN", Message="honk")
      5

botocore/client.pyc in _api_call(self, *args, **kwargs)
    249                     "%s() only accepts keyword arguments." % py_operation_name)
    250             # The "self" in this scope is referring to the BaseClient.
--> 251             return self._make_api_call(operation_name, kwargs)
    252
    253         _api_call.__name__ = str(py_operation_name)

botocore/client.pyc in _make_api_call(self, operation_name, api_params)
    535
    536         if http.status_code >= 300:
--> 537             raise ClientError(parsed_response, operation_name)
    538         else:
    539             return parsed_response

ClientError: An error occurred (NotFound) when calling the Publish operation: Endpoint with arn A:VERY:BAD:ARN not found
```

**Comment by JackDanger** [comment]
@adambullmer For better or worse Moto acts like a very reliable implementation of AWS. So it checks the ARN to make sure it's a valid endpoint and topic. Here's an example from [the tests](https://github.com/spulec/moto/blob/master/tests/test_sns/test_publishing_boto3.py#L15-L27) that'll let you test that your publishing is reliable:

```
    conn = boto3.client('sns', region_name='us-east-1')
    created = conn.create_topic(Name="some-topic")
    topic_arn = created.get('TopicArn')
    conn.publish(TopicArn=topic_arn, Message="my message")
```

**Comment by adambullmer** [comment]
Yeah, that definitely makes it work. I was hoping for less bootstrapping in my testing. Do you know if across multiple clients the same topics will persist?
i.e.
1. test bootstrap creates a sns client and creates the topic
2. test exercises code where it also creates a sns client
3. test exercises code where it publishes to the second sns client

**Comment by JackDanger** [comment]
> Do you know if across multiple clients the same topics will persist?

The same topics will persist across clients as long as you haven't forked the Python process (i.e. Moto is in-memory and acts just like a real AWS for everything in the process).

If you take a look at [the tests I linked above](https://github.com/spulec/moto/blob/master/tests/test_sns/test_publishing_boto3.py#L15-L27) you'll see an example of two clients - the first creates an SNS topic, the second creates an SQS queue, the first then subscribes to the SQS queue and publishes to SNS.

In case it helps to understand the architecture of Moto: You can run Moto in server mode and all AWS clients will interact with it without being able to tell it's not the real AWS. It's really quite a faithful reimplementation.

**Comment by adambullmer** [comment]
Awesome! Got it working. Thanks for your help!
