### ISSUE TITLE
APIGateway update_rest_api fails with 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by dacut** [spulec/moto#982]
This snippet of code fails:

    import boto3
    from moto import mock_apigateway
    
    mock = mock_apigateway()
    mock.start()
    apigw = boto3.client("apigateway")
    rest_info = apigw.create_rest_api(name="test")
    apigw.update_rest_api(restApiId=rest_info["id"])

Results in:

    Traceback (most recent call last):
    [deletia]
      File ".../moto/core/utils.py", line 165, in __call__
        status, headers, response = result
    TypeError: 'NoneType' object is not iterable

The problematic code starts in [apigateway/responses.py, APIGatewayResponse.rest_apis_individual method](https://github.com/spulec/moto/blob/master/moto/apigateway/responses.py#L41):

    def restapis_individual(self, request, full_url, headers):
        self.setup_class(request, full_url, headers)
        function_id = self.path.replace("/restapis/", "", 1).split("/")[0]

        if self.method == 'GET':
            rest_api = self.backend.get_rest_api(function_id)
            return 200, {}, json.dumps(rest_api.to_dict())
        elif self.method == 'DELETE':
            rest_api = self.backend.delete_rest_api(function_id)
            return 200, {}, json.dumps(rest_api.to_dict())

In this case, Boto is issuing a `PATCH` request that falls through and returns None.

Fixing this fully will require additional functionality to be implemented; for now, a giant TODO and raising NotImplementedError might suffice.

**Comment by terrycain** [comment]
This still an issue?

**Comment by spulec** [comment]
I'm going to close this out; feel free to reopen with more info.
