### ISSUE TITLE
SQSResponse should only include MD5OfMessageAttributes key when there are message attributes

### ISSUE THREAD

**Issue by ingluisjimenez** [spulec/moto#993]
There was a regression introduced in https://github.com/spulec/moto/pull/919, as the `MD5OfMessageAttributes` parameter is now being included with every response, even when there are no message attributes.

What ends up happening is that in cases when there are no message attributes, the responses include a `MD5OfMessageAttributes` with the md5 hash of an empty string, which happens to be `d41d8cd98f00b204e9800998ecf8427e`, and this is not compatible with client libraries like the aws-sdk-php, which attempts to verify the hash and `null` fails to match the hash returned by moto.

Not sure if this is affecting the java/ruby sdks, and/or if they are expecting this key to be always present, but definitely it's breaking the php sdk ( we use localstack, which uses moto )

**Comment by spulec** [comment]
Fixed with #992
