### ISSUE TITLE
NotImplementedError: The create_change_set action has not been implemented

### ISSUE THREAD

**Issue by Noah-Huppert** [spulec/moto#995]
When testing code which calls `client.create_change_set` decorated with `@mock_cloudformation` a `NotImplementedError` is thrown for the `create_change_set` action.

**Comment by spulec** [comment]
Thanks for opening! I'll add this as a feature request.

There are a lot of feature requests right now though so I can't make any promises on timing.

**Comment by Noah-Huppert** [comment]
Much appreciated

**Comment by bblommers** [comment]
This has been implemented in #1389

**Comment by Noah-Huppert** [comment]
Thanks!!!
