### ISSUE TITLE
Filter dicts have not been implemented in Moto for '%s' yet for instance.group-name

### ISSUE THREAD

**Issue by Prasadchitnis26** [spulec/moto#998]
I am attempting to use the describe_instances function in boto3. I am supplying a filter that returns a string, and am receiving the following message:

NotImplementedError: (u"Filter dicts have not been implemented in Moto for '%s' yet. Feel free to open an issue at https://github.com/spulec/moto/issues", u'instance.group-name')

So I am opening an issue.Thank you for your help.

**Comment by spulec** [comment]
Thanks for opening! I'll add this as a feature request.

There are a lot of feature requests right now though so I can't make any promises on timing.

**Comment by bblommers** [comment]
This was fixed by #1083, so I'll close this
